### ISSUE TITLE
About Json RPC Plugin API

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#1001]
1. Replace `ExecutablePlugin.cs` and `PythonPlugin.cs` with one `JsonRPCPlugin.cs`. 
2. Move `python.exe` from `PythonPlugin.cs` to `plugin.json` e.g. `python.exe plugin.py`
3. Make `query` for Json RPC Plugin an object instead of string
4. On `wpm install` check availability of plugin language and hide plugin or show warning text e.g.: **"This plugin requires python\node\php\etc"**
5. Add to Json RPC Plugin key modifiers for items

I think not hard to make this. 😄

After making this we can develop plugins on any language and we can develop really rich json rpc plugins rather than current nonsense

_Sorry for my english_

**Comment by lances101** [comment]
This would follow the same approach that Alfred uses. C# plugins would stay as they are but executable plugins will not depend on a specific language or tech. I like this a lot.
