### ISSUE TITLE
希望wox新增功能

### ISSUE THREAD

**Issue by LightSofa** [Wox-launcher/Wox#1007]
希望wox新增——根据功能的描述 来搜索软件的功能。

就像我们常用的搜索引擎那样，举个例子: 假如你使用google搜索——“图片编辑”，那么google会向你返回一些拥有“图片编辑”这种功能的应用程序的URI。

我希望wox增加一种与之类似功能，它也能通过 功能描述 搜索与之对应的应用程序，不同之处在于它的搜索范围是本机或局域网内的应用程序。

**Comment by qianlifeng** [comment]
太模糊了, 恐怕暂时做不到
