### ISSUE TITLE
[Plugin.WebSearch] Search engines icons reset to default randomly

### ISSUE THREAD

**Issue by Sobak** [Wox-launcher/Wox#1008]
Sadly, I didn't manage to reproduce it (yet?), but it happened to me twice in last three days that icons set for search engines in the plugin are resetting to plugin's main icon (this magnifying glass).

I'm pretty sure that on the fresh install engines have their respective icons. Then it got lost, maybe because of changing keywords for many of engines. But next day I set everything up again and it didn't survive long (btw: no restart in this time, I hibernated my computer). No manual cache or config cleaning, too.

**Comment by bao-qian** [comment]
don't worry, it has been reset to default because it encounter some unrecoverable exception, if it won't happen continuously just ignore it
