### ISSUE TITLE
在win8.1上运行失败

### ISSUE THREAD

**Issue by YangKeao** [Wox-launcher/Wox#101]
## Exception

```
System.UnauthorizedAccessException: 对路径“C:\Program Files (x86)\wox\Config”的访问被拒绝。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void WinIOError(Int32, System.String)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, DirectorySecurity dirSecurity)
   在 System.IO.Directory.CreateDirectory(String path, DirectorySecurity directorySecurity)
   在 Wox.Infrastructure.Storage.BaseStorage`1.Load() 位置 c:\Projects\Wox\Wox.Infrastructure\Storage\BaseStorage.cs:行号 48
   在 Wox.Infrastructure.Storage.BaseStorage`1.get_Instance() 位置 c:\Projects\Wox\Wox.Infrastructure\Storage\BaseStorage.cs:行号 31
   在 Wox.MainWindow..ctor() 位置 c:\Projects\Wox\Wox\MainWindow.xaml.cs:行号 117
   在 Wox.App.OnStartup(StartupEventArgs e) 位置 c:\Projects\Wox\Wox\App.xaml.cs:行号 101
   在 System.Windows.Application.<.ctor>b__0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Program Files (x86)\wox\Wox.exe" 
- Exception Handle: System.Windows.Application.DispatcherUnhandledException
- Timestamp: 2014-07-07T11:43:55.2831309+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.2.9200.0
- CLR Version: 2.0.50727.7905
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.5.51641
  - v4 Full 4.5.51641
  - v4.0 Client 4.0.0.0
  - v4.5.1 installed with Windows 8.1
## Assemblies - Wox.exe
- Wox, Version=1.0.0.145, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\wox\Wox.exe)
- log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a (C:\Program Files (x86)\wox\log4net.dll)
- Wox.Plugin, Version=1.0.0.145, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\wox\Wox.Plugin.dll)
- Wox.Infrastructure, Version=1.0.0.145, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\wox\Wox.Infrastructure.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Program Files (x86)\wox\WindowsInput.dll)
- NHotkey, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\wox\NHotkey.dll)
- Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Program Files (x86)\wox\Newtonsoft.Json.dll)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\Microsoft.VisualBasic\8.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.resources\2.0.0.0_zh-CHS_b77a5c561934e089\System.resources.dll)
- PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_64\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
- PresentationFramework.resources, Version=3.0.0.0, Culture=zh-CHS, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll)
- PresentationFramework.Aero, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.Aero\3.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)
- mscorlib.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
## Modules - Wox
- C:\Program Files (x86)\wox\Wox.exe (Wox, 1.0.0.145, Wox, 1.0.0.145, ), 0x0000000000A20000
- C:\Windows\SYSTEM32\ntdll.dll (NT 层 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAABEC0000
- C:\Windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFA998B0000
- C:\Windows\system32\KERNEL32.dll (Windows NT 基本 API 客户端 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA98E0000
- C:\Windows\system32\KERNELBASE.dll (Windows NT 基本 API 客户端 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9310000
- C:\Program Files (x86)\MacType\MacType64.dll (The Ultimate Font Rasterizer, 1, 2012, 1022, 0, The Ultimate Font Rasterizer, 1, 2012, 1022, 0, 2ch & THEMEX), 0x0000000180000000
- C:\Windows\system32\USER32.dll (多用户 Windows 用户 API 客户端 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9B60000
- C:\Windows\system32\GDI32.dll (GDI Client DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9FB0000
- C:\Windows\system32\ADVAPI32.dll (高级 Windows 32 基本 API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAAB8B0000
- C:\Program Files (x86)\MacType\EasyHK64.dll (, , , , ), 0x00007FFAA49B0000
- C:\Windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 7.0.9600.16384, Microsoft Corporation), 0x00007FFAAA100000
- C:\Windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAAB9F0000
- C:\Windows\system32\RPCRT4.dll (远程过程调用运行时, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAABD20000
- C:\Windows\system32\PSAPI.DLL (Process Status Helper, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAAA430000
- C:\Windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAABA50000
- C:\Windows\system32\MSCTF.dll (MSCTF 服务器 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9A20000
- C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.33440 built by: FX45W81RTMREL, Microsoft® .NET Framework, 4.0.30319.33440, Microsoft Corporation), 0x00007FFA97F80000
- C:\Windows\system32\SHLWAPI.dll (外壳简易实用工具库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00000000010C0000
- C:\Windows\SYSTEM32\combase.dll (用于 Windows 的 Microsoft COM, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAABA90000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA8A030000
- C:\Windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.8428_none_88dcdb0b2fb19957\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.8428, Microsoft® Visual Studio® 2005, 8.00.50727.8428, Microsoft Corporation), 0x00000000506F0000
- C:\Windows\system32\shell32.dll (Windows 外壳公用 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAAA440000
- C:\Windows\SYSTEM32\SHCORE.dll (SHCORE, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA7B30000
- C:\Windows\SYSTEM32\profapi.dll (User Profile Basic API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9240000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\mscorlib\754b97958c657ea98c1bcb5106dd3505\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA80EC0000
- C:\Windows\system32\ole32.dll (用于 Windows 的 Microsoft OLE, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9760000
- C:\Windows\SYSTEM32\kernel.appcore.dll (AppModel API Host, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA80C0000
- C:\Windows\SYSTEM32\CRYPTBASE.dll (Base cryptographic API DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA9110000
- C:\Windows\SYSTEM32\bcryptPrimitives.dll (Windows Cryptographic Primitives Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA90B0000
- C:\Windows\system32\uxtheme.dll (Microsoft UxTheme 库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA7F40000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA96820000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System\1ed3e622c2a3a1a24d12778941b00e6f\System.ni.dll (.NET Framework, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA80490000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\7c2b49dfa41d3d76f45d3200c3eefb6a\System.Drawing.ni.dll (.NET Framework, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA96B50000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\e3644fa62c6a46f60a51250ed934f666\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA7F3F0000
- C:\Windows\assembly\GAC_MSIL\Microsoft.VisualBasic\8.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll (Visual Basic Runtime Library, 8.0.50727.7905 (win9rel.050727-7900), Microsoft® Visual Studio® 2005, 8.0.50727.7905, Microsoft Corporation), 0x0000000002990000
- C:\Windows\SYSTEM32\VERSION.dll (Version Checking and File Installation Libraries, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA6720000
- C:\Windows\system32\dwmapi.dll (Microsoft 桌面窗口管理器 API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA7950000
- C:\Windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x0000000002DA0000
- C:\Windows\system32\ws2_32.dll (Windows Socket 2.0 32 位 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAABE60000
- C:\Windows\system32\NSI.dll (NSI User-mode interface DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAAB9C0000
- C:\Windows\system32\mswsock.dll (Microsoft Windows Sockets 2.0 服务提供程序, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA8960000
- C:\Windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll (System.Configuration.dll, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x000000001B940000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Xml\af723dca77b184472744a83b2d1846b8\System.Xml.ni.dll (.NET Framework, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FFA7ED40000
- C:\Windows\assembly\GAC_MSIL\System.resources\2.0.0.0_zh-CHS_b77a5c561934e089\System.resources.dll (.NET Framework, 2.0.50727.7905 (win9rel.050727-7900), Microsoft(R) .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x000000001BC60000
- C:\Windows\SYSTEM32\CRYPTSP.dll (Cryptographic Service Provider API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA8BF0000
- C:\Windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA8710000
- C:\Windows\SYSTEM32\bcrypt.dll (Windows 加密基元库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA8D30000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\be099a40bfd129bf179f15a344a4df91\WindowsBase.ni.dll (WindowsBase.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FFA8C670000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\75fbee3757fd47ce19d2bb9737f0021c\PresentationCore.ni.dll (PresentationCore.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FFA7DD70000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\731f38398f474237196ac723e65785c0\PresentationFramework.ni.dll (PresentationFramework.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FFA7CB10000
- C:\Windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll (wpfgfx_v0300.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00000000504B0000
- C:\Windows\system32\OLEAUT32.dll (, 6.3.9600.16384, , 6.3.9600.16384, Microsoft Corporation), 0x000000001C0F0000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\System.Core\59ae0a68a5da38112da36468b4245c43\System.Core.ni.dll (.NET Framework, 3.5.30729.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.5.30729.7903, Microsoft Corporation), 0x00007FFA94750000
- C:\Program Files (x86)\wox\log4net.dll (Apache log4net for .NET Framework 2.0, 1.2.13.0, log4net, 1.2, The Apache Software Foundation), 0x000000001C1B0000
- C:\Program Files (x86)\wox\Wox.Plugin.dll (Wox.Plugin, 1.0.0.145, Wox.Plugin, 1.0.0.145, ), 0x0000000002E10000
- C:\Program Files (x86)\wox\Wox.Infrastructure.dll (Wox.Infrastructure, 1.0.0.145, Wox.Infrastructure, 1.0.0.145, ), 0x000000001C260000
- C:\Program Files (x86)\wox\WindowsInput.dll (WindowsInput, 1.0.4.0, WindowsInput, 1.0.4.0, michaelnoonan), 0x000000001C3E0000
- C:\Program Files (x86)\wox\NHotkey.dll (NHotkey, 1.1.0.0, NHotkey, 1.1.0.0, ), 0x000000001C400000
- C:\Windows\SYSTEM32\urlmon.dll (Win32 的 OLE32 扩展, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FFAA17A0000
- C:\Windows\SYSTEM32\iertutil.dll (Internet Explorer 的运行时实用程序, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FFAA14F0000
- C:\Windows\SYSTEM32\WININET.dll (Win32 的 Internet 扩展, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FFAA12A0000
- C:\Windows\SYSTEM32\WindowsCodecs.dll (Microsoft Windows Codecs Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA6FA0000
- C:\Windows\SYSTEM32\mscms.dll (Microsoft 颜色匹配系统 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA67E0000
- C:\Windows\SYSTEM32\USERENV.dll (Userenv, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA8830000
- C:\Windows\SYSTEM32\WindowsCodecsExt.dll (Microsoft Windows Codecs Extended Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFAA4190000
- C:\Windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll (PresentationFramework.Classic.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x000000001C6A0000
- C:\Windows\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll (PresentationFramework.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft(R) .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x000000001C700000
- C:\Windows\SYSTEM32\d3d9.dll (Direct3D 9 Runtime, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FFA90100000
- C:\Windows\SYSTEM32\nvd3dumx.dll (NVIDIA WDDM D3D Driver, Version 335.23 , 9.18.13.3523, NVIDIA Windows WDDM D3D driver, 9.18.13.3523, NVIDIA Corporation), 0x00007FFA7BA20000
- C:\Windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\bfc2e49c22535d14d2888115892ad4f7\PresentationFramework.Aero.ni.dll (PresentationFramework.Aero.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FFA9C2D0000
- C:\Program Files (x86)\wox\Newtonsoft.Json.dll (Json.NET .NET 3.5, 5.0.8.16617, Json.NET, 5.0.8.16617, Newtonsoft), 0x000000001C8B0000
- C:\Windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_zh-CHS_b77a5c561934e089\mscorlib.resources.dll (Microsoft 公共语言运行时类库, 2.0.50727.7905 (win9rel.050727-7900), Microsoft(R) .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x000000001C990000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.7905 (win9rel.050727-7900), Microsoft® Visual Studio® 2005, 8.0.50727.7905, Microsoft Corporation), 0x00007FFA9A300000
## Threads - 9
- 6952, Running Normal, Started: 2014/7/7 星期一 11:43:44, StartAddress: 0x0000000000000000
- 6468, Wait Normal, Started: 2014/7/7 星期一 11:43:44, StartAddress: 0x00007FFAABF36490
- 7948, Wait Highest, Started: 2014/7/7 星期一 11:43:44, StartAddress: 0x00007FFAABF36490
- 7808, Wait Normal, Started: 2014/7/7 星期一 11:43:49, StartAddress: 0x00007FFAABF36490
- 4108, Wait Normal, Started: 2014/7/7 星期一 11:43:49, StartAddress: 0x00007FFAABF36490
- 3816, Wait Normal, Started: 2014/7/7 星期一 11:43:49, StartAddress: 0x00007FFAABF36490
- 6112, Wait Normal, Started: 2014/7/7 星期一 11:43:49, StartAddress: 0x00007FFAABF36490
- 5892, Wait Normal, Started: 2014/7/7 星期一 11:43:52, StartAddress: 0x00007FFAABF36490
- 2548, Wait Normal, Started: 2014/7/7 星期一 11:43:53, StartAddress: 0x00007FFAABF36490

**Comment by orzFly** [comment]
不要放在 Program Files，或者你自己给权限。

这不是我们的问题，这是 Windows 的设计问题。

**Comment by FelixHuoEZ** [comment]
It occurs to me the same problem when I edit the actionkeyword in the plugin - Websearch. I wonder to know how to fix it.
I put Wox in my user directory in my PC.

**Comment by bao-qian** [comment]
@saccohuo please open a new issue.
