### ISSUE TITLE
Replace Win+R doesn't override default Run window

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#1010]
1. Wox version / commit number:  **1.3.183**
2. Steps to **reproduce** the bug:
   - Enable "Replace Win+R" in Shell plugin
   - Press "Win+R"
3. Windows version:  **10.0.14393**
4. Exception: **None**
5. **whole** log file: 
   [2016-10-10.txt](https://github.com/Wox-launcher/Wox/files/519587/2016-10-10.txt

I've enabled the option to replace Win+R with Wox, however when I pressWin+R I get both windows open (Wox with `>` sign and the default Run window) and the default Run window overrides Wox, so that any commands I enter end up there instead of Wox

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/x48xfu93b8jq2fir/artifacts/Releases%2FWox-1.3.297.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by eugenesvk** [comment]
Unfortunately this doesn't work.
Also this update removed my customized theme (though the usual update seems to retain it).
UPD: Removed a reference to another error as it disappeared after I've restored my custom theme

**Comment by HA3IK** [comment]
@eugenesvk I've had this problem. I disabled this feature, then turned back, and call "Restart Wox". After such manipulations, all working well

**Comment by eugenesvk** [comment]
After upgrading Win10 to the latest  preview version it's now working
Or maybe it was just following @HA3IK advice that did the trick :), although I think I've done it right installing the newer Wox build
Thank you!

**Comment by eugenesvk** [comment]
Nope, it's still half-broken :(
After a boot it wasn't working (both default window and Wox window would pop up), then after disabling/enabling it was still broken, and only a restart of the Wox (had to manually kill the process as it wouldn't exit completely on its own) made it work again.
Not sure what exactly is wrong, but somehow it's not always overriding the default window

**Comment by lances101** [comment]
Main problem now is that hotkey bindings are inconsistent with issues like this one popping up on different machines. Hotkeys are planned for a rework (#459).

**Comment by bao-qian** [comment]
duplicate #802 
reopen if you can find a **stable** way to reproduce it.
