### ISSUE TITLE
[GetWox] Plugin like boosting

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#1011]
This is not really a functional issue, but it is unintended behaviour. 

@happlebao 
The plugin section at [GetWox](http://www.getwox.com/plugin) is being "boosted" by somebody. Apparently the backend has either a hole or somebody is just registering accounts like crazy. Please check the server.

**Comment by bao-qian** [comment]
i'm too busy recently, do you want to take a look?
send me your email address and your private key.

**Comment by lances101** [comment]
Sure. I suppose it's a ssh? [Grab it here](http://boromak.com/storage/lances101.pub)
[Email me here](mailto:b.makogonyuk@alumnos.upm.es)

**Comment by bao-qian** [comment]
email sent

**Comment by bao-qian** [comment]
Do you have the permission to manage issue? eg close

**Comment by lances101** [comment]
Nope. I have no permissions on the main repo (this one).

**Comment by lances101** [comment]
Also, I did not get your email. Maybe my uni's email server denied it or something. Could you please try with [my main one? (clickable)](mailto:boris.makogonyuk@gmail.com)

**Comment by bao-qian** [comment]
you have the permission for this repo and website repo now, right?

**Comment by lances101** [comment]
yes I do

**Comment by bao-qian** [comment]
fixed
the database has been hacked with 50k fake users using email ended with `*inbound*`.
those data generated on 2016/10/4, 2016/10/5, 2016/11/21, 2016/12/5.
all those user and their like has been deletes.

although I don't have idea why the database has been hacked though.

**Comment by bao-qian** [comment]
hope following rules help

``` ufw
➜  wox git:(master) ✗ ufw status
Status: active

To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
```

**Comment by bao-qian** [comment]
happen again
![image](https://cloud.githubusercontent.com/assets/1169912/24336435/33d662f2-1287-11e7-9cdc-2ae791e94dca.png)

**Comment by bao-qian** [comment]
``` sql
wox=# delete from plugins_plugin_liked_users p using auth_user a where a.id=p.us er_id and a.email like '%inbound%';
DELETE 60
wox=# delete from auth_user where email like '%inbound%';
DELETE 70
```

``` python
for p in Plugin.objects.all():
    p.refresh_from_db()
```

**Comment by germanoeich** [comment]
Correct me if I am wrong, but just deleting them won't help, as they will come back. Were those users added manually on the DB?

**Comment by bao-qian** [comment]
@germanoeich 

>  but just deleting them won't help, as they will come back.

partially true, they will come back, so I also add a temp fix for email blacklist https://github.com/Wox-launcher/Website/commit/5bcdcc2eb695c90618d749d7be7df1c2373ad79a

> Were those users added manually on the DB?

I don't know. the website is not written by myself and it is slow and ...
first I thought the server has been compromised, so I enable the firewall. then they come back, so I add a tmp fix for email blacklist.
