### ISSUE TITLE
can't edit existing web search plugin item

### ISSUE THREAD

**Issue by Morriz** [Wox-launcher/Wox#1018]
try to edit an existing plugin by editing the URL, then save...it gives error:

`New Action Keywords have been assigned to another plugin, please assign other new action keyword`

But if I first delete the item and then add it all goes well.

Using Windows 10 Home edition with latest updates

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by bao-qian** [comment]
reopen if you still have issue

**Comment by jacksonriley** [comment]
Hi, I get this same issue after updating to 1.3.524 - keywords that I had added for web search don't work anymore, and I can't edit them or create new ones with the same name.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
