### ISSUE TITLE
Hello this is a bug that I meet with wox

### ISSUE THREAD

**Issue by tedcampa** [Wox-launcher/Wox#1019]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 10/15/2016 08:28:24
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
Une tâche a été annulée.
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() dans c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:ligne 69
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Wox.Core.Updater.<UpdateApp>d__0.MoveNext() dans C:\projects\wox\Wox.Core\Updater.cs:ligne 56
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-10-15.txt](https://github.com/Wox-launcher/Wox/files/530800/2016-10-15.txt)

**Comment by lances101** [comment]
If you are still having issues, [please try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by bao-qian** [comment]
set http proxy in wox setting
