### ISSUE TITLE
Wox errors

### ISSUE THREAD

**Issue by idawnlight** [Wox-launcher/Wox#1020]
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：随便瞎点滚滚鼠标然后就迷之崩了
3. Windows 版本：Microsoft Windows NT 10.0.14393.0
4. Exception：
   PresentationFramework
   System.InvalidOperationException
   只能在按下主鼠标按钮时调用 DragMove。
   在 System.Windows.Window.DragMove()
   在 Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 109
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   [2016-10-15.txt](https://github.com/Wox-launcher/Wox/files/531097/2016-10-15.txt)
6. 截图 （可选）：
   ![qq 20161015191120](https://cloud.githubusercontent.com/assets/18070833/19409660/6c182386-930b-11e6-8293-912ac94fe289.png)

**Comment by jhdxr** [comment]
duplicate of #811
