### ISSUE TITLE
wrong result when calculating large numbers

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#1022]
Try search existing issues before you open new one
1. Wox version / commit number:  1.3.231
2. Steps to **reproduce** the bug: 
   `Alt + space`
   input `1476716883801-1476716304118`
   wox tells me the result is 0, which is absolutely wrong. 
3. Windows version: win10 x64 10586

**Comment by lances101** [comment]
Hey there @jhdxr. We are using [YAMP (repo link)](https://github.com/FlorianRappl/YAMP) to parse and output math results. I just ran a small snippet and it indeed seems like it does not accept numbers of that size. This is not a "bug" per say just a limitation. 

As of "right now" there are no hotfixes for it. There are two ways of solving this issue:
- taking matters into our own hands and making a pull request with a fix to YAML
- switching to a different math parsing library 

I am open to proposals.

**Comment by jhdxr** [comment]
thx @lances101 , I reported this as a bug because this plugin tells me the result instead of saying the number is out of range.

**Comment by lances101** [comment]
Yea.. That's because YAMP returns 0 instead of throwing an exception :( If YAMP was throwing an error we would display something in that regard.

**Comment by FlorianRappl** [comment]
My recommendation would be to switch from YAMP to [MAGES](https://github.com/FlorianRappl/Mages). It is faster, has more features, and works in the given scenario. It also should be fairly easy to integrate / support.

**Comment by lances101** [comment]
@FlorianRappl  great, I will try to make a PR tomorrow. Most likely will merge on Sunday.

**Comment by FlorianRappl** [comment]
Perfect @lances101! Also great project you have there 👍

**Comment by wasikuss** [comment]
I already tested MAGES. Works great, but validation regex needs update and what about matrices? Do we need to add or remove handling matrices? I will create PR after that.

**Comment by FlorianRappl** [comment]
Matrices work pretty much the same as in YAMP except that logical subscripting was removed. That may not matter to you or most people as logical subscripting is usually not used very often (unless you are a MATLAB pro and appreciate its power).

**Comment by wasikuss** [comment]
But we should allow to use as many features from MAGES (object creating, type casting) or stay with simple logic (for ex. arithmetic and logic without custom objects and functions)?

I discovered that it would be better to remove the validation of query and add default activation keyword. It will unleash full power of MAGES, but won't have performance issues as in interpreting all queries without activation keyword.

**Comment by FlorianRappl** [comment]
Depends on your use case. I would just include the core that is available via NuGet. It contains a useful set of standard functions and everything to get going. If you are willing / cool ;p you can create (i.e., expose) a static class or object that allows accessing the launcher API; that way you could script things in the launcher. But maybe that is too far fetched.

**Comment by wasikuss** [comment]
It's only calc :P I would rather stick to math expressions. BTW: Core package allows to creation of objects and functions ;) So what about action keyword and removing regexes? They're quite buggy allowing query like `({[1+1)}]` to run (due to bracket "counting" not "pairing"), and also not allowing more complex but valid queries to run. And error checking would help to fix invalid query ( result based on exception text from MAGES ).

**Comment by Announcement** [comment]
Do you mean like typing `mages` pressing enter, and then getting a mages only prompt? that wouldn't be so bad i suppose.

There are much better, more elegant solutions to handle these kind of problems but I'm not familiar enough to suggest such a non-trivial method such as a waterfall of sort.

**Comment by wasikuss** [comment]
yes, action keyword, mayby `calc`?. It would prevent from calling buggy regexes and allow to use more complex queries. I will do PR tomorrow.
