### ISSUE TITLE
如何让wox打开的cmd具有管理员权限？

### ISSUE THREAD

**Issue by zhizunbao84** [Wox-launcher/Wox#1023]
我的电脑是win7 专业版64位，我已经设置c盘system32里面的cmd.exe默认具有管理员权限
但是我从wox里面启动的cmd却还是没有管理员权限。
怎么设置啊？

**Comment by jhdxr** [comment]
从wox启动的cmd权限是继承wox的。因此你需要以管理员启动wox

**Comment by bao-qian** [comment]
右键 / ctrl+o / shift+enter
![image](https://cloud.githubusercontent.com/assets/1169912/20737029/367c10c4-b6a2-11e6-8bf7-fcb289542468.png)
