### ISSUE TITLE
Wox开机启动时报错

### ISSUE THREAD

**Issue by ReiujiUtsuho** [Wox-launcher/Wox#1026]
日志文件：
[2016-10-23.txt](https://github.com/Wox-launcher/Wox/files/546379/2016-10-23.txt)

异常信息：
Wox version: 1.3.202
OS Version: Microsoft Windows NT 6.3.9600.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\Xiaohei\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/23/2016 21:54:30
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 58
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jhdxr** [comment]
参见 https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183 的known issue

> System.Threading.Tasks.TaskCanceledException: 设置 http 代理

写的这么简略其实我并没有看懂。。。是因为设置了代理导致的异常么？（因为特地用中文写的，所以我才是科学上网会导致的问题？

**Comment by bao-qian** [comment]
自动更新偷懒是直接放在 github 上的
github 被干了
所以没挂代理就会有问题
