### ISSUE TITLE
关于第一次使用Wox就遇到的糟心bug

### ISSUE THREAD

**Issue by neederhow** [Wox-launcher/Wox#1027]
//Wox 版本 ：1.3.183
//Windows 版本：win10 专业版 版本 1607（OS内部版本 14399.321）
//Exception：
1.win+R调用CMD插件后，再次使用 win+R 或 alt+空格 热键不会显示输入框，屏幕中间出现一条黑色竖线，需重启程序
2.输入 Settings 没有结果，无法进入设置，只能通知栏右键进入
3.无法调用everything，甚至添加在 文件夹 插件里的文件夹也搜索不到
//不会发截图_(:з」∠)_

**Comment by Ghostish** [comment]
我也遇到一样的问题

**Comment by bao-qian** [comment]
1. 黑线是 bug ：#875
2. 删除 %APPDATA%\Wox 来重置（记得备份）
3. 这个要单独装 everything，release 里面有给 everything 的下载链接

**Comment by rangersmalljump** [comment]
我之前是只要搜索一次，下次搜索就会出现黑线我设置一下 勾选开机启动  启动时不显示主窗口 失去焦点时自动隐藏 之后问题就解决了

**Comment by bao-qian** [comment]
@rangersmalljump 
试一下新 build https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735
如果还有问题，请在 #875 讨论
