### ISSUE TITLE
Set topmost is not working

### ISSUE THREAD

**Issue by heyflorin** [Wox-launcher/Wox#1028]
When setting the topmost for a query, it does not work. I get a "Succeed" notification but it doesn't actually make it the top result when querying again. 
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: Hold shift when running query to Set Topmost Item
3. Windows version: 10.0.10586
4. Log File: Attached

[2016-10-27.txt](https://github.com/Wox-launcher/Wox/files/556508/2016-10-27.txt)

**Comment by bao-qian** [comment]
known issue
#315
just type more times...
