### ISSUE TITLE
Windows 10 UWP apps don't show up

### ISSUE THREAD

**Issue by marcinjahn** [Wox-launcher/Wox#1031]
Wox doesn't support Windows 10 UWP apps - they don't show up in the results. For example, if I type "Groove music" I don't see Groove app. Is it going to be fixed?

**Comment by lances101** [comment]
[Support for that comes in later builds that have not been released yet.](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

I am busy with work right now. But I hope this weekend I will be able to spend time on this.

**Comment by marcinjahn** [comment]
It works with this new build - great.
BTW, I have a few observations on the things that could be added/improved with Wox - should I post them all in one post, or should I create new post for each? It would be around 3-4 suggestions.

**Comment by lances101** [comment]
Well, please check first the existing tickets. Maybe your suggestion has been made before. But yes, usually you would create as four different posts.
