### ISSUE TITLE
Disabling start wox on system startup does nothing - still starts up on login 

### ISSUE THREAD

**Issue by sguergachi** [Wox-launcher/Wox#1032]
This happens in Windows 10 latest.

**Comment by bao-qian** [comment]
then disable it from task manager

**Comment by sguergachi** [comment]
So the check box is a lie? Does it do anything? Why is it even there if I have to disable it on a system level...

**Comment by bao-qian** [comment]
It **should** disable it, I'd appreciate it if you can fix it

**Comment by happlebao** [comment]
duplicate #1016 
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.321/artifacts
