### ISSUE TITLE
Wox version: 1.3.183: System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by jiabai** [Wox-launcher/Wox#1033]
[2016-10-29.txt](https://github.com/Wox-launcher/Wox/files/559807/2016-10-29.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 10/29/2016 14:49:48
Exception:
mscorlib
System.UnauthorizedAccessException
尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Wox.SettingWindow.SetStartup() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 64
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 61
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
1. disable your firewall
2. uncheck "start wox on startup" in settings

**Comment by bao-qian** [comment]
#726
