### ISSUE TITLE
can't remember last open position

### ISSUE THREAD

**Issue by ycreative** [Wox-launcher/Wox#1035]
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：
   这是目前我的win10版本号

![image](https://cloud.githubusercontent.com/assets/18115255/19829280/d333146e-9e0e-11e6-8422-d85cdf6966ea.png)

**Comment by bao-qian** [comment]
输入框大小长度可以改
![image](https://cloud.githubusercontent.com/assets/1169912/20393548/31a7f766-acd4-11e6-9548-dc0ba9857e05.png)

宽度要自己改 theme 文件

**Comment by bao-qian** [comment]
position problem duplicate #823
