### ISSUE TITLE
[Wox.Plugin.Query.SplitSearch] Exception: mscorlib System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jeekbs** [Wox-launcher/Wox#1038]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 10/31/2016 08:59:53
Exception:
mscorlib
System.ArgumentOutOfRangeException
索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-10-31.txt](https://github.com/Wox-launcher/Wox/files/560919/2016-10-31.txt)

**Comment by lances101** [comment]
[Please try this build](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by bao-qian** [comment]
plugin bug: Wox.Plugin.Query.SplitSearch
ask the author
