### ISSUE TITLE
在软件的输入框中输入“截图工具”，会出现以下问题

### ISSUE THREAD

**Issue by interpen** [Wox-launcher/Wox#1041]
RT，不能右键出现的文件路径，否则软件本身会假死，然后无法使用。

还有一个问题：系统从休眠状态恢复之后，软件也无法正常使用。

以上问题可以在完全关闭软件再开启之后得到解决。

系统WIN7 64位 SP1 旗舰版 。系统安装在固态硬盘上，此硬盘只有一个分区。

**Comment by bao-qian** [comment]
版本？
用最新版 https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183
