### ISSUE TITLE
Wox not show last command on reopen

### ISSUE THREAD

**Issue by jrock2004** [Wox-launcher/Wox#1050]
I want to open Wox and not see the last thing I typed in there. I checked the settings and I see nothing there. Could you please update to where it will not display the last command you used?

**Comment by artofvs** [comment]
I would love this too

**Comment by roose** [comment]
@jrock2004, @artofvs Try latest build https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Comment by artofvs** [comment]
@roose tried latest one (1.3.300) and it seems like standard behavior didn't change in that version (no new options in settings too)

**Comment by roose** [comment]
@artofvs oh sorry, I misunderstood =) I think "want to see last query"
Old query text is selected, why not just enter new query?

**Comment by jrock2004** [comment]
Because the drop down of the selected text results are executed.

**Comment by lances101** [comment]
@jrock2004 hey there. The query should not execute if you are toggling Wox after submitting a query. The query only executes when there are changes in the query box. What plugin is causing issues for you?

**Comment by abulawright** [comment]
I have found a workaround to what I think you want to archive.

@jrock2004 If you want the search bar to be empty with no previous query, then this is what I have done.

1. In the settings, goto HotKey
2. Change Wox Hotkey to something random
3. Then add a new Custom Query Hotkey with the Hotkey as the main one you want and the 'Action Keyword' leave blank.

The next time you use the hotkey, it should load a blank search.

**Comment by ghost** [comment]
its happened a few times now that ive used one of the system commands like "sleep" to turn off my computer, then when i start it up again the next day i end up triggering it... either because i type in another command and hit enter before the new results have time to show up, or once or twice ive triggered it while i was dusting off my keyboard

clearing the command when the computer starts up would solve that problem for me

**Comment by drasbeck** [comment]
The workaround, although usable, is not very intuitive for regular users. An option in settings would be more forthcoming.

Also: Wox cannot be dismissed with the "blank hotkey".

**Comment by bao-qian** [comment]
@drasbeck yes of course, so this is a workaround and not a fix

**Comment by bao-qian** [comment]
hi new build out, check the new option
![image](https://cloud.githubusercontent.com/assets/1169912/22866790/ab7c1980-f173-11e6-8f8b-3d275e6dcb52.png)
you need option 2 (empty last query)

https://ci.appveyor.com/project/happlebao/wox/build/1.3.344/artifacts

@jrock2004  @artofvs @roose @lances101 @abulawright @drasbeck @davebrny @gerroon @wrgrant

**Comment by drasbeck** [comment]
Very stoked to try this out, looks awesome! But I get the following error when running the executable:

```
Wox version: 1.3.342
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: 
Date: 02/13/2017 09:40:45
Exception:
Wox.Infrastructure
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.Infrastructure.Helper.NonNull[T](T obj) in C:\projects\wox\Wox.Infrastructure\Helper.cs:line 15
   at Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 59
   at Wox.Infrastructure.Storage.JsonStrorage`1.Load() in C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:line 41
   at Wox.ViewModel.MainViewModel..ctor(Settings settings) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 61
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 54
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by bao-qian** [comment]
@drasbeck 
please upload your `%APPDATA%\Wox\Settings\Settings.json` then
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.344/artifacts

**Comment by bao-qian** [comment]
@evmorov try https://ci.appveyor.com/project/happlebao/wox/build/1.3.344/artifacts

**Comment by drasbeck** [comment]
Hi @happlebao, with the new exe, everything works as expected.

**Comment by wrgrant** [comment]
@happlebao 1.3.344 build working great!

**Comment by bao-qian** [comment]
reopen if you have more issue
