### ISSUE TITLE
wox1.3.300在everything1.4.1.782b 版本下内存溢出

### ISSUE THREAD

**Issue by skefy** [Wox-launcher/Wox#1051]
## Known problems for 1.3.300:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：1.3.300
2. 如何**重现** bug：everything版本1.4.1.782b .  使用wox搜索的时候会内存溢出, 在任务管理看wox占的内存大概有2G多.
3. Windows 版本：win10 64位
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
duplicate #1017
