### ISSUE TITLE
there is a problem with the lately win10 ver14959

### ISSUE THREAD

**Issue by jinpeng15800** [Wox-launcher/Wox#1052]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14959.0
Date: 11/05/2016 14:51:01
Exception:
Wox.Plugin.Program
System.NullReferenceException
[Uploading 2016-11-05.txt…]()
[Uploading 2016-11-05.txt…]()

Object reference not set to an instance of an object.
   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136
   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102
   at Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 94
   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by jinpeng15800** [comment]
[2016-11-05.txt](https://github.com/Wox-launcher/Wox/files/573076/2016-11-05.txt)

**Comment by Remiol** [comment]
Not the only problem, many plugins (translate, switch..) don't work well.
I had so many crashes these days that I'm thinking to uninstall it.
And it seems that the creator doesn't answer questions.

**Comment by roose** [comment]
@jinpeng15800 Try latest build https://ci.appveyor.com/project/happlebao/wox/build/artifacts
@Remiol Plugins have its own creators and repositories, @happlebao is busy for now

**Comment by lances101** [comment]
@Remiol, the translate plugin is not supported by Wox itself. It's a third party plugin. 
There are other third party plugins, look at the available ones via `wpm install translate` and choose the one that fits your needs. I personally use the `Google Translate` plugin which I support. 

As @roose said, @happlebao is busy right now and I also started working recently so it's hard to delegate time to Wox. 

@jinpeng15800, please tell if a recent build helps you.

**Comment by Remiol** [comment]
Please don't accept third party plugins which are not tested. People will uninstall your software. The reason why I tried it was the connection with Everything. I like also the fuzzy search. Great ideas!

**Comment by Remiol** [comment]
The Google Translate plugin crashed also yesterday. Yesterday, I decided to reinstall Wox from scratch without plugins because I didn't know which plugin is from serious people and which not.

**Comment by jinpeng15800** [comment]
[2016-11-09.txt](https://github.com/Wox-launcher/Wox/files/579841/2016-11-09.txt)
@roose @lances101  it still run error when I install the new build .this time when it launch,there is no eeror,but when i type any word ,it crash,the window disappaer  ,the error window also flash across。

**Comment by jinpeng15800** [comment]
[2016-11-09.txt](https://github.com/Wox-launcher/Wox/files/579852/2016-11-09.txt)

**Comment by jinpeng15800** [comment]
perhaps when microsoft update their windows build  this or next weekend ,the bugs will fix itself  ,who knows...

**Comment by roose** [comment]
@jinpeng15800 Please try deleting your settings file. You can find it in the following path: `C:\Users\<username>\AppData\Roaming\Wox\Settings`

**Comment by jinpeng15800** [comment]
@roose  thank you !!  I can use it again ! but I can not start the program by wox as usual,sorry to trouble you
![_20161109162937](https://cloud.githubusercontent.com/assets/23273883/20131656/cc921e46-a699-11e6-8702-ba896a343424.png)

**Comment by roose** [comment]
@jinpeng15800 np, hmm, please try restart Wox

**Comment by jinpeng15800** [comment]
@roose  it‘s weird,when i quit wox ,I can not restart it by shortcut icon

**Comment by roose** [comment]
@jinpeng15800 Can you upload log file?

**Comment by jinpeng15800** [comment]
@roose 
[2016-11-09.txt](https://github.com/Wox-launcher/Wox/files/580594/2016-11-09.txt)

**Comment by roose** [comment]
@jinpeng15800 hmm, sorry, I don't know why is not work, try in Wox(if it's runs) enter `restart wox` and press enter

If it's don't work try fully reinstall Wox, uninstall Wox with `Control Panel -> Programs and Features` and delete `C:\Users\<username>\AppData\Roaming\Wox`, `C:\Users\<username>\AppData\Local\Wox` folders, then install Wox from https://ci.appveyor.com/api/buildjobs/f37kx5rklhmr2vyw/artifacts/Releases%2FWox-1.3.301.exe

I'm on win10 build 14393.351, all ok, may be due to win build 😕

**Comment by jinpeng15800** [comment]
@roose  I try it but still ... alright ,it doesn't matter ,I will wait for the new build of ms.
to be honest ,this is the first time I use english to comunicate,thanks alot for suport me

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
