### ISSUE TITLE
crash after issuing wox.plugin.runner command

### ISSUE THREAD

**Issue by basaandewiel** [Wox-launcher/Wox#1059]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 11/06/2016 20:23:32
Exception:
System
System.ComponentModel.Win32Exception
Het systeem kan het opgegeven bestand niet vinden
   bij System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   bij System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bij Wox.Plugin.Runner.Runner.RunCommand(ActionContext e, Query query, Command command)
   bij Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:regel 146
   bij System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   bij System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   bij System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bij System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bij System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bij System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bij System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bij System.Windows.Input.InputManager.ProcessStagingArea()
   bij System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bij System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   bij System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   bij System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-11-06.txt](https://github.com/Wox-launcher/Wox/files/574653/2016-11-06.txt)

**Comment by lances101** [comment]
Runner is not an official Wox plugin and therefore we cannot provide support for it. 
[Please open an issue in the repo of the plugin](https://github.com/jessebarocio/Wox.Plugin.Runner)

[You can also try using a latest build of Wox](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).
