### ISSUE TITLE
启动慢

### ISSUE THREAD

**Issue by breezyjin** [Wox-launcher/Wox#1061]
在win10 中使用wox 1.3.813版本，启动比较慢，一开始以为是设置了Program的问题。
我设置Program插件为禁用，启动还是需要5分钟。
查看任务管理器，发现wox读磁盘IO非常大，持续好几分钟。
这个是正常的吗？可以优化一下吗？

**Comment by lances101** [comment]
我现在知道中文，但我会尽力帮助你。

[请尝试这个版本](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe). 
您可能需要先解锁二进制文件（通过打开属性并单击解除阻止）

**Comment by jhdxr** [comment]
1.3.813？目前不存在这个版本吧。另外启动慢指的是什么？是首次查找很慢（输入关键字后不出结果？）还是说启动后要很久才能显示窗体？

另外在插件那你能看到每个插件的初始化耗时和查询耗时，看看是否有某个特别大的？

**Comment by jinpeng15800** [comment]
![qq 20161115230209](https://cloud.githubusercontent.com/assets/23273883/20310902/a29a1a28-ab88-11e6-89b7-073cf37c5bda.png)
@lances101 @jhdxr 这个程序的插件耗时很严重。。。。

**Comment by jhdxr** [comment]
@jinpeng15800 但在你一开始的时候提到过设置Program为禁用依然没有解决这个问题？现在依然如此吗？另外请再次确认你的wox版本（并告诉我们）

@lances101 this issue might be duplcate of #1017 , but according to #351 , if a plugin is disabled, `init()` or constructor should not be called (I don't confirm this, since I fail to compile the latest code)

**Comment by jinpeng15800** [comment]
@jhdxr  这个贴不是我发的，只是路过问一下。。
我把程序这个插件禁用之后速度就正常了，但是这个插件对我很重要，我需要用它快速打开一些程序，我是用的版本是1.3.304 之前  @lances101 提到的295版本我也试过也是一样

**Comment by jhdxr** [comment]
@jinpeng15800 如果你是win7或者你不需要ump的支持，你可以考虑先使用1.3.183，并不存在这个问题（但可能会有一些别的问题

**Comment by jinpeng15800** [comment]
@jhdxr  I tried the build 1.3.183 ,and it's perfect ,thank you

**Comment by bao-qian** [comment]
试一下新版本
https://ci.appveyor.com/project/happlebao/wox/build/1.3.331/artifacts

**Comment by sustain86** [comment]
新版中移除了程序插件，那如何实现快速启动？
‘

**Comment by bao-qian** [comment]
@sustain86 新版中没有移除任何插件啊？
截图并上传 log 看一下

**Comment by sustain86** [comment]
额 1.3.331里面没少但是之前的325里面没有
然后331开机启动还是慢  我算了log里各项插件加载时间总计几乎三分钟
Wox : 1.3.331

[2017-01-14.txt](https://github.com/Wox-launcher/Wox/files/705998/2017-01-14.txt)

**Comment by bao-qian** [comment]
@sustain86 你试一下
1. 禁止 程序 插件
2. 禁止 控制面板 插件
3. 和两个一起禁止
启动时间有什么差别？
然后上传 log

以前用 release 里面的 1.3.183 有这个问题吗？

**Comment by sustain86** [comment]
[2017-01-17.txt](https://github.com/Wox-launcher/Wox/files/711166/2017-01-17.txt)

log中
21:04 为禁止程序插件后重启电脑启动wox
21:11 为退出后再次启动wox
21:21 为同时禁止程序插件和控制面板后再启动
21:27 为只禁止控制面板后再启动

问题： 插件禁止后仍然启动
            开机后第一次启动时间较长，磁盘占用比例较高，之后的几次启动时间就会缩短，相互之间几乎无差别`。
            
1.3.183和这个情况一样

**Comment by bao-qian** [comment]
@sustain86 
你再试试这个版本 https://ci.appveyor.com/project/happlebao/wox/build/1.3.341/artifacts

如果还是开机第一次启东要几分钟，之后的启动就只是几秒的话，那我没什么办法了。。。
这属于系统问题了。。。
你可以试试重新创建一个账号（非 admin）然后启动试试看。
新账号没问题，那就说明是系统问题。新账号有问题，上传 log 我再想想。。。

**Comment by bao-qian** [comment]
有问题再开
