### ISSUE TITLE
输入框插入字符光标自动移到末尾

### ISSUE THREAD

**Issue by pangliang** [Wox-launcher/Wox#1062]
1. Wox 版本 / commit number：
1.3.183

2. 如何**重现** bug：
输入框先输入"adef", 然后我想在ad中间输入bc, 移动光标到ad中间, 但是当输入"b"之后光标自动移动到了f后面, 也就是变成了"abdefc"

3. Windows 版本：
win10

4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
我现在知道中文，但我会尽力帮助你。

[请尝试这个版本](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe).
您可能需要先解锁二进制文件（通过打开属性并单击解除阻止）

**Comment by jhdxr** [comment]
duplicate of #813 , this is fixed in the latest version (without public release)

@lances101 提供的版本应该也解决了这个问题

**Comment by lances101** [comment]
@jhdxr thanks. Gosh, I really need to rollout 295 at least as soon as possible. 50% of the issues popping up are for the 183. 

Closed due to being a duplicate of #893
