### ISSUE TITLE
如何打开文件夹

### ISSUE THREAD

**Issue by shuijinliuxi** [Wox-launcher/Wox#1063]
用 Wox 通过 everythings 搜索到的文件列表，如何打开文件所在的文件夹呢？

我在官网上没看到相关的功能，也搜索不到这方面的说明。

**Comment by lances101** [comment]
我不知道中文，我使用翻译。 一旦你选择了文件，按下“SHIFT + ENTER”。 这将打开一个子查询，您可以在其中选择打开文件的文件夹。

如果您有任何问题，请在此回复。
