### ISSUE TITLE
mscorlib System.IO.IOException The process cannot access the file 'C:\Users\x\AppData\Local\Wox\app-1.3.x\Images\app_error.png' 

### ISSUE THREAD

**Issue by tashakcor** [Wox-launcher/Wox#1068]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/08/2016 22:50:40
Exception:
mscorlib
System.IO.IOException
Процесс не может получить доступ к файлу "C:\Users\Natalia\AppData\Local\Wox\app-1.3.67\Images\app_error.png", так как этот файл используется другим процессом.
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalDelete(String path, Boolean checkHost)
   в System.IO.File.Delete(String path)
   в Squirrel.Utility.<DeleteDirectory>b__34(String file) в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 336
   в Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 224
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

`...`

**Edit**: @lances101 here. Highjacking top comment just in case people miss @roose's message with the fix.

## How to fix

"Try deleting `C:\Users\<username>\AppData\Local\Wox\app-1.3.67` folder, and restarting Wox." @roose

**Comment by roose** [comment]
Try to delete `C:\Users\Natalia\AppData\Local\Wox\app-1.3.67` folder, and restart Wox.

**Comment by tashakcor** [comment]
thank you!

**Comment by dvdantunes** [comment]
thank you! this fix worked for me too 👍

**Comment by adeonir** [comment]
thanks! this fix worked here, too.

**Comment by FelixHuoEZ** [comment]
Thanks, it does work.

**Comment by zhangjialiang-tt** [comment]
it helps.thanks!

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
