### ISSUE TITLE
Open File-Location functionality.

### ISSUE THREAD

**Issue by CoenraadS** [Wox-launcher/Wox#107]
Hi, I have an enhancement I would like to request.

My ideal enhancement would be a context menu on right-click, that would bring up the respective context menu as if I clicked the item in a normal desktop environment, but I understand that might be unfeasible.

A more realistic enhancement would be 'Open-file location'.
I coded my own implementation that works on right-click:
https://gist.github.com/CoenraadS/83c4cae2989225679faa

Click handling simply done in OnMouseClickItem()
And added an openFileLocation() method

However I'm pretty sure this doesn't belong in ResultPanel.xaml.cs, but I am unsure how to implement its functionality properly without messing up the program a lot, hence I'm not created a pull request, but I would appreciate it if you could perhaps integrate it correctly into Wox.

**Comment by qianlifeng** [comment]
Yes, I thought about the context menu function, the context menu should be customized by plugin creator. see below, click to see the large version.
<img src="http://scott-tuchuang.qiniudn.com/wox%20context%20menu.png" />

**Comment by Ra0EL** [comment]
Hi,
I guess that would also provide an alternative to the lack of **"Open with..."** feature in Wox :)
It is nice to be able to search files. But would be better to have the choice to what ever I want with this file ( open, edit... maybe even copy, delete... ) :smile:

**Comment by CoenraadS** [comment]
Seems to be a nice library already existing that could be used: http://www.codeproject.com/Articles/22012/Explorer-Shell-Context-Menu

**Comment by qianlifeng** [comment]
Looks great. We can implement this when we complete the context menu architecture.

**Comment by qianlifeng** [comment]
This has implemented in V1.1.0. So I'm closing this.

**Comment by terepanda** [comment]
Hi,
Is there any way to specify a filer to open the file location (Open containing folder)?  Wox always uses exploer.exe even the system default filer has been changed (HKEY_CLASSES_ROOT\Folder).  I'd really appreciate if Wox uses the default filer when it's changed, or user can specify the filer Wox uses.  Of course, Wox uses the default filer to open a folder when a query specifies a folder.  This is only the case for 'open containing folder' functionality.

**Comment by bao-qian** [comment]
@terepanda use #623
