### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException 已取消一个任务。

### ISSUE THREAD

**Issue by Xstarfct** [Wox-launcher/Wox#1071]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/09/2016 09:06:42
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 [System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object](url) source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-11-09.txt](https://github.com/Wox-launcher/Wox/files/579772/2016-11-09.txt)

**Comment by jhdxr** [comment]
这个是已知问题，是由于自动更新并且github（的部分域名）被墙导致的，科学上网可解决

this is a known issue. the domain used for self-update is blocked in China due to GFW, you may need some "magic" to deal with this.

**Comment by Xstarfct** [comment]
so  if i config the proxy, may be the issue will be resoved?

**Comment by jhdxr** [comment]
@Xstarfct yep, or you may disable the auto-update
since you can start wox, you can edit the setting.json manually:
1. open `%appdata%\Wox\Settings\Settings.json`
2. looking for `AutoUpdates`
3. change the value from `true` to `false`

**Comment by Xstarfct** [comment]
ok  thank u for your help .
