### ISSUE TITLE
下载不了 能发个邮件么？为什么后面不在百度云上面放备用下载了？yongzhian@163.com thx

### ISSUE THREAD

**Issue by yongzhian** [Wox-launcher/Wox#1073]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by jhdxr** [comment]
后面发的几个都属于测试版吧，如果你没有掌握『科学上网』技能的话，那这些测试版不适合你（参考 known problems的第三个）

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/20367608/2539b0a0-ac48-11e6-99a3-83f1778dea96.png)

**Comment by yongzhian** [comment]
Thanks
