### ISSUE TITLE
Win7下debug版抛exception

### ISSUE THREAD

**Issue by thinkinnight** [Wox-launcher/Wox#1079]
应该是加了win10支持的原因，首先一堆Windows.ApplicationModel找不到，然后安装好win10 SDK后，还是有一个Windows.ApplicationModel.Package有元数据但是load不了。
在release版下，会catch异常并进行记录，但是debug版下没有catch，所以会直接抛异常。
在只有下面异常时，
An exception of type 'System.TypeLoadException' occurred in Wox.Plugin.Program.dll but was not handled in user code

Additional information: Could not find Windows Runtime type 'Windows.ApplicationModel.Package'.

可以在调用_uwps = UWP.All();时判断是否是win10来处理掉该异常

**Comment by bao-qian** [comment]
只支持最新 windows10 + vs2015 update 3 来开发。
