### ISSUE TITLE
About 'Hide Wox when loses focus'

### ISSUE THREAD

**Issue by IamIpanda** [Wox-launcher/Wox#108]
Even though checked the option 'Hide Wox when loses focus', on the first time you launch Wox, If you focus other window before input window shows, Wox will still show for ever.

P.S. or to say, it's too slow...

**Comment by orzFly** [comment]
Good point. Wox should not show the input box at startup.

**Comment by qianlifeng** [comment]
We have a argument `wox.exe hidestart` to hide wox when startup.  I think when user double click the wox.exe, we should show the Wox directly. I will try to speed up startup.

**Comment by IamIpanda** [comment]
Well it's always like that...
I want to search a file... Ah call Wox to launch Everything. Then I pressed Alt+Space, ouch... so slow. Let me think, That file is on D:. When I started explorer, Wox showed up >/////< for ever...

**Comment by qianlifeng** [comment]
It can't be so slow!!! @lamlpanda What's version are you use? Can you debug the Wox? If you can, try to add `return null` before [this line](https://github.com/qianlifeng/Wox/blob/master/Wox/Converters/ImagePathConverter.cs#L55). I know Wox will be slow to show program icons in some old machine(without SSD), but even it should be a little slow in that situation, it can't be even so slow as you described.

**Comment by orzFly** [comment]
I think, in his situation, Wox is running in the background. The memory management of Windows is quite silly that Wox is moved into page file. It’s really slow to wake such a .NET program from page file into memory.

I think @IamIpanda don’t have too much memory and he has a large enough page file.
-- 
orzFly / Yeechan Lu

On July 13, 2014 at 16:15:56, qianlifeng (notifications@github.com) wrote:

It can't be so slow!!! @lamlpanda What's version are you use? Can you debug the Wox? If you can, try to add return null before this line. I know Wox will be slow to show program icons in some old machine(without SSD), but even it should be a little slow in that situation, it can't be even so slow as you described.

**Comment by bao-qian** [comment]
200ms faster for query now. 
Try the Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
- [ ] Wox should not show the input box at startup.

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15480982/2b39220a-2120-11e6-8661-9bfc6e6ccb8e.png)
done
