### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by gustafsoldan** [Wox-launcher/Wox#1083]
[2016-11-10.txt](https://github.com/Wox-launcher/Wox/files/584110/2016-11-10.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/10/2016 19:30:35
Exception:
mscorlib
System.IO.IOException
Processen kan inte komma åt filen C:\Users\Gustaf\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Caculator\Images\calculator.png eftersom den används i en annan process.
   vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   vid System.IO.File.InternalDelete(String path, Boolean checkHost)
   vid System.Threading.Tasks.Task.Execute()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 234
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 342
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 0
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 234
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 342
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 0
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 234
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 342
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 0
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 234
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 342
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a9>d__b7.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:rad 286
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 533
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:rad 49
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:rad 73
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:rad 533
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() i c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:rad 169
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Wox.Core.Updater.<UpdateApp>d__0.MoveNext() i C:\projects\wox\Wox.Core\Updater.cs:rad 56
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   vid System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   vid System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by roose** [comment]
Try to delete `C:\Users\Gustaf\AppData\Local\Wox\app-1.3.67` folder, and restart Wox.

**Comment by lances101** [comment]
Duplicate, please check #1068. Closed.
