### ISSUE TITLE
frequently popup error window

### ISSUE THREAD

**Issue by FelixHuoEZ** [Wox-launcher/Wox#1087]
In recent three days, Wox always popup an error window, and after a few minutes, Wox will be forced to close because of some unexpected error with the operating system.
The window and log file are as follows.

![error in popup window](http://i.imgur.com/qy7H9NP.png)
[2016-11-11.txt](https://github.com/Wox-launcher/Wox/files/584873/2016-11-11.txt)

**Comment by lances101** [comment]
Duplicate. Please check #1068
