### ISSUE TITLE
Python version in readme

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#109]
May be necessary to write in the readme that for work python plugins need python 2.7
(sorry for my english)

**Comment by qianlifeng** [comment]
Wox include a built-in python 2.7 environment in last commit (with requests and beautifulsoup4), and the python API has changed. I will update the  [Create-Plugins-using-Python](https://github.com/qianlifeng/Wox/wiki/Create-Plugins-using-Python) when I have time, also the readme. Thx.

**Comment by roose** [comment]
@qianlifeng Fine, look forward to it, thank you.
