### ISSUE TITLE
everything

### ISSUE THREAD

**Issue by cougarzy** [Wox-launcher/Wox#1092]
之前用带是1.20版本，点击wox，可以直接启动everything插件，更新到最新版之后必须手动点击everything插件吗？请高手回复，谢谢。

**Comment by cougarzy** [comment]
显示everything service没有运行，请问什么原因呢，谢谢。

**Comment by lances101** [comment]
我不知道中文。 这是翻译。 对不起，坏的语言。

一切都不再与Wox一起安装。
您需要单独安装它。[ 您可以在这里下载。](https://www.voidtools.com/)

**Comment by cougarzy** [comment]
@lances101 ,thx for your help,i appreciate it,would you PLEASE use English help again?

**Comment by lances101** [comment]
Sure, no problem.  Anyway, did it solve your issue?

**Comment by cougarzy** [comment]
@lances101 yeah,its helpful,thx man.
