### ISSUE TITLE
Wox error

### ISSUE THREAD

**Issue by ahswch** [Wox-launcher/Wox#1093]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt

`）：
6. 截图 （可选）：

`Wox version: 1.3.67 OS Version: Microsoft Windows NT 10.0.14393.0 Date: 11/14/2016 11:53:40 Exception: Wox System.NullReferenceException 未将对象引用设置到对象的实例。    在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48    在 System.Windows.Application.OnStartup(StartupEventArgs e)    在 System.Windows.Application.<.ctor>b__1_0(Object unused)    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by lances101** [comment]
You are running a pretty old version of Wox - `1.3.67`. 

[Please update to the latest release `1.3.183` from here](https://github.com/Wox-launcher/Wox/releases)
or [download one of the latest builds (`1.3.295`) from here](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe)

**Comment by bao-qian** [comment]
we don't support old version
