### ISSUE TITLE
可不可以考虑加入一个配置来取消鼠标的滑过事件

### ISSUE THREAD

**Issue by gys13200** [Wox-launcher/Wox#1102]
当鼠标在屏幕中间时， 我打开wox来做一些操作的时候，  Wox的焦点会从第一个移动到鼠标所在的位置
![image](https://cloud.githubusercontent.com/assets/13346590/20331523/caa27558-abe0-11e6-8339-e59ce52c10a3.png)

当有下拉列表时，
![image](https://cloud.githubusercontent.com/assets/13346590/20331593/4db05488-abe1-11e6-9931-3eb8d3078dbf.png)

**Comment by qianlifeng** [comment]
Already fixed in v2
