### ISSUE TITLE
win10 64bits 安装报错

### ISSUE THREAD

**Issue by XuHuaiyu** [Wox-launcher/Wox#1103]
1. wox版本：1.3.183

2. what did I got?

![image](https://cloud.githubusercontent.com/assets/9039012/20333980/84aeb604-abf1-11e6-9d80-2524b51da00b.png)

3. error log:

[SquirrlelSetup.txt](https://github.com/Wox-launcher/Wox/files/593707/SquirrlelSetup.txt)

**Comment by lances101** [comment]
You seem to be trying to run Wox through the .exe that you downloaded. Although it is an option, it will reset Wox's files every time. Have you tried running Wox through the desktop icon or start menu? 

In the case that running Wox through the shortcuts does not work either, please check in the Task Manager that Wox is not running and delete the folder `C:\Users\xhy\AppData\Local\Wox\`. Then try running `Wox-1.3.183.exe` again.

**Comment by bao-qian** [comment]
looks there is an dead wox process running.
after delete the folder `C:\Users\xhy\AppData\Local\Wox`,
restart your pc,
then try again

**Comment by XuHuaiyu** [comment]
hi, guys
Sorry to reply you later @happlebao @lances101 

I do as @happlebao said, and install Wox successfully.
