### ISSUE TITLE
websearch插件中为搜索地址添加ICON，重启WOX后自动失效变回原ICON

### ISSUE THREAD

**Issue by MrCloudyGod** [Wox-launcher/Wox#1109]
已经在WIN10和WIN7两个系统下进行过测试。
WOX版本为1.3.183
在websearch插件中修改搜索引擎的图标，刚修改完的时候是可以再搜索栏中正常显示的。
一旦重启过wox，就又自动变回原来的默认图标了。
重启WOX之后，在WIN7系统下还会出现自行添加的搜索引擎的触发关键字失效的问题，WIN10虽然图标回到默认，但自行添加的搜索引擎触发关键字还能正常使用。
对了，有的时候修改的触发关键字还会提示我已经被使用，但实际上根本没有被占用啊。

另外，我试用过1.3.306的版本……这个图标问题似乎是解决了，但因为太卡我又退回来了……

**Comment by bao-qian** [comment]
试一下 1.3.231?

**Comment by MrCloudyGod** [comment]
非常感谢，强迫症的问题被解决了真是非常舒坦~
另外想问一个问题，就是为什么getwox那个网站上依旧是1.3.183版本呢
包括AppVeyor那里的新版本我也是在issues中寻找答案时偶然看到的……
还有1.3.306卡顿的原因是啥……中间的历史版本好像有很多……为啥最优推荐1.3.231呢……
后面的版本如果有什么新功能或者新改进只要不卡我还是非常乐意用代号新的2333~

**Comment by bao-qian** [comment]
最新版就是因为有严重 bug （也就是说我不知道……………） 才没放出来啊……
231 是 https://github.com/Wox-launcher/Wox/issues/1017#issuecomment-261450584 有人测出来的…

新修改主要是加了 uwp 的功能… 然而有bug…

**Comment by MrCloudyGod** [comment]
原来如此……难怪我在用1.3.306的时候搜索搜到了UWP软件……
嘛不过个人习惯常用UWP都固定到屏幕去了，也没有对这个功能的追求，老老实实用这个版本好了233

说个别的，对wox的主题比较感兴趣。也看着自带的主题改了改代码……
不过自己是个代码白痴也不懂…只是复制粘贴这样子弄出了一个还算合胃口半透的样式…
期间发现那个cornerradius，也就是那个圆角参数啊，添加之后是有圆角了……但是圆角底下还是有一层白色的方角……不知道为何
还有在getwox站上的plugins里我看到有几个插件的演示图上的主题很好看，似乎给搜索框框的外边框添加了平铺式的图片……不知道怎么实现的……

以上与此issues标题无关的问题只是随便一问，不用解答也没事~~哈哈，自己捣鼓捣鼓玩

再次感谢~

**Comment by bao-qian** [comment]
主题问题你另外开 issue 用英语问吧
ui 我不是很懂
很懂那个（b什么的）不会中文
