### ISSUE TITLE
Add hotkey for quick lunch.

### ISSUE THREAD

**Issue by BeyondIM** [Wox-launcher/Wox#111]
1. Launch first result when hitting "Tab"
2. Launch #th result when hitting "Alt+#th"
3. Launch #th result and keep  open when hitting "Ctrl+#th"

**Comment by qianlifeng** [comment]
Thx for the suggestions. I will implement this in the feature.

**Comment by orzFly** [comment]
I am curious about the real scene of the third suggestion.

**Comment by vovkkk** [comment]
> I am curious about the real scene of the third suggestion.

‘Keep open’ is must-have feature, it would speedup launching many apps one-by-one, let’s say I want to mess with regex — Zeal (docs), Kodos (test regex), Sublime Text (edit/launch Python code), music app, chat/skype, etc. — w/o ‘keep open’ you press <kbd>alt+space</kbd> each time — it is tediously.

Though <kbd>Ctrl+#th</kbd> is questionable, imho, I’d prefer <kbd>Ctrl+enter</kbd> on highlighted item (or better if it would be customisable).

**Comment by ghost** [comment]
i was only thinking about this today when using the hacker news plugin, its good for browsing but if you want to open more than one of the links then it takes a lot of key pressing, so yea something like ctrl + enter would be a good one alright
