### ISSUE TITLE
Can't set hotkey to Win + Space

### ISSUE THREAD

**Issue by appel** [Wox-launcher/Wox#1112]
Thanks so much for Wox, it's great to have something that approaches Spotlight on Windows! I wanted to emulate it as close as possible (muscle memory, amiright?), so I tried setting the hotkey to WIN + Space, but unfortunately it seems Wox doesn't play ball. Not sure if it's a bug, or if it's possible, but hoping it is.

> Before you report any bugs try search existing issues

No issues found.

> Please specify Wox version

1.3.295

> Please describe the steps to reproduce the bug

Try to set hotkey to `Win + Space`. Wox will put `Win + LWin` `succeed`, instead. Wox hotkey subsequently seems to be set to `Win`, whereas I'm hoping to be able to use `Win + Space`.

> Please provide Windows version

Windows 10 Home x64 - 1607 - 14393.447

> Please provide Exception info if you have.

No exception

> Please provide logs from %APPDATA%\Wox\Logs if you have.

Nothing related to this bug.

> Please provide screenshot if you have

Not applicable.

**Comment by bao-qian** [comment]
almost impossible since windows 10,
windows 10 won't allow app to overwrite existing shortcut.

**Comment by appel** [comment]
Well, that's the weird thing. Apparently you _are_ allowed to overwrite the `Win` shortcut this way, which seems to me to be just about the most important standard Windows hotkey. I'm currently able to alternate between Wox and the Windows start menu by hitting the Win key.

Plus, `Esc` seems to work. As does `Win + Shift + S`. So then why not `Win + Space`?

**Comment by bao-qian** [comment]
You can use win key for shortcut key, but you can't overwrite/suppress   **existing** shortcut (there are some exceptions though). There are no docs (at least I didnt find it) for this behaviour.

**Comment by appel** [comment]
Gotcha. I'll just make it work with `CTRL + Space`. ;) Thanks @happlebao!

**Comment by mpb27** [comment]
You can use AutoHotKey to send `Alt+Space` when `Win+Space` is pressed:

`#space::SendInput !{Space}`

**Reference**: http://www.msfn.org/board/topic/140220-disable-winspace-hotkey/?do=findComment&comment=942026

**Comment by liaten** [comment]
> 
> 
> You can use AutoHotKey to send `Alt+Space` when `Win+Space` is pressed:
> 
> `#space::SendInput !{Space}`
> 
> **Reference**: http://www.msfn.org/board/topic/140220-disable-winspace-hotkey/?do=findComment&comment=942026

This is not a good solution to the problem.

**Comment by eeriemyxi** [comment]
> You can use AutoHotKey to send `Alt+Space` when `Win+Space` is pressed:
> 
> `#space::SendInput !{Space}`
> 
> **Reference**: http://www.msfn.org/board/topic/140220-disable-winspace-hotkey/?do=findComment&comment=942026

I still do not understand how AutoHotkey is able to do it but not Wox; is there some concealed amity between Microsoft and Chris Mallet?
