### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1113]
安装有道插件 重启后一直不能用
everything装了之后 是不能直接在wox里面使用么？每次都要先打开everything，才能在wox里面搜，否则显示服务无法运行

**Comment by bao-qian** [comment]
1 你是装的这个吗？`wpm install 有道`
2 是的，everything 不要关

**Comment by ghost** [comment]
1-谢谢完美解决我的问题！我装的是 wpm install youdao 希望以后注明啊 而且很多微信公众号的推荐都是说youdao
2-要是内嵌everything就好了
thanks again

**Comment by bao-qian** [comment]
我既不知道有哪些公众号。。。
这些公众号写文也没问过我。。。。

**Comment by ghost** [comment]
但其实wpm install youdao也是有一个插件的 youdao translator 只是一直装不上...=_=心疼

**Comment by AjiMIde** [comment]
点赞！实际上是安装 **wpm install 有道**。。。。坑爹 呀~~~
