### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by kayshen0817** [Wox-launcher/Wox#1118]
之前用的好好的，突然就报错不能用了，也不是程序员，所以也不懂怎么回事，就提交一下日志，做个贡献么好了。先不用了。
2016-11-21 08:58:48.5598|INFO|Wox.Plugin.Program.Main.Init|Preload 360 programs from cache
2016-11-21 08:58:48.5859|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-21 08:58:48.5859|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|未将对象引用设置到对象的实例。
2016-11-21 08:58:48.5859|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
2016-11-21 08:58:48.5859|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-21 08:58:48.5999|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|未将对象引用设置到对象的实例。
2016-11-21 08:58:48.5999|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
2016-11-21 08:58:48.5999|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-21 08:58:48.5999|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|发生一个或多个错误。
2016-11-21 08:58:48.5999|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-11-21 08:58:48.6159|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|未将对象引用设置到对象的实例。
2016-11-21 08:58:48.6159|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-11-21 08:58:48.6159|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-11-21 08:58:48.6159|ERROR|System.Threading.Tasks.Parallel.ForWorker|发生一个或多个错误。
2016-11-21 08:58:48.6159|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-11-21 08:58:48.6329|ERROR|System.Threading.Tasks.Parallel.ForWorker|未将对象引用设置到对象的实例。
2016-11-21 08:58:48.6329|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-11-21 08:58:48.6539|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox.Plugin.Program
   TargetAssembly: Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Program.dll
   TargetSite: System.Collections.Generic.List`1[Wox.Plugin.Program.ProgramSource] DefaultProgramSources()
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: 发生一个或多个错误。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 94
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 53
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment

* Command Line: "C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Wox.exe" 
* Timestamp: 11/21/2016 08:58:48
* IntPtr Length: 8
* System Version: Microsoft Windows NT 10.0.14393.0
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.6.01586
   * v4 Full 4.6.01586
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Wox.exe)
* Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
* Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
* Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
* HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
* Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\kaysh\AppData\Local\Wox\app-1.3.183\NLog.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* PresentationCore.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份

**Comment by kayshen0817** [comment]
谢谢，我试试看。

**Comment by kayshen0817** [comment]
为了保险起见，%APPDATA%下Local和Roaming里面的wox文件夹都删了，应为我用的是默认设置，所以没有去备份配置文件或者插件什么的。刚刚开始接触还没有加插件，以前折腾过黑苹果，所以用过Alfred,那个真的是非常好用，后来因为工作需要就换回windows了，一直想找个类似的软件，但是没有，不久前无意中看到您这个软件，赶紧就下了。真的是很不错，真的是太方便太喜欢了（可惜windows的字体渲染很尿性)。希望软件越做越好。谢谢！

**Comment by bao-qian** [comment]
谢谢
喜欢请右上角加星
字体我推荐这款 https://be5invis.github.io/Iosevka/inziu.html

**Comment by kayshen0817** [comment]
好的，谢谢！抽空也学点编程去。
