### ISSUE TITLE
WOX插件HOSTS无法正常安装

### ISSUE THREAD

**Issue by cced3000** [Wox-launcher/Wox#1119]
http://www.getwox.com/plugin/20

不管是通过下载拉到搜索框，还是wpm isntall hosts 都无法正常安装，按照过程虽然提示已经安装，要重启，但是重启后，并没有这个插件列表里并没有这个插件，而且也无法通过命令启动功能。

**Comment by lances101** [comment]
That plugin uses Python. Please check that you have your Python path set in Wox's settings. 

Before reinstalling the Hosts plugin, I recommend you close you and then navigate to `%appdata%/Plugins`and delete all "Hosts" plugin directories. 

Reopen if you still have issues.
