### ISSUE TITLE
默认的触发关键字*无法使用

### ISSUE THREAD

**Issue by muxiaokun** [Wox-launcher/Wox#1123]
![qq 20161122013436](https://cloud.githubusercontent.com/assets/9822226/20493461/d9e225e6-b053-11e6-8a3e-14df43809ee7.png)
![qq 20161122013515](https://cloud.githubusercontent.com/assets/9822226/20493487/fb447d38-b053-11e6-8147-17c2495b040f.png)
所有触发关键字为*的不设置关键字都无法正常使用，随意设置关键字均正常
我有两台电脑安装了Wox都是Win10x64 一台能正常运行 一台会出现上述问题

**Comment by muxiaokun** [comment]
delete %APPDATA%\Wox

如果是自动就更好了^_^

**Comment by FunkySamuel37** [comment]
@muxiaokun i got the same problem, what you mean? delete the Wox.exe?

**Comment by bao-qian** [comment]
Delete above directory

**Comment by FunkySamuel37** [comment]
the directory above where wox.exe? or move the whole folder out the c://users/Username/AppData ？

**Comment by bao-qian** [comment]
c://users/Username/AppData/wox
This is the setting directory, delete it will reset wox.

**Comment by FunkySamuel37** [comment]
okey, thanks you so much @happlebao.
Every Thing is perfect now. 😀
The config file is in the C:\Users\Samuel37\AppData\RoamingWox in my system, it's windows 10.
