### ISSUE TITLE
Wox.Plugin.Program System.NullReferenceException

### ISSUE THREAD

**Issue by zhizunbao84** [Wox-launcher/Wox#1128]
[2016-11-23.txt](https://github.com/Wox-launcher/Wox/files/608055/2016-11-23.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/23/2016 11:30:11
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

**Comment by yuqh** [comment]
the same question I'd met

**Comment by ztmdsbt** [comment]
I met this issue too.

**Comment by Eligioo** [comment]
Tried resetting %APPDATA%\Wox folder?

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份
