### ISSUE TITLE
 Access any folder

### ISSUE THREAD

**Issue by idrissKour** [Wox-launcher/Wox#1129]
Hello,

I use recently _WOX_ and some file or folder does not appear but in _Everything_ it appears.
for exemple :  C:/a/b  : I such the file or directory by typing b.
In _Everything_ it will appears but not in _WOX_.

**Comment by lances101** [comment]
@bobobob951357, to find a file in a folder with Everything you need to use backwards slashes as is used in Windows.  

[An example of a query like this is available on the wiki](https://github.com/Wox-launcher/Wox/wiki/Default-Plugins.-Everything-Search)

**Comment by idrissKour** [comment]
Hello, 
I have a problem when I enter a filename it looks to infinity without finding then before it succeeded

`Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\user\AppData\Roaming\Wox\Logs\1.3.67\2016-11-25.log
2. copy below exception message
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/25/2016 19:56:33
Exception:
mscorlib
System.IO.IOException
L'accès au chemin d'accès 'Images' est refusé.
   à System.IO.DirectoryInfo.MoveTo(String destDirName)
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() dans c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:ligne 234

**2016-11-25.log**
```
2016-11-25 19:57:21.6459|ERROR|System.Number.ParseDouble|
   à System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
```
   `

**Comment by bao-qian** [comment]
Screenshot?

**Comment by idrissKour** [comment]
Hello,


After System.IO.IOException It is said : 
The process can not access the file : ... , because it is being used by another process.
After à System.Threading.Tasks.Task.Execute(): 
-- End of the trace ... -- 

![1](https://cloud.githubusercontent.com/assets/23707852/20636753/27e0a098-b38c-11e6-8862-4d909f0b3d01.png)


![2](https://cloud.githubusercontent.com/assets/23707852/20636697/3634515e-b38b-11e6-93d2-2da99f63250b.png)

**Comment by bao-qian** [comment]
whole log file please
1016-11-26.log
