### ISSUE TITLE
体验性问题

### ISSUE THREAD

**Issue by ddqspace-xyz** [Wox-launcher/Wox#1130]
输入的时候，如果想从中间再输入插入一段，这时输入英文字符时，每输入一个字符，光标就会跳到最后，这时如果没有写完的话，又得回头继续输入，比较影响体验，而输入中文则不会有这个问题。
![image](https://cloud.githubusercontent.com/assets/16386654/20638013/320684be-b3d4-11e6-856a-a3a5fb410592.png)
![image](https://cloud.githubusercontent.com/assets/16386654/20638015/3f33741c-b3d4-11e6-9a26-37607430f6d1.png)

**Comment by jhdxr** [comment]
duplicate of #813
用1.3.231：https://ci.appveyor.com/project/happlebao/wox/build/1.3.231/artifacts

**Comment by ddqspace-xyz** [comment]
Thanks, sincerely holp wox better.

2016-11-27 1:36 GMT+08:00 xiami <notifications@github.com>:
