### ISSUE TITLE
win10 cannot open this file

### ISSUE THREAD

**Issue by Lilaccoral** [Wox-launcher/Wox#1131]
win 10 cannot open this file

1,"fusion","GAC",0
1,"WinRT","NotApp",1
3,"System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System\ee1c3ea3e0049df6d53b35e21c2247e4\System.ni.dll",0
3,"PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\bc3f07633c1829b68228796f72a64663\PresentationCore.ni.dll",0
3,"PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\a3317d3137e1e1302c5f8f34ffce1622\PresentationFramework.ni.dll",0
3,"System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\46ebe2b057622677cfc3fd04f47081c0\System.Core.ni.dll",0
3,"WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\WindowsBase\61103ac73bccca74b102807a0baf3495\WindowsBase.ni.dll",0
3,"System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xaml\db1726d3f4aef60e7fc01ed9879d9870\System.Xaml.ni.dll",0
3,"System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runt73a1fc9d#\4da3c72f42204a2df7e76da2a003a8df\System.Runtime.Remoting.ni.dll",0
3,"System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\a7f47973b917fdac945dd35f56b99eaf\System.Configuration.ni.dll",0
3,"System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\42142f2f161821b78f345ecf759fa095\System.Xml.ni.dll",0
3,"System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Numerics\ed34299df90bda5a02598c5c4b4a9e24\System.Numerics.ni.dll",0
3,"System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runteb92aa12#\d55e112b638ed61c3240dd7e16670fd1\System.Runtime.Serialization.ni.dll",0
3,"System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml.Linq\3eacb3a4f85df004c8de770939a0ce93\System.Xml.Linq.ni.dll",0
3,"System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Data\29b20969676c89ace6ddd9b6c4b8c978\System.Data.ni.dll",0
3,"System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\3ac58fb7cb8d849d0f85f2435e1a0066\System.Drawing.ni.dll",0
3,"PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\957a4e9177ae3dcd484b648d21000323\PresentationFramework.Aero2.ni.dll",0
3,"System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.ServiceModel\9d0f658faeab6352336ec6d83411ed47\System.ServiceModel.ni.dll",0
3,"System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Net.Http\7b8c4f0b63e4cdb8b7edfe1fac0a005c\System.Net.Http.ni.dll",0
2,"PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",0
3,"System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\04e26b57f0c211fdb0d877810b37497f\System.Windows.Forms.ni.dll",0
3,"UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\UIAutomationTypes\87662a15ac428be4fd81e30b61f63925\UIAutomationTypes.ni.dll",0
3,"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Web\32dfa16b008e619728960e40eb978ce3\System.Web.ni.dll",0
3,"System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Comp46f2b404#\56508422f503c43a73350424949e69ef\System.ComponentModel.DataAnnotations.ni.dll",0
2,"PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",0
2,"PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",0
3,"UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","C:\Windows\assembly\NativeImages_v4.0.30319_64\UIAutomationProvider\202b3ae257e405db5bb3c51d4623986d\UIAutomationProvider.ni.dll",0

**Comment by bao-qian** [comment]
screenshot and log file?
