### ISSUE TITLE
 蓝色条滚动，任何命令没有反应

### ISSUE THREAD

**Issue by Dixeran** [Wox-launcher/Wox#1138]
禁用everything插件后，用快捷键一呼出就下面有个蓝色条滚动，输入什么命令都没有反应。启动everything插件后可以搜索到文件，但是everything没法设置触发关键字，关键字那里是空的。

**Comment by Dixeran** [comment]
把Everything插件目录下的plugin.json屏蔽掉就没有这个问题了，应该是这个插件和别的插件冲突了

**Comment by bao-qian** [comment]
1 log？
2 screenshot？
3 版本？
