### ISSUE TITLE
suggestion for wpm install

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#1140]
Hope there's a way to install plugin from github. 
For example, `wpm install Wox-launcher/Wox.Plugin.Kitty`.

Because now the speed of visiting getwox.com is very slow (at least from where i am), and I think it's convient for for plugin developer

**Comment by bao-qian** [comment]
Ideally all plugin should be hosted on GitHub, getwox should be just for index and cache purpose
