### ISSUE TITLE
每次呼出都未清除上次搜索条件，也未被全选

### ISSUE THREAD

**Issue by DZ9** [Wox-launcher/Wox#1141]
每次呼出都需要手动清除上次的搜索条件，而且未被全选，需要手动全选或逐个删除。
版本1.3.183，使用环境：win10
在以往的issue中作者说呼出后上次的搜索条件会被全选，但是我在该版本下亲测并不会被全选，需要手动逐个删除。
以上是我目前发现wox不太方便的地方，麻烦作者了。

**Comment by iEverX** [comment]
我也是win10，wox也是1.3.183，我的会选中

**Comment by FlyingRadish** [comment]
win10, 同样的情况，每次都要删除很烦

**Comment by nintha** [comment]
我也是win10，但是有一种解决方法：兼容性设置成win7，重启就可以解决了

**Comment by bao-qian** [comment]
暂时办法 #1050 (comment)

**Comment by bao-qian** [comment]
试一下新版， 你应该会需要第二项选项

![image](https://cloud.githubusercontent.com/assets/1169912/22866822/144e2fb6-f174-11e6-9c27-bdd087221372.png)
https://ci.appveyor.com/project/happlebao/wox/build/1.3.344/artifacts

@DZ9 @iEverX @houxg @Nintha @wch352136 @ssjlz4670 @echoonly

**Comment by bao-qian** [comment]
有问题再开
