### ISSUE TITLE
error

### ISSUE THREAD

**Issue by free2pay** [Wox-launcher/Wox#1146]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 12/06/2016 09:21:06
Exception:
Wox.Plugin.Folder
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Folder.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:行号 40
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 25
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 81
   在 System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
[2016-12-06.txt](https://github.com/Wox-launcher/Wox/files/632744/2016-12-06.txt)

**Comment by bao-qian** [comment]
感谢汇报
试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/artifacts 的  `Releases\Wox-1.3.xxx.exe`
或者
删除 `%APPDATA%\Wox`，删前记得备份
