### ISSUE TITLE
Program插件 - 快捷方式图标不显示

### ISSUE THREAD

**Issue by ooknight** [Wox-launcher/Wox#1147]
1. Wox 版本 ：1.3.183
2. 如何**重现** bug：
    Program插件添加文件夹，文件夹中都是快捷方式，关闭再启动wox后，快捷方式图标不显示
3. Windows 版本：
    win7sp1
    Microsoft .NET Framework 4.6.1
    Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030
    Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
    Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215
    Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215
4. Exception：
5. **整个** log 文件 ：
[2016-12-06.txt](https://github.com/Wox-launcher/Wox/files/633088/2016-12-06.txt)

6. 截图 （可选）：
![2016-12-06_140928](https://cloud.githubusercontent.com/assets/5999599/20915153/02878010-bbbf-11e6-95d4-1c2e496610e8.png)
![2016-12-06_140959](https://cloud.githubusercontent.com/assets/5999599/20915154/05c47602-bbbf-11e6-89d9-5b210c4b18a9.png)

**Comment by bao-qian** [comment]
把 cache `%AppData%\Roaming\Wox\Cache` 删了
