### ISSUE TITLE
设置插件触发关键字为空白后无法再设置触发关键字

### ISSUE THREAD

**Issue by xueyawei** [Wox-launcher/Wox#1149]
点了*设置触发关键字为空白后，再也无法设置触发关键字。卸载重装也不行

![image](https://cloud.githubusercontent.com/assets/15012008/21005370/8f73b810-bd02-11e6-8eee-e82f14fc20c0.png)
之前设置关键字的地方已经没有了

Add: 因为这个触发关键字的原因，好多功能无法使用
比如我现在输入setting ，设置没有了。
![image](https://cloud.githubusercontent.com/assets/15012008/21007814/912eca3c-bd0c-11e6-8a35-79f3217e5024.png)

但是如果我用wpm卸载了“程序”插件，就可以出来了
![image](https://cloud.githubusercontent.com/assets/15012008/21007851/d16c2b8a-bd0c-11e6-83d5-28e4be3376ab.png)

ps:卸载后重新安装没有用，关键字还是空白。难道有什么配置文件没被卸载吗？ 我怎么找到配置文件并编辑这个关键字的设置？

**Comment by xueyawei** [comment]
问题表面上解决了，但还是希望修复一下。
Solution:
打开文件：C:\Users\你的用户名\AppData\Roaming\Wox\Settings\Settings.json
这个就是配置文件，修改json里的设置即可

**Comment by ghost** [comment]
我把Wox插件管理的触发关键词设置为NULL，就修改不了了，不知道其他插件是不是也这样。和这个一样的问题。

**Comment by ghost** [comment]
wpm不能用了很麻烦的

**Comment by bao-qian** [comment]
> Solution:
打开文件：C:\Users\你的用户名\AppData\Roaming\Wox\Settings\Settings.json
这个就是配置文件，修改json里的设置即可

**Comment by ghost** [comment]
好吧，我完全删除重装的。我研究一下。

**Comment by ghost** [comment]
建议你把这个写到帮助文档里，设置文件在 `C:\Users\你的用户名\AppData\Roaming\Wox\Settings\Settings.json`

**Comment by bao-qian** [comment]
之前有的
被删掉了
https://github.com/Wox-launcher/Wox/wiki#faq
