### ISSUE TITLE
some how avoid duplicates

### ISSUE THREAD

**Issue by thecotne** [Wox-launcher/Wox#115]
![screen](http://i.imgur.com/YrwIs3W.png)
![screen](http://i.imgur.com/DCdgCna.png)

**Comment by roose** [comment]
In Settings page disable "AppPathsProgramSource" in "Programs" plugin

**Comment by thecotne** [comment]
why we need AppPathsProgramSource at all?

**Comment by roose** [comment]
@thecotne some programs may not create shortcuts in start menu

**Comment by thecotne** [comment]
@roose so can't we scan for duplicates 
so i can search for programs witch does not have shortcut in start menu and also don't have duplicates

**Comment by aaroncampf** [comment]
What logic would we use to determine which shortcut is correct?
Would you want us to just use the first shortcut it finds?

**Comment by thecotne** [comment]
if we have multiple shortcuts of one file and that file it self
we must display only one from them one which better Matchs search query

**Comment by aaroncampf** [comment]
What if they have different names but the same target?

**Comment by thecotne** [comment]
display one which better matches search query

if some one thinks it's wrong behavior make it optional

**Comment by aaroncampf** [comment]
Here is my question

How do we define duplicates:
1. Matching Name
2. Matching Target
3. Matching Name & Target
4. Something Else

**Comment by thecotne** [comment]
Matching Target 
name can be different as example 
"chrome.exe" and "google chrome"

**Comment by byzeus2014** [comment]
This is a helpful suggestion.

**Comment by vovkkk** [comment]
In addition, it would be helpful to have some general exclude rules based on regex/wildcards or/and folder, e.g. I’m not interested to see `*uninstall*.lnk` files from Start Menu.

**Comment by jeroendv** [comment]
this is more then a suggestion, it would effectively more then double the signal to noise ratio of the query results.

in general almost all app installations have a tendency to install more then one link in the start menu. So  for every program there are often 3 hits: the exe, the start menu *.lnk to the exe, the uninstall.lnk.

Only the first (or debatably the second) is useful, while the others are plain noise that the user needs to manually filter.

**Comment by bao-qian** [comment]
please try new release
https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196

let me know if it fix or not.
