### ISSUE TITLE
关于电脑重启wox无法正常使用的问题

### ISSUE THREAD

**Issue by jinpeng15800** [Wox-launcher/Wox#1150]
## Known problems for 1.3.183:

如果我新安装1.3.183，所有的都很正常，很好用。但是我重启电脑之后，再打开之后（已开启everything），就会有问题：输入关键词之后 ， 不会出现搜索结果。。无论是搜索file还是exe。。等待很长时间之后查出来的结果也不会很准确。
我的电脑是win10

**Comment by jinpeng15800** [comment]
@happlebao  I translate to english : when I restart my win 10 PC ,I cannot use wox (1.3.183) as usual .when I input the keyword ,it will not show the result quickly (1or2 mins) ，after wait long , the result also not correct like before(when I just install the wox)  .so I had to  reinstall the wox  and it goes right ..

**Comment by bao-qian** [comment]
你重装后一起正常是吗？那就可以关了？
