### ISSUE TITLE
Wox.Plugin.WebSearch.SearchSourceSettingWindow System.NullReferenceException 

### ISSUE THREAD

**Issue by ssPARTRICKss** [Wox-launcher/Wox#1151]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 12/09/2016 17:34:23
Exception:
Wox.Plugin.WebSearch
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.WebSearch.SearchSourceSettingWindow..ctor(IList`1 sources, PluginInitContext context, SearchSource old) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\SearchSourceSetting.xaml.cs:行号 23
   在 Wox.Plugin.WebSearch.SettingsControl.OnEditSearchSourceClick(Object sender, RoutedEventArgs e) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\SettingsControl.xaml.cs:行号 47
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

**Comment by bao-qian** [comment]
试一下新版
https://ci.appveyor.com/project/happlebao/wox/build/1.3.340

**Comment by bao-qian** [comment]
还是有问题再开
