### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by waltleaf** [Wox-launcher/Wox#1157]
1、Wox启动后会自动创建桌面快捷方式，有流浪软件的嫌疑
2、插件删除很麻烦。插件管理模块没有删除功能，只能去删文件夹，但是程序运行期间文件夹不能删除，有文件被占用，即使退出程序一样提示文件被占用，所以要先设置不开机自启动，然后重启电脑，删除文件夹，再打开程序才能用。

我的系统：
操作系统名称	Microsoft Windows 10 专业版
版本	10.0.14393 版本 14393

Wox版本：1.3.183

**Comment by lances101** [comment]
You should use `wpm uninstall` to delete plugins. That will actually exit Wox before uninstalling the plugin therefore you would not have any issue with it being in use. 

[Please take a look here](https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Plugins)
