### ISSUE TITLE
Ver 1.3.312 启动和搜索缓慢，内存占用过高

### ISSUE THREAD

**Issue by zlphoenix** [Wox-launcher/Wox#1158]
1. Wox 版本 / commit number：1.3.312
2. 如何**重现** bug：启动 Wox后随输入任何信息，内存和CPU占用迅速上涨
3. Windows 版本：Win 10.0.14393
4. Exception：无
5. **整个** log 文件[2016-12-16.txt](https://github.com/Wox-launcher/Wox/files/656270/2016-12-16.txt)
6. 截图 （可选）：
![image](https://cloud.githubusercontent.com/assets/1305437/21249487/60985410-c379-11e6-9514-86a8c3c5abcb.png)
![image](https://cloud.githubusercontent.com/assets/1305437/21249495/6d93febc-c379-11e6-843b-cdc56d4c8d18.png)

**Comment by lances101** [comment]
Duplicate. Please take a look at #1017
