### ISSUE TITLE
Wox.ViewModel.SettingWindowViewModel System.NullReferenceException 

### ISSUE THREAD

**Issue by bineyond** [Wox-launcher/Wox#1159]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 12/17/2016 15:21:56
Exception:
Wox
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.ViewModel.SettingWindowViewModel..ctor() 位置 C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:行号 28
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 44
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[Uploading 2016-12-17.txt…]()

**Comment by MoeHero** [comment]
我也出现了类似问题 看起来是设置出了问题？
我把C:\Users\用户名\AppData\Roaming\Wox这个文件夹整个删除就ok了
不过设置都初始化了

**Comment by songjhh** [comment]
Me too
每次开机都这样 删除完后就好了 再开机又不行了

**Comment by bao-qian** [comment]
试一下新版
https://ci.appveyor.com/project/happlebao/wox/build/1.3.340

**Comment by bao-qian** [comment]
还是有问题再开
