### ISSUE TITLE
highlight how it matched

### ISSUE THREAD

**Issue by thecotne** [Wox-launcher/Wox#116]
![screen](http://i.imgur.com/2i8Eco3.png)

how paint is related to AIMP3 audio converter 
i guess its AIM<b>P</b>3 <b>a</b>ud<b>i</b>o co<b>n</b>ver<b>t</b>er 
so highlight would be nice

**Comment by bao-qian** [comment]
hi @thecotne 
this feature has been implemented in https://github.com/Wox-launcher/Wox/pull/2817
check new release
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735
