### ISSUE TITLE
wox got an error !

### ISSUE THREAD

**Issue by moeinrahimi** [Wox-launcher/Wox#1164]
hi
when i try to open wox this error message pops up, also i attachedd the log file .

👍 Wox version: 1.3.183OS Version: Microsoft Windows NT 10.0.10240.0Date: 12/28/2016 21:01:28Exception:Wox.Plugin.ProgramSystem.NullReferenceExceptionObject reference not set to an instance of an object.   at Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 136   at Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:line 102   at Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 27   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 96   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2016-12-28.txt](https://github.com/Wox-launcher/Wox/files/676133/2016-12-28.txt)

**Comment by lances101** [comment]
[Please try this build and report back](https://ci.appveyor.com/api/buildjobs/m1hh02lv6mrvo900/artifacts/Releases%2FWox-1.3.323.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).
