### ISSUE TITLE
[Bug] right click menu not closing correctly with "Hide Wox when focus is lost"

### ISSUE THREAD

**Issue by stephtr** [Wox-launcher/Wox#1166]
1. Wox version: 1.3.183
2. Steps to **reproduce** the bug:
    Activate "Hide Wox when focus is lost"
    Right click an item in the search result list (Set as topmost, run as admin get shown)
    Close Wox by clicking outside
    Reopen Wox
    -> Wox still displays the submenu list (Set as topmost, run as admin) and not the main menu.
3. Windows version: Windows 10 14986
4. Exception: none
5. **whole** log file: no entry
6. Screenshot

**Comment by nrllh** [comment]
You have to right click once, then it will be closed =)

**Comment by stephtr** [comment]
I know, but I thought it would be more intuitive/usefull if that wasn't necessary.

**Comment by lances101** [comment]
I agree with you that it is counter intuitive, because you do not expect the contextual menu to be there once you select a result from it. This is a small fix that could be theoretically done before the next release.
