### ISSUE TITLE
Wox 1.3.67 startup error

### ISSUE THREAD

**Issue by toby524** [Wox-launcher/Wox#1168]
Wox version: 1.3.67 OS Version: Microsoft Windows NT 10.0.14393.0 Date: 01/01/2017 09:21:18 Exception: Wox System.NullReferenceException 未将对象引用设置到对象的实例。    在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48    在 System.Windows.Application.OnStartup(StartupEventArgs e)    在 System.Windows.Application.<.ctor>b__1_0(Object unused)    在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)    在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
1.3.67 is not supported anymore. Please download either 1.3.183 from the downloads section or a [dev build from Appveyor.](https://ci.appveyor.com/api/buildjobs/m1hh02lv6mrvo900/artifacts/Releases%2FWox-1.3.323.exe)
