### ISSUE TITLE
can't search for system things like "device manager" and "uninstall a program"

### ISSUE THREAD

**Issue by thecotne** [Wox-launcher/Wox#117]

**Comment by roose** [comment]
@thecotne https://github.com/coenraads/wox.plugin.controlpanel/releases, change extention to *.zip and unzip in plugins folder
@qianlifeng http://www.getwox.com/plugin/detail/6aaa585159a34f969d091109f5fd1e56 wrong download link, "download plugin control panel failed" install error in wox wpm

**Comment by thecotne** [comment]
@roose Does not work

and what does wox file extension?

**Comment by roose** [comment]
@thecotne keyword "cp", e.g. "cp device manager", in settings page you see "Control Panel" plugin?
*.wox file for Wox Plugin Management(wpm), for install plugins

**Comment by thecotne** [comment]
i can't install Wox.Plugin.ControlPanel
i tried change extention to *.zip and unzip in plugins folder
also tried wpm install Control Panel
does not work

also i think cp prefix for control panel things is not good idea it must be Smart enough to search without prefix (or keyword what ever)

**Comment by roose** [comment]
need restart wox after unpacking plugin

**Comment by thecotne** [comment]
i restarted wox but it does not work
i have windows 8.1

bookmark search and wpm also does not work

**Comment by roose** [comment]
hm, i also have windows 8.1, all works, bookmarks on "b" keyword, control panel on "cp", may be @qianlifeng helps you

**Comment by qianlifeng** [comment]
@roose [http://www.getwox.com/plugin/detail/6aaa585159a34f969d091109f5fd1e56](http://www.getwox.com/plugin/detail/6aaa585159a34f969d091109f5fd1e56) now synced to the latest release.  
I'm writing the new getwox.com website, by then user can upload plugins/theme to getwox.com instead of publish release in github.

**Comment by qianlifeng** [comment]
@thecotne what's version did you use?

**Comment by qianlifeng** [comment]
@CoenraadS It's sounds that we can merge your control panel into Wox system plugins. 
But I'm wondering if there is some way to get the control panel items dynamically instead of hard-code items title in code. Because the control panel title is different in other countries. It will be better to get the local control panel item dynamically, so that user can search them using their familiar language.

**Comment by russelg** [comment]
@qianlifeng http://sourceforge.net/p/launchy/code/HEAD/tree/trunk/Launchy_QT/plugins/controly/
This is how Launchy finds them, maybe this can ported to C# and used?

**Comment by CoenraadS** [comment]
@qianlifeng 

I have a work in progress dynamic control panel here: (no idea how its acts in languages other then English though..)
https://github.com/CoenraadS/Wox.Plugin.ControlPanelX

It includes an older .dll that uses low quality icons.

The .dll is being developed here, but currently I'm revamping the Icon extraction method, and everything is broken :+1: 
https://github.com/CoenraadS/Windows-Control-Panel-Items

Having some troubles with it loading the default icon using LoadImage() though, can't seem to find a solution either, so no eta..

**Comment by qianlifeng** [comment]
@CoenraadS I have tried the new ControlPanelX plugin. It works perfect in languages other then English, and returns local language of control panel items :+1: 
Could you merge this into Wox system plugin after you find the solution about loadimage? You can send a pull request or I I can add you to contributor if you would like to contribute Wox more.

**Comment by thecotne** [comment]
@qianlifeng there is only one version in https://github.com/qianlifeng/Wox/releases
so i have that

also i will make some plugins and i think tags in github repo is best for plugin versions 
like package control in sublime text

also i recommend use http://chocolatey.org/ so its easy to install 
and i recommend make wox protocol in windows and install plugins from browser 
how to register url handler (protocol) http://msdn.microsoft.com/en-us/library/ie/aa767914(v=vs.85).aspx

**Comment by qianlifeng** [comment]
@thecotne Do you have any logs in the log.txt inside wox directory, it's hard to find issues beforeI get some useful info.

I'm making the new getwox.com to support plugin/theme upload and share. something like [http://www.packal.org/](http://www.packal.org/). With new website, we can do more plugin check when uploading(E.g user must provide an icon and preview image for your plugin).

wox protocol is a good idea, I will see if we can make that happen.

**Comment by CoenraadS** [comment]
@qianlifeng

[Wox.Plugin.ControlPanelX](https://github.com/CoenraadS/Wox.Plugin.ControlPanelX/releases) is released.

Feel free to test it out. I'm going to look into how I can perhaps publish the .dll on Nuget before I try to integrate it into Wox.

**Comment by orzFly** [comment]
@CoenraadS In many aspects I hope you could directly combine your code into the Wox instead of a separated assembly WindowsControlPanelItems.

**Comment by CoenraadS** [comment]
@orzFly 
https://github.com/qianlifeng/Wox/pull/119

**Comment by thecotne** [comment]
```
Date:2014-07-16 21:51:28,766 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-16 21:51:29,316 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-16 21:51:29,319 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:08:18,129 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 00:08:18,381 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:08:18,384 Level:ERROR Msg:Couldn't load plugin Control Panel: Could not load file or assembly 'Wox.Plugin.ControlPanel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:08:18,388 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:11:50,787 Level:WARN  Msg:Parse plugin config C:\Users\cotne_000\Desktop\Wox.1.0.0.162-beta\Plugins\Wox.Plugin.ControlPanel-1.1\plugin.json failed: ExecuteFile C:\Users\cotne_000\Desktop\Wox.1.0.0.162-beta\Plugins\Wox.Plugin.ControlPanel-1.1\Wox.Plugin.ControlPanel.dll didn't exist
Date:2014-07-17 00:11:50,828 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 00:11:51,023 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:11:51,026 Level:ERROR Msg:Couldn't load plugin Control Panel: Could not load file or assembly 'Wox.Plugin.ControlPanel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:11:51,030 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:45:27,722 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 00:45:27,938 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:45:27,942 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:47:24,331 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 00:47:24,554 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 00:47:24,558 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 01:22:32,565 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 01:22:32,773 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 01:22:32,775 Level:ERROR Msg:Couldn't load plugin Control Panel: Could not load file or assembly 'Wox.Plugin.ControlPanel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 01:22:32,779 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 03:42:14,067 Level:WARN  Msg:Could't find python environment, all python plugins disabled.
Date:2014-07-17 03:42:14,304 Level:ERROR Msg:Couldn't load plugin Browser Bookmarks: Could not load file or assembly 'Wox.Plugin.BrowserBookmark, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 03:42:14,307 Level:ERROR Msg:Couldn't load plugin Control Panel: Could not load file or assembly 'Wox.Plugin.ControlPanel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
Date:2014-07-17 03:42:14,311 Level:ERROR Msg:Couldn't load plugin Wox Plugin Management: Could not load file or assembly 'Wox.Plugin.PluginManagement, Version=1.0.0.162, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
```

so problem is i have not installed python 
it must be packed with wox i think

**Comment by thecotne** [comment]
i installed python 3.4 makes no difference

**Comment by qianlifeng** [comment]
@thecotne try this solution: [http://stackoverflow.com/questions/3007190/vsts-2010-sgen-error-could-not-load-file-or-assembly-exception-from-hresult](http://stackoverflow.com/questions/3007190/vsts-2010-sgen-error-could-not-load-file-or-assembly-exception-from-hresult)

**Comment by thecotne** [comment]
```
I was able to fix this error by finding the assembly DLL in Windows Explorer, 
right clicking, Properties, and then pressing the "unblock" button. 
The DLL has a stream that is marking it as an 
external file - and by clicking unblock you remove that designation.
```

@qianlifeng what is assembly DLL?

**Comment by qianlifeng** [comment]
*.dll in Wox plugin directory 
E.g `<Wox Directory>\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll`

**Comment by thecotne** [comment]
now it works and how to avoid that ?
how other portable programs work without that?

**Comment by qianlifeng** [comment]
@thecotne Can't figure out why it happened in your computer, we will look at this if any others also this kind of issues.  
I'm closing this issue since control panel plugin has been migrated.
