### ISSUE TITLE
Wox窗口位置自动复位

### ISSUE THREAD

**Issue by wutangyibo** [Wox-launcher/Wox#1172]
提个建议：
增加一个Wox是否自动复位的选项。
问题：
把Wox窗口位置移动后，再重新键入字符，Wox窗口就自动回到屏幕中间的位置。对于非透明的主题，有时就会挡住屏幕的其它内容，这个有点影响体验。

**Comment by lances101** [comment]
Confirmed. The window will still jump around while typing even if the option to remember last launch position is set.

**Comment by Vanav** [comment]
Possible duplicate of #823.

**Comment by happlebao** [comment]
duplicate #823

**Comment by bao-qian** [comment]
@wutangyibo @lances101 @Vanav 
try new build https://ci.appveyor.com/project/happlebao/wox/build/1.3.352/artifacts

**Comment by bao-qian** [comment]
reopen if issue still exist
