### ISSUE TITLE
Error "Everything Service is not running" if Everything service is running, but Everything UI is not running

### ISSUE THREAD

**Issue by Vanav** [Wox-launcher/Wox#1176]
1. Wox version / commit number: 
Wox v1.3.183 and v1.3.324.
Everything v1.3.4.686.x64 and v1.4.1.809b.x64
2. Steps to **reproduce** the bug:
Everything service is running (C:\Program Files\Everything\Everything.exe -svc), Everything UI is not running.
Wox shows error: "Everything Service is not running".
If I start Everything UI, then error disappears.
3. Windows version:
Windows 10 x64.
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
2017-01-04 23:31:19.5323|INFO|Wox.Plugin.Program.Main.Init|Preload 161 programs from cache
2017-01-04 23:31:19.6205|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
2017-01-04 23:31:21.4278|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2017-01-04 23:31:21.4383|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|Ошибка в приложении.
2017-01-04 23:31:21.4383|ERROR|Wox.Plugin.Everything.Everything.EverythingAPI+<Search>d__43.MoveNext|
   в Wox.Plugin.Everything.Everything.EverythingAPI.<Search>d__43.MoveNext() в C:\projects\wox\Plugins\Wox.Plugin.Everything\Everything\EverythingAPI.cs:строка 222

**Comment by anilpalepu** [comment]
I had the similar issue when Wox was installed. So i installed Everything 64 bit again from downloads since my PC was 64bit (Everything-1.3.4.686.x64-Setup.exe) and after that Everything was running fine. Maybe its not the same issue but thought i would post what got it working for me.

**Comment by Vanav** [comment]
I have this issue with distributions from official Everything site. Have not tried attached to Wox version.

**Comment by lances101** [comment]
If you are still running into issues with Everything search not being available through Wox, try going into the actual settings window of Everything and setting it to run as a service there. After that try restarting Everything and Wox.

**Comment by Vanav** [comment]
Everything UI must also be running, not only Everything service?

**Comment by lances101** [comment]
Just make sure you don't "exit" Everything and just close the window instead. If you are quitting it by clicking `File -> Exit` it actually stops the service too.

**Comment by Vanav** [comment]
I exit from tray icon, but service is running. I thought that running service should be enough?

**Comment by lances101** [comment]
We use the official library for integrating with Everything, but apparently, yes, you are right, if the GUI is not running it does not get detected by the library. 

**Edit:** this is a bug, but I don't see a straightforward way of fixing it right now.

**Comment by gtassara** [comment]
any news on this topic? i still have the same problem

**Comment by thdoan** [comment]
I hope there is some way to fix this soon because the Everything UI consumes a lot of memory (73MB) compared to the service (0.8MB):

![image](https://user-images.githubusercontent.com/4110567/30953702-e30aa58a-a3e1-11e7-8e29-c5ea3ad02fa3.png)

Wox seems to function just fine even if you quit the UI, so I just ignore the warning.

**Comment by stereokai** [comment]
How can I check that Everything service is even loading? Because I can't see it in Task Manager

**Comment by lusky3** [comment]
Any chance of this getting resolved on the roadmap? I see this issue has been open for almost a year now.

@stereokai If it's not running under Task Manager > Services, you might want to check services.msc

**Comment by vincegiordano** [comment]
This works if you install Everything Search Engine (64-bit)

[(https://www.filehorse.com/download-everything-64/)](url)

**Comment by madrulane** [comment]
> This works if you install Everything Search Engine (64-bit)
> 
> [(https://www.filehorse.com/download-everything-64/)](url)

No it doesn't. I have it installed (the last version), the Service is running (under services) and VOX says that it's not running.

**Comment by korirdennis** [comment]
> I had the similar issue when Wox was installed. So i installed Everything 64 bit again from downloads since my PC was 64bit (Everything-1.3.4.686.x64-Setup.exe) and after that Everything was running fine. Maybe its not the same issue but thought i would post what got it working for me.

I had a similar issue but got it working by adding the part to where python is installed 
![image](https://user-images.githubusercontent.com/38191858/81219293-47529300-8fe8-11ea-90a4-03915c7af1bd.png)

**Comment by bao-qian** [comment]
the info is misleading, both everything service and everything client need running.
if you don't want everything client ui running, please use Everything Client Service 
http://voidtools.com/forum/viewtopic.php?f=2&t=1982

@Vanav @anilpalepu @thdoan  @mardulas @ChaosZero112

please let me know if you still have issue.
