### ISSUE TITLE
Build & Deployment Instructions

### ISSUE THREAD

**Issue by tylervick** [Wox-launcher/Wox#1178]
I was wondering if there is any more clear documentation for building & deploying the project? Loading it up in Visual Studio (2015) requires UWP references to be added.

Additionally - How would I package the release into a single .exe? I'm not seeing any deployment configuration in the VS Solution.

Any help would be greatly appreciated!

**Comment by lances101** [comment]
You need to install the Windows 10 SDK to be able to compile Wox successfully. The package that links that UWP libraries to C# should get installed automatically by NuGet. The other option is to unload the "Program" plugin so that you can compile without it (if that is viable to you).

**Comment by bao-qian** [comment]
deployment is complex, see script here https://github.com/Wox-launcher/Wox/tree/master/Deploy
appveyor should auto build a exe if you open a pr

**Comment by bao-qian** [comment]
updated local package script:
https://github.com/Wox-launcher/Wox/blob/master/Deploy/local_build.ps1
run this after your build in visual studio
