### ISSUE TITLE
[Question] Launch portable applications

### ISSUE THREAD

**Issue by Kristinita** [Wox-launcher/Wox#1179]
### 1. Briefly

It would be possible launch portable applications like installed?

### 2. Detail

For example, I have installed version of Google Chrome browser. <kbd>Alt+Space</kbd> → I can run Chrome via Wox:

![Chrome](http://i.imgur.com/emtR68T.png)

And I have Opera portable. I can not run Opera via Wox:

![Opera](http://i.imgur.com/gUDr5zH.png)

I install programs use [**Chocolatey**](https://chocolatey.org/) — package manager for Windows. I don't want install applications use [**PortableApps**](http://portableapps.com/download) or other special launchers for portable programs, because via Chocolatey I can update all my programs (more than 150) automatically.

For example, in ``E:\Chocolatey\bin`` folder I have many ``.exe`` applications.

![Chocolatey applications](http://i349.photobucket.com/albums/q393/Sasha_Chernykh/Big_Images/explorer_2017-01-07_15-55-29_zpsxi1gs1or.png)

Can I somehow launch all these applications via Wox?

### 3. Did not help

1. <kbd>Right_Click</kbd> to Wox tray icon → `Settings` → `Plugin` → `Programs` → I click `Index File Suffixes` and `Reindex` → but it not solved my problem.
2. Also, I don't find Wox plugin for my task.

Thanks.

**Comment by lances101** [comment]
You can achieve this with the "Program" plugin, but you need to add the directory where your portable applications are located first. You can do that through the settings pane of the "Program" plugin (the same one where you pressed the reindex button). Wox will then scan recursively that folder for all executables and shortcuts it can find. 

![opera](https://cloud.githubusercontent.com/assets/4784785/21787098/950ad4aa-d6c7-11e6-8b47-0f4aaa25cb2a.PNG)

**Comment by Kristinita** [comment]
@lances101 , thank you very much!
