### ISSUE TITLE
网页搜索触发关键字出错

### ISSUE THREAD

**Issue by Herryyang** [Wox-launcher/Wox#1180]
我在网页搜索添加了新的触发关键字，电脑重启后，添加的触发关键字和url没了，但当我重新添加的时候又提示这些关键字已经指派给其他的命令了

**Comment by bao-qian** [comment]
感谢汇报
试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/artifacts 的  `Releases\Wox-1.3.xxx.exe`
