### ISSUE TITLE
希望不要保留上次的搜索关键字

### ISSUE THREAD

**Issue by wch352136** [Wox-launcher/Wox#1181]
例如我打开Wox搜索了qq，下次我打开Wox想要搜索其他东西的时候发现搜索的关键字依然是qq"并且"结果依然全部列出。这种类似保留历史记录的东西希望能去掉（或者在设置里能有选项可以关掉），原因如下：
1.Wox是个高频次使用的软件，但是连续两次搜索同一个关键字是个小概率的事件，这个东西除了每次让人多按一次删除按钮，应该没有什么其他意义。
2.隐私，例如你上次通过Wox搜索了什么较隐私的东西（照片啦，日记啦，不可描述啦），然后其他人无意间（不可能保证你的电脑永远只是你自己用）再次打开Wox就会发现你上次搜索的内容，选择的哪一项，具体目录结构，这种有可能泄露一些隐私的体验，总不是那么好。
希望开发者，能适当考虑一下这个建议

**Comment by cofedream** [comment]
同意，因为这点，我还是依旧在使用ALMRun，虽然这个更新也是很久前...

**Comment by echoonly** [comment]
支持,  最好还是有设置项确定是否要保留, 而且即使保留的话也希望再次打开时是把之前的输入全选的状态,  这样如果选择直接输入, 就会抹掉之前的内容

**Comment by iEverX** [comment]
1.3.183版本, 上一次的输入是全选状态

**Comment by bao-qian** [comment]
暂时办法 #1050 (comment)

**Comment by bao-qian** [comment]
重复 #1141
