### ISSUE TITLE
wox启动报错

### ISSUE THREAD

**Issue by Dixeran** [Wox-launcher/Wox#1183]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 01/10/2017 22:18:03
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Error parsing positive infinity value. Path '', line 1, position 1.
   在 Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity()
   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 58
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Load() 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 40
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 63
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 49
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Dixeran** [comment]
删除roming里面的文件以后解决了

**Comment by Herryyang** [comment]
谢谢，我也刚遇到这个问题

**Comment by ghost** [comment]
any updates here? i also have the exact error.

**Comment by Dixeran** [comment]
Try to delete the folder where
```
C:\Users\lenovo\AppData\Roaming\Wox
```
then the programme will reset.

**Comment by Dixeran** [comment]
Try to delete the folder where
```
C:\Users\[Your user name]\AppData\Roaming\Wox
```
then the programme will be reseted.
