### ISSUE TITLE
指令没有响应

### ISSUE THREAD

**Issue by ltd920678778** [Wox-launcher/Wox#1187]
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：唤起主窗口, 键入指令
3. Windows 版本：windows 10 15002
4. Exception：唤起主窗口后键入设定好的指令, 没有反应, 重建索引页没用.
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）:
[2017-01-13.txt](https://github.com/Wox-launcher/Wox/files/703286/2017-01-13.txt)

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份
