### ISSUE TITLE
blurry in settings

### ISSUE THREAD

**Issue by gonik** [Wox-launcher/Wox#1190]
First of all, i'd like to say that this is a wonderful piece of software. Keep up the good work!

Secondly, I have two issues

1) When i'm trying to run shell commands:
I press `>` as intended, and startt typing the command e.g. `ipconfig`

![wox1](https://cloud.githubusercontent.com/assets/603308/21920952/221ccf86-d96d-11e6-81af-9225dc734d29.png)

As you can see in the screenshot above, no results are returned, and if I press enter nothing is done. This applies not only to `ipconfig` but to all commands.

2) Opening the Settings window:
When I right click the taskbar icon and click `Settings` then I get following wierd appearance:
![wox2](https://cloud.githubusercontent.com/assets/603308/21921106/599a06b2-d96e-11e6-9909-8d9428e4efe9.png)

As you can see there is a blurry "overlay" which disapears when i click anywhere on the screen.
This does not appear when I launch Settings, by typing `settings` in the main Wox window.

![Wox Settings](https://camo.githubusercontent.com/418b3802174625a48e032bc2a4a929e369061dcb/687474703a2f2f696d6775722e636f6d2f56554673724c752e706e67)

Wox version: 1.3.183
Windows version: Win 10 version 1607 (OS Build 14393.693)
Log file: [2017-01-12.txt](https://github.com/Wox-launcher/Wox/files/703685/2017-01-12.txt)

**Comment by rogino** [comment]
I am running the same version, and shell commands work if I first press space: >ipconfig does not work, but > ipconfig and other commands do work

**Comment by gonik** [comment]
Thank you rogino, indeed you are correct! I don't know why i haven't thought earlier, to press space after the ">" character...

Now remains only the second bug (with the blurry overlay)

**Comment by bao-qian** [comment]
duplicate #711

**Comment by bao-qian** [comment]
try new build https://ci.appveyor.com/project/happlebao/wox/build/1.3.346/artifacts
