### ISSUE TITLE
一个建议：添加“取消鼠标选中”的选项 | Do not change selected result on mouseover

### ISSUE THREAD

**Issue by jinpeng15800** [Wox-launcher/Wox#1193]
@happlebao  一个小建议，希望在选项中添加一个选项可以取消鼠标对搜索结果的选中，比如我的搜索结果在第一位，但是因为鼠标刚好放在后面几位的结果上，点回车就变成了鼠标选择的那个，会有一定干扰，或者可以做成只有在鼠标移动时才会被选中也可以

**Comment by jinpeng15800** [comment]
A small proposal, in the hope that the option to add an option to cancel the mouse on the search results selected, such as my search results in the first place, but because the mouse just on the back of a few results  Enter into a Mouse selection, there will be some interference, or can be made only when the mouse moves will be selected can also be

**Comment by JKiddGBY** [comment]
我也希望有这个功能，或者至少在我没有移动鼠标的时候，不要根据光标位置来选中项目。
不然很容易误操作，按回车之前还得注意鼠标的位置。。

**Comment by linyubin** [comment]
second it

**Comment by rosuH** [comment]
Same resquest.
- - - 
同样觉得需要鼠标穿透。很多时候都会选错。

**Comment by Nigh** [comment]
request +1.

ps. 经常因为鼠标误选，很麻烦。

**Comment by CrazyCoder** [comment]
A quick fix is to comment out [this line](https://github.com/Wox-launcher/Wox/blob/master/Wox/ResultListBox.xaml.cs#L25) or change `true` to `false`.

**Comment by michaldvorak79** [comment]
+1
Open Wox.
Enter a command you entered a thousand times before.
See some random application open, because the mouse cursor was at the wrong place at the wrong time.
So incredibly annoying.

**Comment by michaldvorak79** [comment]
+1. This issue is still rather annoying.

**Comment by qianlifeng** [comment]
This has been fixed in v2
