### ISSUE TITLE
Too much cpu usage on Windows

### ISSUE THREAD

**Issue by gerroon** [Wox-launcher/Wox#1197]
Hi

I see that Wox is constantly active (or almost constantly every couple seconds at least). It is using somewhere between 2 to 4 percent of cpu when it is in the background. Now this might not be much for a desktop user but it is a crucial issue for mobile laptop users considering that this app runs in the background constantly.

I am using it on Win10 x64  v1.3.183

**Comment by bao-qian** [comment]
won't investigate in the near future, so issue will be closed.
