### ISSUE TITLE
FR: Fire and forget

### ISSUE THREAD

**Issue by gerroon** [Wox-launcher/Wox#1198]
Hi

Currently Wox remembers the last command firef next time it is open. This sucks because I have to erase the line to retype a new command. It would be nice to have an option to disable it.

thanks

**Comment by wrgrant** [comment]
I agree! Previous versions did not have this behavior.

Please revert to giving a fresh window whenever it is closed by losing focus, pressing ESC, or a firing a command :)

**Comment by ghost** [comment]
is the text not highlighted when you open it again? or is this just happening in a newer version of wox? im using v1.3.183 and the text is always highlighted

**Comment by wrgrant** [comment]
Yes, text is not highlighted for me on Win 10 and v1.3.183, forcing to delete text manually before typing again.

I downgraded to previous 1.3.67 and it is highlighted whenever I launch Wox via hotkey.

**Comment by ghost** [comment]
im on windows 10 as well. strange

**Comment by bao-qian** [comment]
seems repeated #1050 
check workaround https://github.com/Wox-launcher/Wox/issues/1050#issuecomment-269366751
