### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by weison620** [Wox-launcher/Wox#1201]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 01/19/2017 09:36:47
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
工作已取消。
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 於 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs: 行 69
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 於 C:\projects\wox\Wox.Core\Updater.cs: 行 56
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate [catchHandler)]([url](url))
[2017-01-19.txt](https://github.com/Wox-launcher/Wox/files/715500/2017-01-19.txt)

**Comment by bao-qian** [comment]
忽略或者 wox 设置中设置 http 代理
