### ISSUE TITLE
Update Chocolately package

### ISSUE THREAD

**Issue by Daxten** [Wox-launcher/Wox#1205]
https://github.com/ckesc/chocolatey-packages

is unmaintained for some time now, this should get removed so no one installs old packages, or, even better, be updated.

**Comment by bao-qian** [comment]
sorry I have no permission on that repo or package on chocolately

**Comment by ckesc** [comment]
Chocolatey repo maintainer here :)
@bao-qian sorry! It took a while but I updated to v2x. And I am planning to push 2.3.0 this week
Feel free to assigning chocolatey issues to me.

Also maybe we can setup autopublish
