### ISSUE TITLE
Exception in Wox Plugin

### ISSUE THREAD

**Issue by agi96** [Wox-launcher/Wox#1207]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 01/26/2017 16:51:29
Exception:
Wox.Plugin.Program
System.NullReferenceException
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 136.
   bei Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 102.
   bei Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 94.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 27.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 96.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0
(Object )

[2017-01-26.txt](https://github.com/Wox-launcher/Wox/files/732731/2017-01-26.txt)

**Comment by flavius-popan** [comment]
Getting the same error. Please assist.

**Comment by sajidunnar** [comment]
Same Error :)

**Comment by bao-qian** [comment]
try new build 
open https://ci.appveyor.com/project/happlebao/wox/build/artifacts, then download `Releases\Wox-1.3.xxx.exe`
or
delete `%APPDATA%\Wox`, backup before you do that
