### ISSUE TITLE
Some files not indexed.

### ISSUE THREAD

**Issue by CoenraadS** [Wox-launcher/Wox#121]
Hello

Wox returns most results correctly from `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools`

However on my pc I cannot search for `Defragment and Optimize Drives`, `Local Security Policy` or `Windows Memory Diagnostic`

**Comment by orzFly** [comment]
Can you find a "desktop.ini" under that directory? There should be something [LocalizedFileNames] in it...

**Comment by CoenraadS** [comment]
Interesting
`Defragment and Optimize Drives` = `dfrgui`
`Windows Memory Diagnostic` = `Memory Diagnostics Tool`
`Local Security Policy` = `Security Configuration Management`

Guess there is nothing Wox can do about that..
