### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by ToddChae** [Wox-launcher/Wox#1214]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug:
3. Windows version: Window 10 (X64)
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
[Logs.zip](https://github.com/Wox-launcher/Wox/files/750856/Logs.zip)

6. Screenshot (optional): 
![1](https://cloud.githubusercontent.com/assets/25473143/22597154/cad3f7ac-ea71-11e6-957e-28382ebcb0cc.PNG)
![2](https://cloud.githubusercontent.com/assets/25473143/22597155/cafe02d6-ea71-11e6-9325-27b433b2ced2.PNG)

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
try new build
open https://ci.appveyor.com/project/happlebao/wox/build/artifacts, then download Releases\Wox-1.3.xxx.exe
or
delete %APPDATA%\Wox, backup before you do that
