### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by nakulbende** [Wox-launcher/Wox#1221]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/07/2017 10:38:28
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Log file: 

[2017-02-07.txt](https://github.com/Wox-launcher/Wox/files/758164/2017-02-07.txt)

**Comment by bao-qian** [comment]
could you reproduce this issue? like type what command would cause this?

**Comment by nakulbende** [comment]
I was just trying to invoke a search target in websearch plugin

Perhaps it is the culprit? I cant save the changes in icon files with this plugin - I will assign a icon to each search query entry, and the next time Wox starts it forgets everything

**Comment by nakulbende** [comment]
Also, I put this theme in folder, which causes it to immidiately crash if this theme is selected:

<ResourceDictionary  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">     <ResourceDictionary.MergedDictionaries>         <ResourceDictionary Source="Base.xaml"></ResourceDictionary>     </ResourceDictionary.MergedDictionaries>     <Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">         <Setter Property="Background" Value="#3a3a3a"/>         <Setter Property="Foreground" Value="#fb997e" />     </Style>     <Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">         <Setter Property="Background" Value="#252525"></Setter>     </Style>     <Style x:Key="WindowStyle" TargetType="{x:Type Window}" BasedOn="{StaticResource BaseWindowStyle}" >     </Style>     <Style x:Key="PendingLineStyle" BasedOn="{StaticResource BasePendingLineStyle}" TargetType="{x:Type Line}" >     </Style>     <Style x:Key="ItemTitleStyle" BasedOn="{StaticResource BaseItemTitleStyle}" TargetType="{x:Type TextBlock}" >         <Setter Property="Foreground" Value="#6fce76"></Setter>     </Style>     <Style x:Key="ItemSubTitleStyle" BasedOn="{StaticResource BaseItemSubTitleStyle}" TargetType="{x:Type TextBlock}" >         <Setter Property="Foreground"  Value="#7ff17a"></Setter>     </Style>     <Style x:Key="ItemTitleSelectedStyle" BasedOn="{StaticResource BaseItemTitleSelectedStyle}" TargetType="{x:Type TextBlock}">         <Setter Property="Foreground" Value="#06eac9" />     </Style>     <Style x:Key="ItemSubTitleSelectedStyle" BasedOn="{StaticResource BaseItemSubTitleSelectedStyle}" TargetType="{x:Type TextBlock}">         <Setter Property="Foreground" Value="#1fcebf" />     </Style>     <Color x:Key="ItemSelectedBackgroundColor">#5b5b5b</Color>     <Style x:Key="ThumbStyle" BasedOn="{StaticResource BaseThumbStyle}" TargetType="{x:Type Thumb}">     </Style>     <Style x:Key="ScrollBarStyle" BasedOn="{StaticResource BaseScrollBarStyle}" TargetType="{x:Type ScrollBar}">     </Style> </ResourceDictionary>

**Comment by bao-qian** [comment]
those are separate issue,  could you reproduce `System.ArgumentOutOfRangeException`  ?

**Comment by bao-qian** [comment]
duplicate #926 please update relevant info there
