### ISSUE TITLE
WOX Launcher focus problem

### ISSUE THREAD

**Issue by questking** [Wox-launcher/Wox#1222]
Wox wont come back in focus if you click on desktop and then press the hotkeys. Have to manually click on search bar to bring cursor on wox.

I am using alt + space. This that a problem ?

## Known problems for 1.3.183:

1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
can't repeat, and alt+enter should not be the cause.
I'd recommend you record a video

**Comment by mokanfar** [comment]
I have this issue as well but in sublime text when typing something in a text file or when in chrome intermittently, wox fails to be in focus when activated. you have to manually click the bar. I do not see any of those known issue errors in log file that are listed in known problems area.

-  Windows 7 Professional SP1
-  wox 1.3.183

I changed theme still same issue, will try to restart to see if issue goes away if not next step delete appdata and get back to you at a later time. Thank you for making great product

**Comment by bao-qian** [comment]
@mokanfar focus issue has nothing todo with appdata,
try restart machine and install new build https://ci.appveyor.com/project/happlebao/wox/build/1.3.337/artifacts

**Comment by bao-qian** [comment]
@questking please try new build also https://ci.appveyor.com/project/happlebao/wox/build/1.3.337/artifacts

**Comment by bao-qian** [comment]
reopen if problem still exist
