### ISSUE TITLE
please help me fix the problem, thank you very much.

### ISSUE THREAD

**Issue by CoreyZhang** [Wox-launcher/Wox#1223]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\corey\AppData\Roaming\Wox\Logs\1.3.323\2017-02-08.txt
2. copy below exception message
Wox version: 1.3.323
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: C:\Python32\pythonw.exe
Everything SDK Path: C:\Users\corey\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/08/2017 17:56:49
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\corey\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Images\calculator.png”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalDelete(String path, Boolean checkHost)
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 0
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 0
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 0
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a9>d__b7.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:行号 286
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 533
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:行号 49
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 73
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 533
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:行号 169
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-02-08.txt](https://github.com/Wox-launcher/Wox/files/760375/2017-02-08.txt)

**Comment by happlebao** [comment]
although there is no workaround now, but this issue is duplicate: #811

**Comment by bao-qian** [comment]
重启电脑

**Comment by bao-qian** [comment]
有问题再开

**Comment by CoreyZhang** [comment]
还是报错，我台式机没有问题，笔记本用不了

Sent from my iPad

On 15 Feb 2017, at 7:32 PM, happlebao <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1223<https://github.com/Wox-launcher/Wox/issues/1223>.

**Comment by happlebao** [comment]
新的 报错 log

**Comment by bao-qian** [comment]
新的 报错 log

**Comment by CoreyZhang** [comment]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new1. upload log file: C:\Users\corey\AppData\Roaming\Wox\Logs\1.3.323\2017-02-17.txt2. copy below exception message
Wox version: 1.3.323OS Version: Microsoft Windows NT 10.0.14393.0IntPtr Length: 8x64: TruePython Path: C:\Python32\pythonw.exeEverything SDK Path: C:\Users\corey\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dllDate: 02/17/2017 00:52:35Exception:mscorlibSystem.IO.IOException文件“C:\Users\corey\AppData\Local\Wox\app-1.3.183\Images\app_error.png”正由另一进程使用，因此该进程无法访问此文件。   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   在 System.IO.File.InternalDelete(String path, Boolean checkHost)   在 System.Threading.Tasks.Task.Execute()--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 0--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 234--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 342--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a9>d__b7.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:行号 286--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 533--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:行号 49--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 73--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 533--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:行号 169--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56--- 引发异常的上一位置中堆栈跟踪的末尾 ---   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


发件人: happlebao [mailto:notifications@github.com]
发送时间: 2017年2月15日 19:32
收件人: Wox-launcher/Wox <Wox@noreply.github.com>
抄送: CoreyZhang <coreyzhang@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [Wox-launcher/Wox] please help me fix the problem, thank you very much. (#1223)


有问题再开

**Comment by bao-qian** [comment]
重启

**Comment by bao-qian** [comment]
重启电脑

**Comment by CoreyZhang** [comment]
重启不行，不知道原因，才发！

谢谢

发件人: happlebao [mailto:notifications@github.com]
发送时间: 2017年2月17日 1:07
收件人: Wox-launcher/Wox <Wox@noreply.github.com>
抄送: CoreyZhang <coreyzhang@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [Wox-launcher/Wox] please help me fix the problem, thank you very much. (#1223)


重启

**Comment by bao-qian** [comment]
删除 C:\Users\corey\AppData\Local\Wox\app-1.3.183
