### ISSUE TITLE
Wox does not clear launcher bar after pressing Enter

### ISSUE THREAD

**Issue by drasbeck** [Wox-launcher/Wox#1224]
1. Wox version / commit number: 1.3.183

2. Steps to **reproduce** the bug: Invoke Wox, write a command. Next time Wox is invoked that same command is there.

3. Windows version: Windows 10 Pro 1607 (Build 14393.693)

It would be nice with an option to clear the Wox bar after pressing Enter, such that Wox is ready to search for something new, next time it is invoked.

As it is now I'm forced to invoke Wox, then press Ctrl + A to select everything, and only then can I start writing my next command/search/whatever. By standard procedure from Alfred (and others) the bar is usually empty when you invoke it.

**Comment by drasbeck** [comment]
Another approach could be that everything is already selected when Wox is next invoked, so that users can choose to write a new command or simply press enter to run the previous command.

**Comment by bao-qian** [comment]
duplicate: https://github.com/Wox-launcher/Wox/issues/1050
workaround https://github.com/Wox-launcher/Wox/issues/1050#issuecomment-269366751
please subscribe https://github.com/Wox-launcher/Wox/issues/1050 for new info
