### ISSUE TITLE
"System.ArgumentOutOfRangeException"

### ISSUE THREAD

**Issue by l0ader3000** [Wox-launcher/Wox#1226]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/11/2017 20:12:32
Exception:
mscorlib
System.ArgumentOutOfRangeException
Der Einfügeindex liegt außerhalb des gültigen Bereichs. Der Index darf keine negative Zahl sein und muss kleiner oder gleich der Größe sein.
Parametername: index
   bei System.Collections.ArrayList.Insert(Int32 index, Object value)
   bei System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   bei System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   bei MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-02-11.txt](https://github.com/Wox-launcher/Wox/files/768827/2017-02-11.txt)

**Comment by bao-qian** [comment]
duplicate #926
