### ISSUE TITLE
FR/Suggestion: Further Folder- & Program-Plugin Options 

### ISSUE THREAD

**Issue by l0ader3000** [Wox-launcher/Wox#1230]
Hey there,

first a big "Thank you!" for this awesome tool! 
So I just switched over from Launchy and I could not help but recognize that the folder-indexing-feature/-plugin is less intuitive from the folder-indexing launchy provides. What I'm really missing:

1. Recursive Folder-Indexing with a selectable depth for each selected folder (The Program-Plugin has at least the depth-selector)
2. Indexing of Network-Folders 
3. Regex based creation of folder-selectors for index, e.g.: "website-*" as created selector would index every folder it finds with "website-" at the beginning of the folder-name (Not even provided by launchy)

Also the two plugins could be better merged into one ("Program" & "Folder") and then just provide a "include program-executables with following file suffixes:"-option for every folder (like launchy does) one does create to be indexed. That would be more intuitive IMO.

What do you think about this?

Greetings, Johannes

**Comment by bao-qian** [comment]
actually the folder plugin is not for *search* folders, it is for navigate between folders.
if you want to search folders, you'd better using everything plugin
you can check which plugin give the current result by <kbd>shift</kbd><kbd>enter</kbd>

for network folder, if you add that folder in everything settings (not in wox), it should be indexed, give it a try.

**Comment by l0ader3000** [comment]
Thank you for the explanation, but there's still something I don't get:
Where is the difference between "navigate between" and "search" folders? 
Quick example to understand my point of view: I have a NAS which I'm constantly working on. The NAS itself has some client-folders (depth of interest: around 2 to 3 further folders-layers) and a lot of resource-folders for graphical, coding, animation, learning stuff etc - every folder itself with a different depth of interest: the resource folder for graphicdesign-stuff, for example, has more folder-layers which are used frequently to navigate to them - E.g.: graphicdesign/stocks/iconssets/streamline/ . Sometimes I want to navigate to stocks/, sometimes I directly want to go to streamline/ . Those folders (and the whole NAS itself) are not something I want to "search" - I exactly know the stuff/folder-names I have to work with constantly and where they are located. 

So let me ask you if I got this right: In cases where I know where I want to go ("navigate", which is the/my case most of the time), I should use the folder-plugin to set up those "directly-go-to"-folders"? But then such a setup would directly translate to hours of add-search-click-submit in the folder-plugin for every folder on the NAS (well not exactly all, but I think you get the point).

Would this still be the job for the Everything-Plugin or shouldn't the Folder-Plugin actually be more capable to support such cases?

**Comment by bao-qian** [comment]
it's just a bad name, it would be better if you could suggest a better name
you should use everything plugin, I rarely use folder plugin personally.
install `everything.exe` from github release first.

demo:
navigate:
![2017-02-14_15-27-12](https://cloud.githubusercontent.com/assets/1169912/22935393/63c4201c-f2ca-11e6-8553-45b535901ea5.gif)
search:
![2017-02-14_15-28-35](https://cloud.githubusercontent.com/assets/1169912/22935396/657571c2-f2ca-11e6-81f7-96315587cebf.gif)



you could go to folder_c directly using everything plugin by type `folder_c`

**Comment by bao-qian** [comment]
depth wouldn't matters in normal case
if you

1. don't have recursive link
2. don't have 100+ layers 

etc

**Comment by l0ader3000** [comment]
So after fiddling around with the settings of _Everything_ I have to admit that it seem to be like Launchy on steroids. I'm still a bit confused on how _Everything_ handles RegEx - but I'm sure time and therefore heavy consultation of some docs will also solve that for me.

**Comment by bao-qian** [comment]
regex for everything is not support at the momonet #930

**Comment by hahattan** [comment]
> for network folder, if you add that folder in everything settings (not in wox), it should be indexed, give it a try.

Can you elaborate on how to add network folder in everything settings ?
