### ISSUE TITLE
Tray icon vanished

### ISSUE THREAD

**Issue by shanehou** [Wox-launcher/Wox#1238]
Wox 1.3.183 / Python 3.6.0 / Everything 1.4.1.809b / x86-64

Shows a dialog box that ask me to upload log file and open a new issue every time I install a plugin

Tray icon is not shown anymore, even if I restart Wox.

Log file: http://pastebin.com/W8kp8aca

**Comment by bao-qian** [comment]
try new build
open https://ci.appveyor.com/project/happlebao/wox/build/artifacts, then download Releases\Wox-1.3.xxx.exe
or
delete %APPDATA%\Wox, backup before you do that

**Comment by shanehou** [comment]
Seems like the problem was caused by themes or plugins. After I deleted %APPDATA%\Wox everything was back to normal.
