### ISSUE TITLE
Option to provide more than one Plugin keyword

### ISSUE THREAD

**Issue by russelg** [Wox-launcher/Wox#124]
I made a plugin which shows the top streams from Twitch, and there's no way to give this plugin the option to open a stream not on the top list without making another plugin. 

Allowing people to assign more than one keyword to their plugin means that I could do something like `live` to see who is live, and `watch <stream name>` to watch a stream not on that list. I think this would be able to stop fragmentation of plugins, where multiple plugins would be made to accomplish tasks that are pretty similar to other tasks. For now at least, I have made two separate plugins, which I don't believe is necessary.

**Comment by qianlifeng** [comment]
Since we allow users to change the default action word. What if user changed the default actionkeyrowd? Let's say user changed `live` to `l` and 'watch' to `w`, if wox passed `l query` and `w query`, could plugin recognize it?

**Comment by orzFly** [comment]
We can replace "l query" with "live query" before passing to plugins.

— orzFly / Yeechan Lu

**Comment by qianlifeng** [comment]
that make sense.

**Comment by aaroncampf** [comment]
What if we made it so plugins did not use word but used Dictionary<GUID,String> GUID is the action's ID and the string is the default keyword.

This would allow an many key words

OR

The plugin could just go
twitch watch
twitch live

The action word is twitch, so they would have to use one more word, but at least it solves the problem

**Comment by bao-qian** [comment]
Hi, good news. This feature is partially done. See https://github.com/Wox-launcher/Wox/issues/352 for further discussion.

**Comment by bao-qian** [comment]
Done. See #352
