### ISSUE TITLE
Problem with uploading new plugin

### ISSUE THREAD

**Issue by vladimirantos** [Wox-launcher/Wox#1242]
Hello,
I have a problem with uploading my C# plugin. Maybe because I do not understand how it should be done. Please create a detailed guide. 
I try uploaded plugin in zip format. Zip contains 3 files:
- plugin.json
- icon.png
- Wox.Plugin.Test.dll
DLL library contains only empty class with implementation IPlugin (methods dont contains code). 
When I tried upload, I got this message "Invalid plugin file. Wox plugin shoulds end with .wox“
Here is my plugin.json file:
`{
  "ID":"D2D2C23B084D411DB66FE0C79D6C2A6C",   
  "ActionKeyword":"test",                     
  "Name":"TestPlugin",                              
  "Description":"My first plugin",    
  "Author":"bluray",                     
  "Version":"1.0.0",                         
  "Language":"csharp",                       
  "Website":"http://www.getwox.com",        
  "IcoPath": "Images\\lock.png",              
  "ExecuteFileName":"Wox.Plugin.Test.dll"   
}`

I have questions:
What is ID? It can be any MD5 hash?
What are the size must have an icon?

Thanks for help.

**Comment by bao-qian** [comment]
- id: 
in vs c# interactive: 
> System.Guid.NewGuid()
[2d5e9b2d-8a8b-45e8-9b2b-b416daf40fb8]

- icon: at least 48*48

- messages: rename your zip file to .wox

you can download a existing plugin and check how other people package their plugin

**Comment by vladimirantos** [comment]
Thanks, please update your documentation (icon size, zip to wox). But now I have new problem. I uploaded .wox file with png icon, dll library and plugin.json file. Error message is: 

> Invalid plugin file. We didn't find plugin.json file in your plugin. 

Plugin.json file is in plugin.wox. Json file contains this:
`{
  "ID":"d996f55dcccd4c14a8594d0d8668fbcc",   
  "ActionKeyword":"key",                     
  "Name":"PluginName",                              
  "Description":"Plugin for searching",   
  "Author":"author",                    
  "Version":"1.0.0",                         
  "Language":"csharp",                      
  "Website":"http://www.getwox.com",        
  "IcoPath":"icon.png",              
  "ExecuteFileName":"Wox.Plugins.Test.dll"   
}`

Thank you for advices

**Comment by bao-qian** [comment]
as I said, download a plugin and unpack it to compare with yours.

**Comment by bao-qian** [comment]
the plugin.json should be in the root of that zip, not under a directory

**Comment by vladimirantos** [comment]
Problem solved, thanks!
