### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by chujianyun** [Wox-launcher/Wox#1244]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 02/20/2017 14:39:01
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unterminated string. Expected delimiter: ". Path 'records['amd64_microsoft-windows-ipconfig.resources_31bf3856ad364e35_10.0.10586.0_en-us_5462c744a81025e5C:\Windows\WinSxS\amd64_microsoft-windows-ipconfig.resources_31bf3856ad364e35_10.0.10586.0_en-us_5462c744a81025e5']', line 42, position 100.
   在 Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   在 Newtonsoft.Json.JsonTextReader.ParseProperty()
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 58
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Load() 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 40
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 63
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 49
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
试一下新 build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.347/artifacts
