### ISSUE TITLE
How to remove a package on the website

### ISSUE THREAD

**Issue by JiajunW** [Wox-launcher/Wox#1253]
Hi I upload a plugin to search on stackoverflow. And...found that there is already a plugin there...

So I just wanna remove my package, but I didn't see any delete button on the website.

**Comment by bao-qian** [comment]
which one?

**Comment by roose** [comment]
@JiajunW I think this is not a problem, users may select you plugin instead of some other, don't delete, add new feature etc

**Comment by JiajunW** [comment]
@roose I just don't wanna confuse users.. And I can add new features to the original one as well if needed :)

@happlebao http://www.getwox.com/plugin/122 This one please..
And just curious, whether this is by design that one cannot delete his package?

**Comment by bao-qian** [comment]
you should be able to do that 
go to 
http://www.getwox.com/u/54935
and you will find the delete button

C:\Users\Chengxi\Documents\ShareX\Screenshots\2017-02\chrome_2017-02-24_12-44-41.png
![image](https://cloud.githubusercontent.com/assets/1169912/23303958/144edd2a-fa8f-11e6-9fcb-e33da458af2b.png)
