### ISSUE TITLE
Wox.Plugin.Everything System.NullReferenceException

### ISSUE THREAD

**Issue by LOSTZHOU** [Wox-launcher/Wox#1258]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 02/27/2017 10:26:38
Exception:
Wox.Plugin.Everything
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Everything.EverythingSettings.View_Loaded(Object sender, RoutedEventArgs re) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\EverythingSettings.xaml.cs:行号 18
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
whole log？

**Comment by bao-qian** [comment]
or reset 
delete %APPDATA%\Wox, backup before you do that

**Comment by LOSTZHOU** [comment]
可以用中文表达吗？




 
From: happlebao
Date: 2017-02-27 20:54
To: Wox-launcher/Wox
CC: LOSTZHOU; Author
Subject: Re: [Wox-launcher/Wox] Wox.Plugin.Everything System.NullReferenceException (#1258)
or reset
delete %APPDATA%\Wox, backup before you do that

**Comment by bao-qian** [comment]
上传整个 log 文件 （%APPDATA%\Wox\Logs\version\date.txt）?
或者
删除 `%APPDATA%\Wox`，删前记得备份

**Comment by LOSTZHOU** [comment]
我把wox 卸载并把安装目录下的文件全部删除后解决了问题



 
From: happlebao
Date: 2017-02-28 09:59
To: Wox-launcher/Wox
CC: LOSTZHOU; Author
Subject: Re: [Wox-launcher/Wox] Wox.Plugin.Everything System.NullReferenceException (#1258)
上传整个 log 文件 （%APPDATA%\Wox\Logs\version\date.txt）?
或者
删除 %APPDATA%\Wox，删前记得备份
