### ISSUE TITLE
Don't exist a graphical interface option to disable the Win Key+R shortcut overload

### ISSUE THREAD

**Issue by wellington1993** [Wox-launcher/Wox#1259]
Please add option to disable the Win key + R overload.

Sorry but I don't find this option.

**Comment by bao-qian** [comment]
In settings -> plugin -> program plugin

**Comment by wellington1993** [comment]
Hi,

Thanks @happlebao. I found the problem and the problem not is the program plugin.

The problem is the Shell plugin. 
But after disable the plugin still running on next boot.
Temporary solution is enable and disable every boot.

Any idea?

**Comment by bao-qian** [comment]
Sorry, it is the shell plugin.
You need to untick the win+r option in shell plugin.

**Comment by wellington1993** [comment]
@happlebao Yes, but every reboot I need to untick.
But I moved the plugin folder to outside of plugins dir.
Worked for me. 

Thanks!

**Comment by bao-qian** [comment]
what version are you using?
I can disable it and it is continues disabled after wox restart.

**Comment by bao-qian** [comment]
perhaps you didn't close the setting windows before your "reboot"?
