### ISSUE TITLE
想知道那个录制屏幕的软件叫什么？

### ISSUE THREAD

**Issue by ruijanlee** [Wox-launcher/Wox#126]
http://www.appinn.com/wox-launcher/
这个页面上的那个录制屏幕的软件叫什么？
虽然和Wox没什么关系，但是非常想知道那个软件的名字。

**Comment by ruijanlee** [comment]
找到了，GifCam。

**Comment by orzFly** [comment]
http://blog.bahraniapps.com/gifcam/ :smiley:
