### ISSUE TITLE
System.Xml.XmlException 在行 14 位置 6 的 'system:String' 开始标记和结束标记 'system:string' 不相符。行 14，位置 94。

### ISSUE THREAD

**Issue by kakurineuin** [Wox-launcher/Wox#1262]
Wox 启动时就出现此错误，请帮忙，谢谢。

---
Wox version: 1.3.357
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\Kevin\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/01/2017 10:04:36
Exception:
System.Xml
System.Xml.XmlException
在行 14 位置 6 的 'system:String' 开始标记和结束标记 'system:string' 不相符。 行 14，位置 94。
   于 System.Xml.XmlTextReaderImpl.Throw(Exception e)
   于 System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   于 System.Xml.XmlTextReaderImpl.ParseEndElement()
   于 System.Xml.XmlTextReaderImpl.ParseElementContent()
   于 System.Xaml.XmlCompatibilityReader.Read()
   于 MS.Internal.Xaml.Parser.XamlScanner.DoXmlRead()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<P_StartElement>d__7.MoveNext()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<P_Element>d__5.MoveNext()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<P_ElementContent>d__12.MoveNext()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<P_ElementBody>d__8.MoveNext()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<P_Element>d__5.MoveNext()
   于 MS.Internal.Xaml.Parser.XamlPullParser.<Parse>d__4.MoveNext()
   于 MS.Internal.Xaml.NodeStreamSorter.ReadAheadToEndOfAttributes()
   于 MS.Internal.Xaml.NodeStreamSorter.ReadAheadAndSortCtorProperties()
   于 MS.Internal.Xaml.NodeStreamSorter.MoveNext()
   于 System.Xaml.XamlXmlReader.Read()
   于 System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   于 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

**Comment by bao-qian** [comment]
上传 `%APPDATA%\Wox\Logs\date`

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.362/artifacts
