### ISSUE TITLE
Plugin repo down?

### ISSUE THREAD

**Issue by sphair** [Wox-launcher/Wox#1270]
Is the plugin repository down?

When I try to install a plugin, I only get 404. Tracked down the code to see which URL it tries to fetch from, and it tries to download from api.getwox.com/media/plugin/DB634BE6F3D34F6D9D64F7C2AEE3ECEC/Wox.Plugin.Switcheroo-6444bf94-d3c6-408f-a638-f2612de34e6a.wox

which does not return any file.

1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: wpm install Switcheroo
3. Windows version: 10, 15046
4. Exception: 2017-03-03 11:28:05.0456|ERROR|System.Net.HttpWebRequest.GetResponse|The remote server returned an error: (404) Not Found.

**Comment by bao-qian** [comment]
yes it's down. thanks for let me know

**Comment by bao-qian** [comment]
up now

**Comment by jazeem-azeez** [comment]
getwox domain is not reachable (sold/expired)
http://www.getwox.com/
