### ISSUE TITLE
[Program-Plugin] Re-Index custom locations when content changes

### ISSUE THREAD

**Issue by snwflake** [Wox-launcher/Wox#1272]
Is there way Re-indexing the the given location when its content changes?
I'm currently thinking of just deleting this plugin and recoding it myself :/

Can't even index a location with more than 10 files/folders because then it take ~30 mins + to index.

I really needed to create a folder, symlinking all my wanted search content inside and index that location.
Using "everything" is not an option, except I want to get flooded with useless /tmp or appData tmp files.

**Comment by snwflake** [comment]
`Offtopic `Pls check, acknowledge or at least reply to your pull requests! `/Offtopic`

**Comment by bao-qian** [comment]
Program plugin is slow and not supposed to index non-program files. You can set your index location in everything settings.

**Comment by snwflake** [comment]
Thanks for clarifying. Everything will check on changes inside the indices I guess.

This is closed then
