### ISSUE TITLE
打开右键菜单后无法返回主搜索界面

### ISSUE THREAD

**Issue by god891006** [Wox-launcher/Wox#1276]
在wox中查找某个文件，找到之后右击查找文件位置，在进入wox之后，所有命令全部失效，一直都是这几个命令
![image](https://cloud.githubusercontent.com/assets/25874986/23601048/7bda9a04-0284-11e7-9434-5a7373957e47.png)
无论再写什么命令都不执行
![image](https://cloud.githubusercontent.com/assets/25874986/23601076/9ad90f4e-0284-11e7-84f2-6f1a382dbf27.png)

**Comment by bao-qian** [comment]
1.  版本
2. log
3. gif

**Comment by bao-qian** [comment]
按 esc
