### ISSUE TITLE
删除关键字之后，无法再次设置关键字

### ISSUE THREAD

**Issue by god891006** [Wox-launcher/Wox#1279]
1. Wox 版本 / commit number：
2. 如何**重现** bug：删除关键字之后无法再次设置该插件的关键字，并且使用wox什么也搜不到，重装wox也没用。即使禁用该插件也是什么也搜不到。
3. Windows 版本：v1.3.357
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
[2017-03-07.txt](https://github.com/Wox-launcher/Wox/files/824020/2017-03-07.txt)

6. 截图 （可选）：
![image](https://cloud.githubusercontent.com/assets/25874986/23651585/dff6f028-0360-11e7-991c-c327b1b3fd9d.png)

)

**Comment by jhdxr** [comment]
临时解决方案：`%appdata%/Wox/Settings/Settings.json`，找到`Control Panel`下的`ActionKeywords`，把`""`改成`"*"`



但为什么这种设置错误会导致Wox完全搜不到东西呢_(:з」∠)_

**Comment by jhdxr** [comment]
Thanks for your report. This issue has already been fixed
in the latest released version of Wox, which you can download [here](https://github.com/Wox-launcher/Wox/releases)
