### ISSUE TITLE
[Feature?]Ignore mouse input

### ISSUE THREAD

**Issue by snwflake** [Wox-launcher/Wox#1280]
## Feature: Ignore mouse input

Since I'm coming from macOS, I use Wox frequently.

## The problem:

I tend to ignore the mouse for most of the time, since its annoying to me. However, the curser sometimes hovers in the middle of the screen because I was once again too lazy to move it aside. Now when opening Wox, it happens so that the curser just out of nowhere selects the 2nd, 3rd and so on result, without moving it though. Probably I hit the desk, or whatever.

I don't know how often I restarted my pc, signed off, quit my music app, etc. because of that.

## Request

I would love to have an option that disables the entire mouse input. I would figure it out myself, but I'm not familiar with neither C# nor GUI stuff in general.

I appreciate any suggestions regarding this problem. 
Cheers!

**Comment by bao-qian** [comment]
repeated # #975

**Comment by snwflake** [comment]
Sorry, search term wasn't accurate
