### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by chunsuper** [Wox-launcher/Wox#1289]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\chunk\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/10/2017 13:37:58
Exception:
Wox.Plugin.Switcheroo
System.TypeLoadException
未能从程序集“Wox.Infrastructure, Version=1.3.357.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。
   在 Wox.Plugin.Switcheroo.Plugin.Init(PluginInitContext context)
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
duplicate #1286

**Comment by bao-qian** [comment]
Wox.Plugin.Switcheroo 更新了
