### ISSUE TITLE
Web Searches plugin mixing other results into response

### ISSUE THREAD

**Issue by russelg** [Wox-launcher/Wox#129]
![wox_2014-07-21_18-50-15](https://cloud.githubusercontent.com/assets/1552840/3642650/04623e0e-10c5-11e4-84be-933cb44377c1.png)

I don't believe this is intended behaviour.

Test with wikipedia as well:
![wox_2014-07-21_18-54-16](https://cloud.githubusercontent.com/assets/1552840/3642668/63c6db84-10c5-11e4-8bd1-8461b364ebcf.png)

**Comment by qianlifeng** [comment]
Yeah, there are two reasons:
1. @orzFly added google search suggestions to web search
2. Some other programs match the query and displayed  

About the search suggestions, I think there is no need to add this, I rarely uses those suggestions. When user started a new web search, typically speaking user know what they are looking for. Also those suggestions sometime slowdown the typing I think.  
For the programs results mixing into the web searches, we should find a solution.

**Comment by orzFly** [comment]
Google Suggestions can help you correct spelling errors....

**Comment by orzFly** [comment]
BTW you can try "google 3 gb / 24kb/s"...

**Comment by russelg** [comment]
That's neat and all but it should probably be optional if anything.

By the way, the suggestions from google aren't the problem, the results from other plugins seeping through is the problem.

**Comment by russelg** [comment]
@orzFly 
That is the expected response. I'm not sure if this is related, but:
![wox_2014-07-21_20-17-22](https://cloud.githubusercontent.com/assets/1552840/3643285/0be59c28-10d1-11e4-8988-333fb6578107.png)

That works and all. but when I put a space afterwards, there are no results returned, as if Wox is waiting to receive query parameters, as seen below.
![wox_2014-07-21_20-18-39](https://cloud.githubusercontent.com/assets/1552840/3643297/32af598e-10d1-11e4-9919-096e138d7f68.png)

But if I continue with a letter, it goes back into normal mode.
![wox_2014-07-21_20-18-43](https://cloud.githubusercontent.com/assets/1552840/3643296/2e73d71e-10d1-11e4-9c48-c92001709692.png)

I don't think spaces are being handled correctly.

**Comment by orzFly** [comment]
Sorry, I didn't test clearly before I post the comment. 
Here is the real behavior in Alfred:

![image](https://cloud.githubusercontent.com/assets/158528/3643308/81e7c040-10d1-11e4-97bf-cd441d8e205d.png)

The last item is a custom search and its keyword is "microsoft".

**Comment by qianlifeng** [comment]
@orzFly  I will make the web search suggestions optional, user can turn it on or not. Also Bing or Baidu suggestion source should be added, since we can't access google.com from china.  

@russelg I can reproduce that issue, will look into that.

**Comment by orzFly** [comment]
@qianlifeng That's okay since my original design is user can select pre-defined suggestion for every web searches or disable it.

**Comment by qianlifeng** [comment]
@russelg  this issue has been fixed now. Pls check the latest code. Please let me know if you have any issues.

**Comment by russelg** [comment]
@qianlifeng Confirmed!
