### ISSUE TITLE
[UI] Contextual menu UI improvement

### ISSUE THREAD

**Issue by sirotnikov** [Wox-launcher/Wox#1294]
Wox 1.3.357 on Windows 10

I find myself confused a lot by the Wox contextual menu, especially when Wox "remembers" a previously open contextual menu, it takes me a lot of time to understand what is happening.

I suggest the following changes:

1. When in contextual menu, add visible element that displays that we're in a contextual menu, with the Program Icon and name for the program whose context you're in.
2. I think that when the text field is empty, pressing "Backspace" should also exit the contextual menu (like escape). I keep intuitively pressing "Backspace" to exit the contextual menu, expecting it to change. 
3. I think that Wox should not remember being in contextual menu if it loses focus for longer than a few seconds.

I think this will make the use more intuitive.

**Comment by sirotnikov** [comment]
Is this still the case?

**Comment by qianlifeng** [comment]
> Is this still the case?

We will use a different contextual menu in V2, the menu will not be displayed in the secondary interface, but suspended in the lower right corner of the results list, so there should be no such problems as you said.

![image](https://github.com/Wox-launcher/Wox/assets/1725475/dfd8db51-eb76-41fe-818e-8b8266f7e6fd)
