### ISSUE TITLE
1.3.357开启报错，并且之前的插件消失了

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#1298]
报错信息，log文件在最后

Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\ever\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/14/2017 19:23:50
Exception:
Wox.Plugin.Switcheroo
System.TypeLoadException
未能从程序集“Wox.Infrastructure, Version=1.3.357.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。
   在 Wox.Plugin.Switcheroo.Plugin.Init(PluginInitContext context)
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2017-03-14.txt](https://github.com/Wox-launcher/Wox/files/841105/2017-03-14.txt)

**Comment by bao-qian** [comment]
#1286 
我重构忘记不要改签名了
暂时删除 %APPDATA%\Wox\Plugins\Switcheroo

**Comment by iEverX** [comment]
还有问题是装了新版本之后，之前自己写的插件都没有了

**Comment by bao-qian** [comment]
@iEverX 你贴下 log 或者自己看下是哪个插件有问题吧？
插件不会删除，还在 %APPDATA%\wox\plugins  下，你用 release 版打开就应该能看到。

**Comment by bao-qian** [comment]
Wox.Plugin.Switcheroo 更新了
