### ISSUE TITLE
快捷键唤出窗口没有自动获取焦点

### ISSUE THREAD

**Issue by mx1700** [Wox-launcher/Wox#13]
重现步骤：
1.快捷键唤出窗口（此时又焦点）
2.点击其他程序（此时失去焦点）
3.快捷键隐藏窗口
4.快捷键唤出窗口（此时无焦点）

**Comment by qianlifeng** [comment]
我已经注意到这个问题了，确实是个比较讨厌的问题。对于用户来说呼出窗口后的第一件事情就是输入查询内容，如果此时不能输入，那么确实是个很糟糕的事情。
我曾查阅了一些资料，试过一些方法但是都没有效果。我后面会继续寻找解决方案的。另外如果你有好的方案也可以发request给我。谢谢

**Comment by qianlifeng** [comment]
Fixed. f389b1ae93bdd83ac9c3a590994a1843a3824da1
