### ISSUE TITLE
I want to ask about alt+tab with switheroo

### ISSUE THREAD

**Issue by benyaminl** [Wox-launcher/Wox#1301]
I want to ask about alt+tab with switheroo, until now, I'm new to Wox, also Wox is great for me, I like to use keyboard alot, since I'm a bit of geek, and the problem I face is, everytime I press alt+tab with switheroo, for switching the windows, the newest windows list isn't updated, so I nedd to type again the win and start again with something.. So, how to fix this things or make the switheroo auto update when I press alt+tab without I del the win word and start typing again.. Thanksss

**Comment by lances101** [comment]
@benyaminl I've updated Wox.Plugin.Switcheroo so that it forces a query reset when Alt+Tab is pressed. Please update your plugin.

**Comment by benyaminl** [comment]
@lances101 Thanks. It Works well!
