### ISSUE TITLE
Use casplock for hotkey

### ISSUE THREAD

**Issue by hiep2000** [Wox-launcher/Wox#1306]
I use "Shift + casplock" for my hotkey, but everytime I use this combination, casplock toggles. 
I think Wox can restore the state of casplock if it's trigged. Find and run robot do this fine.
I'm using Wox 1.3.357.

**Comment by germanoeich** [comment]
Gonna give this a go.

**Comment by bao-qian** [comment]
@germanoeich If you want to code sth, id suggest looking for bug or help_need first. I don't want more hacks in keyboard hotkeys code.

**Comment by germanoeich** [comment]
@happlebao Fair enough, but I don't quite agree with this. Gonna look for bugs and help_needed, but you should let people implement features if it's gonna be useful for someone. I mean, that's the point of open source. I'd be happy to refactor the hack-heavy areas of the code if that allowed people to contribute easier, but in the end you approve the PRs.

**Comment by bao-qian** [comment]
@germanoeich hotkey is really problematic, take a look https://github.com/Wox-launcher/Wox/issues/459
ideally there are you be only 1 interface to control the hotkey, not 4. I will definitely approve the PR if you can do that.

**Comment by germanoeich** [comment]
Count me in. Will comment at #459 if I have any questions. Thanks
