### ISSUE TITLE
Program plugin Never stops indexing (uwp)

### ISSUE THREAD

**Issue by dingsbums** [Wox-launcher/Wox#1309]
1. Wox version / commit number: 1.3.357
2. Steps to **reproduce** the bug: just open the programm
3. Windows version: 10

In Plugin when I "Reindex" the Program Plugin it never stops "indexing" and it never indexes.

Edit: just to let you  I am on insider build 15063 (still the same as on build 14986)

[2017-03-18.txt](https://github.com/Wox-launcher/Wox/files/852673/2017-03-18.txt)

**Comment by bao-qian** [comment]
a buggy uwp app break the whole program indexing
one broken uwp app should not brake the whole indexing

**Comment by dingsbums** [comment]
I tried uninstalling a few uwp apps. still the same (maybe because of insider builds?)

and also when I launch the app, this is the log file.. maybe a different issue or maybe it is connected to this one

[2017-03-25.txt](https://github.com/Wox-launcher/Wox/files/869613/2017-03-25.txt)

**Comment by iwillalwaysbe** [comment]
I have the same problem

**Comment by bao-qian** [comment]
@dingsbums @iwillalwaysbe 
try 
https://ci.appveyor.com/project/happlebao/wox/build/1.3.422

**Comment by dingsbums** [comment]
still errors in logfile but it seems to index the folder correctly now. you want the new logs?

**Comment by bao-qian** [comment]
@dingsbums yes please

**Comment by dingsbums** [comment]
[2017-04-03.txt](https://github.com/Wox-launcher/Wox/files/889752/2017-04-03.txt)

**Comment by bao-qian** [comment]
try remove 

Microsoft.WelcomeScreen_10.0.14931.1000_neutral__cw5n1h2txyewy
Microsoft.Windows.PeopleExperienceHost_10.0.14986.1000_neutral_neutral_cw5n1h2txyewy
HolographicViewer_1.0.0.0_neutral__cw5n1h2txyewy
Holograms_1.0.0.0_neutral__cw5n1h2txyewy
Microsoft.Windows.ProximityConnectService_10.0.14986.1000_neutral_neutral_cw5n1h2txyewy

then try again and upload the logs

this exception has been mentioned in #198 , but I forgot to check it, sad.

**Comment by bao-qian** [comment]
reopen if you still have this issue
