### ISSUE TITLE
Textcursor moves to end of line automatically/unintentionally

### ISSUE THREAD

**Issue by l0ader3000** [Wox-launcher/Wox#1314]
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: Write some stuff in wox, use arrow-keys to move the textcursor to middle or beginning of the textline to insert a new word/letter, press key for the first letter (of the word).
3. Windows version: Win 10 Pro N - Build: 14393.953
4. Exception: None
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional):
![wox-bug-cursor](https://cloud.githubusercontent.com/assets/2073401/24246815/5c159ce4-0fc9-11e7-8855-a7582076a4fd.gif)

**Comment by germanoeich** [comment]
I can't reproduce this, can you try to disable your plugins and see if it still happens?

**Comment by bao-qian** [comment]
Please try the new pre-release

**Comment by l0ader3000** [comment]
@germanoeich thx for the suggestion! but, as @happlebao suggested: Bug seems to be fixed in latest pre-release (1.3.357).

**Comment by bao-qian** [comment]
@JohaWeber good
