### ISSUE TITLE
功能建议:程序插件索引的时候可以添加正则表达式匹配

### ISSUE THREAD

**Issue by advancer68** [Wox-launcher/Wox#1315]
程序插件默认索引的开始菜单 但是很多不需要的快捷方式(比如当我搜索qq的时候会出现 卸载qq 设置引导 等不怎么需要的快捷方式)被索引进来,会影响搜索结果,所以希望添加程序插件 索引的时候可以允许自己设置索引的正则表达式 这样就可以根据自己意愿排除那些不需要的快捷方式

**Comment by bao-qian** [comment]
重复 # #239
