### ISSUE TITLE
Wox won't hide itself on alt-tab from desktop

### ISSUE THREAD

**Issue by germanoeich** [Wox-launcher/Wox#1316]
1. Wox version / commit number: 1.3.357
2. Steps to **reproduce** the bug: Win + D, open Wox and alt-tab to another window. 
3. Windows version: Win10 Pro Version 1607 OS Build 14393.953
4. Exception: None

When you are in Desktop and launch Wox and then Alt-tab to another window, Wox won't recognize it has lost focus and will stay on top of the other windows, sometimes when you interact with another window it will go away, sometimes it will just stay open. The more you alt-tab, the more likely for it to stay on top even after interacting with window. 
Probably related to #703, but I'm not entirely sure.

**Comment by bao-qian** [comment]
there is a "hide wox when focus is lost" option, try it

**Comment by germanoeich** [comment]
It is enabled. It works when I open Wox from any window and alt-tab away, but not when I come from the desktop.

**Comment by bao-qian** [comment]
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.409/artifacts ?

**Comment by germanoeich** [comment]
Fixed in .409. Closing this.
