### ISSUE TITLE
未能找到路径“C:\Users\X\AppData\Local\Wox\app-1.3.183\Plugins”的一部分。

### ISSUE THREAD

**Issue by FIRELU** [Wox-launcher/Wox#1318]
1. upload log file: C:\Users\LOUIS\AppData\Roaming\Wox\Logs\1.3.357\2017-03-29.txt
2. copy below exception message
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\LOUIS\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/29/2017 01:53:54
Exception:
mscorlib
System.IO.DirectoryNotFoundException
未能找到路径“C:\Users\LOUIS\AppData\Local\Wox\app-1.3.183\Plugins”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   在 Wox.Plugins.PluginsList.Main.LoadPluginInfo(String path)
   在 Wox.Plugins.PluginsList.Main.Init(PluginInitContext context)
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
请上传完整的 log

**Comment by FIRELU** [comment]
sorry. I lost it. I reinstall it. if show the same problems, I'll submit again

**Comment by bao-qian** [comment]
reopen if you still have this problem
