### ISSUE TITLE
Wox won't load!

### ISSUE THREAD

**Issue by alextac98** [Wox-launcher/Wox#1323]
Wox is stuck loading and won't respond. The blue bar at the bottom of the search bar just goes accross the search bar.
![image](https://cloud.githubusercontent.com/assets/17330069/24471153/34fed542-148f-11e7-88ee-6fa6ee8c8ac5.png)

## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.357
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://ci.appveyor.com/project/happlebao/wox/build/1.3.414/artifacts

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
Version and log?

**Comment by alextac98** [comment]
Version 1.3.357
I can't run the command on Wox because of the same issue, but I've attached my directory.


[Wox.zip](https://github.com/Wox-launcher/Wox/files/885882/Wox.zip)

**Comment by bao-qian** [comment]
@alextac98 
please upload the "whole log file （`%APPDATA%\Wox\Logs\version\date.txt`):"

**Comment by alextac98** [comment]
[1.3.357.zip](https://github.com/Wox-launcher/Wox/files/886071/1.3.357.zip)

**Comment by bao-qian** [comment]
try
https://ci.appveyor.com/project/happlebao/wox/build/1.3.422

**Comment by bao-qian** [comment]
reopen if you still have this issue
