### ISSUE TITLE
不能搜索出程序启动项

### ISSUE THREAD

**Issue by iwillalwaysbe** [Wox-launcher/Wox#1325]
### windows版本：
win10

### 现象：
1. 无法搜索程序的启动项，快速启动功能没法用。
2. wox更新到最新版本也还是这样。
3. program插件的重新索引也是一直索引停不下来。
4. 之前出现过wox占用内存过高，杀掉wox进程后，再次启动wox，就出现了现在遇到的问题。

![image](https://cloud.githubusercontent.com/assets/13460208/24485981/279de176-153a-11e7-9f7d-a5043b33ca05.png)

### log文件：
[2017-03-30.txt](https://github.com/Wox-launcher/Wox/files/880941/2017-03-30.txt)

### exception message：

Wox version: 1.3.415
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: C:\Users\ZhangYS\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/30/2017 11:10:42
Exception:
Squirrel
System.Exception
Update.exe not found, not a Squirrel-installed app?
   在 Squirrel.UpdateManager.getUpdateExe() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 313
   在 Squirrel.UpdateManager.getApplicationName() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 292
   在 Squirrel.UpdateManager..ctor(String urlOrPath, String applicationName, String rootDirectory, IFileDownloader urlDownloader) 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 41
   在 Wox.Core.Updater.<GitHubUpdateManager>d__3.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 113
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__1.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 30
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.SettingWindow.<OnCheckUpdates>d__24.MoveNext() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 309
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
1. 控制面板中卸载 wox
2. 确保 `%LOCALAPPDATA%\Wox` 中删干净了
3. 重装 https://ci.appveyor.com/project/happlebao/wox/build/1.3.416/artifacts

**Comment by bao-qian** [comment]
related #1252

**Comment by iwillalwaysbe** [comment]
按您说的方法删除 `%LOCALAPPDATA%\Wox`  之后，再重装，可以搜索到程序启动项了。但是program插件的索引项还是有问题。添加`D:\Program Files\ ` 可以索引，但是在添加其它文件夹就索引不出来。比如`C:Program Files\`, `D:\Program Files(X86)\ ` 就会一直Indexing。 看了这个issue（#1252），也没看出来明确的解决索引问题的方法是什么。

**Comment by bao-qian** [comment]
@iwillalwaysbe 新log？

**Comment by bao-qian** [comment]
@iwillalwaysbe 方法就是在新的 1.3.365 中那个 #1252 的问题修复了，但你这个看起来相关但又没修复，所以需要 log 做进一步分析。

**Comment by iwillalwaysbe** [comment]
今早试了一下，除了 `D:\Program Files\ `之外,program插件还是一直Indexing。

### log文件：

[2017-04-01.txt](https://github.com/Wox-launcher/Wox/files/887274/2017-04-01.txt)

**Comment by bao-qian** [comment]
@iwillalwaysbe 试一下 https://ci.appveyor.com/project/happlebao/wox/build/1.3.422

**Comment by bao-qian** [comment]
有问题再开
