### ISSUE TITLE
migrating from launchy

### ISSUE THREAD

**Issue by marcspc** [Wox-launcher/Wox#1326]
Hi, I've been testing launchy but seems an abandoned project, this one seems more complete,
I've been testing it for a while and I'm missing some things, maybe there are plugins or something to fix it:

- being able to decide how deep in a folder structure and which file sufixes PER ROUTE to add to the index:
https://puu.sh/v3hNk/27f53769a2.png

- when running something from WOX, it will be moved to the top of suggestions the next time I search by that name

**Comment by bao-qian** [comment]
1. currently no
2. just choose this item more times, duplicate #315
