### ISSUE TITLE
Everything setup wox error

### ISSUE THREAD

**Issue by mddemir** [Wox-launcher/Wox#1331]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\mdemir\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/31/2017 08:29:25
Exception:
mscorlib
System.IO.IOException
'Themes' yoluna erişim reddedildi.
   konum: System.IO.DirectoryInfo.MoveTo(String destDirName)
   konum: System.Threading.Tasks.Task.Execute()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs içinde: satır 234
[2017-03-31.txt]
(https://github.com/Wox-launcher/Wox/files/884618/2017-03-31.txt)

**Comment by happlebao** [comment]
what do you mean by "everything" in your title "Everything setup wox error"?

**Comment by happlebao** [comment]
duplicate #1292 
please subscribe and reply in #1292 if you still have this probelm
