### ISSUE TITLE
每次启动都会显示这个错误

### ISSUE THREAD

**Issue by 0x57406E67** [Wox-launcher/Wox#1333]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 04/01/2017 11:23:55
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2017-04-01.txt](https://github.com/Wox-launcher/Wox/files/887333/2017-04-01.txt)

**Comment by 0x57406E67** [comment]
![snipaste20170401_113314](https://cloud.githubusercontent.com/assets/5814034/24575066/0fcbce00-16cf-11e7-9358-d114867889bd.png)
无法搜索文件，输入任何字搜索框中都是进度条一直转，但是不会有任何结果。Everything开着。

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.420/artifacts
