### ISSUE TITLE
Apps from Windows Store aren't shown

### ISSUE THREAD

**Issue by popenke** [Wox-launcher/Wox#1334]
### Issue
When I search for an app installed from Windows Store the Wox app can't find it.

### Details
1. Wox version / commit number: **1.3.183**.
2. Steps to **reproduce** the bug: Try to find an app installed from Windows Store.
3. Windows version: **10** (All updates until 4/1/2017).
6. Screenshot: 
- Windows search:
<img width="960" alt="slack" src="https://cloud.githubusercontent.com/assets/395142/24580438/83a9c3a4-16de-11e7-8a37-9b9c15e15a81.png">

- Wox app search:
<img width="960" alt="no-slack" src="https://cloud.githubusercontent.com/assets/395142/24580451/b163d320-16de-11e7-8005-8888461d7fd9.png">

**Comment by bao-qian** [comment]
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.422
