### ISSUE TITLE
每次挂机回来得到一堆更新弹窗

### ISSUE THREAD

**Issue by tinymins** [Wox-launcher/Wox#1339]
![image](https://cloud.githubusercontent.com/assets/1808990/24685831/8f5364f6-19e2-11e7-8aa2-f46d7b76e63e.png)
这样不好吧？失败就默默失败好了或者消息中心弹个消息也比一个模式对话框用户体验好吧_(:з」∠)_

**Comment by bao-qian** [comment]
不好 _(:з」∠)_

**Comment by bao-qian** [comment]
@tinymins 
https://ci.appveyor.com/project/happlebao/wox/build/1.3.423/artifacts

**Comment by bao-qian** [comment]
@tinymins  有问题再开？
