### ISSUE TITLE
首页Readme截图中，显示按键的效果，怎么做的？

### ISSUE THREAD

**Issue by luboq** [Wox-launcher/Wox#1340]
左下角，请问用什么工具，显示的？

![](https://camo.githubusercontent.com/9db33546d3a905a9ad915e0948d3ba3f47f57b64/687474703a2f2f692e696d6775722e636f6d2f4474784e424a692e676966)

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/533

**Comment by luboq** [comment]
@happlebao 谢谢，我问之前用中文搜了，没用英文。
