### ISSUE TITLE
After pressing home button it takes you to the end of the input

### ISSUE THREAD

**Issue by 1Mark** [Wox-launcher/Wox#1346]
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug: Type in a word ( no need to do a space after the word) then press the home key. It will take you to the beginning of the word but you can only type one character before it teleports back to the end of the word. 
3. Windows version: 
4. Exception: Windows 10 Education 64-bit (10.0, Build 14393) (14393.rs1_release_inmarket.170303-1614)
6. Screenshot (optional): [gif](https://gyazo.com/65e3e11cb04de05ec0bede956c85497e)

**Comment by bao-qian** [comment]
Try 1.3.424 in the release

**Comment by 1Mark** [comment]
Oh, I only use stable versions. Ok well, in that case, I'll just wait.

**Comment by bao-qian** [comment]
duplicate: #813
