### ISSUE TITLE
Antivirus Wox as Malware ?

### ISSUE THREAD

**Issue by nrllh** [Wox-launcher/Wox#1347]
![image](https://cloud.githubusercontent.com/assets/13475745/24779395/6475be38-1b30-11e7-816d-af7d0486634d.png)
I just downloaded the last update and then got the warning from the antivirus. Till now i didn't get something like that, when i downloaded wox.

**Comment by bao-qian** [comment]
Try download using browser or add wox to whitelist .

**Comment by bao-qian** [comment]
close due to no response.
