### ISSUE TITLE
[BrowserBookmark] improve bookmark search results

### ISSUE THREAD

**Issue by thecotne** [Wox-launcher/Wox#135]
![screenshot](http://i.imgur.com/IHucC8r.jpg)

and as an example of correct search result here is vimium search results
![screenshot](http://i.imgur.com/WcYHjIX.jpg)

the important thing is if bookmark has empty title his url is more importent then other-s urls and titles

**Comment by qianlifeng** [comment]
> the important thing is if bookmark has empty title his url is more importent then other-s urls and titles

I think it depends. But we do need to find some common rules to improve  the sorting of urls. Something like if a n url is shorter than others, then it should be more importent.

**Comment by thecotne** [comment]
> if a n url is shorter than others, then it should be more importent.

i agree

**Comment by bao-qian** [comment]
please try new release
https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196

let me know it fix or not.
