### ISSUE TITLE
Memory usage optimization for folder plugin

### ISSUE THREAD

**Issue by 46Leo** [Wox-launcher/Wox#1350]
Hi, I just downloaded and installed the latest version, 1.3.183 on Windows 10.
I have an issue with ram usage when browsing inside a folder with many images... ( like c:/user/screenshots )

Wox shows a little thumb for each image, but the more i scroll down between pics, the more ram it uses (few GB) ... 
How can i solve this problem? Is there a way to limit its usage of ram? 
I attatched a screenshot...

Thanks!! :)

![2017-04-07](https://cloud.githubusercontent.com/assets/27013456/24804399/9c281b36-1bae-11e7-9203-ddbd977a022e.png)

**Comment by bao-qian** [comment]
I need your query string

**Comment by bao-qian** [comment]
>  browsing inside a folder 

so you are using the folder plugin?

**Comment by 46Leo** [comment]
this is another screenshot about it.
i don't know if it is the folder plugin... maybe it is... i just type:  C:/ ..../ and so on....

![2017-04-07 1](https://cloud.githubusercontent.com/assets/27013456/24806150/32a74578-1bb4-11e7-991a-8cce95a5b3ce.png)

**Comment by bao-qian** [comment]
1. try https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. if 1 is not help, just don't use it this way, use everything plugin.
e.g. `Catture di schermata\`

**Comment by 46Leo** [comment]
not working... :(

i hope you can solve it, i found it a useful feature.... many times i search a folder and then i browse inside it, like you do in launchy pressing TAB button.... 

anyway, thanks for help! :)

**Comment by medoni** [comment]
For thumbnails, BitmapImage has a DecodePixelWidth/Height property. Maybe this reduces memory usage of large Images. 

https://msdn.microsoft.com/en-us/library/aa969769(v=vs.110).aspx

https://github.com/Wox-launcher/Wox/blob/e12635f32e4fb68f571c4e4e495d0f1267d16616/Wox.Infrastructure/Image/ImageLoader.cs#L134

**Comment by bao-qian** [comment]
@46Leo could you try https://ci.appveyor.com/project/happlebao/wox/build/1.3.439?

**Comment by 46Leo** [comment]
bad luck... :(
still very ram consuming...

has anyone else my same problem or it's just me ?

![2017-04-13](https://cloud.githubusercontent.com/assets/27013456/25020731/d795b59e-208f-11e7-818e-7782e0c83720.png)

**Comment by bao-qian** [comment]
Half memory though...

**Comment by bao-qian** [comment]
How many files you have in your folder?

**Comment by 46Leo** [comment]
> Half memory though...

well, not exactly, it depends on how long I scroll down... and then, even if I abort the research or if i just press Esc, it seems that it keeps everything in memory. Then, if i search something else in another directory (images) the ram starts growing again until I close or restart WOX....




> How many files you have in your folder?

Screenshot folder has 203 pics, 3840x1080, about 1MB each

**Comment by bao-qian** [comment]
ok I see the problem.
Feature request: let wpf load images from uri （or sth else) automatically instead manually load it into memory.

**Comment by lances101** [comment]
Please try this build from appveyor:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.509/artifacts

**Comment by 46Leo** [comment]
> Please try this build from appveyor:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.509/artifacts

I'm sorry for my late answer. 
It's working properly now, there's no more huge ram consumption.
Thanks a lot! 👍
