### ISSUE TITLE
System.IO.FileNotFoundException: 未能加载文件或程序集“Newtonsoft.Json, Version=8.0.0.0,

### ISSUE THREAD

**Issue by yyysuo** [Wox-launcher/Wox#1351]
WOX:1.3.424
OS:windows 10 pro 1607 x64

[2017-04-07.txt](https://github.com/Wox-launcher/Wox/files/906015/2017-04-07.txt)

**Comment by bao-qian** [comment]
试下删除
`%APPDATA%\Wox\Plugins\*Wox.Plugin.Express*`

**Comment by yyysuo** [comment]
确实是快递查询这个插件导致的
http://www.getwox.com/plugin/79

**Comment by BenTown** [comment]
快把这插件下架吧:)
