### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zxjack** [Wox-launcher/Wox#1354]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\zxjac\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/09/2017 00:26:51
Exception:
Wox.Plugin.WeiboPicBed
System.TypeLoadException
未能从程序集“Wox.Infrastructure, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.BaseStorage`1”。
   在 Wox.Plugin.WeiboPicBed.Settings.Settings_Loaded(Object sender, RoutedEventArgs e)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-04-09.txt](https://github.com/Wox-launcher/Wox/files/907622/2017-04-09.txt)

**Comment by bao-qian** [comment]
删除 C:\Users\zxjac\AppData\Roaming\Wox\Settings\Plugins\Switcheroo, 然后重装
