### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by jinpeng15800** [Wox-launcher/Wox#1355]
1.既然用wox就是为了键盘流，所以希望在选中某个文件后不需要鼠标右键来进行拓展操作，直接可以使用→来进行操作。
2.希望在右键（→）菜单中，出现有的管理员打开，打开文件夹，置顶，加入其他常见的邮件功能，比如复制，剪切，属性，复制路径等等，具体可以借鉴everything以及listary
3.希望在搜索结果中加入分类，程序/路径/文件夹等
4.希望在自定义查询热键中加入唤醒wox后的快速映射， 比如 我输入 wd  可以直接将我编辑好的我的文档的结果放在第一位，方便快速打开；再例如 xm 可以编辑映射到我的xmind软件 这种映射可以是 文件，文件夹，程序，或者网页甚至更多
5.可以加入关键词来搜索某一类文件 比如 folder 来搜索文件夹  pic 来搜索图片  例如： pic 壁纸  来搜索名字是壁纸的图片  （包块所有图片的文件类型）
6.是否可以在启动wox时自动启动everything（填写路径后）

@happlebao  现在wox已经很出色了，希望他越来越棒

**Comment by bao-qian** [comment]
1. ctrl+o / shift+enter
2. #1317 
3. 排列顺序是按照相关度的。可以给程序插件设置单独的快捷键。everything 文件和文件夹的区分有专门的符号 https://www.voidtools.com/support/everything/searching/ 
4. 多选几次结果会往前面排
5. *壁纸*.jpeg （可能要 beta 的 everything 版本
6. 不可能，everything 要 UAC

**Comment by jinpeng15800** [comment]
谢谢
