### ISSUE TITLE
“程序” 插件 无法索引根目录

### ISSUE THREAD

**Issue by ariakeumi** [Wox-launcher/Wox#1357]
无论硬盘根目录文件多少，都是一直在“索引中”。

Windows 10 

WOX 1.3.424

**Comment by bao-qian** [comment]
> 无论**硬盘**根目录文件多少，都是一直在“索引中”。

文件太多 卡死了
你只应该添加 **程序** 目录

**Comment by ariakeumi** [comment]
@happlebao 但是我的大量程序都放在根目录呀，在老版本中就不会这样，请问还有什么解决方法么？_(:3ゝ∠)_

**Comment by bao-qian** [comment]
你把 %APPDATA%\Wox\logs 删了，
然后再开，
然后上传 log 我看一看

**Comment by ariakeumi** [comment]
@happlebao  [http://7xkr1g.com1.z0.glb.clouddn.com/2017-04-10.txt](url)

**Comment by ariakeumi** [comment]
[2017-04-10.txt](https://github.com/Wox-launcher/Wox/files/908535/2017-04-10.txt)

@happlebao

**Comment by bao-qian** [comment]
相关 PR #1282
过段时间应该会修复

**Comment by ariakeumi** [comment]
辛苦了！

**Comment by bao-qian** [comment]
试一下
https://ci.appveyor.com/project/happlebao/wox/build/1.3.436/artifacts

**Comment by ariakeumi** [comment]
@happlebao 还是不行呢 _(:3ゝ∠)_
[2017-04-13.txt](https://github.com/Wox-launcher/Wox/files/917506/2017-04-13.txt)

**Comment by bao-qian** [comment]
这个呢？
https://ci.appveyor.com/project/happlebao/wox/build/1.3.410/artifacts
不行的话上传 log

**Comment by ariakeumi** [comment]
@happlebao  可以了(｢･ω･)｢

**Comment by bao-qian** [comment]
@ariakeumi 那看来我代码改错了，我再研究研究。。。。。。

**Comment by mrfmrf** [comment]
“程序” 插件索引不到程序
windows10
wox 1.3.442
[Uploading 2017-04-26.txt…]()

**Comment by mrfmrf** [comment]
[2017-04-26.txt](https://github.com/Wox-launcher/Wox/files/957546/2017-04-26.txt)

**Comment by mrfmrf** [comment]
@happlebao 重新安装也不行

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
