### ISSUE TITLE
last selection (e.g. which application was started)

### ISSUE THREAD

**Issue by 0x4a** [Wox-launcher/Wox#1358]
Is there a way/plugin to show the last n commands I entered?

I am currently migrating from FindAndRunRobot, and use the launcher primarily to run applications. It is nice to just select my most used programs from a list, without entering anything.

**Comment by bao-qian** [comment]
ctrl+h

**Comment by 0x4a** [comment]
more or less...
this duplicates my last *entry*, what I want, is my last *selection* (e.g. which application was started)

**Comment by bao-qian** [comment]
currently no.

**Comment by 0x4a** [comment]
Consider this a feature-request then ;-)
