### ISSUE TITLE
incorrect search results

### ISSUE THREAD

**Issue by thecotne** [Wox-launcher/Wox#136]
![screenshot](http://i.imgur.com/z0QQUNw.jpg)

**Comment by qianlifeng** [comment]
Seems our fuzzy finder is not so smart.

**Comment by qianlifeng** [comment]
I have changed our fuzzy finder item weight rule. It should be more accurate now. You can try again when next release.

**Comment by bao-qian** [comment]
I think this has already been fixed.
![w09r oww2z_4k1lv um i0i](https://cloud.githubusercontent.com/assets/1169912/10949812/b8257d90-832c-11e5-901e-71e9b20c8e23.png)

**Comment by thecotne** [comment]
@happlebao is not `Paint` more relevant to `paint` then `paint.net`?

**Comment by bao-qian** [comment]
@thecotne Yes, it is. But Wox is usable and this is not a **bug** now. It may improved in the future.

**Comment by bao-qian** [comment]
![bqrca 0w m v6r6gi88p o](https://cloud.githubusercontent.com/assets/1169912/11018827/54f47560-85d3-11e5-82c0-9df7faa16b61.png)

Hi, I think this already been fixed. please try the latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

**Comment by bao-qian** [comment]
They are compared as `Paint.lnk` and `paint.net.lnk`, so fuzzy matcher give them same score.
If we want to solve this, we need add one more field into `Program`, sth like `NameWithoutExtension`.

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15035055/f2b8d31c-1274-11e6-9e1a-a574addb7cb6.png)
should be fixed now.
reopen it if you have more questions.
