### ISSUE TITLE
"Couldn't aquire lock, is another instance running?" when manually update in settings

### ISSUE THREAD

**Issue by kindtree** [Wox-launcher/Wox#1362]
## Known problems for 1.3.424:

1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：Wox设置中的关于界面，点击检查更新，出现报错界面
3. Windows 版本：windows 10旗舰版
4. Exception：Wox设置中的关于界面，点击检查更新，出现报错界面
5. **整个** log 文件：
[Uploading 2017-04-10.txt…]()
6. 截图 （可选）：
![Uploading image.png…]()

**Comment by bao-qian** [comment]
重新上传日志和截图

**Comment by kindtree** [comment]
github无法上传txt文件，我把截图和log文件放到word文档中。
[Wox检查更新功能报错.docx](https://github.com/Wox-launcher/Wox/files/909585/Wox.docx)

**Comment by bao-qian** [comment]
如果是刚启动出现这个错误，
或者隔半小时这个错误不再出现，
忽略即可。
