### ISSUE TITLE
Wox will not hide on start or when launching at login

### ISSUE THREAD

**Issue by WolvenSpectre** [Wox-launcher/Wox#1363]
On Win10, problem exists with both Chocolatey and installer.

Settings are set for hide at launch (tried unchecking and rechecking) and hide on focus loss.

When it launches the input window opens on whichever of my 2 monitors the cursor is on, then will not hide when other windows are in focus.  It will hide when the input field is clicked on and then it looses focus and works normally.

The same happens on restarts, the shortcut, and using Classic Shell or Windows Search to launch it.

## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
**1. Wox version** ?????

**Comment by WolvenSpectre** [comment]
sorry, 1.3.183

**Comment by bao-qian** [comment]
try https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

**Comment by WolvenSpectre** [comment]
Thanks... will do.

**Comment by WolvenSpectre** [comment]
Still occurs on login.  Other instances fixed.  Also the not hiding on loss of focus after logging in is there too.

**Comment by bao-qian** [comment]
known bug #991

**Comment by WolvenSpectre** [comment]
Sorry for the bother... I searched for that and nothing came up.  If I have more issues with it I will put it there.  Thanks for the assistance.
