### ISSUE TITLE
建议更换下载地址

### ISSUE THREAD

**Issue by taolive** [Wox-launcher/Wox#1370]
建议更换下载地址：github-cloud.s3.amazonaws.com，这个地址在广州经常无法下载，频率太高了

**Comment by bao-qian** [comment]
某著名防火墙你不会不知道吧。。。？

**Comment by FlyingRadish** [comment]
虽然有墙的存在，还是建议针对国内用户提供一个更容易访问的下载方式

**Comment by Ramon403** [comment]
不仅仅广州，长沙电信也是无法访问
