### ISSUE TITLE
怎样完全重装Wox？program插件自动消失，又无法重装wox

### ISSUE THREAD

**Issue by god891006** [Wox-launcher/Wox#1371]
[2017-04-13.txt](https://github.com/Wox-launcher/Wox/files/918341/2017-04-13.txt)
版本：1.3.357
昨天还用的好好的，今天查找program插件消失，无法找到，但是\Wox\Settings\Settings.json里面以前设置的快捷键还在，通过快捷键调用却找不到。重装wox发现并不能修复相关问题，在wox插件库里面有找不到查找程序的插件。

wox实在太强大，但是bug还是不少，比如设置的快捷键本来已经用其他的代替，仍然会提示该快捷键已经被占用，在setting里面修改相应快捷键仍然仍然不能解决问题。

是否可以考虑一个备份设置的功能，尤其是在网页搜索上面，设置很花时间，还有就是自带的哪些插件应该也放在插件库里面，遇到我这样的问题，插件就找不到了，卸载有无法卸载干净，只能干瞪眼。

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
1. 程序插件问题 #1357  
2. 重置： 删除 %APPDATA%\Wox\Settings
3. 备份： #259
