### ISSUE TITLE
总是报Everything Service没有运行

### ISSUE THREAD

**Issue by Chigogo** [Wox-launcher/Wox#1375]
## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：每次搜索时
3. Windows 版本：Win10 专业版 1607 14393.1066
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：Windows 找不到该文件
6. 截图 （可选）：![截图20170415160558.png](https://ooo.0o0.ooo/2017/04/15/58f1d4ec9ea65.png)

**Comment by mkhalila** [comment]
I can also confirm that this issue exists, I am also running it on windows 10 - only installed yesterday.

Wox is incredibly powerful and usable as it is, but without file search working (this issue) it's difficult to fully migrate over to it/recommend it.

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/25066098/88de781a-2214-11e7-8c3e-0d0058383bde.png)

**Comment by Chigogo** [comment]
Do you mean that I need to install everything and python3 manually?

**Comment by bao-qian** [comment]
Yes

**Comment by Chigogo** [comment]
OK, Thanks. To be honest, that sounds weird.
