### ISSUE TITLE
[QUESTION] Will WOX support cmd argument again?

### ISSUE THREAD

**Issue by benyaminl** [Wox-launcher/Wox#1376]
I use wox as a windows shell replacer alongside with Emerge Desktop(Death Project, but still the best which work on Windows 7 x64), nah for now I use sendkeys method to show wox using leftwindowskey, and send keys using alt+shift+down. It's pain in the ass sometime that the sendkey stuck and causing other program doing something unexpected. My question is, is there any cmd argument for wox like the old wox? Thanks before...

**Comment by lances101** [comment]
Sorry, no. Not at this point. Maybe once Wox has a portable distribution this would be possible.

**Comment by bao-qian** [comment]
latest version has command argument support.
