### ISSUE TITLE
Nuget Install-Package Wox.Plugin Fail （失敗）

### ISSUE THREAD

**Issue by sd12582000** [Wox-launcher/Wox#1381]
USE **## visual studio community 2017**   
Please help

Install-Package : 無法安裝封裝 'Wox.Plugin 1.3.159'。  
您正嘗試將此封裝安裝到以 '.NETFramework,Version=v3.5' 為目標的專案，但該封裝不包含任何與架構相容的組件參考或內容檔。如需詳細資訊，請連絡封裝作者。
位於 線路:1 字元:1
\+ Install-Package Wox.Plugin
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    \+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
![default](https://cloud.githubusercontent.com/assets/1571554/25189635/4f617f6a-255c-11e7-96c9-44b73792e543.png)

**Comment by sameclub** [comment]
将 Target framework 改成 4.5.2 就可以了。

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
