### ISSUE TITLE
wox got an error

### ISSUE THREAD

**Issue by mddemir** [Wox-launcher/Wox#1384]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: pythonw.exe
Everything SDK Path: C:\Users\mdemir\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/20/2017 08:23:11
Exception:
mscorlib
System.IO.IOException
'Themes' yoluna erişim reddedildi.
   konum: System.IO.DirectoryInfo.MoveTo(String destDirName)
   konum: System.Threading.Tasks.Task.Execute()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs içinde: satır 234

[2017-04-20.txt](https://github.com/Wox-launcher/Wox/files/940547/2017-04-20.txt)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
