### ISSUE TITLE
UWP.ResourceFromPri|Load pri failed

### ISSUE THREAD

**Issue by Starxyz** [Wox-launcher/Wox#1385]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True

[2017-04-21.txt](https://github.com/Wox-launcher/Wox/files/945702/2017-04-21.txt)

**Comment by lances101** [comment]
This issue was created long ago and the log file attached does not contain the error mentioned.
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
