### ISSUE TITLE
wox error after windows update

### ISSUE THREAD

**Issue by optimusic** [Wox-launcher/Wox#1387]
1. Wox version: 1.3.183
2. OS Version: Microsoft Windows NT 10.0.14393.0
3. Date: 04/21/2017 17:26:26
4. Exception:
Wox.Plugin.Program
System.NullReferenceException
개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: Wox.Plugin.Program.Main.DefaultProgramSources() 파일 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:줄 136
   위치: Wox.Plugin.Program.Main.IndexPrograms() 파일 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:줄 102
   위치: Wox.Plugin.Program.Main.Init(PluginInitContext context) 파일 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:줄 94
   위치: Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 파일 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:줄 27
   위치: Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 파일 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:줄 96
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
