### ISSUE TITLE
How can hide program title in result list?

### ISSUE THREAD

**Issue by nrllh** [Wox-launcher/Wox#1388]
In earlier versions there was no title of any program. Now i get always titles. Is there anyway to hide it?

**Comment by lances101** [comment]
@NurullahDe what do you mean by program titles? Are you using Switcheroo?

**Comment by nrllh** [comment]
In query results at the latest version there is a new feature;
In result page there is also program description near each row





-------- Ursprüngliche Nachricht --------
Von: Boris Makogonyuk <notifications@github.com>
Datum: 20.05.17 15:16 (GMT+01:00)
An: Wox-launcher/Wox <Wox@noreply.github.com>
Cc: NurullahDe <nurullah.demir@studmail.w-hs.de>, Mention <mention@noreply.github.com>
Betreff: Re: [Wox-launcher/Wox] How can hide program title in result list? (#1388)


@NurullahDe<https://github.com/nurullahde> what do you mean by program titles? Are you using Switcheroo?

**Comment by lances101** [comment]
Could you provide a screenshot when possible? Thanks.

**Comment by nrllh** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/13475745/26279630/2fca5fc6-3db9-11e7-80c9-bc8b7c375ce1.png)
i don't want to get these titles, the file name is enough for me..

**Comment by lances101** [comment]
I cannot fix this right now, but I labeled your issue accordingly. Once we have time or somebody PRs this it will be included in the functionality of the plugin.

**Comment by Radd-max** [comment]
is there any update on this ?
