### ISSUE TITLE
Can't find some applications

### ISSUE THREAD

**Issue by huabin** [Wox-launcher/Wox#1390]
Wox can't find some applications, such as cmder

1. Wox version / commit number:     

    1.3.424

2. Steps to **reproduce** the bug:
    - install wox
    - install cmder
    - open wox, and search cmder
    - can't be found

3. Windows version:
    
    Windows 10

**Comment by lances101** [comment]
@hzb not a bug. cmder does not create any entries in Windows' registry or Start Menu folders.
If you want Wox to see cmder (or any other executable that is not installed via an installer) you have two options:

- **[Recommended]** Add just cmder.exe to your start menu via Windows' context menu. And hit reindex in Wox
![image](https://cloud.githubusercontent.com/assets/4784785/26276331/a17c3fe8-3d75-11e7-90fa-1f5fc775458a.png)


- Add the folder where you have cmder as an indexed folder to the Folder plugin.
![image](https://cloud.githubusercontent.com/assets/4784785/26276275/770d1bca-3d74-11e7-8128-365d69f170e9.png)
