### ISSUE TITLE
一直显示Everything Service 没有运行

### ISSUE THREAD

**Issue by davidan106** [Wox-launcher/Wox#1391]
1. Wox 版本 / commit number：1.3.357&1.3.424
2. 如何**重现** bug：搜索程序都是这样
3. Windows 版本：Windows10 Enterprise ver.
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：程序目录中没有上述路径
6. 截图 （可选）：
![image](https://cloud.githubusercontent.com/assets/25627232/25369607/c35d8166-29b7-11e7-89bb-11fea0e96743.png)

**Comment by teddy-hoo** [comment]
我也遇到了同样的问题，重装了几次也不行。
windows版本：win7 service pack 1

**Comment by WooodHead** [comment]
试试单独安装Everything程序试试？只是建议一下

**Comment by AjiMIde** [comment]
win10 64bit 遇到此问题，单独安装 everything 并设置开机启动，问题解决，附 everything 地址：
[http://www.voidtools.com/](http://www.voidtools.com/)
下载相关程序安装即可。

**Comment by jinpeng15800** [comment]
wox需要运行everything才能用哦，需要安装everything 并在使用wox的时候同时开启everything

**Comment by Ramon403** [comment]
我也是这样的，经过测试，需要运行et才行，要不然把et安装成服务

**Comment by tomexou** [comment]
"Everything" is an optional plugin. Remove it if you don't need.
I just use "Program Plugin" only.

**Comment by ghost** [comment]
单独安装以后可以使用，不过我的wox没法搜索文件，不知道为啥

**Comment by mymartin** [comment]
下载了最新版的 everything 和 Wox 。
1. 安装everything时将“以管理员权限运行”修改成“everything服务”，然后继续安装即可。
2. everything安装后，进入设置里面勾选“everything服务”。
![image](https://user-images.githubusercontent.com/6276117/29763589-5cc7bdac-8c06-11e7-9c65-751b9fcfd2a7.png)

最终效果：
![image](https://user-images.githubusercontent.com/6276117/29763615-7a853180-8c06-11e7-91f9-83656ba3eb88.png)

**Comment by westfly** [comment]
从1.3 切换到最新1.4版本之后就可以了

**Comment by CrazyPassion** [comment]
If your system is 32bit, you need 32bit version of everything. Same with 64bit system.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
new build has full installer, which bundled everything
