### ISSUE TITLE
Remember last launch location ignored

### ISSUE THREAD

**Issue by andrew-james-heard** [Wox-launcher/Wox#1393]
1. Wox version 1.3.424
2. Steps to **reproduce** the bug: drag window to new location, reboot, active Wox, is displayed at default mid-screen position
3. Windows version: 10, Home 64-bit
4. Exception:
5. **whole** log file: is attached
[2017-04-26.txt](https://github.com/Wox-launcher/Wox/files/956849/2017-04-26.txt)
`):
6. Screenshot (optional):

**Comment by gutierri** [comment]
I'm facing the same problem, I made a gif to demonstrate

![wox remember](https://user-images.githubusercontent.com/1111356/32245076-c010de1a-be61-11e7-92e0-058dfb88308c.gif)

**Comment by lances101** [comment]
This is because Wox saves it's settings only after closing the Settings window and the position is considered a setting. I know, it's not user-friendly. 

Workaround for now: move Wox to new position, open Settings, close settings. 
Wox will save the position.

**Comment by lances101** [comment]
7e51f1a fixes this. Try latest builds from the dev branch https://ci.appveyor.com/project/happlebao/wox/build/1.3.501/artifacts

I will merge dev into master and draft a new release soon enough.

**Comment by bao-qian** [comment]
close due to fixed

**Comment by sveco** [comment]
Hi. Using Wox 1.4.1196, issue is still there after restart. Wox remembers position only for one session, then resets to middle of screen after restart of app or reboot. Setting windows open/close does not help. How hard is to just save last position and then read it on start.
