### ISSUE TITLE
Wox cannot access cache files (pinyin.cache, image.cache, etc)

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1394]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 04/26/2017 10:50:42
Exception:
mscorlib
System.IO.IOException
Kan geen toegang krijgen tot het bestand C:\Users\Dirk\AppData\Roaming\Wox\Cache\Image.cache omdat het wordt gebruikt door een ander proces.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bij System.IO.FileStream..ctor(String path, FileMode mode)
   bij Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:regel 99
   bij Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:regel 44
   bij Wox.Infrastructure.Image.ImageLoader.Initialize() in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:regel 37
   bij Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:regel 52
   bij Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:regel 31
   bij System.Windows.Application.OnStartup(StartupEventArgs e)
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2017-04-26.txt](https://github.com/Wox-launcher/Wox/files/957750/2017-04-26.txt)

**Comment by lances101** [comment]
A temporal fix is to exit Wox and to delete all your cache files located at `%appdata%/Wox`. Although please note that this seems to be a recurring error.

I have been unable to reproduce this error locally and therefore **need user input** as to what is causing it. 

If anybody has ProcessHacker or any other software that allows to track the usage of a file installed, please check what is accessing the cache file when Wox throws the exception.

**Comment by lances101** [comment]
Build 1.3.467 has this fixed now. A new version containing this fix will be released soon. 

Meanwhile you can download a version where this is fixed from [Appveyor here](https://ci.appveyor.com/project/happlebao/wox/build/1.3.467/artifacts).

**Comment by jhdxr** [comment]
@lances101 
@bao-qian 

I suggest mark 467 or 475 (compiled from the latest commit of master) as pre-release to prevent more issues like this.

**Comment by lances101** [comment]
@jhdxr 
[Drafted 1.3.475 as prerelease. ](https://github.com/Wox-launcher/Wox/releases/tag/1.3.475)

**Comment by lovemacs** [comment]
开机启动没用,一直都是手动启动....ﾍ()ﾟ∀ﾟﾍ)))))～
