### ISSUE TITLE
Mysterious scrolling

### ISSUE THREAD

**Issue by mikeyww** [Wox-launcher/Wox#1398]
I have set Wox to select the last query.  I frequently find that when I activate Wox, the cursor has, by itself, scrolled down 2 or 3 lines (entries).  I have no idea why this happens, but it is irritating!

My log file is attached here [2017-04-30.txt](https://github.com/Wox-launcher/Wox/files/967232/2017-04-30.txt).

Mike

________________________________

Wox version: 1.3.424.
Computer: TOSHIBA PORTEGE R930
Operating system: Microsoft Windows 7 Professional 64-bit Version 6.1.7601
Service pack: 1.0
Total physical memory (MB): 16262
Available physical memory (MB): 5777
Processor: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz 64-bit
Processor type: Intel64 Family 6 Model 58 Stepping 9
BIOS: TOSHIBA Default System BIOS Version 6.80  
Motherboard: TOSHIBA PORTEGE R930 Version A0
Display name: Intel(R) HD Graphics 4000
Display resolution: 1366 x 768
Display dots per inch (DPI): 120

**Comment by lances101** [comment]
This issue was created long ago and the log file does not contain any relevant information.
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
