### ISSUE TITLE
Pugin not displaying results when added functions

### ISSUE THREAD

**Issue by OscarLewis** [Wox-launcher/Wox#1400]
Hello, I am trying to make a simple python wox plug in (got to start somewhere) and am having trouble getting wox to open the url or even display the result. This does display a result when I do not include any of the openURL or JsonRPCAction code but once I add it nothing shows up when I enter the keyword besides "activate plug in". Any advice is super useful, thanks!

CODE:
import webbrowser
import requests
from wox import Wox,WoxAPI

#Your class must inherit from Wox base class https://github.com/qianlifeng/Wox/blob/master/PythonHome/wox.py
#The wox class here did some works to simplify the communication between Wox and python plugin.
class Genius(Wox):

  def query(self, query):
        url = "www.genius.com"
        results = []
       results.append({
        "Title": title ,
        "SubTitle":title,
        "IcoPath":"Images/app.ico",
        "JsonRPCAction":{
          "method": "openUrl",
          "parameters":[url],
          "dontHideAfterAction":True
          }
        })
        return results

   def openURL(self, url):
        webbrowser.open(url)
        #todo:doesn't work when move this line up 
        WoxAPI.change_query(url)

        
if __name__ == "__main__":
    Genius()

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
