### ISSUE TITLE
Please add Remove USB confirmation

### ISSUE THREAD

**Issue by Mnaukal** [Wox-launcher/Wox#1407]
When I use `reu` command to safely unplug my USB drive, I would like to see some kind of confirmation dialog (message), that the safe unplug from system was successful (as you can see when you safe unplug through the system tray).
![screenshot 2017-05-06 11 20 18](https://cloud.githubusercontent.com/assets/9487592/25771305/801f8634-324e-11e7-8780-a859cc40be0c.png)

**Comment by JohnTheGr8** [comment]
This is the main Wox repository, you want to open this issue at the plugin's repository here: [allanpk716/RemoveUSB](https://github.com/allanpk716/RemoveUSB)

**Comment by Mnaukal** [comment]
Sorry.
