### ISSUE TITLE
Command Prompt closes

### ISSUE THREAD

**Issue by mihai-vlc** [Wox-launcher/Wox#141]
Windows 7 X64
I have checked Do not close command prompt 
but after the command is finished the cmd is still closes.
I can't seem to run commands like `cd /`
And is there any way to specify the default folder to run that command ?

**Comment by sevenam** [comment]
Did some brief testing on this.
It seems to depend on what folder the command prompt application resides in.
As far as I could see all commands that reside in C:\Windows\System32 would keep the command prompt window open, while an .exe in c:\program files\ would not.

Tested this with nmap.exe by copying it from c:\program files\nmap to c:\windows\system32. After copying it to c:\windows\system32 it would keep the command prompt window open. Before copying the window was closed at completion.

**Comment by ningfei** [comment]
In CMD.cs, ShellRun from MainWindow.xaml.cs is used to execute cmds. But in both the two places, no leaveCmdOpen param is given. That may be why the setting "Do not close Command Prompt after command execution" in the CMD plugin has no effect at all?

**Comment by happlebao** [comment]
Releated: #332

**Comment by bao-qian** [comment]
Hi, here are some updates.
Which style do you prefer?
1. type command, then pause, then exit. ![1](http://i.imgur.com/ZnD4Jzi.png)
2. type command, then stay in the cmd. ![2](http://i.imgur.com/YFfSms7.png)

@ningfei @ionutvmi @sevenam @monsteryip

**Comment by mihai-vlc** [comment]
@happlebao I think it will be better to make that a preference so people can toggle to two styles

**Comment by bao-qian** [comment]
@ionutvmi please suggest a name for each style, I'm not a native speaker...

**Comment by mihai-vlc** [comment]
maybe a dropdown or radio buttons that something like:

After command exectution:  
- Close the cmd window
- Wait for a key press before closing
- Keep the cmd window open

**Comment by ningfei** [comment]
Cool! This is exactly what this "leave open" option should be. Would be cool if we can have both style 1&2.

**Comment by monsteryip** [comment]
nice！！！

**Comment by bao-qian** [comment]
hi this has been implemented
please try new release https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735
