### ISSUE TITLE
Web Search plugin sometimes omits last character once the request reaches chrome.

### ISSUE THREAD

**Issue by 1Mark** [Wox-launcher/Wox#1414]
1. Wox version / commit number: 1.3.424:
2. Steps to **reproduce** the bug:

Sometimes I will search using the "Web searches" feature. I start Wox then type "g dmz"

![](https://i.gyazo.com/36444bf1faa3fe78af2232d29f624ba8.png)

Then I press enter but when google search results come up its just searched for "dm" instead of dmz.

![](https://i.gyazo.com/ea7fcd4af72184d6c7cfbf7a8934b811.png)

Note I didn't use the up and down arrows, I just pressed enter. So it should search for "dmz". 

This happens about 1 in 10 times. Therefore, I can't easily reproduce the issue, but it has happened several times so I'm sure its not me making the mistake.

**Comment by lances101** [comment]
@1Mark I know you are saying that the issue only happens rarely, but I couldn't reproduce it so far. I've labeled this as a bug.

**Comment by 1Mark** [comment]
That's fine I can't reproduce it at all either, it happens randomly on occasion.

**Comment by bao-qian** [comment]
Closed due to no further info and cannot reproduce
