### ISSUE TITLE
[Folder Plugin] Ctrl + Enter doesn't work

### ISSUE THREAD

**Issue by arcanjoserra** [Wox-launcher/Wox#1415]
the ctrl + enter command just doesnt work for me

i have to ctrl + click

**Comment by BilibiliHentai** [comment]
I run into this problem too.

**Comment by lances101** [comment]
@arcanjoserra @BilibiliHentai what <kbd>Ctrl</kbd>+<kbd>Enter</kbd> command are you talking about?
Wox has a context menu bound to <kbd>Shift</kbd>+<kbd>Enter</kbd> and mouse right clicks.

**Comment by arcanjoserra** [comment]
It's actually the command for the folder plugin. 

You type "fd" then select the folder then hit ctrl + é enter. That's what the box says, but only ctrl + click works on that context.

**Comment by lances101** [comment]
**Confirmed.** <kbd>Ctrl</kbd>+<kbd>Enter</kbd> does nothing for results coming from the folder plugin.

**Comment by arcanjoserra** [comment]
Thank you so much for having the patience to address this @lances101

**Comment by amanhigh** [comment]
Noticing Same Issue.
