### ISSUE TITLE
Unhandled exception when using python plugin

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#142]
Fiirst i use v2ex, and it occured. Then, i wrote a very simple one like v2ex plugin (just no libs imported except json), and it remained the same.

Windows8.1 64bit. Python 2.7.6

the log

Date：2014-07-27 18:06:20,779 Level：ERROR Msg：Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Wox.JsonRPC.JsonRPCQueryResponseModel' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
Date：2014-07-27 18:12:46,659 Level：ERROR Msg：Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Wox.JsonRPC.JsonRPCQueryResponseModel' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.

**Comment by roose** [comment]
I guess you are using an old version of plugin. Did you read this: [Create Plugins using Python](https://github.com/qianlifeng/Wox/wiki/Create-Plugins-using-Python)?

**Comment by qianlifeng** [comment]
Yes, We have changed the python plugin API. Check it out [https://github.com/qianlifeng/Wox/wiki/Create-Plugins-using-Python](https://github.com/qianlifeng/Wox/wiki/Create-Plugins-using-Python)
