### ISSUE TITLE
程序插件丢失（program plugin miss ）

### ISSUE THREAD

**Issue by etertops** [Wox-launcher/Wox#1421]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：Wox-1.3.424
2. 如何**重现** bug：安装1.3.424就出现这个问题
3. Windows 版本：win10
4. Exception：程序插件丢失，重新安装也不会装上去！！！！！！
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：
![12345](https://cloud.githubusercontent.com/assets/10496380/26116446/c1ff15de-3a95-11e7-85ab-c95fbf36f040.jpg)

**Comment by FelixHuoEZ** [comment]
I have the same problem, so is there a solution for that?

**Comment by zxszx4** [comment]
我测试了下，用什么360卸载之类的卸载不管用，找了下注册表，相关信息删除也不管用，后来我把“C:\Users\Alan\AppData\Local\Wox”和“C:\Users\Alan\AppData\Roaming\Wox”两个文件夹删除后重启，重装后该插件能够恢复并正常运行，不知道你们行不行。

**Comment by lances101** [comment]
Try reinstalling Wox. Do so by following these steps:
- exit Wox
- delete the contents of the following folders
  - `%appdata%/Wox`
  - `%localappdata%/Wox`
- download Wox from [the releases page](https://github.com/Wox-launcher/Wox/releases)
- launch the executable as you would any other .exe

If you keep having any problems reopen this issue.
