### ISSUE TITLE
Web Search - Multi sites/One Keyboard?

### ISSUE THREAD

**Issue by muzikman** [Wox-launcher/Wox#1424]
Can Wox search multiple websites with one keyword?

**Comment by lances101** [comment]
Nope, this is not possible. 

Also, how do you expect this to work? Your idea is that Wox will open multiple websites with a specific web query?

**Comment by muzikman** [comment]
Yes, open up a browser window for each query based on one keyword.  A couple of similar apps do it already.  Executor (which isn't current) and keypirinha but the configuration is all through .ini files for each plugin, making it difficult. 

Associate the trigger keyword to multiple URLs then type the query string, launching each URL in a separate window. Throw all of the GUI config in a collection or something like that.

**Comment by muzikman** [comment]
I forget which language your plugins are coded in but I'm a web developer, not a windows dev.

**Comment by muzikman** [comment]
with keypirinha, after setting it up in the config file for the plugin. I would assign multiple URLs to one trigger keyword. After typing in the trigger keyword, I would hit tab, then type in the query.  

It launches x amount of URL associated with the trigger keyword.  It's a really nice feature and not many apps can do that, as I explained in an earlier post.  I just hate configuring everything through .ini files.

**Comment by Gabrieljean454fgd** [comment]
very good idea!
Wox is a great think for windows and thank you developer/community for this great work.
I think an another way to improve is had copy/path in result search for file folder on right click (like everything copy full name)

Thanks.
