### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by Ramon403** [Wox-launcher/Wox#1428]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：一直在
3. Windows 版本：win10 x64

问题1： 你的getwox网站大陆访问太慢，我用 “wpm install 有道” 经常搜索不出插件，偶尔能搜出来
问题2： 即便搜索出来，点击安装之后也无反应，基本无法安装，不要说是墙的问题，给wox设置了http代理走我的ss也不行

**Comment by immafrady** [comment]
相同问题！

**Comment by geosmart** [comment]
相同问题！

wox远程plugin库是不再维护了吗？这么好的工具不要死掉啊

**Comment by geosmart** [comment]
http://www.getwox.com/官网都打不开

**Comment by ian-ie** [comment]
+1

**Comment by bao-qian** [comment]
should be resolved now. open new issue if still have problem
