### ISSUE TITLE
不是有效的win32应用程序，有32位的吗（还是xp）

### ISSUE THREAD

**Issue by ethanzhongyi** [Wox-launcher/Wox#1429]
## Known problems for 1.3.183:

不是有效的win32应用程序

**Comment by lances101** [comment]
This issue was created long ago and there is no log file attached. 
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
