### ISSUE TITLE
Feedback about the new getwox website. http://new.getwox.com

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#143]
The new website of [getwox.com](http://new.getwox.com) is almost done. you guys have some comments on this?  
We will change the feature description in the home page. For now, I just "Copy" that from alfred.

The new website allow users to upload their plugins and themes to getwox.com (no github required anymore). And we force users to upload a plugin preview and icon when they uploading plugin.    

Free free to give your style or functional suggestions.

**Comment by mihai-vlc** [comment]
page load takes too long http://puu.sh/auJ7m/04c786443b.png
sometimes i get these errors http://puu.sh/auJkK/661f051b9c.png

**Comment by orzFly** [comment]
@ionutvmi Qiniu is a CDN especially for China networks. Their servers for overseas users are really bad. This is really a problem for users outside China.

**Comment by aaroncampf** [comment]
I quite like the website, but maybe it could use a video overview/tutorial.
I am trying to find a person to make a video for another project I'm working on.
Maybe they could make a video for the website (assuming I find someone at all)?

Also, I think there should be a link to the GitHub on there (maybe the standard fork "me on github" message)

**Comment by thecotne** [comment]
@qianlifeng remove dropdown menus it's better to go to themes gallery and have theme builder and upload theme links in there 

also put plugin installation command in input or textarea so it's easier to select and avoids accidentally selecting something else

**Comment by aaroncampf** [comment]
Baergo http://www.youtube.com/user/DCBaergo said he would be willing to make a video on Wox.
I think we could greatly benefit from having a video somewhere on the website and the GitHub.

Any thoughts and/or suggestions?
I think he should make the video talkative and friendly, rather than the usual sterile videos you normally see.

**Comment by qianlifeng** [comment]
@aaroncampf Sounds greate,

**Comment by CoenraadS** [comment]
I think it looks amazing.

Just some small errors:
(browse) plugin => plugins
(browse) theme => themes

Launch apps and files on your `computer` without lifting your hands off the keyboard. Wox learns which apps you use most and prioritises them when you search.

Customise the default searches in Wox's setting`s` window to make them fit your everyday needs.

Show off your design skills`,` share your themes with friends, and import their themes.

**Comment by qianlifeng** [comment]
@CoenraadS  thx for pointing out those typos.

**Comment by qianlifeng** [comment]
I have launch the new website for Wox. https://www.getwox.com

**Comment by thecotne** [comment]
@qianlifeng title tag is missing

**Comment by qianlifeng** [comment]
@thecotne Thx, Working on it.

**Comment by roose** [comment]
@qianlifeng Add to site please opengraph and twitter card tags - title, description and image in main page, and plugin name, description and image on single plugin page
