### ISSUE TITLE
Wox version: 1.3.183

### ISSUE THREAD

**Issue by tedcampa** [Wox-launcher/Wox#1430]
[2017-05-22.txt](https://github.com/Wox-launcher/Wox/files/1020128/2017-05-22.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.15063.0
Date: 05/22/2017 22:24:39
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unterminated string. Expected delimiter: ". Path 'Items[79].Query', line 321, position 10.
   à Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   à Newtonsoft.Json.JsonTextReader.ParseProperty()
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) dans C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:ligne 58
   à Wox.Infrastructure.Storage.JsonStrorage`1.Load() dans C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:ligne 40
   à Wox.ViewModel.MainViewModel..ctor(Settings settings) dans C:\projects\wox\Wox\ViewModel\MainViewModel.cs:ligne 62
   à Wox.App.<OnStartup>b__8_0() dans C:\projects\wox\Wox\App.xaml.cs:ligne 49
   à Wox.Infrastructure.Stopwatch.Normal(String name, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 28
   à System.Windows.Application.OnStartup(StartupEventArgs e)
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
