### ISSUE TITLE
C:\Users\liangbiwen\AppData\Roaming\Wox\Logs\1.3.424\2017-05-24.txt

### ISSUE THREAD

**Issue by Hior247** [Wox-launcher/Wox#1433]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 05/24/2017 08:37:37
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\liangbiwen\AppData\Roaming\Wox\Cache\Pinyin.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Alphabet.<>c.<Initialize>b__3_0() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 25
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 Wox.Infrastructure.Alphabet.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 29
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 54
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

[2017-05-16.txt](https://github.com/Wox-launcher/Wox/files/1024097/2017-05-16.txt

)

**Comment by lances101** [comment]
Duplicate of #1394
