### ISSUE TITLE
Wox stuck in old search query additionnal panel

### ISSUE THREAD

**Issue by Lyptik** [Wox-launcher/Wox#1434]
1. Wox version / commit number:  1.3.424
3. Windows version:
win10 v1607 / 14393.1198
2. Steps to **reproduce** the bug:

- summon wox
- type a query
- summon panel with shift+enter
- end your query / close wox
- summon wox
- type a query
-> you will have no result because wox is stuck on the panel

to get around this

- erase your query
- (you will see the panel)
- close it by pressing escape
-> you are in normal state again

**Comment by JiaHong-Lee** [comment]
Environment:
Wox version: Same as above
Windows version: Same as above

Can confirm this issue on my laptop. Would be great if Wox can automatically return to the general query panel on every activation. 

Perhaps the developers can consider separating the panel state (which should be reset on every activation) from the string query state (which should return the last string queried to the panel). Just an opinion though. 

Kudos to the developers for making such a great product!
