### ISSUE TITLE
我希望能添加让托盘图标符合win10风格的选项

### ISSUE THREAD

**Issue by inoribea** [Wox-launcher/Wox#1437]
或许可以用自定义的形式……

**Comment by smallNERD** [comment]
图标文件的存储位置  `C:\Users\kongq\AppData\Local\Wox\app-1.3.183\Images\`
可以找相应的代码 修改

**Comment by NERD-k** [comment]
图标文件的存储位置 `C:\Users\用户\AppData\Local\Wox\app-1.3.183\Images\`
可以找相应的代码 修改
