### ISSUE TITLE
Feature Request: Alt Tab support.

### ISSUE THREAD

**Issue by CoenraadS** [Wox-launcher/Wox#144]
Hello

I think it would be a neat feature to add an option to hook alt-tab, and use Wox to select the Windows.

An empty query should simply show all windows in the list, to also make it possible to tab between windows with one hand.

There are various c# alt-tab replacements on GitHub with which collaboration may be possible.
i.e. https://github.com/christianrondeau/GoToWindow

**Comment by aaroncampf** [comment]
How is this feature any different/better then just using Alt-Tab

**Comment by thecotne** [comment]
@aaroncampf it's much better believe me

after clicking alt+tab you can search/filter window list which is better then clicking tab again and again

**Comment by CoenraadS** [comment]
@aaroncampf
![1](http://i.imgur.com/U6w5qfz.png)

![2](http://i.imgur.com/sDdiiPM.png)

**Comment by aaroncampf** [comment]
I will ask qianlifeng and see if he approves the extention, if so, I will start working on it.

**Comment by qianlifeng** [comment]
@aaroncampf  Seems @orzFly has made a similar plugin [switcheroo](https://github.com/orzfly/wox.plugin.switcheroo)

**Comment by thecotne** [comment]
can it replace alt+tab?

**Comment by qianlifeng** [comment]
@thecotne  You can use [AHK](http://www.autohotkey.com/) to replace alt + tab:

```
LAlt & Tab::
    Run,wox.exe query "win "
Return
```

**Comment by lnksz** [comment]
Dear Devs, 

I would be also interested in such feature  :+1: 
@qianlifeng I tried with AHK, but it does not show me anything. What should it show?

Thanks!
