### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1441]
I'm getting the following compilation error:
"The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?)

It looks like I'm missing required assemblies in "C:\Program Files (x86)\Windows Kits\10\References". Can anyone tell me how I can download/install these missing assemblies? I have already installed Windows 10 SDK.  I also tried googling the answer without any luck.

![Screenshot of compilation error](https://cloud.githubusercontent.com/assets/1163664/26530154/6b6d14b2-439d-11e7-9278-09fc9bb6e11f.png)

**Comment by tomexou** [comment]
Yes, I have downloaded the latest source code in VS2017 today, it also has built failed. 
I try to modify the tool to be a portable edition.

**Comment by lances101** [comment]
You need to install the Windows 10 SDK. 
https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
We use it for UWP applications. Another option is to unload the Program plugin project in the solution and compile (I used to do that myself in an environment where I could not afford to install the dev kit). 

Reopen if your problem persists after installing the SDK.
