### ISSUE TITLE
绑定在任务打开，失去焦点。

### ISSUE THREAD

**Issue by wataru-c** [Wox-launcher/Wox#1442]
## 中文 / Chinese

1. Wox 版本：1.3.424
2. Windows 版本：Win 10

BUG：把Wox绑定到任务栏并打开时，没法聚焦到焦点。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
