### ISSUE TITLE
载入速度慢，希望能优化速度。

### ISSUE THREAD

**Issue by inoribea** [Wox-launcher/Wox#1444]
输入字符后需要等待1至2秒才加载出列表。
虽然不是多数情况，还是希望能优化下。

**Comment by xiaoyuervae** [comment]
之前速度还是挺好的，现在搜索速度变得奇慢无比，不知道是什么原因。

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

I need full log files so that Wox load times are present.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
