### ISSUE TITLE
Only basic calculator functions work.

### ISSUE THREAD

**Issue by jfbleach** [Wox-launcher/Wox#1446]

**Comment by jfbleach** [comment]
This pages shows the following should work: 
https://github.com/Wox-launcher/Wox/wiki/Default-Plugins.-Calculator
(sqrt(2)*5)/sin(0.5)  

But none of the functions like sqrt work only basic match operators

**Comment by lances101** [comment]
What version of Wox are you using?

Seems to work fine on v1.3.424:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/4784785/26711522/23649c04-4761-11e7-80d9-be9f81df91c9.gif)

**Comment by jfbleach** [comment]
I got it working, I hadn't installed python - this page (https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Installation) still lists it as optional, but python must be required to get all of the calc functions working.
