### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by ssPARTRICKss** [Wox-launcher/Wox#1447]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 06/02/2017 12:19:35
Exception:
System.Drawing
System.ComponentModel.Win32Exception
参数错误。
   在 System.Drawing.Icon.Initialize(Int32 width, Int32 height)
[2017-06-02.txt](https://github.com/Wox-launcher/Wox/files/1046674/2017-06-02.txt)

**Comment by lances101** [comment]
We do not support 1.3.183 anymore although it is the "latest" release technically. Please try build 1.3.424 https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
