### ISSUE TITLE
不会搜索已安装程序，我记得以前是可以的

### ISSUE THREAD

**Issue by feimiao** [Wox-launcher/Wox#1448]
1.3.424版
不会搜索已安装程序，我记得以前是可以的。
Win10
[2017-06-02.txt](https://github.com/Wox-launcher/Wox/files/1047021/2017-06-02.txt)

![image](https://cloud.githubusercontent.com/assets/18380365/26716232/3a79ed8c-47ab-11e7-86e1-2306c6dd760b.png)

**Comment by smallNERD** [comment]
#  在插件“程序” 添加 你装文件的 文件夹，应该能解决问题。
## 我猜测原来能搜索到是插件 “程序” 提供的， 但它只索引了 开始菜单 和 注册表， 我的电脑在更新系统和Wox也出现了你说的问题，用上面我说的方法解决了，我猜测 有可能是 Win10的更新 修改了 开始菜单 和 注册表的 一些 运行机制。

**Comment by NERD-k** [comment]
## 在插件“程序” 添加 你装文件的 文件夹，应该能解决问题。

我猜测原来能搜索到是插件 “程序” 提供的， 但它只索引了 开始菜单 和 注册表， 我的电脑在更新系统和Wox也出现了你说的问题，用上面我说的方法解决了，我猜测 有可能是 Win10的更新 修改了 开始菜单 和 注册表的 一些 运行机制。

**Comment by feimiao** [comment]
感谢 smallNERD~~~
发现是我的插件“程序”丢失了。
主程序覆盖安装不行，清理干净以前的所有文件全新安装就好了。
具体是什么导致的情况不明。
![image](https://user-images.githubusercontent.com/18380365/27034133-daae4e5a-4fae-11e7-9f19-c3b9055499b9.png)
