### ISSUE TITLE
Wox crash when wpm install 有道翻译 私Key版

### ISSUE THREAD

**Issue by aiplay** [Wox-launcher/Wox#1452]
## ** Here is the exception message**
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Users\xujh\AppData\Local\Programs\Python\Python36\pythonw.exe
Everything SDK Path: C:\Users\xujh\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/06/2017 11:00:32
Exception:
ICSharpCode.SharpZipLib
ICSharpCode.SharpZipLib.SharpZipBaseException
Unexpected EOF
   在 ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()
   在 ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   在 ICSharpCode.SharpZipLib.Zip.ZipInputStream.BodyRead(Byte[] buffer, Int32 offset, Int32 count)
   在 Wox.Core.Plugin.PluginInstaller.UnZip(String zipedFile, String strDirectory, Boolean overWrite) 位置 C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:行号 185
   在 Wox.Core.Plugin.PluginInstaller.Install(String path) 位置 C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:行号 23
   在 Wox.PublicAPIInstance.<>c__DisplayClass13_0.<InstallPlugin>b__0() 位置 C:\projects\wox\Wox\PublicAPIInstance.cs:行号 112
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_1.<ResultForInstallPlugin>b__0(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 170
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Try reinstalling Wox. Do so by following these steps:
- exit Wox
- delete the contents of the following folders
  - `%appdata%/Wox`
  - `%localappdata%/Wox`
- download Wox from [the releases page](https://github.com/Wox-launcher/Wox/releases)
- launch the executable as you would any other .exe

If you keep having any problems reopen this issue.
