### ISSUE TITLE
Standard icon used for apps even though icon is embedded in .exe

### ISSUE THREAD

**Issue by Cantello** [Wox-launcher/Wox#1455]
1. Wox version / commit number: 1.3.424
2. Steps to **reproduce** the bug: Start Wox, re-index (not really necessary), search for e.g. PSPad, see result list
3. Windows version: Win 7, SP1
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`): [2017-06-07.txt](https://github.com/Wox-launcher/Wox/files/1057154/2017-06-07.txt)
6. Screenshot (optional): 
![2017-06-07 09_21_50-wox](https://user-images.githubusercontent.com/594700/26866733-cd2c0146-4b62-11e7-8690-0711cee2ef6a.png)

![2017-06-07 09_22_49-pspad editor](https://user-images.githubusercontent.com/594700/26866772-fb343086-4b62-11e7-808b-d00bba251a7e.png)
![2017-06-07 09_23_06-pspad editor](https://user-images.githubusercontent.com/594700/26866774-fcc31624-4b62-11e7-8998-22c0d10d4e91.png)

**Comment by SwedishChef** [comment]
Still the same issue with 1.3.524

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
