### ISSUE TITLE
Add a feature like Alfred to use number to select the search result

### ISSUE THREAD

**Issue by oseack** [Wox-launcher/Wox#1458]
v1.3.424

Please see attached screenshot. I really wish Wox can have a similar feature. It can reduce the keyboard clicks to enter expected result. 
For example, if the expected item is at row 8, I either need tab through the top or I need to enter more characters to get to the result. If Wox let just press 8, that's going to save a lot of typing.

Thanks.

![image](https://user-images.githubusercontent.com/3401968/26993230-3c94dfde-4d30-11e7-95c7-c528d764de70.png)

![image](https://user-images.githubusercontent.com/3401968/26993466-2199d238-4d31-11e7-9298-628f96134a2d.png)

**Comment by lances101** [comment]
Wox already has this feature. Modifier key is Alt.
