### ISSUE TITLE
建议：可以考虑做一个通过名称来杀死进程的插件

### ISSUE THREAD

**Issue by RocStone** [Wox-launcher/Wox#1460]
可以考虑做一个通过名称来杀死进程的插件
一般来说cmd里杀进程要用pid，如果能直接用进程名称来杀就比较方便了
一个小建议而已，还是要多谢你的工作，软件很好用，给你star

**Comment by jhdxr** [comment]
`taskkill /im explorer.exe`

**Comment by lances101** [comment]
Wox already has a plugin for that. Install it by querying: 
`wpm install Wox.Plugin.ProcessKiller`
