### ISSUE TITLE
Wox does not respect last query settings

### ISSUE THREAD

**Issue by Lomacar** [Wox-launcher/Wox#1462]
1. Wox version / commit number: 1.3.424
3. Windows version: 10 build 1511
2. Steps to **reproduce** the bug:

- Do a search with Wox.
- Do another search with Wox
- Even though the default setting is for Wox to select the last query, it is not selected, so when you start typing a new query it just adds text to the previous query.
- In Wox general settings set "Last Query Style" to "Empty last Query"
- Try another search with Wox
- The previous search is still there

**Comment by Lomacar** [comment]
Update. Wox now works correctly for me. My computer was restarted in between, so I guess that was enough to fix it. But it was a real problem after first installing it.

**Comment by divmain** [comment]
I'm experiencing this issue as well.  Restart did not resolve.

**Comment by wigglestheholy** [comment]
I am experiencing this issue as well. Same version.

**Comment by dimitrior** [comment]
Same issue, same version.

**Comment by dimitrior** [comment]
#1491

**Comment by dimitrior** [comment]
OK, I was experiencing the same issue (same Wox version). I just managed to solve this issue. Restarted PC - didn't work at first. Then I set the Last Query Style drop-down to each of its 3 settings, 1 by 1. This still did not work, but having set it to "Empty Last Query", I closed Wox and re-opened it. Now it works! 
#1491 @wigglestheholy  @divmain

**Comment by lances101** [comment]
7e51f1a fixes this. Try latest builds from the dev branch https://ci.appveyor.com/project/happlebao/wox/build/1.3.501/artifacts 

I will merge dev into master and draft a new release soon enough. 

Reopen if still experiencing issues.

**Comment by shaneknysh** [comment]
I am still getting this behavior with Wox 1.3.524

**Comment by Lotiara** [comment]
Yes, me too

**Comment by ghost** [comment]
Yes, me too I am still getting this behavior with Wox 1.3.524

**Comment by s7726** [comment]
Seeing this on latest 1.3.524 as well.
Worst thing about it is it keeps the `ctrl-o` screen from the last command, so it's more keystrokes to get out of that, and then start typing the next query.
I have tried restarting wox in between settings as well

**Comment by UrosOgrizovic** [comment]
@dimitrior Selecting each value for 'Last Query Style' one by one, then choosing 'Empty last Query', then restarting Wox (v 1.3.524) also did the trick for me - thank you! :) By the way, just to be crystal clear, no PC restart was necessary.

**Comment by AzeezAbir** [comment]
So the final solution is to set the last query style to select last query and then restart wox and you'll see wox respecting you.
