### ISSUE TITLE
文档里说自带Python

### ISSUE THREAD

**Issue by SetoKaiba** [Wox-launcher/Wox#1463]
> Wox支持使用Python进行插件的开发。Wox自带了一个打包的Python及其标准库，所以使用Python 插件的用户不必自己再安装Python环境。同时，Wox还打包了requests和beautifulsoup4两个库， 方便用户进行网络访问与解析。

但是实际测试好像所有Python插件都无效。。

**Comment by NERD-k** [comment]
### 仿佛并没有
 在设置页面要我们选择python的路径。
有可能插件里调用了 Python的非标准库，导致插件失效。

**Comment by SetoKaiba** [comment]
嗯，仿佛并没有。。装了python后，然后就有效了。。没装python之前，连自带的helloworld的python都没效

**Comment by lances101** [comment]
Python is not distributed with Wox at the moment. 
Right now you need to install Python manually.

**Comment by bao-qian** [comment]
you can install python by using full installer now.

**Comment by bao-qian** [comment]
try new release now.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
