### ISSUE TITLE
【新功能建议】建议允许手动设置插件路径，即绿色版 Wox

### ISSUE THREAD

**Issue by IceWeet** [Wox-launcher/Wox#1465]
环境搭建不易，建议wox可以作为绿色版使用，但目前没看到更改插件安装目录和其他app数据目录的地方。

**Comment by rickywu** [comment]
最好是和App放一个目录，这样重装系统也不丢失配置

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
new build support portable mode by add a `UserData` along with wox.exe

**Comment by bao-qian** [comment]
#629
