### ISSUE TITLE
软件图标未显示

### ISSUE THREAD

**Issue by scoyzhao** [Wox-launcher/Wox#1481]
开启以后，软件图标不显示
![image](https://user-images.githubusercontent.com/26707590/27269530-4a8a1700-54ea-11e7-8106-fb6fc1555fa0.png)
请问该如何解决这个问题 @orzFly

**Comment by FanNengHu** [comment]
我也遇到了同样的问题，系统是win7 64位。希望有人解答一下。

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by lances101** [comment]
This issue was created long ago and there is no log file attached. 
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
