### ISSUE TITLE
Auto-Startup not working with Space in Windows-Username

### ISSUE THREAD

**Issue by commaender** [Wox-launcher/Wox#1486]
I'm using Wox v1.3.424
When activating the option "Start Wox on system startup", it creates an entry in registry HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run.

Problem: My Windows Username is "Firstname Lastname", with a space in the username.
Wox then creates the registry key with path:
C:\Users\Firstname Lastname\AppData\Local\Wox\app-1.3.424\Wox.exe

But because of the space char, the path must be surrounded by quotes!

Windows interpretes this as "Run application "Firstname" with Parameters "Lastname\AppData\..."
When booting windows, I get the error "File Firstname not found", and Wox isn't starting.

Editing the registry key doesn't help, because Wox recreates it with missing quotes again.

**Comment by lances101** [comment]
Fixed on dev branch as of f223568. I will be merging dev into master soon enough.
Meanwhile, you can download a build that includes this fix from appveyor:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.502/artifacts

**Comment by bao-qian** [comment]
close due to fixed
