### ISSUE TITLE
Everything 服务没有运行，实际Everything是打开的

### ISSUE THREAD

**Issue by FuYung** [Wox-launcher/Wox#1487]
1.3.424版本，window10

**Comment by tanshanli** [comment]
everthing打开了不代表everthing服务也是开的。cmd-》> services.msc--》检查是否有everthing服务。
没有可以考虑重装everthing或查看everthing设置是否得当。反之，重装wox试试。
（我目前装的最新版也是win10运行，所以排除BUG可能）

**Comment by FuYung** [comment]
everything服务是开启的。
重装wox，升级最新版everything解决。

**Comment by ErgeAIA** [comment]
Everthing还要单独装一个？不是内置的？

**Comment by bao-qian** [comment]
close due to the origin issue has been solved
