### ISSUE TITLE
ERR :: Path including space in their name

### ISSUE THREAD

**Issue by Ra0EL** [Wox-launcher/Wox#149]
Hi,

it seems Wox cannot handle properly file or folder names having space characters.
E.g. :    `C:\My Bin\Wox`

This raises error message when I try to use some plugins, like HackerNews.
As soon as I type :
`hn <tab>`
I have this error message :

> Wox has occurred an error that can't be handled.
> `\<path\>\pythonw.exe` can't open file `\<path_truncated_at_first_space\>`: [Errno 2] No such file or directory.

Any fix ?

**Comment by qianlifeng** [comment]
I have fixed this bug.  Checkout the latest codes.
