### ISSUE TITLE
Clean input box on 'Hide Wox'

### ISSUE THREAD

**Issue by amychta** [Wox-launcher/Wox#1491]
Would be nice to have option to configure Wox in a way, so each run I see empty input field (instead of word that I typed on previous Wox run)

**Comment by fareloz** [comment]
Settings -> Last Query Style -> Empty last query

**Comment by amychta** [comment]
Could you please tell me where exactly you see that settings? On general Tab?

**OS: Windows 10,  
Wox version 1.3.183**

![image](https://user-images.githubusercontent.com/3037946/27488281-2ec31adc-583f-11e7-8cc2-22455d1a004f.png)

**Comment by fareloz** [comment]
I'm using latest pre-release v1.3.424
The option is under Auto update on the page

**Comment by amychta** [comment]
@fareloz Thank you!

**Comment by kalvn** [comment]
I have the option on my side configured on **Empty last Query** but it doesn't work. Any idea why?

**Comment by dimitrior** [comment]
I was have the same problem. @kalvn see #1462

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by dolphin-cat** [comment]
same problem latest release it won't clear the search result, i tried deleting the wox folder
