### ISSUE TITLE
wox 更新的时候出错

### ISSUE THREAD

**Issue by leiaoo** [Wox-launcher/Wox#1495]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\realy\AppData\Roaming\Wox\Logs\1.3.424\2017-06-28.txt
2. copy below exception message

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16193.0
IntPtr Length: 8
x64: True

Python Path: C:\Python27\pythonw.exe
Everything SDK Path: C:\Users\realy\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/28/2017 19:48:50
Exception:
Squirrel
System.Exception
Couldn't acquire lock, is another instance running
   在 Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 778
   在 Squirrel.UpdateManager.<acquireUpdateLock>b__32_0() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 274
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__1.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 41
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.SettingWindow.<OnCheckUpdates>d__24.MoveNext() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 309
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

上面是错误日志
我每次点一下更新，就会报这样的错误
平时用的时候，也偶尔会报这样的错误
![image](https://user-images.githubusercontent.com/8576385/27635848-55eb59e4-5c3b-11e7-8835-042e86f3f95e.png)

**Comment by lances101** [comment]
Duplicate of #1396
