### ISSUE TITLE
Add Nodejs plugin support.

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#15]
I didn't find existed libraries that we can use in .Net.

**Comment by kosz78** [comment]
May be this can be used https://github.com/tjanczuk/edge#how-to-call-nodejs-from-c

**Comment by kosz78** [comment]
Also it will be great to support other script language for example:
- http://www.csscript.net/
- https://github.com/fholm/IronJS/

**Comment by qianlifeng** [comment]
@orzFly 
Click to view a large version.
<img src="http://scott-tuchuang.qiniudn.com/wox%20invoke.jpg" />  

<img src="http://scott-tuchuang.qiniudn.com/wox_rpc_query.jpg" />

**Comment by orzFly** [comment]
I think ActionJsonRPC should be a sub-object instead of string

**Comment by qianlifeng** [comment]
yes, it is.

**Comment by rickmed** [comment]
Does Nodejs env comes with as of version 1.2.605?

**Comment by bao-qian** [comment]
@ricmed205 sorry, no. Won't happen this year.

**Comment by qianlifeng** [comment]
already support in v2
