### ISSUE TITLE
[Suggestion] Use tab to cycle switch candidates below search box

### ISSUE THREAD

**Issue by txchen** [Wox-launcher/Wox#150]
Now if we type something in the search box, and if there are multiple result items, we have to use arrow key to select. Which means, your right hand must move to type arrow key.

If tab key can also do the job, it would be convenient and fast.

**Comment by qianlifeng** [comment]
We will add this feature in V1.1.0. Thx for your suggestion

**Comment by txchen** [comment]
Thanks a lot for taking this request:)
