### ISSUE TITLE
Hibernate Command

### ISSUE THREAD

**Issue by sepehrhosseini** [Wox-launcher/Wox#1503]
Hi

is there any chance that you'd add **Hibernate** Command to your _Awesome Launcher_
Wox does anything I need.... except this one!

Thanks

**Comment by jacostag** [comment]
I would also like that command, but in the mean time, @sepehrHosseini  you can use the shell plugin and type: shutdown /h 
That will hibernate the machine if is enabled.

**Comment by vasselai** [comment]
I really really miss this one. Is there any chance that it could get included, e.g. within the System Commands plugin? It would be a great addition.

**Comment by MuizNadeem** [comment]
> I would also like that command, but in the mean time, @sepehrHosseini you can use the shell plugin and type: shutdown /h
> That will hibernate the machine if is enabled.

Alternately you can also create a batch file called hibernate.bat and put shutdown /h inside the file. this will save you from accidentally shutting down your PC
