### ISSUE TITLE
wox 启动 chrome 无法打开已经启动的进程，只能是重新打开

### ISSUE THREAD

**Issue by huaf22** [Wox-launcher/Wox#1507]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug： chrome 浏览器启动后最小化，使其在后台运行，任务栏有chrome 图标，这时如果还需要打开 chrome 时， 用 wox 启动 chrome 结果是重新打开一个 chrome 进程而不是重新显示已经启动chrome 页面
3. Windows 版本：Windows 10

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5006161/27899751-639368de-61e0-11e7-9953-36a05c8424bd.gif)

**Comment by tiagopotencia** [comment]
It happens with some apps that can have multiple instances (for example, it doesn't happen with Spotify). Will be good to have an option to open a already opened window or create a new instance of the application. I want to fork this project to create a pull request with this feature :)

**Comment by bluesky129** [comment]
你这个录制全屏的gif是什么工具？

**Comment by huaf22** [comment]
@bluesky129  FastStone Capture

**Comment by bluesky129** [comment]
@huaf22 多谢，但是我发现录制视频格式没法设置成gif。默认是wmv的，你是如何设置的，还是后面其他啥工具转的？

**Comment by pzsdev** [comment]
安装这个插件：wpm install Switcheroo for Wox
默认触发关键字为 win
