### ISSUE TITLE
Wox对输入无响应

### ISSUE THREAD

**Issue by Alovez** [Wox-launcher/Wox#1509]
提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：
Wox对输入不做任何提示
3. Windows 版本：
Windows 7
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
[2017-07-07.txt](https://github.com/Wox-launcher/Wox/files/1129820/2017-07-07.txt)
6. 截图 （可选）：
![default](https://user-images.githubusercontent.com/10412290/27940849-ea354360-62ff-11e7-9e03-b3b139df4e9b.JPG)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
