### ISSUE TITLE
路径中具有非法字符。

### ISSUE THREAD

**Issue by inernoro** [Wox-launcher/Wox#1513]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：Wox-1.3.424.exe
2. 如何**重现** bug：打开就报错
3. Windows 版本：windows10
4. Exception：
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\inernoro\AppData\Roaming\Wox\Logs\1.3.424\2017-07-12.txt
2. copy below exception message

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 07/12/2017 20:13:37
Exception:
mscorlib
System.ArgumentException
路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2)
   在 Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 119
   在 Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 22
   在 Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 85
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
[2017-07-12.txt](https://github.com/Wox-launcher/Wox/files/1141906/2017-07-12.txt)

6. 截图 （可选）：

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
