### ISSUE TITLE
Search Results in the order of Plugin Priorities

### ISSUE THREAD

**Issue by onlineth** [Wox-launcher/Wox#1517]
Hello, I have installed Wox a few days ago and I think it's awesome. One feature though that is missing (or have I not found it?) is a way to organize my plugins of what I want to show up first.

For instance, I have a desktop application called X, when I type in X, folder name's, emails, and finally, the application (it's a shortcut on the desktop so it's a .lnk file) will show up. This could apply to a range of search queries other than just desktop applications.

What would be nice (and kind of necessary) is it take the plugins installed in Wox, and list them on preference in an order. Then, when I perform a search, it will like the results from the various plugins based on the order it appears in the settings.

**Comment by lances101** [comment]
<kbd>Shift</kbd>+<kbd>Enter</kbd> calls the context menu where you can set it as TopMost. 

Reopen the issue if you meant a different thing.
