### ISSUE TITLE
关键字提示插件无效

### ISSUE THREAD

**Issue by VictoriousRaptor** [Wox-launcher/Wox#1519]
1. Wox 版本 / commit number：
1.3.424
2. 如何**重现** bug：
一直存在
3. Windows 版本：
10.14393.1480
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：

[2017-07-20.txt](https://github.com/Wox-launcher/Wox/files/1161500/2017-07-20.txt)

PS：本人很久没有使用wox，因此不确定是插件问题还是bug，是插件更新了没有以前的效果？我记得以前只要打入命令的一部分就会弹出提示

另外似乎任何用"*"关键字触发的插件都无法被正确触发

**Comment by lances101** [comment]
Try deleting Wox data files. You can do so by following these steps:
- exit Wox
- delete the contents of the following folders
  - `%appdata%/Wox`
  - `%localappdata%/Wox`
- launch Wox

If you keep having any problems reopen this issue.
