### ISSUE TITLE
使用everything插件搜索到文件或文件夹后按enter出错

### ISSUE THREAD

**Issue by chris-peng** [Wox-launcher/Wox#153]
如题，wox直接崩溃，错误如下

System.MissingMethodException: 找不到方法:“System.Action Wox.Plugin.PluginInitContext.get_HideApp()”...

**Comment by russelg** [comment]
This happens due to the API changes. The deprecation part is never 
activated and it calls get_<method>() instead.

**Comment by chris-peng** [comment]
没有办法解决吗？

**Comment by russelg** [comment]
I'll try submit a fixed build.

**Comment by qianlifeng** [comment]
@russelg I'm working on it.

**Comment by russelg** [comment]
Oh alright, thanks.

**Comment by qianlifeng** [comment]
@chris-peng  Done. try `wpm install everything` to upgrade

**Comment by chris-peng** [comment]
可以了，谢谢啊
