### ISSUE TITLE
Everything plugin macro feature

### ISSUE THREAD

**Issue by BrijeshPanicker** [Wox-launcher/Wox#1536]
Hi,
Thanks for this wonderful software.
I am trying to search through Everything plugin using their macro feature eg(audio: or  pic:  )
But it doesnt work through wox
Eg: if i search the term **video:abc** nothing shows up. 
As soon as I put the colon character the search stops working.
If I search the same term using Everything gui it works there.
Doesnt wox support searching with macros feature?

**Comment by lzq2357** [comment]
i want this feature too...      maybe  wox's everything plugin need update,i guess

**Comment by lgoose** [comment]
I know it's not close to the same thing, but you can set up a custom hotkey with the extensions that you want to search for in everything (ie XLS on my end) and it works fairly well.

Not a full fledged work around, but definitely gets the job done for smaller searches.
