### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by Stufra** [Wox-launcher/Wox#1538]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: 
Date: 08/02/2017 15:21:53
Exception:
mscorlib
System.Reflection.TargetInvocationException
Ein Aufrufziel hat einen Ausnahmefehler verursacht.
   bei System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   bei System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   bei System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   bei System.Runtime.Serialization.ObjectManager.DoFixups()
   bei System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   bei System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   bei System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   bei System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   bei System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   bei System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   bei Wox.Properties.Resources.get_app() in C:\projects\wox\Wox\Properties\Resources.Designer.cs:Zeile 68.
   bei Wox.MainWindow.InitializeNotifyIcon() in C:\projects\wox\Wox\MainWindow.xaml.cs:Zeile 103.
   bei System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   bei System.Windows.FrameworkElement.TryFireInitialized()
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
