### ISSUE TITLE
"This single-instance application could not connect to the original instance" when restart Wox for plugin install with wpm.

### ISSUE THREAD

**Issue by russelg** [Wox-launcher/Wox#154]
When I install a plugin and restart Wox, I get this error.
## Exception

```
Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException: This single-instance application could not connect to the original instance.
   Source: Microsoft.VisualBasic
   TargetAssembly: Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   TargetModule: Microsoft.VisualBasic.DLL
   TargetSite: Void Run(System.String[])
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at Wox.EntryPoint.Entry(String[] args) in c:\Users\Patchouli Knowledge\Wox\Wox\App.xaml.cs:line 37
   at Wox.EntryPoint.Main(String[] args) in c:\Users\Patchouli Knowledge\Wox\Wox\App.xaml.cs:line 31

```

**Comment by qianlifeng** [comment]
I have this kind of errors too when restarting Wox. Try to find a solution.

**Comment by russelg** [comment]
http://social.msdn.microsoft.com/Forums/vstudio/en-US/14f8eb38-e261-4c84-8b16-0e1a43d89e17/wpf-single-application-and-restart-trouble?forum=wpf

http://stackoverflow.com/a/6806011/1984170

You might be able to find some solutions here. I think to fix this, the way to restart Wox needs to be changed. I'm not good at C# so I cannot over an actual solution here.

**Comment by bao-qian** [comment]
May I know which plugin you are trying to install?

**Comment by bao-qian** [comment]
#322

**Comment by bao-qian** [comment]
Hi, I refactored the logic of restart. use `ping` to test existence of Wox will cause more bugs in the future.
Please try with build [1.2.592](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.592/artifacts) and provide feedbacks.

@qianlifeng @russelg
