### ISSUE TITLE
插件可自定义取消多选几次排到最靠前机制

### ISSUE THREAD

**Issue by iwaller** [Wox-launcher/Wox#1541]
能否针对某个插件，取消对结果多选几次排到前面的机制，比如有个插件：Clipboard History，功能是管理剪贴板复制历史，期望每次最新复制都排到最前面，但是当前不是，经测试发现，插件返回的是正常的排序，但Wox在接收到插件数据后，又按选择次数进行了重排序，而这种机制，对Clipboard History这种插件是不合适的。

所以建议： 能开放让插件选择是否需要根据选择次数进行重排序，可以默认进行重排序，但也可以通过配置不进行重排序，让插件开发者决定。

> Wox version: 1.3.183

问题截图如下:
![image](https://user-images.githubusercontent.com/12227282/28909886-f43a81c8-785c-11e7-87cb-0791e6dabee6.png)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.

**Comment by kongtianyi** [comment]
I faced the same problem, I need to show orderly result, but the result be reordered by Wox. I'm using the lastest version. @lances101 @iwaller @qianlifeng
