### ISSUE TITLE
windows 8.1 WOX突然不支持应用程序搜索 

### ISSUE THREAD

**Issue by wupengju** [Wox-launcher/Wox#1544]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：最新版本
2. 如何**重现** bug：下载最新版本，安装（安装竟然没有任何选择文件夹的提示就自动安装完成了）
3. Windows 版本：8.1
4. Exception：没有报错，就是搜索不了其他的应用程序，搜索结果展示的是电脑设置相关的
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：
![image](https://user-images.githubusercontent.com/16716231/28999814-de25aed4-7a88-11e7-9928-874d8d862191.png)

**Comment by Bpazy** [comment]
我出现了同样的问题，在查看了日志之后，我发现这个问题是因为Program这个插件加载失败了
![qq 20170827142248](https://user-images.githubusercontent.com/9838749/29747630-4b239900-8b33-11e7-92a4-bfa53768c44d.png)

删掉对应文件即可，会重新自动创建。

**Comment by lances101** [comment]
Duplicate of #1394
