### ISSUE TITLE
Translate Plugin Fails to Display Arabic Characters

### ISSUE THREAD

**Issue by AmrEldib** [Wox-launcher/Wox#1545]
1. Wox version / commit number: **1.3.424**
2. Steps to reproduce the bug:
- Try to translate any English word to Arabic using `tr en ar word` 
- Notice that I use `tr` as short for the translate plugin
- Arabic word isn't displayed correctly
- When using other plugins (like Everything), Arabic words show up correctly.
3. Windows version: **10 Build 16257**
4. Exception: **N/A**
5. whole log file （`%APPDATA%\Wox\Logs\version\date.txt`): N/A
6. Screenshot (optional): 
![image](https://user-images.githubusercontent.com/769272/29010636-8f6c210c-7ae1-11e7-88c8-c105e3e3adc0.png)

**Comment by lances101** [comment]
There are many translation plugins for Wox, but none of them is directly supported by the Wox organization. I cannot tell by this screenshot which one you are using. 

Please create an issue in the corresponding GitHub repository.
