### ISSUE TITLE
Dash.doc无法使用

### ISSUE THREAD

**Issue by ojeo** [Wox-launcher/Wox#155]
插件安装完，按教程https://github.com/qianlifeng/Wox.Plugins
将doc下载后目录如下
Wox\Plugins\431b6287-b9a6-420c-a098-0645c8da9a61\Docset\Python2.docset\

结果没效果呀
而且看你源码，如果没有Docset会自己创建这个文件夹的，结果也没自动创建
是不是插件有问题？

**Comment by qianlifeng** [comment]
@ojeo 请使用最新版的Wox再看看

**Comment by Abirdcfly** [comment]
我遇到了同样的问题。

**Comment by qianlifeng** [comment]
如果还有此问题，可以提到https://github.com/qianlifeng/Wox.Plugin.Doc.
