### ISSUE TITLE
HHKB 键盘快捷键支持

### ISSUE THREAD

**Issue by hongliang5316** [Wox-launcher/Wox#1550]
Hello:
   我目前用HHKB键盘工作在windows上, 想设置该软件的启动快捷键为ctrl+space, 但是设置的时候同时按住ctrl+space 出现的是  
![image](https://user-images.githubusercontent.com/13626322/29103159-7e1023ca-7cf0-11e7-9f6a-b246a11750cd.png)
　有人有解决的办法吗？

**Comment by lances101** [comment]
Hotkey refactoring is still on its way here - #459 
Please follow that issue.
