### ISSUE TITLE
更新后wox总是占用很多内存

### ISSUE THREAD

**Issue by sabuli** [Wox-launcher/Wox#1559]
Wox 版本  1.3.424
日常使用中，搜索过东西之后，内存飙高
Windows 版本：win10家庭版 版本 10.0.15063 版本 15063

5. **整个** log 文件 
[2017-08-14.txt](https://github.com/Wox-launcher/Wox/files/1221366/2017-08-14.txt)

（`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：
![image](https://user-images.githubusercontent.com/16255782/29259859-69e14418-80f8-11e7-8882-6fed9b5f8287.png)

**Comment by sabuli** [comment]
安装v1.3.357版本同样出现一打开内存就疯狂飙高的情况，原因可能是什么呢？电脑内文件太多吗？

**Comment by jhdxr** [comment]
请尝试 https://ci.appveyor.com/project/happlebao/wox/build/1.3.462/artifacts   这个build对你是否适用。相关报告请回复到 #1683  谢谢
