### ISSUE TITLE
插件出错导致wox崩溃

### ISSUE THREAD

**Issue by Q-E-D** [Wox-launcher/Wox#156]
Wox.Plugin.Switcheroo插件在最新版本的wox中出现异常:
https://github.com/orzFly/Wox.Plugin.Switcheroo/issues/1

**插件无法使用的同时，Wox崩溃！**

**Comment by HerringtonDarkholme** [comment]
It seems to be caused by this refactoring.

https://github.com/qianlifeng/Wox/blob/aa7724df613396c05b8441e358db80ad9986f03b/Wox.Plugin/PluginInitContext.cs

**Comment by qianlifeng** [comment]
如果插件有问题，请联系插件作者修改。

**Comment by HerringtonDarkholme** [comment]
https://github.com/orzFly/Wox.Plugin.Switcheroo/issues/1#issuecomment-53954893
插件作者就丢了句NuGet不更新劳资就不改的意思呢…
https://www.nuget.org/packages/Wox.Plugin
