### ISSUE TITLE
请每次都定位在第一条

### ISSUE THREAD

**Issue by teraStars** [Wox-launcher/Wox#1563]
## Known problems for 1.3.424:
经常性发生wox莫名其妙给我定位到后面的N条去了，于是经常搞错。
后来我才发现是由于鼠标位置的问题。如果我鼠标位置刚好在下拉框出来的位置时，它就会跑到鼠标位置所在的地方。
比如现在我的操作。我按alt+空格，然后输入gt，其它没有做任何操作。我本来是想选国泰君安的，但因为我原来鼠标出现在那个位置，结果wox自动给我选了第四条的gta5。
![qq 20170819005834](https://user-images.githubusercontent.com/7426499/29469242-fdcc1b88-8479-11e7-8d21-ae5e954bbefa.jpg)

**Comment by lances101** [comment]
Duplicate of #975
