### ISSUE TITLE
Bug：can't instead of Win+R

### ISSUE THREAD

**Issue by haohao20030214** [Wox-launcher/Wox#1564]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：
**first open the "instead of Win+R"option**
![1](https://user-images.githubusercontent.com/6049048/29492288-980fdb82-85a9-11e7-8648-d8ea45b7d4d7.PNG)

**than press Win+R**
![2](https://user-images.githubusercontent.com/6049048/29492313-5e66a446-85aa-11e7-8db1-0d7dda6b8a97.PNG)

3. Windows 版本：windows 10 Education
4. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
[2017-08-20.txt](https://github.com/Wox-launcher/Wox/files/1236861/2017-08-20.txt)

**Comment by lances101** [comment]
Windows 10 Education edition is limited in terms of the available APIs. 
Best suggestion I have is to try launching Wox as Administrator.
