### ISSUE TITLE
Installed Wox, wpm doesn't work in CMD.exe

### ISSUE THREAD

**Issue by invious** [Wox-launcher/Wox#1567]
How do I get wpm to work? I get, `Wpm is not recognized as an internal or external command ...`

**Comment by javanli** [comment]
You can use `wpm` in Wox like this.
![image](http://opkq28qwn.bkt.clouddn.com/FoK7RgAIoIFAhJgSX6SdTkBipLd5)

**Comment by lances101** [comment]
Closed. Author went silent.

**Comment by dank8** [comment]
@javanli could you please convert the image to text. The image has been lost.
