### ISSUE TITLE
Feature request: Do not open a new window if the app is already running.

### ISSUE THREAD

**Issue by hdavidzhu** [Wox-launcher/Wox#1570]
It would be awesome if Wox did not start a new window when the application is already running. For instance, when I try to open Chrome, Google Chrome opens a new window. Instead, what I prefer is if it brought my existing window into focus like in macOS.

**Comment by DrBones** [comment]
This is also a feature I desire! 

Unfortunately, this seems to be tied to how Windows works. When a program is started, a new instance is opened, except if the program handles that itself (like e.g. Sublime Text or VS Code). 

If you use only one virtual Desktop I might recommend the switcheroo plugin. It does require the knowledge if the window is actually open and does not open it if, it is not.

Thus not really a perfect solution but for things like Chrome - which I have usually always open - it has some of the Alfred style that I am so desperately trying to emulate.

Lets hope someone figures out how to combine switcheroo and Wox smartly,

Cheers

**Comment by lances101** [comment]
Wox only tells the system "run this executable", it does not really do much else.

As @DrBones said, this is how Windows works. There was also a discussion on the same topic before, but I cannot find the issue right now.

**Comment by dotCipher** [comment]
Any updates on this feature? I would love to see it too :)

**Comment by chaselambda** [comment]
I find that the windows search opens up the current app, so that hints to me that this is possible

**Comment by dechimp** [comment]
I know this is unrelated, but if you are _searching_ for something using chrome, you can open those searches in a new tab on the existing window by:
Plugin > Web Searches > Open search in: New tab
