### ISSUE TITLE
Wox 无法启动

### ISSUE THREAD

**Issue by wanyuanyang** [Wox-launcher/Wox#1571]
Wox version: 1.3.357
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
Python Path: 
Everything SDK Path: 
Date: 09/01/2017 08:43:57
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\wan\AppData\Roaming\Wox\Cache\Pinyin.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Alphabet.<>c.<Initialize>b__3_0() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 25
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 Wox.Infrastructure.Alphabet.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 29
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 51
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lizhuangs** [comment]
同样的错误。


Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Administrator\AppData\Roaming\Wox\Logs\1.3.424\2017-09-03.txt
2. copy below exception message

Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.3.9600.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 09/03/2017 13:42:31
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\Administrator\AppData\Roaming\Wox\Cache\Pinyin.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Alphabet.<>c.<Initialize>b__3_0() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 25
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 Wox.Infrastructure.Alphabet.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Alphabet.cs:行号 29
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 54
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by NoahDragon** [comment]
可以使用Process Explorer查看哪个进程占用了`C:\Users\wan\AppData\Roaming\Wox\Cache\Pinyin.cache`文件，关掉那个进程就好了。

**Comment by CoderChow1994** [comment]
把Image.cache删了就正常了。

**Comment by lizhuangs** [comment]
@CoderChow1994 没用的,删除了下次又出现了.我已经重复好多次了.心累.

**Comment by lizhuangs** [comment]
@NoahDragon 查了,没有进程在使用它,手动可以直接删除那个文件.我也是无语了.

**Comment by CoderChow1994** [comment]
@lizhuangs 我一次就好了，之后不会出错了，出搓再删呗。。。

**Comment by lances101** [comment]
Duplicate of #1394 

You can keep track of the problem in the mentioned issue.
