### ISSUE TITLE
主题不能调整字体大小

### ISSUE THREAD

**Issue by lizhuangs** [Wox-launcher/Wox#1572]
官网界面有个在线设置主题很不错，但实际软件中字体太小了。切换主体那里只能修改字体，不能修改字体大小和行高，要是有这个就更好了。

**Comment by SYSU-SU** [comment]
字体大小可以在base.xml代码中修改fontsize来改变，可能也需要微调一下窗口的边距看起来会更好

**Comment by bao-qian** [comment]
you can make custom theme file, check base.xaml
