### ISSUE TITLE
wox无法退出

### ISSUE THREAD

**Issue by lizhuangs** [Wox-launcher/Wox#1578]
点右下角的退出，或者输入exit退出都没法真正的退出，任务管理器中wox.exe还在，导致你再点击wox.exe程序的时候根本打不开程序，必须先将任务管理器中的wox.exe杀掉。
然后如果输入restart wox的话，直接程序崩了。
系统环境是win10 1703

说实话，wox挺好用的一个软件，只是问题太多了。现在维护的我发现好像就happybao一个人了，感觉好可惜。

**Comment by lances101** [comment]
Please follow #1752 on the status of this issue.
