### ISSUE TITLE
不妨使用NTFS索引查找

### ISSUE THREAD

**Issue by lkytal** [Wox-launcher/Wox#158]
输入命令的时候还是显著的感到有些延迟啊... 不妨像listary一样用ntfs索引查找, 速度很快

**Comment by qianlifeng** [comment]
Wox是事先索引的，所以慢应该与索引无关。之所以慢（显示卡顿）应该是因为加载每个item图片的时候造成的。这个问题已经尝试做了一些改进，但是还没完全解决。SSD上看起来会好很多

**Comment by byzeus2014** [comment]
我是在SSD上，输入命令确实没有感觉卡顿。

**Comment by qianlifeng** [comment]
#199 我已经新建了一个Issue用来解决这个问题。
