### ISSUE TITLE
在设置触发关键词的时候如果留空了 以后的所有搜索都会是使用这个插件，到最后只能禁用

### ISSUE THREAD

**Issue by lhd1997** [Wox-launcher/Wox#1597]
windows 10

**Comment by lhd1997** [comment]
![qq 20170916205654](https://user-images.githubusercontent.com/22672969/30512431-f317c49e-9b21-11e7-870d-758a29fac0d0.png)
问题解决了，找到了设置文件 重新填入触发关键词即可

**Comment by jhdxr** [comment]
duplicate of #1397
