### ISSUE TITLE
Error on Wox startup after installing plugin "PluginsList"

### ISSUE THREAD

**Issue by J-Setzer** [Wox-launcher/Wox#1598]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\[MYNAME]\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/17/2017 09:36:46
Exception:
mscorlib
System.AggregateException
Mindestens ein Fehler ist aufgetreten.
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   bei Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 91.
   bei Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:Zeile 60.
   bei Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 31.
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Additional notes**
I did the following changes after first installation:
1. change language to Deutsch
1. set maximum results shown from 6 to 10
1. changed theme
1. checked "Remember last launch location"
1. checked "Hide Wox when focus is lost"
1. installed plugin "PluginsList" from within Wox (wpm)

After these changes Wox always starts with the error message above. Every change in settings also shows this error. I cannot reset the settings, Wox does not save the changes any more.

Uninstall and Reinstall did **not** fix the problem.

**Comment by dimitrior** [comment]
Had same problem - see fix at #1774

**Comment by lances101** [comment]
PluginsList is not an official Wox plugin therefore we cannot provide support for it. 

You can [ask the developer to update it here](https://github.com/vladimirantos/Wox.Plugins.PluginsList/), or you can fork it, update it and upload it as a new plugin. 

Anyway, the functionality of the plugin is already included in Wox. You can get a list of installed plugins by using the `wpm list` command. 

Closed due to being a third-party plugin.

**Comment by dimitrior** [comment]
Hi @lances101 You answered all my questions - thanks!
