### ISSUE TITLE
启动报错 Image.cache由另一进程使用

### ISSUE THREAD

**Issue by TroySmith9** [Wox-launcher/Wox#1602]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.10240.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 09/19/2017 22:10:33
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\troy\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 37
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lizhuangs** [comment]
我最近一直是这个错。但是我查过，这个文件根本 没有被其它程序使用，手动把这个文件删除就好了。但是过不几天可能这个错误又出来了。

**Comment by jhdxr** [comment]
duplicate of #1394

**Comment by tianyunperfect** [comment]
@lizhuangs 
我和你的情况一样的，彻底解决了吗？

**Comment by lizhuangs** [comment]
@tianyunperfect 没有，目前没在用，稳定性太差了。打开xshell就卡死了。现在好像作者没空维护，等稳定了再试试

**Comment by luodesinan** [comment]
也出现同样的问题，现目前只能等了？

**Comment by jhdxr** [comment]
能否都说下自己的系统的版本以及是否装了什么可能相关的程序？

因为我自己这么久并没有遇到，所以想看看有没有什么共同的地方来复现这个问题

**Comment by luodesinan** [comment]
大佬，这是出现问题时的提示：


 version: microsoft windows nt 10.0.15063.0 intptr length: 8 x64: true python path: everything sdk path: date: 12/07/2017 10:40:34 exception: mscorlib system.io.ioexception 文件“c:\users\administrator\appdata\roaming\wox\cache\image.cache”正由另一进程使用,因此该进程无法访问此文件。 在 system.io.__error.winioerror(int32 errorcode, string maybefullpath) 在 system.io.filestream.init(string path, filemode mode, fileaccess access, int32 rights, boolean userights, fileshare share, int32 buffersize, fileoptions options, security_attributes secattrs, string msgpath, boolean bfromproxy, boolean uselongpath, boolean checkhost) 在 system.io.filestream..ctor(string path, filemode mode, fileaccess access, fileshare share, int32 buffersize, fileoptions options, string msgpath, boolean bfromproxy) 在 system.io.filestream..ctor(string path, filemode mode) 在 wox.infrastructure.storage.binarystorage`1.save(t data) 位置 c:\projects\wox\wox.infrastructure\storage\binarystorage.cs:行号 99 在 wox.infrastructure.storage.binarystorage`1.tryload(t defaultdata) 位置 c:\projects\wox\wox.infrastructure\storage\binarystorage.cs:行号 44 在 wox.infrastructure.image.imageloader.initialize() 位置 c:\projects\wox\wox.infrastructure\image\imageloader.cs:行号 37 在 wox.app.b__10_0() 位置 c:\projects\wox\wox\app.xaml.cs:行号 52 在 wox.infrastructure.stopwatch.normal(string message, action action) 位置 c:\projects\wox\wox.infrastructure\stopwatch.cs:行号 31 在 system.windows.application.onstartup(startupeventargs e) 在 system.windows.application.b__1_0(object unused) 在 


system.windows.threading.exceptionwrapper.internalrealcall(delegate callback, object args, int32 numargs) 在 system.windows.threading.exceptionwrapper.trycatchwhen(object source, delegate callback, object args, int32 numargs, delegate catchhandler)




在 2017-12-07 10:53:35，"蝦米" <notifications@github.com> 写道：


能否都说下自己的系统的版本以及是否装了什么可能相关的程序？

因为我自己这么久并没有遇到，所以想看看有没有什么共同的地方来复现这个问题

**Comment by lizhuangs** [comment]
我的是win8.1系统。之前出问题的时候不记得安装了什么导致的。qq电脑管家不知道算不算。

**Comment by lances101** [comment]
Duplicate of #1394 

You can keep track of the problem in the mentioned issue.
