### ISSUE TITLE
希望「程序」插件能增加一个直接输入特定关键字就重建索引的功能

### ISSUE THREAD

**Issue by Moyf** [Wox-launcher/Wox#1604]
## English

I hope I can type some keyword (for example: rebuild) to rebuild "program" plugin's index, instead of go to "setting", find "plugin->program" then click Rebuild button.

I'm a newbie to github so I don't know if it's right to ask for new feature in "issue", If I did something wrong please ignore me  : ( 

## 中文 / Chinese

已搜索，暂未发现类似的请求。

希望能直接在 Wox 命令框中输入一个指令（比如 rebuild）来调用「程序」插件的重建索引功能；有时候只是添加了一个文件，但还是要进入设置，找到插件，点击重建按钮，会略微有点麻烦。

第一次使用 Github 的 Issue 功能，不知新功能需求可否提在这里。如果提错了请直接忽视 _(:з」∠)_

**Comment by zxbu** [comment]
很简单，输入 rew ，执行restart wox就重建索引了
