### ISSUE TITLE
如何快速打开文件呢？

### ISSUE THREAD

**Issue by snfnwgi** [Wox-launcher/Wox#1605]
比如我想打开a.txt   ,可以像alferd 一样, open a.txt 吗

**Comment by zyzhang15** [comment]
You can  just input `a.txt` ,and press Enter.  the file a.txt will be open with the default editor.

**Comment by snfnwgi** [comment]
什么意思呢？我直接输入a.txt 只出来一个从链接中打开，没有从编辑器打开呢

**Comment by zyzhang15** [comment]
please reamd the the Requirements in wox's[ README.md](https://github.com/Wox-launcher/Wox#installation).
you should install `everthing.exe`  before and make sure the service of everthing run in the background.

**Comment by snfnwgi** [comment]
啥 意思 呢，哥我看我也是国人，能用中文说吗

**Comment by zyzhang15** [comment]
wox的  [README.md](https://github.com/Wox-launcher/Wox#installation) 中有说明,
想要通过wox 搜索文件,需要先在电脑上安装[everthing](https://www.voidtools.com/) ,并启动. 保持everthing 后台运行,然后在wox 中输入a.txt    wox就可以调用everthing的服务来搜索a.txt文件. 否则搜索结果中就没有该文件的结果.

**Comment by snfnwgi** [comment]
哈哈，谢谢了大哥，可以了
