### ISSUE TITLE
Exception - PresentationFramework -> System.Windows.Markup.XamlParseException

### ISSUE THREAD

**Issue by hekystyle** [Wox-launcher/Wox#1607]
# Log file
[2017-09-27.txt](https://github.com/Wox-launcher/Wox/files/1336988/2017-09-27.txt)

# Exception message
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 09/27/2017 13:55:38
Exception:
PresentationFramework
System.Windows.Markup.XamlParseException
Při inicializaci Wox.MainWindow došlo k výjimce.
   v System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   v System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   v System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   v System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   v Wox.App.<OnStartup>b__10_0() v C:\projects\wox\Wox\App.xaml.cs:řádek 60
   v Wox.Infrastructure.Stopwatch.Normal(String message, Action action) v C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:řádek 31
   v System.Windows.Application.OnStartup(StartupEventArgs e)
   v System.Windows.Application.<.ctor>b__1_0(Object unused)
   v System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   v System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Try reinstalling Wox. Do so by following these steps:
- exit Wox
- delete the contents of the following folders
  - `%appdata%/Wox`
  - `%localappdata%/Wox`
- download Wox from [the releases page](https://github.com/Wox-launcher/Wox/releases)
- launch the executable as you would any other .exe

If you keep having any problems reopen this issue.
