### ISSUE TITLE
Folder plugin usage example

### ISSUE THREAD

**Issue by thdoan** [Wox-launcher/Wox#1608]
I added `C:\PAP` to the Folder Path list, but when I searched for "pap" this folder is not listed. What is the purpose of adding folders to this plugin?

**Comment by lances101** [comment]
You are using it correctly. Try scrolling through the results list. Its likely that the weight on that result is lower than the rest.

Reopen this issue if the problem persists.

**Comment by Girmii** [comment]
I would assume that explicitly adding a folder to the list would give it such a weight that it shows up very high, if not first, in the search results. It is counter-intuitive that this is not the case.

**Comment by desmondw** [comment]
@thdoan @Girmii I found success manually setting an "Action Keyword" that you need to preface as a command.
Set here:
![image](https://user-images.githubusercontent.com/1052705/219752179-de6a3604-5055-4450-a53a-0ea3cd00a1f4.png)
See here:
![image](https://user-images.githubusercontent.com/1052705/219752674-7d39b980-00de-4a6c-9e9a-cefc2eba1a75.png)

Although I do agree, this kind of default behavior is counter-intuitive for the exact purpose people install Wox for.

EDIT: Even better, if you change the action keyword in the "Everything" plugin and don't change the folder keyword, you can also achieve the same behavior without prefacing with a command
