### ISSUE TITLE
Bad documentation on plugins

### ISSUE THREAD

**Issue by simonkaspersen** [Wox-launcher/Wox#1610]
Hi!
Would love to see some better documentation on creating plugins. Not only 4 lines of files that needs to be present, but also examples and how to properly import them so Wox finds them. 

I am struggeling to get Wox to see it in the Plugin-folder

**Comment by lances101** [comment]
Hey there. We don't currently have a good documentation on plugin development.
As of now, only the following sources are available:
- [old wox documentation ](http://doc.getwox.com/en/plugin/create_plugin.html)
- [C# plugin distributed with Wox](https://github.com/Wox-launcher/Wox/tree/master/Plugins/HelloWorldCSharp)
- [Python plugin distributed with Wox](https://github.com/Wox-launcher/Wox/tree/master/Plugins/HelloWorldPython)
