### ISSUE TITLE
[Plugin request] Alfred-like snippets

### ISSUE THREAD

**Issue by novmikvis** [Wox-launcher/Wox#1614]
Add plugin that allows define text keywords and assign text blocks to them:
(no need for fancy UI, plain text multi-line input is good enough)

From [Alfred team](https://www.alfredapp.com/help/features/snippets):

> Do you frequently have to type your address, a block of text or website address? Typing them manually takes time, requires looking the same information up every time and leaves you with the possibility of making a typo error.
> Saving your text clip as an Alfred snippet ensures that the next time you need it, it'll save you time and be as perfect as the first time you typed it

![](https://www.alfredapp.com/help/features/snippets/snippets-editing.png)
![](https://www.alfredapp.com/help/features/snippets/snippets-preferences.png)

Same idea as [Cerebro plugin](https://github.com/puyt/cerebro-snippets)

![](https://github.com/puyt/cerebro-snippets/raw/master/screenshot1.gif)
![](https://github.com/puyt/cerebro-snippets/raw/master/screenshot2.gif)

**Comment by alrafer** [comment]
Great idea, totally concur! 👍

**Comment by NicolasVanhecke** [comment]
This is the exact reason I started using Alfred. Is there any news on this? I don't see it implemented in v1.3 yet...

**Comment by kalaschnik** [comment]
I’m using Beeftext where you can define keywords that get replaced. You can also set up a modal window, similar to wox. Maybe you two should collaborate ¯\\_(ツ)_/¯

![GIF](https://user-images.githubusercontent.com/9831678/66193111-33316680-e692-11e9-99ae-5dea2dd6c0e9.gif)

Beeftext Repo
https://github.com/xmichelo/Beeftext
https://github.com/xmichelo/Beeftext/issues/200

**Comment by youtextme** [comment]
If you’re coming from macOS Alfred snippets: on Mac, **free Raycast Snippets** is the closest first-party feel (keyword → expand). On Windows, PowerToys/Wox/Flow are the right tracks — just flagging the Mac equivalent for dual-boot folks.

https://www.raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
