### ISSUE TITLE
Cannot set hot key in hot key tab. Got ImeProcessed when using chinese input method.

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [Wox-launcher/Wox#1618]
### version: 
wox-1.3.183, windows10

### reproduce:
With sougou chinese input method activited, open hotkey tab in setting window. Add or edit a hotkey entry. Input ',', got 'ImeProcessed'. Input 'Ctrl+,', got 'Ctrl+ImeProcessed'. After disable the input methods, the hotkey window functions well.

![default](https://user-images.githubusercontent.com/32661032/31367661-675c6940-adab-11e7-9712-94abaddb8a91.png)

possibly relevant to the this post. https://www.cnblogs.com/yingql/archive/2010/03/31/1701777.html

使用中文输入法时，如果设置热键，会得到ImeProcessed的结果。关闭中文输入法后可以正常工作。
可能与上文链接中的帖子相关。

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
