### ISSUE TITLE
增加优先级或者收藏夹优先显示

### ISSUE THREAD

**Issue by yinxufeng** [Wox-launcher/Wox#162]
比如搜索qq，往往搜索的结果中第一个不是想要的qq.exe。如果提供优先级（多次搜索QQ，在列表中选择的事qq.exe)，或者可以将qq.exe加入到一个收藏夹中，这样在搜索qq时，优先将qq.exe排在更前面

**Comment by qianlifeng** [comment]
已经有这个功能了。多次选择的item会有更高的优先级。你可以在config文件夹下面的UserSelectedRecords.json 看到你的记录和权重
