### ISSUE TITLE
Everything Service displays all folders and subfolders in seemingly random order.

### ISSUE THREAD

**Issue by noahbaxter** [Wox-launcher/Wox#1630]
When searching for folders in everything service, results are listed that include the folder I want, but usually some deep folder hierarchy inside instead of the toplevel folder I want. How do I make folders appear in a logical hierarchical order?

**Comment by lances101** [comment]
Could you provide an example?

**Comment by noahbaxter** [comment]
[image: Inline image 1]

When I search for C:\Users, I would expect it to show the shortest path
first, so I could open my Users folder, and not random folders deeply
nested inside.

**Comment by lances101** [comment]
That is how Everything sorts results by default. 

It may be possible to specify the order through the Everything SDK or by sorting them manually.   This could be an added feature in the future once we get to a stable build.
