### ISSUE TITLE
Cursor jumps to end of line with every keypress, making it hard to edit current query - 1.3.183

### ISSUE THREAD

**Issue by vildechaya** [Wox-launcher/Wox#1631]
When entering a query in the wox box, I've noticed that the cursor automatically jumps to the end of the line with every keypress. This is fine most of the time, but if I'm editing the query and put the cursor somewhere in the middle, it makes it almost unusable. (For instance, using wox as a caluculator, and going back to edit the calculation.)

## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by devonzara** [comment]
I am unable to reproduce this issue on v1.3.424.

**Comment by lances101** [comment]
Not relevant on latest versions. Closed.

It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
