### ISSUE TITLE
Wox box jumps between screens on multi-screen setup - 1.3.183

### ISSUE THREAD

**Issue by vildechaya** [Wox-launcher/Wox#1632]
I have a two monitor setup. Every time I use the Wox hotkey, I never know which screen it will pop up on. There doesn't seem to be an obvious pattern. Also, sometimes when I'm entering a query into wox, the box will suddenly jump from one screen to the other. It's very curious.

**Comment by JohnTheGr8** [comment]
Does it not always open in the monitor the cursor is in? That seems to always be the case for me...

You're right about the box jumping screens, I can confirm it will jump to the other monitor if I move the cursor to it and then start typing.

**Comment by vildechaya** [comment]
John - you're absolutely right. Wox follows the cursor. Thanks for connecting the dots on that for me.

**Comment by JohnTheGr8** [comment]
I'll look into the jumping issue if I get some time...

Cheers

**Comment by rareinator** [comment]
The box doesn't really jump around for me.

**Comment by JohnTheGr8** [comment]
To reproduce the box-jumping-around issue:

1. Press hotkey to launch Wox
2. Move cursor to the other monitor
3. Start typing a query

**Comment by rareinator** [comment]
I cant reproduce this issue, though I also have a newer version of wox. Version 1.3.424 so the issue seems to have already been fixed.

**Comment by JohnTheGr8** [comment]
That's possible, I'm on 1.3.183 as well.

@vildechaya Have you tried the pre-release?

**Comment by jhdxr** [comment]
I don't have the necessary environment (multi screen) to reproduce this issue, but I suggest you try the latest pre-release as well. And of course, PR is welcome.

**Comment by JohnTheGr8** [comment]
I cannot check right now, but I will test the latest pre-release later today if @vildechaya hasn't responded...

**Comment by JohnTheGr8** [comment]
I can confirm this issue is no longer present in v1.3.424. You can close this issue...
