### ISSUE TITLE
不能打开QQ聊天对话框

### ISSUE THREAD

**Issue by jiaziang** [Wox-launcher/Wox#1637]
### 系统信息

1.Wox版本1.3.424
2.Windows版本 win10 1703

### 问题描述：希望在搜索qq之后打开qq的聊天对话框而不是重新打开一个qq登陆界面。
可能是由于qq支持多开所以会出现这种情况，不知有没有好的办法实现。
3q~

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by jhdxr** [comment]
这个目前没有合适的思路，因为QQ并没有暴露对应的接口_(:з」∠)_

**Comment by I-Want-ToBelieve** [comment]
这是正确的行为, 已经打开的聊天对话框可以通过 alt + tab 切换.

**Comment by bao-qian** [comment]
qq 没接口
这需要专门的插件去逆向
