### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hamzty** [Wox-launcher/Wox#1638]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Asus\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/27/2017 08:41:27
Exception:
mscorlib
System.UnauthorizedAccessException
Es wurde versucht, einen nicht autorisierten Vorgang auszuführen.
   bei Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   bei Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   bei Wox.SettingWindow.SetStartup() in C:\projects\wox\Wox\SettingWindow.xaml.cs:Zeile 63.
   bei Wox.App.AutoStartup() in C:\projects\wox\Wox\App.xaml.cs:Zeile 97.
   bei Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:Zeile 80.
   bei Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 31.
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by CzBiX** [comment]
Check the settings in your security protect software.

**Comment by hamzty** [comment]
regarding which settings?

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
