### ISSUE TITLE
Installer needed

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#164]
Every time download and unpack in the new folder - is bad, we need the installer which will check whether the previous version installed and install with save settings and plugins from previous version.

**Comment by Abel-Liu** [comment]
Wix is powerful.
http://wixtoolset.org/

**Comment by qianlifeng** [comment]
Since Wox will support auto update function. I think installer is not needed, Wox should be portable.

**Comment by roose** [comment]
if will the auto update function, I agree, the installer does not needed

**Comment by spalger** [comment]
I agree that it's not needed, but having an installer really improves the experience. I have to admit that I was a bit confused when I downloaded the zip.
