### ISSUE TITLE
[Feature Request]Use Tab key to show context menu of result item

### ISSUE THREAD

**Issue by CzBiX** [Wox-launcher/Wox#1641]
What I do: Press Tab key on result item.
What expected: Show context menu of item.
What happend: Select next item.

![image](https://user-images.githubusercontent.com/760097/32142630-131cca70-bcd6-11e7-9183-4339d81ca7aa.png)

**Comment by modyuan** [comment]
+1
I want this too!!just like Listary!!

**Comment by lances101** [comment]
The ongoing refactoring of hotkeys is still in progress - #459

Please post your suggestions there.
