### ISSUE TITLE
wox热键设置有问题

### ISSUE THREAD

**Issue by yueludanfeng** [Wox-launcher/Wox#1642]
版本：1.3.424
 我发现不知道从哪个版本开始，wox的热键设置就出现问题了：我一直习惯将wox的激活热键设置为Alt+W，但是最近的好多版本都不能设置该组合键为激活wox的热键，我记得以前的版本是可以设置的，希望这个bug可以修改一下，非常感谢！！！

**Comment by lances101** [comment]
@yueludanfeng <kbd>ALT</kbd>+<kbd>W</kbd> should be a valid combination for Wox. 

Could you please try setting it once more and then upload the latest log from `%appdata%/Wox/Logs` and also `%appdata%/Wox/Settings.json` ?

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
