### ISSUE TITLE
Everything plugin problems

### ISSUE THREAD

**Issue by Cariocecuz** [Wox-launcher/Wox#1645]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: 
Date: 10/30/2017 11:24:43
Exception:
mscorlib
System.AggregateException
Ocorreram um ou mais erros.
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   em Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) em C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   em Wox.App.<OnStartup>b__10_0() em C:\projects\wox\Wox\App.xaml.cs:line 60
   em Wox.Infrastructure.Stopwatch.Normal(String message, Action action) em C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   em System.Windows.Application.OnStartup(StartupEventArgs e)
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-10-30.txt](https://github.com/Wox-launcher/Wox/files/1427001/2017-10-30.txt)

**Comment by lances101** [comment]
`RedditRead` is not an official Wox plugin and therefore we cannot provide support for it. 
Please open an issue in the repo of the plugin.
