### ISSUE TITLE
Show plugin icon when searching for plugins instead of PluginManager's default icon

### ISSUE THREAD

**Issue by arkraft** [Wox-launcher/Wox#165]
When i type the first letters of a plugins name the plugin appears in the search result. 
But instead of the plugin icon, the default PluginManager icon appears.
![image](https://cloud.githubusercontent.com/assets/7426376/3980195/04aec54c-285f-11e4-8aa1-d413ddb0cc2e.png)
It would be a lot better if the icon from plugin configuration would be used.

**Comment by qianlifeng** [comment]
I agree
