### ISSUE TITLE
支持mingw python

### ISSUE THREAD

**Issue by kailiu42** [Wox-launcher/Wox#1650]
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：在settings中python directory选择mingw python的安装路径，提示无法找到python。
3. Windows 版本：Windows 10 1709
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

我使用的是通过msys2安装的mingw64 python。该版本python可直接在windows cmd窗口中运行。但通过wox的设置选择了python.exe安装路径后提示找不到python。希望能支持。

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
