### ISSUE TITLE
无法设置空格为插件触发关键词 Can not set blank space as plugin keyword

### ISSUE THREAD

**Issue by Drake-Z** [Wox-launcher/Wox#1656]
1. Wox 版本 / commit number：v1.3.424
2. 如何**重现** bug：将 Everything 插件的触发关键词设为一个空格
3. Windows 版本：Win10 64bit
4. Exception：设置的关键词无效，且无法再在 GUI 界面修改，只能直接修改 Settings.json 恢复

修改 Settings.json 的时候发现程序是直接把空格转为空字符串的。
我觉得如果不支持空格的话可以在文档里说明一下。

**Comment by jhdxr** [comment]
duplicate of #1397 

https://ci.appveyor.com/project/happlebao/wox/build/1.3.455/artifacts
