### ISSUE TITLE
Wox 报错，无法使用！

### ISSUE THREAD

**Issue by wu-ricky** [Wox-launcher/Wox#1657]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python35\pythonw.exe
Everything SDK Path: C:\Users\Ricky\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 11/02/2017 22:56:31
Exception:
Wox.Core
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 89
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   在 System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value)
   在 System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   在 System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   在 [System.Windows.Data.BindingExpressionBase.Invalidate(Boolean](url) isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.Activate(Object item)
   在 System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   在 System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   在 MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   在 MS.Internal.Data.DataBindEngine.Run(Object arg)
   在 System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   在 System.Windows.ContextLayoutManager.UpdateLayout()
   在 System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-11-02.txt](https://github.com/Wox-launcher/Wox/files/1438224/2017-11-02.txt)

**Comment by wu-ricky** [comment]
完整卸载后，重新安装可以使用，但是发送这个问题我明确是安装插件“快递查询”所发生的！

**Comment by shetz163** [comment]
我也是一样的问题,怎么完全卸载啊,在程序里调用系统的卸载之后我也在目录里删除了文件,但依旧双击WOX的安装文件之后 弹出报错

**Comment by wu-ricky** [comment]
1、卸载Wox后重启
2、删除安装目录C:\Users\Ricky\AppData\Local\Wox和缓存文件夹C:\Users\Ricky\AppData\Roaming\Wox
3、用Registry Workshop搜索删除注册表
4、重新安装Wox

**Comment by wu-ricky** [comment]
Wox很强大，但是貌似有点不稳定，资源占用也很大，另外我再寻找一款可以直接 从wox上创建evernote笔记的插件，若有烦请提醒我！谢谢

**Comment by lances101** [comment]
Duplicate of #1356. 
Please continue the discussion of this issue there.
