### ISSUE TITLE
Focus after search

### ISSUE THREAD

**Issue by gutierri** [Wox-launcher/Wox#1660]
After a search, for example in "wiki languages" it opens a tab in my browser and closes the WOX. But the focus is not in the browser window.

**Comment by lSindra** [comment]
Could not replicate it using Windows 10 and Google Chrome.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
