### ISSUE TITLE
Can not launch Google Scholar Search

### ISSUE THREAD

**Issue by ZeweiSong** [Wox-launcher/Wox#1662]
I tried the default command for Google Scholar search, but it failed to pop up the search function. Other searching, such as Google and Bing work fine.

Thanks!

![wox_google_scholar_error](https://user-images.githubusercontent.com/7750107/32360951-c73dd4f0-c095-11e7-9aa4-86306620482f.png)

**Comment by ZeweiSong** [comment]
I renamed the command and renamed it back, and now it works! Well, I'm still not quite sure how I fix it.

**Comment by ccelik97** [comment]
> 
> 
> I renamed the command and renamed it back, and now it works! Well, I'm still not quite sure how I fix it.

Yeah it also happened here exactly as you said too. Maybe it wasn't enabled at first, I don't know..

**Comment by DaTouJun** [comment]
I also encountered the same issue, and it was also resolved by using the renaming method to normally enable Google Scholar
