### ISSUE TITLE
数字达到11位以后，计算器插件出错

### ISSUE THREAD

**Issue by edsion1107** [Wox-launcher/Wox#1664]
1509683404004-1509683392773=0
![tim 20171103143706](https://user-images.githubusercontent.com/1925286/32362470-921e0966-c0a4-11e7-88f8-01ef1f14263c.png)

**Comment by edsion1107** [comment]
版本1.3.183

**Comment by jhdxr** [comment]
duplicate of #1022 

用最新的：https://ci.appveyor.com/project/happlebao/wox/build/artifacts
