### ISSUE TITLE
唤起wox之后不会自动获得焦点

### ISSUE THREAD

**Issue by znewcradle** [Wox-launcher/Wox#1669]
这真的很影响使用，每次alt+space唤起wox之后，wox都无法自动获得焦点，都得点击一下才能开始输入搜索内容，很影响效率。

**Comment by jhdxr** [comment]
版本？系统？

**Comment by znewcradle** [comment]
我是win10 1709，刚刚装的是pre-release 的最新版本；不过现在我换成了最新的稳定版本，这个问题已经没有了。

**Comment by Lemon-cxh** [comment]
win10 wox最新，也是不会自动获得焦点
