### ISSUE TITLE
How to "create" commands ?

### ISSUE THREAD

**Issue by Ra0EL** [Wox-launcher/Wox#167]
Hi,
I wonder how I can use Wox to start commands with parameters. And make Wox remember this command for further calls, in a very fast, effective and convenient way.

I explain more.
For instance, let's say I want to regularly run this command :
`reg query HKLM\Software\policies\microsoft\windows\windowsupdate /s`
As I never remember all of these parameters ( _and don't want to_ ) I would like Wox to _learn_ this command the first time I type it entirely.
And after that, I would like this command to be suggested by Wox the next time I will enter `reg` in Wox prompt.

Oh, and I don't want to create Windows shortcuts for all of my specific commands like that ( I know this may be the workaround for now on ) :wink: .

**Comment by orzFly** [comment]
Create a folder, and add it as a FileSystemSource into Wox -> Settings -> Programs.

Then create a shortcut in the folder to "reg query HKLM\Software\policies\microsoft\windows\windowsupdate /s”. Name the shortcut as you like.

**Comment by orzFly** [comment]
I am sorry that I didn't notice your last sentence.

But I personally think this is an easy method instead of creating such complex settings in Wox.

**Comment by qianlifeng** [comment]
The only thing Wox learned from your command is the command itself. Wox will rememeber the command you executed. 
![image](http://tupi.sinaapp.com/9e24655dcb46bb19e42d498eb0838406.png)
Do you mean when you type `reg` next time, Wox should prompt you following three items at least?
`reg query`
`reg query HKLM\Software\policies\microsoft\windows\windowsupdate`
`reg query HKLM\Software\policies\microsoft\windows\windowsupdate /s`

**Comment by Ra0EL** [comment]
Using shortcuts is what I am currently doing. But I dont find it that convenient.

I havent noticed that Wox can remember a complete command. I think that it is a valuable answer to my question. And I am not sure that prompting for 3 items, as you suggest, is necessary.
But still there is the question : how to clean what Wox will suggest ?

For instance, let's say I have run this command but I made a typo. Next time, Wox will present both the command with typo and the fixed command. How can I remove the bad entry from Wox ?

**Comment by qianlifeng** [comment]
Currently, the only way that user want to clear the wrong command is to remove the item in Config/CMDHistory.json file.
