### ISSUE TITLE
(Calculator) Scientific notation for small numbers

### ISSUE THREAD

**Issue by amccaugh** [Wox-launcher/Wox#1672]
The calculator works great, except that it does a poor job reporting small numbers.  Since the Calculator plugin only shows numbers up to 6 decimal places, any number below 0.000001 is rounded to zero.

Suggested fix: For any number < 0.000001, report the number in scientific notation, with the same 6 digits of significant figures.

Current behavior:  "4^-11" outputs "0.000000"
Suggested behavior:  "4^-11"output "2.384186e-7"

1. Wox version / commit number:  1.3.424
3. Windows version:  Windows 10

**Comment by amccaugh** [comment]
It actually may make more sense to report 6 digits of the decimal, to avoid significant rounding errors (see e.g. the behavior of the Google calculator).  So anything <1e-6 would be reported in scientific notation, but numbers between 0.1 and 0.000001 would always have enough significant digits not to have bad rounding errors

If _answer < 0.000001:_  report in scientific notation
Current behavior: "4^-11" outputs "0.000000"
Suggested behavior: "4^-11"outputs "2.384186e-7"

If _0.1 > answer > 0.000001_: report in decimal, but report 6 digits
Current behavior: "4^-9" outputs "0.000004"  (rounding error)
Suggested behavior: "4^-9"outputs "0.00000381469" (much more precise)

Else: Use current behavior

**Comment by jhdxr** [comment]
Thanks for your report. This issue has already been fixed
in the latest released version of Wox, which you can download [here](https://github.com/Wox-launcher/Wox/releases)
