### ISSUE TITLE
使用拼音输入法在搜索框输入时，卡顿现象明显

### ISSUE THREAD

**Issue by RenegadeGuo** [Wox-launcher/Wox#1675]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：使用win10自带的拼音输入法
3. Windows 版本：1709/16299.19
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：提示无法上传
6. 截图 （可选）：

**Comment by ShimotsukiH** [comment]
对，用微软拼音输入法会非常卡……

**Comment by RenegadeGuo** [comment]
这个现在没办法解决么…………是微软拼音的锅么………………

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by XJDKC** [comment]
用系统自带的拼音很卡。。。

**Comment by garylavayou** [comment]
Using the _Microsoft Chinese PinYin **input method**_ will freeze Wox, on Windows 10 1709, and even make Wox crash.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
