### ISSUE TITLE
Image search lead to memory usage kept increasing and never release

### ISSUE THREAD

**Issue by cjun714** [Wox-launcher/Wox#1677]
1. Wox version / commit number: **1.3.424**
2. Steps to **reproduce** the bug: Just **search image like xxx.jpg or xxx.png** in Wox search bar
3. Windows version: **Windows 10 Professional**
4. Exception: **When searching images, memory kept increasing and seemed never released**
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):[2017-11-07.txt](https://github.com/Wox-launcher/Wox/files/1448681/2017-11-07.txt)
6. Screenshot (optional): ![wox_issue](https://user-images.githubusercontent.com/12163580/32477115-d1e8ec36-c3b6-11e7-8521-97c33f1aafe9.jpg)

Python environment:
Work in newest msys64 and installed through pacman:
> pacman -S mingw-w64-x86_64-python2
> whereis python
python: /usr/lib/python2.7 /usr/lib/python3.6 /mingw64/bin/python.exe /mingw64/bin/python2.7-config /mingw64/bin/python2.exe /d/tool/editor/SublimeText3/python33.dll

Issue seemed caused by  caching image's thumbs during search and that cache is never released.

Suggestion:
- Don't cache any thumbs, just generate thumbs in realtime, or 
- has option to disable thumbs when display image searching result

Slow speed to show thumbs is acceptable, but increasing memory usage is always annoyed.

## 中文 / Chinese
1. Wox 版本 / commit number：**1.3.424**
2. 如何**重现** bug：在搜索框搜索类似 xxx.jpg，xxx.png
3. Windows 版本：**Windows 10 Professional**
4. Exception：搜索图片时，内存不断增长且搜索完后也不会释放
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：见上
6. 截图 （可选）：见上

感觉是略缩图的机制造成，生成缩略图耗费大量内存，且为了下次命中，cache搜索完也不释放。

建议：
- 不缓存任何缩略图，只实时生成，或者
- 提供选项，能彻底禁用缩略图（或只显示image文件类型图标），至少可以避免生成和缓存缩略图

不缓存缩略图，而实时生成，只会导致二次查询慢一点，这完全可接受。
但缓存缩略图而不释放，导致内存水位不断在提高，这难以接受。

**Comment by lances101** [comment]
Confirmed.

[`ImageLoader.Load`](https://github.com/Wox-launcher/Wox/blob/3aacfdca20392dd9059e885fbc2e94c833c9e576/Wox.Infrastructure/Image/ImageLoader.cs#L134) never disposes the image.

**Comment by lances101** [comment]
Please try [this build from Appveyor](https://ci.appveyor.com/api/buildjobs/o2fegpn844ybr5op/artifacts/Output%2FPackages%2FWox-1.3.505.exe).

These changes aim to change completely how images are loaded so that we delegate as much as possible to WinAPI.

**Comment by cjun714** [comment]
Wox-1.3.505.exe  seemed has no memory issue now，thumbnail also causes 2nd query keeping fast.
Thanks a lot.

**Comment by lances101** [comment]
Thanks. Will merge soon into main branch.

**Comment by cjun714** [comment]
This problem still exists on newest Wox release.
