### ISSUE TITLE
I've got a Wox error Newtonsoft.Json

### ISSUE THREAD

**Issue by burgyl** [Wox-launcher/Wox#1681]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 11/09/2017 14:15:15
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   à Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) dans C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:ligne 58
   à Wox.Infrastructure.Storage.JsonStrorage`1.Load() dans C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:ligne 40
   à Wox.ViewModel.MainViewModel..ctor(Settings settings) dans C:\projects\wox\Wox\ViewModel\MainViewModel.cs:ligne 62
   à Wox.App.<OnStartup>b__8_0() dans C:\projects\wox\Wox\App.xaml.cs:ligne 49
   à Wox.Infrastructure.Stopwatch.Normal(String name, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 28
   à System.Windows.Application.OnStartup(StartupEventArgs e)
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2017-11-09.txt](https://github.com/Wox-launcher/Wox/files/1457710/2017-11-09.txt)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.

**Comment by burgyl** [comment]
I uninstalled Wox and installed it again and now it work, thank's.
