### ISSUE TITLE
please set the default branch to 'dev'

### ISSUE THREAD

**Issue by mrexodia** [Wox-launcher/Wox#1686]
Currently the default branch is `master`, which causes pull requests to automatically open to master. If you change the default branch to `dev` this won't happen.

**Comment by lances101** [comment]
@bao-qian and @qianlifeng are the ones that have permissions to do so.

**Comment by bao-qian** [comment]
what's the problem if all pr goes to master?

**Comment by jhdxr** [comment]
IMO PRs should go `dev` first, and if it's confirmed stable then merged into master.

**Comment by jhdxr** [comment]
and it's also stated in our guideline: https://github.com/Wox-launcher/Wox/blob/master/README.md#contribution

**Comment by bao-qian** [comment]
done

**Comment by bao-qian** [comment]
development should be done in your own branch, e.g. I use bao.
pr will be merge to master.
stable release will use github release
