### ISSUE TITLE
搜索中的小优化

### ISSUE THREAD

**Issue by jianmofeng** [Wox-launcher/Wox#1687]
当搜索完一个事物并且不删除当前结果，再搜索另一个事物时，会发现还是之前搜索的那个结果

**Comment by lances101** [comment]
Could you please write the specific steps you took in order for this to happen?

Also, repeat those steps once again and upload Wox's latest log file. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by lances101** [comment]
Closed due to inactivity. Author may reopen the issue if needed.
