### ISSUE TITLE
no longer listing Start Menu programs

### ISSUE THREAD

**Issue by mcmile** [Wox-launcher/Wox#1698]
Wox no longer lists applications. I was working fine until about a week ago. For example, here's what happens when I type "chrome" for Google Chrome.  I have tried restarting and reinstalling both Everything and Wox. 

1. Wox version / commit number: 1.3.424

2. Steps to reproduce the bug:

    install wox
    open wox and search for any installed windows program or app
    can't be found

3.  Windows version: 10
![chrome](https://user-images.githubusercontent.com/12766974/33086633-c47000a6-cead-11e7-929e-1fdc11d1f1ef.jpg)

**Comment by gutierri** [comment]
I'm having the same problem and the program search plugin disappeared. And apparently the repository walks without updates. It looks like more people have the same problem #1700

**Comment by gutierri** [comment]
Uninstall and install works again. Then maybe deleting the cache folders will work again. I can not test this now because it's working for now.

**Comment by jhdxr** [comment]
program are indexed and queried by Programs plugin, not everything. please check the status of your Programs plugin.

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by MatteoOreficeIT** [comment]
Add C:\ProgramData\Microsoft\Windows\Start Menu\Programs to search path
