### ISSUE TITLE
Add Wox path to PATH environment variable

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#170]

**Comment by qianlifeng** [comment]
What's your scenario that you want to add Wox path to PATH environment?

**Comment by roose** [comment]
Wox - portable app, if i need run Wox from other program i need to know path to Wox, e.g. from Sublime Text plugin run "wox.exe doc &lt;selected word&gt;"

**Comment by qianlifeng** [comment]
I'm closing this since I think if someone need to use Wox  from commandline, they should add wox path to PATH envionment variable themselves. We won't do this by default.
