### ISSUE TITLE
Match Path

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [Wox-launcher/Wox#1704]
Since Wox uses Everything, is there any way it could adopt the "Match Path" function from it, as an option? I know \ exists to search within folders, but it can get awkward (ie. having to put quotes for names with spaces). On Everything, if I wanted to find a "The Beatles" folder within "James" folder, I just type "the beatles james" with "Match Path" enabled.

**Comment by lances101** [comment]
I have not looked into the Everything SDK, but I think this should not be difficult to implement.
