### ISSUE TITLE
Wox doesn't work after setting "/" as Folder plugin active key

### ISSUE THREAD

**Issue by Dancia** [Wox-launcher/Wox#1707]
I have tried setting "/" as Folder plugin action keyword, after that Wox doesn't find anything at all and I cannot change this particular plugin action keyword, it is blank in ui. I have tried going straight to Wox.Plugin.Folder\plugin.json and setting "ActionKeyword":"*",, but nothing recovered. Also I have tried completely reinstalling Wox, didn't help. I guess it keeps some kind of settings, which are not cleared after uninstall. Any help?

(Windows 10)

EDIT: It seems that if I remove Wox.Plugin.Folder manually, Wox works, but well.. I need that plugin.

**Comment by jhdxr** [comment]
maybe you have either copy a plugin from someone else, or just re-install wox (no need to uninstall the existing one)

**Comment by Dancia** [comment]
I have solved my issue. For future reference: the issue was that Wox reinstalls AppData\Local\Wox files, but config is kept inside AppData\Roaming\Wox and is not automatically deleted when reinstalling.
