### ISSUE TITLE
everything server is not running

### ISSUE THREAD

**Issue by ghost1372** [Wox-launcher/Wox#1711]
1. Wox version / commit number:  1.3.424
2. Steps to **reproduce** the bug:
3. Windows version: Win10 16299-  1709  64bit
[2017-11-30.txt](https://github.com/Wox-launcher/Wox/files/1515466/2017-11-30.txt)

everything server is not running

**Comment by stereokai** [comment]
Same here

**Comment by ghost1372** [comment]
fixed by installing 64bit version of Everything
download here:
https://www.voidtools.com/
