### ISSUE TITLE
Getting Exception on Windows 10 when launching - cannot use Wox

### ISSUE THREAD

**Issue by tshah95** [Wox-launcher/Wox#1712]
[2017-11-29.txt](https://github.com/Wox-launcher/Wox/files/1516640/2017-11-29.txt)

![image](https://user-images.githubusercontent.com/34119252/33415723-6056a65a-d54d-11e7-9340-5ad96313d1bc.png)

**Comment by lances101** [comment]
It seems like you are using an old version of Wox.
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)

Reopen this issue if the problem persists.
