### ISSUE TITLE
python plugin : avoid reimporting the module each time

### ISSUE THREAD

**Issue by sdementen** [Wox-launcher/Wox#172]
Hi,

With a python plugin, the module is apparently reimported each time the command is ran. If the module needs to do some time consuming preprocessing (like scanning folders or querying databases), this is penalising.
Is it possible to avoid reimporting the module each time ? is the python interpreter restarted each time ?

**Comment by qianlifeng** [comment]
Yes,  We started a new process to run the python plugin, so the python interpreter restarted and reimporting the module each time. This architecture will bring a little performance issues but will give Wox the ability to support more plugin languages,e.g. nodejs,ruby and more.
