### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by st4rlight** [Wox-launcher/Wox#1720]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 12/06/2017 15:46:09
Exception:
System
System.Net.WebException
操作超时
   在 System.Net.FileWebRequest.GetResponse()
   在 MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   在 MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   在 System.Windows.ResourceDictionary.set_Source(Uri value)
   在 Wox.Core.Resource.Internationalization.LoadLanguage(Language language) 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 128
   在 Wox.Core.Resource.Internationalization..ctor() 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 27
   在 Wox.Core.Resource.InternationalizationManager.get_Instance() 位置 C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:行号 18
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 44
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by lances101** [comment]
This issue was created long ago and there is no log file attached. 
If you are still having the same problem, attach a log file that contains the error and reopen the issue.
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
