### ISSUE TITLE
attach a keyboard shortcut to a specific command

### ISSUE THREAD

**Issue by sdementen** [Wox-launcher/Wox#173]
Would it be possible to attach another keyboard shortcut than the one used to pop up Wox that would open Wox with already some command entered.
for example :
    ctrl+space => open wox
    ctrl+b => opex wox and enter already "g "

**Comment by qianlifeng** [comment]
You mean this function?
![http://drp.io/files/53fbf44330de4.png](http://drp.io/files/53fbf44330de4.png)

**Comment by sdementen** [comment]
Indeed, can a default for hotkey be defined in the JSON file (as is the actionkeyword the default action except if changed by the user) ?

**Comment by qianlifeng** [comment]
define default hotkey for plugin should cause more conflict
