### ISSUE TITLE
关键插件无效&有时崩溃

### ISSUE THREAD

**Issue by chewnglow** [Wox-launcher/Wox#1739]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：除了everything搜索文件和命令行插件，其他所有的插件均无法运行，有时运行metro程序还会出现异常，导致搜索框只剩一条竖黑线。
3. Windows 版本：win10 15063.726
4. Exception：<System.IndexOutOfRangeException>等
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：
![default](https://user-images.githubusercontent.com/22649869/33793463-773a83d4-dcf3-11e7-9559-b9aa072377b9.png)

![default](https://user-images.githubusercontent.com/22649869/33793462-7051af7a-dcf3-11e7-8cf7-510a47ca84a1.png)

（注：已禁用正常工作的everything插件）
[2017-12-09.txt](https://github.com/Wox-launcher/Wox/files/1544451/2017-12-09.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
