### ISSUE TITLE
opening wox within a given context (ie active window)

### ISSUE THREAD

**Issue by sdementen** [Wox-launcher/Wox#174]
To automate some application through COM, it would be nice to be able to propose plugins that are only active when a given application was active before activating Wox (based for instance on a regex on the window title like "Microsoft Excel - results.xlsx").

For example, if I have Outlook as open application when I open Wox, I could type the command "move xxx" and it would call the "Outlook_MoveItem" plugin that moves the selected item to the outlook folder xxx. or the command "go xxx" (Outlook_GoFolder" and it would move to the outlook folder xxx.
However, if it is instead Excel that was open, the "go xxx" command would start the plugin "Excel_GoSheet". Or even, if Excel is open with a file name "get_stock_prices" the "go xxx" command would start the plugin StockPrice_Go that would automatically fill the range B4 with the value xxx and start some macro.
The whole COM automation can be easily done with Python plugins (I have tested succesfully Wox with some win32api functions) but the dispatching/activation of the right plugin in function of the title of the active window is what is missing within Wox.

With the issue #173, it could be then possible to add shortcut for actions specific to some active application (and for excel, active workbook).

**Comment by qianlifeng** [comment]
I think it's a little hard for wox to dispatching current command to the right plugin based on current context(e.g. prev active window).  This should be done by plugin itself.

Here is a possible approach:
User currently opened outlook, and he want to moves the selected item to the outlook folder xxx, then he activate Wox and type the command 'move xxxx', this will invoke plugin `move` plugin, inside `move` plugin, it will get the last active window (Wox can pass this info to plugin), and it detect outlook was prev activated. Then this plugin will move outlook item to xxxx through COM.

**Comment by sdementen** [comment]
I was more thinking about filtering the list of active plugin based on the context (ie make the enable/disable flag dynamic instead of static).

But your approach is indeed an alternative. How can the plugin get the name of the last active window ?

**Comment by bao-qian** [comment]
C# plugin can get the last active windows through win32 api.
http://stackoverflow.com/questions/9468476/switch-to-last-active-application-like-alt-tab
