### ISSUE TITLE
Visible but inactive custom web searches after upgrading to 1.3.424..

### ISSUE THREAD

**Issue by tshah95** [Wox-launcher/Wox#1740]
After upgrading to 1.3.424, I am not able to any of my custom search.  If I try to save a new search with the old name, it doesn't let me.   Also I can see that the old keyword is present somewhere in the db, but I can't seem to see it in any of the .json files.   [See how edcs and edcs2 is still visible, but I can't use edcs]

Can someone please help me revive all of my old custom web searches..  It's quite painful to work without those.

thanks in advance,
<img width="271" alt="wox_2017-12-08_330" src="https://user-images.githubusercontent.com/34119252/33793717-652500e8-dc71-11e7-89ca-74dd923e4648.png">

Tejas

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
Please upload your `%appdata%\Wox\Settings\Plugins\Wox.Plugin.WebSearch\Settings.json` file. 

Also, run wox and try doing a default web search as well as a custom search. Once your custom search fails, upload the latest log file.

You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by tshah95** [comment]
Here are the files you had asked for.  Hope this helps.

[Settings_json.txt](https://github.com/Wox-launcher/Wox/files/1589857/Settings_json.txt)
[2017-12-26.txt](https://github.com/Wox-launcher/Wox/files/1589864/2017-12-26.txt)

**Comment by lances101** [comment]
@tshah95, sorry, but the logs you uploaded seem to only have a small part. Please upload the full log. 

Also, I checked the URLs in the Settings_json.txt:
- http://directory.cisco.com/dir/empquery.go?sortColumn=&sortOrder=a&q={q}
- https://docs.cisco.com/share/proxy/alfresco/url?docnum={q}

It seems like I cannot resolve the domains for both names. Is this like an intranet portal or something? Do these links work for you?

**Comment by tshah95** [comment]
Yes, there are intranet links, and they used to work before in wox.

**Comment by lances101** [comment]
Okay, that makes sense now. There are different ways in which intranet is usually configured, so in order to be able to help you please tell me how do you connect. I do not need any specific Cisco info, just tell me how you configured your machine to access it: vpn, proxy, etc. 

If you are using a system-wide proxy Wox should be able to use that without any issues. But since in your specific situation it does not seem to work correctly, try adding the proxy in the settings window. 

Indicate how you are accessing it so that I can replicate it with something similar locally.

**Comment by tshah95** [comment]
I'm locally inside the network.  I think the wox installed a new version, and I lost all of my URLs.   Please make sure customer data is not lost when you do the upgrades..  It's quite time consuming adding URLs one by one.   How about importing via csv or something.

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
