### ISSUE TITLE
add python libraries for COM automation 

### ISSUE THREAD

**Issue by sdementen** [Wox-launcher/Wox#176]
Under windows, it may be sensible to add the win32 modules to provide COM automation.
I think it is sufficient to copy the highlighted modules 
![win32_modules](https://cloud.githubusercontent.com/assets/1304950/4040585/e1a63326-2ce8-11e4-8481-cc4d0422d8b4.png) from a portable python installation.

**Comment by qianlifeng** [comment]
I'm not sure if pywin32 Wox packaged(x86) will still work in x64 computer.

**Comment by vovkkk** [comment]
There is 64bit version http://www.lfd.uci.edu/~gohlke/pythonlibs/68tmfkay/pywin32-219-cp27-none-win_amd64.whl

comtypes is cross-platform http://www.lfd.uci.edu/~gohlke/pythonlibs/68tmfkay/comtypes-1.1.1-py2-none-any.whl

This site http://www.lfd.uci.edu/~gohlke/pythonlibs/ is unofficial ofc, but inasmuch as any software (no warranty no guarantee), [Python Guide](http://docs.python-guide.org/en/latest/scenarios/scientific/#unofficial-windows-binaries-for-python-extension-packages) by [Kenneth Reitz](https://github.com/kennethreitz) mentions this site (Kenneth Reitz is somewhat authority in Python world).

**Comment by bao-qian** [comment]
If you want to manipulate COM, use C#.
