### ISSUE TITLE
重启后操作超时 / timeout after restart

### ISSUE THREAD

**Issue by TownTowner** [Wox-launcher/Wox#1770]
## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese
标题错了，时间上看应该是重启之后
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 12/21/2017 02:36:38
Exception:
System
System.Net.WebException
操作超时
   在 System.Net.FileWebRequest.GetResponse()
   在 MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   在 MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   在 System.Windows.ResourceDictionary.set_Source(Uri value)
   在 Wox.Core.Resource.Internationalization.LoadLanguage(Language language) 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 128
   在 Wox.Core.Resource.Internationalization..ctor() 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 27
   在 Wox.Core.Resource.InternationalizationManager.get_Instance() 位置 C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:行号 18
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 44
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

env: （win10 surfacebook1）
Logfile: [2017-12-21.txt](https://github.com/Wox-launcher/Wox/files/1577540/2017-12-21.txt)

**Comment by lances101** [comment]
@TownTowner 
What language were you using when this happened?
Did you restart Wox through Wox or manually? 
Were you restarting because you installed a new plugin?

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
