### ISSUE TITLE
The "Everything" service should be bundled and installed automatically

### ISSUE THREAD

**Issue by Sire** [Wox-launcher/Wox#1772]
Or at least add the download link to the download page, it is not clear you should install this external software.

**Comment by lances101** [comment]
Currently it is not possible to install it completely automatically. 

Wox uses [Squirrel](https://github.com/Squirrel/Squirrel.Windows). Squirrel is an installer that installs to the user's local folder, requires no UAC dialogs and is generally very transparent for the user. This comes at the price that third-party dependencies are not that easy to install. 

What we could do is fire a prompt for the user to automatically download Everything and start the installer in the case that Everything is not already installed. 

**Edit:** as for "it is not clear", the main page does indicate that Everything is a requirement. [We also have a wiki here](https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Installation) describing the whole installation process. 

Anyway, I do agree with you that the whole process of installation should be closer to "double click and forget about it" kind of thing.

**Comment by Sire** [comment]
Thanks! Yes, just a link to the Everything page after installation would be a good start.

The download page doesn't mention Everything for the latest release, only for older ones (https://github.com/Wox-launcher/Wox/releases)
The main page doesn't mention Everything at all (http://www.getwox.com)

**Comment by wickles** [comment]
Why does the release page offer an old version of Everything? The current version is 1.4.1.895, but the Wox release has version 1.3.4.686. Is it important to use one version instead of another?

**Comment by bao-qian** [comment]
@wickles 
no
you can use the latest version
