### ISSUE TITLE
Wox 是否提供便携版？可否提供便携版？附使用场景

### ISSUE THREAD

**Issue by neatgz** [Wox-launcher/Wox#1773]
使用场景：
办公电脑 win7 和家用电脑 win10 
目前的情况是，白天使用办公电脑，晚上回家使用家用电脑。
目前除 wox 以外的所有常用软件都实现了便携，统一放在某自定义文件夹 D:/MyName/Apps 下，所有文档统一放在 D:/MyName/Files。使用某网盘同步 D:/MyName 整个文件夹。（现在的网速不像几年前，已经足够快了）
这样的好处是，1、白天在单位修改了文件、更改了软件设置、更新了软件等等任何操作，自动通过某网盘同步到家用电脑上，实现使用上的无缝体验。（文件关联使用的是 Total Commander 的内部关联，也是便携，彻底弃用了资源管理器）
2、除此之外，电脑重装系统时，只需要安装必备的 vc 运行库，以及安装某网盘客户端以自动下载所有Apps即可。

因此，强烈建议：
1、推出 Wox 便携版。保存配置文件、插件等到程序目录。
2、自定义 python 路径支持相对路径。（此处的相对路径 指 wox 程序目录而非系统的相对路径，如 %wox% 代表wox主程序所在路径）以实现 python 环境的便携。
3、程序列表的路径，支持相对路径。（此处的相对路径 指 wox 程序目录而非系统的相对路径，如 %woxxx% 代表wox主程序所在路径的上层目录），这样的话，上述的 D:/MyName/Apps/wox 文件夹的位置有变动时，wox 的程序列表仍然有效。

上述建议，请作者酌情考虑，谢谢。

**Comment by lances101** [comment]
Please use https://github.com/Wox-launcher/Wox/issues/629
