### ISSUE TITLE
Wox becomes unresponsive if a plugin throws an unhandled exception during initialization

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#1777]
1. Wox version / commit number: valid as of **1.3.424**
2. Steps to **reproduce** the bug: 
- install a plugin that throws an exception during initialization (i.e. `PluginsList` (incompatible))
- launch Wox
- Wox becomes unresponsive after plugin initialization

Fix plan: 
1. Capture all exceptions into an `AggregateException` during [PluginManager.InitializePlugins](https://github.com/Wox-launcher/Wox/blob/master/Wox.Core/Plugin/PluginManager.cs#L88) and throw them after initialization has completed.
2. Notify the user of the error via [Msg](https://github.com/Wox-launcher/Wox/blob/master/Wox/Msg.xaml)

Edit: [Msg](https://github.com/Wox-launcher/Wox/blob/master/Wox/Msg.xaml) itself seems to be unusable in the current state.

**Comment by lances101** [comment]
Closed with commit https://github.com/Wox-launcher/Wox/commit/36c03606dac7fe5997d741879e6ea4fa71d3c6ca

**Comment by garylavayou** [comment]
```
System.AggregateException: One or more errors occurred. ---> 
System.IO.DirectoryNotFoundException: Could not find path “C:\Users\garyw\AppData\Local\Wox\app-1.3.183\Plugins”.

```

Caused by the plugin named `PluginsList`.
