### ISSUE TITLE
Many executable files no longer appear in the results

### ISSUE THREAD

**Issue by CrazyCoder** [Wox-launcher/Wox#1779]
It looks like https://github.com/Wox-launcher/Wox/commit/808523b814ddbb82c6ac13f1da697342bc29b6a0 commit is the fault.

**Comment by lances101** [comment]
@CrazyCoder could you please upload a log file where the needed files where not indexed?

Also, please locate some files that it happens with, open the command prompt and run the following command:
`icacls "folder_with_exes" /t > _treedir.txt & explorer.exe . `

Where `folder_with_exes` is the directory from which files are not getting listed. 

This will dump the given folder into a file named `_treedir.txt` and open the file explorer in the folder where the file was generated. Please upload that file too.

**Comment by CrazyCoder** [comment]
The log didn't have any exceptions logged for these files/directories.

Permissions are fine too: https://pastebin.com/raw/CYBkAnLs (the unreadable Cyrillic user names are for the Users and Administrators groups).

For example, typing `matsync` din't provide `c:\dev\bin-common\matsync.exe` result until I reverted the commit mentioned above.

Wox plug-in settings:

https://i.imgur.com/WYR90mw.png
https://i.imgur.com/NrOMcRO.png

**Comment by lances101** [comment]
Okay, that helps a lot. I will replicate that case locally and bring out a hot fix that takes into account both cases. Thanks for your contribution.

**Comment by lances101** [comment]
@CrazyCoder I migrated to a new machine and it seems like I keep having issues with UWP API references even though a fresh version of Win10SDK is installed. Doesn't help that the UwpDesktop package hasn't been updated in a year either. 

**Edit:** It seems like removing the "UwpDesktop" package completely and manually referencing `Windows.winmd` from the Windows 10 kit fixed the problem. I will open a PR to discuss this problem separately. 

I'll update once I have a long term fix ready on your issue.

**Comment by lances101** [comment]
You were right about that last commit. 

[Line 210](https://github.com/Wox-launcher/Wox/commit/808523b814ddbb82c6ac13f1da697342bc29b6a0#diff-9ee9e21c69eec97fb378a1a404afa4dfR210) takes a list of directories in the specified directory, but the directory itself is not scanned. 

I will hotfix this and PR it directly into master.

**Comment by lances101** [comment]
@CrazyCoder[ could you try this build?](https://ci.appveyor.com/project/happlebao/wox/build/1.3.471/artifacts)

**Comment by CrazyCoder** [comment]
Works fine, thanks for the fix.
