### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SkqLiiiao** [Wox-launcher/Wox#1782]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\kongs\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/24/2017 15:20:34
Exception:
mscorlib
System.ArgumentOutOfRangeException
插入索引已超出范围。必须为非负值，并且必须小于或等于大小。
参数名: index
   在 System.Collections.ArrayList.Insert(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jhdxr** [comment]
Duplicate of #1725

**Comment by jhdxr** [comment]
能否说明一下在出现这个问题的时候你在进行的操作？
