### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by josueluna** [Wox-launcher/Wox#1803]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 01/04/2018 10:58:21
Exception:
mscorlib
System.IO.IOException
El proceso no puede obtener acceso al archivo 'C:\Users\josue\AppData\Roaming\Wox\Cache\Image.cache' porque está siendo utilizado en otro proceso.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode)
   en Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) en C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:línea 99
   en Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) en C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:línea 44
   en Wox.Infrastructure.Image.ImageLoader.Initialize() en C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:línea 37
   en Wox.App.<OnStartup>b__10_0() en C:\projects\wox\Wox\App.xaml.cs:línea 52
   en Wox.Infrastructure.Stopwatch.Normal(String message, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 31
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment]
Duplicate of #1394
