### ISSUE TITLE
Wox文件占用问题 / Wox does not close image streams causing file lockups

### ISSUE THREAD

**Issue by StephinChou** [Wox-launcher/Wox#1804]
1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：
>  1. 通过wox搜索一个文件并打开。
>  2. 删除或者覆盖文件会失败

3. Windows 版本：win7
4. Exception：文件被占用
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：[2018-01-06.txt](https://github.com/Wox-launcher/Wox/files/1608698/2018-01-06.txt)
6. 截图 （可选）：
![snipaste_20180106_183727](https://user-images.githubusercontent.com/6660127/34638921-b0a379d6-f310-11e7-81d6-05fe75b1088a.png)

**Comment by lances101** [comment]
Wox does not really "open" any file per se, it just issues that command to the OS. 

What kind of file were you trying to open? Is it an image or something? 

**Edit:** confirmed Wox locking on images. Caching seems to never release the object.

**Comment by lances101** [comment]
[Try this build from Appveyor](https://ci.appveyor.com/project/happlebao/wox/build/1.3.509/artifacts).

Should also be generally more snappy when loading images.

**Comment by jhdxr** [comment]
Thanks for your report. This issue has already been fixed
in the latest released version of Wox, which you can download [here](https://github.com/Wox-launcher/Wox/releases)
