### ISSUE TITLE
有道翻译插件不显示任何翻译内容

### ISSUE THREAD

**Issue by Skyzhu881** [Wox-launcher/Wox#1810]
1. Wox 版本 / commit number：1.3.475
2. 如何**重现** bug：
- 新安装1.3.475，然后安装“有道翻译私Key版”，无法翻译
-  在私key上加入API key，仍然无法翻译
-  删除私key版，安装普通版仍然无法翻译
3. Windows 版本：Windows 10 Enterprise, Version 10.0.16299 Build 16299
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
[2018-01-08.zip](https://github.com/Wox-launcher/Wox/files/1610811/2018-01-08.zip)
6. 截图 （可选）：
[snipaste_20180108_151042](https://user-images.githubusercontent.com/7289765/34661661-1ef220f6-f486-11e7-976c-a0d1c7ff42b4.png)

**Comment by jhdxr** [comment]
无论是哪个版本的插件使用的都是1.1版本的接口，根据 http://fanyi.youdao.com/openapi?path=data-mode 的说明，这个接口从2018.1.1开始已经正式失效了。

由于这个并非wox-launcher本身的问题，因此我关闭这个issue了，建议去插件的repo里提

**Comment by Skyzhu881** [comment]
感谢回复。

**Comment by kitboy** [comment]
我发现有道的插件, 只能工作在wox语言设置为en时候
