### ISSUE TITLE
Settings: German Language is not available

### ISSUE THREAD

**Issue by Ogelmompf** [Wox-launcher/Wox#1818]
1. Wox version number:  1.3.183
2. Steps to **reproduce** the bug:
- Wox Settings/General/Language
- Language german is not available, 
  But the the language-file is in directory
  C:\Users\User\AppData\Local\Wox\app-1.3.183\Languages\de.xaml 
3. Windows version: Win7 Ultimate
4. Exception: - 
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`): -
6. Screenshot (optional): -

**Comment by lances101** [comment]
Could you confirm that this is still an issue on the latest version?
Please download one of the latest versions from [the releases page.](https://github.com/Wox-launcher/Wox/releases)
Reopen if problem persists.

**Comment by Ogelmompf** [comment]
Thanks a lot. It's fixed - works fine!
