### ISSUE TITLE
wox 崩溃了，在windows update后 / Windows 7 KB4055532 Font issues

### ISSUE THREAD

**Issue by leiaoo** [Wox-launcher/Wox#1823]
2018-1-10当天windows进行了以下更新
Windows update 适用于 Windows 7 和基于 x64 系统的 Windows Server 2008 R2 的 Microsoft .NET Framework 4.7.1 (KB4033342)
2018-01 Security and Quality Rollup for .NET Framework 3.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1 on Windows 7 and Server 2008 R2 for x64 (KB4055532)
Windows 恶意软件删除工具 x64 - 2018 年 1 月 (KB890830)
Microsoft .NET Framework 4.7.1 升级语言包 (KB4033339)
然后，Wox就出现运行缓慢，输入反应缓慢，不能打开settings
错误信息如下：

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\leo\AppData\Roaming\Wox\Logs\1.3.475\2018-01-10.txt
2. copy below exception message

Wox version: 1.3.475
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Program Files\Python36\pythonw.exe
Everything SDK Path: C:\Users\leo\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/10/2018 15:07:55
Exception:
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Windows.Markup.XamlParseException: 在“System.Windows.Markup.StaticExtension”上提供值时引发了异常。 ---> System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.TypeInitializationException: “System.Windows.Media.Fonts”的类型初始值设定项引发异常。 ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1 ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1
   在 MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)
   在 MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()
   在 MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)
   --- 内部异常堆栈跟踪的结尾 ---
   在 MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)
   在 MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)
   在 MS.Internal.FontCache.FamilyCollection.SystemCompositeFonts.GetCompositeFontFamilyAtIndex(Int32 index)
   在 MS.Internal.FontCache.FamilyCollection.GetFontFamilies(Uri fontFamilyBaseUri, String fontFamilyLocationReference)
   在 System.Windows.Media.Fonts.CreateFamilyCollection(Uri fontLocation, Uri fontFamilyBaseUri, String fontFamilyLocationReference)
   在 System.Windows.Media.Fonts..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Media.Fonts.get_SystemFontFamilies()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   在 System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   在 System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 Wox.SettingWindow..ctor(IPublicAPI api, SettingWindowViewModel viewModel) 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 34
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Activator.CreateInstance(Type type, Object[] args)
   在 Wox.Helper.SingletonWindowOpener.Open[T](Object[] args) 位置 C:\projects\wox\Wox\Helper\SingletonWindowOpener.cs:行号 11
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 Wox.Plugin.Sys.Main.<Commands>b__14_8(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.Sys\Main.cs:行号 188
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

日志文件如下：  
[2018-01-10.txt](https://github.com/Wox-launcher/Wox/files/1617813/2018-01-10.txt)

**Comment by lances101** [comment]
I cannot check right now as I do not have a Windows 7 machine at hand, but it does seem like you are having some major issues caused by the operating system.

[Take a look here at StackOverflow](https://stackoverflow.com/questions/48206725/no-fontfamily-element-found-in-fontfamilycollection)

While this is definitely an issue, sadly, there is **_nothing_** we (Wox) can do to fix this. Most likely, Microsoft will release a fix sometime soon.

**Comment by richlander** [comment]
Please see https://github.com/dotnet/announcements/issues/53

Please accept my apologies from the .NET team on this issue.

**Comment by leiaoo** [comment]
Thank you.

**Comment by lances101** [comment]
@richlander thank you. 

Issue closed. Please follow one of the workarounds at dotnet/announcements#53

**Comment by richlander** [comment]
I just added a third workaround @ https://github.com/dotnet/announcements/issues/53
