### ISSUE TITLE
WOX的搜索框可以调用everything的filter不？

### ISSUE THREAD

**Issue by cloud-yu** [Wox-launcher/Wox#1826]
## WOX搜索无法使用everything的filter
`版本`：v1.3.475
`everything版本`：v1.4.1.877(x64)

1. `使用everything搜索时`: 可以使用过滤器搜索特定的文件，如“video：”仅搜索视频文件
![image](https://user-images.githubusercontent.com/8436078/34836830-0418c48c-f734-11e7-9ff1-32dd01fa02f9.png)
2. `使用wox搜索时`:无法使用过滤器，搜索无结果
![image](https://user-images.githubusercontent.com/8436078/34836959-4bcd8c04-f734-11e7-849a-7bfd0155e9dc.png)

请问可以在WOX里直接使用everything的过滤器么？

**Comment by lzq2357** [comment]
好像不支持，我试了一天。。。没找到好的方法。估计要重写 wox的 everything插件。   暂时转到 listary 用这个功能了。但是listary 搜索结果感觉不准确
