### ISSUE TITLE
Matching weight for Title and Description on Programs plugin

### ISSUE THREAD

**Issue by lSindra** [Wox-launcher/Wox#1828]
### When
Searching for Programs.

#

### What
Matching weight from program **title** to **description** is the same, resulting in messed up orders. It IS possible to set as 'topmost in this query' but this needs to be done for every combination of letters.

# 

### Possible Solution
Use different weights for measuring the importance of **title** and **description**, iex: 1 to **title** and 0.5 to **description**.
# 
### Screenshot
In this example, first result **title = 'Postman'** and **description = 'Google Chrome'**
![screenshot 5](https://user-images.githubusercontent.com/25848129/34851386-afabdafe-f721-11e7-8dbf-ca0b24b3671a.png)

**Comment by lances101** [comment]
This is definitely not the intended behaviour. Will look into it.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
