### ISSUE TITLE
Icon selection not showing images in explorer

### ISSUE THREAD

**Issue by kleinfreund** [Wox-launcher/Wox#183]
When selecting an icon for a custom web search, the explorer window is not showing image files.

One can still enter the filename of the image to select it.

Also, a question. Are we supposed to copy icons to `Wox/Images/websearch` by hand?

**Comment by qianlifeng** [comment]
Thx, It's a known bug. We will fix this. And yes, we could copy icons to `Wox/Images/websearch`, and locate the folder default to `Wox/Images/websearch`, that should be more handy.
