### ISSUE TITLE
python Hello World 

### ISSUE THREAD

**Issue by KrapfalAT** [Wox-launcher/Wox#1832]
```
# -*- coding: utf-8 -*-

from wox import Wox
import os

class HelloWorld(Wox):
    def query(self, key):
        results = []
        results.append({
            "Title": "Open Slack",
            "SubTitle": "Channel: "+key,
            "IcoPath": "Images/app.ico",
            "JsonRPCAction":{
				"method": "openslack",
				"parameters": [key],
				"dontHideAfterAction":False
            }
        })
        return results

    def openslack(self,key):
		os.system("c:\WOX\Programme\slack.ahk "+key+" ;bis not compiled")


if __name__ == "__main__":
    HelloWorld

```

why does this not work?

**Comment by lances101** [comment]
You can always check Wox logs at `%appdata%/Wox/Logs/<date>.txt`. Any python errors (as long as they are actual errors) will be there

I cannot run the code right now, but just from a quick look, I see a couple of issues. 

<img width="267" alt="2018-01-12 23 12 56" src="https://user-images.githubusercontent.com/4784785/34897424-3d409414-f7ee-11e7-9441-ca8d7d027fe9.png"> 

(dots are spaces, arrows are tabs)

In Python you cannot mix tab and space indentation, which you are doing as seen on the screenshot. Also, you are not calling the HelloWorld function in the last line, you lack braces `()`

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
