### ISSUE TITLE
Wox settings and hotkey didn't work, but go back normal again after restarting

### ISSUE THREAD

**Issue by waithope** [Wox-launcher/Wox#1839]
- Wox version / commit number: 1.3.475
- Windows version:window 10 10.0.16299

It happened multiple times in the past few days,  it's kinda annoying to restart.
By the way,  always happened on system startup.

**Comment by lances101** [comment]
Once you restart your machine and this happens, attach a log file that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`
