### ISSUE TITLE
请问下：给常用程序设立别名

### ISSUE THREAD

**Issue by babyforever** [Wox-launcher/Wox#1840]
## Known problems for 1.3.505:

你好。刚开始用，发现搜索文件和程序都很快，很赞。但是，常用的程序有的名字很长，能不能和AltRun之类的软件那样，可以给常用程序起个别名? 比如，photoshop，直接通过别名ps快速搜索找到程序？

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
Once you type "ps" you can select Photoshop in the list of results, press <kbd>Shift</kbd>+<kbd>Enter</kbd> (or right-click on the result) and select "Set as topmost in this query". This will ensure that upon typing "ps" the first result is always Photoshop. 

Reopen if you still need help.
