### ISSUE TITLE
程序启动时磁盘读写过于频繁

### ISSUE THREAD

**Issue by lkytal** [Wox-launcher/Wox#185]
大概有20s磁盘占用在90%以上...

**Comment by qianlifeng** [comment]
可能因为在索引程序目录的原因

**Comment by lkytal** [comment]
估计也是... 所以还是推荐使用ntfs索引啊, listary启动机非常流畅...

**Comment by byzeus2014** [comment]
开机启动的时候，不用重新索引程序目录吧？ 因为刚开机，程序目录与上次关机是不会发生变更的，直接使用上次关机前建立的索引就OK。
是否可以更改为：先使用上次关机前建立的索引，程序在后台自己重建索引。

**Comment by qianlifeng** [comment]
@byzeus2014 可以，以此换来更快的启动时间。

**Comment by byzeus2014** [comment]
希望能加入这个调整啊. 我也想做份贡献, 可是我没有搞过C#啊....
现在这个软件的一个功能就是要替掉桌面的快捷方式，如果启动慢的话，开机基本处于不可用的状态，所以个人感觉这个问题是最严重的。基本上可以把这个软件置于不可用的状态。
