### ISSUE TITLE
Is there a way to keep the order of the results? (Plugin)

### ISSUE THREAD

**Issue by harrynull** [Wox-launcher/Wox#1857]
I am trying to make a dictionary plugin for Wox. It is almost done but there's one problem that the order of the results is not fixed: even the item is the first element of the `List<Result>` returned by `Query` function, it is not guaranteed that it is the first in the result list. It could be annoying since the full match result sometimes isn't at the top.

So, is there a way to ensure a specific result is always at the top?

**Comment by inormis** [comment]
Same problem for me

E.g. My Plugin returns a collection of Result objects in next order
- Result1
- Result2
- Result3

The order is very important to me. But Wox changes order based on the frequency of usage of the Results and maybe smth else.
Change of Score of the result doesn't help. 
It seems like there's no way to influence the order?

![image](https://user-images.githubusercontent.com/2038932/65635747-36b55580-dfe1-11e9-8256-a9355a8a7352.png)

**Comment by bao-qian** [comment]
you can keep order now, please use new version and set `KeepResultRawScore` in plugin metadata

https://github.com/Wox-launcher/Wox/pull/2834/files
