### ISSUE TITLE
everything插件：使用应用程序的位置为可执行的工作目录是什么意思

### ISSUE THREAD

**Issue by meison92** [Wox-launcher/Wox#1860]
(drop your screenshot here)

![default](https://user-images.githubusercontent.com/17672199/35423424-a9176dd0-0288-11e8-9540-f94a3388b510.png)

**Comment by jhdxr** [comment]
这东西。。。虽然翻译的有些拗口，但其实意思并没错。。。如果你看不懂的话也许你需要去[这个wiki](https://en.wikipedia.org/wiki/Working_directory)
