### ISSUE TITLE
python plugin: cannot work when inputing chinese query

### ISSUE THREAD

**Issue by ohfighting** [Wox-launcher/Wox#1861]
Hi, I am a wox fan since version 1.0. Now I want to update my wox 1.0 to the lastest version v1.3.475 because of many exciting features.

I test the python plugin HelloWorld(Default). When I input "h test", it works well. But when I input "h 测试", there is not any response.
It seems that the v1.3.475 cannot support chinese query in python plugin. 
Can you examine  this problem? Thanks very much!

Win10
Wox v1.3.475 
Python2.7.8

**Comment by lances101** [comment]
Sorry, Python 2 handles strings differently to Python 3 and the default plugin that we distribute with Wox targets Python 3. 

You can install Python 3 side by side with Python 2 and set the Python path in Wox to Python 3. 

Reopen if you still have issues.

**Comment by AndrewLauu** [comment]
Would you like to explain how can I use the "HelloWorld" plugin, and what is it usage?

Thanks a lot.
