### ISSUE TITLE
Missing custom websearch

### ISSUE THREAD

**Issue by Ponf** [Wox-launcher/Wox#1862]
### Are you submitting a bug report?

YES

### Steps to reproduce

1. I have created custom search to open specific page with parameter
2. After some time custom search disappeared from Web Searches plugin list
3. I still see suggest in Wox main window, but it doesn't work
4. When I'm trying to add same search again, I receive error

### Wox Error Window 

![screenshot-2018-01-26 17 07 43](https://user-images.githubusercontent.com/1001409/35443572-aa04765a-02bc-11e8-8770-2c17d74d124b.png)

**Comment by alexya** [comment]
From the error prompt message, it seems that the Action Keyword `exp` you set for it has been used by another plugin. 
Could u please try to change the Action Keyword to another one such as `pxe`, etc.

**Comment by lances101** [comment]
Wox version?

**Comment by Ponf** [comment]
@lances101 1.3.475

@alexya `exp` keyword was used by me and it worked for few days, but now it's lost (I don't see my custom search with `exp` keyword). Also main window doesn't show anything on `exp`:
![screenshot-2018-02-12 11 37 00](https://user-images.githubusercontent.com/1001409/36088730-7385b47e-0fe9-11e8-8c6c-18c2fdff829a.png)

I thing local cache with plugin settings got corrupted, so that's why I don't see my custom search.

**Comment by joekwon** [comment]
I just installed Wox a week ago and I'm experiencing this exact bug. I'm able to create a customer we search with an action keyword but the keyword stops working after a few hours and disappear from the list. Any attempt to recreate the custom search with the same action keyword results in the same error. I'm on Windows 10 64-bit and Wox 1.3.524.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
