### ISSUE TITLE
[Suggestion] Consider the ability to enable drag and drop for searches that return files

### ISSUE THREAD

**Issue by cosimochellini** [Wox-launcher/Wox#1864]
For me, a really useful feature would be to be able to, _after doing the search for the selected file_, drag the file / folder as in the default expoler file and release it where needed.

**Thanks for listening and patience**

**Comment by phileastv** [comment]
I recently switvhed from Listary to Wox, and this is a feature I miss so much.

I would greatly appreciate to see this implemented in Wox !

**Comment by cosimochellini** [comment]
@wedza this project is dead, consider this similar app, its great
https://github.com/oliverschwendener/ueli
