### ISSUE TITLE
my new issue

### ISSUE THREAD

**Issue by tt502199126** [Wox-launcher/Wox#1870]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by jhdxr** [comment]
Close due to emty issue.
Feel free to reopen it if you could provide more detail (kindly refer to the instructions in this issue template)
