### ISSUE TITLE
Feature Request: allow passing parameters to program before launching it.

### ISSUE THREAD

**Issue by vhanla** [Wox-launcher/Wox#1871]
### Are you submitting a bug report?

No

First and foremost, thank you for this awesome software, it is a must.

Feature Request:

I would like to know if there is a way to add parameters after finding a program.

I know that .lnk files already include params, but reading a .lnk file is relatively easy, and it might be handy to show them before proceeding to launch a program and also modify those params too.
In case it is an executable it might just be a matter of adding the parameters before launch.

Scenarios:
Specially for programmers. Sometimes some software we use requires to pass parameters to get a special behaviour on the target software. e.g. launching another Firefox instance with a different user profile (`firefox.exe -P <profilename>`), debugging parameters, etc. also for Chrome, or any other software that have command line options.

In case this is a no go for now, maybe you could tell me if that could be achievable with a plugin so I might write it.

Extra: remember or save them labeled so it might save us to write the same parameters again and again.

**Comment by lances101** [comment]
This is not currently possible, and I think we had a similar suggestion although I cannot find it right now. I am interested in this feature myself, but I currently don't have the time to take a look into it. 

As for writing a plugin that would allow you to do this, well, if you are proficient in C# you could take a look at the implementation of the "Program" plugin and send us a PR that allows to pass command line arguments. 

I think the correct way to go about this is to add an extra key character that at the same time is not a valid Windows path character (like `>`) and then passing everything that follows it as a parameter.

If you would rather write your own plugin, you would need to add the option of adding a specific executable, an alias, and then splitting the query string into the matching alias and the arguments.

**Comment by vhanla** [comment]
Thank your for your answer. I tried to compile it but I'm not sure why it doesn't compile, I guess it has to do with UWP apps listing, which I suppose requires a Windows 10 special library, which I cannot build with. 
UWP.cs Package is not found even though I added Windows.WinMD in references.
