### ISSUE TITLE
Hotkey Error

### ISSUE THREAD

**Issue by tboevil** [Wox-launcher/Wox#1876]
### Are you submitting a bug report?

绑定时如果使用中文,ALT+~,切换英文后无法启动,且绑定时显示为Oem8

**Translation (from online translator):**
Binding if you use Chinese, ALT+~, to switch to English after not start, and the binding is displayed as Oem8

**Comment by jhdxr** [comment]
这个的确是和输入法的兼容有关系，显示为`oem8`说明输入法拦截了你的输入，应用并不知道你真正输入了什么

**Comment by tboevil** [comment]
目前我是用ahk解决的,我看看有没有更好的解决办法

**Comment by jhdxr** [comment]
试下这个版本：

try this build:


https://ci.appveyor.com/project/happlebao/wox/build/1.3.521/artifacts
