### ISSUE TITLE
After opening a window and then pressing the hotkey will bring the search bar but it wont have focus.

### ISSUE THREAD

**Issue by questking** [Wox-launcher/Wox#1878]
If you open a window eg. a folder and then press the hotkey for wox, the search bar shows up but without focus. I think there is a solution to it but since i am unable to compile it from source. I will write it here for someone to test.

In the OnLoaded() event in MainWindow.xaml (code behind) add -> this.Activate(); 
Please check if this works.

**Comment by LMLB** [comment]
Having the same problem. (I have the hotkey set to Ctrl+Win+Space if it matters)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
