### ISSUE TITLE
Web Searches URL编码问题

### ISSUE THREAD

**Issue by 9chu** [Wox-launcher/Wox#188]
搜索路径中包含非法字符时没有对其做URL Encode，自定义百度搜索时无法正常使用。

此外，建议增加插件帮助功能。如在plugin.json中追加帮助信息。

**Comment by qianlifeng** [comment]
此问题已经被@zlsun 修复，后续的版本会包含此修改。[https://github.com/qianlifeng/Wox/commit/9ae8c27a364212b0178165701259c100052ada4e](https://github.com/qianlifeng/Wox/commit/9ae8c27a364212b0178165701259c100052ada4e)
