### ISSUE TITLE
请问能否增加【去掉任务栏托盘图标】的选项吗？

### ISSUE THREAD

**Issue by salutkun** [Wox-launcher/Wox#1884]
请问能否增加【去掉任务栏托盘图标】的选项吗？ 

 **translation (by @jhdxr)**  
any option to remove tray icon?

**Comment by alexya** [comment]
我倒是觉得留着挺好的。就是感觉这个图标有点儿丑，能换个漂亮的么？
看Alfred的图标，好漂亮的说......

**Comment by jhdxr** [comment]
@alexya 欢迎PR

Duplicate of #563
