### ISSUE TITLE
Any way to force Wox to a specific monitor?

### ISSUE THREAD

**Issue by hillsoftware** [Wox-launcher/Wox#1889]
### Are you submitting a bug report?

(NO)

Is there a way to force Wox to only appear on a specific monitor? Or could this be added as an option?

I run 3 monitors and if I have something full screen and I hit ALT SPACE, I would like the pop up for wox to appear on my left monitor.  That way I can use wox, but not pop the game or whatever out of full screen when it needs to leave full screen to show the wox screen on the middle monitor.

Thanks for your time.

Michael

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
