### ISSUE TITLE
开机第一次启动时总要加载很久

### ISSUE THREAD

**Issue by csvwolf** [Wox-launcher/Wox#189]
第一次启动 无法用快捷键唤出 只能手动点击等待完全启动完毕

Win8.1 x64

**Comment by byzeus2014** [comment]
根本原因是启动慢吧... 还没有启动完成, 导致不能响应快捷键. 我的Win7 x64也有同样的问题.

**Comment by csvwolf** [comment]
不光是慢吧……无论开机之后多久 只要我不手动点击等待启动永远启动不完

**Comment by shangvven** [comment]
win10 预览版，系统启动后，可以用快捷键直接呼出

**Comment by byzeus2014** [comment]
这么牛。。。纯SSD硬盘吗？

**Comment by jinlong** [comment]
我的windows8.1，第一次启动也很慢，不知道有什么办法没，其它都挺好的

**Comment by byzeus2014** [comment]
慢的原因应该是这个 ： https://github.com/qianlifeng/Wox/issues/185

**Comment by jinlong** [comment]
这个有做改善嘛？第一次启动半天不可用，有点郁闷。。。@byzeus2014

**Comment by qianlifeng** [comment]
启动慢还是因为加载插件，索引文件等操作引起的。后面看能不能做些改善，改善方法之一就是缓存索引文件，每次启动的时候先读取上次的索引信息，然后后台静默索引替换更新。

**Comment by byzeus2014** [comment]
新版本启动快了很多！

**Comment by jinlong** [comment]
太帅了，速去下载个最新版

**Comment by mitoop** [comment]
我用SSD启动还是很慢 希望改进啊 @qianlifeng

**Comment by elitezhe** [comment]
本人纯SSD, win7 x64, 开机后第一次alt + 空格 呼出,总是需要很长时间,大约5秒(无论开机过了多长时间,只要是第一次呼出). 以后用都是快的一比, 立即出现.

**Comment by csvwolf** [comment]
确实比上个版本快 但这个问题还存在QvQ

**Comment by qianlifeng** [comment]
最近的版本还没有修复这个问题，感觉快了一点的应该是心理作用:smile:。后面会优化启动速度的。

**Comment by qianlifeng** [comment]
启动慢的问题找到了，并不是索引文件引起的。因为索引文件会在线程中执行，所以不会拖慢启动速度。问题在这里 https://github.com/qianlifeng/Wox/blob/master/Wox/PluginLoader/Plugins.cs#L35

**Comment by mitoop** [comment]
@qianlifeng  wox有时候退出是什么情况 期待下一个build赶紧降临.

**Comment by qianlifeng** [comment]
@mitoop 能不能重现退出的具体步骤？或者log.txt有没有什么具体的错误信息？

**Comment by mitoop** [comment]
@qianlifeng 最多的情况是刚开机时右键打开 没有反应(或者短暂出现搜索框,搜索框左下角有蓝色下边线)就退出去了 日志里几乎都是这两种warning级别的:"指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。" 或者 "Can't access to directory....."不能到达目录

**Comment by bingu** [comment]
啥时候能release新版本补上这个呢

**Comment by qianlifeng** [comment]
@bingu 快了，最近在做新的Wox网站。

**Comment by mitoop** [comment]
@qianlifeng  现在wox等待启动好后 只要输入稍微快点 就自己退出了 不知道什么情况 新版本大概什么时候出来啊

**Comment by qianlifeng** [comment]
[V1.0.2](https://github.com/qianlifeng/Wox/releases) 已经出来了

**Comment by mitoop** [comment]
马上 下载试试

**Comment by jinlong** [comment]
哈哈，马上下载新版

**Comment by calon** [comment]
新版第一次启动后输入字符就报错，但是没有截屏记录。
后来也没有复现过了。

**Comment by qianlifeng** [comment]
@calon 下次有错误记得提个issue :smile:
