### ISSUE TITLE
If a keyword does not match any local result, directly run an online search and pop out the result.

### ISSUE THREAD

**Issue by Kooklen** [Wox-launcher/Wox#1890]
本地搜不到的关键词直接跳出搜索引擎比较好？like Alfred

**Translation:**
If a keyword does not match any local result, directly run an online search and pop out the result.

**Comment by VictoriousRaptor** [comment]
If a keyword does not match any local result, directly run an online search and pop out the result.

**Comment by jhdxr** [comment]
@VictoriousRaptor Thanks for the translation, I have updated it.

**Comment by jhdxr** [comment]
目前wox的在线搜索其实还都是打开浏览器去搜索的。这个功能要求首先在wox内实现搜索以及结果的获取

**Comment by ilharp** [comment]
赞同。
Microsoft UWP Toolkit 上面有类似的实现（也有source code）。
