### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by LmKong** [Wox-launcher/Wox#1893]
### Are you submitting a bug report?

(write your answer here) Yes.

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)Wox version: 1.3.475
OS Version: Microsoft Windows NT 6.2.9200.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\john\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/09/2018 08:11:01
Exception:
System.MissingMethodException: 找不到方法:“Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)”。
   在 Wox.Core.Resource.Theme.SetWindowAccent(Window w, AccentState state)
   在 Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 62
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here) C:\Users\john\AppData\Roaming\Wox\Logs\1.3.475\2018-02-09.txt

### Screenshots (optional)

(drop your screenshot here)

**Comment by jhdxr** [comment]
could you give any details about what actions did you do? otherwise it's a bit difficult to reproduce this issue.

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
