### ISSUE TITLE
启动wox时不插移动硬盘就会报错

### ISSUE THREAD

**Issue by NightWatch0** [Wox-launcher/Wox#1895]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.不插移动硬盘时打开wox（以前基本不拔下来）
2.出现错误

### Wox Error Window text

Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\qq404\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/10/2018 18:31:15
Exception:
System.AggregateException: 发生一个或多个错误。 ---> System.IO.DirectoryNotFoundException: 未能找到路径“E:\Steam\steamapps”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   在 WoxSteam.Library.<GetGames>d__5.MoveNext() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Library.cs:行号 47
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 WoxSteam.Steam.LoadGames() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:行号 191
   在 WoxSteam.Steam.Load() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:行号 60
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 91
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (内部异常 #0) System.IO.DirectoryNotFoundException: 未能找到路径“E:\Steam\steamapps”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   在 WoxSteam.Library.<GetGames>d__5.MoveNext() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Library.cs:行号 47
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 WoxSteam.Steam.LoadGames() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:行号 191
   在 WoxSteam.Steam.Load() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Steam.cs:行号 60
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

### Detailed logs

[2018-02-10.txt](https://github.com/Wox-launcher/Wox/files/1713279/2018-02-10.txt)

### Screenshots (optional)

(drop your screenshot here)
![default](https://user-images.githubusercontent.com/24457233/36061177-9f1e156c-0e91-11e8-8d06-9e6651b237ee.png)

**Comment by lances101** [comment]
Said plugin is developed by a third-party and we cannot provide support for it or update it. You can ask the developer to update it, or you can fork, update and upload it yourself as a new plugin.

If this plugin is causing you problems and you cannot use Wox, you need to delete this plugin. This can be done by exiting Wox, going to `%appdata%/Wox/Plugins` and deleting the corresponding plugin's folder.

Closed due to being a third-party plugin.

**Comment by NightWatch0** [comment]
但即使我关闭了steam插件后还是报错……

发件人: Boris Makogonyuk
发送时间: 2018年2月11日 1:24
收件人: Wox-launcher/Wox
抄送: NightWatch0; Manual
主题: Re: [Wox-launcher/Wox] 启动wox时不插移动硬盘就会报错 (#1895)

Steam is not an official Wox plugin and therefore we cannot provide support for it.
Please open an issue in the repo of the plugin

**Comment by lances101** [comment]
@NightWatch0, as I said before, the plugin does not seem to be compatible with the version of Steam you have installed or there is a different issue which we cannot control. I do not have Steam installed and cannot tell you what exactly is going wrong. 

What you can do so that you don't have the error appearing in Wox is to delete the Steam **plugin**. To do this follow these steps:
- Exit Wox (right-click in the task bar and click "Exit")
- Press <kbd>Win</kbd> + <kbd>R</kbd> and into the Run box type `%appdata%/Wox/Plugins`
    This will open the folder where Wox stores its plugins. 
- Find the the folder that contains the Steam plugin. It most likely has the word "Steam" in it
- Delete that folder
- Start Wox

**Comment by NightWatch0** [comment]
好吧，你是对的，非常抱歉打扰你了，谢谢
发件人: Boris Makogonyuk
发送时间: 2018年2月11日 7:16
收件人: Wox-launcher/Wox
抄送: NightWatch0; Mention
主题: Re: [Wox-launcher/Wox] 启动wox时不插移动硬盘就会报错 (#1895)

@NightWatch0, as I said before, the plugin does not seem to be compatible with the version of Steam you have installed. I do not have myself Steam installed and cannot tell you what exactly is going wrong.
What you can do so that you don't have the error appearing in Wox is to delete the Steam plugin. To do this follow these steps:
• Exit Wox (right-click in the task bar and click "Exit")
• Press Win + R and into the Run box type %appdata%/Wox/Plugins
This will open the folder where Wox stores its plugins.
• Find the the folder that contains the Steam plugin. It most likely has the word "Steam" in it
• Delete that folder
• Start Wox
