### ISSUE TITLE
Auto dismiss when not focused anymore

### ISSUE THREAD

**Issue by zhuochun** [Wox-launcher/Wox#19]
Auto hide when the focused has changed to other apps.

**Comment by orzFly** [comment]
I think it's good to _add an option_ for this. But don't force this option
because I think sometimes it's useful to switch to other apps and then back.

**Comment by zhuochun** [comment]
@orzFly Agrees.

**Comment by qianlifeng** [comment]
auto dismiss Wox maybe not a good option for most people.
