### ISSUE TITLE
Runtime error in win8.1

### ISSUE THREAD

**Issue by fzxing** [Wox-launcher/Wox#190]
Previously, I use Wox(1.0 beta) in win7, it works well.
Now my os is update to win8.1, runtime errors always occur, randomly.

below is the log:
Date：2014-10-08 12:20:26,929 Level：ERROR Msg：Python Invoke failed: IndexError : list index out of range
Date：2014-10-08 12:20:27,603 Level：ERROR Msg：Python Invoke failed: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。

**Comment by qianlifeng** [comment]
Please try the latest version of Wox. [https://github.com/qianlifeng/Wox/releases](https://github.com/qianlifeng/Wox/releases)

**Comment by fzxing** [comment]
Thank you for your quick reply. The lastest version seems to has a little problem of pip_install.

I need to use pip_install and easy_install to add some python package. With wox of the old version, i install python and related environment myself.

In the lastest version, python environment is integrated into release package. But when click pip_install or easy_install (Path: PythonHome\Scripts), an error message is prompt:
驱动器中没有磁盘，请在驱动器E:中插入磁盘

My PC only has disk of C:\
