### ISSUE TITLE
Hi guys, some Qs

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#1904]
I'm really new to GitHub. I'm actually fairly decent at coding stuff in some languages, definitely need to brush up on python. I'm keen to help out. But I don't really know where to start. I definitely do not understand github. I have some great ideas for plugins. I use Wox all the time. (It's super). I'd love to do some updated to runner for example.

Can I ask some Qs and hopefully folks can point me in the right direction. These are mainly for the owner or regular contributors.

1. Are you using Beta or Stable on your computers? If not Beta why not? It seems to work fine for pretty much everything.

- How to use the repositry to update files on a compiled wox exe for daily usage? I.e. someone hits issue fixed, uploads a file (e.g. hotkey.xml I think i just saw by jhdxr to fix 1876) , how do I take advantage of that change in my running wox? There is no exe file nor matching xml file in the %userprofile%\appdata\local directory?

- are you guys somehow installing the nuget package via Visual Studio? 

- For example I currently have my github desktop cloning the repositry to %userprofile%\Documents\github should it perhaps clone to %userprofile%\appdata\local to autoupdate wox?

2. Starting wox as admin so that programs can be started as admin seems really important. I'm trying to piss about with bat files to get windows to just do it without a UAC prompt on startup (but without directly opening it using task scheduler which basically seems to lower the priority of the processes). Best way so far is a bat file run on startup by TS as admin. 

3. Loads more Qs but this seems a good start.

Cheers!
Lewis

**Comment by jhdxr** [comment]
> Are you using Beta or Stable on your computers? If not Beta why not? It seems to work fine for pretty much everything.

Yup. [CI](https://ci.appveyor.com/project/happlebao/wox/history) will build it for you. no need to replace anything manually

> are you guys somehow installing the nuget package via Visual Studio

Affirmative for me. but I'm not sure about other people, since I'm not an expert at c#.

the folder containing this repo (source code) has nothing to do with the folder where wox will be installed. 

> Starting wox as admin so that programs can be started as admin seems really important. 

really bad idea. it means you bypass UAC totally. If some program need to be run as admin (should be minor), just right click on the result, and there should be an option called "run as admin"

**Comment by lgjmac** [comment]
Thank you for this jhdxr. I appreciate it, genuinely.

On the UAC point, do you think UAC is a very important safeguard? I do find the box annoying and love being able to write directly in powershell as admin from wox.

**Comment by jhdxr** [comment]
yep, UAC is very important. If you really don't like it and you don't care about the security, you can just disable it.

**Comment by bao-qian** [comment]
close due to no further activity.
