### ISSUE TITLE
http://www.getwox.com/plugin is down! :(

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#1905]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by lgjmac** [comment]
Bad timing because I just uninstalled wox trying to work out the plugin configurations ... :(

**Comment by jhdxr** [comment]
looks like the whole site went down. @bao-qian may be the host is expired?

**Comment by bao-qian** [comment]
website back now: wox.one
sorry for inconvenience

**Comment by bao-qian** [comment]
You need new version of wow to use new website
