### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by baosailong** [Wox-launcher/Wox#1906]
### Are you submitting a bug report?
Yes.
(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 02/20/2018 03:03:01
Exception:
Wox.Plugin.Folder
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Folder.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:行号 40
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 81
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

### Detailed logs

(drop your log file here)
[2018-02-20.log](https://github.com/Wox-launcher/Wox/files/1737941/2018-02-20.log)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
use new version
