### ISSUE TITLE
Now that getwox.com doesn't work....

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#1908]
Please please can somebody tell me how to install the plugins like clipboard, kill, colors, etc? None of them have wox files on the repo....

Thank you!

Is everyone else able to install plugins somehow? wpm install .... doesn't work for me.

**Comment by Shinao** [comment]
On my version 1.3.183 I just need to create a folder in the plugin directory with the correct files then restart wox and the new plugin is detected.
![2018-02-22_11-16-31](https://user-images.githubusercontent.com/3755971/36532764-eddbfc12-17c1-11e8-8086-8696aa125764.jpg)

To get the files you either have to find them or compile them yourself.
Example with my plugin https://github.com/Shinao/Wox.Plugins/tree/master/Need
Compile it and copy and paste everything in Release into that Newplugin folder.

**Comment by lgjmac** [comment]
Thank you!
But please could you go through exactly what you mean by compile. As in foolproof steps (assuming in Visual Studio?) Thanks!

**Comment by Shinao** [comment]
- Launch Visual Studio
- Open the project (Need.csproj for example)
- Build > Build Solution
- Go to folder `TheProject/build/Release`
- Copy everything into a folder in the Wox plugins directory (Wox settings > Plugins > Plugin directory)
- Restart Wox

**Comment by bao-qian** [comment]
website back now: wox.one
sorry for inconvenience

**Comment by bao-qian** [comment]
You need new version of wow to use new website

**Comment by bao-qian** [comment]
You need new version of wow to use new website
