### ISSUE TITLE
I don't think it's coming back. Does anyone have any good alternatives?

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#1909]
So far I have tried:
-cerebro (ok but not great)
-keypirinha, yeah sort of new good reviews, ini file type is interesting but ultimately it doesn't save many key presses at all.
- something by nirsoft
- something called zaza or zuzu but it wouldn't even install
- I have tried assembling wox plugins in visual studio, and using wox library, but I'm really unfamiliar with VS and can't work it out, 
- a mixture keypirinha and autohotkey seems the best alternative but it isn't the same :(

PLEASE COME BACK WOXY

**Comment by bao-qian** [comment]
website back now: wox.one
sorry for inconvenience

**Comment by bao-qian** [comment]
You need new version of wow to use new website

**Comment by bao-qian** [comment]
You need new version of wow to use new website
