### ISSUE TITLE
 pip_install and easy_install not work

### ISSUE THREAD

**Issue by fzxing** [Wox-launcher/Wox#191]
In the lastest version, python environment is integrated into release package. 
But when click pip_install or easy_install (Path: PythonHome\Scripts), an error message is prompt:
驱动器中没有磁盘，请在驱动器E:中插入磁盘

My PC has disk of C: only  and Wox is located at c:\,

**Comment by qianlifeng** [comment]
Download `pip.bat` and `pythonx.bat` from [https://github.com/qianlifeng/Wox/tree/dev/PythonHome](https://github.com/qianlifeng/Wox/tree/dev/PythonHome) and replace them in `PythonHome`.  

Then, try to use `pip.bat install xxx` command in PythonHome directory.

**Comment by fzxing** [comment]
Thanks, qianlifeng. The bat file works well for pip install.

Furthermore, i try to intall pywin32-219.win-amd64-py2.7.exe into PythonHome, which cannot be installed via pip. However, this setup package can be only installed to the home_installtion_path of python-2.7.6.amd64.msi(according to windows registry). So i have to install python-2.7.6.amd64.msi to overwrite exiting file in Wox\PythonHome.

After installtion, I trigger python plugin in wox, an error is prompt:
![11](https://cloud.githubusercontent.com/assets/7519334/4603067/20df7f62-515a-11e4-9bcb-56e5f4ff6c6d.PNG)

The python plugin works well in the wox of 1.0 beta, where i setup python environment myself.
(Many usefull python package can be installed via .exe only, maybe old manner of python installtion in wox 1.0 beta is a better solution for Wox)

**Comment by qianlifeng** [comment]
We have changed Python plugin API. Pls check [https://github.com/qianlifeng/Wox/blob/master/Plugins/Wox.Plugin.HackerNews/main.py](https://github.com/qianlifeng/Wox/blob/master/Plugins/Wox.Plugin.HackerNews/main.py) as example.

**Comment by fzxing** [comment]
Thank you for your help :-)
