### ISSUE TITLE
Make the order of result items fixed (Python plugin)

### ISSUE THREAD

**Issue by ohfighting** [Wox-launcher/Wox#1911]
Wox is an exciting tool which help me a lot in my work. 
Now I have update wox from 1.0 to 1.3.475. 
Everything works better, however, I found a problem: the order of result items is changeable.
In my Python plugin, it will generate 5 results and I need the position of each result items fixed (in specific  order).
I think it is a very important feature for some plugins. Is there anyway to realize it?
Thanks very much!

**Comment by Garulf** [comment]
It’s not pretty but I’ve corrected this by using a random number printed off screen with each result. Keeps the order maintained at least until support is added. Needed this for my Twitter plugin I made. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ohfighting** [comment]
@Akrasia , thanks very much!  Can you provide a link of your twitter plugin, or show some code snippet of "using a random number printed off screen"

**Comment by bao-qian** [comment]
if you want to keep order, then set the score for result according to your order.

**Comment by bao-qian** [comment]
you can keep order now, please use new version and set `KeepResultRawScore` in plugin metadata

https://github.com/Wox-launcher/Wox/pull/2834/files

**Comment by 42useGitHub** [comment]
> you can keep order now, please use new version and set `KeepResultRawScore` in plugin metadata
> 
> https://github.com/Wox-launcher/Wox/pull/2834/files

how to make it on my own computer to "set KeepResultRawScore"

I can not find any config-like file in my wox directory that I can "set KeepResultRawScore"
