### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dasu88** [Wox-launcher/Wox#1915]
[2018-02-26.txt](https://github.com/Wox-launcher/Wox/files/1757017/2018-02-26.txt)

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
