### ISSUE TITLE
Too much cpu usage on Windows

### ISSUE THREAD

**Issue by Qvinto1** [Wox-launcher/Wox#1917]
Wox seems to constant using ~4%CPU on windows 10. This can be a significant battery drain for laptops - is there any way this can be reduced?

**Comment by IanSmith123** [comment]
This is mine. It's ok. 

version: 1.3.524
![](http://oqyjccf1n.bkt.clouddn.com/20180228-201529.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
