### ISSUE TITLE
Wox ID how to generate

### ISSUE THREAD

**Issue by shanddzhou** [Wox-launcher/Wox#1918]
I want to try to write a WOX plugin, but do not know how the ID is generated?

**Comment by IanSmith123** [comment]
Maybe you need this. https://www.uuidgenerator.net/

**Comment by shanddzhou** [comment]
Okay thank you. But this generated ID will not be repeated?

2018-02-28 20:12 GMT+08:00 Les1ie <notifications@github.com>:

**Comment by bao-qian** [comment]
@shanddzhou 
yes, you can generate uuid/wox id in that way.
