### ISSUE TITLE
Python plugin exception when inputing chinese character in v1.0.0.219

### ISSUE THREAD

**Issue by fzxing** [Wox-launcher/Wox#192]
In the lastest version 1.0.0.219 with python plugin, it works well when inputing english, but when i input chinese, wox prompt a python runtime error , as below:
![default](https://cloud.githubusercontent.com/assets/7519334/4609065/3318237e-5294-11e4-9eb0-dede980be7b2.PNG)

Even i trim the code as below, error is also occured: 

```
#encoding=utf8
from wox import Wox,WoxAPI
class FaPiao(Wox):
    def query(self, query):
        return []
if __name__ == "__main__":
    FaPiao()
```

It ok when input: "fp abc", but error when input "fp 你好"

**Comment by qianlifeng** [comment]
It's encoding issues in Python, Pls use the latest `wox.py` file. [https://github.com/qianlifeng/Wox/blob/dev/PythonHome/wox.py](https://github.com/qianlifeng/Wox/blob/dev/PythonHome/wox.py)

**Comment by fzxing** [comment]
Thank you for fixing so quickly! Now it's OK.
