### ISSUE TITLE
PirateBay 搜索结果出现后，回车跳转至任意结果，会 Wox got an error.

### ISSUE THREAD

**Issue by payshangjj** [Wox-launcher/Wox#1926]
[2018-03-02.txt](https://github.com/Wox-launcher/Wox/files/1774017/2018-03-02.txt)

PirateBay 搜索结果出现后，回车跳转至任意结果，会 Wox got an error.

### Steps to reproduce

1.
![1](https://user-images.githubusercontent.com/7725874/36887339-b4be441a-1e2b-11e8-85ed-8574ac6bd271.png)
 
2.回车

3.  Wox got an error.

![default](https://user-images.githubusercontent.com/7725874/36887373-de95f2e2-1e2b-11e8-8790-8f4bd4f43100.png)

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\layne\AppData\Roaming\Wox\Logs\1.3.183\2018-03-02.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 03/02/2018 15:07:11
Exception:
System
System.ComponentModel.Win32Exception
Unknown error (0x80041002)
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.PirateBay.Main.<>c__DisplayClass3_0.<Query>b__0(ActionContext e) 位置 C:\Users\dmratcliffe\Source\Repos\triggerbot\Wox.Plugin.Torrent\Wox.Plugin.Torrent\Main.cs:行号 53
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 153
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-03-02.txt](https://github.com/Wox-launcher/Wox/files/1774025/2018-03-02.txt)

### Screenshots (optional)

(drop your screenshot here)
![default](https://user-images.githubusercontent.com/7725874/36887213-16662ac6-1e2b-11e8-8a9e-aa1e0cae418d.png)

**Comment by niv-d** [comment]
This is my plugin, I'm not sure whats gone wrong.

It looks like you don't have an application to open magnet links, what is your torrent client?

**Comment by gkgy** [comment]
我也是

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
