### ISSUE TITLE
建议：增加关闭模糊匹配和排除文件夹的功能

### ISSUE THREAD

**Issue by mxalbert1996** [Wox-launcher/Wox#1927]
![Pic1](https://user-images.githubusercontent.com/9391933/36933590-be185fb4-1f16-11e8-9fb5-936769efffe1.png)
先说模糊匹配，现在的匹配模式（Everything 搜索以外）应该是并不要求包含整个单词，而是只要含有其中所有字符并且先后顺序正确就算匹配上，但我觉得这样对我来说完全没有意义，我希望能够精确匹配（或者只开启首字母匹配）。

![2018-03-03 4](https://user-images.githubusercontent.com/9391933/36933596-d291a09a-1f16-11e8-83fa-d3e54673b76f.png)
然后是排除特定文件夹，有时候遇到这种情况体验真的非常糟糕。

**Comment by cqjjjzr** [comment]
bump. 也可以改进评分功能，让能精确匹配的排在最前，最好降低一下以使用次数判定的权值

**Comment by yunkuangao** [comment]
+1
