### ISSUE TITLE
多屏显示建议

### ISSUE THREAD

**Issue by chernglee** [Wox-launcher/Wox#1928]
在多屏幕的任何一个屏幕中操作wox，该程序会在当前屏幕打开？
这个功能能不能加入？

**Comment by jafin** [comment]
> Operate wox in any screen of multi-screen, this program will open in the current screen?
> Can this feature be added

I just tried this now, multiscreen seems to work fine. Was using 1.3.524.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
