### ISSUE TITLE
Wox在睡眠唤醒后崩溃

### ISSUE THREAD

**Issue by BenjaminDbb** [Wox-launcher/Wox#1930]
你好，我在使用过程中发现，每次笔记本睡眠唤醒后，Wox就会崩溃掉。
不知道是否近期更新可以解决？

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
