### ISSUE TITLE
I can't use it.

### ISSUE THREAD

**Issue by huang207** [Wox-launcher/Wox#1931]
[2018-03-09.txt](https://github.com/Wox-launcher/Wox/files/1797103/2018-03-09.txt)

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by jhdxr** [comment]
`Wox.Plugin.Macros`
 this plugin needs to be updated. plz inform plugin author about this issue.

I'm closing this ticket since it's not a issue about Wox core
