### ISSUE TITLE
Win + R  Crash Wox

### ISSUE THREAD

**Issue by jrt324** [Wox-launcher/Wox#1933]
### Are you submitting a bug report?

windows 10  shortcut win + R  will still crash work

### Steps to reproduce

1. install and run wox
2.press shortcut key: Win +R 
3.wox crash 

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by oneces** [comment]
win+r屏幕有竖线
![QQ图片20190314100605](https://user-images.githubusercontent.com/17893284/54326386-3bb44800-4641-11e9-9ef5-fc37509a7a3f.png

**Comment by Lucas-Fan** [comment]
这个问题现在还存在啊，没有解决这个bug

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
