### ISSUE TITLE
Wox version: 1.3.183

### ISSUE THREAD

**Issue by Sigri44** [Wox-launcher/Wox#1934]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 03/10/2018 19:45:40
Exception:
Wox.Plugin.Program
System.NullReferenceException
La référence d'objet n'est pas définie à une instance d'un objet.
   à Wox.Plugin.Program.Main.DefaultProgramSources() dans C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:ligne 136
   à Wox.Plugin.Program.Main.IndexPrograms() dans C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:ligne 102
   à Wox.Plugin.Program.Main.Init(PluginInitContext context) dans C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:ligne 94
   à Wox.Infrastructure.Stopwatch.Normal(String name, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 27
   à Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) dans C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:ligne 96
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by jhdxr** [comment]
plz try the latest version form release page
