### ISSUE TITLE
search will be selected when triggered by new hotkey that first added.

### ISSUE THREAD

**Issue by elitezhe** [Wox-launcher/Wox#194]
比如我自定义 alt + y 呼出wox, 自定义关键词为yd(有道词典), 结果我按alt + y, yd是被选中的.

这样,我就不得不再按一下→ 右箭头,才能输入单次.

这样操作的话 还不如直接 alt+空格  然后输入"yd 单词" 方便了.
希望改进为不是默认选中的.

**Comment by qianlifeng** [comment]
这个问题好像只会出现在你刚刚新加的快捷键上。你试试看重新启动wox存不存在这个问题了

**Comment by elitezhe** [comment]
果然..重启之后没有问题了~@qianlifeng

**Comment by qianlifeng** [comment]
恩，不过这还是个Bug。理想情况下，新添加的快捷键也不应该有问题才对。

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue
