### ISSUE TITLE
Wox crashes on startup, event viewer error attached

### ISSUE THREAD

**Issue by nakulbende** [Wox-launcher/Wox#1942]
Hello, 

When I click on Wox, it starts, and then immediately crashes. Nothing happens on Alt + Space, except if its a fresh start of my computer, in which case the Wox window appears, and crashes within a second. 

I am using the version 1.3.524, I am on Windows 10. Here is the crash report from event viewer:

Faulting application name: Wox.exe, version: 1.3.524.0, time stamp: 0x5a91ace4
Faulting module name: d3d9.dll, version: 10.0.16299.98, time stamp: 0xbc4a6017
Exception code: 0xc0000409
Fault offset: 0x0000000000043577
Faulting process id: 0x2204
Faulting application start time: 0x01d3bb12a1da0ed7
Faulting application path: C:\Users\Nakul Bende\AppData\Local\Wox\app-1.3.524\Wox.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 2b24b60a-4040-4268-8cd7-5960d7056615
Faulting package full name: 
Faulting package-relative application ID: 

It is blaming the directX registry? Thinking that a windows upgrade can repair it, I actually reinstalled the system and still the issue persists. Any thoughts?

**Comment by fromage9747** [comment]
@nakulbende I am experiencing the very same issue. 

There is also a .Net Framework error occurring.  

![image](https://user-images.githubusercontent.com/23147783/64838827-1c619c00-d61f-11e9-8b2b-1b5435d0d0cf.png)

![image](https://user-images.githubusercontent.com/23147783/64838838-28e5f480-d61f-11e9-84f0-5c3fa144ef7c.png)

It's worrying that this issue has been open since 2018 with no replies.

**Comment by wagnergerald** [comment]
Same here:
Name der fehlerhaften Anwendung: Wox.exe, Version: 1.3.524.0, Zeitstempel: 0x5a91ace4
Name des fehlerhaften Moduls: d3d9.dll, Version: 10.0.18362.329, Zeitstempel: 0x1ac9a115
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000000ac44e
ID des fehlerhaften Prozesses: 0x1340
Startzeit der fehlerhaften Anwendung: 0x01d571734ea1fcef
Pfad der fehlerhaften Anwendung: C:\Users\Gerald\AppData\Local\Wox\app-1.3.524\Wox.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\d3d9.dll
Berichtskennung: 39ca231f-7960-4189-b0fe-7c7d0f0e1acb
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by fromage9747** [comment]
@bao-qian Yahoo!  Confirmed fixed.  now I no longer have to use listary.  Thank you!
