### ISSUE TITLE
Can you provider a zipped executable file in release page? 

### ISSUE THREAD

**Issue by gdipkf1986** [Wox-launcher/Wox#1947]
hi Sorry but can you provide a zipped exe file on release page? 

Since the company policy actually we have only allow to download files from certain website (yes! thanks god github is in the whitelist), but .exe is banded.  :( 

I'm sure im not the only person have this issue.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
new version also has portable version.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
