### ISSUE TITLE
I'm willing to help with Spanish language translation

### ISSUE THREAD

**Issue by ArielBailon** [Wox-launcher/Wox#1949]
I don't know if this is the best place to put this(sorry if its not) but im willing to help with the spanish translation if needed, just let me know what i can do, i do know enough english and have some experience on translating from eng to spanish, im a native spanish speaker so, just wanted to point out this, great work on wox so far. thanks.

**Comment by jhdxr** [comment]
thanks for your interest. there is a folder called `Languages` inside Wox main program and each plugins, e.g.

https://github.com/Wox-launcher/Wox/tree/master/Wox/Languages

https://github.com/Wox-launcher/Wox/tree/master/Plugins/Wox.Plugin.Program/Languages

besides those xml files, you also need to update the `AvailableLanguages` [here](https://github.com/Wox-launcher/Wox/blob/master/Wox.Core/Resource/AvailableLanguages.cs)


hope these tips helpful.

**Comment by bao-qian** [comment]
close due to no further activity.
