### ISSUE TITLE
Wox plugin

### ISSUE THREAD

**Issue by woxhelp** [Wox-launcher/Wox#195]
I'm not sure how to install plugins for Wox. I downloaded the plugin but neither method works: tried using "wpm install" in wox and python; and tried drag dropping the plugin into wox - neither worked.

**Comment by qianlifeng** [comment]
Could you open the `log.txt` in your wox folder and see if any errors logged? When you drag dropping the plugin into Wox, is there any windows popup?

**Comment by guanpu** [comment]
what do you mean by "drag & drop to Wox"? drag the <em>downloaded *.wox file</em> to the <em>folder</em> where wox.exe located, or to the <em>setting interface</em> of the programe or to the main <em>input box</em>? None of these will work in win7 64bit.

**Comment by qianlifeng** [comment]
I mean drop the *.wox to the main input box of wox.

**Comment by guanpu** [comment]
great,it's working. Maybe this operation is not so friendly with the 'hide when lose focus' setting,but anyway,it works. Thx for your remarkable job.
