### ISSUE TITLE
Calculator does parse 64 integers greater than 2^31 - 1

### ISSUE THREAD

**Issue by huwcbjones** [Wox-launcher/Wox#1950]
### Are you submitting a bug report?

yes

### Steps to reproduce

1. Enter int max (2147483648) with calculator enabled, output is -2147483648

### Wox Error Window text
No error text was generated...

### Detailed logs

[2018-03-25.txt](https://github.com/Wox-launcher/Wox/files/1845768/2018-03-25.txt)

### Screenshots (optional)
Below shows the parsing error 
![image](https://user-images.githubusercontent.com/5251487/37879637-f4bbf45e-3073-11e8-83da-f3c49af8b1ac.png)

Here it shows that the actual calculation is not affected, only parsing the initial arguments.
![image](https://user-images.githubusercontent.com/5251487/37879693-9bf36d74-3074-11e8-9190-c7854687344d.png)

**Comment by huwcbjones** [comment]
After delving into the code, I believe the issue lies within `Mages.Core`

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
