### ISSUE TITLE
2225496293@qq.com

### ISSUE THREAD

**Issue by LOSTZHOU** [Wox-launcher/Wox#1953]
[2018-03-29.txt](https://github.com/Wox-launcher/Wox/files/1858799/2018-03-29.txt)

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by jhdxr** [comment]
请尝试最新版 https://github.com/Wox-launcher/Wox/releases

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
