### ISSUE TITLE
can't set as topmost querey

### ISSUE THREAD

**Issue by CookieSalesman** [Wox-launcher/Wox#1956]
### Steps to reproduce

I do not know how Github works or where to even ask this since this appears hyper-complex, however the issue is simple and I can't find a solution:

Setting as topmost in query simply doesn't work. It doesn't do anything; nothing happens.

**Comment by sayashr** [comment]
I have the same problem. Any solve?

**Comment by sayashr** [comment]
Solved! Installed [Python](https://www.python.org/downloads/release/python-371/) on my computer, and now Topmost works 👍

**Comment by CookieSalesman** [comment]
WOW thanks. Didn't expect that to fix.

**Comment by Sclamy** [comment]
More info? Topmost hasn't ever worked for me, and I have Python 3.7.2

**Comment by MarshallGitHub** [comment]
For some reason, works now.

Can't remember what I did but it may have had to do with a reinstall.

**Comment by CookieSalesman** [comment]
> More info? Topmost hasn't ever worked for me, and I have Python 3.7.2

Unfortunately that's all I had to do. Perhaps you're missing something else?
Have you tried reinstalls?

**Comment by Sclamy** [comment]
Yep, several times, and had wox on three different computers in the last year

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by CookieSalesman** [comment]
As sayashr said I believe I was able to resolve this issue by installing Python, but can't recall.

Thanks.
