### ISSUE TITLE
用wox查找图片，然后该图片会被wox一直占用

### ISSUE THREAD

**Issue by Mikluv** [Wox-launcher/Wox#1957]
### Are you submitting a bug report?

(write your answer here)
yes，用wox查看图片，图标，并打开文件夹，之后该图标会被wox一直占用，剪切删除都不可用。只有把wox关闭，该文件才能正常操作。但是再打开wox后，这个占用依旧存在。

### Steps to reproduce

1.用wox查找图片并打开
2.对该图片进行删除或者剪切操作
3.都会提示该图片被wox占用

### Wox Error Window text

(paste here)
删除文件时，会提示“操作无法完成，因为文件已在Wox中打开”

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

![image](https://user-images.githubusercontent.com/32835511/38123088-cf1100b4-340b-11e8-8d6a-a0500780b5c5.png)

**Comment by jhdxr** [comment]
https://ci.appveyor.com/api/buildjobs/wyjvukb78fltqap7/artifacts/Output%2FPackages%2FWox-1.3.527.exe

这个版本是否解决了你的问题？
（无论是否解决，麻烦在测试后回报。多谢

**Comment by Mikluv** [comment]
版本：1.3.527  测试了一会~~ 没有发现上面的问题了~ 谢谢

**Comment by huanlingex** [comment]
你好，我也有这个问题，但是这个版本下载不了了

**Comment by jhdxr** [comment]
@huanlingex  请使用最新的pre-relase 1.3.578 https://github.com/Wox-launcher/Wox/releases
