### ISSUE TITLE
Could I use wox to open a .lnk document?

### ISSUE THREAD

**Issue by Effyfana** [Wox-launcher/Wox#1962]
WOX could not open .lnk files any more. When I click on a .lnk search result, a notification pops out from the right bottom of the screen, saying "plugin: everything can't open this file" or "plugin: program can't start ………program path". I have tried to reinstall wox or change settings of the program plugin, but these procedures didn't seem to fix this problem.
Log file has been attached below.
[2018-04-02.txt](https://github.com/Wox-launcher/Wox/files/1868299/2018-04-02.txt)

**Comment by guanxiux** [comment]
I met with the same issue before, and fixed it somehow. You could try my way out and see if it could help. First, **run cmd.exe** and **start whichever .lnk file that is funtionable when double clicked**. If it fails to be opened out of **no associations to execute it**, then perhaps your are in just the same case as I was, **registries conflicting**. Simply **run some cleaner program** (like 360 I used. Not the free CCleaner, I always used it before but it never solved that problem.) and **clean up unnecessary registries** , and you issue could probably be solved.

**Comment by Effyfana** [comment]
@guanxiux  Recently I found this issue was fixed automatically, so I don't need to  use any cleaner program any more. But still thank you for your advice! I am confused why this issue could be fixed automatically since I can't recall any operation I did that might work. Maybe the auto-update of win10 works.

**Comment by xor-gate** [comment]
I have the same but with a .bat file running under wox v1.3.524.20180714 and everything v1.4.1935.20190602

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
