### ISSUE TITLE
wox got an error

### ISSUE THREAD

**Issue by himelee** [Wox-launcher/Wox#1963]
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2)
   在 Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 119
   在 Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 22
   在 Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 85
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2018-04-03.txt](https://github.com/Wox-launcher/Wox/files/1868809/2018-04-03.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
