### ISSUE TITLE
Search bar is not automatically active after keyboard shortcut

### ISSUE THREAD

**Issue by bananapicker** [Wox-launcher/Wox#1966]
After pressing my keyboard shortcut to bring up the wox search bar, it is not already selected (ie.. if I try to type immediately after the keyboard shortcut nothing happens).  What happens now is after the keyboard shortcut I have to move my mouse pointer to select the search bar then I can type my search.  

This REALLY slows down my search time as I have to move my hands from the keyboard to my mouse to select the search bar then back to the keyboard to type.

If there is a setting I am missing, I have not found it as I tried selecting and tested each option and none would have the searchbar active after the keyboard shortcut automatically.

**Comment by vince-p** [comment]
I have the same issue. Is there anything we can do to help debug this?

**Comment by roose** [comment]
Please try change Wox hotkey from `alt+space` to `ctrl+space`(or other) does the error still exist?

**Comment by vince-p** [comment]
I have tried several hotkeys but it does not help.
Sometimes the wox bar is active (ie keys i type go directly into the wox search), other times it is inactive.
One thing I have noticed is that it seems like if there is an active cursor in another app then the wox bar will definitely not be active when triggered.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
