### ISSUE TITLE
命令行替换win+R导致wox崩溃

### ISSUE THREAD

**Issue by tigerhuhuhu** [Wox-launcher/Wox#1968]
### Are you submitting a bug report?

YES. 

### Steps to reproduce

1. 安装Wox-1.3.524.exe/ Everything-1.3.4.686.x64-Setup.exe / python3.6.0.exe 
2. 确认.net 版本为4.7.1
3. 尝试命令行替换功能“win+R”，wox崩溃，alt+space无法调用，仅显示一条文本框输入竖线。只能手动退出wox后重新运行。

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

如图所示wox崩溃只剩下一条文本输入框

![image](https://user-images.githubusercontent.com/14320186/38456870-bf5a36de-3abb-11e8-8e8a-48091ebbc209.png)

手动勾选掉“替换win+R”选项后可以正常使用

![image](https://user-images.githubusercontent.com/14320186/38456723-7aee0972-3aba-11e8-947a-d7b88c51f405.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
