### ISSUE TITLE
Win7x64运行1.01版本崩溃

### ISSUE THREAD

**Issue by ifdog** [Wox-launcher/Wox#197]
管理员运行了也不行呢
## Exception

```
Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException: 此单实例应用程序无法连接到原始实例。
   Source: Microsoft.VisualBasic
   TargetAssembly: Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
   TargetModule: Microsoft.VisualBasic.DLL
   TargetSite: Void Run(System.String[])
   在 Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   在 Wox.EntryPoint.Main(String[] args) 位置 c:\Projects\Wox\Wox\App.xaml.cs:行号 27

```
## Environment
- Command Line: "C:\Program Files (x86)\Wox\Wox.exe" 
- Exception Handle: System.AppDomain.UnhandledException
- Timestamp: 2014-10-21T09:57:52.0321876+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
- CLR Version: 2.0.50727.5485
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.5420 SP2
  - v3.0 3.0.30729.5420 SP2
  - v3.5 3.5.30729.5420 SP1
  - v4 Client 4.5.50938
  - v4 Full 4.5.50938
  - v4.0 Client 4.0.0.0
  - 4.5.1 installed on Windows 8, Windows 7 SP1, or Windows Vista SP2
## Assemblies - Wox.exe
- Wox, Version=1.0.0.231, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\Wox.exe)
- Wox.Infrastructure, Version=1.0.0.231, Culture=neutral, PublicKeyToken=null (C:\Program Files (x86)\Wox\Wox.Infrastructure.dll)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\Microsoft.VisualBasic\8.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- Microsoft.VisualBasic.resources, Version=8.0.0.0, Culture=zh-CHS, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\Microsoft.VisualBasic.resources\8.0.0.0_zh-CHS_b03f5f7f11d50a3a\Microsoft.VisualBasic.resources.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- mscorlib.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
## Modules - Wox
- C:\Program Files (x86)\Wox\Wox.exe (Wox, 1.0.0.231, Wox, 1.0.0.231, ), 0x00000000003C0000
- C:\windows\SYSTEM32\ntdll.dll (NT 层 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000077BA0000
- C:\windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 4.0.40305.0 (Main.040305-0000), Microsoft® .NET Framework, 4.0.40305.0, Microsoft Corporation), 0x000007FEF5610000
- C:\windows\system32\KERNEL32.dll (Windows NT 基本 API 客户端 DLL, 6.1.7601.18015 (win7sp1_gdr.121129-1432), Microsoft® Windows® Operating System, 6.1.7601.18015, Microsoft Corporation), 0x0000000077A80000
- C:\windows\system32\KERNELBASE.dll (Windows NT 基本 API 客户端 DLL, 6.1.7601.18015 (win7sp1_gdr.121129-1432), Microsoft® Windows® Operating System, 6.1.7601.18015, Microsoft Corporation), 0x000007FEFDBD0000
- C:\windows\system32\ADVAPI32.dll (高级 Windows 32 基本 API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE9D0000
- C:\windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.7601.17744 (win7sp1_gdr.111215-1535), Microsoft® Windows® Operating System, 7.0.7601.17744, Microsoft Corporation), 0x000007FEFE730000
- C:\windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE8F0000
- C:\windows\system32\RPCRT4.dll (远程过程调用运行时, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFEFC0000
- C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.18408 built by: FX451RTMGREL, Microsoft® .NET Framework, 4.0.30319.18408, Microsoft Corporation), 0x000007FEF5570000
- C:\windows\system32\SHLWAPI.dll (外壳简易实用工具库, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE660000
- C:\windows\system32\GDI32.dll (GDI Client DLL, 6.1.7601.18577 (win7sp1_gdr.140822-1508), Microsoft® Windows® Operating System, 6.1.7601.18577, Microsoft Corporation), 0x000007FEFE5F0000
- C:\windows\system32\USER32.dll (多用户 Windows 用户 API 客户端 DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x0000000077980000
- C:\windows\system32\LPK.dll (Language Pack, 6.1.7601.18177 (win7sp1_gdr.130605-1534), Microsoft® Windows® Operating System, 6.1.7601.18177, Microsoft Corporation), 0x000007FEFDE80000
- C:\windows\system32\USP10.dll (Uniscribe Unicode script processor, 1.0626.7601.18454 (win7sp1_gdr.140424-1533), Microsoft(R) Uniscribe Unicode script processor, 1.0626.7601.18454, Microsoft Corporation), 0x000007FEFED70000
- C:\windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFFE80000
- C:\windows\system32\MSCTF.dll (MSCTF 服务器 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDD70000
- C:\windows\system32\nvinitx.dll (NVIDIA shim initialization dll, Version 344.11 , 9.18.13.4411, NVIDIA D3D shim drivers, 9.18.13.4411, NVIDIA Corporation), 0x000007FEFD8E0000
- C:\Program Files\NVIDIA Corporation\CoProcManager\detoured.dll (, , , , ), 0x000000000F000000
- C:\Program Files\NVIDIA Corporation\CoProcManager\nvd3d9wrapx.dll (NVIDIA d3d9wrap dll, Version 344.11 , 9.18.13.4411, NVIDIA D3D shim drivers, 9.18.13.4411, NVIDIA Corporation), 0x000007FEFA510000
- C:\windows\system32\SETUPAPI.dll (Windows 安装程序 API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFEB90000
- C:\windows\system32\CFGMGR32.dll (Configuration Manager DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFDB80000
- C:\windows\system32\OLEAUT32.dll (, 6.1.7601.17676, , 6.1.7601.17676, Microsoft Corporation), 0x000007FEFEAB0000
- C:\windows\system32\ole32.dll (用于 Windows 的 Microsoft OLE, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDE90000
- C:\windows\system32\DEVOBJ.dll (Device Information Set DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFDC40000
- C:\Program Files\NVIDIA Corporation\CoProcManager\nvdxgiwrapx.dll (NVIDIA dxgiwrap dll, Version 344.11 , 9.18.13.4411, NVIDIA D3D shim drivers, 9.18.13.4411, NVIDIA Corporation), 0x000007FEFA440000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF2960000
- C:\windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.6229_none_88dcc0bf2fb1b808\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.6229, Microsoft® Visual Studio® 2005, 8.00.50727.6229, Microsoft Corporation), 0x0000000072290000
- C:\windows\system32\shell32.dll (Windows 外壳公用 DLL, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFF0F0000
- C:\windows\system32\profapi.dll (User Profile Basic API, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD9B0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\mscorlib\c3beeeb6432f004b419859ea007087f1\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF1A60000
- C:\windows\system32\CRYPTBASE.dll (Base cryptographic API DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD7D0000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.5467 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5467, Microsoft Corporation), 0x000007FEF18D0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System\b337dab72a2755e40ca63d298f0967ab\System.ni.dll (.NET Framework, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEF0D90000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\e18bc53d06e2706d572028d884947d71\System.Drawing.ni.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEF0B00000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\8697c535307bc60a1bb2eaa725611736\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEEFA60000
- C:\windows\assembly\NativeImages_v2.0.50727_64\Microsoft.VisualBas#\90cbb3ef06c528ab51de796fd312d33e\Microsoft.VisualBasic.ni.dll (Visual Basic Runtime Library, 8.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® Visual Studio® 2005, 8.0.50727.5483, Microsoft Corporation), 0x000007FEDE230000
- C:\windows\system32\CRYPTSP.dll (Cryptographic Service Provider API, 6.1.7601.18526 (win7sp1_gdr.140706-1506), Microsoft® Windows® Operating System, 6.1.7601.18526, Microsoft Corporation), 0x000007FEFD170000
- C:\windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFCE70000
- C:\windows\system32\RpcRtRemote.dll (Remote RPC Extension, 6.1.7601.17514 (win7sp1_rtm.101119-1850), Microsoft® Windows® Operating System, 6.1.7601.17514, Microsoft Corporation), 0x000007FEFD8C0000
- C:\Program Files (x86)\Wox\Wox.Infrastructure.dll (Wox.Infrastructure, 1.0.0.231, Wox.Infrastructure, 1.0.0.231, ), 0x0000000063740000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Remo#\5397b30ed76b2cc90afba655795cecec\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEE4070000
- C:\windows\system32\ws2_32.dll (Windows Socket 2.0 32 位 DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFE6E0000
- C:\windows\system32\NSI.dll (NSI User-mode interface DLL, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFEFB0000
- C:\windows\system32\PrxerDrv.dll (Proxifier Winsock Layered Service Provider x64, 3, 21, 1, 0, Proxifier Standard Edition, 3, 21, 1, 0, Initex), 0x000007FEFCB00000
- C:\windows\system32\mswsock.dll (Microsoft Windows Sockets 2.0 服务提供程序, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD110000
- C:\windows\System32\wshtcpip.dll (Winsock2 帮助程序 DLL (TL/IPv4), 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFCAE0000
- C:\windows\System32\wship6.dll (Winsock2 帮助程序 DLL (TL/IPv6), 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD100000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\83d22abe564832841371449f563ad507\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5483, Microsoft Corporation), 0x000007FEED650000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Xml\5ce7538caef24ef64d79b600b1ad4c23\System.Xml.ni.dll (.NET Framework, 2.0.50727.5485 (Win7SP1GDR.050727-5400), Microsoft® .NET Framework, 2.0.50727.5485, Microsoft Corporation), 0x000007FEEDC90000
- C:\windows\system32\security.dll (Security Support Provider Interface, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000061E30000
- C:\windows\system32\SECUR32.DLL (Security Support Provider Interface, 6.1.7601.18443 (win7sp1_gdr.140411-1533), Microsoft® Windows® Operating System, 6.1.7601.18443, Microsoft Corporation), 0x000007FEFD570000
- C:\windows\system32\SSPICLI.DLL (Security Support Provider Interface, 6.1.7601.18443 (win7sp1_gdr.140411-1533), Microsoft® Windows® Operating System, 6.1.7601.18443, Microsoft Corporation), 0x000007FEFD740000
- C:\windows\system32\credssp.dll (Credential Delegation Security Package, 6.1.7601.18540 (win7sp1_gdr.140716-1508), Microsoft® Windows® Operating System, 6.1.7601.18540, Microsoft Corporation), 0x000007FEFCD40000
- C:\windows\system32\msv1_0.DLL (Microsoft Authentication Package v1.0, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD0A0000
- C:\windows\system32\cryptdll.dll (Cryptography Manager, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x000007FEFD420000
- C:\windows\assembly\GAC_MSIL\Microsoft.VisualBasic.resources\8.0.0.0_zh-CHS_b03f5f7f11d50a3a\Microsoft.VisualBasic.resources.dll (Visual Basic 运行库, 8.0.50727.5420 (Win7SP1.050727-5400), Microsoft (R) Visual Studio (R) 2005, 8.0.50727.5420, Microsoft Corporation), 0x0000000063B90000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Core\6c3e7d6992b9434ee9f9118a8ebaa9fe\System.Core.ni.dll (.NET Framework, 3.5.30729.5420 built by: Win7SP1, Microsoft® .NET Framework, 3.5.30729.5420, Microsoft Corporation), 0x000007FEDCCA0000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.5483 (Win7SP1GDR.050727-5400), Microsoft® Visual Studio® 2005, 8.0.50727.5483, Microsoft Corporation), 0x000007FEE82C0000
- C:\windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_zh-CHS_b77a5c561934e089\mscorlib.resources.dll (Microsoft 公共语言运行时类库, 2.0.50727.5420 (Win7SP1.050727-5400), Microsoft(R) .NET Framework, 2.0.50727.5420, Microsoft Corporation), 0x000000006D160000
- C:\windows\system32\psapi.dll (Process Status Helper, 6.1.7600.16385 (win7_rtm.090713-1255), Microsoft® Windows® Operating System, 6.1.7600.16385, Microsoft Corporation), 0x0000000077D60000
## Threads - 8
- 15064, Running Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000000000000
- 2484, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 4760, Wait Highest, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 15256, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 2152, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 14816, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 652, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520
- 9496, Wait Normal, Started: 2014/10/21 9:57:49, StartAddress: 0x0000000077BCC520

**Comment by qianlifeng** [comment]
在 c8273bf665d8ec569308bde16e8f7e89a7b6fb5b 中做了修复，你可以试试看这里的最新版本能不能运行。[https://ci.appveyor.com/project/qianlifeng/wox/build/job/yemlj0ab0i8aac3f/artifacts](https://ci.appveyor.com/project/qianlifeng/wox/build/job/yemlj0ab0i8aac3f/artifacts)
