### ISSUE TITLE
Wox crashed When OS startup

### ISSUE THREAD

**Issue by mooncircle** [Wox-launcher/Wox#1970]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.Win10 updated to 15063.994
2.This problem happened when OS startup.
3.

### Wox Error Window text

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 04/10/2018 08:58:51
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\Administrator\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 37
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-04-10.txt](https://github.com/Wox-launcher/Wox/files/1892444/2018-04-10.txt)

### Screenshots (optional)

![wox_20180410091020](https://user-images.githubusercontent.com/5237833/38530805-2d874040-3c9f-11e8-8e1b-f9ddbf9695b0.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
