### ISSUE TITLE
Microsoft Office Applications not found

### ISSUE THREAD

**Issue by TalkingQuickly** [Wox-launcher/Wox#1971]
### Are you submitting a bug report?

Yes

### Steps to reproduce

Using a standard install of Wox + the Everything plugin, the majority of applications work perfectly (incredible piece of software!) but none of the applications in the office suite are found. E.g. typing in "Word" "Excel" or "Powerpoint" doesn't detect the corresponding applications. So far I can't replicate the problem with any other applications and can't find any reference to similar problems anywhere else in the issue tracker.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
