### ISSUE TITLE
我怎么将我想要的常用文件夹放到前面的位置，

### ISSUE THREAD

**Issue by doneself** [Wox-launcher/Wox#1974]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)
每次我输入我想要的文件夹名，文件夹都排到底部了。

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

use everything syntax `folder: folder Name`

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
