### ISSUE TITLE
Wox突然不识别拼音，设置里重新索引无限循环

### ISSUE THREAD

**Issue by Dandjinh** [Wox-launcher/Wox#1975]
### Are you submitting a bug report?

(write your answer here)
Yes

### Steps to reproduce

1. Wox里输入Settings打开设置
2. 设置 -> 插件 -> 程序 -> 重新索引
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)
[2018-04-12.txt](https://github.com/Wox-launcher/Wox/files/1901098/2018-04-12.txt)

### Screenshots (optional)

(drop your screenshot here)
![error](https://user-images.githubusercontent.com/23111507/38652835-4f4cce42-3e3a-11e8-8fc7-664bc7191b99.gif)

**Comment by Dandjinh** [comment]
检查过了是因为之前操作不当导致开始菜单里有个文件夹错误--"目录名称无效"

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
