### ISSUE TITLE
The wox process does not end when I exit the program from the taskbar

### ISSUE THREAD

**Issue by Peeeng** [Wox-launcher/Wox#1984]
As the title.
![woxissue](https://user-images.githubusercontent.com/33120546/38787843-1396c8d6-4163-11e8-9111-293330c56c16.png)

My system is win10 Enterprise。
Thank you for solving the problem.

**Comment by shawlq** [comment]
that happen to me, either.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
