### ISSUE TITLE
Can't start shortcut link

### ISSUE THREAD

**Issue by rumingruyue** [Wox-launcher/Wox#1988]
When I use the latest tool , I cannot start the shortcut links.

![popo 2018417111815](https://user-images.githubusercontent.com/38344148/38846926-8f80def4-4231-11e8-8af3-9d9c47d549f0.png)
![2018-04-17_11-17-50](https://user-images.githubusercontent.com/38344148/38846929-916b00fa-4231-11e8-92dd-75cd99c664e9.png)

**Comment by michaelllh** [comment]
I have the same problem

**Comment by wll8** [comment]
@rumingruyue @michaelllh 
我通过修改注册表解决问题。
I solved the problem by modifying the registry.
`reg add "HKCR\lnkfile" /v IsShortcut /f && taskkill /f /im explorer.exe && explorer.exe`

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
