### ISSUE TITLE
Disable Win+R from launching Wox

### ISSUE THREAD

**Issue by elig0n** [Wox-launcher/Wox#1990]
Although it is not stated in the settings win key + r which usually serves for Run invokes Wox.
How can I disable it ? 
Can I make it enabled but disable win+r run dialog (without external program i.e. Autohotkey) ?

**Comment by kleinfreund** [comment]
It’s quite hidden in the settings.

Open *Wox’ Settings* > Go to *Plugin* > *Shell* > Uncheck *Replace Win+R*

This should absolutely not be a default setting.

**Comment by nowox** [comment]
Yes quite hidden in the settings. It would be nice to have it somewhere else :)

**Comment by xcl-net** [comment]
![TIM截图20191226121030](https://user-images.githubusercontent.com/15728845/71457412-ccc36c80-27d8-11ea-9642-eedafeecf932.png)

**Comment by bao-qian** [comment]
close due to question seems resolved.
