### ISSUE TITLE
Wox 出错，在我把有道插件安装时

### ISSUE THREAD

**Issue by Yasin27878** [Wox-launcher/Wox#1991]
### Are you submitting a bug report?

(write your answer here)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.17133.0
Date: 04/18/2018 17:22:02
Exception:
System
System.UriFormatException
无效的 URI: 此 URI 为空。
   在 System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   在 Wox.Core.Resource.Theme.GetResourceDictionary() 位置 C:\projects\wox\Wox.Core\Resource\Theme.cs:行号 70
   在 Wox.Core.Resource.ResourceMerger.UpdateResource[T](T t) 位置 C:\projects\wox\Wox.Core\Resource\ResourceMerger.cs:行号 31
   在 Wox.Core.Resource.Theme.ChangeTheme(String themeName) 位置 C:\projects\wox\Wox.Core\Resource\Theme.cs:行号 58
   在 Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 53
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
