### ISSUE TITLE
how to upload wox plugin?

### ISSUE THREAD

**Issue by StephinChou** [Wox-launcher/Wox#1992]
I wrote a plugin by python and I want to upload it up to wox plugin repository.
but i got an error 'wox plugin should end with .wox'

I have no idea how to do that.
Just want to know how to turn my python file to the plugin ends with .wox

**Comment by ZhihaoJun** [comment]
Same error here. I wrote a C# plugin. Tried to compress all plugin files then upload. It failed too.

**Comment by StephinChou** [comment]
Just pack your all files and edit the suffix of the packed-file to '.wox'  then upload it.
