### ISSUE TITLE
Can't set anything as a topmost query

### ISSUE THREAD

**Issue by CookieSalesman** [Wox-launcher/Wox#1994]
Title, I can't set anything as a topmost query... Nothing happens.

**Comment by Darthagnon** [comment]
Same seems to occur here; setting as topmost query has no discernible effect.

**Comment by stavfx** [comment]
+1.
I did however notice that if I disable the Program plugin, it starts behaving better. However that kind of ruins the whole point

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
