### ISSUE TITLE
请求增加新功能

### ISSUE THREAD

**Issue by GoingTime** [Wox-launcher/Wox#1995]
希望支持导出软件和（支持自定义配置的）插件的配置信息

**Comment by Moyf** [comment]
同请求 _(:з」∠)_
现在如果重装的话整个软件都得重新配置一遍……有可能做成 Portable 吗？

**Comment by ikkz** [comment]
插件[Wox.Plugin.PluginBackup](https://github.com/cildhdi/Wox.Plugin.PluginBackup)已开发完毕，具体使用可以查看链接。

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
you can copy/backup settings in %APPDATA\Wox folder, new version also has portable mode,
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
