### ISSUE TITLE
Wox will hijack win+R without asking me

### ISSUE THREAD

**Issue by HarborZeng** [Wox-launcher/Wox#1998]
### Are you submitting a bug report?
 
(write your answer here)
Yes

### Steps to reproduce

1. when press win+R
2. got wox showed up rather than window run
3. yeah, hot key are not set to win+R

### Wox Error Window text

(paste here)
no error

### Detailed logs

(drop your log file here)
no log
### Screenshots (optional)

(drop your screenshot here)
no screenshot

**Comment by gissehel** [comment]
Try this:
* Start wox
* Open wox settings (from menu on tray icon, or wox command "settings")
* Go to the "Plugin" tab
* Search for the "Shell" plugin
* Select the "Shell" plugin
* Uncheck "Replace Win+R"

Does it solve your problem ?

**Comment by Darthagnon** [comment]
Hopefully, eventually, Wox will be updated to have this setting disabled by default, as it should be. No program should hijack system shortcuts by default without telling the user explicitly.

**Comment by skjerns** [comment]
> Hopefully, eventually, Wox will be updated to have this setting disabled by default, as it should be. No program should hijack system shortcuts by default without telling the user explicitly.

this would be great indeed.
