### ISSUE TITLE
Add Everything Plugin

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#2]

**Comment by orzFly** [comment]
f9ff9af0 has finished Everything protocol. However this plugin still needs some tweaks.

**Comment by qianlifeng** [comment]
Seems everything plugin didn't support wildcard like *.js

**Comment by orzFly** [comment]
Regular Expression is supported. BTW, there is some options for RegEx.

> private static extern void Everything_SetRegex(bool bEnable);

I think we can translate wildcard into RegEx such as replacing \* into .*, ?
into . and leaving [a-z] as is.

**Comment by cxfksword** [comment]
i think the normal mode is more convenience then regex mode...

**Comment by cxfksword** [comment]
Can change default to normal mode? And when user input a `ev @` begin, then change to regex mode

**Comment by qianlifeng** [comment]
I also think the normal mode will be more convenience.

**Comment by orzFly** [comment]
Since icons has been added by @cxfksword in #59 #60, this can be closed now.
