### ISSUE TITLE
Add workflow hotkey

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#20]
Maybe we can provide a setting panel for users to add custom workflow hotkey. e.g. there is a workflow whose action keyword is `fy`. Users can set a hotkey for this keyword, like <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>. After user pressed <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>, WinAlfred will auto show with query `fy`.

**Comment by qianlifeng** [comment]
This feature is similar with what we have done for CMD workflow (triggered by <kbd>Win</kbd> + <kbd>R</kbd>). But will be a more general function. And after this feature is done. CMD hotkey should be added through this common function.

**Comment by orzFly** [comment]
The workflow should be able to decid what to fill in the query box.
But by the way maybe a workflow can have multiple functions to be triggered
by hotkey.

So I think there should be only one feature: allowing workflows to have
functions triggered by hotkey.
Then the workflow can show a query box with some prefixes filled or invoke
some command.

— orzFly / Yeechan Lu

**Comment by qianlifeng** [comment]
But if we do so, The behavior of workflows hotkey is difficult to unity, which may confuse uses. They have to read docs to understand what will happen after they trigger the workflow hotkey. And I think we should keep things simple. For workflow functions, there should be only one or two entrances. one is best. It will be too complicated if we provide multiple functions to be triggered by hotkey.

**Comment by orzFly** [comment]
Just have a look at some [Alfred Workflows](http://www.alfredworkflow.com/) in Mac.  It's just MacAlfred's idea. In the Alfred's idea, a workflow can have any combinations and repetitions of hotkeys and commands. 

For example:
- Douban (3 command: book, movie, music): http://lucifr.com/2013/03/14/douban-workflow-for-alfred-v2/
- Quick Open Finder (one hotkey to open Finder): http://www.alfredworkflow.com/#Quick%20Open%20Finder

**Comment by qianlifeng** [comment]
@orzFly I misunderstand your idea. I thought you mean that one action keyword should have multiple ways to be triggered. I'm ok with multiple commands. It's reasonable. 

> So I think there should be only one feature: allowing workflows to have functions triggered by hotkey.

You are right, we should let workflow decides which function will be triggered if it has multiple action keywords.

**Comment by qianlifeng** [comment]
b3e5f09c838901c780126c23b15da635f09329e9 <img src="http://ww2.sinaimg.cn/large/5d7c1fa4gw1eds7rp6sokj20rj0erjt5.jpg" />
