### ISSUE TITLE
Cross Platform Build by Mono?

### ISSUE THREAD

**Issue by edwardchanjw** [Wox-launcher/Wox#200]
Cross platform build (Mac OS x and Linux) support by using Mono?
Does't know Mono much, just a suggestion.

Thanks for good piece of software!

**Comment by orzFly** [comment]
> At this point, no group in the Mono project has plans to implement Windows Presentation Foundation APIs as part of the project.
> We do not have any plans because the project is too large and there has not been any serious interest from the community to make this effort move forward.
> &mdash; http://www.mono-project.com/docs/gui/wpf/
