### ISSUE TITLE
Win10 无法启动快捷方式( can't start any software shortcuts)

### ISSUE THREAD

**Issue by rumingruyue** [Wox-launcher/Wox#2002]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1. win10  wox version:1.3.524
2. can't start any software links
3.

### Wox Error Window text

(paste here)
`Plugin:Program
Can't start ******`

### Detailed logs

[2018-04-27.txt](https://github.com/Wox-launcher/Wox/files/1953566/2018-04-27.txt)

### Screenshots (optional)

![wox](https://user-images.githubusercontent.com/38344148/39340361-5eef8246-4a00-11e8-98f8-1729ea329b1d.png)
![screenshot 2018-04-27 09 46 29](https://user-images.githubusercontent.com/38344148/39340362-613f7ce0-4a00-11e8-80ac-65016f9ce6dd.png)

**Comment by guanxiux** [comment]
我不久前也遇到这个问题, 后来摸索着解决了, 感觉你可以参照我的方法检验一下是不是相同的情况. 运行 cmd.exe , 试着用 start 命令随便启动一个能双击启动的 .lnk 文件, 如果有弹窗说缺少关联程序不能启动这个文件, 那么你跟我之前的情况可能是一样的, 是**注册表有冲突**之类的, 用**清理软件**(注意可能不是所有清理软件都有足够的清理面, 我之前一直在用的 CCleaner 就一直没能解决问题, 为了这特意装了一回 360)**清理下注册表**就行了.
I met with the same issue before, and fixed it somehow. You could try my way out and see if it could help. First, run cmd.exe and start whichever .lnk file that is funtionable when double clicked. If it fails to be opened out of no associations to execute it, then perhaps your are in just the same case as I was, **registries conflicting**. Simply **run some cleaner program** (like 360 I used. Not the free CCleaner, I always used it before but it never solved that problem.) and **clean up unnecessary registries** , and you issue could probably be solved.

**Comment by wll8** [comment]
@rumingruyue 
我通过修改注册表解决问题。
I solved the problem by modifying the registry.
`reg add "HKCR\lnkfile" /v IsShortcut /f && taskkill /f /im explorer.exe && explorer.exe`

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
