### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by harveyqiu** [Wox-launcher/Wox#2007]
How to build locally?

“powershell.exe -NoProfile -File D:\develop\Wox\Scripts\post_build.ps1 Debug D:\develop\Wox\”

This command failed to execute.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
try new master branch, which works with vs2019
