### ISSUE TITLE
控制面板卸载某程序（Visual Assist X）后，Wox出现未处理的异常

### ISSUE THREAD

**Issue by Ji-Yuhang** [Wox-launcher/Wox#201]
![wox-](https://cloud.githubusercontent.com/assets/5045085/4787800/d365677a-5db0-11e4-92a9-bd25062c3386.png)

**Comment by Ji-Yuhang** [comment]
抱歉，我没办法拷贝文字。只能上图。

**Comment by qianlifeng** [comment]
你应该不是用的最新版，这个问题在最新版里面已经修复  

[https://github.com/qianlifeng/Wox/blob/master/Wox.Plugin.SystemPlugins/Program/ProgramSources/FileSystemProgramSource.cs#L61](https://github.com/qianlifeng/Wox/blob/master/Wox.Plugin.SystemPlugins/Program/ProgramSources/FileSystemProgramSource.cs#L61)

**Comment by qianlifeng** [comment]
https://github.com/qianlifeng/Wox/releases/tag/1.0.1 中的第三条就是修复的这个问题。
