### ISSUE TITLE
无法正常呼出

### ISSUE THREAD

**Issue by myuanz** [Wox-launcher/Wox#2011]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. 打开Wox
2. Esc关掉
3. 快捷键呼出
4. 偶尔只会出现一个竖着的长条，退出重启后恢复正常

### Wox Error Window text

None

### Detailed logs

(drop your log file here)

### Screenshots (optional)

我现在无法触发了

[2018-04-30.txt](https://github.com/Wox-launcher/Wox/files/1960474/2018-04-30.txt)

**Comment by vitalQ** [comment]
对，我也出现这个问题，每次都要退出重新打开，不好重现这个问题

**Comment by yungchow** [comment]
我也是，竖长条黑线长短不一，通常大概5cm，多次呼出可以出现10cm的黑竖线

**Comment by myuanz** [comment]
我已经好久没有触发了,今天重装了系统,又来了

**Comment by AntonyLee** [comment]
我这边触发的几率很高。重启又再回复正常，过会就又变成这样了。

![image](https://user-images.githubusercontent.com/1336185/40647777-4f5ef988-635f-11e8-9599-6d4ad00fe31b.png)

**Comment by SamuelZon258** [comment]
+1

**Comment by bao-qian** [comment]
duplicate #962 
please subscribe #962 for update
