### ISSUE TITLE
UAC窗口焦点问题和搜索结果的鼠标选择问题

### ISSUE THREAD

**Issue by brook12** [Wox-launcher/Wox#2012]
1.  UAC窗口的焦点问题。
通过WOX打开的程序如果触发了UAC，无法直接通过键盘快捷键或方向键选择“是”或“否”，因为焦点还在下层的程序上。

2. 搜索结果的选择问题。
当弹出搜索结果时，如果鼠标在搜索结果菜单弹出的范围内，即使鼠标不动，所选结果也有一定概率跳到鼠标所指的位置，结果就是必须手动调整选择，无法盲选。

**Comment by mgrddsj** [comment]
同样有第二个问题！
