### ISSUE TITLE
Slow & Everything Plugin Not Working Despite Reinstalls

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#2014]
Hey guys,
Wox is awesome.But suddenly it has become really slow and the everything plugin isn't working. Anyone know what might be interfering with it? Because I have re installed and remade the build in VS and also installed the gh file tried everything. Must be something on my computer that prevents everything from working..
Ideas welcome!

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
