### ISSUE TITLE
Caret jumping to the end of the input field after every entered character

### ISSUE THREAD

**Issue by azonin** [Wox-launcher/Wox#2015]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Invoke Wox
2. Type "123+456" and wait for the "579" to show up as the result
3. Using either cursor keys on your keyboard or mouse, set the caret before "1"
4. Enter "(" and the caret immediately jumps to the end of the line (after "6)
5. This makes editing simple equations very difficult, if you want to add parentheses or insert a multi-digit number.

### Wox Error Window text

n/a

### Detailed logs

n/a

### Screenshots (optional)

n/a

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
