### ISSUE TITLE
有幸使用这个强大的工具，请问怎么用wox切换窗口呢？比如我的Chrome已经打开了，从别的程序里怎么快递切换到已经打开的chrome里面？

### ISSUE THREAD

**Issue by Bourne-M** [Wox-launcher/Wox#2018]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by Dandjinh** [comment]
可以自己写个插件，具体思路是 

> 窗口枚举 -> 显示结果 -> 选择 -> 窗口置顶

**Comment by yyangdid** [comment]
好像这个功能已经有插件了啊，wpm install Switcheroo for Wox 
默认触发关键字是win

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
