### ISSUE TITLE
Quick Question on Post Build

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#2019]
Quick question; hoping for a quick answer :) !!!!

How to install the self-build of wox and remain that all the plugins work?

I have tried:

Copying the contents of the folders to AppData/Local/Wox and AppData/Roaming/Wox to mirror the release wox install but something seems to be missing. Possibly to do with squirrels.

I want to be able to properly contribute :)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
new version also has portable mode.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
