### ISSUE TITLE
Searching with command "g"

### ISSUE THREAD

**Issue by BoltPow3r** [Wox-launcher/Wox#2020]
### Are you submitting a bug report?

no

When using search functionality with a browser it does not open the web page directly, but instead uses google search. For example if I alt+space and then type g google.com it will search google.com using google search instead of opening google.com. I'm not sure if this was intended or not, but personally I find it more useful if searches that end with e.g.: .com or .at or .org etc etc open directly (as if I was typing them in the URL)

It is just a suggestion. I love the work you've done.

**Comment by bao-qian** [comment]
![image](https://user-images.githubusercontent.com/1169912/82868705-ae1bfa00-9f5f-11ea-92d4-76afc4bdbafe.png)
