### ISSUE TITLE
能不能支持鼠标移动到屏幕边缘直接唤醒开关丫?不习惯用键盘

### ISSUE THREAD

**Issue by Noah1995** [Wox-launcher/Wox#2021]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by cqjjjzr** [comment]
不推荐，至少这样对于大部分人会造成严重的误点击。

**Comment by bao-qian** [comment]
not possible at the moment.
