### ISSUE TITLE
[help or request] Custom lookup presets

### ISSUE THREAD

**Issue by alshdavid** [Wox-launcher/Wox#2022]
Hi,

I am unable to find this feature, and am wondering if it's built into the product already, otherwise make the suggestion.

My workflow involves opening a few specific programs.
Would be cool if I could add my own search presets.

e.g. "terminal" => "C:\program files\cmder\cmder.exe --my-flags"

**Comment by Dandjinh** [comment]
create a .lnk in a specific folder and then you call it using Wox

**Comment by bao-qian** [comment]
close due to resolved as @Dandjinh  said
