### ISSUE TITLE
Wox中，对每个条目的优先级是如何计算的？

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#203]
同一项，执行多次貌似不会提升优先级。
这个对效率的影响还是比较大的。

**Comment by qianlifeng** [comment]
其实是有提升的，只不过不明显。你可以看下`Config\UserSelectedRecords.json` 就知道了。不过可以考虑让他的权重更大一点，记得以前也有用户提过这个问题的。
