### ISSUE TITLE
希望使用方向键上下选择时输入框自动补全

### ISSUE THREAD

**Issue by woncode** [Wox-launcher/Wox#2038]
在输入框输入一个关键字，下面会出现许多候选项。
我经常只需要选择使用以前输入过的内容，但是需要更改或添加一些参数。
使用上下方向键选择常用的选项时，输入框却无法更改为当前选择项的内容，
因此出现上面的需求时必须要从头到尾打一遍，太繁琐了。
如下图，我希望当我用方向键选择到“ipconfig”时，此时输入框的内容也为“ipconfig”
![default](https://user-images.githubusercontent.com/20252778/40194470-1e1be8b6-5a3d-11e8-9697-7f94cbc38286.PNG)

**Comment by mukuangling** [comment]
赞同，希望能支持此功能。

**Comment by qianlifeng** [comment]
Will track on #3036
