### ISSUE TITLE
我是来送名字的

### ISSUE THREAD

**Issue by guanpu** [Wox-launcher/Wox#204]
哈哈，原来Windows版的Alfred已经在做了。看到[开发中的 Windows 版的 Alfred 得有个好名字](http://www.v2ex.com/t/98605)点进来的。
我想说的是，我觉得叫Betty比较好哦，一听就是女侍应的名字,A对B,男对女，管家对仆从，简直绝了。

我正打算用node-webkit搞个类似的——[https://github.com/guanpu/betty](https://github.com/guanpu/betty)——发现这个已经很好了，我那个就纯粹玩玩啦。如果需要，名字可以送给这个项目！

**Comment by qianlifeng** [comment]
谢谢，目前Wox不打算更改名字。
