### ISSUE TITLE
wox error

### ISSUE THREAD

**Issue by JoeyLee96** [Wox-launcher/Wox#2040]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)
![snipaste_2018-05-19_10-35-26](https://user-images.githubusercontent.com/18721811/40264138-41ab650e-5b50-11e8-9731-75d00015ef16.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
