### ISSUE TITLE
当快捷键设置成Ctrl + rightCtrl 或者ctrl + leftCtrl的时候 快捷键只生效一次（第一次开启的时候）

### ISSUE THREAD

**Issue by oldddddriver** [Wox-launcher/Wox#2042]
### Are you submitting a bug report?
Yes

### Steps to reproduce

估计是bug，没有log
当快捷键设置成Ctrl + rightCtrl
或者ctrl + leftCtrl的时候
快捷键只生效一次（第一次开启的时候）
windows版本1083

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
