### ISSUE TITLE
Wox Popup (suggestions) is not visible when Wox is positioned at the bottom of the screen

### ISSUE THREAD

**Issue by nerdpad** [Wox-launcher/Wox#2044]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Open Wox
2. Change the launcher position to the Bottom Left corner (move it to the bottom-left corner of the screen)
3. Close Wox
4. Open Wox
5. Type something in Wox

When Wox is positioned at the bottom of the screen and there is no place for the Popup to open, and you type something. The Wox Popup (The list of suggestions) still appear at the bottom and get cut off the screen.

### Actual Behavior
1. The Popup still expands to the bottom (and beyond the screen)
2. The popup is not visible

### Expected Behavior (IMHO)
1. The popup can change position (Eg: appear on top) if there is no room at the bottom
2. The popup should change orientation and should be visible

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
