### ISSUE TITLE
wox 无法搜索

### ISSUE THREAD

**Issue by heuropean** [Wox-launcher/Wox#2045]
我不知道碰触了什么，wox 无法搜索了，只有下面图片的4个列表，如何解决这个问题？
（wox重新启动，就好了）是否可以修改配置，来解决这个问题，而不用重复启动

![wox_pro](https://user-images.githubusercontent.com/36780317/40337645-57f0c3c2-5da3-11e8-9cc4-763a14f66baf.jpg)

**Comment by blurHY** [comment]
这个是某个项的菜单，在文本框里按esc

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
