### ISSUE TITLE
设置HTTP代理失败

### ISSUE THREAD

**Issue by easepan** [Wox-launcher/Wox#2053]
### Are you submitting a bug report?

yes

### Steps to reproduce

1. enable http proxy

### Wox Error Window text

proxy connection failed

**Comment by mgrddsj** [comment]
I have the same problem. But the proxy is actually working. It seems it always displays "proxy connections failed". After turning the switch on, I can use searching suggestions from Google. 

我也有这个问题，但是代理可以用。打开开关之后，尽管测试不成功，谷歌的搜索建议是可以用的。
