### ISSUE TITLE
It's not obvious that I need to restart in order to change "last query" behavior in settings.

### ISSUE THREAD

**Issue by tomasfejfar** [Wox-launcher/Wox#2058]
### Are you submitting a bug report?

Kind of :) It's IMO a bug (not correct behavior) that is more like a feature request (it's not an error).

### Steps to reproduce

Last query kept displaying when I installed vox. So I changed it in settings. It kept appearing. I needed to restart vox. It was not obvious that I need to do that.

**Comment by mrmatos6837** [comment]
Agreed. I actually struggled for a little bit before I came to the github issues page thinking it was probably a bug. 
I would have never guessed I was supposed to close the app to make it work.
