### ISSUE TITLE
设置界面无法显示

### ISSUE THREAD

**Issue by LukeLike** [Wox-launcher/Wox#2062]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. 单击 Wox 的托盘，选择 Settings
2. 弹出了设置窗口，但窗口内无内容
(Wox 版本 1.3.524)

### Wox Error Window text

无

### Detailed logs

[2018-06-06.txt](https://github.com/Wox-launcher/Wox/files/2075756/2018-06-06.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/8063808/41032838-2aa77940-69b7-11e8-9768-024061236e17.png)

**Comment by LukeLike** [comment]
貌似是其他软件引起的，不是 wox 本身的问题。

**Comment by gsfish** [comment]
我最近也遇到了这个问题，请问你是如何解决的呢？

**Comment by gsfish** [comment]
我最近也遇到了这个问题，请问你是如何解决的呢？ @LukeLike

**Comment by LukeLike** [comment]
应该是某个软件和 Wox 发生了冲突，把对应软件关掉就没事了。具体是那个软件我忘了（有可能是 mactype, startisback 这类对系统行为影响比较大的软件）。你可以试着关掉自己后台运行的软件排查一下。
