### ISSUE TITLE
如何备份插件配置以应付重装系统？ 

### ISSUE THREAD

**Issue by momo5269** [Wox-launcher/Wox#2063]
### Are you submitting a bug report?
No

### Steps to reproduce
1.找到wox目录打包压缩
2.重装系统
3.安装wox，后用压缩包覆盖

如题……配置比较繁琐的情况下，如何备份呢 - -

**Comment by momo5269** [comment]
似乎 用appdata目录下的覆盖就可以？
问题已解决 appdata目录下文件覆盖即可 - -我好蠢啊 - -

**Comment by ikkz** [comment]
[这儿](https://github.com/cildhdi/Wox.Plugin.PluginBackup)有个插件嘻嘻

**Comment by momo5269** [comment]
非常感谢！🐱

LeiLeiLei <notifications@github.com> 于2019年2月18日周一 下午10:02写道：

**Comment by bao-qian** [comment]
close due to resolved.
