### ISSUE TITLE
安装多个插件后启动崩溃 - -

### ISSUE THREAD

**Issue by momo5269** [Wox-launcher/Wox#2064]
### Are you submitting a bug report?

YES

### Steps to reproduce

1.安装插件60、21、11、129、79、46、135
2.重启wox →显示崩溃 丢失语言设置 于是禁用部分插件
3.再次重启依旧

### Detailed logs

[2018-06-07.txt](https://github.com/Wox-launcher/Wox/files/2079142/2018-06-07.txt)

### Screenshots (optional)
![2018-06-07_141537](https://user-images.githubusercontent.com/698991/41081406-4b61d38c-6a5d-11e8-86bc-addb96d6b116.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
