### ISSUE TITLE
WOX 启动时，剪贴板请求失败

### ISSUE THREAD

**Issue by yslmyr** [Wox-launcher/Wox#2065]
### Are you submitting a bug report?
yes

### Steps to reproduce

1.Woxk随系统启动，报错

### Wox Error Window text

************** 异常文本 **************
System.Runtime.InteropServices.ExternalException (0x800401D0): 所请求的剪贴板操作失败。
   在 System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   在 System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   在 System.Windows.Forms.Clipboard.GetDataObject()
   在 Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   在 Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### Detailed logs

[2018-06-07.txt](https://github.com/Wox-launcher/Wox/files/2080208/2018-06-07.txt)

**Comment by Zonciu** [comment]
+1
在远程桌面时，连接中断恢复后也会报相同的错误。

**Comment by jochne** [comment]
+1

**Comment by imckh** [comment]
+1 每次电脑开机就会出现这个错误

**Comment by llinfeng** [comment]
求问：取消/删除有关剪切板的插件会不会解决问题呢？

+1 同样问题，附件是所有报错的截图；
![wox_detailed_error_messages](https://user-images.githubusercontent.com/5890407/45329379-29404100-b52e-11e8-9af2-a16d18d6a847.jpg)
![wox_error_message](https://user-images.githubusercontent.com/5890407/45329380-29404100-b52e-11e8-8d4c-1e6ddb5225bb.jpg)

**Comment by DongLau** [comment]
+1

**Comment by llinfeng** [comment]
删掉对应的剪切板记录的插件会解决问题。

**Comment by llinfeng** [comment]
关于剪切板历史——可以用[Ditto](https://ditto-cp.sourceforge.io/)来满足需求。

**Comment by DongLau** [comment]
> 关于剪切板历史——可以用[Ditto](https://ditto-cp.sourceforge.io/)来满足需求。

多谢

**Comment by liberize** [comment]
try my patched version:
https://github.com/liberize/Wox.Plugin.ClipboardManager/releases
