### ISSUE TITLE
算是抄袭吗？

### ISSUE THREAD

**Issue by YAIBA2** [Wox-launcher/Wox#2066]
火萤酱
https://j.huoying666.com/
首页没有看到关于wox任何版权声明，感觉就是一个模子出来的
这。。。要是有商业合作当我没说

**Comment by chrisliu0220** [comment]
国外这种软件多的是，只是你不知道罢了，是否可以说wox抄袭别人软件 ？

**Comment by Youxikong** [comment]
<del>这算是违反了开源的规则。而且火萤这家公司真的是劣迹斑斑。</del>
以上言论未经考证，请勿轻信。

**Comment by Youxikong** [comment]
其中还包含了eveything的32位版，甚至签名都不舍得改一下。

**Comment by mukuangling** [comment]
不过火萤那软件"在搜索框无内容的情况下，直接按回车进入设置"的功能还不错.我一直希望Wox能隐藏通知栏图标

**Comment by chrisliu0220** [comment]
> 其中还包含了eveything的32位版，甚至签名都不舍得改一下。
改了签名才算违反了开源规则吧？人家证书都放上去了，仔细看看代码、文件结构等等，哪里用到wox的东西了？有什么劣迹你也说说看，无脑喷子，别在这里秀了

**Comment by bao-qian** [comment]
close due to no further discussion.
