### ISSUE TITLE
Adding a new query

### ISSUE THREAD

**Issue by msmcmiller** [Wox-launcher/Wox#2069]
### Are you submitting a bug report?

No

Hi there,

I am a former Alfred user on the Mac operating system. I am now using a PC and was looking for a similar program to cut down on some of the repetitive things I type and access each day. I found Wox listed on a form and though I would have a try. I've got it installed but, when I tried to add a query for searching the web it isn't working. The example I am using is not the actual domain as it is used within my company but I think you should be able to get gist. 

So the query is https://domain.com/local/(this would be the query)/offers . I entered https://domain.com/local/{q}/offers . Wox attempts to search the id I enter but doesn't find anything. In fact it drops off at https://domain.com/local which is not even in the system (not a page).  I am sure my experience has to with some silly mistake I am making but could someone help me out?

Best regards,

![capture](https://user-images.githubusercontent.com/17754363/41549830-a9a011ec-72ec-11e8-80b9-d56ade6359f9.PNG)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
