### ISSUE TITLE
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。

### ISSUE THREAD

**Issue by imckh** [Wox-launcher/Wox#2077]
Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: C:\Programing\Python\Python36\pythonw.exe
Everything SDK Path: C:\Users\98799\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/21/2018 21:39:56
Exception:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by peiqianggao** [comment]
同样的问题 +1

**Comment by jimmy-yao** [comment]
同样的问题

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: C:\Program Files (x86)\Python\Python3\pythonw.exe
Everything SDK Path: C:\Users\GuoQianLin\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/12/2018 10:05:42
Exception:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
