### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by onlinelei** [Wox-launcher/Wox#2079]
### Steps to reproduce

1.wpm install Wox.Plugin.SimpleClock
2.clock add 19:30 post card

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/27/2018 10:22:36
Exception:
System.TypeLoadException: 未能从程序集“Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。
   在 Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   在 Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) 位置 C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:行号 166
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs
```
System.TypeLoadException: 未能从程序集“Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。
   Source: Wox.Plugin.SimpleClock
   TargetAssembly: Wox.Plugin.SimpleClock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.SimpleClock.dll
   TargetSite: Boolean CommandExecution(System.Collections.Generic.List`1[System.String])
   在 Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   在 Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) 位置 C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:行号 166
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.exe" 
* Timestamp: 06/27/2018 10:23:40
* Wox version: 1.3.524
* OS Version: Microsoft Windows NT 10.0.16299.0
* IntPtr Length: 8
* x64: True
* Python Path: 
* Everything SDK Path: C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.7.02556
   * v4 Full 4.7.02556
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.exe)
* Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.Plugin.dll)
* Wox.Core, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\NLog.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Pinyin4Net.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Newtonsoft.Json.dll)
* Wox.Plugin.Caculator, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Color, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Wox.Plugin.Shell, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\WindowsInput.dll)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Management.winmd)
* Wox.Plugin.Sys, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Storage.winmd)
* Windows.System, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.System.winmd)
* Wox.Plugin.ProcessKiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Roaming\Wox\Plugins\Wox.Plugin.ProcessKiller-aaaa2766-1bfc-4152-941b-5d7caa47da3a\Wox.Plugin.ProcessKiller.dll)
* Wox.Plugin.SimpleClock, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Roaming\Wox\Plugins\Wox.Plugin.SimpleClock-71bfa88b-e27d-4788-b0f4-ce266f740619\Wox.Plugin.SimpleClock.dll)
* Wox.Plugin.Boromak, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Roaming\Wox\Plugins\Wox.Plugin.SimpleClock-71bfa88b-e27d-4788-b0f4-ce266f740619\Wox.Plugin.Boromak.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\NHotkey.Wpf.dll)
* Squirrel, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\NuGet.Squirrel.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
* PresentationCore.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* System.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.resources.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll)
* System.Deployment.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment.resources\v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a\System.Deployment.resources.dll)
* PresentationFramework-SystemDrawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemDrawing\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemDrawing.dll)

2018-06-27 10:23:43.5534|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2018-06-27 10:23:43.5534|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.TypeLoadException>
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能从程序集“Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。>
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 Wox.Plugin.SimpleClock.Commands.AlarmCommand.AlarmTimer_Elapsed(Object sender, ElapsedEventArgs e)
   在 System.Timers.Timer.MyTimerCallback(Object state)>
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <Wox.Plugin.SimpleClock>
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void AlarmTimer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)>
2018-06-27 10:23:43.5594|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233054>
2018-06-27 10:23:43.5730|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2018-06-27 10:23:48.5527|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2018-06-27 10:23:48.5527|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2018-06-27 10:23:48.5527|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.TypeLoadException>
2018-06-27 10:23:48.5527|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能从程序集“Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。>
2018-06-27 10:23:48.5527|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 Wox.Plugin.SimpleClock.Commands.AlarmCommand.AlarmTimer_Elapsed(Object sender, ElapsedEventArgs e)
   在 System.Timers.Timer.MyTimerCallback(Object state)>
2018-06-27 10:23:48.5577|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <Wox.Plugin.SimpleClock>
2018-06-27 10:23:48.5577|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void AlarmTimer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)>
2018-06-27 10:23:48.5577|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233054>
2018-06-27 10:23:48.5577|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2018-06-27 10:23:53.5531|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2018-06-27 10:23:53.5531|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2018-06-27 10:23:53.5531|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.TypeLoadException>
2018-06-27 10:23:53.5531|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能从程序集“Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Storage.Storage`1”。>
2018-06-27 10:23:53.5531|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 Wox.Plugin.SimpleClock.Commands.AlarmCommand.AlarmTimer_Elapsed(Object sender, ElapsedEventArgs e)
   在 System.Timers.Timer.MyTimerCallback(Object state)>
2018-06-27 10:23:53.5581|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <Wox.Plugin.SimpleClock>
2018-06-27 10:23:53.5581|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void AlarmTimer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)>
2018-06-27 10:23:53.5581|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233054>
2018-06-27 10:23:53.5581|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

### Screenshots (optional)
nothing i can do

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
