### ISSUE TITLE
Youtube Query and Wox.Spotify plugin not working

### ISSUE THREAD

**Issue by bryantan16046562** [Wox-launcher/Wox#2080]
### Are you submitting a bug report?

(write your answer here)

I don't have any bug reports but as for plugin Youtube Query and Wox.Spotify, i couldn't search for anything as it doesn't display anything. I tried to uninstall ad install it again doesn't work.

### Screenshots (optional)

(drop your screenshot here)
screenshot == https://drive.google.com/file/d/1ilYlGzLVJ1DYB5QCYqbzmuK-JwefzfdS/view?usp=sharing

**Comment by Chachu1** [comment]
youtube plugin is not working for me either. 
![2018-07-01_12-29-34](https://user-images.githubusercontent.com/13281554/42132597-35f11710-7d2c-11e8-84aa-3f6f19996247.gif)

**Comment by n0x84** [comment]
I've just installed WOX. First two plugins I've checked not working :/ Not a good start.

**Comment by manuelDiaz5** [comment]
same problem here
