### ISSUE TITLE
Settings window empty

### ISSUE THREAD

**Issue by rubo88** [Wox-launcher/Wox#2081]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Open settings
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

![wox_2018-06-27_20-32-22](https://user-images.githubusercontent.com/16985034/41992648-5de6fe14-7a49-11e8-8063-4ad66a4377df.png)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
