### ISSUE TITLE
How to add 2 or more action keywords

### ISSUE THREAD

**Issue by SteveMavic** [Wox-launcher/Wox#2082]
### Are you submitting a bug report?

No

------------------------------------------------

What should I do in order to add two or more action keywords? For example I have keyword "hc" to list certain results, but I'd like to have possibility to add items through "cbadd" command.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
