### ISSUE TITLE
Everythign not working with Wox

### ISSUE THREAD

**Issue by billingsaur** [Wox-launcher/Wox#2083]
### Are you submitting a bug report?

(write your answer here)
NO

I just downloaded Everything but when I search for a file nothing pops up in Wox.

**Comment by lgjmac** [comment]
Try using the older version of Everything on the Releases page.
Or: since the new version has a lot of new features like preview: you should try reinstalling Everything and then also installing the Everything SDK from the voidtools website 
[here](https://www.voidtools.com/Everything-SDK.zip)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
