### ISSUE TITLE
issue :0 wox plugin macros

### ISSUE THREAD

**Issue by growolff** [Wox-launcher/Wox#2085]
### Are you submitting a bug report?
YES
(write your answer here)

### Steps to reproduce

1. Installed wox plugin macros
2. it crashed
3.

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\xx\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/02/2018 01:46:35
Exception:
System.AggregateException: Se han producido uno o varios errores. ---> System.TypeLoadException: No se puede cargar el tipo 'Wox.Infrastructure.Storage.Storage`1' del ensamblado'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null'.
   en Wox.Plugin.Type.Main.Init(PluginInitContext context)
   en Wox.Infrastructure.Stopwatch.Debug(String message, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 19
   en Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 101
   en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   en System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   en System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   en Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 91
   en Wox.App.<OnStartup>b__10_0() en C:\projects\wox\Wox\App.xaml.cs:línea 60
   en Wox.Infrastructure.Stopwatch.Normal(String message, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 31
   en System.Windows.Application.OnStartup(StartupEventArgs e)
   en System.Windows.Application.<.ctor>b__1_0(Object unused)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Nº de excepción interna 0) System.TypeLoadException: No se puede cargar el tipo 'Wox.Infrastructure.Storage.Storage`1' del ensamblado'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null'.
   en Wox.Plugin.Type.Main.Init(PluginInitContext context)
   en Wox.Infrastructure.Stopwatch.Debug(String message, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 19
   en Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 101
   en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by shubham418** [comment]
yep, plugin caused crash for me as well, although the exception was System.NullReferenceException

Here's the log file.

[2018-07-05.txt](https://github.com/Wox-launcher/Wox/files/2221427/2018-07-05.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
