### ISSUE TITLE
Add Settings results

### ISSUE THREAD

**Issue by DragoCubed** [Wox-launcher/Wox#2088]
### Are you submitting a bug report?

No

Classic Shell aka Classic Start can do this. It's important because many settings are moving from the control panel to the Settings app.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
track using https://github.com/Wox-launcher/Wox/issues/2875
please subscribe #2875 for updates.
