### ISSUE TITLE
经常出现未处理的异常

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#209]
Win8.1

经常出现未处理的异常：

1.频繁对Settings进行操作时。
2.系统任务繁忙时，也会出现异常。其他程序则正常。
3.关闭一个异常之后，又继续弹出异常提示。

**Comment by qianlifeng** [comment]
具体的异常提示？

**Comment by ghost** [comment]
无法查看，窗口黑屏。

另外一个奇怪的地方是：

Hotkey自己改成`Ctrl + C` 。暂时无法排除自己环境问题还是其他方面。

**Comment by qianlifeng** [comment]
可以去Wox目录下面的log.txt看

**Comment by ghost** [comment]
最近几次的异常原因：
System.OutOfMemoryException: 没有足够的内存继续执行程序。 这个当时进行解压的操作。

## Environment
- Command Line: "D:\Program Files\Wox\Wox.exe" 
- Exception Handle: System.Windows.Application.DispatcherUnhandledException
- Timestamp: 2014-12-02T19:19:55.1994923+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.2.9200.0
- CLR Version: 2.0.50727.8000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.5.51641
  - v4 Full 4.5.51641
  - v4.0 Client 4.0.0.0
  - v4.5.1 installed with Windows 8.1

主要的几个异常信息：

System.InvalidOperationException: 呈现线程上发生未指定的错误。
   Source: PresentationCore
   TargetAssembly: PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationCore.dll
   TargetSite: Void NotifyPartitionIsZombie(Int32)
   在 System.Windows.Media.MediaContext.NotifyPartitionIsZombie(Int32 failureCode)
   在 System.Windows.Media.MediaContext.NotifyChannelMessage()
   在 System.Windows.Interop.HwndTarget.HandleMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

---

System.Runtime.InteropServices.COMException: UCEERR_RENDERTHREADFAILURE (异常来自 HRESULT:0x88980406)
   Source: PresentationCore
   TargetAssembly: PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationCore.dll
   TargetSite: Void SyncFlush()
   在 System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   在 System.Windows.Media.Composition.DUCE.CompositionTarget.UpdateWindowSettings(ResourceHandle hCompositionTarget, RECT windowRect, Color colorKey, Single constantAlpha, MILWindowLayerType windowLayerType, MILTransparencyFlags transparencyMode, Boolean isChild, Boolean isRTL, Boolean renderingEnabled, Int32 disableCookie, Channel channel)
   在 System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   在 System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   在 System.Windows.Interop.HwndTarget.HandleMessage(Int32 msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

**Comment by qianlifeng** [comment]
看样子是你内存不足

**Comment by ghost** [comment]
呵呵，距上次回复已经九天了。
在Log文件发现三种类型的Exception：

第一种是：System.OutOfMemoryException 
原因：`这个是我当时系统正在进行大量的解压工作，所以大概内存比较紧，没什么好说`。

第二种是：System.InvalidOperationException: 呈现线程上发生未指定的错误。
原因：`未知`。

第三种：System.Runtime.InteropServices.COMException: UCEERR_RENDERTHREADFAILURE (异常来自 HRESULT:0x88980406)
原因：`未知`。

不过这几天回到Win7系统。再试用看看。

**Comment by qianlifeng** [comment]
不好意思回复了这么晚。有可能在win8.1下确实会出现类似的问题，我一直都在win7下面工作，所以没有发现类似的问题。这几个原因都很不明朗，很难判断是什么原因引起的错误。

**Comment by qianlifeng** [comment]
http://blogs.msdn.com/b/dsui_team/archive/2013/11/20/10469037.aspx 这边有一个可能的解释。

> Historically speaking, the most common bucket of WPF render thread failures was associated with video hardware or driver problems.

看起来很硬件或者驱动有关？
