### ISSUE TITLE
Wox 非常耗内存资源，达到了618M，能否优化下？

### ISSUE THREAD

**Issue by valuex** [Wox-launcher/Wox#2090]
如题，wox比chrome还耗内存资源，是因为高分屏的原因吗，请看看能否优化下，谢谢。
相关信息：
系统：win10 pro
电脑： surface laptop 8G内存版

**Comment by jhdxr** [comment]
请问 #1683 里的版本（https://github.com/Wox-launcher/Wox/issues/1683#issuecomment-346630226） 是否能够解决你的问题？

**Comment by valuex** [comment]
谢谢，尝试了下，内存消耗还是很高，系统信息如上，看看能否帮忙解决。

**Comment by mukuangling** [comment]
我的win101803_x64，刚看了下内存占用约160M左右

**Comment by quentinck** [comment]
目前问题情况咋样啊？

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
