### ISSUE TITLE
启动不了,不知道为什么

### ISSUE THREAD

**Issue by xman55555** [Wox-launcher/Wox#2093]
英文看不懂,直接就是启动不了,...........

**Comment by xman55555** [comment]
[2018-07-06.txt](https://github.com/Wox-launcher/Wox/files/2169968/2018-07-06.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
