### ISSUE TITLE
Unable to write to c:\programdata\xps - it policies may be restricting access to this folder

### ISSUE THREAD

**Issue by PKeves** [Wox-launcher/Wox#2094]
I'm getting error during installation of wox, this is the step's I took to try to install it:

1. Download all the required programs for wox

2. download wox.exe and got a subsequent error when trying to install it: "unable to write to c:\programdata\xps - it policies may be restricting access to this folder

3. Tried to run it as administrator and it still doesn't' work, I'm running it on my personal computer in which I have no restrictions at all.

Could you please help me to fix this?

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
