### ISSUE TITLE
Allow user to set their custom ActionKeyword

### ISSUE THREAD

**Issue by orzFly** [Wox-launcher/Wox#21]
Maybe there is a lot of translation workflows (Google, Baidu, Yodao, etc.) sharing the same ActionKeyword "fy".

**Comment by qianlifeng** [comment]
Agree.

**Comment by minzhang** [comment]
Hope build-in bookmark plugin can has its own ActionKeyword too.
I have lots bookmarks in Chrome, typing 'winword' caused thirty some  bookmark entries on top of 'Microsoft Word'.
