### ISSUE TITLE
计算器支持各种进制的计算及进制之间的转换

### ISSUE THREAD

**Issue by bitbegin** [Wox-launcher/Wox#210]
### 比如这样的计算：

输入：
    0x100-0x20

计算结果：

```
0xE0 (16进制)
224 (10进制)
...
```
### 进制转换：

输入：
    100

结果：

```
0x64
100
```

如果太复杂，能够支援到2/10/16进制就可以了。

进制的问题太长遇到了，希望可以得到支持

**Comment by qianlifeng** [comment]
我暂时没有时间对计算器插件增加这个支持,如果有人愿意做,可以发起pull request。
