### ISSUE TITLE
关于URL插件

### ISSUE THREAD

**Issue by youguanxinqing** [Wox-launcher/Wox#2102]
请问，安装了URL插件，但是每次在输入框输入网址都显示失败

PS:我有百度，但找不到相关的解决方式

---------
-------------------------- Begin exception --------------------------
First Chance Exception:
Exception fulle name:
 <System.ComponentModel.Win32Exception>
Exception message:
 <系统找不到指定的文件。>
Exception stack trace:
 <   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)>
Exception source:
 <System>
Exception target site:
 <Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)>
Exception HResult:
 <-2147467259>
-------------------------- End exception --------------------------
---------

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
