### ISSUE TITLE
Add a setting to the calculator to remove the selection of the decimal separator based on the locale

### ISSUE THREAD

**Issue by DerBensch** [Wox-launcher/Wox#2106]
I can only use a German Windows at work and in every programming language, you need a dot as a decimal separator, but the calculator changes it automatically to a comma.
Therefore, I have to change it every time I use the results.

It would be nice if there were a setting to disable the automatic replacement.

**Comment by Prophe-T** [comment]
I would second this and add the ability to enter values in your locale for the non-programming folks, eg "1,72+1,345" instead of "1.72+1.345". If you use wox as a daily driver for non-programming productivity, math is a little off-throwing.
Apart from that thanks for your work on wox.

**Comment by ZielonyBuszmen** [comment]
How to change `dot` to `comma` in calculator? Is there any option about that?

**Comment by ghost** [comment]
Is there still no solution? :)

**Comment by ZielonyBuszmen** [comment]
Yes, still no solution

**Comment by stefanpawlik** [comment]
Would also highly appreciate this feature :)

**Comment by gawkla** [comment]
my vote on this issue!

**Comment by RalfRoemling** [comment]
+1

**Comment by RalfRoemling** [comment]
Definitely a yes for locale standards.
Strange that the surface is translated but the Calc is not. 
Anybody tried to contact the author cxfksword himself?

**Comment by jjw24** [comment]
This has been fixed in my fork with additional improvements: https://github.com/jjw24/Wox/releases/tag/JJW24-v1.44.21

**Comment by DerBensch** [comment]
Thank you and SysC0mp very much.
