### ISSUE TITLE
Keyboard hotkey to reindex Program plugin

### ISSUE THREAD

**Issue by m5x** [Wox-launcher/Wox#2113]
It would be great if it was possible to hit e.g. F5 to reindex files in Program plugin instead of having to go through context menu and settings.

**Comment by jeroendv** [comment]
+1

**Comment by markhavemann** [comment]
+1

**Comment by ilumos** [comment]
This is something Launchy (Windows) and Alfred (macOS) have, and I used very frequently - would be great to see it in Wox, and hopefully not too difficult to add?
