### ISSUE TITLE
Image loading will slow down the search speed

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#212]
While you search items that didn't search before, loading images of thoese program will slow down the search.

**Comment by qianlifeng** [comment]
we can cache top used images.

**Comment by tianjianchn** [comment]
yes, this is the #207's answer. can wox load images async?

**Comment by qianlifeng** [comment]
This commit will help improve the loading speed of images. 8ef6fc366dccd1e0bcb22834280a6b565c14b977

**Comment by bao-qian** [comment]
the image is loaded async now and there is no more blocking in main ui thread
try this one https://ci.appveyor.com/project/happlebao/wox/build/1.2.917/artifacts
description: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900
@kiliwalk
