### ISSUE TITLE
版本1.3.524，在win10 1803下安装之后，win+R 快捷键之后，windows的运行也出来了

### ISSUE THREAD

**Issue by lingxyd** [Wox-launcher/Wox#2120]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by seagle0128** [comment]
同样的问题，Replace Win+R之后，Windows运行窗口还是出来了。

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
