### ISSUE TITLE
Idea for way to reindex without restart

### ISSUE THREAD

**Issue by lgjmac** [Wox-launcher/Wox#2122]
It would be great to avoid needing to restart Wox in order to access a newly installed program via Programs plugin
Has anyone found a solution already?
I am finding that Wox takes about 5 seconds to load (quick computer, plugins are: clipboard, process killer, simple web search as well as the others).
I know it can be found through everything file search. This is useful but often too many results/hidden behind simple web search when not having its own hotkey.
I can code something in Python; wondered if anyone has any ideas?

**Comment by roose** [comment]
@lgjmac The Programs plugin has a "Reindex" button in the settings

**Comment by lgjmac** [comment]
Hi yeah; I was kind of looking for a solution without mouse clicking. That's what I meant at least. I.e. Install app --> Search in Wox... Possibly a Reindex Alt-Space function

**Comment by roose** [comment]
Ah, I understand, like "reindex" query, nice idea

**Comment by jeroendv** [comment]
+1

**Comment by cmeyertons** [comment]
+1

**Comment by hi2u** [comment]
This is really a big missing feature I think.  Albert and almost every other launcher I know of doesn't need to be restarted when the shortcuts change.  

I'm auto-generating 100s of shortcut .lnk files, and having to manually close and re-open Wox every time slows me down a lot, especially painful when I'm testing my generation code for new shortcuts.  Not even my script that runs `taskkill /im wox.exe` seems to work reliably.  It works sometimes, and not others, not sure why.  I don't really want to have to add `/F` to force it for something done this often.

A simple command line option along the lines of:

> wox.exe /reindex

...which just reindexes in the current running process would make it easy for us to trigger it via any method we like, including (but not limited to):

* Internally, you can just create a .lnk shortcut that runs `wox.exe /reindex` and give it whatever name and icon you like
* Externally with a hotkey, e.g. from the shortcut or AutoHotkey etc
* From any kinds of scripts that can run commands
* Scheduled tasks
* etc...

So assuming that's not too hard, I think adding a simple CLI option would give the most flexibility in how people want to trigger the reindex.

Alternatively if it's done with a global hotkey (i.e. the Wox window doesn't need to be focused), that's probably the 2nd best option, which could still be triggered from an autohotkey script to simulate pressing the global hotkey.
