### ISSUE TITLE
Search optimization（搜索优化）

### ISSUE THREAD

**Issue by Rain120** [Wox-launcher/Wox#2125]
The search program removes the uninstaller and specifies the character display uninstaller
![image](https://user-images.githubusercontent.com/20939839/43041819-19f01b38-8d9e-11e8-8240-f6acbb4b6ab9.png)
搜索时默认去除卸载程序的搜索，指定字符显示卸载应用的程序搜索

**Comment by jhdxr** [comment]
in fact this can be done by #800 , however the PR is not mergable at this moment.
