### ISSUE TITLE
Nuget / chocolatey auto publishing

### ISSUE THREAD

**Issue by ckesc** [Wox-launcher/Wox#213]
Please configure CI server to autopublish WOX =)

I`ve noticed tha you using appveyor. It seems tha it can be configured to autobuild-and-pack for nuget system. Than you can (also automatic) publish it to https://chocolatey.org (It is apt-get for windows)

**Comment by qianlifeng** [comment]
I'm thinking about auto publishing `Wox.Plugin.dll` to nuget automatically. I found [myget](https://www.myget.org/). If appveyor can cover that, I will happy to do some research on it.

**Comment by qianlifeng** [comment]
Finally, get auto publishing to nuget work.

**Comment by ckesc** [comment]
Great! What about chocolatey?

16:49, вс, 14.12.2014, qianlifeng notifications@github.com:

**Comment by qianlifeng** [comment]
Still working on it.

**Comment by ckesc** [comment]
Made package for easy install via [chocolatey.org](http://chocolatey.org) !
https://chocolatey.org/packages/wox

May be add this badgeto readme? =)
<a href="https://chocolatey.org/packages/wox">
  <img src="https://img.shields.io/badge/chocolatey-wox-b4884f.svg?style=flat" style="height:auto; width: 100%">  
</a>

``` html
<a href="https://chocolatey.org/packages/wox">
  <img src="https://img.shields.io/badge/chocolatey-wox-b4884f.svg?style=flat" style="height:auto; width: 100%">  
</a>
```

**Comment by qianlifeng** [comment]
Thx ckesc. it will be great if we can make this automatically.

**Comment by ckesc** [comment]
Hey! I found some instruction for it http://www.jdibble.co.uk/blog/building-and-deploying-clickonce-applications-with-appveyor/ May be you will try it? :) 

If need I can add you as maintainer to chocolatey package
