### ISSUE TITLE
Take all available RAM on win10 1803

### ISSUE THREAD

**Issue by tortoise-chen** [Wox-launcher/Wox#2130]
### Are you submitting a bug report?
YES
(write your answer here)

### Steps to reproduce

1.open wox
2.search anything
3.RAM boom

### Wox Error Window text

(paste here)

### Detailed logs

[2018-07-15.txt](https://github.com/Wox-launcher/Wox/files/2217938/2018-07-15.txt)

(drop your log file here)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/32928865/43057306-06056b56-8e74-11e8-90fb-f786617f310b.png)
(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
