### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by ShadowEvan** [Wox-launcher/Wox#2134]
### Are you submitting a bug report?

(write your answer here)
是的

### Steps to reproduce

1.开机（以前开机没出现过这种情况，最近也没下载别的软件）
2.然后就提示Wox got an error
3.

### Wox Error Window text

(paste here)
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\mrz\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/26/2018 13:15:25
Exception:
System.AggregateException: 发生一个或多个错误。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WoxSteam.Options.Load() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Options.cs:行号 35
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 18
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 93
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 91
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (内部异常 #0) System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WoxSteam.Options.Load() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Options.cs:行号 35
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 18
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 93
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

### Detailed logs

(drop your log file here)
[2018-07-26.txt](https://github.com/Wox-launcher/Wox/files/2230542/2018-07-26.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by winkidney** [comment]
+1, 操作同上面的同学，遇到类似错误

```
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\winkidney\AppData\Roaming\Wox\Logs\1.3.524\2018-07-27.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\winkidney\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/27/2018 10:59:15
Exception:
System.AggregateException: 发生一个或多个错误。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WoxSteam.Options.Load() 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Options.cs:行号 35
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\Documents\Visual Studio 2015\Projects\WoxSteam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 18
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 93
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 
```

[2018-07-27.txt](https://github.com/Wox-launcher/Wox/files/2234258/2018-07-27.txt)

![image](https://user-images.githubusercontent.com/4109722/43299338-635adcb2-918c-11e8-9ebb-83ae269ab9ea.png)

**Comment by ShadowEvan** [comment]
I solved the problem after reset.

**Comment by winkidney** [comment]
@ShadowEvan Hi, it seems that I can not find a function named "reset". How should I do if I want to reset?
Thanks~

**Comment by ShadowEvan** [comment]
@winkidney 
Reset: delete `%APPDATA%\Wox`
Actually, you can find it in README.......XD

**Comment by winkidney** [comment]
@ShadowEvan Thank you, it helps a lot~
