### ISSUE TITLE
Problem about 'Settings'

### ISSUE THREAD

**Issue by oliver0314** [Wox-launcher/Wox#2135]
### Are you submitting a bug report?

No

Hello dear Wox developer, I installed the latest stable version 1.3.524 and have installed Everything and Python. When I opened 'Settings' of WoX by right-clicking the icon in the Taskbar, the page is completely blank. Besides that, everything else seems to work fine. What could the problem probably be? 

Thank you very much.
Oliver

**Comment by rgphoto70** [comment]
I'm having the same issue with Wox 1.3.578 and Win10 1809.

**Comment by bao-qian** [comment]
tracing use new issue https://github.com/Wox-launcher/Wox/issues/2838
please subscribe new issue if problem still exist.
