### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by MyGitHubPigStar** [Wox-launcher/Wox#2137]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.从官网下载有道的插件，[功能完好，使用正常]
2.从官网下载快递查询的插件，[崩溃，出错]

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by MyGitHubPigStar** [comment]
删除快递查询插件，恢复使用

**Comment by bao-qian** [comment]
close due to author resolved by himself.
