### ISSUE TITLE
Requirement: Support of alias input

### ISSUE THREAD

**Issue by snakorse** [Wox-launcher/Wox#2147]
Sometimes I want to execute a long-title script by the shell plugin, I must type in the full script file title so that the cmd can run  it correctly, this is tired. So I hope a feature like alias that I can just type a short alias and than press the Tab key, the full-long-words can auto take in place. and I think this will be helpfull in other scenarios.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

new version has better fuzzy match functionality, you can index you script in program plugin settings and search you script using fuzzy match.
