### ISSUE TITLE
How wox ask me - Please open new issue

### ISSUE THREAD

**Issue by dubconst** [Wox-launcher/Wox#2150]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\usr\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/04/2018 10:34:55
Exception:
System.AggregateException: Произошла одна или несколько ошибок. ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в WoxSteam.Options.Load() в c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:строка 35
   в WoxSteam.Main.Init(PluginInitContext context) в c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:строка 60
   в Wox.Infrastructure.Stopwatch.Debug(String message, Action action) в C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:строка 18
   в Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) в C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:строка 93
   в System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   в System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   в System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   в System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   в System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   в Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) в C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:строка 91
   в Wox.App.<OnStartup>b__10_0() в C:\projects\wox\Wox\App.xaml.cs:строка 60
   в Wox.Infrastructure.Stopwatch.Normal(String message, Action action) в C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:строка 31
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Внутреннее исключение #0) System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в WoxSteam.Options.Load() в c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:строка 35
   в WoxSteam.Main.Init(PluginInitContext context) в c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:строка 60
   в Wox.Infrastructure.Stopwatch.Debug(String message, Action action) в C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:строка 18
   в Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) в C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:строка 93
   в System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   в System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   в System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

[2018-07-08.txt](https://github.com/Wox-launcher/Wox/files/2259295/2018-07-08.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
