### ISSUE TITLE
Suggestion: Store settings and plugins in local folder for easy install on new PC

### ISSUE THREAD

**Issue by tdoerrich** [Wox-launcher/Wox#2153]
### Are you submitting a bug report?
No

# Suggestion
It would be awesome if Wox would work fully in a portable mode, meaning that all the plugins, the config file, etc. All are created in the same folder I have the Wox launcher. I'm not sure this could work for windows apps and such, but if it would work it would be a lot easier when setting up a new PC (or at work), to just copy over my portable Wox version and that already comes with the set-up I want to have.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

new version has portable mode.
