### ISSUE TITLE
Order the priority of search results by plugin

### ISSUE THREAD

**Issue by nevara** [Wox-launcher/Wox#2154]
I installed the Switcheroo plugin and I want to have the Switcheroo results on top of everything else. At the moment it is not possible to have the Switcheroo results at the beginning of the result list.

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Comment by vergilcw** [comment]
I also think this would be super useful. I came searching trying to do the exact same thing (make switcheroo results show first)
