### ISSUE TITLE
Exception: System.ComponentModel.Win32Exception (0x80004005): 没有应用程序与此操作的指定文件有关联。

### ISSUE THREAD

**Issue by overlordsnyt** [Wox-launcher/Wox#2155]
### Are you submitting a bug report?

yes

### Steps to reproduce

1.Alt+Space打开Wox
2.输入“g hahah”，按Enter
3.弹出错误报告

translation:
1.Alt+Space open Wox
2.input “g hahah”，press Enter
3.pop an error report

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\ProgrammingTools\Python3\pythonw.exe
Everything SDK Path: C:\Users\overlord\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/08/2018 12:14:08
Exception:
System.ComponentModel.Win32Exception (0x80004005): 没有应用程序与此操作的指定文件有关联。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.<Query>b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 153
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2018-08-08.txt](https://github.com/Wox-launcher/Wox/files/2268892/2018-08-08.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/9302521/43815994-29e5717c-9b05-11e8-971c-43b5b538728d.png)

**Comment by flier268** [comment]
沒有用過這個專案，但我也有遇到一模一樣的問題，搜尋的時候剛好看到這篇，後來我自己找到解決方案，特別來這邊分享一下
@Wox-launcher
提供解決方案：
把
```C#
System.Diagnostics.Process.Start(filepath);
```
改成
```C#
string explorer_path = Path.Combine(Directory.GetParent(Environment.GetFolderPath(Environment.SpecialFolder.System)).FullName, "explorer.exe");
System.Diagnostics.Process.Start(explorer_path, filepath);
```

**Comment by overlordsnyt** [comment]
> 沒有用過這個專案，但我也有遇到一模一樣的問題，搜尋的時候剛好看到這篇，後來我自己找到解決方案，特別來這邊分享一下
> @Wox-launcher
> 提供解決方案：
> 把
> 
> ```cs
> System.Diagnostics.Process.Start(filepath);
> ```
> 
> 改成
> 
> ```cs
> string explorer_path = Path.Combine(Directory.GetParent(Environment.GetFolderPath(Environment.SpecialFolder.System)).FullName, "explorer.exe");
> System.Diagnostics.Process.Start(explorer_path, filepath);
> ```

谢谢！

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
