### ISSUE TITLE
Updating a plugin on the website 

### ISSUE THREAD

**Issue by antonio-fasolato** [Wox-launcher/Wox#2157]
I created a plugin and uploaded to your website (http://www.wox.one/plugin/106).

I have a new version of the plugin, but if I try to upload it I get an error saying that the plugin name already exists.

How can I update the plugin?

Thanks

**Comment by roose** [comment]
@antonio-fasolato after login, click on your name and you'll see the "Edit" button on the plugin

**Comment by antonio-fasolato** [comment]
Thanks, I was able to update everything.
