### ISSUE TITLE
Is there anyone who can pick up this app for further improvements/maintenance?

### ISSUE THREAD

**Issue by avxkim** [Wox-launcher/Wox#2160]
Just talked to jhdxr via email, he told me that they are very busy now and won't do any further improvements to this beautiful app.

So, maybe there's someone with enough knowledge to take this app?

**Comment by lances101** [comment]
I am currently busy with work too and I don't know when will be my next time window to be able to focus on Wox.

I don't know what is the situation of other members like @happlebao.

**Comment by jhdxr** [comment]
just to clarify, I'm willing to see PRs and I'll check them time to time (maybe once per month). There are builds available for each commit from the CI, so people who like to try something new can get the latest version there.

Personally, wox has already satisfy most of my needs, and I don't know when I'll have time to focus on all my open source projects neither.

**Comment by bao-qian** [comment]
this project is back to active.

Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
