### ISSUE TITLE
WOX 打不开，直接提示已停止工作

### ISSUE THREAD

**Issue by llyzot** [Wox-launcher/Wox#2161]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Wox.exe
  应用程序版本:	1.3.524.0
  应用程序时间戳:	58893cef
  故障模块名称:	Wox.exe
  故障模块版本:	1.3.524.0
  故障模块时间戳:	58893cef
  异常代码:	c0000005
  异常偏移:	00006f81
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by llyzot** [comment]
Wox Error Window text
Version=1
EventType=APPCRASH
EventTime=131784640780370721
ReportType=2
Consent=1
ReportIdentifier=fa31687d-9d61-11e8-9fc1-00266c19d735
IntegratorReportIdentifier=fa31687c-9d61-11e8-9fc1-00266c19d735
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=Wox.exe
Sig[1].Name=应用程序版本
Sig[1].Value=1.3.524.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=5a91ace4
Sig[3].Name=故障模块名称
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=故障模块版本
Sig[4].Value=6.1.7601.24168
Sig[5].Name=故障模块时间戳
Sig[5].Value=5b1aad6d
Sig[6].Name=异常代码
Sig[6].Value=c06d007e
Sig[7].Name=异常偏移
Sig[7].Value=000000000001a06d
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=6.1.7601.2.1.0.256.1
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=7283
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=72836eb6216b49be15302fdb224c1b5d
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=f0b0
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=f0b04b3cc0c9de2a942408d0a3b425c3
UI[2]=C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.exe
UI[3]=Wox 已停止工作
UI[4]=Windows 可以联机检查该问题的解决方案。
UI[5]=联机检查解决方案并关闭该程序
UI[6]=以后联机检查解决方案并关闭程序
UI[7]=关闭程序
LoadedModule[0]=C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\system32\KERNEL32.dll
LoadedModule[4]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\system32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\system32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[11]=C:\Windows\system32\GDI32.dll
LoadedModule[12]=C:\Windows\system32\USER32.dll
LoadedModule[13]=C:\Windows\system32\LPK.dll
LoadedModule[14]=C:\Windows\system32\USP10.dll
LoadedModule[15]=C:\Windows\system32\IMM32.DLL
LoadedModule[16]=C:\Windows\system32\MSCTF.dll
LoadedModule[17]=C:\Windows\system32\VERSION.dll
LoadedModule[18]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[19]=C:\Windows\system32\MSVCR120_CLR0400.dll
LoadedModule[20]=C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\be2b233163fe3b9af2d68b10d4798ef2\mscorlib.ni.dll
LoadedModule[21]=C:\Windows\system32\ole32.dll
LoadedModule[22]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[23]=C:\Windows\system32\uxtheme.dll
LoadedModule[24]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System\7935235c3f8e2147cd57dffc75cbb0fb\System.ni.dll
LoadedModule[25]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\155ef8f4581aba01873e9bb62ccb9304\System.Core.ni.dll
LoadedModule[26]=C:\Windows\assembly\NativeImages_v4.0.30319_64\WindowsBase\a425c169b298379abc6e2f9b0135840e\WindowsBase.ni.dll
LoadedModule[27]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[28]=C:\Windows\system32\rsaenh.dll
LoadedModule[29]=C:\Windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\fb207b0e62d2e5bbc2242bccdf30f3a0\PresentationCore.ni.dll
LoadedModule[30]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\b4e80d855823c48f094bbb87ec8e01e8\PresentationFramework.ni.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xaml\50dc59a5cdb1341e4c65dee908b4d53c\System.Xaml.ni.dll
LoadedModule[32]=C:\Windows\system32\dwrite.dll
LoadedModule[33]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[34]=C:\Windows\system32\MSVCP120_CLR0400.dll
LoadedModule[35]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[36]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[37]=C:\Windows\system32\api-ms-win-core-xstate-l2-1-0.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[39]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runt73a1fc9d#\6e829982880fd95623008c20683e063b\System.Runtime.Remoting.ni.dll
LoadedModule[40]=C:\Windows\system32\SspiCli.dll
LoadedModule[41]=C:\Windows\system32\ws2_32.dll
LoadedModule[42]=C:\Windows\system32\NSI.dll
LoadedModule[43]=C:\Windows\system32\mswsock.dll
LoadedModule[44]=C:\Windows\System32\wshtcpip.dll
LoadedModule[45]=C:\Windows\System32\wship6.dll
LoadedModule[46]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\38cbf8710575db230f3c9efeb1846953\System.Configuration.ni.dll
LoadedModule[47]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\8618d1f3e45476beb264435bd0169ca2\System.Xml.ni.dll
LoadedModule[48]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\nlssorting.dll
LoadedModule[49]=C:\Windows\system32\shell32.dll
LoadedModule[50]=C:\Windows\system32\profapi.dll
LoadedModule[51]=C:\Windows\system32\bcrypt.dll
LoadedModule[52]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[53]=C:\Windows\system32\dwmapi.dll
LoadedModule[54]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.ServiceModel\a09c6bd7ae8cc53f2f981637457aa2d6\System.ServiceModel.ni.dll
LoadedModule[55]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Data\6fe71fe2e6e36ef07ce152a951b26992\System.Data.ni.dll
LoadedModule[56]=C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[57]=C:\Windows\system32\CRYPT32.dll
LoadedModule[58]=C:\Windows\system32\MSASN1.dll
LoadedModule[59]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Runteb92aa12#\c0c3e4a1a3649fd531bfee8ecda13353\System.Runtime.Serialization.ni.dll
LoadedModule[60]=C:\Windows\system32\urlmon.dll
LoadedModule[61]=C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
LoadedModule[62]=C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[63]=C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[64]=C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[65]=C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[66]=C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[67]=C:\Windows\system32\normaliz.DLL
LoadedModule[68]=C:\Windows\system32\iertutil.dll
LoadedModule[69]=C:\Windows\system32\WININET.dll
LoadedModule[70]=C:\Windows\system32\USERENV.dll
LoadedModule[71]=C:\Windows\system32\Secur32.dll
LoadedModule[72]=C:\Windows\system32\api-ms-win-downlevel-advapi32-l2-1-0.dll
LoadedModule[73]=C:\Windows\system32\WindowsCodecs.dll
LoadedModule[74]=C:\Windows\system32\mscms.dll
LoadedModule[75]=C:\Windows\system32\WindowsCodecsExt.dll
LoadedModule[76]=C:\Windows\system32\icm32.dll
LoadedModule[77]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Numerics\9d4a64c4118119b3ff8f0c5110638c44\System.Numerics.ni.dll
LoadedModule[78]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml.Linq\23b80ac54e723bb106f7716442847fe8\System.Xml.Linq.ni.dll
LoadedModule[79]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\02625034c914c7d09b2eaae095fa72d5\System.Drawing.ni.dll
LoadedModule[80]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.23894_none_145eb2808b8d6928\gdiplus.dll
LoadedModule[81]=C:\Windows\system32\sxs.dll
LoadedModule[82]=C:\Windows\system32\CLBCatQ.DLL
LoadedModule[83]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_fa3b1e3d17594757\comctl32.dll
LoadedModule[84]=C:\Windows\system32\apphelp.dll
LoadedModule[85]=C:\Windows\system32\PROPSYS.dll
LoadedModule[86]=C:\Windows\system32\LINKINFO.dll
LoadedModule[87]=C:\Windows\System32\shdocvw.dll
LoadedModule[88]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[89]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[90]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[91]=C:\Windows\system32\ntmarta.dll
LoadedModule[92]=C:\Windows\system32\WLDAP32.dll
LoadedModule[93]=C:\Windows\system32\wtsapi32.dll
LoadedModule[94]=C:\Windows\system32\WINSTA.dll
LoadedModule[95]=C:\Windows\system32\d3d9.dll
LoadedModule[96]=C:\Windows\system32\d3d8thk.dll
LoadedModule[97]=C:\Windows\system32\aticfx64.dll
LoadedModule[98]=C:\Windows\system32\WINMM.dll
LoadedModule[99]=C:\Windows\system32\atiu9p64.dll
LoadedModule[100]=C:\Windows\system32\atiumd64.dll
LoadedModule[101]=C:\Windows\system32\atiumd6a.dll
LoadedModule[102]=C:\Windows\system32\POWRPROF.dll
LoadedModule[103]=C:\Windows\System32\ieframe.dll
LoadedModule[104]=C:\Windows\System32\api-ms-win-downlevel-shell32-l1-1-0.dll
LoadedModule[105]=C:\Windows\System32\WINHTTP.dll
LoadedModule[106]=C:\Windows\System32\webio.dll
LoadedModule[107]=C:\Windows\system32\actxprxy.dll
LoadedModule[108]=C:\Windows\System32\gameux.dll
LoadedModule[109]=C:\Windows\System32\XmlLite.dll
LoadedModule[110]=C:\Windows\System32\wer.dll
LoadedModule[111]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio1c9175f8#\a79cf7f333280cb196945542f2c780c1\PresentationFramework.Aero.ni.dll
LoadedModule[112]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\383c2de82535098e6df44417bcceebdd\System.Windows.Forms.ni.dll
LoadedModule[113]=C:\Windows\system32\psapi.dll
LoadedModule[114]=C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
LoadedModule[115]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Net.Http\89fcbf00923024d3e00a9a4bccfa692f\System.Net.Http.ni.dll
LoadedModule[116]=C:\Windows\system32\rasapi32.dll
LoadedModule[117]=C:\Windows\system32\rasman.dll
LoadedModule[118]=C:\Windows\system32\rtutils.dll
LoadedModule[119]=C:\Windows\system32\credssp.dll
LoadedModule[120]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[121]=C:\Windows\system32\WINNSI.DLL
LoadedModule[122]=C:\Windows\system32\dhcpcsvc.DLL
LoadedModule[123]=C:\Windows\system32\dhcpcsvc6.DLL
LoadedModule[124]=C:\Windows\system32\DNSAPI.dll
LoadedModule[125]=C:\Program Files\Bonjour\mdnsNSP.dll
LoadedModule[126]=C:\Windows\system32\rasadhlp.dll
LoadedModule[127]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[128]=C:\Windows\system32\msctfui.dll
LoadedModule[129]=C:\Windows\assembly\NativeImages_v4.0.30319_64\UIAutomationTypes\f6dff51a539c9de63d4173d3c8f0dfdf\UIAutomationTypes.ni.dll
LoadedModule[130]=C:\Windows\system32\UIAutomationCore.dll
LoadedModule[131]=C:\Windows\system32\OLEACC.dll
LoadedModule[132]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio84a7b877#\dd16bab56995ec11b82f16466c5b5f42\PresentationFramework-SystemData.ni.dll
FriendlyEventName=已停止工作
ConsentKey=APPCRASH
AppName=Wox
AppPath=C:\Users\Administrator\AppData\Local\Wox\app-1.3.524\Wox.exe

**Comment by Jefsky** [comment]
我也遇到了，该怎么解决？

**Comment by DarrenZhu95** [comment]
试试安装 .NET Framework 4.8,我的同样情况已解决

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
