### ISSUE TITLE
Manually Add Plugin

### ISSUE THREAD

**Issue by clrncmcnlsn** [Wox-launcher/Wox#2162]
I would like to know how to manually add a plugin.
The documentation is incomplete.
I tried adding the **HelloWorldCSharp** to the plugins folder (both _\Wox\app-1.3.524\Plugins\HelloWorldPython_ and _\AppData\Roaming\Wox\Plugins_) but don't know where to go from there.

**Comment by roose** [comment]
@clrncmcnlsn 
The correct path is  `AppData\Roaming\Wox\Plugins`
Did you compile the plugin?
Do you have the correct plugin.json in the `HelloWorldCSharp` folder?
Do you enter correct keyword in Wox?
Check please Wox settings in the Plugins tab, is there a plugin in the list?
Check Wox log files, are there any errors associated with your plugin?

**Comment by gissehel** [comment]
Ok, I wrote several plugins and had quite a lot of problems manually loading plugins the first few times.

Here are the gotchas you should avoid:
* Don't try to load plugin using wox with command line arguments. Never worked for me
* Did not try to put the plugin directly in the plugin dir, but I would try to do it before fixing the following points
* your plugin.json SHOULD contains an ID which SHOULD be a 32 characters long haxadecimal value. Anything other than that will fail
* you plugin.json SHOULD contains a version which SHOULD be of the format MAJOR.MINOR.RELEASE (like 2.0.1). A classical windows version number (MAJOR.MINOR.RELEASE.BUILD like 2.0.0.1) will fail
* You can (and that's the only way I use) make a .wox and drag'n'drop the .wox to the wox bar to load the plugin
* a .wox file SHOULD be a zip file renamed .wox
* a .wox file SHOULD contain the plugin.json at the top of the the zip file and not in any subfolder
* a .wox SHOULD reference the .dll and the icon relatively to the plugin.json

**Comment by gissehel** [comment]
Also, improvement wox could make:
* Allow any string as ID that should be unique for the plugin. Thus a logical unique ID would be the project url `"ID":"https://github.com/username/projectname"` 
* Allow any string as a version ( `"Version":"1.0.0.1-alpha"` would be allowed )
