### ISSUE TITLE
WOX takes up so much tesources

### ISSUE THREAD

**Issue by cazz1965** [Wox-launcher/Wox#2164]
It is not exactly a problem.
Just curious why Wox takes up so much memory to run. 
220 over Kbytes and about 1% of CPU processing power to run.

Anyway to make it slimmer?

Thanks

**Comment by SupinePandora43** [comment]
if WOX take much resources when it used, finding resulsts etc - thats normal. but it just started ... and takes so much to listening user alt+space

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
