### ISSUE TITLE
Control Panel plugin: some characters are not recognized

### ISSUE THREAD

**Issue by xmcp** [Wox-launcher/Wox#2169]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Make sure the computer language is set to Simplified Chinese, and the Control Panel plugin is enabled.
2. Input "设备" in Wox, and you will see an entry called "设备管理器".
3. Input "设备管" or "设备管理器", and you will NOT see that entry anymore.

### Wox Error Window text

null

### Detailed logs

[2018-08-14.txt](https://github.com/Wox-launcher/Wox/files/2286018/2018-08-14.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/6646473/44079789-ab2ea394-9fdc-11e8-8596-42b26ae9570c.png)

![image](https://user-images.githubusercontent.com/6646473/44079807-b4eaa270-9fdc-11e8-9fa8-5f1800258e5a.png)

![image](https://user-images.githubusercontent.com/6646473/44079825-c2982988-9fdc-11e8-9cfc-058b24dd9157.png)

### Version Info

Wox 1.3.524
Control Panel plugin 1.0.0
Windows 10 Enterprise 1803 (17134.165)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
