### ISSUE TITLE
第一次呼出时反应较慢

### ISSUE THREAD

**Issue by vingi** [Wox-launcher/Wox#218]
我设置了wox的开机自启动,并自定义热键呼出,但开机后第一次用热键呼出时反应很慢,有可能几秒到十几秒才会呼出来,看起来像是在Init,能否开机启动后在后台预执行Init的操作,避免第一次呼出时的不良体验

**Comment by qianlifeng** [comment]
你用的什么版本？v1.0.2已经解决了启动慢的问题。

**Comment by vingi** [comment]
哈..1.0.1..已经解决了? 那我马上去升.0.2版

**Comment by qianlifeng** [comment]
@vingi 如果没问题了记得关掉这个
