### ISSUE TITLE
Avast antivirus blocking Wox

### ISSUE THREAD

**Issue by matteocontrini** [Wox-launcher/Wox#219]
Hi,
I can't launch Wox because Avast Antivirus is blocking and deleting the file when I double click on it.
This should be checked and reported as false negative to Avast.

**Comment by qianlifeng** [comment]
I have report this issue to AVG. Waiting feedback.

![image](https://cloud.githubusercontent.com/assets/1725475/5473702/5c274444-8646-11e4-866c-514daa8990ce.png)

**Comment by matteocontrini** [comment]
Keep in mind that Avast != AVG
;)

**Comment by qianlifeng** [comment]
My god!!!  **Apologize**.

**Comment by bao-qian** [comment]
@qianlifeng any progress?
