### ISSUE TITLE
Wox got en error

### ISSUE THREAD

**Issue by hello-wangjj** [Wox-launcher/Wox#2190]
### Are you submitting a bug report?

yes

### Steps to reproduce

1. 安装打开Wox直接报错
    when I Install and open Wox,  I directly got en error

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 08/29/2018 10:40:05
Exception:
System.NotSupportedException: 未找到适用于完成此操作的图像处理组件。 ---> System.Runtime.InteropServices.COMException: 无法找不到组件。 (异常来自 HRESULT:0x88982F50)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   在 System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   在 System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   在 System.Windows.Media.Imaging.BitmapImage.EndInit()
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 42
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs
[2018-08-29.txt](https://github.com/Wox-launcher/Wox/files/2330494/2018-08-29.txt)

**Comment by bao-qian** [comment]
Please try new release with tons of bug fix and 100 times speedup. 
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
