### ISSUE TITLE
Writing plugins in javascript

### ISSUE THREAD

**Issue by avxkim** [Wox-launcher/Wox#2195]
Would be it possible to use javascript in order to create a plugin?

**Comment by evilchinesefood** [comment]
Did you ever get an answer for this or figure it out?

**Comment by lqzhgood** [comment]
http://doc.wox.one/en/plugin/create_plugin.html

 use JSONRPC to complete this.Using this approach, Wox will greatly improve the supported plugin types. **Almost any language** can be used to write the Wox plugin.

But, how to start ?  
Does Wox support Node ?

**Comment by roose** [comment]
No, but we have this old suggestion =) #1001

**Comment by m-x-m-e** [comment]
Hello, I found a way how to make a javascript plugin (using node.js).
I will post some code soon on this issue #2409 

EDIT: I attached some code in the other issue if someone is interested.
