### ISSUE TITLE
How to create `.wox`

### ISSUE THREAD

**Issue by Zeroto521** [Wox-launcher/Wox#2199]
Now I had written a python plugin. see -> https://github.com/Zeroto521/Wox.Plugin.Youdao
I wanted to upload to http://www.wox.one/plugin. Then I got a ERROR.
How can I create a `.wox` file?

also see this #1992

**Comment by roose** [comment]
Just make zip archive and change extension to `.wox`(plugin files only, without parent folder)

**Comment by Zeroto521** [comment]
I am trying

**Comment by Zeroto521** [comment]
well done.
