### ISSUE TITLE
"wpm" command not working

### ISSUE THREAD

**Issue by matteocontrini** [Wox-launcher/Wox#220]
The "wpm install ..." command is not working for me. The log says:

```
Date:2014-12-17 18:04:48,394 Level:ERROR Msg:Plugin Wox Plugin Management query failed: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

**Comment by qianlifeng** [comment]
Since we upgrade the getwox.com, the api changes. WPM will work on V1.1.0

**Comment by qianlifeng** [comment]
v1.1.0 is out. Please upgrade to v1.1.0. I'm closing this.

**Comment by matteocontrini** [comment]
Should I replace all the files for updating? No installer yet?

**Comment by qianlifeng** [comment]
yes, you can replace all the files. V1.2.0  will release auto upgrade.

**Comment by matteocontrini** [comment]
Thanks
