### ISSUE TITLE
how to edit item title height in the theme?

### ISSUE THREAD

**Issue by SpaceOctopus** [Wox-launcher/Wox#2203]
I seem to be able to easily edit the base.xaml  to suit my needs (I needed to change font size), and found everything I need except for what controls the BaseItemTitle line height or padding.  Not sure which I need to ensure that my larger font isn't being cut off like this:
![2018-09-10_05-17-40](https://user-images.githubusercontent.com/8183379/45297062-f60f9a80-b4b8-11e8-8e58-bdbe7196163f.png)

If you can just point me to which file and line it's in, I'm sure I can figure it out! Thanks :smile:

**Comment by bao-qian** [comment]
sorry, this is not possible at the moment.
