### ISSUE TITLE
Request - Python caching module (e.g. requests-cache)

### ISSUE THREAD

**Issue by deefrawley** [Wox-launcher/Wox#2206]
### Are you submitting a bug report?

No

Can we get a Python web caching module included with Wox, such as requests-cache, so we can use caching with plugins?

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.
