### ISSUE TITLE
Access fail error message on every windows booting

### ISSUE THREAD

**Issue by hkjin81** [Wox-launcher/Wox#2211]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Run Wox automatically on windows boot

### Wox Error Window text

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 09/17/2018 09:16:05
Exception:
mscorlib
System.IO.IOException
'C:\Users\hkjin\AppData\Roaming\Wox\Cache\Image.cache' 파일은 다른 프로세스에서 사용 중이므로 프로세스에서 액세스할 수 없습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   위치: System.IO.FileStream..ctor(String path, FileMode mode)
   위치: Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 파일 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:줄 99
   위치: Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 파일 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:줄 44
   위치: Wox.Infrastructure.Image.ImageLoader.Initialize() 파일 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:줄 37
   위치: Wox.App.<OnStartup>b__10_0() 파일 C:\projects\wox\Wox\App.xaml.cs:줄 52
   위치: Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 파일 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:줄 31
   위치: System.Windows.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cosimochellini** [comment]
the project is deprecated, try https://github.com/oliverschwendener/ueli

**Comment by roose** [comment]
@hkjin81 delete the `C:\Users\hkjin\AppData\Roaming\Wox\Cache\Image.cache` and restart Wox
