### ISSUE TITLE
建议增加切换应用功能

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2215]
现有的切换需要依赖插件设置，每次需要输入 wim ，能否提供一个版本和mac一样，当检测到软件已打开，切换到该软件而不是重新打开一份，当然如果可以的话，把这个做成一个设置更好。

Existing application switching needs to rely on plug-in settings. Every time you need to enter wim, you can provide a version like mac. When it detects that the software is open, switch to the software instead of re-opening it. Of course, if you can, please Make a setting better.

**Comment by bianyl** [comment]
同，每次wox打开又打开了新窗口，希望能像mac的alfred一样
