### ISSUE TITLE
执行【设置-插件-程序-重新索引】，无限读条

### ISSUE THREAD

**Issue by ibrucekong** [Wox-launcher/Wox#2218]
因为更新了第三方的软件，但是wox索引还是已经卸载的那个版本，想重新索引获取当前最新的软件索引。
所以执行【设置-插件-程序-重新索引】，但是却无限读条，无法完成重新索引。谢谢！

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
