### ISSUE TITLE
Proxy setting does not work

### ISSUE THREAD

**Issue by rliuyi** [Wox-launcher/Wox#2219]
1. Open Wox Settings -> Http Proxy, version: 1.3.524
2. Input Http Server, Port, Username, Password
3. Click 'Test Proxy', then show 'Proxy connection failed.'

Wox Error log: 

2018-09-21 03:52:46.6332|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.Sockets.SocketException>
2018-09-21 03:52:46.6332|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <以一种访问权限不允许的方式做了一个访问套接字的尝试。 x.x.x.x:8080>

[2018-09-21.txt](https://github.com/Wox-launcher/Wox/files/2403615/2018-09-21.txt)

**Comment by cosimochellini** [comment]
the project is dead, consider to switch to https://github.com/oliverschwendener/ueli

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
@cosimochellini this project is not dead, try new release. tons of bug fix and 100 times speedup.
