### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by baddate** [Wox-launcher/Wox#2221]
should I install everything before wox's installation?

**Comment by roose** [comment]
I think yes, in this release in desc https://github.com/Wox-launcher/Wox/releases/tag/v1.3.67
```
1. everything.exe
2. python.exe
3. wox.exe
```

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
