### ISSUE TITLE
Hex2Dec function of calculator plugin not working.

### ISSUE THREAD

**Issue by frazzyfin** [Wox-launcher/Wox#2222]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Type hex2dec(FFF) into query bar. The result is not shown at all.

**Comment by jhdxr** [comment]
the calculator has migrated to Mages, and `hex2dec` is not supported any more. you can see [here](https://github.com/FlorianRappl/Mages/blob/master/doc/functions.md) for the supported functions.
