### ISSUE TITLE
Access Windows Settings

### ISSUE THREAD

**Issue by kallebornemark** [Wox-launcher/Wox#2223]
### Are you submitting a bug report?

No.

Is it possible to access Windows Settings, such as *Bluetooth & other devices*, through Wox?

**Comment by roose** [comment]
No, but you can use `> ms-settings:bluetooth` and it will be stored in history for later use.
List of all settings urls: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app

**Comment by bao-qian** [comment]
will use https://github.com/Wox-launcher/Wox/issues/2875 to implement this feature.
please subscribe to #2875  for update.
