### ISSUE TITLE
Availability for Linux?

### ISSUE THREAD

**Issue by kgoetke** [Wox-launcher/Wox#2224]
This isn't an issue, but I'm not sure where else to put this.

I am wondering if Wox will ever become available on Linux? I love using Wox on my Windows computer, but I would really love to be able to use it on my Linux computer.

**Comment by Elvyria** [comment]
Such launchers came from Linux systems and there's already plenty of alternatives such as [Rofi](https://github.com/DaveDavenport/rofi) there's no real need in Wox at Linux system.

**Comment by kgoetke** [comment]
Yeah, but I like the feel and look of Wox.

**Comment by kvnxiao** [comment]
https://github.com/albertlauncher/albert is customizable for your look and feel.

**Comment by bao-qian** [comment]
free free to open pr.

**Comment by OleksaBaida** [comment]
@Elvyria like a user who needs to switch between OSes from time to time I feel that there is a lot of sense in such tools as cross-platforms : simplifies switching between "work" profiles on different OSes
