### ISSUE TITLE
clock add error

### ISSUE THREAD

**Issue by binghe17** [Wox-launcher/Wox#2226]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: D:\temp\WinTemp\AppData\Roaming\Wox\Logs\1.3.524\2018-09-30.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: D:\work\run\Python35-32\pythonw.exe
Everything SDK Path: D:\temp\WinTemp\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/30/2018 14:15:39
Exception:
System.TypeLoadException: 'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null' 어셈블리에서 'Wox.Infrastructure.Storage.Storage`1' 형식을 로드할 수 없습니다.
   위치: Wox.Plugin.SimpleClock.Commands.Alarm.AlarmAddCommand.CommandExecution(List`1 args)
   위치: Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) 파일 C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:줄 166
   위치: Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 파일 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:줄 146
   위치: System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   위치: System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   위치: System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   위치: System.Windows.Input.InputManager.ProcessStagingArea()
   위치: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   위치: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   위치: System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   위치: System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   위치: System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   위치: System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
