### ISSUE TITLE
Everything SDK Path: C:\Users\ThinkPad\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

### ISSUE THREAD

**Issue by shenqilzb666** [Wox-launcher/Wox#2227]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by faimin** [comment]
same error to me
```
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\admin\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/03/2018 08:41:18
Exception:
System.Security.SecurityException: 不允许所请求的注册表访问权。
   在 System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   在 Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   在 Wox.SettingWindow.StartupSet() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 77
   在 Wox.App.AutoStartup() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 92
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 80
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
失败的程序集的区域是:
MyComputer
```

**Comment by roose** [comment]
@faimin it's not error, it's just Everything SDK Path, it seems like Wox can't write autostart value when Windows loads into registry, try start Wox with admin rights

**Comment by sinisteraadi** [comment]
> try start Wox with admin rights

Doesn't help. 

> Python Path: C:\Program Files\Python35\pythonw.exe
> Everything SDK Path: C:\Users\Godfather\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
> Date: 10/10/2018 08:30:59
> Exception:
> System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at BinaryAnalysis.UnidecodeSharp.Unidecoder.Unidecode(String input)
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.ParseChromeBookmarks(String path, String source) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 51
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks(String path, String name) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 69
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks() in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 77
>    at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\Main.cs:line 26
>    at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
>    at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
>    at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
>    at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
>    at System.Windows.Application.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at BinaryAnalysis.UnidecodeSharp.Unidecoder.Unidecode(String input)
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.ParseChromeBookmarks(String path, String source) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 51
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks(String path, String name) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 69
>    at Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks() in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:line 77
>    at Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) in C:\Users\borismakogonyuk\Documents\Wox.Plugin.BrowserBookmark\source\Main.cs:line 26
>    at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
>    at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
>    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
>

**Comment by faimin** [comment]
> @faimin it's not error, it's just Everything SDK Path, it seems like Wox can't write autostart value when Windows loads into registry, try start Wox with admin rights

@roose  I try start `Wox` with `admin rights`, but it doesn't work.

**Comment by roose** [comment]
@sinisteraadi your trouble is BrowserBookmark plugin, turn off it or remove

@faimin something is blocking access to the registry, try add Wox to your antivirus exceptions list and to the firewall

**Comment by sinisteraadi** [comment]
@roose  Disabling didn't help. I had to delete the Bookmark Plugin folder. Wox is working now. 
Thanks.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
