### ISSUE TITLE
It's too large. Can we customize the size?

### ISSUE THREAD

**Issue by chaozh** [Wox-launcher/Wox#223]
It's too large for displaying simply the dark bar and a inputbox. I wonder if we can customize the box size and the place it show up.

**Comment by qianlifeng** [comment]
Yes, you can. Change the following codes in **Theme\Default.xaml** (this is the base of all theme):

```
<Setter Property="Width" Value="800" />
```

Wox will remember the place you changed. So, just drag drop the wox to anywhere, and it will show up in there next time.

**Comment by chaozh** [comment]
great! Yet it should provide a gui setting panel or something.

**Comment by qianlifeng** [comment]
It's a theme related customization, so i didn't put it in the setting panel.

**Comment by chaozh** [comment]
These settings should not be theme related maybe or theme editor should provide a gui interface.

**Comment by gblazex** [comment]
How about the height of each result row?
(cause the font size can be customized)

**Comment by bao-qian** [comment]
@galambalazs it is not possible for now.
