### ISSUE TITLE
Suggestion : search in "open" windows

### ISSUE THREAD

**Issue by cazzoo** [Wox-launcher/Wox#2230]
It's been a single day I use Wox and it seems to be really complete.
Actually, while using it, I was looking for a window that was currently open but hidden below another one. I then figure to myself if there was a way to get to this window through wox search bar but didn't found the way to do it.

If it's not actually the case, would you mind thinking adding such a feature, looking over the title of all opened windows.
Also, I think that it would be nice to do the same for active (running) applications, looking whether for displayName or FullCommandLine (see task manager about these).

Kindly regards

**Comment by roose** [comment]
Hi, if you talk about switch between open windows, may be this plugin helps you http://www.wox.one/plugin/52

**Comment by cazzoo** [comment]
That's exactly what I was looking for! Thank you for the advice :)
