### ISSUE TITLE
Color Theme Recommendation

### ISSUE THREAD

**Issue by matrix1001** [Wox-launcher/Wox#2233]
### Are you submitting a bug report?

No

## Recommend my color theme
[github: Wox-ColorTheme](https://github.com/matrix1001/Wox-ColorTheme)

Default themes are NOT attractive at all. However I figured out how to make a colorful theme and I made one for everyone.

Hope this could be somehow add to the default themes. It is really nice.

![sample1](https://user-images.githubusercontent.com/32097922/46590456-f87c0900-cae5-11e8-8d6b-d5badb165bf7.png)
![sample2](https://user-images.githubusercontent.com/32097922/46590459-fca82680-cae5-11e8-9304-5942837215cd.png)

**Comment by ghost** [comment]
how did you make it
