### ISSUE TITLE
Win+R WOX就不能用了，是什么问题，能否修复？

### ISSUE THREAD

**Issue by NMSAzulX** [Wox-launcher/Wox#2235]

**Comment by yongpz** [comment]
我也是  Windows10 1809 不知为什么

**Comment by yongpz** [comment]
> 我也是 Windows10 1809 不知为什么

哦~不，我刚刚尴尬了，我按了esc(我以为可以隐藏界面)，之后就有问题，然后启用了”失去焦点自动隐藏“，不使用esc，一切正常。

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/29190635/48847378-59cd1280-eddc-11e8-9ec3-e11797e94105.png)
我的更尴尬，Alt+Tab启动，直接变成一条竖线了，根本不能用了~~~~~~

**Comment by ghost** [comment]
图片圈偏左了，尴尬。。。

**Comment by ghost** [comment]
现在已经卸载了
