### ISSUE TITLE
软件bug还是什么，可以解释一下吗？

### ISSUE THREAD

**Issue by Skinyi** [Wox-launcher/Wox#2236]
### Are you submitting a bug report?
No

今天我在删除我的一张个人证件照片的时候，没有激活过wox却显示的“该文件已在wox中打开”，截图如下：
![snipaste_2018-10-11_10-09-23](https://user-images.githubusercontent.com/23148648/46776519-86eac780-cd3e-11e8-89f4-c7fab63057e2.png)

这让我不禁担忧了起来，我不知道这是程序bug还是什么情况，请开发团队解释一下。谢谢。

Translation:
Today when I tried to delete one of my personal photos, I failed and Windows had show a message dialog window  indicating that the file has been opened by WOX. Above screenshot make me worried about personal information leak and I don`t know that is it a bug or something else terrible. And I just need your explaination. Thanks.

**Comment by jhdxr** [comment]
你之前搜索的结果中可能包含了这张图片，然后结果中的缩略图是需要读取原始文件的。（我没有碰过那块代码以下不确定）出于性能的考虑好像没有直接释放，虽然我记得新版这块已经重构过了。

代码都是开源的你担忧的话自己去审计一遍，不放心的话用自己编译的版本。
