### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by eleanoryeung** [Wox-launcher/Wox#2237]
WOX report an error on start. (V 1.3.524)

Delete %APPDATA%\Wox\Cache and %APPDATA%\Wox\Settings won't work.

### Are you submitting a bug report?
Yes

### Steps to reproduce
1. Start WOX
2. Get Error Report

### Wox Error Window text
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: D:\Program Files\Anaconda3\pythonw.exe
Everything SDK Path: C:\Users\ASUS\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/11/2018 16:30:59
Exception:
System.AggregateException: 发生一个或多个错误。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WoxSteam.Options.Load() 位置 c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:行号 35
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 18
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 93
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 91
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (内部异常 #0) System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 WoxSteam.Options.Load() 位置 c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:行号 35
   在 WoxSteam.Main.Init(PluginInitContext context) 位置 c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 18
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 93
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

### Detailed logs
[2018-10-11.txt](https://github.com/Wox-launcher/Wox/files/2468038/2018-10-11.txt)

**Comment by roose** [comment]
Wox.Plugin.Steam plugin error, disable it and create issue here if you need this plugin: https://github.com/SkaceKamen/Wox.Plugin.Steam

**Comment by eleanoryeung** [comment]
Fixed by removing the Steam plugin. I will close the issue.
