### ISSUE TITLE
Supported version of Wox in plugin config file?

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#224]
i.e.:

``` json
{
    "ID":"ID",
    "ActionKeyword":"ak",
    "Name":"Name",
    "Description":"Description",
    "Author":"Author",
    "Version":"1.0.0",
    "Language":"python",
    "Website":"https://github.com/",
    "IcoPath":"Images\\image.png",
    "ExecuteFileName":"main.py",
    "Wox": ">= 1.1.0"
}
```

...and where dev docs???

**Comment by qianlifeng** [comment]
I moved it to http://doc.getwox.com. I'm still improving it.

**Comment by qianlifeng** [comment]
Why do you think we should add supported Wox version in plugin config file?

**Comment by roose** [comment]
e.g., on plugin install, show message: this plugin version incompatible with this wox version and may be not work right

hm. may be optional, or not need this option? )

**Comment by qianlifeng** [comment]
I think this option maybe helpful when we publish new Wox version frequently or Wox plugin getting more and more. Also I think we should encourage user to upgrade to latest Wox version (this should be easy after we implement auto-upgrade), when user upgraded to latest version, this option seems not so important. 
For now, my main work is to make Wox more stable, and build the Wox community and improve documentation.

**Comment by roose** [comment]
@qianlifeng  Ok, I agree with you)
