### ISSUE TITLE
关于使用习惯的小建议

### ISSUE THREAD

**Issue by sunshinenny** [Wox-launcher/Wox#2240]
### Tips for using habits
> When Alfred was used, a particularly convenient function was found.
> **switch to default input method when opening operation.**
#### My thoughts on the Chinese people
- For some Chinese users, the Chinese input method is the default.
- For wox, the usual operation is to start with English (for example, using keywords for search)
- if each time, the Chinese input method is used to open the wox.
- switch to Chinese or English input each time, or enter it and return to use it in English.
- operation is rather inconvenient.
- **so we hope to add default input function**
> Used translate
-----
### 关于使用习惯的小建议
> 当时使用 Alfred 的时候，发现一个特别方便的功能
> **打开操作时默认切换为指定输入法**
#### 我的思考
- 对于部分中国用户来说，中文输入法是默认的
- 对于 wox 这款软件来说，一般的操作都是以英文开头(例如使用关键词进行搜索)
- 如果每一次都是使用中文输入法打开 wox
 - 那每一次都要切换中英文输入，或者输入后砸回车使用其英文
- 操作相当不便捷。
- **故希望可以添加默认输入法功能**

**Comment by taikulawo** [comment]
思考的是对的，但`Windows`有键盘选项，允许每个独立的`app`使用不同的输入法，你只需要一次在`Wox`输入界面改成英文输入法之后，下一次会自动切换成英文

![image](https://user-images.githubusercontent.com/24750337/46904060-3d060b00-cf11-11e8-97b1-5bbc282fd953.png)

**Comment by sunshinenny** [comment]
Thanks
我自己没发现这个选项 打扰了……

**Comment by jhdxr** [comment]
感谢建议，@iamwwc 提供的方法应该可以解决你的问题了（我也是这么做的）。issue我就先关了，有新的想法再打开。

**Comment by balthild** [comment]
Windows 设置“允许我为每个每个应用窗口使用不同的输入法”之后，每个窗口的输入法都独立了。但我希望只有 Wox 使用英文输入法，其他所有窗口都保持输入法切换状态（这是来自 Alfred 的使用习惯）。所以，还是希望 Wox 可以加上类似的功能。
