### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dltmdcks98** [Wox-launcher/Wox#2243]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\dltmd\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/18/2018 15:28:00
Exception:
System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.TypeLoadException: 'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null' 어셈블리에서 'Wox.Infrastructure.Storage.Storage`1' 형식을 로드할 수 없습니다.
   위치: Wox.Plugin.Type.Main.Init(PluginInitContext context)
   위치: Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 파일 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:줄 19
   위치: Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 파일 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:줄 101
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   위치: Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 파일 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:줄 91
   위치: Wox.App.<OnStartup>b__10_0() 파일 C:\projects\wox\Wox\App.xaml.cs:줄 60
   위치: Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 파일 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:줄 31
   위치: System.Windows.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<.ctor>b__1_0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (내부 예외 #0) System.TypeLoadException: 'Wox.Infrastructure, Version=1.3.524.0, Culture=neutral, PublicKeyToken=null' 어셈블리에서 'Wox.Infrastructure.Storage.Storage`1' 형식을 로드할 수 없습니다.
   위치: Wox.Plugin.Type.Main.Init(PluginInitContext context)
   위치: Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 파일 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:줄 19
   위치: Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 파일 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:줄 101
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
[2018-10-18.txt](https://github.com/Wox-launcher/Wox/files/2490506/2018-10-18.txt)

**Comment by roose** [comment]
Try to disable\remove `Wox.Plugin.Macros` plugin

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
