### ISSUE TITLE
Can't find anything using Wox

### ISSUE THREAD

**Issue by frirwind** [Wox-launcher/Wox#2246]
Maybe this is not the correct place to post this but I didn't know of any other place to go for my question.

I come from Launchy and though I really like the application, it doesn't seem supported at all lately.

Now I try to open some files (lyrics from my band's upcoming album) so I try to search for the files by inputting their names. (IE: Martyr, Tapestries of Time) and literally everything shows up instead of those lyric files. Now, I can find the file by scrolling all the way down the list but the seems super sub-optimal.

Am I doing something wrong? Or is there a way to better optimise this process? I don't feel like trying to train the app to open the file named "martyr" by searching for it in a huge list.

I would appreciate some help/ a response very much.

Take care!

Rik

**Comment by PerryCodes** [comment]
Personally, I'm going back to Launchy.  I tried Wox due to Launchy's developer being tied down with Chrome development @ Google (good for him!).  But the fact that Launchy was written by a computer scientist with a PhD and has worked at Google for the past 6 years really shows when comparing these two applications.  Unsupported or not.

**Comment by deefrawley** [comment]
Hi Rik. What is the actual filename of the lyrics file? Do you see the same result when you do the same search in the Everything tool?

**Comment by frirwind** [comment]
The everything tool does it quite well. :)

![image](https://user-images.githubusercontent.com/44305349/47737702-c3408200-dc71-11e8-8dd8-53cd8439a9f6.png)

I guess that the fuzzy search prioritizes all the different windows tools/settings that contain the letters M-A-R-T-Y-R over the actual files that I try to find though.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
