### ISSUE TITLE
Experience when compared to Launchy

### ISSUE THREAD

**Issue by PerryCodes** [Wox-launcher/Wox#2247]
### Are you submitting a bug report?

No

### ToDo: update after more thoughtful experience can be reported

My original reply was a knee-jerk reaction to an issue I experienced without fully understanding how Wox works... I will provide a more in-depth write-up after spending more time with Wox - especially focusing on how it compares to Launchy (which is most likely what others will have experienced first)

**Comment by tsadiq** [comment]
You can right click on any results and "Set as topmost in this query".

**Comment by DragoCubed** [comment]
have you done that in-depth write-up yet?

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
