### ISSUE TITLE
系统中软件更新后，wox的索引没有更新，检索的还是之前的软件快捷键

### ISSUE THREAD

**Issue by ibrucekong** [Wox-launcher/Wox#2248]
系统中软件更新后，wox的索引没有更新，检索的还是之前的软件快捷键，点击重新索引，但是无限读条，无法成功。

**Comment by superwg1984** [comment]
我也遇到这个问题了，重新索引无限滚动

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
