### ISSUE TITLE
能否添加ALTRUN 那样自定义程序名称的列表

### ISSUE THREAD

**Issue by vividmuse** [Wox-launcher/Wox#225]
现在这样是检索程序文件名， 但是有些绿色的软件 会有重名或者并不是我想要运行的程序，比如vmware 我运行的时候也许用xnj 三个字母代替更为简便，刚开始用这个软件，不知道显示顺序能不能通过使用频率来调节？

**Comment by vividmuse** [comment]
再或者可以直接拉取altrun的配置文件 优先显示？

**Comment by qianlifeng** [comment]
待我研究一下ALTRUN。

**Comment by vividmuse** [comment]
辛苦了。

**Comment by vividmuse** [comment]
不知是否有进展？

**Comment by qianlifeng** [comment]
暂时还没做，有消息了我会在这边更新的。

**Comment by bao-qian** [comment]
你可以为这些程序建一个快捷方式文件夹，比如xnj.exe。
然后把这个文件夹加到folder plugin的索引里。
