### ISSUE TITLE
搜索wox关键字显示不准确

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2255]
![2018-11-04 03 15 03](https://user-images.githubusercontent.com/35698144/47956495-3afb0d80-dfe0-11e8-9faf-daa627c20f61.png)

我敲wox搜索，前面是可以用的，但是最后三个的结果却完全不与wox沾边，如何解决呢？？谢谢！

**Comment by roose** [comment]
no way, **WO**rdpad.e**X**e, **W**ind**O**ws fa**X**
