### ISSUE TITLE
Some way to record keywords

### ISSUE THREAD

**Issue by Zeroto521** [Wox-launcher/Wox#2258]
## Problem

As title.

So, is there some way to record keywords or operation each time?

## Trying 

I have thought to generate a plugin which it can record log.

But it not working when another plugin is working. 

`_(:з」∠)_`

**Comment by ikkz** [comment]
u can find `History.json` in wox's setting directory then your plugin can read.

**Comment by Zeroto521** [comment]
Follow your saying. I find the JSON file `C:\Users\Zero\AppData\Roaming\Wox\Settings\History.json`.

Content example
```JSON
    {
      "Query": "set",
      "ExecutedDateTime": "2018-11-07T19:53:20.0753808+08:00"
    }
```
When I key in keyword, but this file **no any change at all**.

**Comment by ikkz** [comment]
我测试了一下发现这个json文件在wox退出时会修改，在代码里也可以找到：
函数 [MainWindow.OnClosing](https://github.com/Wox-launcher/Wox/blob/master/Wox/MainWindow.xaml.cs#L47) 调用了 [MainViewModel.Save](https://github.com/Wox-launcher/Wox/blob/master/Wox/ViewModel/MainViewModel.cs#L610)，这个函数又调用了 [WoxJsonStorage<History>.Save](https://github.com/Wox-launcher/Wox/blob/13e6c5eefcc669b9abc93d84b569226afe679e9f/Wox.Infrastructure/Storage/JsonStorage.cs#L95).
所以获得上一次关闭wox之前的记录是很简单的，但是要获得最新的记录，可能需要C#的反射。

**Comment by Zeroto521** [comment]
那我想，适时候学 `C#` 了

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
query history can be retrieved via control+h
