### ISSUE TITLE
Maximum Depth Option?

### ISSUE THREAD

**Issue by mohitg11** [Wox-launcher/Wox#2259]
### Are you submitting a bug report?
No

### Question

Hi,

Thanks for the excellent app. I am unable to find the option in the Program plugin to set the Maximum Depth to search. I see there is a related commit (?): https://github.com/Wox-launcher/Wox/commit/4c5a046bc0c228c06f491b33d42eaff969dd07af.

This is what I see in the Program plugin settings, 
![image](https://user-images.githubusercontent.com/6474421/48316583-4953b580-e5ee-11e8-864a-51ac4572ce9e.png)

Thanks in advance.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

you can just index C:\Portable now.
