### ISSUE TITLE
Is Feb 24th the most recent release? I heard something about an update in October?

### ISSUE THREAD

**Issue by MostHated** [Wox-launcher/Wox#2260]
Hey there,
    I was just wondering if I missed something, I see that Is Feb 24th the most recent release. Then the commits show July 15th as the most recent changes, but I heard/saw something about an update in October I thought, but I don't see anything close to that. Am I missing something somewhere?

Thanks,
-MH

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
