### ISSUE TITLE
Feature request: run shortcut using ".\ <command>" or "run <command>" (see screenshot)

### ISSUE THREAD

**Issue by 0x6A7232** [Wox-launcher/Wox#2262]
I mean like a way to pass off command (+ any argument(s) ) to Windows run function. Say for example, 
.\ diskmgmt.msc
-OR-
run diskmgmt.msc

http://tinypic.com/r/qnmrrl/9
-OR-
http://tinypic.com/m/kbax55/4

**Comment by roose** [comment]
Like this?
![default](https://user-images.githubusercontent.com/277651/48545177-815d4000-e8ef-11e8-8155-f5a0cbc1f9e4.png)

**Comment by 0x6A7232** [comment]
Yes; but without the cmd window intermediately opening.  I think the system-side would use the "start" command (if you were in the cmd, say, it would be `start diskmgmt.msc`)

**Comment by roose** [comment]
You can set `RunCommand` in settings

![default](https://user-images.githubusercontent.com/277651/48617077-97d2cc80-e9bf-11e8-9259-75bc1157a5e3.png)

**Comment by 0x6A7232** [comment]
Ah, that's what I was looking for, I must be blind.  Thanks much!

**Comment by bao-qian** [comment]
close due to resolved.
