### ISSUE TITLE
打开时报错

### ISSUE THREAD

**Issue by sywoon** [Wox-launcher/Wox#2264]
打开时报错

Date: 11/17/2018 22:37:11
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by jindongwang** [comment]
一样的错误，很突然

**Comment by jindongwang** [comment]
完全删除，重装就好了。推测可能与最近的win10系统更新有关

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
