### ISSUE TITLE
Wox-1.3.524.exe - Installation has failed. Failed to extract installer.

### ISSUE THREAD

**Issue by d3-X-t3r** [Wox-launcher/Wox#2266]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Run Wox-1.3.524.exe as Administrator
2. Wait for error message
3. Click "Close" on error message.

### Wox Error Window text

[Window Title]
Wox-1.3.524.exe

[Main Instruction]
Installation has failed

[Content]
Failed to extract installer

[Close]

### Detailed logs

<No log file generated>

- OS: Windows 10 Enterprise x64 v1709 build 16299.726
- Able to extract Wox-1.3.524.exe using 7-zip, so download isn't corrupted
- Unable to install contained .nupkg manually either ("Install-Package : No match was found for the specified search criteria and package name")

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/1624052/48744990-80048c80-ecce-11e8-8dd8-730eb548c5d0.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
