### ISSUE TITLE
Wox RunCommand, Command 不存在报错

### ISSUE THREAD

**Issue by yanhan-dev** [Wox-launcher/Wox#2273]
### Are you submitting a bug report?

是的

1. Wox设置 -> 插件 -> 命令行 -> 替换Win+R打钩, 下拉框选RunCommand 保存并关闭
2. 按下Win+R , 输入任意Win命令行找不到的应用, 比如我输入把`CMD`错误的写成了`CDM`
3. 输入后按下回车, 即可重现错误

### Wox Error Window text

日志文件没找到

### Screenshots (optional)

(drop your screenshot here)

**Comment by yanhan-dev** [comment]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\栾凤杰\AppData\Roaming\Wox\Logs\1.3.524\2018-11-29.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\栾凤杰\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 11/29/2018 14:16:49
Exception:
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.Shell.Main.Execute(String command, Boolean runAsAdministrator) 位置 C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:行号 233
   在 Wox.Plugin.Shell.Main.<>c__DisplayClass10_0.<GetCurrentCmd>b__0(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:行号 139
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
