### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by jeroendv** [Wox-launcher/Wox#2279]
There seems to be ample activity in the issue's section of this project
and even some activity in terms of pull request.
This indicates there is desire by people to use this project.

Yet the commit history would indicate his project is no longer maintained. No new commits and nor are the PR accepted.

There are however ample forks. (i.e. 1157)  Would anyone know if this project has an actively maintained fork? or how to find it?

**Comment by jeroendv** [comment]
Duplicate of #2138

**Comment by jcklpe** [comment]
@jeroendv It does not seem to be to me. I like that wox is open source but so far it seems the only actively maintained launcher for windows is Listary which is closed source. At least I think it's being actively maintained as I've interacted a fair amount with the developer in his help forum and he says that version 6 will be coming out soon. Though I have also found comments form people saying that he has been promising version 6 for about 5 or so years now so.... who knows..?

Hain is an electron based program that has a little more development going on I think. It's not bad, but it didn't have the full feature set I wanted and it's linux version is only sorta supported.

**Comment by yo1995** [comment]
@bao-qian @jhdxr @qianlifeng Hopefully we can still see an update for this nice little tool! Or at least add more maintainer to the project so that the PRs and issues can be solved gradually.

**Comment by jhdxr** [comment]
I use Wox everyday. but it has enough feature for me, and it's also very stable on my PCs. 

To be honest I don't have enough time to look into those complicated PRs and bug reports without details, especially those crashes, high memory usages, hangs. These cases need a lot of time to reproduce and debug. So you can see what I have merged for the past serveral month are just tranlsations, which is very easy to review. 

New year is coming and I spent some of my holidays here. hopefully there will be more bugfix and some feautres in the following days. Hope you enjoy it.

**Comment by yo1995** [comment]
> I use Wox everyday. but it has enough feature for me, and it's also very stable on my PCs.
> 
> To be honest I don't have enough time to look into those complicated PRs and bug reports without details, especially those crashes, high memory usages, hangs. These cases need a lot of time to reproduce and debug. So you can see what I have merged for the past serveral month are just tranlsations, which is very easy to review.
> 
> New year is coming and I spent some of my holidays here. hopefully there will be more bugfix and some feautres in the following days. Hope you enjoy it.

Yep. Thx for reply. It also works fine on my system. The only concern is that it seems to be less plugins coming out for this nice tool. I really want Wox to prosper and gain more popularity in the upcoming future.

**Comment by jdhao** [comment]
@jcklpe , Listary 6 has finally comes to its beta stage. I have used its preview version recently. It is now stable enough to use for everyday file and web search. You can download Listary 6 beta [here](https://www.listary.com/download/beta/listary6/ListaryInstaller.exe). 

There is also a tool called [utools](https://u.tools/) which incorporates a lot of plugins, for example, file search, web search, colorplate, developer tools (unix time stamp, base64 encoding and decoding), image bed  and more. It looks promising. I don't know if it has a english version. You may give it a try.

**Comment by jcklpe** [comment]
@jdhao  Thanks!

**Comment by bao-qian** [comment]
Hi guys,

https://github.com/Wox-launcher/Wox/releases

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/82024217-016d8d00-96c2-11ea-9192-06d0a28406f6.png)

@jcklpe @jdhao @yo1995 @jeroendv @jhdxr

**Comment by yo1995** [comment]
So happy to hear this news! Can't wait to update to the latest version.

**Comment by yo1995** [comment]
@bao-qian 你好，看到目前发布的版本都是pre-release，请问是否会在未来发布稳定的release版本呢？谢谢 😃
