### ISSUE TITLE
wox启动时报错

### ISSUE THREAD

**Issue by elitezhe** [Wox-launcher/Wox#228]
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox.Infrastructure
   TargetAssembly: Wox.Infrastructure, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Infrastructure.dll
   TargetSite: Void OnAfterLoad(Wox.Infrastructure.Storage.UserSettings.UserSettingStorage)
   在 Wox.Infrastructure.Storage.UserSettings.UserSettingStorage.OnAfterLoad(UserSettingStorage storage) 位置 c:\projects\wox\Wox.Infrastructure\Storage\UserSettings\UserSettingStorage.cs:行号 170
   在 Wox.Infrastructure.Storage.BaseStorage`1.Load() 位置 c:\projects\wox\Wox.Infrastructure\Storage\BaseStorage.cs:行号 82
   在 Wox.Infrastructure.Storage.BaseStorage`1.get_Instance() 位置 c:\projects\wox\Wox.Infrastructure\Storage\BaseStorage.cs:行号 51
   在 Wox.MainWindow..ctor() 位置 c:\projects\wox\Wox\MainWindow.xaml.cs:行号 164
   在 Wox.App.OnStartup(StartupEventArgs e) 位置 c:\projects\wox\Wox\App.xaml.cs:行号 39
   在 System.Windows.Application.<.ctor>b__0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```
## Environment
- Command Line: "D:\Greensoft\Wox\Wox.exe" 
- Exception Handle: System.Windows.Application.DispatcherUnhandledException
- Timestamp: 2015-01-04T09:38:23.6187802+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.2.9200.0
- CLR Version: 2.0.50727.8009
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.5.51641
  - v4 Full 4.5.51641
  - v4.0 Client 4.0.0.0
  - v4.5.1 installed with Windows 8.1
## Assemblies - Wox.exe
- Wox, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (D:\Greensoft\Wox\Wox.exe)
- Wox.Plugin, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (D:\Greensoft\Wox\Wox.Plugin.dll)
- Wox.Infrastructure, Version=1.1.1.295, Culture=neutral, PublicKeyToken=null (D:\Greensoft\Wox\Wox.Infrastructure.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (D:\Greensoft\Wox\WindowsInput.dll)
- NHotkey, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (D:\Greensoft\Wox\NHotkey.dll)
- Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (D:\Greensoft\Wox\Newtonsoft.Json.dll)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
- PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_64\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
- PresentationFramework.resources, Version=3.0.0.0, Culture=zh-CHS, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll)
- PresentationFramework.Aero, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\PresentationFramework.Aero\3.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)
- System.ComponentModel.DataAnnotations, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\windows\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\3.5.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll)
- System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Runtime.Serialization\3.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_MSIL\System.Xml.Linq\3.5.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\windows\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll)
- mscorlib.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorlib.dll)
## Modules - Wox
- D:\Greensoft\Wox\Wox.exe (Wox, 1.1.1.295, Wox, 1.1.1.295, ), 0x0000000000C00000
- C:\windows\SYSTEM32\ntdll.dll (NT 层 DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF932180000
- C:\windows\SYSTEM32\MSCOREE.DLL (Microsoft .NET Runtime Execution Engine, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF919380000
- C:\windows\system32\KERNEL32.dll (Windows NT 基本 API 客户端 DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF92F8D0000
- C:\windows\system32\KERNELBASE.dll (Windows NT 基本 API 客户端 DLL, 6.3.9600.17238 (winblue_gdr.140723-2018), Microsoft® Windows® Operating System, 6.3.9600.17238, Microsoft Corporation), 0x00007FF92F490000
- C:\windows\system32\ADVAPI32.dll (高级 Windows 32 基本 API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF9300F0000
- C:\windows\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 7.0.9600.16384, Microsoft Corporation), 0x00007FF931A40000
- C:\windows\SYSTEM32\sechost.dll (Host for SCM/SDDL/LSA Lookup APIs, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92FA10000
- C:\windows\system32\RPCRT4.dll (远程过程调用运行时, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931EC0000
- C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll (Microsoft .NET Runtime Execution Engine, 4.0.30319.34014 built by: FX45W81RTMGDR, Microsoft® .NET Framework, 4.0.30319.34014, Microsoft Corporation), 0x00007FF9192E0000
- C:\windows\system32\SHLWAPI.dll (外壳简易实用工具库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF9316C0000
- C:\windows\SYSTEM32\combase.dll (用于 Windows 的 Microsoft COM, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931C90000
- C:\windows\system32\USER32.dll (多用户 Windows 用户 API 客户端 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931720000
- C:\windows\system32\GDI32.dll (GDI Client DLL, 6.3.9600.17246 (winblue_gdr.140801-1518), Microsoft® Windows® Operating System, 6.3.9600.17246, Microsoft Corporation), 0x00007FF92FE40000
- C:\windows\system32\IMM32.DLL (Multi-User Windows IMM32 API Client DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF931E80000
- C:\windows\system32\MSCTF.dll (MSCTF 服务器 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931B30000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF909140000
- C:\windows\WinSxS\amd64_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.8428_none_88dcdb0b2fb19957\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.8428, Microsoft® Visual Studio® 2005, 8.00.50727.8428, Microsoft Corporation), 0x0000000051500000
- C:\windows\system32\shell32.dll (Windows 外壳公用 DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF9301A0000
- C:\windows\SYSTEM32\SHCORE.dll (SHCORE, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92D9C0000
- C:\windows\SYSTEM32\profapi.dll (User Profile Basic API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92F3C0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\mscorlib\68fa7254983666f79432d89eeb11cc1e\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF908260000
- C:\windows\system32\ole32.dll (用于 Windows 的 Microsoft OLE, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF932000000
- C:\windows\SYSTEM32\kernel.appcore.dll (AppModel API Host, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92E220000
- C:\windows\SYSTEM32\CRYPTBASE.dll (Base cryptographic API DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92F300000
- C:\windows\SYSTEM32\bcryptPrimitives.dll (Windows Cryptographic Primitives Library, 6.3.9600.17120 (winblue_gdr.140509-1516), Microsoft® Windows® Operating System, 6.3.9600.17120, Microsoft Corporation), 0x00007FF92F2A0000
- C:\windows\system32\uxtheme.dll (Microsoft UxTheme 库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92E0A0000
- C:\Program Files\Listary\ListaryHook64.dll (Listary Hook, 4.22.1679.0, Listary, 4.22.1679.0, Bopsoft), 0x00007FF9195F0000
- C:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.9600.16384_none_34a8918f959016ea\COMCTL32.dll (公用控件库, 5.82 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92F7D0000
- C:\windows\SYSTEM32\OLEACC.dll (Active Accessibility Core Component, 7.2.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92C410000
- C:\Program Files (x86)\Stardock\Start8\Start8_64.dll (Start button for Windows 8, 1.4.7.0, Stardock Start8, 1.4.7.0, Stardock Software, Inc), 0x00007FF92A3C0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System\007c0b9c5683e57bf9595bba9b363d6c\System.ni.dll (.NET Framework, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF907680000
- C:\windows\assembly\NativeImages_v2.0.50727_64\WindowsBase\98f76e43d081ac5cf40f1827bf647a7f\WindowsBase.ni.dll (WindowsBase.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FF903A50000
- C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationCore\18bcf7cb9f3e612fa49f2f5ec0096c74\PresentationCore.ni.dll (PresentationCore.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FF902A80000
- C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\3ed4ddc8ad3661c133c01565e6a188d5\PresentationFramework.ni.dll (PresentationFramework.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FF901820000
- C:\windows\Microsoft.NET\Framework64\v3.0\WPF\wpfgfx_v0300.dll (wpfgfx_v0300.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x0000000050750000
- C:\windows\system32\OLEAUT32.dll (, 6.3.9600.17403, , 6.3.9600.17403, Microsoft Corporation), 0x00007FF92FD70000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Core\7632e49ddfdeab5d950716542a4a09c8\System.Core.ni.dll (.NET Framework, 3.5.30729.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.5.30729.7903, Microsoft Corporation), 0x00007FF91B030000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.7905 (win9rel.050727-7900), Microsoft® .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x00007FF9080B0000
- C:\windows\SYSTEM32\SspiCli.dll (Security Support Provider Interface, 6.3.9600.16408 (winblue_gdr.130920-1803), Microsoft® Windows® Operating System, 6.3.9600.16408, Microsoft Corporation), 0x00007FF92F270000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Remo#\ce0198a588ca8458c7e5ffd56d5696f8\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.8012 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8012, Microsoft Corporation), 0x00007FF91FA00000
- C:\windows\SYSTEM32\CRYPTSP.dll (Cryptographic Service Provider API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92EE60000
- C:\windows\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92E8A0000
- C:\windows\SYSTEM32\bcrypt.dll (Windows 加密基元库, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92EF70000
- C:\windows\system32\dwmapi.dll (Microsoft 桌面窗口管理器 API, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92D7F0000
- D:\Greensoft\Proxifier v3.21 Portable Edition Incl Keys\Proxifier PE\PrxDrvPE64.dll (Proxifier Portable Edition Network Engine x64, 3, 21, 1, 0, Proxifier Portable Edition, 3, 21, 1, 0, Initex), 0x00007FF909AE0000
- C:\windows\system32\WS2_32.dll (Windows Socket 2.0 32 位 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92FD10000
- C:\windows\system32\NSI.dll (NSI User-mode interface DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931E70000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Drawing\04032d409024366e73a773763baee00a\System.Drawing.ni.dll (.NET Framework, 2.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8007, Microsoft Corporation), 0x00007FF906C40000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Windows.Forms\5d513e5f88735d3047c0c061560f9f30\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.8008 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8008, Microsoft Corporation), 0x00007FF905BA0000
- D:\Greensoft\Wox\Wox.Plugin.dll (Wox.Plugin, 1.1.1.295, Wox.Plugin, 1.1.1.295, ), 0x000000001BF00000
- D:\Greensoft\Wox\Wox.Infrastructure.dll (Wox.Infrastructure, 1.1.1.295, Wox.Infrastructure, 1.1.1.295, ), 0x000000001C020000
- D:\Greensoft\Wox\WindowsInput.dll (WindowsInput, 1.0.4.0, WindowsInput, 1.0.4.0, michaelnoonan), 0x000000001C1A0000
- D:\Greensoft\Wox\NHotkey.dll (NHotkey, 1.1.0.0, NHotkey, 1.1.0.0, ), 0x000000001C1C0000
- C:\windows\system32\psapi.dll (Process Status Helper, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF931AF0000
- C:\windows\SYSTEM32\urlmon.dll (Win32 的 OLE32 扩展, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF927C60000
- C:\windows\SYSTEM32\iertutil.dll (Internet Explorer 的运行时实用程序, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF928100000
- C:\windows\SYSTEM32\WININET.dll (Win32 的 Internet 扩展, 11.00.9600.16384 (winblue_rtm.130821-1623), Internet Explorer, 11.00.9600.16384, Microsoft Corporation), 0x00007FF928580000
- C:\windows\SYSTEM32\USERENV.dll (Userenv, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92EBB0000
- C:\windows\SYSTEM32\WindowsCodecs.dll (Microsoft Windows Codecs Library, 6.3.9600.17483 (winblue_r5.141106-1500), Microsoft® Windows® Operating System, 6.3.9600.17483, Microsoft Corporation), 0x00007FF92D640000
- C:\windows\SYSTEM32\mscms.dll (Microsoft 颜色匹配系统 DLL, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF90A5F0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Xml\4343d7cc5b592511e2f3279aa5aabe96\System.Xml.ni.dll (.NET Framework, 2.0.50727.8009 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8009, Microsoft Corporation), 0x00007FF906E80000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Configuration\6d45d249d6ca2655353b134f7fdfec18\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8007, Microsoft Corporation), 0x00007FF907530000
- C:\windows\SYSTEM32\WindowsCodecsExt.dll (Microsoft Windows Codecs Extended Library, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF90A5A0000
- C:\windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll (PresentationFramework.Classic.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x000000001C420000
- C:\windows\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll (PresentationFramework.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft(R) .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x000000001C480000
- C:\windows\SYSTEM32\d3d9.dll (Direct3D 9 Runtime, 6.3.9600.17095 (winblue_gdr.140413-1506), Microsoft® Windows® Operating System, 6.3.9600.17095, Microsoft Corporation), 0x00007FF925390000
- C:\windows\SYSTEM32\VERSION.dll (Version Checking and File Installation Libraries, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92CE40000
- C:\windows\SYSTEM32\aticfx64.dll (aticfx64.dll, 8.17.10.1333, AMD Inc. Radeon DirectX 11 Driver, 8.17.10.1333, Advanced Micro Devices, Inc. ), 0x00007FF92CE50000
- C:\windows\SYSTEM32\atiu9p64.dll (atiu9pag.dll, 8.14.01.6413, Advanced Micro Devices, Inc PowerXpress Vista User Mode Driver, 8.14.01.6413, Advanced Micro Devices, Inc. ), 0x00007FF90A570000
- C:\windows\SYSTEM32\atiumd64.dll (atiumd64.dll, 9.14.10.01080, Advanced Micro Devices, Inc. Radeon DirectX Universal Driver, 9.14.10.01080, Advanced Micro Devices, Inc. ), 0x00007FF909D70000
- C:\windows\SYSTEM32\atiumd6a.dll (Radeon Video Acceleration Universal Driver, 8.14.10.0481, Advanced Micro Devices, Inc. Radeon Video Acceleration Universal Driver, 8.14.10.0481, Advanced Micro Devices, Inc. ), 0x0000000050CF0000
- C:\windows\SYSTEM32\POWRPROF.dll (电源配置文件帮助程序 DLL, 6.3.9600.17031 (winblue_gdr.140221-1952), Microsoft® Windows® Operating System, 6.3.9600.17031, Microsoft Corporation), 0x00007FF92EE10000
- C:\windows\assembly\NativeImages_v2.0.50727_64\PresentationFramewo#\9d6241fea5ec4249c6a282c80ae98e93\PresentationFramework.Aero.ni.dll (PresentationFramework.Aero.dll, 3.0.6920.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.0.6920.7903, Microsoft Corporation), 0x00007FF923160000
- D:\Greensoft\Wox\Newtonsoft.Json.dll (Json.NET .NET 3.5, 6.0.5.17707, Json.NET, 6.0.5.17707, Newtonsoft), 0x000000001CBC0000
- C:\windows\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\3.5.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll (System.ComponentModel.DataAnnotations.dll, 3.5.30729.7903, Microsoft® .NET Framework, 3.5.30729.7903, Microsoft Corporation), 0x000000001C650000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Runtime.Seri#\ec98cd3b8daab761b41607ff460cb8dc\System.Runtime.Serialization.ni.dll (System.Runtime.Serialization.dll, 3.0.4506.8002 (FX35W81RTMGDR.030729-8000), Microsoft® .NET Framework, 3.0.4506.8002, Microsoft Corporation), 0x00007FF919E30000
- C:\windows\assembly\GAC_MSIL\System.Xml.Linq\3.5.0.0__b77a5c561934e089\System.Xml.Linq.dll (.NET Framework, 3.5.30729.7903 built by: Win9Rel, Microsoft® .NET Framework, 3.5.30729.7903, Microsoft Corporation), 0x000000001CCA0000
- C:\windows\assembly\NativeImages_v2.0.50727_64\System.Data\8dcbb60d0c7b21a8093ed337d3d242fb\System.Data.ni.dll (.NET Framework, 2.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8007, Microsoft Corporation), 0x00007FF905340000
- C:\windows\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll (.NET Framework, 2.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® .NET Framework, 2.0.50727.8007, Microsoft Corporation), 0x00000000509E0000
- C:\windows\system32\CRYPT32.dll (加密 API32, 6.3.9600.16431 (winblue_gdr.131015-2301), Microsoft® Windows® Operating System, 6.3.9600.16431, Microsoft Corporation), 0x00007FF92F5A0000
- C:\windows\system32\MSASN1.dll (ASN.1 Runtime APIs, 6.3.9600.16384 (winblue_rtm.130821-1623), Microsoft® Windows® Operating System, 6.3.9600.16384, Microsoft Corporation), 0x00007FF92F470000
- C:\windows\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_zh-CHS_b77a5c561934e089\mscorlib.resources.dll (Microsoft 公共语言运行时类库, 2.0.50727.7905 (win9rel.050727-7900), Microsoft(R) .NET Framework, 2.0.50727.7905, Microsoft Corporation), 0x000000001CD00000
- C:\Windows\Microsoft.NET\Framework64\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.8007 (FX35W81RTMGDR.050727-8000), Microsoft® Visual Studio® 2005, 8.0.50727.8007, Microsoft Corporation), 0x00007FF91BF30000
## Threads - 13
- 3928, Running Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 1828, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 2816, Wait Highest, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 3064, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 3564, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 2164, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 4872, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 2412, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 32, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 4384, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 5204, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 6100, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390
- 552, Wait Normal, Started: 2015/1/4 9:38:23, StartAddress: 0x00007FF9321F0390

---

如上,一旦运行wox 无论是管理员模式 还是非管理员模式都会弹出这个错误信息 并且wox不工作, 我也不太看得明白.不知道这个是我电脑的问题 还是wox的问题.

**Comment by qianlifeng** [comment]
可能你把config搞坏了，把wox目录下的config目录全部删掉试试

**Comment by elitezhe** [comment]
多谢 果然好了
