### ISSUE TITLE
Wox search program plugin is very slow and consum a lot of memory

### ISSUE THREAD

**Issue by sztinyhu** [Wox-launcher/Wox#2281]
Bug: Wox was very slow, and it consumed a lot of memory over than 1500MB，
        It took more than five seconds to search the start menu program.
WOX version：1.3.524 / Win10-1809
I tried to do:  clean cache, and re-install program, or reset wox: delete %APPDATA%\Wox
but the bug existed stilly.
And open the wox setting:【Setting-Plugs-Program-Reindex】，reindex takes very quickly, less than 1 second, but search action is very slowly(more than 5 five seconds). 

Last I remove the plugin : Wox.Plugin.Program, it works fine. (Of course , I cannot execute the program over the WOX.

What's problem with the plugin? 
(btw the %appdata%wox/romaing/wox/cache/Pinyin.cache is too large about 95MB, and it was only 950K in my another computer.

Log：
[2018-12-09.txt](https://github.com/Wox-launcher/Wox/files/2660535/2018-12-09.txt)

![1](https://user-images.githubusercontent.com/7954095/49697631-e2c5b580-fbf4-11e8-9818-003912350061.PNG)
![2](https://user-images.githubusercontent.com/7954095/49697632-e2c5b580-fbf4-11e8-95a3-bb2728e004fc.PNG)
![3](https://user-images.githubusercontent.com/7954095/49697633-e2c5b580-fbf4-11e8-99c6-3d99fe73c190.PNG)

**Comment by sztinyhu** [comment]
I have reset wox: delete %APPDATA%\Wox
but the bug existed stilly.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
