### ISSUE TITLE
可以Alt + Space 显示wox，然后再按Alt + Space隐藏吗？

### ISSUE THREAD

**Issue by heelsleeh** [Wox-launcher/Wox#2282]
### Are you submitting a bug report?

(write your answer here)
不是

可以Alt + Space 显示，然后再按Alt + Space隐藏吗？

**Comment by pandaGames** [comment]
设置一下热键不就可以了吗？

**Comment by wdzhong** [comment]
好像默认就是可以再按一次快捷键隐藏啊

**Comment by heelsleeh** [comment]
> 
> 
> 设置一下热键不就可以了吗？

找了一下好像没有相关的设置。

**Comment by heelsleeh** [comment]
> 
> 
> 好像默认就是可以再按一次快捷键隐藏啊

试了一下不行，我安装的是windows server 2019, 不知道和系统有没有关系。

**Comment by yo1995** [comment]
Windows10 是再按隐藏的

**Comment by heelsleeh** [comment]
> 
> 
> Windows10 是再按隐藏的

今天全新安装了一次，现在可以正常工作了，谢谢大家的帮助。
