### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by Orion-wyc** [Wox-launcher/Wox#2284]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 12/12/2018 15:32:26
Exception:
Wox
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.MainWindow.OnContextMenusForSettingsClick(Object sender, RoutedEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 201
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
