### ISSUE TITLE
wox特殊情况下不会关闭结果窗口

### ISSUE THREAD

**Issue by magicdmer** [Wox-launcher/Wox#2285]
首先调出wox，输入测试文字 wwww， 然后按Backspace键，一个个删，删了最后一个，结果窗口会隐藏。但是如果一直按着Backspace不放，等到删完，结果窗口依旧显示了一堆结果，没有隐藏

**Comment by magicdmer** [comment]
我修复了，但是我是c#新手，所以修复的方法可能比较粗暴，所以没有pull

**Comment by jhdxr** [comment]
unable to reproduce with build 551. could you provide more details including you env info?

**Comment by magicdmer** [comment]
win 7 x64， 100% reproduce ， not only me， include some other people
I change the code ：
```
if (Results.Visbility != Visibility.Visible && list.Count > 0)
{
         Results.Visbility = Visibility.Visible;
}
```
to
```
if (Results.Visbility != Visibility.Visible && QueryText != "")
{
         Results.Visbility = Visibility.Visible;
}
```
all is ok

**Comment by magicdmer** [comment]
this is operation gif
http://imgbox.com/t3OMw1E1

**Comment by jhdxr** [comment]
已复现。应该是因为现在是每次query string变化都会去查一次，然后删的比查的快的时候就会导致删完但结果还在。
后续看看能不能在做新的查询的时候把老的的task给cancel掉

**Comment by magicdmer** [comment]
> 已复现。应该是因为现在是每次query string变化都会去查一次，然后删的比查的快的时候就会导致删完但结果还在。
> 后续看看能不能在做新的查询的时候把老的的task给cancel掉

又出现一个因为输入速度导致的问题，gif如下：
http://imgbox.com/sJs3muQT
clock是一个定时提醒的插件，当我慢慢的输入clock，一切正常，插件菜单正常列出。而当我很快输入，就出现clock菜单被其他插件（貌似是程序或者everything）干扰的情况，列表不完整，插件也无法正常工作

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
