### ISSUE TITLE
主界面显示问题

### ISSUE THREAD

**Issue by EpisodeLu** [Wox-launcher/Wox#2286]
有个这个图标显示问题![image](https://user-images.githubusercontent.com/5899460/49926554-c5476300-fef6-11e8-96b3-7c345b0ce2d2.png)

**Comment by EpisodeLu** [comment]
> 有个这个图标显示问题![image](https://user-images.githubusercontent.com/5899460/49926554-c5476300-fef6-11e8-96b3-7c345b0ce2d2.png)

重启可以恢复，但是按Win+R还是会变成这样

**Comment by bao-qian** [comment]
duplicate #962 

Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
