### ISSUE TITLE
Win8.1 64位 使用最新版Wox，无法开启启动

### ISSUE THREAD

**Issue by renyanwei** [Wox-launcher/Wox#229]
电脑装了360，但是在打勾开机启动的时候360警告已经允许了，而且关了再打开勾已经勾上了，但是重启之后还是不启动。这时候勾已经没了。

**Comment by qianlifeng** [comment]
打完勾之后看看开始菜单的启动里面有没有Wox，如果有的话说明设置成功。此时如果还不能开机启动，应该是你系统的问题，或者360又作恶了。
