### ISSUE TITLE
4K resolution support

### ISSUE THREAD

**Issue by Aotner** [Wox-launcher/Wox#2291]
Hello there,
 I've been using the launcher for 3/4 months and I am really enjoying it.
However, a few weeks ago I bought a 4K monitor and the glyphs in Wox looks blurry and low-res. 
Would you need any help in order to support this, or it is a known issue and someone is already working on it?

**Comment by jhdxr** [comment]
sorry I don't have 4K monitor so I'm not sure how it looks. could you try [the latest version (build 566)](https://ci.appveyor.com/api/buildjobs/8ka6uoec6o0kpbxg/artifacts/Output%2FPackages%2FWox-1.3.566.exe) since it include #1515 .

**Comment by DoS007** [comment]
I have an 4k monitor with 200% scaling. Everything is sharp! So you can close this.
