### ISSUE TITLE
How to set up a development environment

### ISSUE THREAD

**Issue by seekerlee** [Wox-launcher/Wox#23]
Is it possible to write some getting-started article about how to set up a development environment. This will be a significant help for people from different background including me from java.

**Comment by qianlifeng** [comment]
you can download [Microsoft Visual Studio Express 2013](http://www.visualstudio.com/zh-cn/downloads/download-visual-studio-vs#DownloadFamilies_2) (it's free).  After install, just open the WinAlfred.sln file using the visual sudio. Then press F5 to start building and run this project. If everything is OK, you should be able to see the winalfred window now.

**Comment by seekerlee** [comment]
I had VS2013 Express and checked out your project but was unable to compile. So I asked for a getting started.
If I can set up and run, I'd like to contribute an article about getting started. But I have the following error:
![qq20140131143626](https://f.cloud.github.com/assets/1234986/2048328/0f80c2ce-8a42-11e3-9b5b-c56f0ec54ec5.png)
There seems some dependency issue, after build them one by one and press F5
![2](https://f.cloud.github.com/assets/1234986/2048338/7bb3afba-8a42-11e3-8b63-8b21c62790ee.png)

Seems need to specify a project to run. Any help?

**Comment by orzFly** [comment]
Just right click on the project "Wox" in the solution explorer and set it as the Startup project.

BTW, it seems you are still using our old version. Please consider pull the repo at once because there were lots of renaming.

**Comment by seekerlee** [comment]
@orzFly after update to latest, it runs ok. Thanks.
