### ISSUE TITLE
Launching Website

### ISSUE THREAD

**Issue by HGWells2** [Wox-launcher/Wox#2300]
Hi Wox Team, 

Have just downloaded Wox Launcher and love it used to use Alfred on my Mac and this is a good replacement. 

One question I did have is that my default browser is Edge and I would like to open a website address that I use on a regular basis with a command in Wox rather than typing in the URL. Is there a simple way round this? 

Thanks!

**Comment by jhdxr** [comment]
Sorry we don't have this feature for now. PR welcome.

a workaround: using the `Hotkey` feature, you can use your favorite URL as action keywords. so when you click you hotkey, the full address will pop up, and you just need to press enter.

**Comment by florisla** [comment]
@HGWells2 if the bookmarks plugin does not support Edge, then you can work around this by creating another file to start Edge with the website as a parameter.

E.g. a `lnk` shortcut or a `bat` file.

**Comment by djordjedjukic** [comment]
I would like to contribute.
My question is, do you think is better to make separate plugin for that, or just to expand web searches plugin?
