### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#2301]
It seems `dev` branch has been seperate from `master` 4 years ago, and there are different commits for each branch, which leads to one cannot be merged into another. It also makes PR cannot re-target branch by switching branch on github. Contributors have to switch the branch locally, and re-apply their patch to open PR.

On the other hand, I didn't see any benfit to keep these two irrelevant branch at the same time. Generally after I commit to one branch I have to do switch and cherry-pick in order to make another branch up-to-date.

My suggestion is we rename current `dev` branch into `dev-legacy` or whatever you want, then create new `dev` based on latest `master`, and force push to github. New commits and PRs should go `dev` first, which can also be used for preview release, and merged into `master` later if they're proven to be stable.

**Comment by jhdxr** [comment]
@bao-qian @lances101 could you take a look at this? thx.

**Comment by jhdxr** [comment]
If there is no objection, I'll do it after I month, maybe 2019-Feb-01 or later, depending on if I have time. At the mean time, I'll use `dev-new` for my development.

**Comment by bao-qian** [comment]
we should use our own branch for future, I will use bao.

**Comment by bao-qian** [comment]
we should use our own branch for future, I will use bao.
