### ISSUE TITLE
Something I do not understand about search functioning

### ISSUE THREAD

**Issue by aborruso** [Wox-launcher/Wox#2304]
### Are you submitting a bug report?

No

---

Hi,
if I make this search (the one of the below image) the first results do not concern at all what I am looking for. The word "fattura" is not in those items.
If I scroll down I have the search Everything result.

Why I have these result? Is it a correct behavior?

Thank you

![image](https://user-images.githubusercontent.com/30607/50382108-44c3f780-0698-11e9-8370-0c933c67a93c.png)

**Comment by shimonacarvalho** [comment]
I have the same issue, and this is only on a recent install. It used to work better on my old computer. Did something change? There's always a bunch of useless results first. 

![20181226_134728-](https://user-images.githubusercontent.com/40670806/50435722-10a93a80-0915-11e9-99b5-6fc82462d146.png)

**Comment by wdzhong** [comment]
@shimonacarvalho got the exactly same top 4 results when searching for "society"

**Comment by fareloz** [comment]
@shimonacarvalho 
I am suspicious, that query results aren't sorted after plugins are queried. Therefore, results from 'control panel' plugin are first, even though they have less fuzzy priority in terms of entered query.

**Comment by aborruso** [comment]
@fareloz I do not know.

The problem for me is that I search "fattura", and that I have a lot of pdf files that have in the filename the string "fattura", and these are not first. Instead I have no sense results as first

**Comment by shimonacarvalho** [comment]
It would be nice if they had some debug mode that exposed the score.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
