### ISSUE TITLE
wpm卸载websearch(网页搜索)后怎么重新下载？

### ISSUE THREAD

**Issue by mod3021** [Wox-launcher/Wox#2306]
我在测试wpm时用uninstall卸载了自带的网页搜索，现在想重新下载找不到办法，wpm install没有，有大佬能帮一下吗

**Comment by magicdmer** [comment]
你输入  wpm install web   然后下面会显示搜索出来的列表，其中有个 simple web search，可以安装

**Comment by mod3021** [comment]
自带的网页搜索不是这个web search啊，我说的是那个g用来谷歌搜索的那个

**Comment by magicdmer** [comment]
那就是websearch啊

**Comment by magicdmer** [comment]
链接: https://pan.baidu.com/s/19y2qk4J0UGnwxU4hgJfB-Q 
提取码: 1234 
下载后拖拽到wox框框安装
