### ISSUE TITLE
关于官网插件页面的建议

### ISSUE THREAD

**Issue by magicdmer** [Wox-launcher/Wox#2308]
1. 希望能够加入排序功能，比如按照发布时间，下载量和喜欢量排序，这样能很方便找出好用的插件

2. 插件页面设计一个关联性的展示空间，作用是一些插件年久失修，但发布者几乎不再维护插件，可以让第三方修正升级后上传到这个插件的原始页面展示，而不是当成一个新的插件

**Comment by jhdxr** [comment]
please report to https://github.com/Wox-launcher/Website
