### ISSUE TITLE
Wox crash (updated error log)

### ISSUE THREAD

**Issue by Lyptik** [Wox-launcher/Wox#2310]
Received this, 
[2018-12-27.txt](https://github.com/Wox-launcher/Wox/files/2711030/2018-12-27.txt)
(https://github.com/Wox-launcher/Wox/files/2711029/2018-12-27.txt)

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\dav\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/27/2018 00:28:38
Exception:
System.ArgumentOutOfRangeException: L'index d'insertion était hors limites. Il ne doit pas être négatif et inférieur ou égal à la taille.
Nom du paramètre : index
   à System.Collections.ArrayList.Insert(Int32 index, Object value)
   à System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   à System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   à System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   à MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
