### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by MakerTim** [Wox-launcher/Wox#2315]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\Maker\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/04/2019 00:03:14
Exception:
System.AggregateException: Er zijn één of meer fouten opgetreden. ---> System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij WoxSteam.Options.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:regel 35
   bij WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:regel 60
   bij Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:regel 18
   bij Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:regel 93
   bij System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bij System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bij System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bij System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bij System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bij System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   bij System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   bij Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:regel 91
   bij Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:regel 60
   bij Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:regel 31
   bij System.Windows.Application.OnStartup(StartupEventArgs e)
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Interne uitzondering #0) System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij WoxSteam.Options.Load() in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:regel 35
   bij WoxSteam.Main.Init(PluginInitContext context) in c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:regel 60
   bij Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:regel 18
   bij Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:regel 93
   bij System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   bij System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bij System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
