### ISSUE TITLE
网页搜索：望更新缩放机制并支持svn/ico图标

### ISSUE THREAD

**Issue by ZgblKylin** [Wox-launcher/Wox#2318]
网页搜索插件现在仅支持png等固定大小的图标，经试验，在100%dpi下，48x48图标显示效果最好。

大于48x48的图片，会被强行缩小，并且缩放算法非常粗暴，导致软件内图标有严重锯齿。

而且固定大小的图片对dpi调整也不友好，在高dpi下会显得模糊。

希望：
1. 更新缩放机制，提供更清晰的缩放算法——起码效果不要比我用win10相册自带的缩放功能效果差
2. 支持ico和svg格式图标，以提供顺畅的缩放显示。

![c](https://user-images.githubusercontent.com/13114351/50703295-9bfd9b00-108e-11e9-9abb-f17e4e5c87b3.png)
![c](https://user-images.githubusercontent.com/13114351/50703306-a324a900-108e-11e9-954e-b1607e9e3ce4.png)
如图，这是缩放后和缩放前的图标，使用win10系统相册缩放功能。
若在wox中直接使用后者，缩小后的图标会带有严重的锯齿。

**Comment by jhdxr** [comment]
PR welcome, thx

**Comment by qianlifeng** [comment]
We added svg support in v2
