### ISSUE TITLE
插件安装不了

### ISSUE THREAD

**Issue by Yaocoo** [Wox-launcher/Wox#2319]
无法用 wpm install 命令安装 有道云翻译、Hosts 等插件。例如我输入 `wpm install Hosts` 后，软件会提示安装成功，并且问是否重启生效。我点了重启，但是插件列表中找不到相关插件。目前尝试的插件中只有 有道翻译（中间没有云字）安装成功了。

**Comment by David2k13** [comment]
我也是部分插件安装不了

**Comment by ShimotsukiH** [comment]
我也是部分插件安装不了

**Comment by NanerLee** [comment]
+1, 
我也出现了此问题, 版本是当前日期的最新 release

ps: 原本以为是管理员权限的问题, 但是给了权限还是不行

**Comment by MingOf** [comment]
+1

**Comment by ian-ie** [comment]
+1

**Comment by XavierFAN666** [comment]
Yes, I can't install the extensions. When I input the "wpm install package", then I put enter, it doesn't give any response though I downloaded the package of extension.
