### ISSUE TITLE
Remote desktop consistently showing up first on list

### ISSUE THREAD

**Issue by bilalbari3** [Wox-launcher/Wox#2321]
### Are you submitting a bug report?

No

I consistently get "Remote Desktop Connection" as the first result, even for very unrelated searches. Below are several examples for Settings, Slack, Steam, and Epic.  How can I go about correcting this?

![settings](https://user-images.githubusercontent.com/10054623/50912859-1ddc2400-1401-11e9-9803-02d8b47da9b2.png)

![slack](https://user-images.githubusercontent.com/10054623/50912862-20d71480-1401-11e9-9bf7-c54e28e84acb.png)

![steam](https://user-images.githubusercontent.com/10054623/50912864-23396e80-1401-11e9-8621-42cb964cd1c3.png)

![epic](https://user-images.githubusercontent.com/10054623/50912870-26ccf580-1401-11e9-803b-8d23118c9cb1.png)

**Comment by akamyshanov** [comment]
The text you (and I too) see is the comment of a shortcut, probably Wox searches that too.

# Workaround
1. Locate the "Remote Desktop Connection" shortcut file from the start menu which typically should be at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Remote Desktop Connection.lnk`
2. Open it's properties properties (`alt+enter` or Mouse right click → Properties)
3. Erase everything from the Comment field
4. OK, confirm
5. Restart Wox

**Comment by bilalbari3** [comment]
Thank you!

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
