### ISSUE TITLE
Wox cannot switch between different virtual desktop automatically

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#2327]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. switch to any virtual desktop, let's asy, it's now on desktop 2.
2. using hot key to call wox 
3. keep wox open, and use hot key to switch any desktop other than desktop 2. and use hot key to call wox again
4. it switch back to desktop 2, instead of showing up on the desktop I'm currently working on.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by magicdmer** [comment]
you maybe set remember positon in setting, it will cause this question
