### ISSUE TITLE
Python plugin encoding

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#233]
Now, encoding is `gb2312`, but i use `cp1251`. Need detect system encoding or use https://pypi.python.org/pypi/chardet please

``` python
# ...
import chardet
# ...
rpc_request = json.loads(sys.argv[1],encoding=chardet.detect(sys.argv[1])["encoding"])
# ...
```

work for me on cyrillic and chinese, test please on you system

**Comment by qianlifeng** [comment]
I have tested chinese and english, it's ok, and I pushed those changes to v1.2.0
