### ISSUE TITLE
Use external library in plugin

### ISSUE THREAD

**Issue by czhang03** [Wox-launcher/Wox#2335]
### Are you submitting a bug report?
NO

------------
When developing a plugin, use of external library can be a great help. For example, I am trying to develop a calendar plugin, [ics.py](https://github.com/C4ptainCrunch/ics.py) will be great help for creating a calendar event.

I was wondering if there is anyway to install external library when installing a python plugin, maybe a `requirement.txt` file to specify the external library required by the plugin, and install them when installing the plugin.

**Comment by magicdmer** [comment]
it's a good idea, maybe i can get it in my repo

**Comment by bao-qian** [comment]
bundle it in your plugin, and change your import search path.
