### ISSUE TITLE
搜索过程中崩溃

### ISSUE THREAD

**Issue by epluguo** [Wox-launcher/Wox#2339]
印象中是输入了camb 。其中camb是我自己定义的一个翻译网站。这是个偶现bug，第一次出现
![snipaste_2019-01-24_14-43-48](https://user-images.githubusercontent.com/6416516/51659744-7fe27f00-1fe6-11e9-917d-075b13409d92.png)

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\hopli\AppData\Roaming\Wox\Logs\1.3.524\2019-01-24.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\hopli\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/24/2019 14:39:22
Exception:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

下面是日志附件：
[2019-01-24.txt](https://github.com/Wox-launcher/Wox/files/2790473/2019-01-24.txt)

**Comment by epluguo** [comment]
版本是 1.3.524

**Comment by magicdmer** [comment]
官方版本的搜索是不支持直接当网页快捷方式用的，你必须加上{q} 搜索关键字

**Comment by epluguo** [comment]
> 官方版本的搜索是不支持直接当网页快捷方式用的，你必须加上{q} 搜索关键字

截图里显示不详细，被截断了，实际上配置的网址是：
https://dictionary.cambridge.org/dictionary/english-chinese-simplified/{q}

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
