### ISSUE TITLE
Exception: Calling thread cannot access this object because a different thread owns it

### ISSUE THREAD

**Issue by enzy** [Wox-launcher/Wox#234]
Error log: https://gist.github.com/enzy/2bf4bff2741ba808898b

This happen every time Wox start.

Wox 1.1.1
Win 8.1 x64 (and also in Windows 10 preview build)

**Comment by qianlifeng** [comment]
Strange, I tested on Win8.1 and didn't has this error.

**Comment by bao-qian** [comment]
try [v1.2beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)

**Comment by enzy** [comment]
I'm on 1.2 beta for some time and haven't encounter this bug yet. Thanks
