### ISSUE TITLE
wox setup error

### ISSUE THREAD

**Issue by wyufeng** [Wox-launcher/Wox#2345]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.下载 Wox-1.3.578 
2.使用VS 2015编译
3.运行 wox.exe
4.使用VS2015 debug 可以正常运行
期间修复了一处编译错误。
![image](https://user-images.githubusercontent.com/6323501/51877345-d533dd00-23a6-11e9-94be-aa7aed701402.png)

### Wox Error Window text

Wox version: 1.2.0
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 01/29/2019 09:13:39
Exception:
System.TypeInitializationException: “ChineseToPinyinResourceHolder”的类型初始值设定项引发异常。 ---> System.AggregateException: 发生一个或多个错误。 ---> System.IndexOutOfRangeException: 索引超出了数组界限。
   在 hyjiacan.util.p4n.ChineseToPinyinResource.<>c.<initializeResource>b__4_2(String[] l)
   在 System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   在 System.Linq.ParallelEnumerable.ToDictionary[TSource,TKey,TElement](ParallelQuery`1 source, Func`2 keySelector, Func`2 elementSelector)
   在 hyjiacan.util.p4n.ChineseToPinyinResource.initializeResource()
   在 hyjiacan.util.p4n.ChineseToPinyinResource..ctor()
   在 hyjiacan.util.p4n.ChineseToPinyinResource.ChineseToPinyinResourceHolder..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 hyjiacan.util.p4n.ChineseToPinyinResource.getInstance()
   在 hyjiacan.util.p4n.PinyinHelper.getUnformattedHanyuPinyinStringArray(Char ch)
   在 hyjiacan.util.p4n.PinyinHelper.getFormattedHanyuPinyinStringArray(Char ch, HanyuPinyinOutputFormat outputFormat)
   在 hyjiacan.util.p4n.PinyinHelper.toHanyuPinyinStringArray(Char ch, HanyuPinyinOutputFormat outputFormat)
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 D:\test\Wox-1.3.578\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 Wox.Infrastructure.Alphabet.Initialize() 位置 D:\test\Wox-1.3.578\Wox.Infrastructure\Alphabet.cs:行号 29
   在 Wox.App.<OnStartup>b__10_0() 位置 D:\test\Wox-1.3.578\Wox\App.xaml.cs:行号 54
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 D:\test\Wox-1.3.578\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2019-01-29.txt](https://github.com/Wox-launcher/Wox/files/2805636/2019-01-29.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
try master version which use vs2019
