### ISSUE TITLE
Calculator Rounding Errors

### ISSUE THREAD

**Issue by fudgelabs** [Wox-launcher/Wox#2349]
Hi There,

Just had some issues with the calculator that I thought I'd let you know about.

I am running the latest version, 1.3.578

Regarding the calculator, performing 101.685 - 101.385 gives 0.299999999999997
OR
Performing 101.67 - 101.85 gives -0.180000000000007

Thanks!

### Screenshots

![image](https://user-images.githubusercontent.com/6769759/52024884-89279a80-2556-11e9-8fa8-52867362ba0f.png)

**Comment by magicdmer** [comment]
It maybe caused by Mages library (https://github.com/FlorianRappl/Mages) , because this plugin use Mages to calculate it

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
