### ISSUE TITLE
A possible fix for Issue 2304 (control panel searching feature not working properly)

### ISSUE THREAD

**Issue by pc223** [Wox-launcher/Wox#2352]
I think I found the reason why the control panel searching feature not working properly (relate to [issue 2304](https://github.com/Wox-launcher/Wox/issues/2304)) in [release v1.3.524](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.524), a little exclamation mark! :smile: 

The commit I think made this happen: https://github.com/Wox-launcher/Wox/commit/870ad008bf700e45aec6a71ae8df4258759234de

![52274024-1404fc80-297e-11e9-9e0e-2ea306076324](https://user-images.githubusercontent.com/10551242/52274213-8ece1780-297e-11e9-8328-9b473139d539.png)

**For who trying to find a quick fix: install [release v1.3.183](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183)**

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by pc223** [comment]
Seems OK now for v1.4.1129 :smile:
