### ISSUE TITLE
Opening Windows system menu

### ISSUE THREAD

**Issue by stuartisaac** [Wox-launcher/Wox#2353]
### Are you submitting a bug report?

No

I'm interested in knowing if there's a way to invoke the system menu (what would usually be opened by Alt+Spacebar if Wox were not using it) in order to be able to have easy keyboard access to window Move/Size commands. I've tried using other hotkeys to invoke Wox, but nothing works as well as Alt+Spacebar. If there were a way through Wox to open the system menu for the front-most window, that would be ideal.

**Comment by bao-qian** [comment]
could you give some ui mockup for your suggestion, I cannot understand.
