### ISSUE TITLE
Multi Monitor Setup Troubles. 1.3.578

### ISSUE THREAD

**Issue by Hawaiiankaikai** [Wox-launcher/Wox#2354]
**First off**, besides this problem the app works Great! To give you a visual, I have a quad monitor setup; 3 in a row and 1 above my middle monitor. I usually keep my Wox Box in my middle screen. But I'm having two issues/problems with the placement of the Wox box/bar.

**1st.)**  When I start my computer up from boot or wake it from sleep. The Wox box seems to open in the screen where I have my cursor. It took longer than I care to admit to figure that out. That being said, more often or not my cursor is on a different screen(not my middle main display) when I press my hotkey. Then I have to deal with it being on the wrong screen. _My hotfix to this problem_ is to exit Wox, open the app again, and press the hotkey with the cursor in the middle monitor. Which means to prevent this from happening, when I turn on my PC; is to press the hotkey with the cursor in the middle before I do anything.

**2nd.)** My Wox Box jumps to another screen whenever I play certain games in fullscreen. Its happen to me playing ARK and LOL a few times. But it usually happens with older games that have funky resolutions  (Ex. Command and Conquer Generals, emulators in fullscreen). It would just change Wox box to a screen that doesn't have the game on it. 

My **Solution/Suggestion** to these problems is to add a setting to allow Wox to choose a screen that it will always show up on. You know in the windows display settings it says (Make this my main display). Give us the ability to set it to the main display only. I don't want to keep having to close the app and reopen it.

Really curious to know if this happens to anyone else. Open to any and all tips, solutions, & suggestions.
**Thank you**

**Comment by Streyder** [comment]
Any update on this? It would be awesome if Wox could be "contained" into a single Screen.  This would also make Wox show up in the same place every time. This way I could also disable "Ignore hotkeys in fullscreen mode" and using wox while gaming would become viable.

**Comment by Lomacar** [comment]
Since updating Wox, it now only opens on one monitor. As Hawaiiankaikai describes, it first opens on whichever screen has the cursor and after that it keeps opening on that screen. It used to always open on whichever screen had the cursor, which is what I expect and want. Was this a deliberate change or a bug?

Regardless, it sounds like people want options for this, I thought for sure there already was an option but I guess not.
