### ISSUE TITLE
windows 10 怎么打开回收站

### ISSUE THREAD

**Issue by dbshao** [Wox-launcher/Wox#2355]
我搜索回收站没有任何反应

**Comment by lqzhgood** [comment]
你可以创建一个 回收站的快捷方式。
然后放到某个目录
wox 插件 程序 里面添加这个目录
然后输快捷方式的文件名就可以找到了。

**Comment by Flashkong** [comment]
@lqzhgood 有效，谢谢

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
