### ISSUE TITLE
Python Path error

### ISSUE THREAD

**Issue by Erik-Martus** [Wox-launcher/Wox#2357]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

[2019-02-12.txt](https://github.com/Wox-launcher/Wox/files/2858150/2019-02-12.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by lqzhgood** [comment]
Install Python in here
https://www.python.org/downloads/

Set Python dir in Wox Setting.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
