### ISSUE TITLE
Upgrade Wox to .net framework 4.5?

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#236]
Since I'm implementing Auto upgrade function. I noticed [quirrel.Windows](https://github.com/Squirrel/Squirrel.Windows), which sounds a good choice. Atom uses this to upgrade itself. But this library needs .net framework 4.5, and Wox is now targeting to .net framework 3.5.  

.net framework is installed in win8 by default. So for win8 users, it's not a problem if Wox upgrading to .net framework 4.5. But for win7 users, they may need to install .net framework 4.5 (quirrel.Windows will auto install .net framework 4.5 if it find user didn't install that).  

I don't know how many Wox users still use windows 7 (or didn't install 4.5 in windows 7)? So, I'm not sure if we should upgrade Wox to .net framework 4.5, or should we find another auto upgrade solution.

**Comment by roose** [comment]
I think need add something like Google Analytics to Wox for collect statistic, and on the basis of this information take decide about switch to .net framework 4.5.

**Comment by qianlifeng** [comment]
That's fair.

**Comment by blastdan** [comment]
I know that .net 4.5 would help with plugin development, at least for what I am doing with the chocolatey plugin.
It should however be fueled by customer adoption and adding a way to send machine metrics back for collection is probably the best thing to do in the short term.
