### ISSUE TITLE
Theme font change updates both types of font whenever one is changed

### ISSUE THREAD

**Issue by Duckapple** [Wox-launcher/Wox#2363]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Go to Wox Settings
2. Go to Themes
3. Choose either of the "Query box" or "Result item" fonts to change
4. Change the font to something else

Result: The other font also changes.

### Detailed logs

[2019-02-20.txt](https://github.com/Wox-launcher/Wox/files/2884416/2019-02-20.txt)

**Comment by sausagemountain** [comment]
still not fixed for me 😞, on the latest release

**Comment by bao-qian** [comment]
@sausagemountain @Duckapple 
try new build

https://ci.appveyor.com/project/bao-qian/wox/builds/32384756
