### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sipulinte** [Wox-launcher/Wox#2365]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.每次打开都会弹出对话框，功能无法正常使用
1.The dialog box pops up every time it opens. The function is not working properly.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
