### ISSUE TITLE
dunno what u want here dude

### ISSUE THREAD

**Issue by rzbk71** [Wox-launcher/Wox#2371]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\topha\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/23/2019 15:18:45
Exception:
System.Windows.Media.Animation.AnimationException: Impossible d'animer la propriété sur un(e) 'X2' d'un(e) 'System.Windows.Shapes.Line' à l'aide d'un(e) 'System.Windows.Media.Animation.DoubleAnimation'. Pour plus d'informations, consultez l'exception interne. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   à System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   à System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   à System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   à System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   à System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   à System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   à System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   à System.Windows.Media.Animation.TimeManager.Tick()
   à System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   à System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
