### ISSUE TITLE
Wox got an error  when input "github"  to search

### ISSUE THREAD

**Issue by miaobingyi** [Wox-launcher/Wox#2373]
### Are you submitting a bug report?

(write your answer here)
Yes

### Steps to reproduce

1.Alt + Space  to start Wox
2.input "github" and Space 
3.The Error occours

### Wox Error Window text

Wox version: 1.3.524
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/24/2019 13:41:54
Exception:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2019-02-24.txt](https://github.com/Wox-launcher/Wox/files/2897613/2019-02-24.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
