### ISSUE TITLE
Wox Error Report

### ISSUE THREAD

**Issue by ashrafulrabbi** [Wox-launcher/Wox#2374]
### Are you submitting a bug report?

yes

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

[2019-02-24.txt](https://github.com/Wox-launcher/Wox/files/2897676/2019-02-24.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
