### ISSUE TITLE
Reopening after a right click dialogue reopens the right click dialogue instead of normal search

### ISSUE THREAD

**Issue by Lachstah** [Wox-launcher/Wox#2375]
After right clicking on an item and closing wox, reopening wox then opens the same right click dialogue instead of going to the general search menu. Anyway to have it open the normal search?

**Comment by Lomacar** [comment]
A better UX would be to have right-click open a typical floating menu, rather than affecting the search result list. 

Also, the right-click menu should have more common useful functions, and it should have a submenu which has the full windows shell menu for that file type.
