### ISSUE TITLE
Build error after Fork 

### ISSUE THREAD

**Issue by rqxtrash** [Wox-launcher/Wox#2379]
Hello,I justnow try to view the code after fork and clone,but vs contruction throw many error such as WPF not supported Window Lable,Binding,KeyBinding and so on with Wox Project.
Can’t find namespace "Package","PackageManager" with Wox.Plugin.Program.
Every quote in Wox and Wox.Plugin.Program are not error.
Could you tell me the Python Enviroment is necessary?thanks.

**Comment by bao-qian** [comment]
please try new master version, which use vs 2019.
