### ISSUE TITLE
Support more hotkey modifiers

### ISSUE THREAD

**Issue by ipy** [Wox-launcher/Wox#238]
<kbd>Alt+Space</kbd> conflicts with the Windows system hotkey, so I have to switch to another hotkey combination. However, many of my preferred combinations can not be set, like <kbd>Alt+Alt</kbd>(press Alt twice quickly), <kbd>Win+w</kbd>, <kbd>Alt+F1</kbd>.
Is it possible to support ~~Win key~~ and Fn keys? Since they are used a lot as hotkey modifiers.

UPDATE: Sorry, after testing again, Win key is supported (system hotkeys like <kbd>Win+w</kbd> are not supported).

**Comment by qianlifeng** [comment]
Which system program already token <kbd>Alt+Space</kbd>?. I'm going to support more keys, such as F1-F12, so user can use <kbd>Alt+F1</kbd> or just one <kbd>F1</kbd> as hotkey. But for <kbd>Alt+Alt</kbd>, it's something different from the existing hotkeys. I will investigate to see if we can implement that easily.

**Comment by qianlifeng** [comment]
by the way, we will not allow setting system wide hotkeys like <kbd>Win+w</kbd> (in win8) as Wox hotkey.

**Comment by ipy** [comment]
I use this menu frequently:
![image](https://cloud.githubusercontent.com/assets/2088040/5810714/c5286a00-a085-11e4-87ff-8d726c4aecf6.png)

**Comment by qianlifeng** [comment]
I remembered now. I didn't use that frequently. In this case, you can only change default wox hotkey.

**Comment by LazerPanther** [comment]
https://gist.github.com/LazerPanther/b17dd2487407f09e9578

###Wox Launcher Via `CapsLock`

```
#NoEnv
SendMode Input
#SingleInstance, Force
#Persistent

;  disable CapsLock cmd via [CapsLock]
SetCapsLockState, AlwaysOff

;  [Win]+[CapsLock] --> Activate CapsLock
#vk14::
If GetKeyState("vk14", "T") = 1
    SetCapsLockState, AlwaysOff
Else
    SetCapsLockState, AlwaysOn
Return

;  On [CapsLock] key press/release --> trigger Wox launcher through [Alt]+[Space] 
vk14::SendInput {Alt Down}{Space Down}
vk14 up::SendInput {Alt Up}{Space Up}
```

###Wox Launcher Via `Alt+F1` or `Win+w`

```
#NoEnv
SendMode Input
#SingleInstance, Force
#Persistent

;  On [Alt]+[F1], [Win]+[w] key press/release -> trigger Wox launcher through [Alt]+[Space]
!vk70::SendInput {Alt Down}{Space Down}
!vk70 up::SendInput {Alt Up}{Space Up}
#vk57::SendInput {Alt Down}{Space Down}
#vk57 up::SendInput {Alt Up}{Space Up}
```

###Use all of the above keybindings: `CapsLock`, `Alt+F1`, `Win+w`

```
#NoEnv
SendMode Input
#SingleInstance, Force
#Persistent

;  disable [CapsLock]
SetCapsLockState, AlwaysOff

;  [Win]+[CapsLock] -> Activate CapsLock
#vk14::
If GetKeyState("vk14", "T") = 1
    SetCapsLockState, AlwaysOff
Else
    SetCapsLockState, AlwaysOn
Return

;  On [Alt]+[F1], [Win]+[w] key press/release -> trigger Wox launcher through [Alt]+[Space]
!vk70::SendInput {Alt Down}{Space Down}
!vk70 up::SendInput {Alt Up}{Space Up}
#vk57::SendInput {Alt Down}{Space Down}
#vk57 up::SendInput {Alt Up}{Space Up}

;  On CapsLock key press/release -> trigger Wox launcher through [Alt]+[Space]
vk14::SendInput {Alt Down}{Space Down}
vk14 up::SendInput {Alt Up}{Space Up}
```

**Comment by qianlifeng** [comment]
Another [AHK](http://www.autohotkey.com/) script to use double shift  as the Wox hotkey :smile: 

```
~Shift::
if (A_PriorHotKey = "~Shift" AND A_TimeSincePriorHotkey < 400)
{
   Run, d:\Wox\Wox.exe toggle
}
Sleep 0
KeyWait Shift
return
```

**Comment by arieljannai** [comment]
Hi,

I just wanted to open an issue to ask about the Alt + Space which overrides the windows little menu, and then I saw it already exist :stuck_out_tongue_closed_eyes:
I wanted to suggest Alt + Z instead, it's located close to the Alt + Space combination, and pretty easy to use!
For my opinion, it's better not to override the Alt + Space by default.

What do you think about that?

Thanks,
Ariel.

**Comment by vovkkk** [comment]
What about other hotkeys?
Specifically, for context menu, I’d prefer <kbd>→</kbd> & <kbd>←</kbd> rather than <kbd>shift+enter</kbd> & <kbd>esc</kbd> — sure, it will conflict with moving cursor, but for me it’s not a problem.
Other suggestion would be <kbd>tab</kbd> instead of <kbd>shift+enter</kbd> & <kbd>esc</kbd>, i.e. one key would toggle context menu, currently (1.1.1) <kbd>tab</kbd> equal to <kbd>↓</kbd>.

Ideally, ofc, these keys could be customisable.

**Comment by arieljannai** [comment]
:+1: 
For the customizable  keyboard shortcuts :sunglasses:

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
@ipy 
these are supported in 1.3.102
<kbd>Win+w</kbd>, <kbd>Alt+F1</kbd>
@arieljannai <kbd>Alt+Z</kbd> is supported in 1.3.102

**Comment by frogdesk** [comment]
Windows key isn't working for me. Any time I try to set it to Win + Space, it changes to Win + LWin (it does this if I use any other key as well). And this behaves weirdly, it flashes on and off any time I press Win, but will stay if I press win and another key.

**Comment by Ciantic** [comment]
It's much better advice to use AutoHotkey, adding more flexible shortcut system is difficult problem, that's why AutoHotkey was made. It is must have for everyone anyway, and it can remap pretty much every system keyboard shortcut, and it uses just few megs of memory.

I suggest you add a note below the system shortcut that use AutoHotkey if one needs more than this currently provides.
