### ISSUE TITLE
Wox Presentation Abnormal (update)

### ISSUE THREAD

**Issue by AkiraX2** [Wox-launcher/Wox#2382]
### Steps to reproduce
1. Windows 10 (1803 17134.590).
2. ultra widescreen 2560*1080.
3. Long time using computer, during which there are several times of System Sleep.

 

### Detailed logs
 
[2019-02-28.txt](https://github.com/Wox-launcher/Wox/files/2913347/2019-02-28.txt)
 

### Screenshots
![snipaste_2019-02-28_12-00-12](https://user-images.githubusercontent.com/4423796/53540426-6fc33f80-3b50-11e9-82f2-75cc3fc277d1.png)

**Comment by AkiraX2** [comment]
I know how to reproduce this bug now.

Try `Call Sleep in wox`.

**Comment by pc223** [comment]
Me too! After sleep (by Wox command not native of windows), and log in again, Wox becomes a small line, normal laptop screen, windows 8, although not everytime it's like that

**Comment by bao-qian** [comment]
duplicate #962
