### ISSUE TITLE
有关wox启动cmd的问题

### ISSUE THREAD

**Issue by muyuuuu** [Wox-launcher/Wox#2387]
### Are you submitting a bug report?

是的

### Steps to reproduce

1. 首先启动wox，一切正常。
2. 然后，在任意界面输入win+R，启动cmd
![image](https://user-images.githubusercontent.com/43681138/53787953-501a8580-3f5b-11e9-9d73-7dc6d7c8a90d.png)

3. 然后bug出现了，启动wox得到的cmd和不启动wox直接win+R得到的cmd结果是不一眼的。右图为wox得到的cmd，左图为从电脑直接打开的cmd。
![image](https://user-images.githubusercontent.com/43681138/53788022-82c47e00-3f5b-11e9-989b-4c135aa8d992.png)

可能不是很符合你们的提交要求，但这的确是一个BUG，希望能认真检查一下。

**Comment by jhdxr** [comment]
sounds similar to #295
