### ISSUE TITLE
exclude keywords from the list

### ISSUE THREAD

**Issue by cloudhan** [Wox-launcher/Wox#239]
I think the ability of excluding keywords like 'Uninstall' or the like from appearing on the candidate list should be added
it will make the list cleaner and prevent mis-select

**Comment by qianlifeng** [comment]
Wox will remember what programs you selected, so if you select specified program very frequently. Wox will put it in the top of the candidates.

**Comment by bao-qian** [comment]
As @qianlifeng said, we can increase the weight of last selected programs.

**Comment by bao-qian** [comment]
hi @cloudhan 
this feature has been implemented in https://github.com/Wox-launcher/Wox/pull/800
try the new build
https://ci.appveyor.com/project/bao-qian/wox/builds/32331680/artifacts
