### ISSUE TITLE
Display item number in results for hotkey {Alt + itemNuber}

### ISSUE THREAD

**Issue by VVinRar** [Wox-launcher/Wox#2398]
I want see numbers (like in Alfred) in results for hotkey  {Alt + itemNuber}
Is any way to do this in Wox?? Discover themes (.xaml files) and found:
`

    <Style x:Key="BaseItemNumberStyle" TargetType="{x:Type TextBlock}">

        <Setter Property="Margin" Value="3 0 0 0" />

        <Setter Property="FontSize" Value="22" />

    </Style>
`
Try to add any properties but Wox just ignores that, item numbers don't appear!!!!

**Comment by bao-qian** [comment]
duplicate https://github.com/Wox-launcher/Wox/issues/2398
