### ISSUE TITLE
Can Wox display item numbers in result for hotkey {Alt + Number}?

### ISSUE THREAD

**Issue by VVinRar** [Wox-launcher/Wox#2399]
Can Wox display item numbers in result for hotkey {Alt + Number} like in Alfred??
Discover in theme .xaml files this:
`    <Style x:Key="BaseItemNumberStyle" TargetType="{x:Type TextBlock}">
        <Setter Property="Margin" Value="3 0 0 0" />
        <Setter Property="FontSize" Value="22" />
    </Style>`
Trying add properties but Wox just ignores this, item numbers don't appear.

**Comment by Cdddo** [comment]
Displaying numbers for the search results and having a hotkey to select would be a nice addition that I also miss from Alfred.
