### ISSUE TITLE
Default to the most popular results, also with a short or missing search query

### ISSUE THREAD

**Issue by wolph** [Wox-launcher/Wox#240]
Most of the times I'll start the same few applications so it would be great if Wox would just default to the appications used most often.

Right now it seems that Wox only starts searching after you've entered 2 characters, while "s" always means "settings" for me. And "v" will mean "vnc viewer" 90% of the time. Having a learning system without a minimum amount of characters would help a lot.

**Comment by qianlifeng** [comment]
a learning system without a minimum amount of characters will be available in v1.2.0

**Comment by wolph** [comment]
Fantastic, thank you.

**Comment by atahrijouti** [comment]
@qianlifeng is this feature implemented now ?
