### ISSUE TITLE
Wox.Plugin.Color not show color #90828282

### ISSUE THREAD

**Issue by hamerstandr** [Wox-launcher/Wox#2400]
Wox.Plugin.Color>main.cs
function IsAvailable >
 private bool IsAvailable(string query)
        {
            // todo: rgb, names
            var length = query.Length - 1; // minus `#` sign
            return query.StartsWith("#") && (length == 3 || length == 6);
        }

**Comment by JesperDramsch** [comment]
Hex codes either contain 3 or 6 numbers. #90828282 is not a valid Hex code and therefore should not be shown.s

**Comment by hamerstandr** [comment]
This code( #90828282 ) is displayed, the two digits are initially alpha color!
A=90,R=82,G=82,B=82

**Comment by hamerstandr** [comment]
in sub titls file and players The code is success!

**Comment by bao-qian** [comment]
please open pr for code enhancement.
