### ISSUE TITLE
Clipboard operation failed

### ISSUE THREAD

**Issue by rickywu** [Wox-launcher/Wox#2401]
所请求的剪贴板操作失败。

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Runtime.InteropServices.ExternalException (0x800401D0): 所请求的剪贴板操作失败。
   在 System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   在 System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   在 System.Windows.Forms.Clipboard.GetDataObject()
   在 Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   在 Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Wox
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Wox.exe
----------------------------------------
PresentationFramework
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.7.3353.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Runtime.Remoting
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationFramework.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
Wox.Infrastructure
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Wox.Infrastructure.DLL
----------------------------------------
Wox.Plugin
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Wox.Plugin.DLL
----------------------------------------
Wox.Core
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Wox.Core.DLL
----------------------------------------
NLog
    程序集版本:4.0.0.0
    Win32 版本:4.2.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/NLog.DLL
----------------------------------------
System.ServiceModel
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.7.3260.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Pinyin4Net
    程序集版本:2016.4.24.0
    Win32 版本:1.0.2.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Pinyin4Net.DLL
----------------------------------------
Newtonsoft.Json
    程序集版本:9.0.0.0
    Win32 版本:9.0.1.19813
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Wox.Plugin.Caculator
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Caculator/Wox.Plugin.Caculator.dll
----------------------------------------
Mages.Core
    程序集版本:1.5.0.0
    Win32 版本:1.5.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Caculator/Mages.Core.DLL
----------------------------------------
Wox.Plugin.Color
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Color/Wox.Plugin.Color.dll
----------------------------------------
Wox.Plugin.ControlPanel
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.ControlPanel/Wox.Plugin.ControlPanel.dll
----------------------------------------
Wox.Plugin.Everything
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Everything/Wox.Plugin.Everything.dll
----------------------------------------
Wox.Plugin.Folder
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Folder/Wox.Plugin.Folder.dll
----------------------------------------
Wox.Plugin.PluginIndicator
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.PluginIndicator/Wox.Plugin.PluginIndicator.dll
----------------------------------------
Wox.Plugin.PluginManagement
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.PluginManagement/Wox.Plugin.PluginManagement.dll
----------------------------------------
Wox.Plugin.Program
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Program/Wox.Plugin.Program.dll
----------------------------------------
Windows.ApplicationModel
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/Windows/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Wox.Plugin.Shell
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Shell/Wox.Plugin.Shell.dll
----------------------------------------
Windows.Management
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/Windows/system32/WinMetadata/Windows.Management.winmd
----------------------------------------
WindowsInput
    程序集版本:1.0.4.0
    Win32 版本:1.0.4.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/WindowsInput.DLL
----------------------------------------
System.Runtime
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Wox.Plugin.Sys
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Sys/Wox.Plugin.Sys.dll
----------------------------------------
Wox.Plugin.Url
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.Url/Wox.Plugin.Url.dll
----------------------------------------
Windows.Foundation
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/Windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
Windows.Storage
    程序集版本:255.255.255.255
    Win32 版本:10.0.10011.16384
    基本代码:file:///C:/Windows/system32/WinMetadata/Windows.Storage.winmd
----------------------------------------
Wox.Plugin.WebSearch
    程序集版本:1.3.578.0
    Win32 版本:1.3.578
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Plugins/Wox.Plugin.WebSearch/Wox.Plugin.WebSearch.dll
----------------------------------------
Wox.Plugin.Clipboard
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Clipboard%20History-42577cf3-b2f6-4e68-b6aa-fed83bf574db/Wox.Plugin.Clipboard.dll
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0 built by: NET472REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
WindowsInput
    程序集版本:0.2.0.0
    Win32 版本:0.2.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Clipboard%20History-42577cf3-b2f6-4e68-b6aa-fed83bf574db/WindowsInput.DLL
----------------------------------------
Wox.Plugins.CloseScreen
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Close%20Screen-7acc7b1e-36d4-4daf-a4fe-975360555e04/Wox.Plugins.CloseScreen.dll
----------------------------------------
Wox.Plugin.IPAddress
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/IP%20Address-bc12268c-ecfb-4ef3-9d8e-46c02ed676c5/Wox.Plugin.IPAddress.dll
----------------------------------------
RemoveUSB
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Remove%20USB-986de3c5-9db5-4ff6-9244-a2de142481cb/RemoveUSB.dll
----------------------------------------
Wox.Plugin.Switcheroo
    程序集版本:1.0.6.0
    Win32 版本:1.0.6
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Switcheroo%20for%20Wox-227069d8-37c3-4265-aa72-cc98871b5189/Wox.Plugin.Switcheroo.dll
----------------------------------------
Switcheroo.Core
    程序集版本:0.0.0.0
    Win32 版本:0.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Switcheroo%20for%20Wox-227069d8-37c3-4265-aa72-cc98871b5189/Switcheroo.Core.DLL
----------------------------------------
Wox.Plugin.Weather
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Weather-79722547-75a8-4ea7-a34c-1a344755d4a7/Wox.Plugin.Weather.dll
----------------------------------------
Wox.Plugin.OpenCMD
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Wox.Plugin.OpenCMD-cea1ab06-fd0f-4511-90c2-38405fc632b6/Wox.Plugin.OpenCMD.dll
----------------------------------------
Wox.Plugin.ProcessKiller
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Wox.Plugin.ProcessKiller-1ad38d9e-23e7-46ce-9660-fde3ed506dec/Wox.Plugin.ProcessKiller.dll
----------------------------------------
Wox.Plugin.Volume
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Wox.Plugin.Volume-4387cacd-04fa-41da-b026-757995de2376/Wox.Plugin.Volume.dll
----------------------------------------
Wox.Plugin.Youdao
    程序集版本:1.1.0.0
    Win32 版本:1.1
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/%E6%9C%89%E9%81%93%E7%BF%BB%E8%AF%91-952d9e9d-a0cd-492f-b8d5-09762adc7431/Wox.Plugin.Youdao.dll
----------------------------------------
NHotkey
    程序集版本:1.2.1.0
    Win32 版本:1.2.1.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/NHotkey.DLL
----------------------------------------
NHotkey.Wpf
    程序集版本:1.2.1.0
    Win32 版本:1.2.1.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/NHotkey.Wpf.DLL
----------------------------------------
PresentationCore.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
PresentationFramework.Aero2
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
System.Web.Extensions
    程序集版本:4.0.0.0
    Win32 版本:4.7.3282.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    程序集版本:4.0.0.0
    Win32 版本:4.7.3282.0 built by: NET472REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
CoreAudio
    程序集版本:2.0.0.0
    Win32 版本:2.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Roaming/Wox/Plugins/Wox.Plugin.Volume-4387cacd-04fa-41da-b026-757995de2376/CoreAudio.DLL
----------------------------------------
Squirrel
    程序集版本:1.5.2.0
    Win32 版本:1.5.2.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Squirrel.DLL
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Splat
    程序集版本:1.6.2.0
    Win32 版本:1.6.2
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/Splat.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
NuGet.Squirrel
    程序集版本:3.0.0.0
    Win32 版本:3.0.0.0
    基本代码:file:///C:/Users/Ricky/AppData/Local/Wox/app-1.3.578/NuGet.Squirrel.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.7.3056.0 built by: NET472REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
PresentationFramework-SystemData
    程序集版本:4.0.0.0
    Win32 版本:4.7.3324.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by liberize** [comment]
it's caused by clipboard manager plugin, try my patched version:
https://github.com/liberize/Wox.Plugin.ClipboardManager/releases

**Comment by rickywu** [comment]
@liberize release的plugin.json里版本还是1.1.0

**Comment by liberize** [comment]
@rickywu 你自己改吧，我懒得改了

**Comment by bao-qian** [comment]
duplicate #2065
