### ISSUE TITLE
I cannot upload plugin to server

### ISSUE THREAD

**Issue by duyi324** [Wox-launcher/Wox#2402]
I developed a plugin and I want to upload to [http://www.wox.one/plugin/create](http://www.wox.one/plugin/create), but when I did this, the webpage show `Server error`.

![Server error](https://user-images.githubusercontent.com/8315837/54246573-769a7b00-4570-11e9-952a-7d71bfd56371.png)

**Comment by DamChtlv** [comment]
Same problem here...
I don't have hope since there are so many issues, but if someone manage to fix the server error :
please upload my plugin **[WordPress Codex](https://github.com/DamChtlv/WordPress-Codex-Wox-Plugin)**

**Comment by huhubun** [comment]
same problem..

![微信截图_20200329153719](https://user-images.githubusercontent.com/5095184/77843827-5a956600-71d3-11ea-8d22-78d8de3b5fae.png)
