### ISSUE TITLE
error issue

### ISSUE THREAD

**Issue by xamoisback** [Wox-launcher/Wox#2406]
[2019-03-17.txt](https://github.com/Wox-launcher/Wox/files/2974875/2019-03-17.txt)

### Are you submitting a bug report?

(YES)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\xamoi_xv8ueen\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/17/2019 15:57:07
Exception:
System.NullReferenceException: 개체 참조가 개체의 인스턴스로 설정되지 않았습니다.
   위치: Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) 파일 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:줄 89
   위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   위치: System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   위치: System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   위치: System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   위치: System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value, Boolean selectNow)
   위치: System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   위치: System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   위치: System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   위치: System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   위치: System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   위치: System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   위치: System.Windows.Data.BindingExpression.Activate(Object item)
   위치: System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   위치: System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   위치: MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   위치: MS.Internal.Data.DataBindEngine.Run(Object arg)
   위치: System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   위치: System.Windows.ContextLayoutManager.UpdateLayout()
   위치: System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   위치: System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   위치: System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   위치: System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   위치: System.Windows.Interop.HwndTarget.OnResize()
   위치: System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   위치: System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
