### ISSUE TITLE
Executable plugin exemple

### ISSUE THREAD

**Issue by m-x-m-e** [Wox-launcher/Wox#2409]
Hello,

I saw that it's possible to write executable plugin.
I tried one but never succeed to pass my json answer to Wox.

Can you provide a simple exemple (like for the C# and the Python one) ?

Thanks :)

**Comment by m-x-m-e** [comment]
Ok, i found how to do.

i will post some code soon :)

**Comment by m-x-m-e** [comment]
So, I have a .bat file which is call my .js file.

And my .js file returning some results and doing some stuff. The console.log display in the default out of the .bat file. Not sure that's the best way, but it works.
I need a package.json because of the use of the lib opn.

I attached the files, npm install is necessary.

[wox.zip](https://github.com/Wox-launcher/Wox/files/3004172/wox.zip)

**Comment by r3db34rd0** [comment]
Thank you for your sample plugin.
But,  Is it possible to do the init section that is executed when Wox is loaded?
