### ISSUE TITLE
Activate Application Instead of Opening New Instance

### ISSUE THREAD

**Issue by stephen110** [Wox-launcher/Wox#241]
Would it be possible to check if the application is already running, and if so switch to it rather than opening a new instance of the application?

**Comment by qianlifeng** [comment]
You can use https://github.com/qianlifeng/Wox.Plugin.Switcheroo to activate existing application.

In current version, you still need to use <kbd>win</kbd> to activate this plugin, which may be not handy. 
![http://ww3.sinaimg.cn/large/5d7c1fa4jw1eop5b334ofj20m803g3z7.jpg](http://ww3.sinaimg.cn/large/5d7c1fa4jw1eop5b334ofj20m803g3z7.jpg)

but in v1.2.0, we allow you to activate a plugin without actionkeyword(configurable) like this:
![http://ww4.sinaimg.cn/large/5d7c1fa4jw1eop57jtreyj20m80683zz.jpg](http://ww4.sinaimg.cn/large/5d7c1fa4jw1eop57jtreyj20m80683zz.jpg)

**Comment by wilsonwc** [comment]
I didn't know switcharoo existed, maybe it should either be a core plugin, or be included in the plugin directory on the wox site so it is more easily found/installed

**Comment by bao-qian** [comment]
@wilsonwc it is on the plugin website now
https://www.getwox.com/plugin/52

**Comment by sadi304** [comment]
Is this still working ? It will be very handy to switch between apps like this . 
But in the latest version switch to chrome does not appear . Although win works . But takes time to go through the results

**Comment by bao-qian** [comment]
Just remove win action keywords in plugin setting

**Comment by avxkim** [comment]
If i remove "Win" keyword, and instead use "*" as you suggest, then Wox hangs at all.

**Comment by adilk2005** [comment]
In case anyone wants a walk through of this solution, you can view it at https://www.youtube.com/watch?v=55ah-dqIzlI ... you can jump to 6:42 if you don't want the tutorial to show you other features and helpful tips.
