### ISSUE TITLE
程序无法运行（好像是.net问题）

### ISSUE THREAD

**Issue by laoxiajiadeyun** [Wox-launcher/Wox#2411]
### Are you submitting a bug report?

YES

### Steps to reproduce

1. open wox.exe （打开wox）
2. The program did not run successfully（程序没有成功运行）
3. An exception has been logged in the system event viewer（系统事件查看器有异常记录）

### Wox Error Window text

应用程序: Wox.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.Runtime.Remoting.RemotingException

### Detailed logs

(drop your log file here)
应用程序: Wox.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.Runtime.Remoting.RemotingException

Server stack trace: 
   在 System.Runtime.Remoting.Channels.Ipc.IpcPort.Read(Byte[] data, Int32 offset, Int32 length)
   在 System.Runtime.Remoting.Channels.SocketHandler.ReadFromSocket(Byte[] buffer, Int32 offset, Int32 count)
   在 System.Runtime.Remoting.Channels.SocketHandler.Read(Byte[] buffer, Int32 offset, Int32 count)
   在 System.Runtime.Remoting.Channels.SocketHandler.ReadAndMatchFourBytes(Byte[] buffer)
   在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()
   在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)
   在 System.Runtime.Remoting.Channels.Ipc.IpcClientHandler.ReadHeaders()
   在 System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   在 System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(System.Runtime.Remoting.Proxies.MessageData ByRef, Int32)
   在 Wox.Helper.SingleInstance`1+IPCRemoteService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InvokeFirstInstance()
   在 Wox.Helper.SingleInstance`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SignalFirstInstance(System.String)
   在 Wox.Helper.SingleInstance`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InitializeAsFirstInstance(System.String)
   在 Wox.App.Main()

### Screenshots (optional)

(drop your screenshot here)
![image](https://user-images.githubusercontent.com/30768343/54799217-41400c80-4c97-11e9-88fe-02dbd5b3c950.png)
![image](https://user-images.githubusercontent.com/30768343/54799224-49984780-4c97-11e9-8f78-e92ef85129b4.png)

**Comment by Apuyuseng** [comment]
我也是遇见此问题，将进程关闭后，重新启动就可以正常运行，然后过段时间他有犯浑了。

**Comment by Apuyuseng** [comment]
Requirements:
.net >= 4.5.2
everything: .exe installer + use x64 if your windows is x64 + everything service is running
python3: .exe installer + add it to %PATH% or set it in WoX settings

还是这样操作吧

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
