### ISSUE TITLE
Advice to software and authors

### ISSUE THREAD

**Issue by Foundation-Maker** [Wox-launcher/Wox#2424]
在使用了一段时间之后，觉得这个程序很不错。感谢作者！以下是我提出的一点建议：
1、给软件： 增加类似于Linux命令行的history功能，以h作为提示符，显示十条左右。
2、给作者：我翻看了一些issue，发现我们都有各种自己的想法，但或许我们只是片面的认识，从让软件更好的方面来看，可以从建议方面发起投票活动，集众人之见。

-------------------------------------------------------------

After using it for a while, I feel that this program is very good. Thanks to the author! Here are some suggestions I made:
1, to the software: Add a history function similar to the Linux command line, with h as a prompt, showing about ten.
2, sit up straight: I looked at some issues and found that we all have their own ideas, but perhaps we are only one-sided understanding, from the perspective of making software better, we can initiate voting activities from the recommendations, The view of everyone.

**Comment by bao-qian** [comment]
1 use ctrol+h for history.
2 I will use vote in future.
