### ISSUE TITLE
How to change key bind?

### ISSUE THREAD

**Issue by omohikane** [Wox-launcher/Wox#2430]
I am happy to use this Wox !

How to change key bind in Wox?
I like vim-key bind. so I want to change list scroll [↑↓] to [jk].
what can I do?

thanks

**Comment by jhdxr** [comment]
it's not possible to change this behavior in settings. you have to change the source code.

**Comment by I-Want-ToBelieve** [comment]
You can use [autohotkey](https://www.autohotkey.com/)
```autohotkey
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
$!Space::
SendInput, !{space}
if winActive("ahk_exe wox.exe") {
  $j::
    if winActive("ahk_exe wox.exe") {
      SendInput, {SC148}
    } else {
      SendInput, j
    }
  return
  $k::
    if winActive("ahk_exe wox.exe") {
      SendInput, {SC150}
    } else {
      SendInput, k
    }
  return
}
return
```
You should know, so you can't type jk in the input box.
If you like vim, you might be interested in [this](https://github.com/goreliu/vimdesktop) too.
