### ISSUE TITLE
Characters during IME composition not updated to query.

### ISSUE THREAD

**Issue by phu54321** [Wox-launcher/Wox#2437]
### Are you submitting a bug report?

Yes

### Steps to reproduce

- Type some korean in the query, using default Microsoft Korean IME
- Korean IME composition is not complete until the next composition starts, so the last character is ignored from the query.

### Screenshots (optional)
![bugreport](https://user-images.githubusercontent.com/775265/55789831-0ee73980-5af6-11e9-8183-70061db2526a.gif)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
let me know if problem still exist

**Comment by Zlexarc** [comment]
This bug still exists on latest version.
