### ISSUE TITLE
setting item disappear | 设置选项消失

### ISSUE THREAD

**Issue by Black-Web** [Wox-launcher/Wox#2439]
### Are you submitting a bug report?
yes

### Steps to reproduce

*english*

1. install wox, and hide tray icon in the configuration dialogue, it feels great
2. insatll some plugins and restart wox each time the plugin has been installed
3. the `settings` item disappear from the list when I type in `setting`

there is another problem, when I press `win+R`, the search bar becomes a black vertical line with no width instead of a bar.

problem occur under windows 10

*中文*

1. 安装wox，并设置隐藏托盘，玩了一下感觉良好
2. 依次安装了插件`everything`,`Wox.Plugin.Runner`,`有道翻译`,`Clipboard history`，每次都重启wox
3. 最后一次重启后设置选项消失了

还有一个问题是按下`win+R`后搜索条变成了一条没有宽度的黑线。

问题出现在win10

### Screenshots (optional)

![settingdisappear](https://user-images.githubusercontent.com/26480292/55857712-6d68f200-5ba0-11e9-9ac1-db926bfe7faa.PNG)

**Comment by Black-Web** [comment]
找的解决方法了，删除所有wox有关的文件，重新安装就可以，可能是我之前用过wox留下了什么东西，但是`win+R`搜索框变黑线不知道是什么原因。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

for `黑线` problem, please subscribe #962
