### ISSUE TITLE
Postpone enter key acting until query results loaded

### ISSUE THREAD

**Issue by Asvel** [Wox-launcher/Wox#244]
In some cases, if already knowing what will be the first query result, we don't need keep watching the result list for waiting it appeared then launch it, instead we could send the launching wish as soon as the query key entered.
At present (branch V1.2.0), if the enter key pressed very early, the past query result will be launched.

By the way, I notice there are several results refreshments after a query key entered, is it causing by results of various plugins coming successively? In my view, this feature doesn't have any usage except making result list blinking.

(Sorry for my poor English, if you can't understand please ask me post a Chinese version.)

**Comment by bao-qian** [comment]
那你就说中文。
UI闪烁是已知问题，第一段没看懂。

**Comment by bao-qian** [comment]
The query is near instant now. And UI flickering is fixed now.
try the latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

**Comment by Asvel** [comment]
中文版：在知道第一个搜索结果会是什么的时候，并不需要等看到结果再按回车，也就是说把搜索词和回车连着输入，（9个月前）如果回车按的太早的话，会启动上次搜出的东西。

感谢改进～。

**Comment by bao-qian** [comment]
@Asvel 
现在不会启动上次搜出的东西了，已经足够快了。
你可以试一下最新的build
latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

**Comment by Asvel** [comment]
嗯嗯，好哒～。
