### ISSUE TITLE
"Everything Service is not running" while it's running.

### ISSUE THREAD

**Issue by madrulane** [Wox-launcher/Wox#2441]
### Are you submitting a bug report?

YES

### Steps to reproduce

1. Install Wox
2. Install Everything (install service, launch on start)
3. 

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

![screen 2019-04-10 18 10 23](https://user-images.githubusercontent.com/21111550/55891581-787e4b00-5bbd-11e9-897a-b6480840d3b3.jpg)

**Comment by changjiong** [comment]
i met the same problem ,how to fix it ?

**Comment by josefheld** [comment]
check out this WIKI page:
https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Installation#everything-search-installation

**Comment by bao-qian** [comment]
duplicate #1176
