### ISSUE TITLE
Can't bind any hotkey with Windows key

### ISSUE THREAD

**Issue by norlin** [Wox-launcher/Wox#2445]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Open the Wox Settings -> Hotkey
2. Click into the Wox Hotkey field
3. Press any hotkey with Windows key involved (e.g. Win + E)

### Wox Error Window text

No crash/error has happened.
The hotkey become "Win + LWin" and the Wox is opened by just the Win key down.
Also the system hotkey (Win+E == open Explorer window) is triggered.

### Screenshots (optional)

<img width="268" alt="Screenshot_577" src="https://user-images.githubusercontent.com/370803/56035451-e39d5e00-5d32-11e9-955d-56f94da8ffde.png">

There was some related issues before (#310, #1112) and the answer was basically "it's not possible", though there is the Shell plugin which is successfully overriding the system Win+R hotkey.
Minor issue here is when typing a hotkey in the field, it's not preventing any other system/etc actions for the hotkey.

**Comment by hexaguin** [comment]
Same issue here. Ended up working around this with a simple AutoHotkey script:

```
#Space::
	Send, {F13}
return
````

This binds Win+Space to F13, which can then be set as your Wox shortcut. `#Space` can be replaced with `#E` for Win+E, or whatever other shortcut you like.

Hopefully Wox gets patched so this sort of hack isn't needed.

**Comment by pinguluk** [comment]
Simple AutoHotKey script to disable Win key and to simulate Alt + Space
`~LWin::Send {AltDown}{Space}{AltUp}`
