### ISSUE TITLE
3 Finger Tap Shortcut not working properly

### ISSUE THREAD

**Issue by Kidcredo** [Wox-launcher/Wox#2451]
I assigned my 3 fingers tap on my touch-pad as a shortcut to launch Wox but when ever I use the 3 finger tap shortcut it opens up the previous instance(Does not clear the last query even when the setting was changed) of the app and its not focused, I have to click the launcher to start typing.
Is there a work around or a fix for this.

Thanks in Advance

**Comment by bao-qian** [comment]
![Uploading image.png…]()

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
![image](https://user-images.githubusercontent.com/1169912/82015253-e9414200-96b0-11ea-8b53-f995b05e73c3.png)
