### ISSUE TITLE
[Web searches] Delay if search suggestions are enabled

### ISSUE THREAD

**Issue by sinnlosername** [Wox-launcher/Wox#2454]
### Are you submitting a bug report?
Yes

### Steps to reproduce
1. Enable search suggestions
2. Type something starting with "g" for Google and click "Enter" immediately afterwards. Normally it should now search the completely text you entered before pressing "Enter". However if you write it fast then it will remove the last few characters from the search. For example "g This is a test" ends in "This is a te" on Google

This probably happens because it does not show the current text as the first result until the search suggestions are fetched from google (see screenshots)

### Wox Error Window text
No errors

### Detailed logs
https://pastebin.com/uZQF4R6z

### Screenshots (optional)
https://png.sx/4moQ

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
