### ISSUE TITLE
请求增加新功能

### ISSUE THREAD

**Issue by SamuelZon258** [Wox-launcher/Wox#2457]
希望可以添加"屏蔽关键词"功能
搜索内容时常常出现"卸载"选项 需要思考才能判断哪个是开启应用

I hope to add the "Block Keywords" feature.
The "Uninstall" option often appears when searching for content, I need to think about it to determine which one is open.

**Comment by HsunGong** [comment]
Wonderful

**Comment by bao-qian** [comment]
new version has this feature
https://github.com/Wox-launcher/Wox/releases

![image](https://user-images.githubusercontent.com/1169912/82015178-b8f9a380-96b0-11ea-8fbd-9f1e6d51ed44.png)
