### ISSUE TITLE
如何实现英文名文件夹的快速搜索及进入

### ISSUE THREAD

**Issue by sen14251** [Wox-launcher/Wox#2458]
## 中文描述

你好，我想知道是否能够实现英文名文件夹的快速搜索及进入（像中文名文件夹那样，具体描述见下）

我的目录结构：
G:
├── 小工具
├── utility

* 当我搜索 “小工具” 时，能得到我想要的结果：
  ![小工具.png](https://i.loli.net/2019/04/22/5cbc9e61e6423.png)

* 当我搜索 “utility” 时，会出现一堆干扰项（甚至翻遍了也找不到目标文件夹）：
  ![utility.png](https://i.loli.net/2019/04/22/5cbc9e63c5c71.png)

目前我只能通过使用 wox 的文件夹插件来实现搜索，但这意味着我每拥有一个希望能快捷访问的文件夹我都需要在插件中添加它的路径，这并不方便。
请问是否有更好的解决方式，谢谢。

## In English
 
Hi, I want to know if I can quickly search and enter the English name folder (like the Chinese name folder, see below)

My directory structure:
G:
├── 小工具
├── utility

* When I search for "小工具", I get the result I want:
  ![小工具.png](https://i.loli.net/2019/04/22/5cbc9e61e6423.png)

* When I search for "utility", there will be a bunch of disturbing items (even if I rummaged and I can't find the target folder):
  ![utility.png](https://i.loli.net/2019/04/22/5cbc9e63c5c71.png)

Currently I can only do this by using wox's folder plugin, but this means that every time I have a folder I want to be able to access quickly, I need to add its path to the plugin, which is not convenient.
May I ask if there is a better solution, thanks.

**Comment by Char-CN** [comment]
我一个文件夹也搜索不到，这是为啥？

**Comment by bao-qian** [comment]
prepend `G:\` in your search query, try using everything search syntax https://www.voidtools.com/support/everything/searching/
![image](https://user-images.githubusercontent.com/1169912/82015030-6ae4a000-96b0-11ea-95b8-181f55cb7055.png)
