### ISSUE TITLE
About u/ü in Pinyin searching

### ISSUE THREAD

**Issue by KhienghThenYang** [Wox-launcher/Wox#2459]
### Are you submitting a bug report?

No

In Pinyin, the letter u after j/q/x/y is no different from ü(v). And some of people prefer to use v rather than u when ther are typing Pinyin. For example, Wox is not support v, so it can't distinguish between nü and nu.

**Comment by bao-qian** [comment]
this is not possible because current c# pinyin library won't support this.
if you can find an c# pinyin library support this, let me know.
