### ISSUE TITLE
搜索不到微信

### ISSUE THREAD

**Issue by yuanqingshan** [Wox-launcher/Wox#2460]
![image](https://user-images.githubusercontent.com/32973553/56625729-38b16c00-6671-11e9-9769-302cc7d17ab4.png)
搜索不到微信，麻烦作者看一下

**Comment by YYforymj** [comment]
everything没启动，提示的不是很明显吗。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
