### ISSUE TITLE
win + r cause the Wox  stop work and crash 

### ISSUE THREAD

**Issue by lmingde** [Wox-launcher/Wox#2465]
English
---
After Using win+r quick key in Windows( or running hotkey, the Wox program stop work and crash:
![wodx](https://user-images.githubusercontent.com/38581341/57001507-94d53c80-6beb-11e9-857e-f80f7371226b.png)
emm，I also find the Wox program stop work and crash sometime when I use hotkey to raise it as same as the case in picture.

中文
---
当我使用win+r快捷键启动Windows 自己的运行程序时，Wox 停止工作并奔溃了。当然其他时候我用Wox中设置的快捷键想要唤醒Wox时也发生过同样的崩溃。

**Comment by bao-qian** [comment]
duplicate #962
