### ISSUE TITLE
在Theme选项卡中选择其他字体后实际显示字体并未改变

### ISSUE THREAD

**Issue by Wo1framalpha** [Wox-launcher/Wox#2467]
问题：在Theme选项卡中选择其他字体后实际显示字体并未改变

     
复现问题的步骤：

1.从任务栏Wox图标右键菜单中进入Setting界面
2.选择Theme选项卡
3.在字体下拉菜单中改变字体

Detailed logs
[Wox.exe.log](https://github.com/Wox-launcher/Wox/files/3140608/Wox.exe.log)

![image](https://user-images.githubusercontent.com/37956663/57119097-35695f00-6d9a-11e9-82a7-d726e8868e3d.png)
![image](https://user-images.githubusercontent.com/37956663/57119108-503bd380-6d9a-11e9-965d-f6e1c0d5c464.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
