### ISSUE TITLE
Occasional "Copy failed, please try later" error

### ISSUE THREAD

**Issue by archon810** [Wox-launcher/Wox#2469]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Input something into Wox (version 1.3.578) and press Enter.
2. Rarely, observe the following error. Usually, it happens once and then upon retrying does copy correctly. However, right now, it's happening no matter how many times I try to press Enter to copy. 

### Wox Error Window text
Copy failed, please try later

### Detailed logs

https://gist.githubusercontent.com/archon810/9336487703f8362be90f5daa28306340/raw/e0edcc444ac249f54bc44dae8c012c9758614860/2019-05-03_14-39-01.txt

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/469543/57166956-bcc1cd00-6db0-11e9-99f5-925e8c71f0f9.png)

**Comment by PowerSlime** [comment]
I have the same bug when `Mouse Without Borders` is running. Sometimes when other software which "listen" to clipboard to.

# Steps to reproduce:
1. Download [Mouse Without Borders](https://www.microsoft.com/en-us/download/details.aspx?id=35460)
2. Run it and connect your second PC
![image](https://user-images.githubusercontent.com/18900377/136168760-c1f46a12-60a3-421b-85f2-2d5258c31a68.png)
3. Input something to calc in Wox (for example: 1+2)
4. Press `Enter` to copy result in clipboard

# Expected result
Result of calculation was copied to clipboard

# Actual result
The error  `Copy failed, please try later` was thrown.

# Runtime info
- Windows 10 20H2, Build 19042.1237
- Wox 1.4.1196
- Mouse Without Borders 2.2.1.327

**Comment by archon810** [comment]
Wait, was this fixed or what's the resolution?

**Comment by qianlifeng** [comment]
> Wait, was this fixed or what's the resolution?

see https://github.com/Wox-launcher/Wox/discussions/3937, we now have limit resource on v1
