### ISSUE TITLE
使用ahk后wox热键失效(alt+space lost effects when using ahk)

### ISSUE THREAD

**Issue by lluxury** [Wox-launcher/Wox#2474]
### Are you submitting a bug report?
yep
(write your answer here)
when run AutoHotkey , the hotkey  alt+space lost effects

add this in ahk script:

Alt & Space::Run C:\Users\yann\AppData\Local\Wox\app-1.3.524\Wox.exe

**Comment by bao-qian** [comment]
you cannot assign Alt & Space to both wox and autohotkey.
if you want to assign Alt & Space using autohotkey, try change wox hotkey from Alt & Space to sth else/
