### ISSUE TITLE
error in work with python 3.7.3 & scoop

### ISSUE THREAD

**Issue by luyi0521** [Wox-launcher/Wox#2475]
### Steps to reproduce

1.使用scoop安装wox
use scoop install wox
2.配置wox使用python3.7.3的python
setting wox use python3.7.3
3.在wox中操作restart wox，出现报错
restart wox application ,error appear

### Wox Error Window text

> 日志中包括我调试xhsell插件的过程，不太好区分，请见谅。
> in logs, include debug info while test xshell plugin, ignore

[2019-05-08.txt](https://github.com/Wox-launcher/Wox/files/3155694/2019-05-08.txt)

**Comment by luyi0521** [comment]
erase setting
error still

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
