### ISSUE TITLE
Return files instead folder

### ISSUE THREAD

**Issue by sstavridis** [Wox-launcher/Wox#2479]
When I want to search for a specific folder inside my disk (C:\) wox returns as results all the files inside on all folders that I have on my disk.

**Comment by bao-qian** [comment]
try using everything syntax https://www.voidtools.com/support/everything/searching/
![image](https://user-images.githubusercontent.com/1169912/82014633-9b780a00-96af-11ea-9a2b-3391a123ea37.png)
