### ISSUE TITLE
Feature request: Launch plugin directly programatically

### ISSUE THREAD

**Issue by NickSeagull** [Wox-launcher/Wox#2482]
Hello, I was wondering if it was possible to implement launching plugins programatically with the current architecture.

The functionality would be the same as assigning hotkeys to keywords, but from any piece of software. This would allow integrating Wox with other apps, like, for example [AutoHotKey](https://www.autohotkey.com/).

The way I envision this is:
* Either allowing Wox to have some special command line flag that launches Wox with a specific query string, or
* Have Wox start some kind of server (HTTP, IPC, doesn't matter) and listen for a special message that triggers this. Perhaps the same server that listens for our JSON that is used for RPC.

If this is possible, I'm eager to give it a try implementing this feature, although I'd love to have some pointers. Wox is an awesome piece of software, and I'd love to help a little bit 😄 .

Thanks in advance!

**Comment by NickSeagull** [comment]
@bao-qian , what do you think about adding a flag to `wox.exe`, so it can start with some specific string already set?

For example, running `wox` would start it normally, but running it like `wox wpm` would start it with the `wpm` string.

**Comment by liberize** [comment]
upvote

**Comment by liberize** [comment]
I patched source code myself.
https://github.com/liberize/Wox/releases
give it a try:
`Wox.exe -q 'wpm list'`

**Comment by NickSeagull** [comment]
Wow! This is so cool @liberize , thanks!

Perhaps you can open a PR and it will get merged eventually?

**Comment by liberize** [comment]
@NickSeagull maybe later, need some code cleanup.

**Comment by bao-qian** [comment]
Hi @NickSeagull  @liberize 
this feature has been merged
check new release https://github.com/Wox-launcher/Wox/releases/tag/v1.3.792
