### ISSUE TITLE
open setting error

### ISSUE THREAD

**Issue by lics1216** [Wox-launcher/Wox#2486]
Python Path: pythonw.exe
Everything SDK Path: C:\Users\Admin\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 05/19/2019 16:45:26
Exception:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Wox.SettingWindow.OnClosed(Object sender, EventArgs e) 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 320
   在 System.Windows.Window.OnClosed(EventArgs e)
   在 System.Windows.Window.WmDestroy()
   在 System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
