### ISSUE TITLE
Characters not being properly escaped in Python plugins

### ISSUE THREAD

**Issue by lylebrown** [Wox-launcher/Wox#249]
I have a [Wox plugin](https://github.com/lylebrown/WoxMusicbee) in development. I'm running into a critical issue - if a "\", set of quotation marks, or theoretically any symbol with significant meaning is typed, an exception is raised.

I've attempted to fix this myself, without success, by doing the following:

```
def query(self, key):
    key.replace("\\", "\\\\")
    return self.argparser(key)
```

Is there another way I can correct this as a plugin developer? At this point, it seems like an issue with how Wox parses input.

**Comment by qianlifeng** [comment]
Thx for reporting this bug, I will look into this after Chinese Spring Festival (The new year celebration in China)
