### ISSUE TITLE
Wox doesn't clear query as set when "run as" (shift + enter) menu is selected

### ISSUE THREAD

**Issue by user00101010** [Wox-launcher/Wox#2494]
### Are you submitting a bug report?

Yes

### Steps to reproduce

0. Have Wox Settings set to empty query on open
1. Open Wox and enter query, for example "cmd"
2. Press Shift + Enter
3. Run cmd as admin
4. Open Wox again, the "Run as administrator" menu is still shown. Need to press escape twice in order to receive an empty query

Expected behavior: On step 4, when opening Wox it should be an empty query.

The empty query setting works normally and as expected if the "run as" (shift + enter) menu was not selected.

### Wox Error Window text
 
N/A

### Detailed logs

N/A

**Comment by orionv** [comment]
Same issue, did you ever find a fix? I'm thinking about modifying the .shell plugin if possible to allow "-a" before a command to simply run it in admin mode or something.

**Comment by user00101010** [comment]
I never found a fix @orionv My "fix" was that I have now enabled the new hidden immersive search in Windows 10 and enabled full disk indexing which offers identical look and functionality. To be honest, I find it to actually work better than Wox or alternatives due to the deep OS level integrations. Not to mention that you don't have extra services running and doing the same thing the OS is already doing (building indexes of the files). There is the down-side that you have to disable web search if you don't want all your local searches being queried to Bing... (gee, thanks Microsoft)

**Comment by AdamJel** [comment]
Hi @bao-qian, I think this is rather a bug then suggestion. It is unexpected behaviour from UX perspective.
