### ISSUE TITLE
Wox not searching through Gdrive

### ISSUE THREAD

**Issue by nikolayshubraka** [Wox-launcher/Wox#2497]
Just installed Google Drive and Google Team Drive. It seems Wox is not able to search within the drive. Is it a matter of making the folders within the Gdrive available offline?

**Comment by nikolayshubraka** [comment]
Just figured out that you can tell Everything to index GDrive as a folder which solved the issue.

**Comment by yudhafebrian** [comment]
> 

how to do that?

**Comment by nikolayshubraka** [comment]
> > 
> 
> how to do that?

Fire up Everything, go to Options,  Indexes, Folders - add G drive as a folder

**Comment by yudhafebrian** [comment]
> > > 
> > 
> > 
> > how to do that?
> 
> Fire up Everything, go to Options, Indexes, Folders - add G drive as a folder

thank you so much it works
