### ISSUE TITLE
使用WIN+R调用命令行时总是弹出开始菜单

### ISSUE THREAD

**Issue by 244671360** [Wox-launcher/Wox#2498]
每次用wox的WIN+R，都是先跳出wox然后接着弹出开始菜单，怎么解决啊

**Comment by xuzheliang135** [comment]
设置为alt键不好吗？

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
