### ISSUE TITLE
pop-up error window about "wox 出错了"

### ISSUE THREAD

**Issue by tangfy** [Wox-launcher/Wox#2509]
### Are you submitting a bug report?

(write your answer here)
Yes.

### Steps to reproduce

1. run wox-1.3.578 on my windows10
2.then pop-up the error windows
3.but It looks like the program functions are still working

### Wox Error Window text

(paste here)
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\tangfy\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/15/2019 16:03:03
Exception:
System.UnauthorizedAccessException: 尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Wox.SettingWindow.SetStartup() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 63
   在 Wox.App.AutoStartup() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 97
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 80
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2019-06-15.txt](https://github.com/Wox-launcher/Wox/files/3292864/2019-06-15.txt)

### Screenshots (optional)

(drop your screenshot here)

![批注 2019-06-15 160953](https://user-images.githubusercontent.com/13523754/59548921-18729f00-8f88-11e9-8af8-591780db4449.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
