### ISSUE TITLE
my bug

### ISSUE THREAD

**Issue by nicole0930** [Wox-launcher/Wox#2510]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.use hotkey : win+~
2. input: bd 百度脑图
3.then report the questions are as above.

### Wox Error Window text

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 06/17/2019 09:10:42
Exception:
System.ComponentModel.Win32Exception (0x80004005): 找不到应用程序
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.<Query>b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

2019-06-17 08:39:40.1431|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2019-06-17 08:39:40.1780|INFO|App.OnStartup|Runtime info:
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True
2019-06-17 08:39:40.1870|INFO|BinaryStorage.TryLoad|Cache file not exist, load default data
2019-06-17 08:39:43.4343|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <要求的函数不受支持>
2019-06-17 08:39:43.4343|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <调用 SSPI 失败，请参见内部异常。>
2019-06-17 08:39:43.4503|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)>

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/26537827/59572624-0c4e2500-90e1-11e9-83ef-06563e876598.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
