### ISSUE TITLE
更新win10 系统至 1903后

### ISSUE THREAD

**Issue by AIMentalModel** [Wox-launcher/Wox#2513]
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\surpe\AppData\Local\Programs\Python\Python37\pythonw.exe
Everything SDK Path: 
Date: 06/19/2019 14:40:39
Exception:
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Wox.MainWindow.OnContextMenusForSettingsClick(Object sender, RoutedEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 208
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2019-06-19.txt](https://github.com/Wox-launcher/Wox/files/3304728/2019-06-19.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
