### ISSUE TITLE
Suggestion : using the new windows 10 default enhanced search over everything

### ISSUE THREAD

**Issue by Rajashow** [Wox-launcher/Wox#2514]
The option to use the build in better search for wox over everything. 

The new windows 10 search options:
![image](https://user-images.githubusercontent.com/10718594/59889545-d936ba80-939a-11e9-95e8-d4b8f6463715.png)

**Comment by jhdxr** [comment]
looks good. how is the speed and the quality of results?
let me see if I can find any related documents about this feature
