### ISSUE TITLE
Search results order (FuzzyMatcher, Score)

### ISSUE THREAD

**Issue by itziksi** [Wox-launcher/Wox#2516]
Hi,
I when I type a query, sometimes I don't under stand the order of the results.
Example, I have 2 apps installed:
AgentRansack and  FORScan
When I type "ran", the result of FORScan appears above the result of AgentRansack.
I've added some debug logs in FuzzyMatcher.CalScore and check the scores.
I see in the logs that FORScan receives higher score. 
Can someone have idea if this is by design ?
Also why "matchLen" is with value of 5 for "FORScan" where query length is only 3 chars.
These are the logs:
( I removed sub-string "|DEBUG|Wox.Infrastructure.FuzzyMatcher.CalScore|" from logs to be readable here.
You can see in line 17587 that FORScan gets a score of 64, while Ransack highest is only 50 
Thanks for your help !

17541: 2019-06-22 23:21:22.5119score: DBG_SCORE str=AgentRansack, query=ran, firstIndex=5, matchLen=3, score =50

17545: 2019-06-22 23:21:22.6049score: DBG_SCORE str=AgentRansack.exe, query=ran, firstIndex=5, matchLen=3, score =40

17577: 2019-06-22 23:21:22.7579score: DBG_SCORE str=Agent Ransack Help, query=ran, firstIndex=6, matchLen=3, score =36

17579: 2019-06-22 23:21:22.7579score: DBG_SCORE str=Agent Ransack, query=ran, firstIndex=6, matchLen=3, score =36

17581: 2019-06-22 23:21:22.7719score: DBG_SCORE str=Agent Ransack, query=ran, firstIndex=6, matchLen=3, score =36

17583: 2019-06-22 23:21:22.8149score: DBG_SCORE str=Uninstall Agent Ransack, query=ran, firstIndex=16, matchLen=3, score =19

17584: 2019-06-22 23:21:22.8269score: DBG_SCORE str=Uninstalls Agent Ransack, query=ran, firstIndex=17, matchLen=3, score =18

17585: 2019-06-22 23:21:22.8399score: DBG_SCORE str=FORScan Log folder, query=ran, firstIndex=2, matchLen=5, score =44

17587: 2019-06-22 23:21:22.8399score: DBG_SCORE str=FORScan, query=ran, firstIndex=2, matchLen=5, score =64

17589: 2019-06-22 23:21:22.8549score: DBG_SCORE str=Uninstall FORScan, query=ran, firstIndex=12, matchLen=5, score =21

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
