### ISSUE TITLE
Suggestion for using System Commands

### ISSUE THREAD

**Issue by mimishy2000** [Wox-launcher/Wox#2523]
Every time,when i use "Win+R" to open System Commands,it will create a Command Window behind.That is unnecessary!I have to close it by myself.Hope to improve it.
![image](https://user-images.githubusercontent.com/30401670/60422136-eadf5400-9c1d-11e9-9475-974763a2cadf.png)

**Comment by OldNero** [comment]
Hmm. I can't replicate this issue. 
Fresh install Windows 10 Enterprise (1903). Fresh install Everything and Wox.

![Untitled](https://user-images.githubusercontent.com/37744772/60930265-8a0ae800-a2bd-11e9-9617-14804e210454.png)

**Comment by hdkn235** [comment]
> Every time,when i use "Win+R" to open System Commands,it will create a Command Window behind.That is unnecessary!I have to close it by myself.Hope to improve it.
> ![image](https://user-images.githubusercontent.com/30401670/60422136-eadf5400-9c1d-11e9-9475-974763a2cadf.png)
me too!

**Comment by voyager** [comment]
If you change Plugin > Shell settings from "CMD" to "RunCommand", you will not have the command prompt window anymore.

That being said, on my machine, the Command Prompt window also stays open after a command is launched, even though "Do not close Command Prompt" options is NOT selected.
