### ISSUE TITLE
Suggestion: Show loading in tray icon

### ISSUE THREAD

**Issue by DanVerseDev** [Wox-launcher/Wox#2525]
It would be nice if the tray shows the program status, like an error icon when the Everything service is stopped, or when the app is loading show a busy icon.

When my PC starts, i have to wait for Wox to finish loading before i can press the hotkey, and the only chance of knowing if the app is loaded is to press right click button until it responds.

It would be nice to have busy icon (orange for example) at app start and when it's ready, the regular icon

**Comment by bao-qian** [comment]
startup indexing time is faster now, 
try it
https://github.com/Wox-launcher/Wox/releases
