### ISSUE TITLE
wox有右键菜单和自定义浏览器么？请问怎么设置？(Do WOx have right-click menus and custom browsers? How do I set it?)

### ISSUE THREAD

**Issue by HeLLLLL** [Wox-launcher/Wox#2529]
1.右键菜单(Right-click menu)
您好，有这样一种情况，当我查到一个txt文件后，我希望可以用notepad++打开它，但是我不知道该怎么操作。
(Hello, there is such a case, when I find a TXT file, I hope to open it with Notepad +, but I do not know how to operate.)
![image](https://user-images.githubusercontent.com/29757543/60799919-b4b64d00-a1a6-11e9-98c3-dcd55477238c.png)
右键后不会像windows一样展开详细菜单。
(Right-click will not expand the detailed menu like Windows.)
![image](https://user-images.githubusercontent.com/29757543/60799953-c4359600-a1a6-11e9-93ba-cc91e241e019.png)
2.自定义浏览器(Custom Browser)
工作需要将ie设置为默认浏览器，但是日常习惯用chrome，请问使用wox搜索后，怎么用chrome或者其他浏览器打开链接。
(Work needs to set ie as the default browser, but Chrome is commonly used everyday. How to use chrome or other browsers to open links after using WOx search?)
![image](https://user-images.githubusercontent.com/29757543/60800044-ff37c980-a1a6-11e9-99a3-e44df984ba7b.png)
![image](https://user-images.githubusercontent.com/29757543/60800057-0d85e580-a1a7-11e9-9a8f-03208eed1640.png)
![image](https://user-images.githubusercontent.com/29757543/60800067-11b20300-a1a7-11e9-9173-376364eb6e4a.png)
期待您的答复！
(Looking forward to your reply!)

**Comment by fengchuan256** [comment]
i can help to answer. you can set it as default in windows.
**click** windows
**type** default apps
**find** web engine
**choose** chrome 
**close**
Please try with wox again

**Comment by bao-qian** [comment]
set it as default browser as @fengchuan256 said.

**Comment by zzqq2199** [comment]
在网页搜索插件中有选项：set browser from path
