### ISSUE TITLE
Add a convenient way to adding folder into Wox index

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#253]
Current solution is to add an item named "Add to Wox index" to "SendTo" explorer context menu.

**Comment by druellan** [comment]
Yes, I feel the need of this. Using Launchy I can: index only folders under a folder, index only certain filetypes under a folder.

**Comment by bao-qian** [comment]
I think this is already been don by setting page of Program plugin.

**Comment by airstrike** [comment]
Don't the settings in the Program plugin relate only to .exe files? I want to add index folders and subfolders from a specific path so that they all show up in my search results. I feel this issue should be reopened
