### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mmickael** [Wox-launcher/Wox#2537]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by mmickael** [comment]
This is not a problem but a feature request.  It will be nice to have a function to convert a number to different base (hex, oct, bin).  Thank you.

**Comment by mmickael** [comment]
Sorry, closed by mistake.

**Comment by NickSeagull** [comment]
@mmickael it is relatively easy to create a plugin to do this. Have a look at the docs: http://doc.wox.one/en/plugin/python_plugin.html

**Comment by bao-qian** [comment]
this should be implemented as plugin.
