### ISSUE TITLE
卸载PC的软件后,下次启动报错提示该文件找不到

### ISSUE THREAD

**Issue by leizhiyuan** [Wox-launcher/Wox#254]
启动的时候是否可以设置自动重新索引?
每次卸载完软件,都需要重新删除cache目录.不太方便.

**Comment by qianlifeng** [comment]
用的v1.1.1?试试v1.2.0  https://github.com/qianlifeng/Wox/releases

**Comment by leizhiyuan** [comment]
@qianlifeng  好的.我先试试,wox很好用.谢谢~

**Comment by leizhiyuan** [comment]
没问题了.谢谢
