### ISSUE TITLE
Wox.Plugin.Program not reading icons from .url files

### ISSUE THREAD

**Issue by SomeoneIsWorking** [Wox-launcher/Wox#2541]
![image](https://user-images.githubusercontent.com/9450683/61374530-4445b500-a8a5-11e9-9758-49b24aacfb83.png)

Wox v1.3.524

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by PINPAL** [comment]
I am also experiencing the same issue. `.url` files are not have their icons fetched correctly.
