### ISSUE TITLE
bilibili.com doesn't work well with wox

### ISSUE THREAD

**Issue by James-Code-007** [Wox-launcher/Wox#2542]
### Steps to reproduce 
1. 添加bilibili的url搜索地址：search.bilibili.com/video?keyword={q}
    add the search engine url of bilibili.com ("search.bilibili.com/video?keyword={q}") to the web search plugin
2. 设置快捷键为“bili”
    set Action Keyword as "bili" 
3. 用bili快捷键搜索任何内容，包括中英文，都显示出错。
    use that Action keyword to search anything, either English or Chinese, the error window pops up.

### Wox Error Window text
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\*****\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/18/2019 15:41:21
Exception:
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.<Query>b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
### Detailed logs
[2019-07-18.txt](https://github.com/Wox-launcher/Wox/files/3405320/2019-07-18.txt)

**Comment by James-Code-007** [comment]
Further more:
1. although the logs show that my OS Version is Microsoft Windows NT 10.0.17763.0, the actual version is MicroSoft Windows 10 64bit Home Edition, 17763.
2. the error was firstly found in v1.3.524  version of Wox,  so I tried the lastest version, both have the above mentioned problem.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
