### ISSUE TITLE
windows10启动wox后win+r屏幕出现了黑线

### ISSUE THREAD

**Issue by xianwdong** [Wox-launcher/Wox#2545]
操作系统：windows10 1903
wox版本：1.3.580
按win+r键屏幕上会出现一条黑线，之后alt+space黑线会消失，再按又出现，无法看见wox窗口
![image](https://user-images.githubusercontent.com/24319123/61574302-654e1600-aaf0-11e9-8065-8d655e9c9971.png)

**Comment by nehcuoh** [comment]
我也出现了

**Comment by bennyhuo** [comment]
+1，重启 wox 解决问题，怀疑是不是跟双屏有关？

**Comment by zly19540609** [comment]
我也出现了 win10 1903 win+r键 会出现一条黑线 打不开wox窗口 只能重启wox
[2019-07-26.txt](https://github.com/Wox-launcher/Wox/files/3436159/2019-07-26.txt)

**Comment by PSilverQ** [comment]
+1，使用wox取代Win+R，进入cmd窗口后，再次呼出wox时会出现无法正常显示窗口的问题

**Comment by xianwdong** [comment]
> 
> 
> +1，重启 wox 解决问题，怀疑是不是跟双屏有关？

我也是双屏

**Comment by JanGuo** [comment]
怎么解决?

**Comment by dijiugeweiba** [comment]
跟楼上一样的问题

**Comment by iscooool** [comment]
我也出现了，解决方法在 #1968 当中有。

**Comment by qrqhuang** [comment]
> 

不是一个问题吧。
现在这个双屏切换后黑屏的问题还是不行。

**Comment by qrqhuang** [comment]
@iscooool 

不是一个问题吧。
现在这个双屏切换后黑屏的问题还是不行。

**Comment by qrqhuang** [comment]
@bao-qian 老大，救救孩子吧
