### ISSUE TITLE
flickering of icons when we install wox on windows 10 1903

### ISSUE THREAD

**Issue by ssoin01** [Wox-launcher/Wox#2547]
whenever I install wox on windows 10 laptop the icons kind of start flickering in destop as well as on the taskbar which seems very annoying. It seems like the app is auto refreshing the desktop every now and then. Please help me out to get rid of from fix.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
