### ISSUE TITLE
Exception after added Custom Search in Web Searches Plugin 

### ISSUE THREAD

**Issue by Y0ngg4n** [Wox-launcher/Wox#2551]
[2019-07-31.txt](https://github.com/Wox-launcher/Wox/files/3450368/2019-07-31.txt)

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: C:\Python37\pythonw.exe
Everything SDK Path: C:\Users\aschuele\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 07/31/2019 09:32:44
Exception:
System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.Collections.ArrayList.set_Item(Int32 index, Object value)
   bei System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bei System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   bei System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   bei MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
