### ISSUE TITLE
Wox went wrong

### ISSUE THREAD

**Issue by xijianfei** [Wox-launcher/Wox#2556]
[2019-08-03.txt](https://github.com/Wox-launcher/Wox/files/3463394/2019-08-03.txt)
![截图](https://user-images.githubusercontent.com/24447756/62407647-4ec6b500-b5ee-11e9-96f1-2465e0ba6378.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
