### ISSUE TITLE
使用cmd命令行calc，会在后面有个cmd框请按任意键继续的问题，版本1.3.524

### ISSUE THREAD

**Issue by 1074191791** [Wox-launcher/Wox#2566]
使用cmd命令行calc，会在后面有个cmd框请按任意键继续的问题，版本1.3.524

**Comment by bao-qian** [comment]
you could search calculator uwp directly at the moment.

**Comment by bao-qian** [comment]
![image](https://user-images.githubusercontent.com/1169912/82010637-41724700-96a5-11ea-991f-fb2c4d79ad70.png)
