### ISSUE TITLE
Don't understand how to install plugins

### ISSUE THREAD

**Issue by Fuwuana** [Wox-launcher/Wox#2567]
I may be an idiot but I don't understand how to install plugins, the README says "Install/Uninstall plugin: type `wpm install/uninstall`" but I don't understand, do I type `Install (Name of Plugin)`? or do I type `wpm install (Name of Plugin)`? How does it work? Sorry for bothering you.

**Comment by strund3r** [comment]
Just open Wox (Alt+Space) and type, for example, `wpm install IP Address`. You can get a list of plugins here: http://www.wox.one/plugin

**Comment by Fuwuana** [comment]
@strund3r Ok, Where do I get the IP address? Say I want to install this plugin http://www.wox.one/plugin/253

**Comment by Vicropht** [comment]
> 
> 
> @strund3r Ok, Where do I get the IP address? Say I want to install this plugin http://www.wox.one/plugin/253

Then just type 

> wpm install DuckDuckGo Web Search

a prompt will ask you if you want to install it with more information about the plugin and afterwards ask you to restart wox in order for the changes to take effect

**Comment by Fuwuana** [comment]
@Vicropht Understood, thank you
