### ISSUE TITLE
wox 乱码什么情况

### ISSUE THREAD

**Issue by zhangxiumin** [Wox-launcher/Wox#2574]
![微信图片_20190827100217](https://user-images.githubusercontent.com/38202512/63735274-d7fd9e80-c8b1-11e9-9d7a-c9b31e414af1.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
