### ISSUE TITLE
Can't stop launching everything automatically

### ISSUE THREAD

**Issue by FrankHB** [Wox-launcher/Wox#258]
Tested 1.2.0 beta and dev branch, it showed that every time wox would try starting the everything process if it did not exist, even if the plugin is disabled. I found no way to configure it elsewhere. Eventually I had commented the related code away and built myself.

**Comment by qianlifeng** [comment]
This maybe a bug, after you disabled everything plugin, it shouldn't try to start everything.exe.

**Comment by druellan** [comment]
I can confirm this. The only way to stop Everything to start, is removing the plugin folder.

**Comment by bao-qian** [comment]
wox won't try to start everything services anymore, it will use existing running / installed everything
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898

**Comment by bao-qian** [comment]
Thanks for report!
