### ISSUE TITLE
启动程序报错

### ISSUE THREAD

**Issue by EKKOBLUE** [Wox-launcher/Wox#2584]
[

### Are you submitting a bug report?

(write your answer here)

启动程序报错如图所示
![image](https://user-images.githubusercontent.com/30229045/64168741-b9357400-ce7e-11e9-8ce2-f1730c8bac85.png)

**Comment by chenbihao** [comment]
一样，启动不了程序

**Comment by EKKOBLUE** [comment]
> 一样，启动不了程序

问题已经解决了，我这里的原因是之前去除快捷方式图标的小箭头导致的快捷方式关联失效了，恢复箭头以后用了新的方式去除箭头，问题解决

**Comment by EKKOBLUE** [comment]
恢复快捷方式图标小箭头的方式和另一个不影响快速启动的去除箭头方式


taskkill /f /im explorer.exe
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons" /v 29 /d "C:\Windows\system32\imageres.dll,154" /t reg_sz /f
reg add "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons" /v 29 /d "C:\Windows\system32\imageres.dll,154" /t reg_sz /f
reg add "HKEY_CLASSES_ROOT\lnkfile" /v IsShortcut /t reg_sz /f
reg add "HEKY_CLASSES_ROOT\piffile" /v IsShortcut /t reg_sz /f
start explorer

复制粘贴到一个新建文本文件保存为.bat格式双击运行。
注意：
如果还需要除去小箭头用下面的命令，用下面这个方法就可以避免错误了
新建一个文本文件，粘贴后另存为.bat文件，然后以管理员身份打开

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons" /v 29 /d "%systemroot%\system32\imageres.dll,197" /t reg_sz /f
taskkill /f /im explorer.exe
attrib -s -r -h "%userprofile%\AppData\Local\iconcache.db"
del "%userprofile%\AppData\Local\iconcache.db" /f /q
start explorer
pause




------------------ 原始邮件 ------------------
发件人: "chenbihao"<notifications@github.com>; 
发送时间: 2019年9月6日(星期五) 下午5:30
收件人: "Wox-launcher/Wox"<Wox@noreply.github.com>; 
抄送: "庞振德"<81337943@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Wox-launcher/Wox] 启动程序报错 (#2584)




怎么恢复呢，新的方式是什么
 
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。
Seems that all Contributiors are tired to update this project because of `996`.

**Comment by chenbihao** [comment]
> 感觉没人维护这个项目了，老板跑路了。
> Seems that all Contributiors are tired to update this project because of `996`.

haha，感觉也是，而且用起来有些地方有点不顺手，要不自己重新写个? /滑稽

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
