### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by sachin3973** [Wox-launcher/Wox#2586]
### Are you submitting a bug report?
Yes
(write your answer here)

### Steps to reproduce

1. Well, I don't know I just install and it was working just fine and I was installing some new plugin.
2. Then received this error message and now I won't be able to search anything.
3. 

### Wox Error Window text

[2019-09-09.txt](https://github.com/Wox-launcher/Wox/files/3589381/2019-09-09.txt)

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by JagteshwarSingh** [comment]
I also got the same error and coincidently enough on the same day well. I also tried uninstalling and reinstalling the whole Wox program but it still shows the same error.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
