### ISSUE TITLE
Install to a specific location

### ISSUE THREAD

**Issue by mikolajek** [Wox-launcher/Wox#2587]
I've reviewed [the install guidelines](url=https://github.com/Wox-launcher/Wox/wiki/Getting-started.-Installation), but they don't address my question, so I'm putting it here.

Is there a way to install Wox in a specific location, not in the AppData/Local directory?

If not possibly I can just move the files to the location of choice, can I?

**Comment by HsunGong** [comment]
Maybe it is impossible now, you can folk it and try it yourself?

**Comment by jjw24** [comment]
You can now use portable mode in my [forked version](https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.12.2).

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
new version support portable mode.
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by bao-qian** [comment]
duplicate #629
