### ISSUE TITLE
Sometimes wox doesnot start on system startup

### ISSUE THREAD

**Issue by arjunQ21** [Wox-launcher/Wox#2588]
Sometimes wox just doesnot start on system startup in Windows 10.
Even after cheking the "start wox on system startup" checkbox, sometimes it wont start.
Maybe its a little bug, please fix this.
And even in Windows Task Mangaer, under Startup Tab, wox is not shown. I think this info can help a little.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
