### ISSUE TITLE
安装完新插件后重启就报错

### ISSUE THREAD

**Issue by littlepure2333** [Wox-launcher/Wox#2589]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\littlepure\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/14/2019 15:21:46
Exception:
System.Exception: Update.exe not found, not a Squirrel-installed app?
   在 Squirrel.UpdateManager.getUpdateExe() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 313
   在 Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments) 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 196
   在 Wox.Core.Plugin.PluginInstaller.Install(String path) 位置 C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:行号 93
   在 Wox.PublicAPIInstance.<>c__DisplayClass13_0.<InstallPlugin>b__0() 位置 C:\projects\wox\Wox\PublicAPIInstance.cs:行号 112
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_1.<ResultForInstallPlugin>b__0(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 170
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HsunGong** [comment]
`Update.exe not found`，问题是否解决？
如果没有，如下方案：
- 看安装的软件目录里有没有上述`exe`程序
- 从github releases里面重新下一个版本，然后看一下是不是还有问题。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
