### ISSUE TITLE
Backup and restore configurations

### ISSUE THREAD

**Issue by FrankHB** [Wox-launcher/Wox#259]
I'd be glad to see any convenient GUI way to do it rather than pick the configuration files manually.

**Comment by qianlifeng** [comment]
This will be achieved by a "backup config" plugin later, which should have a setting view.

**Comment by bao-qian** [comment]
This should be done after #389.
I think this should be a built-in ability instead of plugin. API should not expose the location of all config files.

**Comment by dandrejvv** [comment]
But when you backup the settings, will it also backup the plugin settings? Can it also download the plugin if it is not installed once you import the settings (maybe make it a checkbox option)?

**Comment by bao-qian** [comment]
1. yes, plugin settings located in %APPDATA%\Settings\Plugins
2. no, just copy the plugins directory

**Comment by bao-qian** [comment]
settings lost here: #794 
- [ ] 1. backup current settings button
- [ ] 2. auto backup current settings before update
