### ISSUE TITLE
Wox-1.3.578 cant install on windows 10.

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2591]
I noticed wox was not working properly with the Alt+Spacebar keypress so I tried to open it from the system tray and it would not open at all. I tried reinstalling it but then I got an error message stating "Installation Failed" from Windows. I'm using Windows 10 Home Single Language 1903.

### Steps to reproduce

1. Open wox launcher
2. Get error message (my case)

### Wox Error Window text
Installation has failed.
There was an error while installing the application.

### Detailed logs
[SquirrelSetup.log](https://github.com/Wox-launcher/Wox/files/3613452/SquirrelSetup.log)

**Comment by HsunGong** [comment]
You may delete `C:\Users\rhnko\AppData\Local\Wox`, `C:\Users\rhnko\AppData\Roaming\Wox` folders and try again?

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。
Seems that all Contributiors are tired to update this project because of `996`.

**Comment by notfound945** [comment]
虽然安装报错，但事实上在 AppData/Local 目录下就有 Wox.exe 可执行文件了，直接打开可以使用，不知道怎样，反正能用！

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
