### ISSUE TITLE
Wox crashed when using the youdao dictionary plugin

### ISSUE THREAD

**Issue by Gong-yf** [Wox-launcher/Wox#2595]
### Are you submitting a bug report?

(write your answer here) **Yes**

### Steps to reproduce

1. **When using youdao dictionary plugin, type "yd"+space, then wox crashed**
2.
3.

### Wox Error Window text

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\gongyf\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/17/2019 16:47:22
Exception:
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2019-09-17.txt](https://github.com/Wox-launcher/Wox/files/3620277/2019-09-17.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by HsunGong** [comment]
You may ask question [there](https://github.com/Wox-launcher/Wox.Plugin.Youdao).

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。
Seems that all Contributiors are tired to update this project because of `996`.
