### ISSUE TITLE
failed wpm install Simple Web Search

### ISSUE THREAD

**Issue by MarcoCantieni** [Wox-launcher/Wox#2596]
[2019-09-17.txt](https://github.com/Wox-launcher/Wox/files/3621820/2019-09-17.txt)
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Mike.Timm\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/17/2019 16:17:42
Exception:
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\Mike.Timm\AppData\Roaming\Wox\Plugins\Simple Web Search-3dbe260a-1aec-4cc7-b645-b6bee08468bd\Wox.Plugin.dll" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei Wox.Core.Plugin.PluginInstaller.UnZip(String zipedFile, String strDirectory, Boolean overWrite) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:Zeile 180.
   bei Wox.Core.Plugin.PluginInstaller.Install(String path) in C:\projects\wox\Wox.Core\Plugin\PluginInstaller.cs:Zeile 75.
   bei Wox.PublicAPIInstance.<>c__DisplayClass13_0.<InstallPlugin>b__0() in C:\projects\wox\Wox\PublicAPIInstance.cs:Zeile 112.
   bei System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   bei System.Windows.Threading.Dispatcher.Invoke(Action callback)
   bei Wox.Plugin.PluginManagement.Main.<>c__DisplayClass12_1.<ResultForInstallPlugin>b__0(ActionContext c) in C:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:Zeile 170.
   bei Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:Zeile 146.
   bei System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   bei System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   bei System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   bei System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   bei System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HsunGong** [comment]
You can manually add this plugin in WOX dir `%AppData%\Roaming\Wox\Plugins`。
- download from [WOX](http://api.wox.one/media/plugin/ca8c0c3dea2e4f75833482489587d33d/Simple%20Web%20Search-999fc5f3-cc79-4ce4-81df-da1ae0497a65.wox)

Your error may be caused by multi use of this folder. Delete plugin folder and try `wpm install` again?

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。
Seems that all Contributiors are tired to update this project because of `996`.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
