### ISSUE TITLE
[Important]Add Collaborators to keep Updates | Someone else rebuild a `Wox` Project to keep updates ? && [Wiki Enhanced] Uninstall Wox Totally

### ISSUE THREAD

**Issue by HsunGong** [Wox-launcher/Wox#2597]
### Delete manaully

1, Uninstall

2, delete folders as follows:

`%AppData%\Local\Wox` and `%AppData%\Roaming\Wox`

### Using `Total Uninstall` of `Everything` to search all `Wox` name files.

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。

**Comment by HsunGong** [comment]
Add Collaborators to keep Updates!!!
Add Collaborators to keep Updates!!!

**Comment by bao-qian** [comment]
Hi ,

https://github.com/Wox-launcher/Wox/releases

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/81972789-b61d9500-9655-11ea-8f2e-ecbf53ab57df.png)
