### ISSUE TITLE
怎么选中一条记录并编辑它继续搜索

### ISSUE THREAD

**Issue by lmhlmh1282** [Wox-launcher/Wox#2598]
### Are you submitting a bug report?

(write your answer here)

在搜索一条记录时，我们会匹配到很多条记录。我怎么选中一条记录并使其添加到输入框中，然后编辑它。就像网页搜索一样，我用上下键选中不同的结果记录，搜索框中的内容也会跟着变化，可以直接编辑输入框以节省时间。

**Comment by enria** [comment]
可以看看[这个](https://pic.downk.cc/item/5ed222e0c2a9a83be569c3ae.gif)，应该是你想要的效果。
这个不是Wox提供的功能，而是我使用Python模仿Wox制做的一个[启动器](https://github.com/enria/Beefalo)中实现的。
就是使用Tab键来展开菜单，我觉得Wox也可以用这样的方式来实现。

**Comment by qianlifeng** [comment]
Track on #3036
