### ISSUE TITLE
not count execute error command in history will be better

### ISSUE THREAD

**Issue by cxfksword** [Wox-launcher/Wox#26]
for example.i want to execute **mstsc** command.some times when i input very fast, wox will execute the **msts** command.but it still save to the history.

![1111](https://f.cloud.github.com/assets/718792/2060692/e238b62a-8c29-11e3-95e1-0dee5e018020.png)
![222222](https://f.cloud.github.com/assets/718792/2060693/e66b00fe-8c29-11e3-98fc-eca57a9471f9.png)

**Comment by orzFly** [comment]
We will fix this with #18 .

In fact, this CMD plugin needs more optimization. The delay before updating the result should be removed IMO because I type very fast too.

**Comment by qianlifeng** [comment]
62475f9bcf06cfba1302ce4f55129adb33df24c2. Fixed cmd history issues when executing cmd with errors.. 
The delay issue of CMD will be fixed in the future.

**Comment by bao-qian** [comment]
With the latest refactoring of result panel, the delay issue should be fixed.
Any body still have this can try Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
@cxfksword @qianlifeng
