### ISSUE TITLE
Can't find %appa

### ISSUE THREAD

**Issue by SonOfDiablo** [Wox-launcher/Wox#2603]
_Are you submitting a bug report?
No._

I just installed WOX and 'Everything'.
And I noticed that in WOX I can't search using environment variables (example being %appdata%) however, I can in Everything.

Is this just an issue local to me because I'm screwing something up or is it just simply not something that WOX can do?

Basically I just want to be able to do something along the lines of "%appdata%/Wox" to open the WOX directory in %appdata%

**Comment by jjw24** [comment]
Wox doesnt support it. What about just adding the folder path to the Folder plugin?

**Comment by SonOfDiablo** [comment]
I mean, I can find it in WOX, I was just interested in knowing if it was possible to use environment variables in WOX or not.

**Comment by wingo1** [comment]
For now, the answer is no.

**Comment by bao-qian** [comment]
no, wox will only support default voidtools. everything settings.
