### ISSUE TITLE
I can't run after installing plugins

### ISSUE THREAD

**Issue by ZannaB** [Wox-launcher/Wox#2612]
I can't run after installing plugins. Last one plugin I instaled is plugins list.

### Wox Error Window text
<!-- 
     Paste below the logs generated by the Wox error reporter.

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\User\AppData\Roaming\Wox\Logs\1.3.524\2019-10-01.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\User\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/01/2019 11:20:45
Exception:
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) w C:\projects\wox\Wox.Core\Resource\Internationalization.cs:wiersz 89
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   w System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   w System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   w System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value, Boolean selectNow)
   w System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   w System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   w System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   w System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   w System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   w System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   w System.Windows.Data.BindingExpression.Activate(Object item)
   w System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   w System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   w MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   w MS.Internal.Data.DataBindEngine.Run(Object arg)
   w System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   w System.Windows.ContextLayoutManager.UpdateLayout()
   w System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   w System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   w System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   w System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   w System.Windows.Interop.HwndTarget.OnResize()
   w System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   w System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
