### ISSUE TITLE
Blacklist/delete search results

### ISSUE THREAD

**Issue by nbredikhin** [Wox-launcher/Wox#2615]
It would be very useful to blacklist/delete search results, so I can remove duplicate results, or things I don't need.

It could work like this: you type something, then select a search result, press 'Delete' or other key and it disapperas from search forever. Plus should be able to manage your blacklist in settings (or at least clear it).

What do you think?

**Comment by jjw24** [comment]
Hey how's it going.

This feature has been implemented in my fork. See if you like it: https://github.com/jjw24/Wox/releases/tag/v1.3.524%2BJJW24.v1.19.6

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases

you can edit ignore sequence in program settings
![image](https://user-images.githubusercontent.com/1169912/81978954-d6058680-965e-11ea-80e9-e2168ed0f796.png)
