### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Gwiths** [Wox-launcher/Wox#2617]
English version
Yes

step
1. Normally installed Everything
2. After installing Wox, open it and it get an error.

Error log:
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
X64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\love2\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/06/2019 23:31:28
Exception:
System.UnauthorizedAccessException: An attempt was made to perform an unauthorized operation.
   In Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   In Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   In the Wox.SettingWindow.SetStartup() location C:\projects\wox\Wox\SettingWindow.xaml.cs: line number 63
   In the Wox.App.AutoStartup() location C:\projects\wox\Wox\App.xaml.cs: line number 97
   In the Wox.App.<OnStartup>b__10_0() location C:\projects\wox\Wox\App.xaml.cs: line number 80
   In the Wox.Infrastructure.Stopwatch.Normal(String message, Action action) location C:\projects\wox\Wox.Infrastructure\Stopwatch.cs: line number 31
   In System.Windows.Application.OnStartup(StartupEventArgs e)
   In System.Windows.Application.<.ctor>b__1_0(Object unused)
   In System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   In System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

File at the end of the report.

中文版本：
是的

步骤
1.正常安装了Everything
2.安装Wox后，打开它就报错了

报错日志：
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17134.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\love2\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/06/2019 23:31:28
Exception:
System.UnauthorizedAccessException: 尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Wox.SettingWindow.SetStartup() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 63
   在 Wox.App.AutoStartup() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 97
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 80
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2019-10-06.txt](https://github.com/Wox-launcher/Wox/files/3694587/2019-10-06.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
