### ISSUE TITLE
Build failure: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by glenviewjeff** [Wox-launcher/Wox#2619]
#1475 # Steps to reproduce

1. Install VS 2019
2. Git clone Wox inside VS 2019
3. Open Wox.sln
4. Build solution
5. Notice namespace errors in Wox.Plugin.Program\Programs\UWP.cs, see lines 13-14, Windows.ApplicationModel and Windows.Management not found 

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0234	The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)	Wox.Plugin.Program	C:\Users\Jeff\source\repos\Wox2\Plugins\Wox.Plugin.Program\Programs\UWP.cs	13		Active

**Comment by glenviewjeff** [comment]
Ooops, guessing this is RTFM once you find TFM. 

Build:
1. Install Visual Studio 2015 and tick all Windows 10 sdk options
2. Open powershell with admin permission and Set-ExecutionPolicy Unrestricted -Scope CurrentUser

**Comment by glenviewjeff** [comment]
Well, following these instructions made no difference. Re-opening issue.

**Comment by glenviewjeff** [comment]
After installing the Windows 10 SDK options and doing a fresh git clone, I'm still getting this error.

**Comment by jjw24** [comment]
You need to get a specific Windows 10 SDK:
Download and install [Windows 10 SDK version 10.0.14393.795](https://go.microsoft.com/fwlink/p/?LinkId=838916).

**Comment by glenviewjeff** [comment]
Thanks much; can we please add this to the build instructions?

**Comment by jjw24** [comment]
Yes there is a PR for this actually, but this repo hasn't been maintained for a while. Feel free to use my branch https://github.com/jjw24/Wox it's been actively developed.

**Comment by bao-qian** [comment]
try new version from master, which use vs 2019
