### ISSUE TITLE
Both fonts change simultaneously in theme settings

### ISSUE THREAD

**Issue by sausagemountain** [Wox-launcher/Wox#2620]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Install latest version of windows (1903 with .net 4.8 only)
2. Install wox (tested release, pre-release and latest AppVeyor build)
3. Theme screen does not have example items
4. Changing one font changes both

### Detailed logs

[2019-10-08.txt](https://github.com/Wox-launcher/Wox/files/3703404/2019-10-08.txt)
(drop your log file here)

### Screenshots (optional)

![2019-10-08 210805](https://user-images.githubusercontent.com/22707290/66412939-e5a95680-ea0f-11e9-8eff-3128b3f86647.png)

**Comment by bao-qian** [comment]
this has been fixed
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
