### ISSUE TITLE
样子货，实在是差劲，比listary差远了

### ISSUE THREAD

**Issue by 2472289148** [Wox-launcher/Wox#2627]
快捷键不能识别双击ctrl键启动，文件夹内没有专门的搜索框，虽然调用了everthing搜索但是我搜一个桌面上的文件夹首先映入眼帘的却是乱七八糟的其他文件夹。被网站洗脑删了listary装这个，现在还得把人家请回来

**Comment by Sloaix** [comment]
@2472289148 开源软件，觉得不好用可以不用，没必要诋毁。

**Comment by 2472289148** [comment]
嗯嗯，对不起



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lsxiao"<notifications@github.com&gt;; 
发送时间: 2019年10月20日(星期天) 晚上10:08
收件人: "Wox-launcher/Wox"<Wox@noreply.github.com&gt;; 
抄送: "2472289148"<2472289148@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Wox-launcher/Wox] 样子货，实在是差劲，比listary差远了 (#2627)




@2472289148 开源软件，觉得不好用可以不用，没必要诋毁。

**Comment by bao-qian** [comment]
close due to not related.
