### ISSUE TITLE
Any idea to port to mono?

### ISSUE THREAD

**Issue by hongxuchen** [Wox-launcher/Wox#263]
Have you ever considered porting Wox to mono so that Linux users can also benefit from it? [kupfer](http://engla.github.io/kupfer/) is super, but not the alfred way; unfortunately I have not found other launchers as powerful and _neutral_ as that.

**Comment by orzFly** [comment]
[WPF is not available on Mono](http://www.mono-project.com/docs/gui/wpf/)...

**Comment by hongxuchen** [comment]
Sorry about that :disappointed:
