### ISSUE TITLE
Wox - Unhandled Exception （索引相关）

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#264]
罗技鼠标更新后就一直报这个错。
手动查看 `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Logitech` ， 发现只有8.58版本，没有报错信息里的8.51版本。
那么有什么办法能强制刷新索引吗?
![Exception](http://i.imgur.com/2O5YF7R.png)

PS：这个这个报错窗口弄个滑动条吧。

**Comment by russelg** [comment]
Re-index the program plugin.

**Comment by bao-qian** [comment]
@kz-lt program plugin is used for custom location, it won't fix this exception.

**Comment by qianlifeng** [comment]
This bug has been fixed in V1.2.0-beta. Pls try that version
