### ISSUE TITLE
[Controlpanel] Localized Entries

### ISSUE THREAD

**Issue by RalfRoemling** [Wox-launcher/Wox#2647]
Hi Overthere, 
great launcher :-)

Just noticed that I can only access Controlpanel-items with their English names, but not with the installed language, here German.

Is there any way how I may add the translated terms?

**Comment by bao-qian** [comment]
you probally need to change windows display language and change wox language.

Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
