### ISSUE TITLE
wox打开后一定会在桌面上生成快捷方式的吗？

### ISSUE THREAD

**Issue by ZhouJian1683** [Wox-launcher/Wox#2648]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.
