### ISSUE TITLE
Python plugins results duplication

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#265]
e.g. if I write "caniuse <query>" and before results loaded fast delete query and type it again, I see 2 or more identical items.
it's my bug or Wox bug? :confused:

**Comment by qianlifeng** [comment]
This should be a Wox bug, I will look into this when I have time.

**Comment by bao-qian** [comment]
@roose Try the Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
