### ISSUE TITLE
wox error

### ISSUE THREAD

**Issue by gle2n** [Wox-launcher/Wox#2655]
Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\the-g\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 11/20/2019 11:53:06
Exception:
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à WoxSteam.Steam.LoadLibraries() dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:ligne 180
   à WoxSteam.Steam.Load() dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:ligne 56
   à WoxSteam.Main.Init(PluginInitContext context) dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:ligne 60
   à Wox.Infrastructure.Stopwatch.Debug(String message, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 18
   à Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) dans C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:ligne 93
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   à System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   à Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) dans C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:ligne 91
   à Wox.App.<OnStartup>b__10_0() dans C:\projects\wox\Wox\App.xaml.cs:ligne 60
   à Wox.Infrastructure.Stopwatch.Normal(String message, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 31
   à System.Windows.Application.OnStartup(StartupEventArgs e)
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Exception interne #0) System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à WoxSteam.Steam.LoadLibraries() dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:ligne 180
   à WoxSteam.Steam.Load() dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Steam.cs:ligne 56
   à WoxSteam.Main.Init(PluginInitContext context) dans c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:ligne 60
   à Wox.Infrastructure.Stopwatch.Debug(String message, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 18
   à Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) dans C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:ligne 93
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by SysC0mp** [comment]
Please try to remove the steam plugin as it seems to be causing your issues.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
