### ISSUE TITLE
How to install a plugin from its source code?

### ISSUE THREAD

**Issue by Francesco270** [Wox-launcher/Wox#2658]
How can I install a Wox plugin from its source code on github? Usually there is a .wox file in the releases page, but that's not always the case. I know that a .wox file is just a zip file renamed, however the files inside the .wox are not the same as those on the source code page.
This is an example: https://github.com/lances101/Wox.Plugin.GoogleTranslate
This plugin doesn't work anymore but there is this fork (https://github.com/sobujbd/Wox.Plugin.GoogleTranslate) which might be updated. But there isn't a .wox file and just download the source code, then zip it and convert it to .wox doesn't work.
Any help please? Thank you

**Comment by theClueless** [comment]
if you download it and compile it and take the output and copy into your plugin folder (%APPDATA%\Wox\Plugins) it should work for you.

**Comment by Francesco270** [comment]
> if you download it and compile it and take the output and copy into your plugin folder (%APPDATA%\Wox\Plugins) it should work for you.

I've tried to compile it in Visual Studio but I didn't get the expected result unfortunately.

**Comment by bao-qian** [comment]
you need compile or ask plugin author.
