### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by Leosirth** [Wox-launcher/Wox#266]
Hello,

I think would be useful the possibility to run multiple commands within a single Wox query.
i.e. running the "closescreen" plugin command followed by "lock" command.

A possible syntax could be:
`<query1> & <query2>`
Or something similar.

Thank you for this great SW.
Regards.

**Comment by qianlifeng** [comment]
How would the results show if we support the multiple commands? Like this?
`----------------------------`
`<query1>` & `<query2>`
`----------------------------`
result item from `<query1>`
`----------------------------`
result item from `<query1>`
`----------------------------`
result item from `<query2>`
`----------------------------`

**Comment by Leosirth** [comment]
I think of something like:

While typing the first command showing the results as usual, when the & is typed than fix on the first line the choosed result from query1 and showing down the results only for query2 and so on.
Following a small mockup:

![query1](https://cloud.githubusercontent.com/assets/800911/6937312/08002ec8-d85b-11e4-88de-ec8b6f2335d0.png)

![query2](https://cloud.githubusercontent.com/assets/800911/6937314/0c3844b2-d85b-11e4-8628-b0b80b7cd5ca.png)

**Comment by bao-qian** [comment]
I don't think this is useful.
