### ISSUE TITLE
Is Wox still actively developed\maintained? 

### ISSUE THREAD

**Issue by theClueless** [Wox-launcher/Wox#2661]
Hi,

I see that Wox is not really active development wise in this repository. was it abandoned ? 
I'm since I just discovered it and it seems like a great tool and I did some development and added the work to a fork which is active - https://github.com/jjw24/Wox
Is it possible to start taking changes from this fork? or maybe add more people to the Wox project so we can add content and features?

@jhdxr @bao-qian @lances101  @qianlifeng tagging you as you are the members of the WOX team.

**Comment by SysC0mp** [comment]
That would be great. Wox is an awesome tool but still has a lot of room for improvement / new features. I could help, too. 👍

**Comment by Francesco270** [comment]
I think we need more work on plugins, lots of them are outdated.

**Comment by bao-qian** [comment]
no it was not abandoned.
yes, I can take change from this fork, open the pr, then I will take a look.

**Comment by SysC0mp** [comment]
It is maybe not abandoned, but a lot of the last pull requests did not make it into this repository.
There are still a lot of them open and the issue list is getting more and more.
Therefore it would eventually be good to add more people with write access to this. 

What do you think?

**Comment by theClueless** [comment]
When I compare the current state of the fork of @jjw24 there are many changes (some of them are already pull request which were opened on August here)  -

![image](https://user-images.githubusercontent.com/14300910/70039661-f9fa7180-15c2-11ea-9193-7bff4d558f7a.png)

I really want that his work (@jjw24) will enter the main trunk so everyone can benefit from it and I would like to help (and I'm sure that @jjw24 would love for his changes to get in as he invested a lot in those).
What do you think we can do to help?

**Comment by kid1412621** [comment]
I saw newest PRs are accepted last couple months.  However the last release is last year.

**Comment by SysC0mp** [comment]
Any updates on that?

**Comment by bao-qian** [comment]
> When I compare the current state of the fork of @jjw24 there are many changes (some of them are already pull request which were opened on August here) -
> 
> ![image](https://user-images.githubusercontent.com/14300910/70039661-f9fa7180-15c2-11ea-9193-7bff4d558f7a.png)
> 
> I really want that his work (@jjw24) will enter the main trunk so everyone can benefit from it and I would like to help (and I'm sure that @jjw24 would love for his changes to get in as he invested a lot in those).
> What do you think we can do to help?

yes he make some great pr for wox.
all his pr will be merged within one month.
really busy last year, will back to work again :)

**Comment by NickSeagull** [comment]
Perhaps, in order to avoid questions like this we can setup a CI/CD system to make automatic releases? I can make an issue about it if you want, and try implementing it.

Also, for questions, maybe spectrum.chat is better so we can use the issues to track the bugs, etc...?

**Comment by theClueless** [comment]
@bao-qian Any update on this?

**Comment by T3rm1** [comment]
Since he just closed the issue without answering why nothing has been merged until now, I think this project is officially dead. Too bad.

**Comment by NickSeagull** [comment]
There is an effort going on to revive Wox, and to improve the interaction between users of Wox and maintainers, making the project much more open in the contributions and communication part.

Please take a look at https://github.com/jjw24/Wox/issues/156 and vote in the case that you agree :)

**Comment by bao-qian** [comment]
Hi guys,

https://github.com/Wox-launcher/Wox/releases

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr and contribution from https://github.com/jjw24/Wox has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/81972789-b61d9500-9655-11ea-8f2e-ecbf53ab57df.png)


@theClueless 
@SysC0mp 
@Francesco270 
@kid1412621 
@NickSeagull 
@T3rm1 

@Kalaschnik

**Comment by NickSeagull** [comment]
Thanks for pointing this @bao-qian . I think that it is important that the project is open enough and has established process so everyone can contribute and you don't become overwhelmed by work, this should be a fun experience, and delegating everything on you won't make it fun for you 😅

**Comment by bao-qian** [comment]
@NickSeagull 
This is a open source project, everyone can contribute with pull request or discuss in issue.
And I welcome active committer/contributor to be part of `Wox-launcher` org member.

**Comment by NickSeagull** [comment]
Yes, I meant that there are times that you don't have the time to respond, and that's absolutely understandable, because you have your life, and this shouldn't be your priority. There is already some work going on to rebuild organizational stuff at http://github.com/flow-launcher, and perhaps it'd be a great time to merge both communities, and create organization members.

I love the work you are doing, and I'm very grateful for the effort you are putting into this project, that's why I wanted for us, the community, to relieve you a little bit :)

**Comment by bao-qian** [comment]
@NickSeagull 
sounds a good idea, probably a separate issue for further discussion?
