### ISSUE TITLE
搜索完文件后右键查看所属文件夹无法返回

### ISSUE THREAD

**Issue by BayMRX** [Wox-launcher/Wox#2662]
已知问题及解决方案：
搜索文件后，右键文件打开所属文件夹，就无法返回起始界面了，也无法在进行新的搜索了，只有退出程序重新打开才可以。

### Steps to reproduce
1.Alt+Space打开程序
2.输入文件进行搜索
3.找到后对文件候选项右键，进入二级菜单（包括打开所属文件夹、在当前查询中置顶等等）
4. 进入二级菜单后就没有办法返回了，只能重新启动程序

### Detailed logs
[2019-11-27.txt](https://github.com/Wox-launcher/Wox/files/3896366/2019-11-27.txt)
### Screenshots (optional)
![QQ截图20191127174220](https://user-images.githubusercontent.com/41069495/69716008-2f770900-1144-11ea-8ef3-f09a3f3d9401.png)

#########################################################
Google Translation：
Known issues and solutions:
After searching for a file, right-click the file to open the folder it belongs to, you cannot return to the initial interface, and you cannot perform a new search. You can only open the program and reopen it.

### Steps to reproduce
1.Alt + Space Open Program
2. Enter files to search
3. Right-click the file candidate after you find it, and enter the secondary menu (including opening the folder to which it belongs, top in the current query, etc.)
4. There is no way to return after entering the secondary menu, only restart the program

### Detailed logs
[2019-11-27.txt] (https://github.com/Wox-launcher/Wox/files/3896366/2019-11-27.txt)
### Screenshots (optional)
! [QQ screenshot 20191127174220] (https://user-images.githubusercontent.com/41069495/69716008-2f770900-1144-11ea-8ef3-f09a3f3d9401.png)

**Comment by Randool** [comment]
对！这个问题很困扰。每次都要重新启动wox才能正常使用。

**Comment by AZE98** [comment]
Try press ESC.

**Comment by Randool** [comment]
@AZE98 Thanks a lot!

**Comment by Darkrains0314** [comment]
> 试着按下ESC。

hhhhh，so easy

**Comment by bao-qian** [comment]
Try press ESC.
