### ISSUE TITLE
upload log file: C:\Users\Administrator\AppData\Roaming\Wox\Logs\1.3.578\2085-10-03.txt

### ISSUE THREAD

**Issue by HBK-Aiyuchengjingyesi** [Wox-launcher/Wox#2664]
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.10586.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 11/28/2019 19:45:31
Exception:
System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.Assembly.GetTypes()
   在 Wox.Core.Plugin.PluginsLoader.<>c__DisplayClass4_1.<CSharpPlugins>b__1() 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 55
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 84
   在 Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 22
   在 Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 85
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
