### ISSUE TITLE
Wox is dead, if you need a good keystroke for windows download Ueli on electron.

### ISSUE THREAD

**Issue by BithSachs** [Wox-launcher/Wox#2667]
bye wox

**Comment by EricSUID** [comment]
0.0

**Comment by LoZeno** [comment]
Ueli still has issue with custom scalings and with launching apps downloaded from the Windows Store (e.g. it can't always detect that Windows Terminal has been installed). It's a promising app, but in my experience Wox is way more stable for now, even if it's unmaintained.
YMMV though.

**Comment by bao-qian** [comment]
close due to unrelated
