### ISSUE TITLE
Add support for searching Outlook Mails

### ISSUE THREAD

**Issue by MisterMountain** [Wox-launcher/Wox#2670]
Hey, i just discovererd Wox and i definitely love the use of Wox. Only thing what i miss is searching in my mails in MS Outlook...

**Comment by SysC0mp** [comment]
Feel free to open a feature request as an issue on following fork: https://github.com/jjw24/Wox
It is actively maintained at the moment.

**Comment by bao-qian** [comment]
hi, this should be implemented as plugin
