### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by mmsouzatx** [Wox-launcher/Wox#2673]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\mauri\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/08/2019 17:42:59
Exception:
System.AggregateException: Um ou mais erros. ---> System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em WoxSteam.Options.Load() na c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:linha 35
   em WoxSteam.Main.Init(PluginInitContext context) na c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:linha 60
   em Wox.Infrastructure.Stopwatch.Debug(String message, Action action) na C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:linha 18
   em Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) na C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:linha 93
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   em System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   em System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   em System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   em Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) na C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:linha 91
   em Wox.App.<OnStartup>b__10_0() na C:\projects\wox\Wox\App.xaml.cs:linha 60
   em Wox.Infrastructure.Stopwatch.Normal(String message, Action action) na C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:linha 31
   em System.Windows.Application.OnStartup(StartupEventArgs e)
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Exceção Interna N° 0) System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em WoxSteam.Options.Load() na c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Options.cs:linha 35
   em WoxSteam.Main.Init(PluginInitContext context) na c:\Users\Kamen\dev\Wox.Plugin.Steam\WoxSteam\Main.cs:linha 60
   em Wox.Infrastructure.Stopwatch.Debug(String message, Action action) na C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:linha 18
   em Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) na C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:linha 93
   em System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
[2019-12-08.txt](https://github.com/Wox-launcher/Wox/files/3937135/2019-12-08.txt)

(drop your screenshot here)

**Comment by iamzhengkai** [comment]
got the same error

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
