### ISSUE TITLE
Error: Access is Denied

### ISSUE THREAD

**Issue by aspen1135** [Wox-launcher/Wox#2674]
I know this should be a fairly easy user-error to troubleshoot. I am on a new windows 10 installation coming from Windows 7 and I am not sure if the permissions systems have been modified since W7.

It says Wox cannot access the directory I am searching for. I only saw one other thread regarding this issue and provided a solution, saying to allow read access for Wox, but I am unable to determine exactly how to do this.

I believe that Wox also runs on another application, Everything, as a framework to run it's searches. I ensured both programs are running as administrators so it should have elevated the permissions to search in all locations on the OS.

How can I give Wox read permissions for my entire HD?

![image](https://user-images.githubusercontent.com/17952043/70411659-b3b07280-1a07-11ea-8d84-6a4878d481c5.png)

**Comment by bao-qian** [comment]
use c:\users\yourusername\Documents instead of `My Document`, `My Document` is not used anymore in win10.
