### ISSUE TITLE
Something to execute in shell as admin without right clicking into context menu? 

### ISSUE THREAD

**Issue by orionv** [Wox-launcher/Wox#2677]
On Windows 10, I use "> x" to run commands in powershell all the time. Problem is I almost always need to be running with admin privileges. I can right click and choose 'run as admin' but then I have to get my mouse involved which kind of takes away a lot of the point of Wox and also involves me having to go through an entire separate menu step. Any way to get this in hotkey form, so maybe I'd just type ">> x" to run as admin?

**Comment by SysC0mp** [comment]
You can use "Shift+Enter" to show the context menu for any search result.

**Comment by jjw24** [comment]
You can use this version of Wox which has the option to set shell plugin to execute commands always as admin. Also has the option to run as different user in context menu: https://github.com/jjw24/Wox/releases

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
new version has the 
![image](https://user-images.githubusercontent.com/1169912/81975904-4cec5080-965a-11ea-8a62-c3a38b72726d.png)
