### ISSUE TITLE
Problem when using custom ConfigurationSection to read from App.Config file

### ISSUE THREAD

**Issue by Ridermansb** [Wox-launcher/Wox#268]
When trying to read custom configurations from App.settings file an error occurs:

```
public class ConfigurationManagerWrapper : IConfigurationManager
{
    // .. Implementations ommited
    public ProjectFoldersSection GetProjectFoldersSection(string sectionName)
    {
        var pluginPath = this.GetType().Assembly.Location.Substring(0, this.GetType().Assembly.Location.LastIndexOf('\\'));
        var config = ConfigurationManager.OpenMappedExeConfiguration(new ExeConfigurationFileMap{ ExeConfigFilename = Path.Combine(pluginPath, "App.config")}, ConfigurationUserLevel.None);
        return (ProjectFoldersSection)config.GetSection(sectionName); // **ERROR HERE**
    }
}
```

Wox [uses reflection to load the plugin](https://github.com/qianlifeng/Wox/blob/89945c0721e8aa6a41148a5ff5cb6f1577555d4a/Wox/PluginLoader/CSharpPluginLoader.cs), this causes that some classes are not loaded. For exemple: 

```
public class ProjectFoldersSection : ConfigurationSection
{
    // .. Implementations ommited
}

[ConfigurationCollection(typeof(ProjectFolder), CollectionType = ConfigurationElementCollectionType.BasicMapAlternate)]
public class ProjectsFoldersCollection : ConfigurationElementCollection
{
    // .. Implementations ommited
}
```

Maybe [this post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1d3962b1-11c7-4090-aee6-d39413c15869/problem-when-using-activatorcreateobject-and-reading-appconfig-file?forum=netfxbcl&prof=required) can help

**Comment by Ridermansb** [comment]
Another link: http://stackoverflow.com/a/1688677/491181

**Comment by Ridermansb** [comment]
I made a fork to try to resolve.
Loading the assembly to the domain, but still did not solve, see commit  2926cff3a7b41ef62cab66e29766c60d2dd1f8e7

Any idea?

**Comment by bao-qian** [comment]
Which assembly you want to load?
Which classes are not loaded?
OS version?
Try [1.2beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)
