### ISSUE TITLE
custom aliases?

### ISSUE THREAD

**Issue by ak1dd** [Wox-launcher/Wox#2684]
I have a script that I run regularly.   There are a lot of things found when I invoke Wox and I have to scroll a lot or keep typing a full filename.   Is it possible to have custom aliases like Alfred so I could do something like:   type "MYS"  would invoke myscript.cmd?

**Comment by bao-qian** [comment]
1 put your script in some folder, 
2 then add your folder in program plugin
3 change program extension to include .cmd
