### ISSUE TITLE
Remember the last input

### ISSUE THREAD

**Issue by slackzh** [Wox-launcher/Wox#269]
for example

When input "amcap" first time, amcap.exe appear as line 6. 

Next time when i want to open amcap.exe again, I still need input complete word "amcap", and navigatie to line 6

Launchy has a feature that remember last input, if i input "am" next time, the amcap.exe will show as line 1, it is convenience to start a program.

**Comment by qianlifeng** [comment]
Wox will remember the selected programs. for example, you input "am" and select "amcap" at line 6, the next time you input "am", "amcap" will show as line 1.

**Comment by sevenam** [comment]
Tested a bit on this with "word.exe" and "excel.exe" in Wox 1.2.0 beta.

After typing "wo" and "ex" and choosing Word and Excel from the list about 10 times, Word and Excel would be moved from number 3 to number 1 on the result list.

**Comment by bao-qian** [comment]
duplicate: #315
