### ISSUE TITLE
Weird line under query box

### ISSUE THREAD

**Issue by ak1dd** [Wox-launcher/Wox#2690]
Love Wox.

On a dark background or window, there is a one pixel white line that is drawn.  It isn't shown in the Theme preview under settings.

I know this is minor, but it is ugly on an all flat theme.
![Wox](https://user-images.githubusercontent.com/38289720/71528869-ceec0080-2896-11ea-842a-c71a6af664ec.jpg)

**Comment by theClueless** [comment]
It is the progress bar, when you have a long time query, you will see the line changing showing Wox is processing.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
