### ISSUE TITLE
建议：在使用everything插件搜索时，增加复制选项

### ISSUE THREAD

**Issue by taooceros** [Wox-launcher/Wox#2691]
希望能在搜索文件的时候增加一项操作，用来复制/剪切文件，相比打开文件所在位置可以很好地增加效率

**Comment by bao-qian** [comment]
shift enter or right click

**Comment by Leezj9671** [comment]
> shift enter or right click

没有复制选项

**Comment by bao-qian** [comment]
looks like your issue has already been resolved in #2934
so this issue remain close.
@Leezj9671
> 
> 
> > shift enter or right click
> 
> 没有复制选项
