### ISSUE TITLE
Wox: Exception during login

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2695]
I have Wox set to launch at startup. This exception happens every single time I log into Windows.

If I close the Exception dialog box and launch Wox manually everything works as expected.

Wox Version: 1.3.524
Windows Version: Windows 10 Home 1909 18363.535

![wox](https://user-images.githubusercontent.com/82423/71766557-1560e100-2ecf-11ea-8e8a-14242fea2e5e.png)

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   at Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Wox
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Wox.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Wox.Infrastructure
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Wox.Infrastructure.DLL
----------------------------------------
Wox.Plugin
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Wox.Plugin.DLL
----------------------------------------
Wox.Core
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Wox.Core.DLL
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/NLog.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Pinyin4Net
    Assembly Version: 2016.4.24.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Pinyin4Net.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Wox.Plugin.Caculator
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Caculator/Wox.Plugin.Caculator.dll
----------------------------------------
Mages.Core
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Caculator/Mages.Core.DLL
----------------------------------------
Wox.Plugin.Color
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Color/Wox.Plugin.Color.dll
----------------------------------------
Wox.Plugin.ControlPanel
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.ControlPanel/Wox.Plugin.ControlPanel.dll
----------------------------------------
Wox.Plugin.Everything
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Everything/Wox.Plugin.Everything.dll
----------------------------------------
Wox.Plugin.Folder
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Folder/Wox.Plugin.Folder.dll
----------------------------------------
Wox.Plugin.PluginIndicator
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.PluginIndicator/Wox.Plugin.PluginIndicator.dll
----------------------------------------
Wox.Plugin.PluginManagement
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.PluginManagement/Wox.Plugin.PluginManagement.dll
----------------------------------------
Wox.Plugin.Program
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Program/Wox.Plugin.Program.dll
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
Windows.Management
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Management.winmd
----------------------------------------
Wox.Plugin.Shell
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Shell/Wox.Plugin.Shell.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
WindowsInput
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/WindowsInput.DLL
----------------------------------------
Wox.Plugin.Sys
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Sys/Wox.Plugin.Sys.dll
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
Windows.Storage
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Storage.winmd
----------------------------------------
Wox.Plugin.Url
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.Url/Wox.Plugin.Url.dll
----------------------------------------
Wox.Plugin.WebSearch
    Assembly Version: 1.3.524.0
    Win32 Version: 1.3.524
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Plugins/Wox.Plugin.WebSearch/Wox.Plugin.WebSearch.dll
----------------------------------------
Wox.Plugin.Clipboard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/reed/AppData/Roaming/Wox/Plugins/Clipboard%20History-553516be-41d7-4207-bf10-cd37bf8288ac/Wox.Plugin.Clipboard.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
WindowsInput
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///C:/Users/reed/AppData/Roaming/Wox/Plugins/Clipboard%20History-553516be-41d7-4207-bf10-cd37bf8288ac/WindowsInput.DLL
----------------------------------------
NHotkey
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.1.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/NHotkey.DLL
----------------------------------------
NHotkey.Wpf
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.1.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/NHotkey.Wpf.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
Squirrel
    Assembly Version: 1.5.2.0
    Win32 Version: 1.5.2.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/Splat.DLL
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/reed/AppData/Local/Wox/app-1.3.524/NuGet.Squirrel.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
