### ISSUE TITLE
incorrect application search results

### ISSUE THREAD

**Issue by egenchen** [Wox-launcher/Wox#270]
I am a new user using beta 1.2.0 version

when i search "proce", i excepting searching for "procexp.exe", but the search result is incorrect.

the last three program in the first screen didn't appear have any keyword like "proce", and the real "procexp.exe" result is near the very bottom.

http://i.imgur.com/TMQ8u1m.png

**Comment by qianlifeng** [comment]
Wox use fuzzy match when searching programs (not everything plugin), it will match your title and sub title. Take your screenshot as example:

![http://i.imgur.com/MD113CT.png](http://i.imgur.com/MD113CT.png)

For the second screenshot, I believe it's returned by everything pluin. For Everyhing plugin results, results returned by everything program. 
![http://i.imgur.com/Qd9tVds.png](http://i.imgur.com/Qd9tVds.png)

**Comment by Leosirth** [comment]
Would be usefull the possibility to enable / disable the fuzzy match in the settings on behalf of exact match results.

**Comment by egenchen** [comment]
It's very clearly how the fuzzy match works, it will be very useful while searching for something.

I had disabled the everything plugin(and had set the "f" keyword for it), the search result is the same as above.
I think the last "procexp.exe" should got a higher score than the "hprof-conv.exe".

Then I manually select the "procexp" item, I can see the item's position moved above. After 5 times, I can see the "procexp" item on the first page. I'd like that the item became the first if I manually selected.

**Comment by egenchen** [comment]
Found another issue while using fuzz match.
I added the suffix: "xsh" to the application search engine for my xshell sessions.
But seems that the fuzz match won't match the "xsh".
As the image show below, I have an session with name: "192.168.1.88.xsh". Enter "88" can see my item in the result, but when I input "88.xsh" or "88xsh", it can't show any result.
Is their anything I missing ?

http://imgur.com/FTQVicf

**Comment by byzeus2014** [comment]
我安装了"广发证券"软件, 输入gf的时候, 搜索结果里面找不到这个软件.
1. 输入guang, 能够找到这个软件, 见下图
![untitled](https://cloud.githubusercontent.com/assets/8944612/7426296/943af17e-eff4-11e4-93ad-5edac277c0fb.png)
1. 输入gf, 就找不到了.  见下图, 我把滚动条的内容都截取了.
   ![untitled2](https://cloud.githubusercontent.com/assets/8944612/7426312/d68b28d2-eff4-11e4-8fcf-2ce5397747c4.png)

![3](https://cloud.githubusercontent.com/assets/8944612/7426315/dd88f8f8-eff4-11e4-9c69-be97dc4c862b.png)

![4](https://cloud.githubusercontent.com/assets/8944612/7426317/e298f1cc-eff4-11e4-9f40-0a00029ccccf.png)

**Comment by bao-qian** [comment]
can't use proce for procexp.exe.
bug confirmed.

**Comment by bao-qian** [comment]
Hi @egenchen @Leosirth @byzeus2014, I fixed this.
Please try latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history)     (top green build -> artifacts -> release-binary.zip).

![f _3 n d jx m8acjifg](https://cloud.githubusercontent.com/assets/1169912/11085326/d97a07bc-883c-11e5-88d6-ca827fa85275.png)
