### ISSUE TITLE
error

### ISSUE THREAD

**Issue by transparent1998** [Wox-launcher/Wox#2704]
### Are you submitting a bug report?
yes
(write your answer here)

### Steps to reproduce

1.Reinstall the windows
2.install Wox
3.restart windows

### Wox Error Window text

(paste here)
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 01/22/2020 15:57:15
Exception:
System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   在 System.IO.Path.Combine(String path1, String path2)
   在 Wox.Core.Plugin.PluginsLoader.PythonPlugins(List`1 source, String pythonDirecotry) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 119
   在 Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:行号 22
   在 Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 85
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2020-01-22.txt](https://github.com/Wox-launcher/Wox/files/4095905/2020-01-22.txt)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
