### ISSUE TITLE
it's this project dead?

### ISSUE THREAD

**Issue by ctwhome** [Wox-launcher/Wox#2712]

**Comment by rewired-gh** [comment]
Definitely dead.

**Comment by kalaschnik** [comment]
Check https://github.com/jjw24/Wox/ for updates on Wox

**Comment by skjerns** [comment]
> Check https://github.com/jjw24/Wox/ for updates on Wox

thanks! why are there two repositories

**Comment by kalaschnik** [comment]
> > Check https://github.com/jjw24/Wox/ for updates on Wox
> 
> thanks! why are there two repositories

jjw24’s repo is a fork from the official one. I don’t know but it seems that the author of the official plugin is not active anymore. Meanwhile, I guess, I would stick to jjw24’s repo.

**Comment by bao-qian** [comment]
not dead. https://github.com/Wox-launcher/Wox/issues/2661#issuecomment-574554531
duplicate of https://github.com/Wox-launcher/Wox/issues/2712

**Comment by bao-qian** [comment]
Hi guys,

https://github.com/Wox-launcher/Wox/releases

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr and contribution from https://github.com/jjw24/Wox has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/81972789-b61d9500-9655-11ea-8f2e-ecbf53ab57df.png)


@ctwhome 
@h0gan1ee 
@Kalaschnik 
@skjerns

**Comment by ctwhome** [comment]
holy molly! @bao-qian thanks for the update! and congrats for the work!
