### ISSUE TITLE
search within the target folders with file names and open in the editor

### ISSUE THREAD

**Issue by veeramarni** [Wox-launcher/Wox#2713]
### Are you submitting a bug report? No

(write your answer here)

Is there something that can search within a folder and open the selected file in one of the editor like notepad++ or sublime?

Similar to https://github.com/deanishe/alfred-sublime-text plugin

**Comment by ghost** [comment]
Yes, You need to install Everything and Everything Plugin for wox

**Comment by veeramarni** [comment]
@VivekKPatel What you mean by "Everything Plugin", I could not find that plugin.

**Comment by ghost** [comment]
@veeramarni  Install this https://www.voidtools.com/

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
