### ISSUE TITLE
Everything Plugin Can't open this file (folders)

### ISSUE THREAD

**Issue by Microdeal32** [Wox-launcher/Wox#2717]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.Search using everything plugin
2.Items are foumds
3.Folder can not be opened. I can open any file but folders. Is I open the parent folder of a file it opens.

### Wox Error Window text

Plugin: Everything
Can't open this file
[2020-02-02.txt](https://github.com/Wox-launcher/Wox/files/4143722/2020-02-02.txt)
![Anotación 2020-02-02 094631](https://user-images.githubusercontent.com/60566711/73605633-eeb2ca80-45a0-11ea-9f84-40ed61c9258b.png)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
