### ISSUE TITLE
Command to list all available action keywords

### ISSUE THREAD

**Issue by sahwar** [Wox-launcher/Wox#272]
It would be nice if there is a command that shows us a list of all action keyword triggers (the built-in and the ones provided by installed plug-ins) and their basic syntax arguments (if any).

Is something like that already available in Wox?

Maybe something like 'wox help kwt'? :)

P.S. I'm sorry in advance if this is a dumb question and something like that already exists, I just couldn't find it in the Wox Docs...

**Comment by qianlifeng** [comment]
https://github.com/qianlifeng/Wox/tree/dev/Plugins/Wox.Plugin.PluginIndicator is doing that, but a kind of different. This plugin will show available commands only after you input  parts of the command

 ![http://i.imgur.com/ogYI0C1.png](http://i.imgur.com/ogYI0C1.png)

**Comment by bao-qian** [comment]
use wpm list
![2015-11-03_17-58-22](https://cloud.githubusercontent.com/assets/1169912/10916694/91a98c84-8254-11e5-84b3-b5f06c44b6e6.png)

**Comment by sahwar** [comment]
@happlebao Wonderful, I'll test it as soon as possible! :+1:

**Comment by bao-qian** [comment]
@sahwar although wpm in [v1.2beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)
won't handle Shell plugin and Web search plugin correctly, it will be fixed when 1.2 out.
Within one month.
