### ISSUE TITLE
Impossible to calculate single digit factorial through the calculator

### ISSUE THREAD

**Issue by qwertyuu** [Wox-launcher/Wox#2720]
### Steps to reproduce

write `8!`

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/3145639/73803004-6a716a80-478d-11ea-88dd-294d73e110d2.png)

**Comment by qwertyuu** [comment]
The code for the calculator plugin seems to only trigger if the input length is larger or equal to 3, which is not the case here with this very valid calculator input.

**Comment by qwertyuu** [comment]
Workaround: Write `08!`. Gives right answer and opens the calculator.

![image](https://user-images.githubusercontent.com/3145639/73803447-d30d1700-478e-11ea-9f05-b4ac8141b43b.png)

**Comment by elhosayny** [comment]
I fixed it by changing [this line](https://github.com/Wox-launcher/Wox/blob/7e3a30c5ce0563a655dd8db72896edc52308838f/Plugins/Wox.Plugin.Calculator/Main.cs#L31) but I'm not sure if that would affect other parts.

```csharp
if (query.Search.Length <= 1  // updated the number from 2 to 1
                || !RegValidExpressChar.IsMatch(query.Search)
                || !IsBracketComplete(query.Search)) return new List<Result>();
```
This is the result : 

<img width="604" alt="Wox" src="https://user-images.githubusercontent.com/8279101/74194698-11587980-4c5a-11ea-8f6f-c7978f1bd72f.PNG">

**Comment by qwertyuu** [comment]
@elhosayny Is there a PR?

**Comment by elhosayny** [comment]
@qwertyuu  Not yet I will create one tomorrow

**Comment by qwertyuu** [comment]
@elhosayny Make sure you link it here I'll 👍 it! 😸

**Comment by elhosayny** [comment]
Sure I will

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
