### ISSUE TITLE
Display Wox on Key-Up instead Key-Down

### ISSUE THREAD

**Issue by skjerns** [Wox-launcher/Wox#2722]
I have the Windows key as a hotkey for Wox.

However, it always pops up on key-down when I do any other Windows-hotkey (win+r, win+d, ...). 

This is just a cosmetic issue, as it dissapears after I press the hotkey. Still, I would like to know if there is a setting to activate Wox only on key up and if there is no other hotkey, and not on key-down.

**Comment by bao-qian** [comment]
Hi, this is not possible right now. pr is welcome.
