### ISSUE TITLE
插件(C#)中有可以退出右键菜单，返回搜索模式的API可以调用吗？

### ISSUE THREAD

**Issue by enria** [Wox-launcher/Wox#2723]
或者有什么方法可以实现呢？
Everything插件中的右键菜单，打开所在文件夹后，再次打开Wox，还是处于上次的右键菜单。请问这样的设计是出于什么样的考虑呢？为什么不是退出菜单，清空搜索框，来准备下一次新的搜索呢？

Does it has any api, for plugin devleloping,  which let application exit context menus and back to search mode?

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
it should work as you expected.
