### ISSUE TITLE
Since the primary mouse button is pressed, only DragMove can be called

### ISSUE THREAD

**Issue by mcanyucel** [Wox-launcher/Wox#2725]
Hey;
I have been told to open a new issue for this error by the program itself, so here we are.
One problem is that the error messages down are in my OS language (Turkish), but what is says is that "Since the primary mouse button is pressed, only DragMove can be called".
What happened is that Android Studio was running on my computer with Emulator on, so it was crawling. I tried to open a program with Wox, it stalled, then I clicked on something else in another window and pressed enter on wox to open my target program. Unfortunately my computer froze at that instant and I think all the calls just coincided (kudos, Android Studio :/).

I have also uploaded the log file. 

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.18362.0
IntPtr Length: 8
x64: True

Python Path: C:\Python38\pythonw.exe
Everything SDK Path: C:\Users\pc\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/11/2020 08:46:18
Exception:
System.InvalidOperationException: Birincil fare düğmesi basılı olduğundan yalnızca DragMove çağırılabilir.
   konum: System.Windows.Window.DragMove()
   konum: Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) C:\projects\wox\Wox\MainWindow.xaml.cs içinde: satır 151
   konum: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   konum: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   konum: System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   konum: System.Windows.Input.InputManager.ProcessStagingArea()
   konum: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   konum: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   konum: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   konum: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   konum: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2020-02-11.txt](https://github.com/Wox-launcher/Wox/files/4184252/2020-02-11.txt)

**Comment by bao-qian** [comment]
duplicate #811
