### ISSUE TITLE
ImportError: No module named wox

### ISSUE THREAD

**Issue by ishu3101** [Wox-launcher/Wox#273]
After downloading and installing **Wox v1.2.0-beta**, I installed the **Hackernews plugin** using the `wpm install command`. When I enter the `keyword hn` it shows all the recent posts which is what it should do as shown below.

![image](https://cloud.githubusercontent.com/assets/3212162/7358924/78915b34-ed8d-11e4-8c61-6f0dde6a4024.png)

But when I run the **main.py** inside the **Hackernews plugin folder**, I get the message saying `ImportError: No module named wox`

**Comment by qianlifeng** [comment]
When you run from Wox, Wox will import https://github.com/qianlifeng/Wox/blob/dev/PythonHome/wox.py automatically.
