### ISSUE TITLE
插件网站打不开 Cannot access the wox plugin website

### ISSUE THREAD

**Issue by Ethan-Crisp** [Wox-launcher/Wox#2738]
http://www.wox.one/plugin
这个网站打不开，Google或者youtube都能打开，不知道是什么问题

**Comment by ache123** [comment]
metoo

**Comment by hyperreal64** [comment]
Same. I can't install plugins via Wox either. I'd like to find the sources of all plugins and install the ones I want manually. Are they only hosted at www.wox.one/plugins?

**Comment by qianruiy** [comment]
一样，也打不开

**Comment by fuwt** [comment]
没人管了吗..

**Comment by billyczhang** [comment]
不能访问

**Comment by liangtingchen** [comment]
有人知道好用的翻译插件吗？

**Comment by lu0se** [comment]
me too

**Comment by phcbest** [comment]
我也同样打不开，建议托管到hub上来

**Comment by bao-qian** [comment]
back now

**Comment by phcbest** [comment]
> 回来了

Thank you

**Comment by xxl-game** [comment]
Cannot access the wox plugin website again!

**Comment by zachgaozihe** [comment]
Cannot access the wox plugin website!
