### ISSUE TITLE
能不能增加一个唤醒自动聚焦输入功能?

### ISSUE THREAD

**Issue by astinx** [Wox-launcher/Wox#2744]
每次热键唤醒wox都要用鼠标点一下才能输入搜索, 想一唤醒就马上直接键盘操作都不行, 能不能加上这个功能? 谢谢了

**Comment by lqzhgood** [comment]
设置里面有啊
![image](https://user-images.githubusercontent.com/9134671/75552541-7a6d2900-5a71-11ea-80e2-9db987c4b987.png)
