### ISSUE TITLE
输入对焦问题

### ISSUE THREAD

**Issue by MaxwellXiao** [Wox-launcher/Wox#2747]
### Are you submitting a bug report?
YES
(write your answer here)

是的

当按下快捷键呼出搜索框时，尽管搜索框光标在闪烁，但仍不能直接键入，需要点击搜索框才能键入。
When you press the shortcut key to call up the search box, although the search box cursor is blinking, you cannot type directly. You need to click the search box to type.
### Steps to reproduce

1.按下快捷键（Press shortcut
2.点击搜索框（Click on the search bar
3.键入（Type in

### Wox Error Window text

NO log

(paste here)

### Detailed logs

[2020-02-28.txt](https://github.com/Wox-launcher/Wox/files/4267020/2020-02-28.txt)

(drop your log file here)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/47251656/75548317-f793a080-5a67-11ea-9e17-7c144592ce53.png)

(drop your screenshot here)
THANK YOU!

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
