### ISSUE TITLE
[Bug] Null Reference When Loading Config on Startup

### ISSUE THREAD

**Issue by AKJ1** [Wox-launcher/Wox#275]
Hey! Short-time User here. Love the launcher. Anyway, ran into this issue, Whenever i would load wox up i get a NullReferenceException. I had rebooted a few times prior to this, so i'm not entirely sure what the issue with it was, but i haven't reproduced it since, for which i'm sorry but i cant provide you with a stacktrace.

Anyway, it seems to have something to do with the user settings not loading properly. Error blows up at Line 171 in UserSettings with Null Reference Exception. 

Seems that there's a case where the internal load returns a null UserSettings object, which in turn throws a hissy fit when you try to acess a nonexistant property. I just glanced at it and decided to go with an alternate solution rather than debugging the whole thing a quick fix was clearing all user data(I.E. Deleting the entire wox folder and then redownloading), so somehow the config file got corrupted in the first place.

**Comment by bao-qian** [comment]
Try [v1.2beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)
