### ISSUE TITLE
1.3.578依旧不能拼音模糊匹配

### ISSUE THREAD

**Issue by camellhj** [Wox-launcher/Wox#2755]
### Are you submitting a bug report?

(write your answer here)

呼出wox界面后，输入拼音kaoqin，并没有出现“考勤”的搜索结果，而我能明确的是肯定有名为考勤的文件存在，但是模糊匹配没有匹配到

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/61722346/75740533-f3ef6a80-5d42-11ea-8c28-7c84a37f27b0.png)

(drop your screenshot here)

**Comment by bao-qian** [comment]
check this option and use new version to try again
https://github.com/Wox-launcher/Wox/releases

![image](https://user-images.githubusercontent.com/1169912/81972173-caad5d80-9654-11ea-8382-394673f05c10.png)

![image](https://user-images.githubusercontent.com/1169912/81972149-c4b77c80-9654-11ea-9ef2-dcb4ff9dd079.png)
