### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ishu3101** [Wox-launcher/Wox#276]
When I run the **main.py** file in the [Hacker News Plugin for Wox](https://www.getwox.com/plugin/12). I get the following error message.

```
Traceback (most recent call last):
  File "C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Hacker News\main.py", line 34, in <module>
    HackerNews()
  File "C:\Program Files\Wox-1.2.0-beta\PythonHome\wox.py", line 13, in __init__
    rpc_request = json.loads(sys.argv[1],encoding=chardet.detect(sys.argv[1])["encoding"])
IndexError: list index out of range
```

**Comment by JohnTheGr8** [comment]
Why are you running `main.py` ? Are you passing the needed arguments properly?

Also in the future _please_ open plugin-related issues in the corresponding plugin's repository.

**Comment by ishu3101** [comment]
I have installed the **Hacker News Plugin** and when you run the **main.py** file you get the error message as  shown above. If there is an error in your python code as above how are you meant to debug when trying to create a Wox Plugin using Python.

**Comment by bao-qian** [comment]
please open plugin-related issues in the corresponding plugin's repository.
