### ISSUE TITLE
Using Win + R in wins10 system will lead to the problem of window shrink in the next open interface

### ISSUE THREAD

**Issue by doudio** [Wox-launcher/Wox#2764]
Using Win + R in wins10 system will lead to the problem of window shrink in the next open interface

**Comment by chenqinA** [comment]
me too

**Comment by chenqinA** [comment]
打开 wox 设置
切换至插件页，左边栏有个命令行
取消勾选替换 win + R

**Comment by chenqinA** [comment]
Open WOx settings           
 Switch to the plug-in page. There is a command line in the left column            
Uncheck replace Win + R

**Comment by bao-qian** [comment]
duplicate #962
