### ISSUE TITLE
showing bug

### ISSUE THREAD

**Issue by lict1212** [Wox-launcher/Wox#2766]
Are you submitting a bug report?
When I opened wox in the browser, wox has a showing bug, black lines appeared but can't type words and after restart it be working

Steps to reproduce
don't have
sorry
Detailed logs
don't have 

Screenshots 
don't have

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

**Comment by lict1212** [comment]
got it ,thanks

**Comment by bao-qian** [comment]
probably duplicate 
#962
