### ISSUE TITLE
The position calculation is error

### ISSUE THREAD

**Issue by byzeus2014** [Wox-launcher/Wox#277]
1. start wox, drag the window to the right of screen. when close wox, the position record in config file will be updata and like below:
   ![picture1](https://cloud.githubusercontent.com/assets/8944612/7426199/6f4e7090-eff2-11e4-9a33-b1d521eb97aa.png)
2. start wox again, the window shows in the left of screen.
   ![picture2](https://cloud.githubusercontent.com/assets/8944612/7426218/c042706e-eff2-11e4-9eb5-94ee3ba0c0db.png)

3.close wox to check the position record in config file, it looks like below:
![picture3](https://cloud.githubusercontent.com/assets/8944612/7426221/d1d52b32-eff2-11e4-9166-d1e8603937f6.png)

**Comment by byzeus2014** [comment]
I have already choose "remember last launch location" function.

**Comment by DarrenCodes** [comment]
@byzeus2014 Are you still experiencing this problem? If yes, try the latest release and see if the problem still exists.

**Comment by bao-qian** [comment]
Please use #271 to discuss position problems in the future.
