### ISSUE TITLE
youdao translate bug

### ISSUE THREAD

**Issue by xiaxiaoguang** [Wox-launcher/Wox#2771]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

想用有道翻译插件
1.输入yd
2.输入想查询的单词
3.没有任何的反应

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\lenovo\AppData\Roaming\Wox\Logs\1.3.578\2020-03-14.txt
2. copy below exception message

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\lenovo\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/14/2020 19:25:10
Exception:
System.ArgumentOutOfRangeException: 插入索引已超出范围。必须为非负值，并且必须小于或等于大小。
参数名: index
   在 System.Collections.ArrayList.Insert(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by 4285f4** [comment]
我也出现了这个问题，我转用插件库中的有道翻译私Key版了，需要自己申请一个Key，作者看来不打算更新了。

**Comment by wxdjs** [comment]
有道云翻译，好像正常，不需要key，无限制  wox 版本1.4.1125
