### ISSUE TITLE
sync text of search suggestion

### ISSUE THREAD

**Issue by hhelibeb** [Wox-launcher/Wox#2773]
With Firefox, while selecting a search suggestion, text in the search bar will change to be the same as the suggestion,
![图片](https://user-images.githubusercontent.com/16676760/76833769-e8ce2b80-6866-11ea-9b5b-a5061830ff41.png)
And Wox has a different behavior, although an item is selected, the text in the box keeps unchanged,
![图片](https://user-images.githubusercontent.com/16676760/76833722-d3590180-6866-11ea-97c4-4abb9071e708.png)

I wonder may Wox can have a same feature. I believe it is a useful. 
For example, if my plugin has several commands, I can set an option '-h' to list all commands, and the user would select one of them to complete the command needed.

**Comment by hhelibeb** [comment]
or sync text by button '→'

**Comment by bao-qian** [comment]
thanks for suggestion

![image](https://user-images.githubusercontent.com/1169912/81971106-24ad2380-9653-11ea-9dc7-c4452605aabd.png)

1 new version has text completion ui.
2 plugin can also change the query text by calling `ChangeQuery`
