### ISSUE TITLE
http://www.wox.one/ 可不可以支持邮箱重置密码呀？ 密码忘了，重新注册 显示邮箱已存在，这太难受了

### ISSUE THREAD

**Issue by windwindwa** [Wox-launcher/Wox#2775]
### Are you submitting a bug report?

NO

http://www.wox.one/ 可不可以支持邮箱重置密码呀？ 密码忘了，重新注册 显示邮箱已存在，这太难受了

**Comment by bao-qian** [comment]
@miaoxingrenya 
sorry for wait too long.
for a temp fix, send me an email bao.github@outlook.com with username, I will reset it to a temp password for now.
