### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by JonnyJong** [Wox-launcher/Wox#2778]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1.我在 Wox 设置\插件\网页搜索中添加了一个 “bilibili.com/av{q}”（bilibili是一个视频网站，av则是这个视频网站的视频ID的开头）
2.我用我设置的“Ctrl + Space”开启了 Wox 搜索
3.输入了 “av”后按空格，输入视频ID
4.按下回车，弹出了 "Wox出错了“ 的窗口

English translation (By Google)
1. I added a "bilibili.com/av{q}" to Wox Settings \ Plugins \ Web Searches (bilibili is a video site, av is the beginning of the video ID of this video site)
2. I turned on Wox search with "Ctrl + Space" I set
3. Enter “av” and press the space to enter the video ID
4. Press Enter, the "Wox got an error" window pops up

### Wox Error Window text

Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.17763.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\jiang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/21/2020 10:04:50
Exception:
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.<Query>b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4362313/2020-03-21.txt)

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/38036899/77217459-b3bf2300-6b5d-11ea-8315-c4a2f1931a03.png)

**Comment by liuqi0270** [comment]
> ### Are you submitting a bug report?
> Yes
> 
> ### Steps to reproduce
> 1.我在 Wox 设置\插件\网页搜索中添加了一个 “bilibili.com/av{q}”（bilibili是一个视频网站，av则是这个视频网站的视频ID的开头）
> 2.我用我设置的“Ctrl + Space”开启了 Wox 搜索
> 3.输入了 “av”后按空格，输入视频ID
> 4.按下回车，弹出了 "Wox出错了“ 的窗口
> 
> English translation (By Google)
> 
> 1. I added a "bilibili.com/av{q}" to Wox Settings \ Plugins \ Web Searches (bilibili is a video site, av is the beginning of the video ID of this video site)
> 2. I turned on Wox search with "Ctrl + Space" I set
> 3. Enter “av” and press the space to enter the video ID
> 4. Press Enter, the "Wox got an error" window pops up
> 
> ### Wox Error Window text
> Wox version: 1.3.578
> OS Version: Microsoft Windows NT 10.0.17763.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: pythonw.exe
> Everything SDK Path: C:\Users\jiang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
> Date: 03/21/2020 10:04:50
> Exception:
> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
> 在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> 在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> 在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
> 在 Wox.ViewModel.MainViewModel.b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
> 在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
> 在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
> 在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
> 在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
> 在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
> 在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
> 在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
> 在 System.Windows.Input.InputManager.ProcessStagingArea()
> 在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
> 在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
> 在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
> 在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
> 在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
> 在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
> 在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> 在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> ### Detailed logs
> [2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4362313/2020-03-21.txt)
> 
> ### Screenshots (optional)
> ![image](https://user-images.githubusercontent.com/38036899/77217459-b3bf2300-6b5d-11ea-8315-c4a2f1931a03.png)

这个问题应该是偶发的吧。我也在用看好久没有更新了，你设的百度搜索会有问题吗？

**Comment by Aicomsoft** [comment]
你好，我设置的不是百度搜索，但你这么说，可能是我的设置有问题。
请问“网页搜索”的设置有什么（语法）规范要求？
谢谢

**Comment by JonnyJong** [comment]
> > ### Are you submitting a bug report?
> > Yes
> > ### Steps to reproduce
> > 1.我在 Wox 设置\插件\网页搜索中添加了一个 “bilibili.com/av{q}”（bilibili是一个视频网站，av则是这个视频网站的视频ID的开头）
> > 2.我用我设置的“Ctrl + Space”开启了 Wox 搜索
> > 3.输入了 “av”后按空格，输入视频ID
> > 4.按下回车，弹出了 "Wox出错了“ 的窗口
> > English translation (By Google)
> > 
> > 1. I added a "bilibili.com/av{q}" to Wox Settings \ Plugins \ Web Searches (bilibili is a video site, av is the beginning of the video ID of this video site)
> > 2. I turned on Wox search with "Ctrl + Space" I set
> > 3. Enter “av” and press the space to enter the video ID
> > 4. Press Enter, the "Wox got an error" window pops up
> > 
> > ### Wox Error Window text
> > Wox version: 1.3.578
> > OS Version: Microsoft Windows NT 10.0.17763.0
> > IntPtr Length: 8
> > x64: True
> > Python Path: pythonw.exe
> > Everything SDK Path: C:\Users\jiang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
> > Date: 03/21/2020 10:04:50
> > Exception:
> > System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
> > 在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> > 在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> > 在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
> > 在 Wox.ViewModel.MainViewModel.b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
> > 在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
> > 在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
> > 在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
> > 在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
> > 在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
> > 在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
> > 在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
> > 在 System.Windows.Input.InputManager.ProcessStagingArea()
> > 在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
> > 在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
> > 在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
> > 在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
> > 在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
> > 在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
> > 在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> > 在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> > ### Detailed logs
> > [2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4362313/2020-03-21.txt)
> > ### Screenshots (optional)
> > ![image](https://user-images.githubusercontent.com/38036899/77217459-b3bf2300-6b5d-11ea-8315-c4a2f1931a03.png)
> 
> 这个问题应该是偶发的吧。我也在用看好久没有更新了，你设的百度搜索会有问题吗？

你好，我设置的不是百度搜索，但你这么说，可能是我的设置有问题。
请问“网页搜索”的设置有什么（语法）规范要求？
谢谢

**Comment by liuqi0270** [comment]
> > > ### Are you submitting a bug report?
> > > Yes
> > > ### Steps to reproduce
> > > 1.我在 Wox 设置\插件\网页搜索中添加了一个 “bilibili.com/av{q}”（bilibili是一个视频网站，av则是这个视频网站的视频ID的开头）
> > > 2.我用我设置的“Ctrl + Space”开启了 Wox 搜索
> > > 3.输入了 “av”后按空格，输入视频ID
> > > 4.按下回车，弹出了 "Wox出错了“ 的窗口
> > > English translation (By Google)
> > > 
> > > 1. I added a "bilibili.com/av{q}" to Wox Settings \ Plugins \ Web Searches (bilibili is a video site, av is the beginning of the video ID of this video site)
> > > 2. I turned on Wox search with "Ctrl + Space" I set
> > > 3. Enter “av” and press the space to enter the video ID
> > > 4. Press Enter, the "Wox got an error" window pops up
> > > 
> > > ### Wox Error Window text
> > > Wox version: 1.3.578
> > > OS Version: Microsoft Windows NT 10.0.17763.0
> > > IntPtr Length: 8
> > > x64: True
> > > Python Path: pythonw.exe
> > > Everything SDK Path: C:\Users\jiang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
> > > Date: 03/21/2020 10:04:50
> > > Exception:
> > > System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
> > > 在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> > > 在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> > > 在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
> > > 在 Wox.ViewModel.MainViewModel.b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
> > > 在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
> > > 在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
> > > 在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
> > > 在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
> > > 在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
> > > 在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
> > > 在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
> > > 在 System.Windows.Input.InputManager.ProcessStagingArea()
> > > 在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
> > > 在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
> > > 在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
> > > 在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
> > > 在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
> > > 在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
> > > 在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> > > 在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> > > ### Detailed logs
> > > [2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4362313/2020-03-21.txt)
> > > ### Screenshots (optional)
> > > ![image](https://user-images.githubusercontent.com/38036899/77217459-b3bf2300-6b5d-11ea-8315-c4a2f1931a03.png)
> > 
> > 
> > 这个问题应该是偶发的吧。我也在用看好久没有更新了，你设的百度搜索会有问题吗？
> 
> 你好，我设置的不是百度搜索，但你这么说，可能是我的设置有问题。
> 请问“网页搜索”的设置有什么（语法）规范要求？
> 谢谢

具体规范我也没有了解很清楚。看你的bilibili站设置应该有些问题。

我的百度是
http://www.baidu.com/s?wd={q}

建议你把B站的更换为 
https://search.bilibili.com/all?keyword={q}

**Comment by JonnyJong** [comment]
> > > > ### Are you submitting a bug report?
> > > > Yes
> > > > ### Steps to reproduce
> > > > 1.我在 Wox 设置\插件\网页搜索中添加了一个 “bilibili.com/av{q}”（bilibili是一个视频网站，av则是这个视频网站的视频ID的开头）
> > > > 2.我用我设置的“Ctrl + Space”开启了 Wox 搜索
> > > > 3.输入了 “av”后按空格，输入视频ID
> > > > 4.按下回车，弹出了 "Wox出错了“ 的窗口
> > > > English translation (By Google)
> > > > 
> > > > 1. I added a "bilibili.com/av{q}" to Wox Settings \ Plugins \ Web Searches (bilibili is a video site, av is the beginning of the video ID of this video site)
> > > > 2. I turned on Wox search with "Ctrl + Space" I set
> > > > 3. Enter “av” and press the space to enter the video ID
> > > > 4. Press Enter, the "Wox got an error" window pops up
> > > > 
> > > > ### Wox Error Window text
> > > > Wox version: 1.3.578
> > > > OS Version: Microsoft Windows NT 10.0.17763.0
> > > > IntPtr Length: 8
> > > > x64: True
> > > > Python Path: pythonw.exe
> > > > Everything SDK Path: C:\Users\jiang\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
> > > > Date: 03/21/2020 10:04:50
> > > > Exception:
> > > > System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
> > > > 在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> > > > 在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
> > > > 在 Wox.Plugin.WebSearch.Main.<>c__DisplayClass8_1.b__1(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 67
> > > > 在 Wox.ViewModel.MainViewModel.b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
> > > > 在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
> > > > 在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
> > > > 在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
> > > > 在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
> > > > 在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
> > > > 在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
> > > > 在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
> > > > 在 System.Windows.Input.InputManager.ProcessStagingArea()
> > > > 在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
> > > > 在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
> > > > 在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
> > > > 在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
> > > > 在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
> > > > 在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
> > > > 在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> > > > 在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> > > > ### Detailed logs
> > > > [2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4362313/2020-03-21.txt)
> > > > ### Screenshots (optional)
> > > > ![image](https://user-images.githubusercontent.com/38036899/77217459-b3bf2300-6b5d-11ea-8315-c4a2f1931a03.png)
> > > 
> > > 
> > > 这个问题应该是偶发的吧。我也在用看好久没有更新了，你设的百度搜索会有问题吗？
> > 
> > 
> > 你好，我设置的不是百度搜索，但你这么说，可能是我的设置有问题。
> > 请问“网页搜索”的设置有什么（语法）规范要求？
> > 谢谢
> 
> 具体规范我也没有了解很清楚。看你的bilibili站设置应该有些问题。
> 
> 我的百度是
> [http://www.baidu.com/s?wd={q}](http://www.baidu.com/s?wd=%7Bq%7D)
> 
> 建议你把B站的更换为
> [https://search.bilibili.com/all?keyword={q}](https://search.bilibili.com/all?keyword=%7Bq%7D)

感谢！
我已经解决问题了。
具体原因我不清楚，但当我把 bilibili.com/av{q} 改为 https://bilibili.com/av{q} 就正常了，问题出在“https://”上。

**Comment by liuqi0270** [comment]
不客气
