### ISSUE TITLE
Wox identified as ransomware by Malwarebytes

### ISSUE THREAD

**Issue by colonelsalt** [Wox-launcher/Wox#2779]
### Are you submitting a bug report?
No. I've been a long-time user of Wox, and just had a strange situation occur where Malwarebytes (Premium) flagged and quarantined it as Ransomware. This was while Wox was running in the background.

Not sure if this is due to a new update and can be fixed (it had me worried for a moment). Most recent Wox log and a screenshot of the Malwarebytes alert included below.

### Detailed logs

[2020-03-21.txt](https://github.com/Wox-launcher/Wox/files/4363527/2020-03-21.txt)

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/7888724/77232850-bd6b7980-6ba3-11ea-8f02-df2e5517b0ff.png)

**Comment by bao-qian** [comment]
that's a auto startup setting fore registry.
if you have issue with auto startup, you can uncheck it in settings.
you can also try https://github.com/Wox-launcher/Wox/releases
