### ISSUE TITLE
Wox plugins won't launch and error displays "Could not create SSL/TLS secure channel." message

### ISSUE THREAD

**Issue by ddcruver** [Wox-launcher/Wox#2781]
### Are you submitting a bug report?

Yes, custom plugins are no longer working and there is many errors in the log.  Most of them have the message "<The request was aborted: Could not create SSL/TLS secure channel.>".

### Steps to reproduce

1. Start Wox
2. Try to Use Plugin

Install Plugins and try to use them.  It seems to be happening for main application functions and plugins.

Version: 1.3.524

### Detailed logs

(drop your log file here)
[2020-03-26.txt](https://github.com/Wox-launcher/Wox/files/4389879/2020-03-26.txt)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
