### ISSUE TITLE
shell插件引起崩溃

### ISSUE THREAD

**Issue by ixsword** [Wox-launcher/Wox#2783]
### Are you submitting a bug report?

是的

### Steps to reproduce

1.打开wox
2.win+r
3.输入ipconfig回车，一闪没了
4.再次win+r,输入ipconfig回车崩溃

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\sword\AppData\Roaming\Wox\Logs\1.3.578\2020-03-28.txt
2. copy below exception message

Wox version: 1.3.578
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: K:\Develop\Python3_7x64\pythonw.exe
Everything SDK Path: C:\Users\sword\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 03/28/2020 01:28:30
Exception:
System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 Wox.Plugin.Shell.Main.Execute(String command, Boolean runAsAdministrator) 位置 C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:行号 233
   在 Wox.Plugin.Shell.Main.<>c__DisplayClass9_1.<GetHistoryCmds>b__4(ActionContext c) 位置 C:\projects\wox\Plugins\Wox.Plugin.Shell\Main.cs:行号 120
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-03-28.txt](https://github.com/Wox-launcher/Wox/files/4395071/2020-03-28.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/8772044/77783579-13ed2200-7094-11ea-9766-6c75e9a5b2b9.png)

**Comment by ixsword** [comment]
sorry,我感觉我是输太快了打错了命令报的错。因为我后面又试了下，输入一个不存在的命令，就会出错

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
