### ISSUE TITLE
wox takes up a lot of memory in win10 1909

### ISSUE THREAD

**Issue by Chinahandsomeboy** [Wox-launcher/Wox#2785]
#2754 # Are you submitting a bug report?

No

### Steps to reproduce

1.设置开机自启Wox
2.Wox自启动后内存占用很大
3.关闭Wox后再次打开内存占用正常

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/26315908/77909755-76c30100-72c0-11ea-8e7a-d2fe216f3f04.png)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
