### ISSUE TITLE
Everything: windows dark mode

### ISSUE THREAD

**Issue by mjarkk** [Wox-launcher/Wox#2791]
### My problem
In the evening when i use the everything tool my eyes burn out of my head, it would be nice if the everything tool follows the windows dark/light theme like the windows file explorer

### Steps to reproduce
Turn on windows dark mode and look at everything

**Comment by enria** [comment]
I think you may have misunderstood. 
[Everything](https://www.voidtools.com) is another software for searching local files, and it provide a DLL file that Wox depends on for searching function. 
You can raise your demand on [voidtools forum](https://www.voidtools.com/forum/). Good luck! 😊

**Comment by mjarkk** [comment]
Oh sorry i thought it was part of this program as you can download everything via the releases page.  
I'll see if i can create an issue in there forum.
