### ISSUE TITLE
Theme builder does not support transparency

### ISSUE THREAD

**Issue by blacklightpy** [Wox-launcher/Wox#2794]
### Are you submitting a bug report?

No

Wox has two themes inbuilt which support transparency - BlurBlack and BlurWhite. I couldn't find a transparency slider on the theme builder. Please add this feature.

**Comment by enria** [comment]
I'm a user. 
You can change the transparency in the theme xaml file. It's not user-friendly, but still a method.

**Comment by blacklightpy** [comment]
> You can change the transparency in the theme xaml file. It's not user-friendly, but still a method.

I guessed it too, but still it's not documented, and adding the feature in the builder can help a lot.
