### ISSUE TITLE
Goto url by typing keyword

### ISSUE THREAD

**Issue by Manfred73** [Wox-launcher/Wox#2796]
### Are you submitting a bug report?

(NO)

I've been using Launchy 2.6 for Winows for years, but today all my settings were suddenly gone.
I was looking for a more modern launcher (since Launchy is quite old and no longer seems to be updated) and found out about Wox. It looks pretty cool.

What I haven't been able to find out though is how I can quickly goto a url (on my NAS), for example Radarr or SickChill. In Launchy I used the Weby plugin where I could associate a keyword like radarr with a Url and then just type radarr to go there.

Does Wox have something like that or a plugin I could use for that? I noticed there is the WebApp plugin, but then I always have to type "wap radarr" instead of "radarr" and it opens in WebApp instead of normal browser. The WebSearch plugin only allows to enter keywords for search engines.

**Comment by enria** [comment]
Hi, guy, I'm a user of Wox. 
For your requirement, I recommend you add a shortcut that is linked to the url that you want to goto in your file system (anywhere whatever) with a short file name, than you can search it with Everything plugin.

**Comment by Manfred73** [comment]
Hi,
Thanks for the tip. That's a good alternative.
Actually I found in the Wapp plugin you can shorten wap to w and it's not that bad to use after all. When I click links in the app window it opens them in Chome anyway.

**Comment by bao-qian** [comment]
close due to question seems resolved.
