### ISSUE TITLE
输入框中内容会乱码(The input box will be garbled)

### ISSUE THREAD

**Issue by WenBoXiaoGeGe** [Wox-launcher/Wox#2798]
### Are you submitting a bug report?

(write your answer here)
是的
Yes

### Steps to reproduce

1.前两天打开的时候就出现了，我也不知道怎么复现，我没有做什么
2.I didn't know how to reproduce it. What did I do
3.

### Wox Error Window text

(paste here)
没有提示报错，只是在输入框中输入内容的时候显示乱码
There is no error, just a garbled code when typing in the input box

### Detailed logs

(drop your log file here)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/42373337/78956901-5f80e080-7b16-11ea-934d-c1b7e9f3b85f.png)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
