### ISSUE TITLE
Wox does not work any work since install a plugin.

### ISSUE THREAD

**Issue by wangyouming** [Wox-launcher/Wox#2802]
When i am installing a  Wox Plugin [快递查询](http://www.wox.one/plugin/79), Wox prompted exception. After that, Wox doest work any more. Every time, i relaunch the program wox, it prompt the same error.

log file:
[2020-04-11.txt](https://github.com/Wox-launcher/Wox/files/4464469/2020-04-11.txt)

exception message:

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.19041.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\wangyouming\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/11/2020 18:42:30
Exception:
System.AggregateException: 发生一个或多个错误。 ---> System.IO.FileNotFoundException: 未能加载文件或程序集“Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。系统找不到指定的文件。
   在 Wox.Plugin.Express.Main.Init(PluginInitContext context)
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 91
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 60
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (内部异常 #0) System.IO.FileNotFoundException: 未能加载文件或程序集“Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。系统找不到指定的文件。
文件名:“Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”
   在 Wox.Plugin.Express.Main.Init(PluginInitContext context)
   在 Wox.Infrastructure.Stopwatch.Debug(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 19
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 101
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。
<---

**Comment by enria** [comment]
这个其实是插件问题，我看了一下插件的[github](https://github.com/zxsean/Wox.Plugin.Express)，三年都没动了，应该是凉了。

我看了一下日志，应该是`Newtonsoft.Json`这个库没有放入到插件中。原因应该是插件作者想使用Wox自己用的`Newtonsoft.Json`，但因为Wox更新了这个库的版本，插件就找不到DLL了。

我又使用Nuget下载了插件使用`Newtonsoft.Json`[对应的版本的DLL](https://www.jianguoyun.com/p/Dcbim2UQi6XaBhi__40D)，放到插件的目录中，没有出错，Wox能运行，插件也能用。

![Snipaste_2020-04-12_00-25-15](https://user-images.githubusercontent.com/18412528/79049120-1c2c8c00-7c54-11ea-90c9-592c5f22eda5.png)

但是，查询快递单没有返回结果。看了下日志，使用的百度快递查询API返回的结果解析失败。我到[百度数据开放平台](https://open.baidu.com)，发现快递查询的接口都没了。

要是这个插件功能不错，我可能会考虑帮你改一下使用的API，再给你打包一个新的插件版本。但是说实在的，我觉得这个插件意义不大，使用网页或者手机APP查就挺好的。

另外，使用Wox查快递的话，我建议你添加一个搜索引擎，网页地址是[https://www.kuaidi100.com/](https://www.kuaidi100.com/)，输入`kd`然后再输入快递单号，就通跳到查询结果网页，也算方便的。

![Snipaste_2020-04-12_00-39-06](https://user-images.githubusercontent.com/18412528/79049446-50a14780-7c56-11ea-90e4-8f8cfc9318a0.png)

**Comment by wangyouming** [comment]
也不太需要这个插件，看到 http://www.wox.one/plugin 有这个插件，就安装试了下，之后Wox就用不了了。现在在Wox插件目录，把 [快递查询](http://www.wox.one/plugin/79) 删除了，wox又能工作了。

Thank you for your work to make my life easier.
