### ISSUE TITLE
wox got an error 

### ISSUE THREAD

**Issue by heming001** [Wox-launcher/Wox#2807]
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.restart computer
2.
3.

### Wox Error Window text

(paste here)
Wox version: 1.3.578
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: 
Date: 04/15/2020 08:41:28
Exception:
System.Net.WebException: 操作超时
   在 System.Net.FileWebRequest.GetResponse()
   在 MS.Internal.WpfWebRequestHelper.GetResponse(WebRequest request)
   在 System.Windows.ResourceDictionary.set_Source(Uri value)
   在 Wox.Core.Resource.Internationalization.LoadLanguage(Language language) 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 128
   在 Wox.Core.Resource.Internationalization..ctor() 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 27
   在 Wox.Core.Resource.InternationalizationManager.get_Instance() 位置 C:\projects\wox\Wox.Core\Resource\InternationalizationManager.cs:行号 18
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 44
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 58
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-04-15.txt](https://github.com/Wox-launcher/Wox/files/4478487/2020-04-15.txt)

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
