### ISSUE TITLE
Modification to Windows Registry won't take effect when wox is executing

### ISSUE THREAD

**Issue by guoxx** [Wox-launcher/Wox#281]
Wox is really cool, thanks for the dev guy.
I have a issue about modification to windows registry. When wox is executing, the modification won't take effect immediately. I'm using windows 7 pro.

**Comment by deltaidea** [comment]
Generally speaking, every process has the environment it had when it started. That applies not only to Wox, but to everything.

More info: http://stackoverflow.com/q/171588

> The environment is copied into the process' memory on startup and therefore has no connection whatsoever to the system-defined envvars anymore.

You probably need to restart Wox.

Could you describe your issue more specifically? What do you change and where do the changes not take effect?

**Comment by guoxx** [comment]
When wox is running on background. All my modification to the windows registry won't take effect.

For instance, I want to add a user environment variable XX_BIN=C:/bin. After I add this variable, I restart cmd, then execute `echo %XX_BIN%`, it output nothing. But, if I exit wox before adding this variable, it works correctly.

**Comment by deltaidea** [comment]
Could you please provide more specific reproduction steps? [Are you using `setx` or `set`?](http://superuser.com/a/79614)

**Comment by guoxx** [comment]
Most of the time, I use GUI to set the user environment variable. But I also tried setx.

Here are steps:
1. Run wox on background
2. Add new user environment variable Foo using GUI or setx
3. Start another cmd, execute echo %Foo%

You will found that cmd print nothing.

**Comment by bao-qian** [comment]
Try restart Wox
![2015-11-03_17-40-55](https://cloud.githubusercontent.com/assets/1169912/10916188/1a4eb1b6-8252-11e5-9428-5c43a35fcea9.png)
