### ISSUE TITLE
Add a setting for hiding the tray icon

### ISSUE THREAD

**Issue by deltaidea** [Wox-launcher/Wox#282]
There should be an option in settings to hide the tray icon to keep it nice and clean.

**Comment by gblazex** [comment]
+1

**Comment by bao-qian** [comment]
This is handled by windows, search "Remove icons from the notification area"

**Comment by sqqqs** [comment]
>This is handled by windows, search "Remove icons from the notification area"
I always need to show all the icons in the settings. The Wox icon there takes up a lot of space. Please add an option to hide this icon.
