### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by mika76** [Wox-launcher/Wox#283]
When I downloaded I noticed it was just a zip file which I had to manually put somewhere and run. I think if you want more people to use this it needs an easier installer.

**Comment by qianlifeng** [comment]
Thx, I will consider that.

**Comment by Leon99** [comment]
Just a suggestion - use Chocolatey (www.chocolatey.org). It takes only two words with it to install Wox - cinst wox.
Though I would suggest adding a dialog on the first run that asks the user if they want to open the Settings dialog to choose a theme and set Wox to run on system startup.

**Comment by che-wf** [comment]
I have tried to install this on two machines. Both times I get an error upon running after unzipping leaving me unable to actually use the program. So, I would also agree that an installation file might be helpful.

**Comment by TheZoker** [comment]
+1

**Comment by mika76** [comment]
Actually what would be best is to create the installer AND a chocolatey package :smile:

**Comment by mika76** [comment]
I didn't realize chocolatey installation was already there. You might want to promote it more from the front page.

**Comment by bao-qian** [comment]
track using #360
