### ISSUE TITLE
Plugin Refactoring

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#2831]
- [ ] remove or update buggy plugin, include 快递, youdao, steam, dash, PLUGINSLIST, express, twitch
related 
https://github.com/Wox-launcher/Wox/issues/1999
https://github.com/Wox-launcher/Wox/issues/2319

**Comment by bao-qian** [comment]
python installation prompt for python plugin

**Comment by bao-qian** [comment]
need usage check
need https://github.com/Wox-launcher/Wox/issues/2540 
youtube query https://github.com/Wox-launcher/Wox/issues/2520
simple clock https://github.com/Wox-launcher/Wox/issues/2503

**Comment by bao-qian** [comment]
- [ ] load plugin into separate process to avoid dll hell

releated
single instance python #2010
Update plugins without the need to restart (with possible solution)  https://github.com/Wox-launcher/Wox/issues/184
Better disable functionality for plugin   https://github.com/Wox-launcher/Wox/issues/351

**Comment by bao-qian** [comment]
api design https://github.com/Wox-launcher/Wox/issues/537

**Comment by bao-qian** [comment]
- [ ] integrate Switcheroo function

**Comment by jhdxr** [comment]
If you are going to change the interface, which I'm also agree with, I think it's a good time to increase the version. There are lots of issues casued by the unlogged api change in 1.3.x.

**Comment by bao-qian** [comment]
@jhdxr 
the interface should not be changed in 1.4. I will try to maintain compatibility.

**Comment by jhdxr** [comment]
one more suggestion:

disabled plugin should not be execuated at all.
e.g. The shell plugin should not replace Win+R if the plugin is disabled even the option is on.
