### ISSUE TITLE
搜索框下拉栏字体显示不太正常

### ISSUE THREAD

**Issue by qw4096** [Wox-launcher/Wox#2835]
如图
![QQ截图20200422084825](https://user-images.githubusercontent.com/13681655/79928717-48c37d80-8476-11ea-98f5-e0243c4b96ec.png)
貌似是加粗的部分显示不正常

**Comment by bao-qian** [comment]
这个是 cleartype 的问题，下个大版本重写新 ui 后会解决。

**Comment by bao-qian** [comment]
已修复，试试新 build https://ci.appveyor.com/project/bao-qian/wox/builds/32351055/artifacts
