### ISSUE TITLE
Wox got an error fro 1.3.792

### ISSUE THREAD

**Issue by dasu88** [Wox-launcher/Wox#2842]
[2020-04-23.txt](https://github.com/Wox-launcher/Wox/files/4519480/2020-04-23.txt)

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by bao-qian** [comment]
close due to no details
