### ISSUE TITLE
wox不支持自动索引吗？

### ISSUE THREAD

**Issue by cantonadong** [Wox-launcher/Wox#2843]
每次还得手工索引，太麻烦了。

**Comment by bao-qian** [comment]
支持自动，请按照格式详细描述问题。

**Comment by cantonadong** [comment]
> 支持自动，请按照格式详细描述问题。

请问索引的频率是怎么样的？没看到有设置项。

**Comment by bao-qian** [comment]
@cantonadong 
background indexing during startup
index per day will be added later
