### ISSUE TITLE
Error on save settings

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#2847]
<details>
  <summary>Error Data</summary>
Wox version: 1.3.792
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\roose\scoop\apps\python\current\pythonw.exe
Everything SDK Path: C:\Users\roose\AppData\Local\Wox\app-1.3.792\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/23/2020 09:36:52
Exception:
Newtonsoft.Json.JsonSerializationException: Error getting value from 'Name' on 'Wox.Plugin.Program.Settings+ProgramSource'. ---> System.ArgumentException: Путь имеет недопустимую форму.
   в System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.GetFullPathInternal(String path)
   в System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   в Wox.Plugin.Program.Settings.ProgramSource.get_Name() в C:\projects\wox\Plugins\Wox.Plugin.Program\Settings.cs:строка 34
   в GetName(Object )
   в Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   --- Конец трассировки внутреннего стека исключений ---
   в Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   в Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   в Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   в Wox.Infrastructure.Storage.JsonStrorage`1.Save() в C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:строка 97
   в Wox.Plugin.Program.Main.Save() в C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:строка 56
   в Wox.Core.Plugin.PluginManager.Save() в C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:строка 61
   в System.Windows.Window.OnClosed(EventArgs e)
   в System.Windows.Window.WmDestroy()
   в System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
</details>

**Comment by bao-qian** [comment]
please give step to reproduce this error.
1 error on every save?
2 error on particular setting?
3 error even after reset?

**Comment by roose** [comment]
Error after every leave from settings window.
What a reset? Where I can find it?

**Comment by bao-qian** [comment]
@roose 
you can reset by delete `%APPDATA%\Wox`
backup before you do

**Comment by roose** [comment]
@bao-qian Ah, I found what generate this error, is "Program" plugin, its ProgramSources settings changed format.
Excuse for troubling)

**Comment by bao-qian** [comment]
thanks for report. @roose
