### ISSUE TITLE
最新的1.3.792的程序插件不正常"Program" plugin in new version 1.3.792 doesn't work properly

### ISSUE THREAD

**Issue by wingo1** [Wox-launcher/Wox#2848]
自定义的路径搜不到东西。另外点击索引后也没有看到索引的过程。
Nothing can be found in the custom path. In addition, I did not see the index process after clicking the reindex.
换回几天前的1.3.735版本后正常。
After switching back to the 1.3.735 version, it is normal.

**Comment by bao-qian** [comment]
please upload log file

**Comment by wingo1** [comment]
在1.3.792版本中，我清除了日志文件，当我单击“重新索引”时，没有创建新的日志文件，并且Cache目录中的文件未更新。
在1.3.735版中，相同的行为会导致创建新的日志文件并更新缓存文件。
With version 1.3.792,  I cleared log file, when I click "reindex", no new log file was created, and files in Cache directory didn't be updated. 
With version  1.3.735, the same behavior cause new log file created and updated the cache files.

**Comment by bao-qian** [comment]
试试这个新 build
https://ci.appveyor.com/project/bao-qian/wox/builds/32384574/artifacts

**Comment by wingo1** [comment]
Problem solved. Thx !
