### ISSUE TITLE
Disable when some programs are in focus

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2854]
Hi
I think it would be a good idea to have wox not work when some programs are in focus. for example i work in ableton, which makes ctrl + space not possible for me.
Also alt + space is really inconvinient when playing games since those keys are often pressed.
so i think being able to add a list of programs, where wox dont work when the specific program is in focus would be great :)

**Comment by bao-qian** [comment]
you can always change hotkey in settings -> Hotkey.
or you can just close the program, wox startup only cost about 1s to 2s.
