### ISSUE TITLE
Default hotkey

### ISSUE THREAD

**Issue by Leon99** [Wox-launcher/Wox#286]
By default, Wox uses Alt + Space. This is a standard Windows hotkey to open a window menu. Which means - chances are some users will have to change it to avoid altering their habits. How about Win + ~? Win is a nice modifier, considering that Wox can easily replace Windows start menu, ~ is often used in games to popup a console, so it is familiar to many people.

**Comment by bao-qian** [comment]
try 1.3.106
https://ci.appveyor.com/project/happlebao/wox/build/1.3.106/artifacts
reopen if you still have this issue
