### ISSUE TITLE
General settings tab not displayed correctly

### ISSUE THREAD

**Issue by forik** [Wox-launcher/Wox#2879]
**Describe the bug**
The general settings tab not displaying all the settings

**Runtime info**
 - Windows 10 Version: 10 Pro, 2004
 - Wox version: 1.3.881

**Additional context**
Bug is on a 4k 27'' display

**Screenshots**
![image](https://user-images.githubusercontent.com/886162/80311777-49e40a00-87ea-11ea-9cab-67aca636dafe.png)

**Comment by bao-qian** [comment]
try this new build https://ci.appveyor.com/project/bao-qian/wox/builds/32420882/artifacts
