### ISSUE TITLE
Failed to load theme creating at theme builder

### ISSUE THREAD

**Issue by jaocarli** [Wox-launcher/Wox#2883]
Hey guys!

I created a theme using the [Theme Builder](http://www.wox.one/theme/builder) and when I try to put it to work it returns the error `Fail to load the xxxx, fallback to default theme`. I wonder how to solve this ...

How to view the theme:
1) Open the Wox screen
2) Type Settings and hit enter
3) go to Theme and try to select the edited theme.

**Comment by bao-qian** [comment]
1 please upload your theme file to debug.
2 please specify wox version

**Comment by sausagemountain** [comment]
I think when I [updated the template](https://github.com/Wox-launcher/Wox/commit/0ce55c069ec3c5a794e19377336cba948830cccf) I forgot to change it in the website repository. I will make a pull request.

**Comment by sausagemountain** [comment]
For now you can open the theme file with a text editor, find lines that look like this

```xaml
<Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
    <Setter Property="Foreground" Value="{%searchFieldTextColor%}" />
    <Setter Property="Background" Value="{%searchFieldBackgroundColor%}"/>
</Style>
```

and edit them look like this

```xaml
<Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
    <Setter Property="Foreground" Value="{%searchFieldTextColor%}" />
</Style>
<Style x:Key="QueryTextSuggestionBoxStyle" BasedOn="{StaticResource BaseQueryTextSuggestionBoxStyle}" TargetType="{x:Type TextBox}">
    <Setter Property="Background" Value="{%searchFieldBackgroundColor%}"/>
</Style>
```

**Comment by jaocarli** [comment]
> 1 please upload your theme file to debug.
> 2 please specify wox version

1) Link: https://rb.gy/ihkpqq
2) Version 1.3.881

**Comment by bao-qian** [comment]
@sausagemountain It's that possible to rewrite your pr without brake the compatibility?

**Comment by bao-qian** [comment]
please try this build 
https://ci.appveyor.com/project/bao-qian/wox/builds/32521089
