### ISSUE TITLE
v1.3.881开启portable模式，重新安装v1.3.881版本后，配置丢失

### ISSUE THREAD

**Issue by yyysuo** [Wox-launcher/Wox#2886]
操作系统：windows 10 pro 19041.208
软件版本：v1.3.881
操作步骤：
1、安装v1.3.881，设置语言为中文，网页搜索插件中自定义一些搜索引擎，并设置为portable模式。
2、重新安装v1.3.881，语言变为默认的英文，自定义的搜索引擎消失。

**Comment by bao-qian** [comment]
did you use portable settings in new installation?

**Comment by yyysuo** [comment]
> did you use portable settings in new installation?

no,when I install wox again,no windows shows up

**Comment by bao-qian** [comment]
since your setting for portable version is located in separate place,you can backup it.
after install new version, everything is completely new.
which means you should enable portable settings again, then close and copy paste you previous backup to your new wox installation location.
