### ISSUE TITLE
Results Scrolling Too Quickly

### ISSUE THREAD

**Issue by eytanweber** [Wox-launcher/Wox#2887]
When I try to scroll through the results of a search, they move way too quickly for me to actually see. As you can see in the attached video, I used my email program as a tester to show you that my trackpad scrolls at a normal speed. Then I opened a Wox search, and the scroll is so sensitive that it flies through results so quickly that I can't see any of them that aren't at the very top or very bottom. Is there a way to slow down the scroll speed?

Here is the tech info:
- HP Zbook Studio x360 G5
- Windows 10 Pro for Workstations, Version 1909, OS Build 18363.778
- Touchpad: Synaptics HID ClickPad, Driver: 19.5.9.38

Please let me know if you have any questions or need any other information.

**Comment by bao-qian** [comment]
hi, I can't find your "attached video"

**Comment by bao-qian** [comment]
and please give the wox version

**Comment by eytanweber** [comment]
I apologize, but the website doesn't allow for me to upload a video file directly. It seems like only image files, excel files, document files, and log files are accepted. I tried zipping the video file, but I guess it didn't come through. Here is a Dropbox link to it instead:

https://www.dropbox.com/s/78myssnq9ff275w/eM%20Client%202020-04-27%2010-50-08.mp4?dl=0

And sorry I forgot the Wox version. It's 1.3.578.

**Comment by roose** [comment]
@eytanweber no Wox window on video =)
@bao-qian "too fast", it's about the results being scrolled by screen, you know, e.g. if max results setting is 6, then for 1 shift the wheel scrolls every 6 results, not one by one

sorry for my english )

**Comment by eytanweber** [comment]
Sorry about that. I guess Wox is invisible to screen recording. But that point is that it's way too sensitive to the point that I can't control it. For example, if I have it set to show 15 results total, and I only see 5 at a time, then I can see the first 5 when it pops up, but not the second 5 results because if I try to scroll down to see the next 5, it immediately jumps to the bottom 5 results.

**Comment by bao-qian** [comment]
@eytanweber 
hi the wox windows is not in your video.
you can use your phone for screen capture if you don't know how to record it.

**Comment by eytanweber** [comment]
Sorry about that. Here's a link to a video taken with my phone.

https://www.dropbox.com/s/tg42lkyrdb31ask/20200429_115335.mp4?dl=0

**Comment by bao-qian** [comment]
@eytanweber 
Hi thanks for your report. I will try to fix it later.

here is a compressed video for future ref.
[scroll_too_quick.zip](https://github.com/Wox-launcher/Wox/files/4559193/scroll_too_quick.zip)
