### ISSUE TITLE
the version v1.3.881 search slowly in portable model.

### ISSUE THREAD

**Issue by greenhand520** [Wox-launcher/Wox#2888]
the version v1.3.881 search slowly in portable model, but when I use everything to search, it's so quickly.
here is the gif
![search so slowly](https://user-images.githubusercontent.com/32732204/80441548-af94db00-893d-11ea-83b7-c6b0cb1cfba2.gif)

**Comment by bao-qian** [comment]
could you compare with non-portal mode?

**Comment by greenhand520** [comment]
first search new keyword, search process is also slow in non-portable model.but search keyword searched before, it maybe quicklyer than in portable model.😨😨😨

**Comment by sergio-u** [comment]
For me it is slow in 1.3.981 but not in 1.3.881 (non-portable mode).

**Comment by bao-qian** [comment]
@mdmbct 
@serch037 
please try new build 
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.996

reopen if you still have issue
