### ISSUE TITLE
Settings window is cropped

### ISSUE THREAD

**Issue by S-ed** [Wox-launcher/Wox#2890]
**Describe the bug**
Settings window is cropped.

**To Reproduce**
Open settings
Go to General tab, or Web Searches plugin

**Expected behavior**
Scrollbar appears at least

**Runtime info**
 - Windows 10 Version: 1809 (Pro)
 - Wox version 1.3.881

**Screenshots**
![screenshot 1588078056](https://user-images.githubusercontent.com/3008353/80488849-aae51c80-8967-11ea-8c24-efb2e16f44d1.png)
![screenshot 1588078744](https://user-images.githubusercontent.com/3008353/80495072-1b903700-8970-11ea-8dc2-bc696ef6e0e3.png)

**Comment by bao-qian** [comment]
duplicate https://github.com/Wox-launcher/Wox/issues/2879
try new build
https://ci.appveyor.com/project/bao-qian/wox/builds/32420882/artifacts

**Comment by S-ed** [comment]
@bao-qian It is fixed! Sorry, I was not aware if it's a duplicate (used search beforehand).

**Comment by bao-qian** [comment]
@S-ed that's fine :)
