### ISSUE TITLE
1.3.981 版本 两个错误造成程式自动关闭，及一个问题反馈

### ISSUE THREAD

**Issue by dasu88** [Wox-launcher/Wox#2898]
版本：1.3.981

问题一、新增热键功能造成程式自动关闭，gif录影如下
![001](https://user-images.githubusercontent.com/23251263/80679646-e0b50d00-8aef-11ea-88eb-8a759fb83c23.gif)

问题二、所有plugin，点击触发关键字，亦造成程式自动关闭，gif录影如下
![002](https://user-images.githubusercontent.com/23251263/80679713-fcb8ae80-8aef-11ea-853e-a2ed787b64b9.gif)

问题三、有时开启执行时，会无反应…需等待一段时间后，才会有符合清单出现，疑似与everything的整合有关，如关闭everything外挂会好一些。

**Comment by bao-qian** [comment]
for problem 3, please try new build
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.996

**Comment by bao-qian** [comment]
problem 1 and 2 should be fixed in newest release
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1012

**Comment by dasu88** [comment]
问题一新增热键导至程式关闭问题仍未修复
![001](https://user-images.githubusercontent.com/23251263/81878193-e879b480-95b9-11ea-9d69-234a594b14df.gif)

**Comment by bao-qian** [comment]
@dasu88 
thanks for report, please try https://ci.appveyor.com/project/bao-qian/wox/builds/32875316/artifacts
