### ISSUE TITLE
File system autocomplete is not working

### ISSUE THREAD

**Issue by Leon99** [Wox-launcher/Wox#290]
In order to use Wox as a replacement for the system Run dialog, I would like to have a possibility to choose one of the suggestions and continue typing. E.g.:
1. User types >c:\W
2. Result list suggests C:\Windows
3. User presses \
4. Input box populates >C:\Windows\, allowing me to continue typing path and provides a list of folders & files under C:\Windows

**Comment by petsuter** [comment]
I have Wox 1.2.0-beta.2. Is this supposed to be fixed there? Because I still can't find a way to select the autocomplete suggestion and then continue writing. I would prefer "Tab" to select the suggestion.

**Comment by wonrax** [comment]
Why is this closed? I still don't know how to autocomplete a directory.
