### ISSUE TITLE
Calculator: Allow the use of commas as unit separator

### ISSUE THREAD

**Issue by HASJ** [Wox-launcher/Wox#2903]
**Is your feature request related to a problem? Please describe.**
My country and Windows use `,` to separate units in operation and, while the calculator in Wox is very handy, it is mildly annoying.

**Describe the solution you'd like**
A plugin option to choose between dots, commas or whatever symbol the user would like to use.

**Describe alternatives you've considered**
There is no alternative outside of using Windows' native calculator

**Additional context**
![image](https://user-images.githubusercontent.com/9345660/80832032-4d004100-8bc2-11ea-9430-fd7d33a82394.png)

![image](https://user-images.githubusercontent.com/9345660/80832052-5689a900-8bc2-11ea-9908-2ecb09f15d0d.png)

**Comment by SysC0mp** [comment]
That should already be possible in the latest version.

**Comment by HASJ** [comment]
> That should already be possible in the latest version.

I'm on v1.3.524 and check for updates does nothing.
