### ISSUE TITLE
建议便携版添加功能同时启动everything.exe文件

### ISSUE THREAD

**Issue by hawkDR** [Wox-launcher/Wox#2906]
便携版的，是否可以考虑启动wox添加一个选项，同时启动便携路径下的everything.exe文件，既然wox搜索文件需要everything支持，大神是否考虑再集成下，直接启动wox就可以用搜索，而不是要自己再提前运行everything这个软件

**Comment by bao-qian** [comment]
把 everything 的 windows 服务选项勾上。

**Comment by bao-qian** [comment]
![image](https://user-images.githubusercontent.com/1169912/81141173-6a585500-8f9e-11ea-9009-b89d99eb8358.png)
