### ISSUE TITLE
Hi I am being asked to activate plugins every time try to use wiki or youtube.. Please help

### ISSUE THREAD

**Issue by K-aushik** [Wox-launcher/Wox#2908]
![Untitled](https://user-images.githubusercontent.com/64869649/81115731-cfca2880-8f41-11ea-8268-8b2a2bf148b1.png)

**Comment by K-aushik** [comment]
Google search works fine other “web searches” dont. They ask “web searches” to be activated. How do I activate?

**Comment by bao-qian** [comment]
that's misunderstanding about the tool tip.
what it means is use `youtube keyword` to search content from youtube website.

**Comment by Yuj1n** [comment]
@bao-qian I have the same problem using the Web Searches Plugin.

When I try use the shortcut for a Google Search "g" it works fine (see below)

![Search Google](https://user-images.githubusercontent.com/27393533/81520659-46bf5100-9388-11ea-8ae2-b6343611c418.png)

However when I try any search like Youtube, Wiki, Duckduckgo, Drive etc it doesn't give me the option to execute the search 

![Drive](https://user-images.githubusercontent.com/27393533/81520765-88e89280-9388-11ea-9f89-50e9a7c7cc5b.png)
![Wiki](https://user-images.githubusercontent.com/27393533/81520768-8a19bf80-9388-11ea-83cb-d152650d6053.png)

Is there a setting I've missed to get this to work?

Thanks

**Comment by mcleodd10** [comment]
I'm likewise having a similar issue. For anything but Google the actual search option appears at the bottom of the list, while the 'Activate Web Searches plugin' result always appears at the top; this is the case for custom searches as well.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.

@evilmanimani  @Yuj1n

**Comment by Yuj1n** [comment]
@bao-qian 

Thank you, tested and working for me.
