### ISSUE TITLE
Crash on attempting action keyword change

### ISSUE THREAD

**Issue by brukberhane** [Wox-launcher/Wox#2909]
**Describe the bug**
The app crashes whenever I attempt to press on an action keyword on the extensions tab of the settings page. No workaround any and all action keywords being changed cause a crash

**To Reproduce**
1. Go into the app settings
2. Click the new tab section
3. Try to change an action keyword for any given extension
4. No error is reported. The application stops responding and promptly closes.

**Expected behavior**
For it to give me some sort of interface to change the action keyword

**Runtime info**
 - Windows 10 Version: `Win 1909 Buld 18363.778`
 - Wox version: `1.3.996`

**Wox Error Window text**
None generated.

**Detailed logs**
[2020-05-06.txt](https://github.com/Wox-launcher/Wox/files/4584018/2020-05-06.txt)

**Comment by tinbolw** [comment]
I am getting the same issue, have no idea how to fix it

**Comment by brukberhane** [comment]
@tinbolw the only fix I've managed to find for it is to downgrade to the last stable version of wox (but 1.5.578 works as well) and change the keywords you want then. You can then upgrade back to the latest pre-release

**Comment by tinbolw** [comment]
Alright, I'll try that

**Comment by tinbolw** [comment]
> @tinbolw the only fix I've managed to find for it is to downgrade to the last stable version of wox (but 1.5.578 works as well) and change the keywords you want then. You can then upgrade back to the latest pre-release

it worked, thanks

**Comment by bao-qian** [comment]
try new build which fix this crash
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1012
