### ISSUE TITLE
网页搜索插件功能异常

### ISSUE THREAD

**Issue by flymanthl** [Wox-launcher/Wox#2910]
这里我将使用GitHub搜索的热键改为了git，看下面动图中，
第一次输入git时，后面紧接着打了一个冒号，然后把这个冒号删除了，GitHub的搜索提示才显示出来。第二次输入git时，按照正常操作习惯，打了一个空格，然后随便输了一串搜索内容，这时GitHub的搜索提示无法显示，按回车程序也没有反应，并没有打开浏览器使用GitHub搜索
![test](https://s1.ax1x.com/2020/05/06/YAZYex.gif)
我的热键设置
![setting](https://s1.ax1x.com/2020/05/06/YAZH00.png)
版本的是1.3.996
![version](https://s1.ax1x.com/2020/05/06/YAZvp4.png)

**Comment by wgf4242** [comment]
网页搜索。经常不好使。。我第一次用。

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/bao-qian/wox/builds/32876502/artifacts
try new build
which should fix this bug
