### ISSUE TITLE
With Launchbar I can see live results as I search for items

### ISSUE THREAD

**Issue by gitguys** [Wox-launcher/Wox#2911]
**Is your feature request related to a problem? Please describe.**

Wox is great but I'm much more productive with Launchbar for Mac because of interactive searches for sites such as Wikipedia.

**Describe the solution you'd like**

With Launchbar I can see live results as I search for items.  For example:

![launchbar wikipedia wox wish](https://user-images.githubusercontent.com/11050768/81374144-d086ca00-90bb-11ea-96b6-90f3540dbe45.png)

I can simply hit the down arrow key to the result I want, then hit enter and go to it.

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/bao-qian/wox/builds/32876502/artifacts
please try new build

you can search wiki with  `wiki` keyword, but query suggestion is only support for google and baidu.
![image](https://user-images.githubusercontent.com/1169912/81946580-1ef31600-9632-11ea-9263-11083d95e7b7.png)

![image](https://user-images.githubusercontent.com/1169912/81946557-18649e80-9632-11ea-9e2f-b71d80ea5c0c.png)

I'd appreciate you can open pr for wiki query suggestion.
