### ISSUE TITLE
最新996版输入时卡顿严重

### ISSUE THREAD

**Issue by qw4096** [Wox-launcher/Wox#2914]
现在用的是996版，输入的时候常常卡顿，换会981版后倒是没那么卡了，但发现输入后常常不出结果，再输入空格才出，再回退到881才没有上述问题

**Comment by WangJincheng4869** [comment]
的确是 我也发现更新到996变得卡顿很多。虽然软件的图标可以正常获取了，以前的老版本不能获取，还是先退回老版本吧 最起码不卡

**Comment by westfly** [comment]
996版本名字不吉利啊

**Comment by bao-qian** [comment]
try this new build, which should fix ui blocking cause by image load
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1012

if still feel ui laggy, open new issue with details.
