### ISSUE TITLE
最新版本问题有点多，反映速度慢，找不到输入的内容，没有首字母查找了

### ISSUE THREAD

**Issue by Mikluv** [Wox-launcher/Wox#2915]
1.检索速度慢了很多
2.我以前输入WE就可以定位到微信，但是新版定位不到了
3.wx这种首字母也搜不到了。

所以暂时回退到578版本

**Comment by WangJincheng4869** [comment]
没错的！我也回退578了

**Comment by bao-qian** [comment]
1. try this new build, which should fix ui blocking cause by image load
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1012

if still feel ui laggy, open new issue with details.

2. for the pinyin settings, check this option:
![image](https://user-images.githubusercontent.com/1169912/81843457-3376d600-9580-11ea-8a04-bdbcbb894a2a.png)

**Comment by Mikluv** [comment]
你好，这个版本拼音简写的问题解决了。检索速度也快了很多

我打开了 Should Use Pinyin，但是还是有拼音找不到文件的问题
![Snipaste_2020-05-14_11-56-21](https://user-images.githubusercontent.com/32835511/81891161-5a61f600-95da-11ea-8fc1-2eadab750d14.png)
![Snipaste_2020-05-14_11-56-30](https://user-images.githubusercontent.com/32835511/81891171-5f26aa00-95da-11ea-9af5-1a274aea0d68.png)

以上截图为使用时候的问题

**Comment by bao-qian** [comment]
pinyin is only supported in program result, not regular files.
