### ISSUE TITLE
Win/malicious_confidence_60% (W) / Suspicious.low.ml.score

### ISSUE THREAD

**Issue by Cheptii** [Wox-launcher/Wox#2916]
Hello, 

I scanned the .exe file on virustotal.com and a malware has been detected.

![image](https://user-images.githubusercontent.com/32555483/81487019-c569a080-9259-11ea-8fc7-ff1fa9bfc332.png)

1. Go to 'virustotal.com'
2. upload .exe file and click on scan.

can you please fix this ?

Kind Regards,
Chepti

**Comment by bao-qian** [comment]
Hi, 
that's false positive result. the code is open sourced, you can check the code if you don't trust the release.
since there are only 3 out of 72 claim this is virus, I suggest just ignore it.
