### ISSUE TITLE
Crash and  show a BIG "|" when launched sometimes

### ISSUE THREAD

**Issue by lannyyip** [Wox-launcher/Wox#2918]
To be able to help you we need enough information to find
what is causing your issue. Please follow the instructions 
and type the requested information where prompted. 

Please try reset Wox before continue, backup before you do.
Reset: delete `%APPDATA%\Wox`

Please delete unnecessary instructions after you finished your bug report.

**Describe the bug**
When launch WoX, quite often that would show a BIG "|" in the screen, without responding any key as WoX is in front. I have to restart WoX to get rid of it.

**To Reproduce**
1. Launch WoX by hot key
2. Ocassionally ,would show up a BIG "|". No key responding.

**Expected behavior**
1. Launch WoX by hot key
2. accept my key and respond correctly

**Runtime info**
 - Windows 10 Version: 
Windows 10 Professional 1909 18363.78
 - Wox version
1.3.524
**Wox Error Window text**
Dont know how to the error text

**Screenshots**
![Snipaste_2020-05-12_11-27-02](https://user-images.githubusercontent.com/3487748/81635944-1be70280-9445-11ea-9545-71c24e51ccd8.png)

drop and drop your screenshots here.

**Additional context**

**Detailed logs**
Please upload latest log file: 
`%APPDATA%\Wox\Logs\version\<date>.txt`
Please upload log as a whole file
[2020-05-12.txt](https://github.com/Wox-launcher/Wox/files/4613241/2020-05-12.txt)
drop and drop your latest log file here

**Comment by bao-qian** [comment]
duplicate #962 
I can't fix this right now since I cannot reproduce it.
please subscribe #962 for udpates.
