### ISSUE TITLE
Wrong startup item

### ISSUE THREAD

**Issue by kubalav** [Wox-launcher/Wox#2928]
**Describe the bug**
Startup item is wrong: Wox.Infrastructure.dll
I have to set right path to Wox.exe

**Runtime info**
 - Windows 10 Version:  Win 10 build 10.0.18363.836
 - Wox version: v1.3.1034

**Comment by bao-qian** [comment]
try new build 
https://ci.appveyor.com/project/bao-qian/wox/builds/32881874/artifacts
