### ISSUE TITLE
Issue when searching HOI4

### ISSUE THREAD

**Issue by sfwssc1** [Wox-launcher/Wox#2929]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\sfwss\AppData\Roaming\Wox\Logs\1.3.1036\2020-05-14.txt
2. copy below exception message
[2020-05-14.txt](https://github.com/Wox-launcher/Wox/files/4630444/2020-05-14.txt)

Exception begin --------------------
  System.AggregateException: One or more errors occurred.
  HResult: -2146233088
  StackTrace: --------------------

  InnerException 1: ------------------------------------------------------------
    System.UnauthorizedAccessException: Access to the path 'E:\Games\Hearts of Iron IV\wiki\images\thumb\f\f0\HoI4_DD_1_map.jpg' is denied.
    HResult: -2147024891
    Source: mscorlib
    TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    TargetModule: CommonLanguageRuntimeLibrary
    TargetSite: Void WinIOError(Int32, System.String)
    StackTrace: --------------------
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at Wox.Image.ImageLoader.LoadInternal(String path) in C:\projects\wox\Wox\Image\ImageLoader.cs:line 71
   at Wox.Image.ImageCache.Add(String key, Func`2 imageFactory) in C:\projects\wox\Wox\Image\ImageCache.cs:line 111
   at Wox.Image.ImageCache.<>c__DisplayClass11_0.<GetOrAdd>b__0() in C:\projects\wox\Wox\Image\ImageCache.cs:line 95
   at System.Threading.Tasks.Task.Execute()
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Wox.exe" 
* Timestamp: 05/14/2020 15:24:06
* Wox version: 1.3.1036
* OS Version: Microsoft Windows NT 10.0.18363.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0
   * v4.8

## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Wox.exe)
* Wox.Core, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\NLog.dll)
* Wox.Plugin, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Mindscape.Raygun4Net.dll)
* Wox.Plugin.Color, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* HelloWorldCSharp, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.BrowserBookmark, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.Everything, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.ControlPanel, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Folder, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.Caculator, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\WindowsInput.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Url, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Wox.Plugin.Sys, Version=1.3.1036.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\NHotkey.dll)
* SQLitePCLRaw.batteries_v2, Version=2.0.2.669, Culture=neutral, PublicKeyToken=8226ea5df37bcae9 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.batteries_v2.dll)
* SQLitePCLRaw.core, Version=2.0.2.669, Culture=neutral, PublicKeyToken=1488e028ca7ab535 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.core.dll)
* SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.2.669, Culture=neutral, PublicKeyToken=b68184102cba0b3b (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.provider.dynamic_cdecl.dll)
* System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\System.Memory.dll)
* SQLitePCLRaw.nativelibrary, Version=2.0.2.669, Culture=neutral, PublicKeyToken=502ed628492ab262 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.nativelibrary.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\NHotkey.Wpf.dll)
* System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Plugins\Wox.Plugin.BrowserBookmark\System.Runtime.CompilerServices.Unsafe.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\CommandLine.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\NuGet.Squirrel.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Management.winmd)
* Microsoft.WindowsAPICodePack.Shell, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Microsoft.WindowsAPICodePack.Shell.dll)
* Microsoft.WindowsAPICodePack, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\sfwss\AppData\Local\Wox\app-1.3.1036\Microsoft.WindowsAPICodePack.dll)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Storage.winmd)
* Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll)
* System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
* System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)
* System.Deployment, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll)
* PresentationFramework-SystemDrawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemDrawing\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemDrawing.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)

**Comment by bao-qian** [comment]
please check this build, reopen if problem still exist.
https://ci.appveyor.com/project/bao-qian/wox/builds/32892835/artifacts
