### ISSUE TITLE
Differences between Wox-1.3, Wox-Full-Installer.1.3, and Everything unclear

### ISSUE THREAD

**Issue by archon810** [Wox-launcher/Wox#2931]
Hi,

https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1036 includes 3 exe assets, and the differences between them are unclear and undocumented on the site http://www.wox.one/, the docs http://doc.wox.one/en/, or the release page.

What does Full Installer include and when is it needed vs just Wox?

What is Everything?

Very confusing.

**Comment by archon810** [comment]
Btw, I'm very excited about Wox development getting resumed https://twitter.com/ArtemR/status/1261025367172673536. The project isn't dead after all, yay!

**Comment by archon810** [comment]
Also Windows Smart Screen is stopping installation. Did you change certificates or something?

**Comment by bao-qian** [comment]
thanks for support, you could also star this project. 

zip is used for portable mode, full installer include everything and python.
the doc will be updated when prerelease become release. I will update release info at the moment.

there is no certificate as before, for the smart screen to work, you could click "more info" to let wox pass. I will try to get some certificate in the future.

**Comment by bao-qian** [comment]
What is Everything?

Everything is a windows program which can search files in whole disk super fast, wox has integration plugin with Everything, but Everything needed installed first.
