### ISSUE TITLE
Error in 1.3.1039.zip | remove update.exe / squirrel  dependency for protable version

### ISSUE THREAD

**Issue by kubalav** [Wox-launcher/Wox#2933]
How to update the portable version? If I download *.Zip the Wox need an update.exe file, otherwise error. I used to update overwrite the existing version, but update.exe needed nowadays.

Is some workaround?

**Comment by bao-qian** [comment]
What would happen when you just use zip content to overwrite your portable folder?
could you give more details?

**Comment by kubalav** [comment]
I renamed the folder "app-1.3.1036" to wox and then run wox.exe - nothing happens. I try to open wox.exe from new wox folder and it is working. Do you think I can update this way?

**Comment by bao-qian** [comment]
could you provide a gif? so I can understand your issue better.

**Comment by kubalav** [comment]
If you download older Wox version e.g. v1.3.996 you can extract and run it without error. If you download the newest version v1.3.1039 and extract and run, you got an error message. Try it and you'll see. If you put update.exe file in the folder up, Wox is working without error.

Working scenario:

C:/Wox-v1.3.1039/
C:/update.exe

**Comment by bao-qian** [comment]
Hi, 

I test with windows sandbox, no error with both 1.3.996.zip or 1.3.1039.zip
![image](https://user-images.githubusercontent.com/1169912/82033945-0f2a0f00-96d0-11ea-9416-83d748dcf0b5.png)

and there is no updated.exe in both version.

below steps tested with windows sandbox.

1. suppose you are currently using portable version 1.3.996.zip
2. if you want to upgrade it, download 1.3.1039.zip
3. unzip it to a folder called wox-1.3.1039
4. close running wox
5. copy `UserData` from wox-1.3.996 folder to wox-1.3.1039.
6. start wox.exe inside wox-1.3.1039.

**Comment by kubalav** [comment]
![wox-bug-report](https://user-images.githubusercontent.com/37414585/82041323-44bb0200-96a8-11ea-9bb5-dad6414b6da4.gif)

**Comment by bao-qian** [comment]
got it, will look into it.

**Comment by bao-qian** [comment]
please try new build, which has fix for this bug
https://ci.appveyor.com/project/bao-qian/wox/builds/32932696/artifacts

let me know if it fix or not.

@WindFi @Jobilein @kubalav

**Comment by kubalav** [comment]
It is working!
