### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ragingtom** [Wox-launcher/Wox#2939]
[2020-05-15.txt](https://github.com/Wox-launcher/Wox/files/4637900/2020-05-15.txt)

Exception begin --------------------
  System.AggregateException: One or more errors occurred.
  HResult: -2146233088
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: mscorlib
  TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: CommonLanguageRuntimeLibrary
  TargetSite: Void ThrowIfExceptional(Boolean)
  StackTrace: --------------------
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginsLoader.CSharpPlugins(List`1 source) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 90
   at Wox.Core.Plugin.PluginsLoader.Plugins(List`1 metadatas, PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 25
   at Wox.Core.Plugin.PluginManager.LoadPlugins(PluginsSettings settings) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 97
   at Wox.App.<OnStartup>b__16_0() in C:\projects\wox\Wox\App.xaml.cs:line 102
   at Wox.Infrastructure.Stopwatch.StopWatchNormal(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 34
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  InnerException 1: ------------------------------------------------------------
    System.IndexOutOfRangeException: Index was outside the bounds of the array.
    HResult: -2146233080
    Source: mscorlib
    TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    TargetModule: CommonLanguageRuntimeLibrary
    TargetSite: Void Add(T)
    StackTrace: --------------------
   at System.Collections.Generic.List`1.Add(T item)
   at Wox.Core.Plugin.PluginsLoader.<>c__DisplayClass5_1.<CSharpPlugins>b__2() in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 86
   at Wox.Infrastructure.Stopwatch.StopWatchDebug(Logger logger, String message, Action action, String methodName) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 22
   at Wox.Core.Plugin.PluginsLoader.<>c__DisplayClass5_0.<CSharpPlugins>b__1(PluginMetadata metadata) in C:\projects\wox\Wox.Core\Plugin\PluginsLoader.cs:line 87
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Wox.exe" --squirrel-firstrun
* Timestamp: 05/15/2020 22:55:32
* Wox version: 1.3.1039
* OS Version: Microsoft Windows NT 10.0.17134.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03761
   * v4 Full 4.8.03761
   * v4.0 Client 4.0.0.0
   * v4.8

## SDK Info
* Python Path: 
* Everything SDK Path: 

## Assemblies - Wox.exe

* Wox, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Wox.exe)
* Wox.Core, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\NLog.dll)
* Wox.Plugin, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net.dll)
* Wox.Plugin.Color, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.BrowserBookmark, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.Everything, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.PluginManagement, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Caculator, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Wox.Plugin.ControlPanel, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* HelloWorldCSharp, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Folder, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.Program, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.Shell, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.WebSearch, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\WindowsInput.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* SQLitePCLRaw.batteries_v2, Version=2.0.2.669, Culture=neutral, PublicKeyToken=8226ea5df37bcae9 (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.batteries_v2.dll)
* SQLitePCLRaw.core, Version=2.0.2.669, Culture=neutral, PublicKeyToken=1488e028ca7ab535 (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.core.dll)
* SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.2.669, Culture=neutral, PublicKeyToken=b68184102cba0b3b (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.provider.dynamic_cdecl.dll)
* System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\System.Memory.dll)
* SQLitePCLRaw.nativelibrary, Version=2.0.2.669, Culture=neutral, PublicKeyToken=502ed628492ab262 (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.nativelibrary.dll)
* System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\alex\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\System.Runtime.CompilerServices.Unsafe.dll)
* Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll)
* System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)

**Comment by bao-qian** [comment]
please try new build, which has fix for this bug

https://ci.appveyor.com/project/bao-qian/wox/builds/32932441/artifacts

let me know if it fix or not.
