### ISSUE TITLE
Unable to use any commands

### ISSUE THREAD

**Issue by sr884** [Wox-launcher/Wox#2941]
![Annotation 2020-05-16 140432](https://user-images.githubusercontent.com/57920226/82120457-2f180c00-977e-11ea-804f-60c42640a48b.png)
I'm unable to use any of the plugin commands, e.g. Spotify - 'sp'. It doesn't bring up any options to play or even initiate the API. 

In fact, I can't even perform "wpm install <plugin>". My Python directory in settings has already been selected to 'Anaconda3' (where python is).

Please could you advise.

**Comment by bao-qian** [comment]
could you upload logs and specify wox version?

**Comment by bao-qian** [comment]
you could also try new release
https://github.com/Wox-launcher/Wox/releases

**Comment by sr884** [comment]
> you could also try new release
> https://github.com/Wox-launcher/Wox/releases

Thanks, the new update has solved this issue.

**Comment by bao-qian** [comment]
good to hear
