### ISSUE TITLE
Can't open searchbar or app by hotkey after windows start up completely.

### ISSUE THREAD

**Issue by HumanMus1c** [Wox-launcher/Wox#2946]
Even kill itself in the background after re-activate it!

**Comment by bao-qian** [comment]
please describe your question in details
you can also upload gif.
I cannot understand your question.

**Comment by HumanMus1c** [comment]
> please describe your question in details
> you can also upload gif.
> I cannot understand your question.

Wox cannot run automatically as windows booted even I selected the "start Wox on system startup" checkbox. And it kills itself or something did in the background after I ran it once.

**Comment by bao-qian** [comment]
@GOMrHU 
please give version number and upload latest log file in. `%APPDATA%\Wox\Logs`

**Comment by bao-qian** [comment]
for the auto statup settings, please try new build
https://ci.appveyor.com/project/bao-qian/wox/builds/32932441/artifacts

**Comment by HumanMus1c** [comment]
I'm using the latest version 1.3.1039

> @GOMrHU
> please give version number and upload latest log file in. `%APPDATA%\Wox\Logs`

there were 6 logs, upload this latest one.
[2020-05-17.txt](https://github.com/Wox-launcher/Wox/files/4640439/2020-05-17.txt)

**Comment by bao-qian** [comment]
@HumanMusicX 

1 try new release https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1073
2 remove `Python Calculator` plugin by delete it from %APPDATA%\Wox\Plugins folder.
