### ISSUE TITLE
After update new version, Wox-search is slower than Cortana-search which was not.

### ISSUE THREAD

**Issue by HumanMus1c** [Wox-launcher/Wox#2947]
I'd rather use the old version of Wox than the latest version for more efficiency!

**Comment by bao-qian** [comment]
please give the version number.
which version is slow, which version is faster.

**Comment by HumanMus1c** [comment]
> please give the version number.
> which version is slow, which version is faster.

Sorry, I didn't notice the version of that old one, But the latest updates really make me feel Wox's search process is slower than Cortana.  And sometime Wox doesn't put the most click result in the first place.

**Comment by ghost** [comment]
I have same problem, but only when I am searching for Files using everything, I am on version 1.3.1036,
any way to solve this issue

**Comment by HumanMus1c** [comment]
> I have same problem, but only when I am searching for Files using everything, I am on version 1.3.1036,
> any way to solve this issue

sorry, I don't know either, so I posted this issue to the developer.

**Comment by bao-qian** [comment]
@GOMrHU @vivek-nodes 
please try new build, which has performance optimization 
https://ci.appveyor.com/project/bao-qian/wox/builds/32932441/artifacts

**Comment by ghost** [comment]
@bao-qian Installed it, File Search Seems Faster than 1036.I  will report back after the use of 1-2 days

**Comment by bao-qian** [comment]
nice, let me know if it still slow.

**Comment by bao-qian** [comment]
please also try this new release, which improvement into a new level.
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1071

**Comment by ghost** [comment]
@bao-qian  sure

**Comment by ghost** [comment]
@bao-qian Everything File Search working perfectly. I am Using `[Alfred](https://github.com/waterzhang0423/WoxAlfredTheme)` Theme with Wox and every time i install new version it will remove alfred theme files, i have add it manually everytime i want to Update.

**Comment by bao-qian** [comment]
@vivek-nodes please open separate issue for this.
