### ISSUE TITLE
Environment/System variables aren't being reloaded

### ISSUE THREAD

**Issue by corevo** [Wox-launcher/Wox#295]
If I change my environment variables, and then open cmd through Wox, the change wouldn't take effect.
While just going to start menu and opening it would refresh the variables.
It is very frustrating when using with applications that change the PATH, I've ran into a problem with Ruby, where I couldn't figure out why ruby gems wasn't recognized by my command prompt although being in the PATH environment variable.

**Comment by bao-qian** [comment]
Try restart Wox
![2015-11-03_17-40-55](https://cloud.githubusercontent.com/assets/1169912/10916188/1a4eb1b6-8252-11e5-9428-5c43a35fcea9.png)

**Comment by iEverX** [comment]
Restarting wox didn't solve this problem

**Comment by happlebao** [comment]
@EverX what's your wox version?

**Comment by bao-qian** [comment]
@iEverX 你的 wox 是什么版本？你有去 release 下最新版试一下吗？或者试一下 [build 1.2.710](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.710/artifacts)

**Comment by iEverX** [comment]
@happlebao 
是最新的release，确认过不可以

最新的build还没试过

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900
the latest version should fix this problem since it will launch new process every time 
reopen if you still can't solve it

**Comment by ZumiKua** [comment]
same here.My Wox version is 1.3.67.
restart wox didn't solve the problem neither.

OS: Windows 10 Home x64

**Comment by elminsterjimmy** [comment]
Same issue in my site. wox version: 1.3.424.
OS: win7 pro sp 1

**Comment by atahrijouti** [comment]
v: 1.3.475 os: Windows 10 Pro

The only way to have environment variables back is through manually closing wox
