### ISSUE TITLE
bat vbs and some exe can't work when start from wox

### ISSUE THREAD

**Issue by theFool32** [Wox-launcher/Wox#296]
A simple vbs like

``` vbs
CreateObject("WScript.Shell").Run "aria2c.exe --conf-path=aria2c.conf",0
```

works well if starts from explorer,but gets error in wox.
![Uploading Unnamed QQ Screenshot20150626150217.png…]()
However it works correctly by starting by lnk in wox.

some exe also get errors saying lacking dlls while dlls are in the same directory.

**Comment by theFool32** [comment]
Image uploaded failed..
Vbs error:

```
脚本：D:\Program Files\Tools\Aria2c\runAria2.vbs
行：1
字符：1
错误：系统找不到指定的文件
代码：80070002
源：（null）
```

**Comment by jack71** [comment]
getting same error

**Comment by vovkkk** [comment]
I’m not sure, but since it says 错误：系统找不到指定的文件 and lnk file defines working directory, I think this is the reason, i.e. your script should set working directory or call exe using absolute path.
And probably you’d need to escape whitespace in path or get path with some vbs method (like `os.path.dirname(os.path.abspath(__file__))` in Python or `cd /D %~dp0` in batch file), but I dunno anything about vbs.

For instance, bat:

``` bat
cd /D %~dp0
@start aria2c.exe --conf-path=aria2c.conf
```

**Comment by theFool32** [comment]
@vovkkk 
It still failed after I change to call exe using absolute path..
Thx anyway :)

**Comment by vovkkk** [comment]
Well, my bat file works just fine, e.g. launch ipython 

``` bat
cd /D D:\Dropbox\mine\notes-md\ip-notebooks
@start ipython notebook
```

I don’t understand how you call aria2c.exe without argument for URL? what it supposed to do? print help page and exit, no?

**Comment by theFool32** [comment]
@vovkkk 
--conf-path=aria2c.conf    sets config.
This script run aria2c.exe and keep it running in the background (because -D doesn't work for me)
Then you can use [yaaw](https://github.com/binux/yaaw) or [webui-aria2](https://github.com/ziahamza/webui-aria2) to manage it.

**Comment by vovkkk** [comment]
You should enable rpc either in command line:

``` bat
cd /D %~dp0
@start aria2c.exe --conf-path=aria2c.conf --enable-rpc --rpc-listen-all
```

or in [config file](https://wiki.archlinux.org/index.php/Aria2#Example_aria2.daemon)

BTW, both yaaw and webui readme mention need of rpc, works fine for me.

**Comment by theFool32** [comment]
I enable it in config file..And aria2 works fine for me too. - -

**Comment by roy128** [comment]
:+1:
