### ISSUE TITLE
Unable to cast object of type 'ProgramSource' to type 'Wox.Plugin.Program.Views.Models.ProgramSource

### ISSUE THREAD

**Issue by northward111** [Wox-launcher/Wox#2963]
Exception begin --------------------
  System.InvalidCastException: Unable to cast object of type 'ProgramSource' to type 'Wox.Plugin.Program.Views.Models.ProgramSource'.
  HResult: -2147467262
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: System.Core
  TargetAssembly: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: System.Core.dll
  TargetSite: Boolean MoveNext()
  StackTrace: --------------------
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Wox.Plugin.Program.Views.ProgramSetting.btnProgramSoureDelete_OnClick(Object sender, RoutedEventArgs e) in C:\projects\wox\Plugins\Wox.Plugin.Program\Views\ProgramSetting.xaml.cs:line 158
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Wox.exe" 
* Timestamp: 05/19/2020 20:14:39
* Wox version: 1.3.1073
* OS Version: Microsoft Windows NT 10.0.17763.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v4 Client 4.8.03761
   * v4 Full 4.8.03761
   * v4.0 Client 4.0.0.0
   * v4.8

## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Wox.exe)
* Wox.Core, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\NLog.dll)
* Wox.Plugin, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Mindscape.Raygun4Net.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\NuGet.Squirrel.dll)
* HelloWorldCSharp, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.Caculator, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Wox.Plugin.Color, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.BrowserBookmark, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.ControlPanel, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.Shell, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.WebSearch, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\WindowsInput.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\NHotkey.Wpf.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Foundation.winmd)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\CommandLine.dll)
* Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Management.winmd)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.Storage.winmd)
* Windows.System, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\Windows\system32\WinMetadata\Windows.System.winmd)
* Microsoft.WindowsAPICodePack.Shell, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Microsoft.WindowsAPICodePack.Shell.dll)
* Microsoft.WindowsAPICodePack, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\BigTomato\AppData\Local\Wox\app-1.3.1073\Microsoft.WindowsAPICodePack.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* System.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.resources.dll)
* mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
* Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
* System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
[2020-05-19.txt](https://github.com/Wox-launcher/Wox/files/4650295/2020-05-19.txt)

**Comment by bao-qian** [comment]
please try this build
https://ci.appveyor.com/project/bao-qian/wox/builds/32979562/artifacts

let me know if it fix or not.
