### ISSUE TITLE
Power Toys 0.18 just released with PowerToys Run, Is it going to Replace Wox?

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#2965]
Just want to know what are future plans for wox, I am Using Power Toys and today they just release 0.18 with power toys run. Just wanted to know if it's going to replace wox in long term. Currently it don't have Plugins and theme so It's not going to replace wox for now.

**Comment by yanghanlin** [comment]
Just FYI, Power Toys Run is in fact built on top of Wox (or at least using the code from Wox).

**Comment by ma0shu** [comment]
> Just FYI, Power Toys Run is in fact built on top of Wox (or at least using the code from Wox).

Yes.![image](https://user-images.githubusercontent.com/61415309/82438795-3287fc00-9acc-11ea-9c3a-ada05be6b5bf.png)

**Comment by ousugo** [comment]
Just because Powertoys Run is built on Wox, that's why the question to be a question. Both are open source. Powertoys Run is developing and operating by MicroSoft,  I guess it will have more developers and users than Wox.

So I also want to ask the question? Is it going to Replace Wox?

**Comment by bao-qian** [comment]
Hi,
Thanks for support for past usage.

Powertoys Run is built on top of Wox, with less feature.
Wox will have more feature and less bug, and it will not going to replace Wox.

to name a few, 
1. powertoy run won't have plugin, and wox will support more programming language to write plugin. js will be next.
2. powertoy run won't have custom theme.
3. powertoy run will collect privacy info https://github.com/microsoft/PowerToys/tree/master/src/modules/launcher/PowerLauncher.Telemetry
4. powertoy run won't integrate with everything to search files.

I will continue keeping in touch with ms.

**Comment by ghost** [comment]
> 1. powertoy run won't have plugin, and wox will support more programming language to write plugin. js will be next.

yeah, but as long it provides core functionality very well like app search, file search , settings search it's not going to matter for most people. Due to lack of Plugins, it's also very easy to setup and less less chances of plugin break something. Its just works out of the box without any setup.

> 2. powertoy run won't have custom theme.

Again if for most people as long as they don't hate it's look its going to be fine.

> 3. powertoy run will collect privacy info 
https://github.com/microsoft/PowerToys/tree/master/src/modules/launcher/PowerLauncher.Telemetry

I am Ok with data collation for better app development.

> 4. powertoy run won't integrate with everything to search files.

 As long as I am able to find my files it's not going to matter 95% of time, the only thing I am going to miss that advance search quarries.

**Comment by bao-qian** [comment]
@vivek-nodes 
in terms of core functionality, search. start menu already built in with windows, but people don't want to use it, because it is slow and don't have ability to do advanced query.

for the file search, one cannot do fast file search on windows without everything. and one cannot do advanced fuzzy file name match without everything.
for the program search, current wox version already search more uwp apps, and search faster than powertoy (which built on with previous stable wox version). wox will be even faster by using sophisticated algorithm in next version.

**Comment by transtone** [comment]
这就被官方收编了。👍

**Comment by bao-qian** [comment]
as I promised.
the latest release use advanced string algorithm to rewrite fuzzy match.
the index time and query time is 100 times faster.
try it out https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196

close due to no further discussion. reopen if you still have issue.
