### ISSUE TITLE
1.4.1115 ui blocking 卡死

### ISSUE THREAD

**Issue by flyinke** [Wox-launcher/Wox#2968]
1.4.1115 容易卡死，没找到日志文件
win10系统
上一个版本没有问题

**Comment by bao-qian** [comment]
1. please upload latest log file located in `%APPDATA%\Wox\Logs`
2. try reset settings by delete `%APPDATA%\Wox`
3. for the faster version, please give version number.
4. please describe in details
  3.1 ui will block under what circumstance?
  3.2 queries you use?
  3.3 settings you changes, like pinyin setting?

**Comment by ghost** [comment]
Yes, I have the same problem. If I turn on the Pinyin switch, it will get stuck.

**Comment by bao-qian** [comment]
please upload some video to show the ui blocking.

**Comment by ma0shu** [comment]
The same. my log:[2020-05-20.txt](https://github.com/Wox-launcher/Wox/files/4656288/2020-05-20.txt)

**Comment by bao-qian** [comment]
1 please upload some video to show the ui blocking. 
2 did you check pinyin settings?

@myy0222  @kingkongdog @flyinke

**Comment by ghost** [comment]
你是中国人吗？@bao-qian

**Comment by bao-qian** [comment]
@kingkongdog 
yes.

**Comment by flyinke** [comment]
https://c-t.work/s/91fc15939d7841

**Comment by ghost** [comment]
哈哈。牛。勾选pingyin开关，就会卡，不勾不卡。具体现象是，alt+space呼出搜索窗口后，按键盘任意按键，wox的搜索窗口都会卡住，没有任何响应。

**Comment by flyinke** [comment]
@bao-qian  Turn off the pinyin function, no problem.

**Comment by bao-qian** [comment]
@kingkongdog @flyinke @myy0222 

https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts
please try this new build, which has performance improvement for pinyin query.

**Comment by ma0shu** [comment]
> @kingkongdog @flyinke @myy0222
> please try this new build, which has performance improvement for pinyin query.

still block after reboot.  
![record](https://user-images.githubusercontent.com/61415309/82445127-e098a380-9ad6-11ea-8894-ff3694d92293.gif)

**Comment by ma0shu** [comment]
> @kingkongdog @flyinke @myy0222
> please try this new build, which has performance improvement for pinyin query.

无响应不强制关闭，一直等待到窗口消失，再开启就能用了。再次重启wox依然卡死。

**Comment by bao-qian** [comment]
@myy0222 did you turn pinyin setting on or off?

**Comment by ma0shu** [comment]
> @myy0222 did you turn pinyin setting on or off?

on. Turn off won't block.

**Comment by bao-qian** [comment]
@myy0222 
please wait 一直等待到窗口消失, then upload the latest log file in `%APPDATA%\Wox\Log`.

**Comment by bao-qian** [comment]
@myy0222 
1 did you try this new build ?
https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts

2 please download and try new build, then please wait 一直等待到窗口消失, then upload the latest log file in %APPDATA%\Wox\Log.

**Comment by ma0shu** [comment]
> @myy0222
> 1 did you try this new build ?
> https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts
> 
> 2 please download and try new build, then please wait 一直等待到窗口消失, then upload the latest log file in %APPDATA%\Wox\Log.

1.4.1125 is OK. Thanks a lot.
(Btw 新版本能优化一下速度吗？刚才退回1.3.578老版本速度提升肉眼可见

**Comment by bao-qian** [comment]
@myy0222 

thanks for confirm ,you can also contribute to this project by start it.
I will try my best to optimize the speed.

do you mean initial startup speed or query speed after several minutes?

**Comment by ma0shu** [comment]
> @myy0222
> 
> thanks for confirm ,you can also contribute to this project by start it.
> I will try my best to optimize the speed.
> 
> do you mean initial startup speed or query speed after several minutes?

已经star.  一开始以为是查询速度慢，刚刚试了下好像和以前也差不多，可能是刚刚启动的原因。但是图标缓存确实慢了些。

**Comment by jhdxr** [comment]
For the pinyin module, I found that sometimes there are very long descriptions which cause the `StringMatcher.ScoreForPinyin` consumed all the CPU & memory. As a workaround I just removed it (https://github.com/Wox-launcher/Wox/commit/90b1f2b63cedcd16d12a1757dce3a7800d0ab59c) in a testing branch. you may wish to apply it on master, or find another solution. @bao-qian

**Comment by bao-qian** [comment]
@jhdxr 
that should not be a problem now, the implementation has been changed. try the new version.
https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts

**Comment by jhdxr** [comment]
sure. I'll give it a go later. I'm also interested in the recent improvements.

**Comment by bao-qian** [comment]
issue fixed as confirm by @myy0222
close now.
let me know if it still have same problem

**Comment by toolgood** [comment]
这次事件的起因是我的ToolGood.Words类库，如果你只要拼音模块，如果你们不怕dll有点大，我可以保证，初始速度会提高很多。

**Comment by bao-qian** [comment]
@toolgood 
是只要拼音模块。
大会大多少呢？快会大概快多少？

**Comment by toolgood** [comment]
这个要等做出来才知道。。。。

**Comment by bao-qian** [comment]
@toolgood 
那就拭目以待了。C# 是没有一个好的拼音模块。

**Comment by jhdxr** [comment]
坦白来说我不认为集成那么一个dll进wox是好主意，实际上本地化上不仅是汉语需要这个的库，别的语言，比如日语（对应到罗马音）之类的也需要，如果把我们这些全部集成进去会非常大。最好能够按需安装（参考别的程序的语言包）

**Comment by toolgood** [comment]
ToolGood.Words.dll  .net 4 大小在550k   .net core 3.1 大小在 438K   初始速度在780ms
ToolGood.Words.Pinyin.dll .net 4 大小在2552K  .net core 3.1 大小在 588K 初始速度在330ms
如果不进行压缩，体积会变大5M，速度只会提高50ms左右

**Comment by bao-qian** [comment]
.net 4 的 2552K 和 .net core 的 588k 为何差四倍？是打错了？

**Comment by toolgood** [comment]
没打错，.net 4 采用的是gzip压缩，.net core 3.1采用的是br压缩。。。

**Comment by toolgood** [comment]
.net 4 和 .net core 2.1 都不支持br压缩，所以压缩不了

**Comment by toolgood** [comment]
再次优化了一下，初始速度在70ms左右。
下一个优化点是减少内存使用量，这个估计很难，因为内嵌的词典比较大有20000多个词组。

**Comment by RizhaoCai** [comment]
Same for the version 1.3.996. I am using a Laptop with 16G RAM and SSD. It should not be so stuck

同使用1.3.996版本，非常卡，卡爆了
