### ISSUE TITLE
fail to find uwp app

### ISSUE THREAD

**Issue by Fooughhy** [Wox-launcher/Wox#2969]
**Describe the bug**
I have a UWP app called "Microsoft Fjärrskrivbord" (Microsoft Remote Desktop as a direct translation) and it is still not showing up in the search results. 

![Hxss7C6JKp](https://user-images.githubusercontent.com/6977416/82408337-ab0aa080-9a6b-11ea-9cf5-2201063c19d1.jpg)
![YPjUydEkQ9](https://user-images.githubusercontent.com/6977416/82408346-afcf5480-9a6b-11ea-90d2-881da713b179.jpg)

**To Reproduce**
1. Install Wox 1.4.1115
2. Install "Microsoft Remote Desktop" UWP app
3. Search for the app using Wox

**Expected behavior**
It should find the app in Wox (ideally, without any additional configuration)

**Runtime info**
 - Windows 10 Version: Pro, build 18363 (Swedish localization)
 - Wox version: 1.4.1115

**Detailed logs**
[2020-05-20.txt](https://github.com/Wox-launcher/Wox/files/4654845/2020-05-20.txt)

**Comment by bao-qian** [comment]
Hi, 
thanks for report.
I can find it on my local machine.

could you try to update Microsoft Remote Desktop to latest version?


![image](https://user-images.githubusercontent.com/1169912/82434388-601d7700-9ac5-11ea-9ba8-cccb73d9e4bc.png)

**Comment by Fooughhy** [comment]
Hmm... As far as I'm aware, I have the latest version of it. Version 10.1.1215.0 is what I have.

I'm unable to find ANY UWP apps though (even though I don't have many installed). I have the UWP app "Windows Terminal" installed, but that isn't showing either.

And as I wrote in the OP, I'm using a swedish version of Windows 10 Pro. I use UELI before, which was able to identify the UWP apps. Which is why I think it's weird that this doesn't.

Have you made any changes to your install of Wox? Are you using Everything?

**Comment by bao-qian** [comment]
@Fooughhy 
could you try this new build
https://ci.appveyor.com/project/bao-qian/wox/builds/33003377/artifacts

if it still not fix, please let me know and upload latest log file.

**Comment by Fooughhy** [comment]
Still doesn't work. I'll use "Windows Terminal" as my check now, as that should be named the same regardless of the localization.

![bild](https://user-images.githubusercontent.com/6977416/82444965-50416b00-9aa4-11ea-9e14-da4cbf062d91.png)

[2020-05-20.txt](https://github.com/Wox-launcher/Wox/files/4656733/2020-05-20.txt)

**Comment by bao-qian** [comment]
from the log file, it seems like you installed thousands of programs.
init launch will be slow, since it need time to finish the indexing. (index performance will be improved in the future). after the index, `UWP index cost`/`Number of indexed uwps`/ `win32 index cost` will be appear in log entry.

could you restart wox, then wait a couple of minutes until index log entry appears, then start search and upload the latest log file?

**Comment by Fooughhy** [comment]
After 20 mins I only got the `UWP index cost` entry.


[2020-05-20.txt](https://github.com/Wox-launcher/Wox/files/4658235/2020-05-20.txt)

EDIT: These are my settings for the "Program" plugin.
![GbIKu7Q3WH](https://user-images.githubusercontent.com/6977416/82474686-b392c380-9acb-11ea-9d3a-3054c27c8e85.png)

**Comment by bao-qian** [comment]
@Fooughhy 
hi, there is no "UWP index cost" in your log file.

**Comment by Fooughhy** [comment]
Sorry, I meant Win32 index cost.

**Comment by bao-qian** [comment]
@Fooughhy 
did you check cpu usage and memory usage using task manager?
could you give a 5 minutes gif/video to show the cpu/memory usage after wox startup by using task manager?
are you using ssd or normal hard disk drive?

**Comment by Fooughhy** [comment]
I briefly checked it, and didn't see anything unusual but will make a proper check later. 

Here's the [video](https://doc-00-88-docs.googleusercontent.com/docs/securesc/rft5sec5u9regsh8oq00r4p7hqvo16ba/lo3cuhflbq480ptaj6e3jvusvk6850pn/1590036825000/07223987715443613485/07223987715443613485/1JM2DbHbiYSeCY1KbEtUu-GpKA-jQtfNC?authuser=0&nonce=ud5ka7qvo3tma&user=07223987715443613485&hash=0h58orqupsov13cqkpm82ahbk89h8f3r).

I clicked "Rebuild Index" and it has been going for probably 2 hours now though...

![Wox_6C29D6m99d](https://user-images.githubusercontent.com/6977416/82541588-fc409000-9b50-11ea-9c63-3aaffcc9ebe9.png)

**Comment by Fooughhy** [comment]
Does Wox go through `$PATH` variables? It says "Index Registry", but not sure exactly what that means. I'm using both scoop and chocolatey as "package managers" and they add ALOT to the path (such as `C:\Windows\system32`). Could this be the reason for the huge amounts of programs? (Also, that I include .ps1 and .psm1 files as suffixes?)

**Comment by jhdxr** [comment]
hi @Fooughhy  can you check if [this build](https://ci.appveyor.com/project/bao-qian/wox/build/artifacts) works for you?

**Comment by Fooughhy** [comment]
There we go! Works with that one. Thanks man!
