### ISSUE TITLE
feature request: rstrip math operators for convenient calculations

### ISSUE THREAD

**Issue by vovkkk** [Wox-launcher/Wox#297]
I really like calculator plugin, but if formula contains trailling math operator it prevents calculation, e.g. `5*3-2` outputs 13, but remove 2 `5*3-` doesn’t output anything, should be 15.

I’ve wrote Calculator in Python

``` python
# coding: utf8

from wox import Wox
import sympy


class Main(Wox):
    def query(self, key):
        results = []
        try:
            value = sympy.sympify(key.rstrip('*/+-'))
            results.append({
                "Title": str(value),
                "SubTitle": "Copy this number to the clipboard",
                "IcoPath": "calculator.png"
                })
        except:
            results.append({"Title": "error", "SubTitle": str(key)})
        return results

if __name__ == "__main__":
    Main()
```

Unfortunately, it is much slower (perhaps, because of sympy), also I don’t understand how to copy into clipboard from Python plugin (docs are really vague, and C# code of default plugin doesn’t help at all: `Clipboard.SetText(result.Result)`).

Also, to be completly honest, I for long time search something like Flashlight (plugin system for Spotlight), but for Windows Search (on Windows 8.1 or 10) — especially calculator — is it even possible?

**Comment by vovkkk** [comment]
Also, `2--3` doesn’t output anything, should be 5.

**Comment by bao-qian** [comment]
1. No, rstrip math operators won't be added. 
2. what do you mean by "copy into clipboard from Python plugin"
3. a better idea would be write a [wolframapha](http://www.wolframalpha.com/) plugin
