### ISSUE TITLE
[1.4.x] fail to find uwp app 

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#2975]
Wox version:1.4.1125
Win: Version 10.0.18363.836

After the upgrade, I failed to find any uwp app. here is a list of the keywords I tried:
* Netease Music: wyy/netease/网易
* Candy Crush Soda Saga: candy/soda
* Windows Terminal: terminal

I checked the log but it seems nothing wrong.
```
2020-05-20 21:55:04.9528|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <16ms>
2020-05-20 21:55:04.9528|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <1583>
2020-05-20 21:55:04.9528|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <62>

2020-05-20 21:55:25.4880|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <18529ms>
2020-05-20 21:56:54.0983|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <17347ms>

```

**Comment by jhdxr** [comment]
According to the comments from #2969 , since I cannot find any log entry `UWP index cost`, I guess my UWP apps haven't been indexed yet.

However, 
* I confirm I have clicked the re-index button and wait until the progress bar disappear.
* a log entry says `Number of preload uwps <62>` so I guess the index exists?

**Comment by bao-qian** [comment]
Number of preload * means cache.
that's a bit weird.
could you try running wox inside windows sandbox, check whether you can find edge (uwp) or not.

**Comment by bao-qian** [comment]
you installed 1000+ programs, so the index time is very long for win32 programs. I will try to improve this in the future.

given the info in your log, it mean uwp is indexing. restart wox, and leave it alone to see how long it takes to index all your uwp programs?

**Comment by jhdxr** [comment]
windows sandbox based on hyper-v, which conflicts with vmware, so I cannot test in that way.

it has been 2+ hours since this issue posted, I checked the log and there is still nothing related to UWP indexing. 
I doubt if there is something, e.g. an exception (although I cannot find one in the log neither), which blocks the indexer for UWP?

**Comment by bao-qian** [comment]
@jhdxr 
I think you can also test with vmware, sandbox is just one of the option.
did you check cpu usage and memory usage using task manager?
could you give a 5 minutes gif/video to show the cpu/memory usage after wox startup by using task manager?
are you using ssd or normal hard disk drive?

**Comment by jhdxr** [comment]
> are you using ssd or noraml hard disk drive?

both. but for OS it's on SSD.
