### ISSUE TITLE
Python 插件 query 中文字符串的问题

### ISSUE THREAD

**Issue by Jecvay** [Wox-launcher/Wox#298]
版本: 1.2.0 beta

我在写插件的时候, 发现如果输入<=3个的汉字的时候, 下面这个 query 会显示出乱码; 大于3个汉字的时候, 显示正常. 求解.

```
def query(self,query):
    if not query:
        return ""

    results = []
    results.append({
        "Title": "中文",
        "SubTitle":query,   # 此处有问题
    })
    return results
```

**Comment by Jecvay** [comment]
问题应该是处在 pythonhome 目录下的 wox.py 文件里面的 chardet 库

```
D:\Program Files (x86)\wox1.2beta\PythonHome>python.exe
Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500
32
Type "help", "copyright", "credits" or "license" for more
>>> import chardet
>>> chardet.detect("哈哈")['encoding']
'windows-1252'
>>> chardet.detect("哈")['encoding']
'windows-1252'
>>> chardet.detect("哈哈哈哈")['encoding']
'EUC-JP'
>>> chardet.detect("哈哈哈哈我也是醉了")['encoding']
'GB2312'
>>>
```

**Comment by bao-qian** [comment]
就是那破玩意的问题
升成 py3，然后用新的文件：https://github.com/Wox-launcher/Wox/blob/master/JsonRPC/wox.py
你电脑装了 py 后，添加到 `%PATH%`
然后装新版 https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898

**Comment by ev01ing** [comment]
是这样的，win的默认编码时gbk(我的电脑是)，然而wox.py中的默认编码是utf-8，wox类中的init的第一句json.loads(sys.argv[1])时解码时用的utf-8。如果是中文，这里会报错无法解码，可以查看日志发现此问题。

解决办法：将wox.py中的init的第一句json.loads(sys.argv[1])改为json.loads(sys.argv[1].decode("gbk"))即可解决，另外，query函数返回的值中的所有字符串前面也要加u，这样就没有问题了。

如果有问题请后续反馈，谢谢。
