### ISSUE TITLE
wox open file/folder thorught specific program

### ISSUE THREAD

**Issue by GitFlzy** [Wox-launcher/Wox#2981]
我想在 wox 里输入 “vsc github” 达到『用 vscode 打开 github 文件夹』的效果。

我现在的做法是在 _设置 -> 插件 -> 程序_ 里面增加一个目录索引，然后在索引的目录里通过快捷方式来实现，但这样有点麻烦，我得打开各种文件夹，复制地址制作链接路径，命名快捷方式。

wox 是否有更便捷的设置方式？如果有，我需要怎么设置？如果没有，这项功能的设置能不能加入，毕竟自己设置有点麻烦。

**Comment by bao-qian** [comment]
currently, no.
we will implement all right click context menu in the future.

**Comment by enria** [comment]
其实我觉得你目前使用的方法就挺好的。一个相对来说便捷一点的方法是你使用vscode打开文件夹后，可以将环境保存成一个workspace文件，比如说是是`github.code-workspace`，这样可以使用 everything 的索引，输入`code github`来搜索并打开这个文件，也就打开这个workspace。
想要Wox给你提供这样的功能，我觉得你也需要做一些配置，比如说`vsc`代表vscode这个程序，`github`是代表你电脑上的哪个文件夹，整体下来也不会变得更加便捷，而且这个功能也没有什么通用性。
我看过应该是Alfred上面有这样的插件，比如说输入`vsc`，就会列出你的vscode的历史，这样选择工程或者文件夹就可以了。实现这个插件也很简单，就看有没有人想做了。
