### ISSUE TITLE
拼音模块bug

### ISSUE THREAD

**Issue by taooceros** [Wox-launcher/Wox#2982]
**Is your feature request related to a problem? Please describe.**
可以设置程序插件的优先级在everything之上吗，因为有些时候有些程序的索引被排在很多包含搜索词的文件或者文件夹下面了，如果单纯置顶容易卡顿

**Describe the solution you'd like**
设置插件优先级，让程序插件优先于everything的文件和文件夹排在搜索结果

**Additional context**
像我如果用“微信”来搜索微信的时候，默认会优先将everything搜索到的文件夹放在搜索的置顶，而不是这个程序 （不知道为什么微信这个程序拼音并不奏效，在之前的版本中是可以用wechat来搜索到微信的，但在最新的prerelease似乎修改了这个逻辑）
![image](https://user-images.githubusercontent.com/45326534/82534946-ac75bf00-9b78-11ea-8e95-bea83b32e7c0.png)

**Comment by taooceros** [comment]
似乎并不是优先级的问题，而是因为“程序”插件在索引中文并采用拼音模块的时候，会有一些问题，似乎没有办法用全拼，只能用首字母，而且在遇到多音字的时候会无法识别

**Comment by bao-qian** [comment]
对，目前只支持首字母。

**Comment by taooceros** [comment]
那关于多音字的问题有无修改的打算

**Comment by taooceros** [comment]
如“行”在我搜索的时候就没办法用x来代表

**Comment by bao-qian** [comment]
多音字下个版本会改进。这个版本为了性能暂时放弃一些功能。

> 如“行”在我搜索的时候就没办法用x来代表

没看懂你这个问题。

**Comment by taooceros** [comment]
这个是举了个多音字的例子，我一不小心发快了……就有comment了一次🥱
谢谢了

**Comment by bao-qian** [comment]
首字母多音字现在是支持的。比如音乐的拼音首字母是yy而不是yl。
全拼的多音字下个版本会加上。

**Comment by taooceros** [comment]
但我在搜索”天行“的时候tx就不行只能用th

**Comment by bao-qian** [comment]
@taooceros 
这是词库的支持不全。你可以列一下，我会向词库作者反馈。

**Comment by taooceros** [comment]
目前我所知道的只有行这个字在“天行”中只能用h（th）表示，而不能用x（tx）
其实我觉得多音字的情况下可能保留所有的可能（如行就x和h都可以表示）会更好一点，不过感觉这个需求其实没这么大，如果是为了性能考虑倒也不必改。
感谢
