### ISSUE TITLE
Error v v1.4.1129

### ISSUE THREAD

**Issue by hamerstandr** [Wox-launcher/Wox#2984]
Click in icon to tray icon > show menu
DoubleClick in icon to tray icon > show menu + Exit

**Comment by bao-qian** [comment]
could you give upload gif to show the isse?

**Comment by hamerstandr** [comment]
![Record_2020_05_22_01_40_53_914](https://user-images.githubusercontent.com/16276736/82607334-ddccaa00-9bcd-11ea-88ed-a5d4ea6a2cfa.gif)

**Comment by hamerstandr** [comment]
> could you give upload gif to show the isse?

![Record_2020_05_22_01_40_53_914](https://user-images.githubusercontent.com/16276736/82607334-ddccaa00-9bcd-11ea-88ed-a5d4ea6a2cfa.gif)

**Comment by hamerstandr** [comment]
wox>mainwindow.xaml.cs>InitializeNotifyIcon()
delete
_notifyIcon.MouseClick += (o, e) =>
            {
                if (e.Button == MouseButtons.Left)
                {
                    if (menu.Visible)
                    {
                        menu.Close();
                    }
                    else
                    {
                        var p = System.Windows.Forms.Cursor.Position;
                        menu.Show(p);
                    }
                }
            };
