### ISSUE TITLE
Wox don't start

### ISSUE THREAD

**Issue by BrenoTeodor-o** [Wox-launcher/Wox#2985]
[2020-05-21.txt](https://github.com/Wox-launcher/Wox/files/4662443/2020-05-21.txt)

Exception begin --------------------
  System.NullReferenceException: Object reference not set to an instance of an object.
  HResult: -2147467261
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: Wox
  TargetAssembly: Wox, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null
  TargetModule: Wox.exe
  TargetSite: Void OnSecondAppStarted(System.Collections.Generic.IList`1[System.String])
  StackTrace: --------------------
   at Wox.App.OnSecondAppStarted(IList`1 args) in C:\projects\wox\Wox\App.xaml.cs:line 181
   at Wox.Helper.SingleInstance`1.ActivateFirstInstanceCallback(Object arg) in C:\projects\wox\Wox\Helper\SingleInstance.cs:line 418
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Wox.exe" 
* Timestamp: 05/21/2020 09:34:27
* Wox version: 1.3.1073
* OS Version: Microsoft Windows NT 10.0.18363.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0
   * v4.8

## SDK Info
* Python Path: pythonw.exe
* Everything SDK Path: 

## Assemblies - Wox.exe

* Wox, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Wox.exe)
* Wox.Core, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\NLog.dll)
* Wox.Plugin, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Mindscape.Raygun4Net.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\NuGet.Squirrel.dll)
* HelloWorldCSharp, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.ControlPanel, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.PluginManagement, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.BrowserBookmark, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.Everything, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Color, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.Caculator, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Wox.Plugin.Folder, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.Program, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Sys, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.Shell, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.WebSearch, Version=1.3.1073.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\WindowsInput.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\NHotkey.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* SQLitePCLRaw.batteries_v2, Version=2.0.2.669, Culture=neutral, PublicKeyToken=8226ea5df37bcae9 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.batteries_v2.dll)
* SQLitePCLRaw.core, Version=2.0.2.669, Culture=neutral, PublicKeyToken=1488e028ca7ab535 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.core.dll)
* SQLitePCLRaw.provider.dynamic_cdecl, Version=2.0.2.669, Culture=neutral, PublicKeyToken=b68184102cba0b3b (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.provider.dynamic_cdecl.dll)
* System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\System.Memory.dll)
* SQLitePCLRaw.nativelibrary, Version=2.0.2.669, Culture=neutral, PublicKeyToken=502ed628492ab262 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\SQLitePCLRaw.nativelibrary.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\NHotkey.Wpf.dll)
* System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\Plugins\Wox.Plugin.BrowserBookmark\System.Runtime.CompilerServices.Unsafe.dll)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\teodo\AppData\Local\Wox\app-1.3.1073\CommandLine.dll)
* Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll)
* System.ValueTuple, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
