### ISSUE TITLE
新版不能输入首字母缩写来检索程序了

### ISSUE THREAD

**Issue by DilrabaLuv** [Wox-launcher/Wox#2986]
以前可以直接用首字母来查询系统自带程序，比如输入iis可以搜到Internet Information Service， 输入rdc可以搜到RemoteAPP和桌面连接。
但是现在必须要输入完整的单词，internet，或者remote等等。
![微信图片_20200521222834](https://user-images.githubusercontent.com/10212292/82570003-976a5180-9bb3-11ea-963e-b9aff610988a.jpg)

另外,现在检索程序的速度比以前慢很多。

**Comment by bao-qian** [comment]
for search ability using first char, it will be add back in next stable release.
for search speed, 
1 please give wox version.
2 do you mean startup time, or do you query after 5 minutes starup?

**Comment by DilrabaLuv** [comment]
> for search ability using first char, it will be add back in next stable release.
> for search speed,
> 1 please give wox version.
> 2 do you mean startup time, or do you query after 5 minutes starup?

1. v1.4.1129
2. after 5 minutes startup

**Comment by bao-qian** [comment]
try new release
https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196

**Comment by bao-qian** [comment]
let me know if it fix or not
