### ISSUE TITLE
两条建议

### ISSUE THREAD

**Issue by iftodo** [Wox-launcher/Wox#299]
1, 程序索引文件后缀不应该也没有必要区分大小写.. 比如putty的后缀就是EXE, 而不是exe.   如果区分大小写的话, 就要添加两种.

2, 程序的当前目录貌似默认是"C:\Users\Administrator\"这种的, 难道不应该是启动的程序所在目录吗?  这样某些程序会报错的, 比如梦幻西游这个游戏.  或许有配置能实现, 但这个问题我是真心没找到在哪可以配置.

**Comment by bao-qian** [comment]
1. 没看懂你2说的啥。如果报错的话请参照[faq](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87)提供更详细的信息。

**Comment by qianlifeng** [comment]
他的意思Wox的working directory设置的不对

**Comment by happlebao** [comment]
close due to no response, reopen it if you have more info.

**Comment by bao-qian** [comment]
因为没有进一步反馈，所以关闭这个 issue，有更多信息的话请重开。
working directory 用 #360 来追踪。
