### ISSUE TITLE
Wox doesn't respond in 2004

### ISSUE THREAD

**Issue by gingerbreap** [Wox-launcher/Wox#2991]
**Describe the bug**
Wox just doesn't work from time to time

**To Reproduce**
1. Start Wox
2. Type anything
3. Wox doesn't respond to the entry
4. Hide wox using ESC
    (Meantime opening plugin settings see no thumbnails of the installed plugins)
5. Wait for couple minutes and the error window appears.

**Expected behavior**

**Runtime info**
 - Windows 10 Version: 2004, build 19608.1006
 - Wox version: 1.3.1039

**Wox Error Window text**
Exception begin --------------------
  System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  HResult: -2146232800
  Data: <System.Object> -> <>
  Data: <AlreadySentByRaygun> -> <True>
  Source: System
  TargetAssembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  TargetModule: System.dll
  TargetSite: System.IAsyncResult BeginRead(Byte[], Int32, Int32, System.AsyncCallback, System.Object)
  StackTrace: --------------------
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.FixedSizeReader.StartReading()
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.TlsStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.ConnectStream.BeginReadWithoutValidation(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.StreamReader.<ReadToEndAsyncInternal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Infrastructure.Http.Http.<Get>d__9.MoveNext() in C:\projects\wox\Wox.Infrastructure\Http\Http.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<GitHubUpdateManager>d__7.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.Core.Updater.<UpdateApp>d__5.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wox.ViewModel.SettingWindowViewModel.<UpdateApp>d__7.MoveNext() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  InnerException 1: ------------------------------------------------------------
    System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
    HResult: -2147467259
    Source: System
    TargetAssembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
    TargetModule: System.dll
    TargetSite: System.IAsyncResult BeginReceive(Byte[], Int32, Int32, System.Net.Sockets.SocketFlags, System.AsyncCallback, System.Object)
    StackTrace: --------------------
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Wox.exe" 
* Timestamp: 05/22/2020 22:03:26
* Wox version: 1.3.1039
* OS Version: Microsoft Windows NT 10.0.19608.0
* x64: True
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.04161
   * v4 Full 4.8.04161
   * v4.0 Client 4.0.0.0

## SDK Info
* Python Path: C:\Program Files\Python38\pythonw.exe
* Everything SDK Path: C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Wox.exe)
* Wox.Core, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Wox.Core.dll)
* Wox.Infrastructure, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Pinyin4Net.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\NLog.dll)
* Wox.Plugin, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Newtonsoft.Json.dll)
* Mindscape.Raygun4Net4, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net4.dll)
* Mindscape.Raygun4Net, Version=5.10.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Mindscape.Raygun4Net.dll)
* Wox.Plugin.ControlPanel, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Program, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Caculator, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Wox.Plugin.Color, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Url, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.Everything, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.WebSearch, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* Wox.Plugin.IPAddress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Roaming\Wox\Plugins\IP Address-c18a1384-0c17-45ca-b59f-cc99a77667d5\Wox.Plugin.IPAddress.dll)
* Wox.Plugin.Folder, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* RemoveUSB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Roaming\Wox\Plugins\Remove USB-b9f5a399-eac7-4b06-b1d6-3354fac324c2\RemoveUSB.dll)
* WoxSteam, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Roaming\Wox\Plugins\Steam-a174b2ea-9ab9-440a-b321-1e7bbf7e1eb6\WoxSteam.dll)
* Wox.Plugin.ProcessKiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Roaming\Wox\Plugins\Wox.Plugin.ProcessKiller-cca7ad85-1bdf-4c8a-b1b1-d1bbd5f6278a\Wox.Plugin.ProcessKiller.dll)
* Wox.Plugin.Sys, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.BrowserBookmark, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.PluginManagement, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.PluginIndicator, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* HelloWorldCSharp, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.Shell, Version=1.3.1039.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\WindowsInput.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\NHotkey.Wpf.dll)
* Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\peter\AppData\Roaming\Wox\Plugins\Steam-a174b2ea-9ab9-440a-b321-1e7bbf7e1eb6\Newtonsoft.Json.dll)
* NeXt.Vdf, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Roaming\Wox\Plugins\Steam-a174b2ea-9ab9-440a-b321-1e7bbf7e1eb6\NeXt.Vdf.dll)
* Windows.ApplicationModel, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.ApplicationModel.winmd)
* Windows.Management, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Management.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* Windows.Storage, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Storage.winmd)
* Microsoft.WindowsAPICodePack.Shell, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Microsoft.WindowsAPICodePack.Shell.dll)
* Microsoft.WindowsAPICodePack, Version=1.1.4.0, Culture=neutral, PublicKeyToken=8985beaab7ea3f04 (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Microsoft.WindowsAPICodePack.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Squirrel.dll)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\CommandLine.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\peter\AppData\Local\Wox\app-1.3.1039\NuGet.Squirrel.dll)
* Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
* Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
* Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
* System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)

**Screenshots**
_ Some Frames were deleted to reduce the size_ 
![1](https://user-images.githubusercontent.com/27958821/82676858-a4ea0f00-9c79-11ea-89bf-f7b171c14740.gif)

**Detailed logs**
[2020-05-22.txt](https://github.com/Wox-launcher/Wox/files/4668477/2020-05-22.txt)

**Comment by ousugo** [comment]
Try to update to latest version V1.4.1129.

**Comment by gingerbreap** [comment]
> Try to update to latest version V1.4.1129.

It worked. Thanks
