### ISSUE TITLE
Throw a exception when loading everything plugin

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#30]
in this place:
\wox\Wox\PluginLoader\CSharpPluginLoader.cs line 23
Assembly asm = Assembly.LoadFile(metadata.ExecuteFilePath);

“System.BadImageFormatException”类型的未经处理的异常出现在 Wox.exe 中。

其他信息: 未能加载文件或程序集“Wox.Plugin.Everything, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。试图加载格式不正确的程序。

**Comment by qianlifeng** [comment]
I have made some changes in the CSharp plugin loader today. Please pull the latest codes to see if this error still exists. Thx.

**Comment by aihuasxy** [comment]
now error is
“托管调试助手“LoaderLock”在“D:\src\wox\Wox\bin\Debug\Wox.vshost.exe”中检测到故障。
其他信息: 正试图在 OS 加载程序锁内执行托管代码。不要尝试在 DllMain 或映像初始化函数内运行托管代码，这样做会导致应用程序挂起。”

at line 79 in runtime.cs
        Runtime.PyEval_InitThreads();

**Comment by qianlifeng** [comment]
Strange, I didn't have this error. You can refer to this [article](http://www.cnblogs.com/lcxu2/archive/2011/01/16/2004016.html) as a workaround.

**Comment by aihuasxy** [comment]
Thx，this problem is resolved according to you suggestion.
But another erros is much harder do fix.
////////

## error info :

## Microsoft Visual C++ Runtime Library

Runtime Error!

Program: d:\src\wox\Wox\bin\Debug\Wox.exe

R6034

An application has made an attempt to load the C runtime library incorrectly.
Please contact the application's support team for more information.
///////////

google but didn't find the key. according to this article(http://www.cppblog.com/deercoder/articles/101006.html ), i guess it may be related to manifest. In previous version i don't have this error.

ps:have pulled the latest version,everything issue is still not resolved :(

**Comment by orzFly** [comment]
There may be something wrong with your compuiler. Can you figure out which
configuration  you are using to build and tell is something about your
system?
- Windows version & arch
- Compiler version
- Build configuration and platform

**Comment by aihuasxy** [comment]
- Windows version & arch
  // Win7 32
- Compiler version
  // VS2010
- Build configuration and platform
  // how?

**Comment by aihuasxy** [comment]
R6034 issue have been resolved .

The python27.dll must be embeded the manifest file using md.exe according to http://blog.sina.com.cn/s/blog_4fe713c70100vqlq.html.

**Comment by qianlifeng** [comment]
Good job @aihuasxy . But why this could happen in specified environment? In my environment, I didn't see this error before. Is there anything we can do to prevent this kind of issues instead of adding manifest file into python27.dll in user's machine.

**Comment by aihuasxy** [comment]
In user's machine may it's no need to do this job, because R6034 is only in DEBUG version.
Maybe due to the lack of "Microsoft.VC90.DebugCRT" information in the manifest of python**.dll.

Although the R6034 is not show again , python environment is not Initialized sucessfully.

LOG  "Could't find python environment, all python plugins disabled."

why?

could you send me these file in your machine?
python.dll and the fold Microsoft.VC90.CRT including msc*.dll.

**Comment by qianlifeng** [comment]
> Could't find python environment, all python plugins disabled.

This is caused by calling `PythonEngine.Initialize();` failed. Maybe pythonnet couldn't find your python27.dll or there are errors when invoking python27.dll.
I'm using x64 system, which may not works in x86. Maybe you can try to reinstall x86 python on  your machine.

**Comment by aihuasxy** [comment]
IronPython or CPython？

**Comment by qianlifeng** [comment]
CPython

**Comment by aihuasxy** [comment]
It doesn't work.
Finally I resolvered R6034 by compiling the python27 using vs2010.

The reason i guss is that python installed before is compiled by vs2008.

Did u use the python from the official web?

**Comment by qianlifeng** [comment]
Yes. I'm using the official 2.7 package. Pythonnet seems doesn't support python 3+. Maybe Wox should including a portable python 2.7 like sublime text in the future.

**Comment by aihuasxy** [comment]
has anyone else  use python plugin sucessfully in win7 32 ?

**Comment by qianlifeng** [comment]
Yes, A friend of mine uses win7 x86 system. At first, he installed python33, but wox python plugin didn't work. Then he uninstall the python33 and install python27. Everything is fine.

**Comment by aihuasxy** [comment]
In 1.0 beta release the everything plugin has been loaded successfully.
This issue should be closed.
