### ISSUE TITLE
Meta: appoint core devs, possibly move to a GitHub organization

### ISSUE THREAD

**Issue by deltaidea** [Wox-launcher/Wox#300]
The main issue right now, in my perspective, is that the development is pretty slow. I mean, the last commit on the dev branch was 27 days ago. There're open PRs from July 2014.

I understand that it might not be possible for @qianlifeng to actively check PRs and merge them, let alone write code at the speed of a full-time programmer. That's totally OK. In fact, I want to thank @qianlifeng for his (her? — unlikely) awesome job of keeping this project alive and hosting its infrastructure.

What I propose is:
- Add more core developers, aka choose at least one more person and give him commit access.
- Optionally, move the project to a separate organization, like github.com/getwox/wox.

Of course, first, there should be a discussion on project values and development direction to avoid incidents between core devs, and second, and even more obvious, the core devs should be chosen.

What do you think?

**Comment by qianlifeng** [comment]
Thx deltaidea, I have to admit that the development is slow now. My main focus now is not on Wox. 
I would very happy to move the Wox project to separate organization, but the problem is that I didn't find proper core developers that would like to continuing to contribute to Wox.

**Comment by bao-qian** [comment]
Hi @qianlifeng, I nominate myself as one of developers.
Please check the email I sent to you.

**Comment by qianlifeng** [comment]
@happlebao Thx, I will contact you
