### ISSUE TITLE
Keyword Highlight Suggestion

### ISSUE THREAD

**Issue by ousugo** [Wox-launcher/Wox#3005]
![image](https://user-images.githubusercontent.com/43401755/82718495-64b87a00-9cd5-11ea-9052-0ca5e94da86d.png)
Version:1.4.1129

In this version, as we can see in the picture above, the keyword "we" what user input in the app list aren't highlight, and the rest of application name are  highlight.

I think this is counter-intuitive and litter misleading. "we" should be highlight instead of other words.

**Comment by jhdxr** [comment]
高亮是针对结果项的，也就是说下面那个列表，而不是你的query

**Comment by ousugo** [comment]
> 高亮是针对结果项的，也就是说下面那个列表，而不是你的query

可能是我没表述清楚，我这里所指的高亮就是说的 Query 的高亮，比如 ”POWERPOINT“ 这一字符串里面，现在高亮的就是除了"WE"以外的其他字符。
![image](https://user-images.githubusercontent.com/43401755/82769929-38356700-9e69-11ea-931c-26e068759218.png)

**Comment by jhdxr** [comment]
hmm，可能UI让你造成了误解，这其中的灰色才是高亮的字体。。。

**Comment by ousugo** [comment]
我的意思就是这个主题下，两者的颜色对调一下是不是效果更好一点😂

**Comment by bao-qian** [comment]
这个是个 ui bug，之后会改。
