### ISSUE TITLE
Uselessly bad indexing?

### ISSUE THREAD

**Issue by lietu** [Wox-launcher/Wox#3013]
**Describe the bug**
The indexing for Wox or Everything seems to be using some algorithm that gives uselessly bad results. As it is I see this tool as a complete waste of time for me.

**To Reproduce**
1. Install Wox
2. Hit hotkey, write in `test`
3. See random results, none of which even vaguely reference `test`

**Expected behavior**
Results are somehow related to search

**Runtime info**
 - Windows 10 Version: 1909 / 18363.778
 - Wox version: 1.3.524

**Screenshots**
![image (12)](https://user-images.githubusercontent.com/1296558/82800800-f6b2b500-9e84-11ea-8f88-8fe7be511d40.png)

vs start menu

![image](https://user-images.githubusercontent.com/1296558/82800896-1f3aaf00-9e85-11ea-8bed-59c772631549.png)

**Comment by lietu** [comment]
Also I'd like to correct this record and say I did not assign anyone to this, some GitHub automation did.

**Comment by cpkio** [comment]
Why not use latest Wox for testing? I installed Everything separately, tweaked its settings (there could be some filters set by default), and ES search in Wox is working fine (Wox does nothing else than filtering the strings).

**Comment by lietu** [comment]
Why would I use anything but the stable release for testing? "Tweaked its settings" is an undocumented step that I know nothing about.

**Comment by bao-qian** [comment]
this has been fixed in new release, and I will release stable version soon.
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
