### ISSUE TITLE
 bug report

### ISSUE THREAD

**Issue by Alphabet1226** [Wox-launcher/Wox#3031]
**Describe the bug**
从微软应用商店下载的QQ32位转制版，搜索时即使已经选择将其置顶，并且也确实已经置顶到了搜索结果的第一行，但每次还是会把光标定位在“存储空间”上。

**Expected behavior**
希望能解决这个bug

**Runtime info**
 - Windows 10 Version: win10ltsc
 - Wox version：1.4.11.29

**Screenshots**
![image.png](https://i.loli.net/2020/05/26/hH9upngY1Tvdxq7.png)

**Comment by bao-qian** [comment]
move your mouse out of the wox window, then it will choose the first result.

**Comment by Alphabet1226** [comment]
> move your mouse out of the wox window, then it will choose the first result.

这是错误的，经过我的尝试表明，不管鼠标在任何地方，都会出现这种情况。
![截图_2020052620581358SS.gif](https://i.loli.net/2020/05/26/K5MVYS9HeFdZjNI.gif)
