### ISSUE TITLE
Cannot set Caret Color for TextBox

### ISSUE THREAD

**Issue by gblazex** [Wox-launcher/Wox#304]
Error I get: _Cannot find the Style Property 'CaretBrush' on the type 'System.Windows.Controls.TextBox'._

```
<Style x:Key="QueryBoxStyle" 
       BasedOn="{StaticResource BaseQueryBoxStyle}" 
       TargetType="{x:Type TextBox}">

    <Setter Property="CaretBrush">
        <Setter.Value><SolidColorBrush Color="Red"/></Setter.Value>
    </Setter>

    ...

</Style>
```

Any idea why?

**Comment by lances101** [comment]
CaretBrush was introduced in .net 4.0, Wox is currently on 3.5, so this property is not supported.

**Comment by bao-qian** [comment]
hi @galambalazs, Wox is target .net 4.5.2 now, try [latest build](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-install-latest-build).
