### ISSUE TITLE
Placeholder text for TextBox

### ISSUE THREAD

**Issue by gblazex** [Wox-launcher/Wox#305]
Is it possible to set from a Theme or otherwise?

**Comment by qianlifeng** [comment]
what's the use case that we need this placeholder for textbox?

**Comment by gblazex** [comment]
I was just thinking there could be separate shortcuts for 
e.g. App Launching vs Web Search (or other types).

And then the TextBox could show which type of Search you triggered (some visual feedback).

**Comment by bao-qian** [comment]
@galambalazs why plugin icon can't satisfy this requirement?
![icon](http://i.imgur.com/BuxJuOE.png)
reopen issue if I misunderstand your requirements.
