### ISSUE TITLE
Searches launch Chrome, not Firefox

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#3050]
Hi,

I'm running the latest version of Wox on Windows 10. When I search using Wox (via the g or d command) Chrome is always launched even though Firefox is set as my default browser in Windows. Did I miss a setting somewhere?

Thanks!

**Comment by Bonjur** [comment]
edit the plugin code

**Comment by fdawans** [comment]
I ran into the same issue. I put firefox.exe in the plugin settings (in Wox GUI) but it does not work.
Where should the code be edited? 
Thanks!

**Comment by SilverThunderbird** [comment]
I have the same issue. Firefox is the default browser, but when it says "Open URL: xxxxx.com", it uses Chrome. Specified firefox.exe in Wox, but no luck.

**Comment by fdawans** [comment]
I moved to the fork (Flow Launcher) in the end.
[link](https://github.com/Flow-Launcher/Flow.Launcher)

**Comment by SilverThunderbird** [comment]
I gave up and am now trying "Executor".

**Comment by Xx-KaixX** [comment]
It was quite easy for me to fix. All I had to do was uninstall chrome.

**Comment by AdilHussain7** [comment]
Remeber to try restarting wox after you've changed the browser location in plugin. That worked out for me. to restart just enter restart wox in the wox search bar
