### ISSUE TITLE
Cannot find programs installed in E:\ drive 

### ISSUE THREAD

**Issue by red9350** [Wox-launcher/Wox#3053]
Even after forced indexing in the Programs plugin, i cannot find any of the programs installed in the E:\ drive.

**Runtime info**
 - Windows 10 Version: 1903
 - Wox version 1.3.1073

**Screenshots**
![image](https://user-images.githubusercontent.com/16651290/83810110-e4701c80-a6b7-11ea-8986-0c223c337b44.png)

![image](https://user-images.githubusercontent.com/16651290/83810231-141f2480-a6b8-11ea-999c-6175e5384d73.png)

![image](https://user-images.githubusercontent.com/16651290/83810248-200ae680-a6b8-11ea-93dc-7393e97072aa.png)

**Detailed logs**
[2020-06-04.txt](https://github.com/Wox-launcher/Wox/files/4732702/2020-06-04.txt)

**Comment by red9350** [comment]
I fixed it by manually deleting the configured locations from AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Program\Settings.json, then adding just the Program Files and Program Files (x86) directories for each drive, waiting for the indexing to finish after each add

**Comment by akimonlet** [comment]
Same problem here, seems like the last version doesn't index when you put only the drive root in location (like "E:")
As soon as I add a folder like "E:/Blender" It find the .exe with no problem

![2020-06-09_171559_NVIDIA_GeForce_Overlay](https://user-images.githubusercontent.com/66687014/84166290-ff0a1300-aa74-11ea-83f7-efe031df62c6.png)
![2020-06-09_171626_NVIDIA_GeForce_Overlay](https://user-images.githubusercontent.com/66687014/84166301-029d9a00-aa75-11ea-977b-bb45e4599555.png)

**Comment by algo-rocks** [comment]
I am having the same issue in Wox search. I think if you manually add the folder as the previous posters mention, and if you ALSO use the EVERYTHING SEARCH GUI Interface, EVERYTHING will show duplicated search results.
