### ISSUE TITLE
Can't find an app

### ISSUE THREAD

**Issue by rominatrix** [Wox-launcher/Wox#3055]
I am used to Launchy at my work computer but someone mentioned Wox in a forum and I installed it and liked it immediately so I want to migrate from Launchy to Wox for both my work computer and my personal one. I use Windows 10. 

One of the applications I use the most is "git bash" which I have installed in: C:\Program Files\Git\bin\bash.exe   This software is also available from the start menu via a .lnk archive. In Launchy I just alt+space and type bash, press enter and I can open the software quickly. However I have not been able to do this. 

"everything.exe" is running (also as a service) and I have reset Wox multiple times. I tried different settings from both programs but I only get to see folders, but not the application itself. Another thing I get is first some folders from c:\windows\WinSxS\....\ (something that has the word bash in it).

I've tried also running Wox as administrator to no avail. I can't even type "chrome" and get chrome's executable, I only see folders. I don't know if I'm missing something, but I understood it was mostly straightforward. I hope you can help me out.

**Runtime info**
 - Windows 10 Version: Windows 10 Home Single Language
 - Wox version: latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/11646466/83929237-0a092e80-a769-11ea-86b5-6c6cd8a9158b.png)

**Detailed logs**
[2020-06-05.txt](https://github.com/Wox-launcher/Wox/files/4738909/2020-06-05.txt)

**Comment by WangJincheng4869** [comment]
我更新到1196也出现了相同的问题，回退578后解决

**Comment by andremueller** [comment]
The `Program` plugin of the pre-release v1.4.1196 has this problem. It just cannot find most of the apps appearing in the Windows start menu. However, after I switched back to version 1.4.1129 the `Program` plugin works fine and finds its apps. So probably that optimization step introduced a bug.
