### ISSUE TITLE
全屏游戏的时候好像会弹出

### ISSUE THREAD

**Issue by Singularity-zju** [Wox-launcher/Wox#31]
因为挺好用的自己clone了一份编译了一下，发现有时候全屏玩游戏的时候会自己弹出来，好像是Wox的原因，可能的话排查下是否有这个问题？

**Comment by qianlifeng** [comment]
是不是你在全屏游戏的时候不经意按了启动WOX的快捷键？

**Comment by Singularity-zju** [comment]
我晚上又测试了一下，用的英雄联盟，应该是没有按到快捷键的。 大约隔个十来分钟会弹出来。

**Comment by qianlifeng** [comment]
如果你已经拿的最新的代码，可以试着注释Wox/MainWindow.xaml.cs里面的WakeupApp方法。但是感觉不应该是这边的错误。

**Comment by Singularity-zju** [comment]
嗯，注释掉以后确实不跳出了。

**Comment by qianlifeng** [comment]
已经在main branch上面移除相关代码，谢谢反馈。
