### ISSUE TITLE
Win 10: Cannot bind Wox hotkey using the Windows key

### ISSUE THREAD

**Issue by cheapsteak** [Wox-launcher/Wox#310]
Upgraded from Win7 to Win10, had Wox hotkey bound to Win+Z, results in alert on boot saying unable to bind Win+Z  

In Wox's settings, the hotkey input box does not recognize when the windows key is pressed

edit: also not registering: Function keys, Home, End, Delete, Page up, Page down, and any numpad keys

edit2: also not registering: any punctuation keys (, . / ; ' [ ] \ - =)

**Comment by qianlifeng** [comment]
Maybe some other program has bind to <kbd>Win</kbd>+<kbd>Z</kbd>, which causes wox can't bind again. 

Hotkey binding has some limitations in the prev release, @Leon99 has committed a [pull request](https://github.com/qianlifeng/Wox/pull/288) to fix this issue.

**Comment by koobs** [comment]
Confirming on a fresh Wox installation on Windows 7, attempting to bind Win-Space, which appears to already be bound to "Aero Peek" (Show Desktop) functionality.

At a minimum, attempting to bind a key that's already bound should result in an error message in the hotkey settings window "<hotkey> is already bound" or equivalent

**Comment by bao-qian** [comment]
@cheapsteak @koobs 
try new version

https://ci.appveyor.com/project/happlebao/wox/build/1.3.114/artifacts
