### ISSUE TITLE
sometimes my wox only show me a line, not the input box

### ISSUE THREAD

**Issue by guoguoaidaogu** [Wox-launcher/Wox#3105]
**Describe the bug**
When I close up my laptop and launch it on, my Wox will only show me a line, not the input box.
Maybe the width of the input box become 1px.

**To Reproduce**
1. close up the laptop.
2. relaunch the laptop.
3. see error.

**Runtime info**
 -Windows 10 Version: 1903 18362.900
 -Wox version: 1.3.524

**Wox Error Window text**
My Wox does not show the error window....

**Screenshots**
Sorry I haven't got any screeshots.

**Additional context**
Oh this is my first time to submit a issue on GitHub.
Sorry for my bad english : (

**Comment by gorcig** [comment]
I am experiencing the same issue. Could it be related putting notebook on docking station? A tried to replicate putting notebook in Hibernate while on docking station and it worked all the time. Now working directly on notebook (put previously in hibernate) it doesn't show standard window. On printscreen marked with yellow the only thing show after starting Wox.


![2020-08-03 17_10_50-sometimes my wox only show me a line, not the input box · Issue #3105 · Wox-laun](https://user-images.githubusercontent.com/11653351/89199371-bbccac00-d5ae-11ea-8ef0-58890e9a55e6.png)
