### ISSUE TITLE
how to use a specific version of python amidst all the versions installed on the system?

### ISSUE THREAD

**Issue by Aquarii** [Wox-launcher/Wox#3106]
I have python **3.7.6** installed on my system (as part of anaconda), and the version required for Wox to work is **3.7.7**! can you help with this? I thought of creating an environment and update python in that env, but I'm not sure if it'll work. and besides this, I don't know **how to make Wox use that specific version** in that specific env. I'm new to python (actually I'm following a tutorial to learn python and pandas etc. and it's my first time using python/anaconda). 
I'll be so grateful if you could give me some guidance.

**Comment by LoZeno** [comment]
When you install Python, the installer will allow you to specify in which directory do you want to install it - try doing that, specifying a different directory from the default, and once you have installed it go into Wox settings:
![image](https://user-images.githubusercontent.com/3267561/88160732-fb86b180-cc06-11ea-9036-15a27f878dc6.png)
You can set the Python installation to use there.
If your other apps need to use version 3.7.6 and are not compatible with 3.7.7 or above, just make sure that in your PATH environment variable you have the path to version 3.7.6 set.
