### ISSUE TITLE
Support for modern Applications

### ISSUE THREAD

**Issue by andrea-capigiri** [Wox-launcher/Wox#311]
Can you expand the application search index to include modern apps?

**Comment by qianlifeng** [comment]
Since windows 10 has released, it's time to do some research to supporting modern apps/universal apps.

**Comment by keichinger** [comment]
Are we speaking only about being able to search/find apps via Wox or also interacting with them using a Universal (Windows Platform) API?

**Comment by bao-qian** [comment]
This is in my plan.
@cH40z-Lord only about being able to search/find apps via Wox

**Comment by bao-qian** [comment]
use #198 to tracking
