### ISSUE TITLE
本插件是否可能在未来提供个人配置导入导出乃至云功能

### ISSUE THREAD

**Issue by sunencheng** [Wox-launcher/Wox#3120]
**功能描述：**
              本软件是否可以在未来（或者已经提供而我没找到）提供个性化配置文件的导入导出功能。
             **需求来源：**本需求来自于个人今天的操作，选择 portable mode，再切换回来后，我本地的网页搜索自定义的搜索项均已消失，功能也已经不可用，但是那些原来的关键字却还处于占用状态，其他插件也不可使用，而Wox\Settings\Plugins\Wox.Plugin.WebSearch       和        Wox\app-1.4.1196\UserData\Settings\Plugins\Wox.Plugin.WebSearch下的Settings.json文件也已失去个人自定义的搜索项。鉴于此种情况，我只能选择彻底卸载wox然后重装。但是我原来的配置却已经全部消失,如果进行了大量的个性化的定制，则重装会比较麻烦，希望大佬们能酌情考虑下这个需求。
             **另外:**portable mode一旦启用，则无法再次关闭，即使按照提示要求删除Roaming的wox文件夹，wox重启后该文件夹依然会出现，导致portable mode关闭失败，不知道这是否是原先的预定功能。

**Comment by qianlifeng** [comment]
in v2, you can put wox setting folder in cloud drive
