### ISSUE TITLE
命令行安装插件时无法使用相对路径

### ISSUE THREAD

**Issue by jxinging** [Wox-launcher/Wox#313]
使用 `Wox.exe installplugin <plugin路径>` 方式安装插件时只能指定绝对路径，使用相对路径时报错: https://github.com/qianlifeng/Wox/blob/master/Wox/CommandArgs/InstallPluginCommandArg.cs#L26

感谢！

**Comment by bao-qian** [comment]
命令行被移除了。以后会加批量安装插件支持。
