### ISSUE TITLE
Search type priorities 

### ISSUE THREAD

**Issue by Lowengeist** [Wox-launcher/Wox#3142]
Hi, I can't seem to find any option making me able to prefer exe over folders. When comparing with my friend's wox, his always shows application on top, mine only shows folder and I have to scroll down to find the exe or ink. He said that having a shortcut in the start menu could take the priorities, but I have one, and it doesn't show up in wox search, even if I scroll down. I tried looking for filters or someting like that but couldn't find anything.
Juste to be clear, I don't wan't a specific app to show up, I want the exe type of file to show up first for every search. I might want to add that I need to type the EXACT name of the file for it to show up, but my friend only need to write a part of the app name. I haven't changed anything in parameters and he also didn't.
Thanks for the help.

**Comment by Lowengeist** [comment]
![Wox_PtFd6l1IZ7](https://user-images.githubusercontent.com/43280164/89694664-b5716380-d911-11ea-97ea-090598f8d6bd.png)
Here is how I would like to looks like (no need for the full name, application coming first)
![woxmoi](https://user-images.githubusercontent.com/43280164/89694667-b6a29080-d911-11ea-95b8-c97428c823e3.png)
And here is how it comes up for me.

**Comment by nosystemworks** [comment]
I'm in the same boat as you! I've found a workaround of sorts, but it's not ideal. Here's what I did:

1. I created a folder with shortcuts to ALL of my programs (that took a while).
2. I opened Wox settings -> Plugin -> Program
3. I clicked on Add and browsed to the shortcut folder.
4. I restarted Wox and now all searches return the shortcuts first.

![1](https://user-images.githubusercontent.com/69624209/90112030-c5dd7000-dd4f-11ea-861d-6063ce81deee.png)

![2](https://user-images.githubusercontent.com/69624209/90112038-ca098d80-dd4f-11ea-82e8-0cdcaad3014c.png)

![3](https://user-images.githubusercontent.com/69624209/90112047-cc6be780-dd4f-11ea-8154-3ff1c727c4b8.png)

![4](https://user-images.githubusercontent.com/69624209/90112066-cfff6e80-dd4f-11ea-87d1-f8c1ff719235.png)

**Comment by Lowengeist** [comment]
Oh Neat ! 
Thanks a lot !

**Comment by filip-van-hoeckel** [comment]
I think this has to do with the version of either Wox or Everything you're running. I had the same behaviour when updating it a while back, but have been unable to solve. I'll probably roll back to a previous version to see whether that makes a difference.

**Comment by wangyang1633** [comment]
I was having the same issue using Wox and had to do different workarounds. I recommend switching to [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher), this search type priority feature has been added in.

**Comment by Lowengeist** [comment]
Thanks mate ! Will definitely check this out
