### ISSUE TITLE
Sort items by usage frequence / increase score

### ISSUE THREAD

**Issue by adrianmak** [Wox-launcher/Wox#315]
For feature one, sorted by most launched application for same searched strings

**Comment by qianlifeng** [comment]
Wox has implemented this feature and enabled by default.

**Comment by qianlifeng** [comment]
@happlebao  Maybe we can consider improving the score for those first selected items? For now, user need to select more times to make item to be the first one. I have seen many people have this issue

**Comment by qianlifeng** [comment]
@happlebao

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/269

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/239

**Comment by petsuter** [comment]
Is the selected item only remembered / higher scored for the exact searched string? It should also be higher score in general.

I would like one frequently used item to appear after a single letter. (This worked great in Launchy).
But it only appears after three letters. With fewer letters, only items I never selected appear. Even at three letters (where I selected the other item many times) the first item I never selected.

**Comment by eight04** [comment]
It seems that the result list is sorted by plugin? I wonder if it is possible to give higher score to user-selected folders. (i.e. the folder added by user > programs > registry > control panel...)

Also, the exact match should have higher score too: `??abc?` (exact match) > `?a?b?c` (fuzzy).

Or even consider the position of a word: `abc??` > `??abc`

**Comment by StayHomeThereIsNoFrance** [comment]
This functionality works strange. I have to pick needed program about 10 times to make it first. And before that i see programs upper that i never run with Wox.

**Comment by ghost** [comment]
This function does not work properly.

The score should be raised immediately after using an item. Not only for the query used, but also for the characters used individually ie:

If you start fresh and want to open Excel, you type "Excel" fully. Next time you do this it should be on top, but also if you type "E" or "Exc", on both of these queries Excel should be on top (or very high on the list depending on the score system) because score was raised.
