### ISSUE TITLE
1.3.524 还是这个版本最好用啊. 

### ISSUE THREAD

**Issue by ge00111** [Wox-launcher/Wox#3152]
1.3.524 还是这个版本最好用啊. 更新了这么多版本.都不如这个版本体验好.速度快.自动选择第一个.

**Comment by WangJincheng4869** [comment]
的确是啊!新版本还存在卡顿的情况

**Comment by ge00111** [comment]
> 的确是啊!新版本还存在卡顿的情况

新版本都用过...都不行.搜索不准确.唯有这个版本相当准确.
