### ISSUE TITLE
Poor fuzzy search ordering

### ISSUE THREAD

**Issue by mattrossman** [Wox-launcher/Wox#3154]
**Describe the bug**
Wox places a result that directly matches the query sequence lower than one that has the letters spread out.

**To Reproduce**
1. Search for "sti"

**Expected behavior**
"Sticky notes" should be the first result instead of "System information", because "Sticky notes" has a perfect mapping to the query.

**Runtime info**
 - Windows 10 Version: 19041.450
 - Wox version: 1.4.1196

**Wox Error Window text**
N/A

**Screenshots**
![t1IgfnJwE9 (2)](https://user-images.githubusercontent.com/22670878/90186094-a7926700-dd85-11ea-9fa2-754006f16ddc.png)

**Additional context**

**Detailed logs**

[2020-08-13.txt](https://github.com/Wox-launcher/Wox/files/5071403/2020-08-13.txt)

**Comment by mattrossman** [comment]
Another example:
![Wox_DZrv08kYys](https://user-images.githubusercontent.com/22670878/90186816-d0ffc280-dd86-11ea-8b4d-8e5d6fd9dd2c.png)

"Terminal" should appear before "Task Manager"

**Comment by mattrossman** [comment]
I've noticed this depends on what I've set for "Last Query Style" and what I've recently searched for. However, through natural use it is producing incorrect query ordering so something seems wrong.

**Comment by pein** [comment]
New install on windows 10, never happened before!
![Wox](https://user-images.githubusercontent.com/105614/94853821-3ccbe680-042c-11eb-92ef-4cd572f6e804.png)
