### ISSUE TITLE
WoX .NET Framework error about Clipboard

### ISSUE THREAD

**Issue by guoguoaidaogu** [Wox-launcher/Wox#3167]
Bug: WoX .NET Framework error about Clipboard

**Describe the bug**
When I turn on my laptop and launch WoX, it show me a *Microsoft .NET Framework* error, and it tells me it requested clipboard operation did not succeed.
Notice: I installed the *Clipboard History* plugin.

**To Reproduce**
Sorry I don't know why the error occurs, and how to reproduce it.

**Runtime info**
 - Windows 10 Version: 1903 18362.1016
 - Wox version: 1.4.1196

**Error Window text**
See the end of this issue. It's too long.

**Screenshots**
![image](https://user-images.githubusercontent.com/65477873/90955667-1d977c00-e4b2-11ea-87f7-f5174c86d13a.png)
If you cannot see the screenshot please reply this issue.

**Additional context**

**Detailed logs**
Please upload latest log file: 
`%APPDATA%\Wox\Logs\version\<date>.txt`
Please upload log as a whole file

drop and drop your latest log file here

**Error WIndow Text:**

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

\*\*\*\*\*\*\*\*\*\*\*\*\*\* Exception Text \*\*\*\*\*\*\*\*\*\*\*\*\*\*
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.ClipChanged()
   at Wox.Plugin.Clipboard.ClipboardMonitor.ClipboardWatcher.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

\*\*\*\*\*\*\*\*\*\*\*\*\*\* Loaded Assemblies \*\*\*\*\*\*\*\*\*\*\*\*\*\*
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Wox
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Wox.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.0.11381
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/NLog.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Wox.Core
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Wox.Core.DLL
----------------------------------------
Sentry
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Sentry.DLL
----------------------------------------
Sentry.Protocol
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Sentry.Protocol.DLL
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/System.Collections.Immutable.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Wox.Infrastructure
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Wox.Infrastructure.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/System.Net.Http.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.2.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/System.ValueTuple.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Wox.Plugin
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Wox.Plugin.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Newtonsoft.Json.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.1.0
    Win32 Version: 1.9.1.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Splat.DLL
----------------------------------------
HelloWorldCSharp
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/HelloWorldCSharp/HelloWorldCSharp.dll
----------------------------------------
Wox.Plugin.Caculator
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Caculator/Wox.Plugin.Caculator.dll
----------------------------------------
Wox.Plugin.BrowserBookmark
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.BrowserBookmark/Wox.Plugin.browserBookmark.dll
----------------------------------------
Wox.Plugin.Color
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Color/Wox.Plugin.Color.dll
----------------------------------------
Mages.Core
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Caculator/Mages.Core.DLL
----------------------------------------
Wox.Plugin.ControlPanel
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.ControlPanel/Wox.Plugin.ControlPanel.dll
----------------------------------------
Wox.Plugin.PluginIndicator
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.PluginIndicator/Wox.Plugin.PluginIndicator.dll
----------------------------------------
Wox.Plugin.PluginManagement
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.PluginManagement/Wox.Plugin.PluginManagement.dll
----------------------------------------
Wox.Plugin.Everything
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Everything/Wox.Plugin.Everything.dll
----------------------------------------
Wox.Plugin.Shell
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Shell/Wox.Plugin.Shell.dll
----------------------------------------
Wox.Plugin.Folder
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Folder/Wox.Plugin.Folder.dll
----------------------------------------
Wox.Plugin.Program
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Program/Wox.Plugin.Program.dll
----------------------------------------
WindowsInput
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/WindowsInput.DLL
----------------------------------------
Wox.Plugin.Sys
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Sys/Wox.Plugin.Sys.dll
----------------------------------------
Wox.Plugin.WebSearch
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.WebSearch/Wox.Plugin.WebSearch.dll
----------------------------------------
Wox.Plugin.Url
    Assembly Version: 1.4.1196.0
    Win32 Version: 1.4.1196
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.Url/Wox.Plugin.Url.dll
----------------------------------------
Wox.Plugins.CloseScreen
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Close%20Screen-bb7b4cf7-1d5e-44c4-9977-630c7cab219a/Wox.Plugins.CloseScreen.dll
----------------------------------------
Wox.Plugin.IPAddress
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/IP%20Address-d1c4d3c5-475c-439c-b941-d8609758a4ae/Wox.Plugin.IPAddress.dll
----------------------------------------
Wox.Plugin.GoogleTranslate
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Google%20Translate-1ae2c50e-21fc-4569-8620-5cfba8fb3a2e/Wox.Plugin.GoogleTranslate.dll
----------------------------------------
Wox.Plugin.Clipboard
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Clipboard%20History-cf98be2a-740a-45e0-8ef9-a17f3da1feac/Wox.Plugin.Clipboard.dll
----------------------------------------
RemoveUSB
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Remove%20USB-2523ccbd-775e-4b38-896c-fd4a5e0eebbc/RemoveUSB.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Wox.Plugin.Weather
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Weather-5f2161ef-c80b-4cd0-a958-0c6d8bcf1469/Wox.Plugin.Weather.dll
----------------------------------------
WindowsInput
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Clipboard%20History-cf98be2a-740a-45e0-8ef9-a17f3da1feac/WindowsInput.DLL
----------------------------------------
Wox.Plugin.SimpleClock
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Wox.Plugin.SimpleClock-4fabc6d1-54e6-4692-9914-027d4077045c/Wox.Plugin.SimpleClock.dll
----------------------------------------
OpenWeatherMap
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Weather.Open-a2d2c997-55ce-43fe-a89e-06a2e8b6db85/OpenWeatherMap.dll
----------------------------------------
Microsoft.Data.Sqlite
    Assembly Version: 3.1.3.0
    Win32 Version: 3.100.320.12804
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/Plugins/Wox.Plugin.BrowserBookmark/Microsoft.Data.Sqlite.DLL
----------------------------------------
Hexadecimal conversion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/%E8%BF%9B%E5%88%B6%E8%BD%AC%E6%8D%A2-ac94d866-7e1a-4d6d-a668-9dba3bcec53e/Hexadecimal%20conversion.dll
----------------------------------------
Wox.Plugin.Boromak
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/Wox.Plugin.SimpleClock-4fabc6d1-54e6-4692-9914-027d4077045c/Wox.Plugin.Boromak.DLL
----------------------------------------
Wox.Plugin.Express
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/Users/a/AppData/Roaming/Wox/Plugins/%E5%BF%AB%E9%80%92%E6%9F%A5%E8%AF%A2-6edfb5e3-3212-4263-85bc-c9fb708065ba/Wox.Plugin.Express.dll
----------------------------------------
NHotkey
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.1.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/NHotkey.DLL
----------------------------------------
NHotkey.Wpf
    Assembly Version: 1.2.1.0
    Win32 Version: 1.2.1.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/NHotkey.Wpf.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
Windows.UI
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.WindowsRuntime/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.WindowsRuntime.dll
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/System.Runtime.DLL
----------------------------------------
CommandLine
    Assembly Version: 2.7.82.0
    Win32 Version: 2.7.82.0
    CodeBase: file:///C:/Users/a/AppData/Local/Wox/app-1.4.1196/CommandLine.DLL
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------

\*\*\*\*\*\*\*\*\*\*\*\*\*\* JIT Debugging \*\*\*\*\*\*\*\*\*\*\*\*\*\*
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by kleerkoat** [comment]
can report this too

**Comment by AlexDT** [comment]
Same problem for me. So far I noticed it 3x from copying a page link from OneNote 365 ProPlus.

**Comment by puidenz** [comment]
+1
This issue occurs every time I turn on my Windows

**Comment by LucQin** [comment]
same for me

**Comment by MRSlouzk** [comment]
+1

**Comment by fawaf** [comment]
same as https://github.com/Wox-launcher/Wox/issues/2943

**Comment by fawaf** [comment]
same as https://github.com/Wox-launcher/Wox/issues/3233

**Comment by fawaf** [comment]
plugin issue https://github.com/Wox-launcher/Wox.Plugin.ClipboardManager/issues/9

**Comment by ql-isaac** [comment]
I do not decide use this Clipboard.Windows has a stronger function.
![image](https://user-images.githubusercontent.com/53886119/163366657-67597405-6915-4f0f-934f-271781e6472c.png)
