### ISSUE TITLE
search window opens to the far right in windows 10

### ISSUE THREAD

**Issue by jcpeterson** [Wox-launcher/Wox#317]
The window opens to the far right of the center of the screen making it very hard to use. This occurs on Windows 10 with the new Wox beta.

**Comment by JonathanWolfe** [comment]
This used to happen to me while I had my resolution at 4k. Once I bumped it down to 1080p Wox was correctly positioned.

**Comment by jcpeterson** [comment]
It's happening to me on a 1080p laptop screen. Since the laptop is screen is 14 inches, the pixels are very small, so Windows is in high dpi mode, as it should be. In any case, it looks like Wox can't handle this sort of this yet. Would really appreciate a fix.

**Comment by jcpeterson** [comment]
I'm still having this issue on the latest build even though issue #370 claims to address this

**Comment by bao-qian** [comment]
Sorry about that. That pull request cause other problems so it is not merged.

**Comment by jcpeterson** [comment]
No problem. Thanks for working on this

**Comment by bao-qian** [comment]
Please use #271 to discuss position problems in the future.
