### ISSUE TITLE
a issue on win10

### ISSUE THREAD

**Issue by Shen-Shuyi** [Wox-launcher/Wox#318]
![qq 20150822084155](https://cloud.githubusercontent.com/assets/12165540/9421678/45225082-48aa-11e5-81b1-bae54a091566.png)
hi, 我用的OS是win10家庭版,而且已经删除迅雷了,但是每次开机都会出现这个报错画面,但是wox是能正常用的

**Comment by qianlifeng** [comment]
请使用v1.2.0 beta
