### ISSUE TITLE
The order of results

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#32]
Could you put the results of plugin at the head of results list, ohter than at the end?

for example, 
When I type "g sth", I prefer the results like this

```
search "sth" on the internet with google
application1
application2
```

Actually, I got that

```
application1
application2
search "sth" on the internet with google
```

which i think is not handy.

**Comment by qianlifeng** [comment]
Yes, it should be more reasonable to reduce the weight of programs when plugins/custom search also shows. Thanks for the advice. 7ae98ca9feb019f983bc712a9514377237a81579
