### ISSUE TITLE
Wox can't search anything and loads no plugins on Win 10

### ISSUE THREAD

**Issue by jcpeterson** [Wox-launcher/Wox#321]
Wox beta works somewhat ok on one installation of Windows 10. On another, much newer installation, Wox starts and comes up using the hotkey, but can't search anything, not even settings etc. I can access the settings from the tray icon, but no plugins appears for some reason. The rest of the settings seems to work ok.

**Comment by jcpeterson** [comment]
Forgot to mention this is on Win 10 Pro

**Comment by qianlifeng** [comment]
Is there any error log? you can get it in Logs folder under Wox dir.

**Comment by schmic** [comment]
Had a quick test yesterday which worked without any issues. Win10 Pro as well.

Searching, plugins, everything was there.

**Comment by keichinger** [comment]
Make sure that you check whether or not Wox is installed in a directory that is UAC protected such as "Program Files". If it is then you might need to run it as admin by right clicking --> Run as Administrator. Works fine on any of my Windows 10 machines

**Comment by jcpeterson** [comment]
It runs as administrator. Everything won't launch automatically either. Will check logs soon...

**Comment by xysmlx** [comment]
I found the same problem on win10 pro. But it has been solved by logs. The error code in the log is HRESULT:0x80131515. You can search this error code on Google. This problem will be solved after you unlock plugins' dll files or unlock Wox.
![unlock](https://cloud.githubusercontent.com/assets/7117752/9868081/30465f2c-5ba7-11e5-87f8-28558d605019.jpg)

**Comment by jcpeterson** [comment]
Thanks. Why does this happen? I have it in my standard downloads folder on two computers, but the problem only occurs on one machine.

**Comment by xysmlx** [comment]
Both of the two computers run Windows 10?
I find that this problem only occurs on Windows 10.
Wox is normal on Windows 7/8/8.1.
Maybe this problem is caused by the security policy of UAC on Windows 10.
@jcpeterson

**Comment by bao-qian** [comment]
Use #279 to track in the future
