### ISSUE TITLE
Restarting causes "Programm does not work anymore" issue

### ISSUE THREAD

**Issue by TheZoker** [Wox-launcher/Wox#322]
When I restart wox (e.g after installing plugin) or by typing "restart" the program crashes and I have to restart it manually.

I use Win 10.

**Comment by keichinger** [comment]
What is the exception/error you're getting?
What version are you on?

**Comment by lances101** [comment]
Can confirm. Upon typing "restart" it just shuts down but does not restart. No errors.

**Comment by lances101** [comment]
Tested on four systems. #368 seems to fix this bug.

**Comment by bao-qian** [comment]
Hi, I refactored the logic of restart. use `ping` to test existence of Wox will cause more bugs in the future.
Please try build [1.2.0.575](https://ci.appveyor.com/api/buildjobs/oevl2s4t54xi9c84/artifacts/Output/release-binary.zip) and provide feedbacks.
Code: 24866ff032829e9bd34704d3d5970d227a4c8db3

**Comment by bao-qian** [comment]
@TheZoker @lances101

**Comment by TheZoker** [comment]
Will test it

**Comment by lances101** [comment]
@happlebao, thanks! Definitely better than before, but with one new problem:

Hotkey registration fails upon restart, but registers fine on the initial start.

**Comment by bao-qian** [comment]
@lances101 could you provide more details?

**Comment by lances101** [comment]
@happlebao Whenever Wox is restarted, the global hotkey does not get unhooked in time, so when the new instance starts, it tries to hook the same key and fails. I will debug this once I have the time.

**Comment by bao-qian** [comment]
@lances101 I get it. This is still a thread issue. I thought I fixed it.
If you wan to help, take a look at line 299 @ 24866ff032829e9bd34704d3d5970d227a4c8db3 
it should return value of firstInstance, and sleep until mutex is released.
sth like.

```
firstInstance = new Mutex(true, applicationIdentifier, out firstInstance );
while (fistInstance != Ture)
{
    sleep(500);
}
return firstInstance;
```

But the `Mutex` is not released, even if the first instance is closed. so `firstInstance` is always `False`. I stuck here.

**Comment by bao-qian** [comment]
@lances101 @TheZoker 

Please try again with build [1.2.592](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.592/artifacts) and provide feedbacks.

**Comment by lances101** [comment]
@happlebao I think you have completely fixed it! :) No more problems with the hotkey part.

**Comment by bao-qian** [comment]
@lances101 thanks for feedback.
