### ISSUE TITLE
Options for disabling mouse selection

### ISSUE THREAD

**Issue by shenhai-ran** [Wox-launcher/Wox#3231]
**Is your feature request related to a problem? Please describe.**
After hotkeys, selection  is set to mouse cursor location. 
Sometimes, I may just want to use `hotkeys+enter` very quick to open my last query. But the mouse location may change the selected term.

**Describe the solution you'd like**
Add option that disable the mouse selections

**Comment by edgartaor** [comment]
Any news on this? 
This is the only problem I have with the app.

**Comment by qianlifeng** [comment]
we will solve this in v2 @lylwx

**Comment by lylwx** [comment]
we solved the ' mouse cursor location' problem in v2
