### ISSUE TITLE
Including Wox.Infrastructure.dll in NuGet package and some Plugin API concerns/issues

### ISSUE THREAD

**Issue by keichinger** [Wox-launcher/Wox#325]
I think we can all agree that the Plugin API is somewhat limiting at the moment, especially for third party developers. I've noticed that v1.3.0.0 Beta (which doesn't run at the moment on my machine) you get a lot more features than you have, let's say, in v1.1 or v1.2.

However, what is still missing is something critical IMO: Wox.Infrastructure.dll should be part of the NuGet package to provide a unified system to third party plugin developers to handle things such as saving/loading data.

I've also got a strong opinion that Wox should at least target .NET 4.0 to stop this hacking with System.Xaml.dll in a regular desktop lib. By default you can't add System.Xaml.dll as reference using the "Add Reference" dialog in Visual Studio, instead you need to manually add it by editing the .csproj file _just_ to try implementing a basic settings UserControl. Obviously the same applies to translations. Adding a ResourceDictionary in .NET 3.5 to a class library is not possible, you have to copy it from somewhere else and move it into your project manually.

A move to .NET 4.0 (or even higher, though that would mean that Wox can no longer target Windows XP users - which any sane person shouldn't do anyway) would also mean to get proper `async`/`await` support for C# which could greatly enhance user experience across the entire application.

I think I've read somewhere that one shouldn't do that  much inside `IPlugin.Query` to increase snappyness of search queries. Moving things into threads doesn't really solve the problem with how to let Wox itself know when results are back in?
Changing the method signature to `public async Task<List<Result>> QueryAsync(Query query) { ... }` (or just providing it as an additional method) would help circumvent issues.
When doing that I suggest either creating an `IPluginAsync` version for async-only or moving `IPlugin` into a common abstract baseclass with virtual implementations to not break everyone with a new update.

**Comment by bao-qian** [comment]
Don't worry, the query is executed in separated thread using `ThreadPoll.QueueUserWorkItem()`

**Comment by happlebao** [comment]
I **will** write a .NET version collector before decide which version should Wox upgrade to.
https://github.com/happlebao/Wox/issues/8

**Comment by bao-qian** [comment]
hi, in the future
1. use #393 to track .net 4.5 issue
2. use #364 to track API issue
