### ISSUE TITLE
Integration with Windows Terminal

### ISSUE THREAD

**Issue by mateusmlo** [Wox-launcher/Wox#3251]
Pretty self-explanatory: it would be nice if we could serve commands directly to the Windows Terminal, since from what I saw on the settings, it only runs on CMD or PowerShell. 
Since WT can run all sorts of other terminals inside it, it would fall to the end-user to know which default terminal the commands would be sent to; e.g. in my case it's zsh, so I'd run UNIX stuff with it, like running an alias to open a project folder etc.

**Comment by SnirBroshi** [comment]
You seem to be confusing the terms shell and terminal:

A terminal is a GUI program that provides textual input and output to be able to run non-GUI programs (which are sometimes called CLI or TUI) in a GUI environment.
A shell is a non-GUI program, so it must run in a terminal, and it provides a command-line interface to be able to run other CLI programs with arguments and usually pipes and stuff.

In Windows if you launch a non-GUI program it will automatically open the terminal for you and run it.

The default terminal in Windows is called "The Windows Console Host", or "conhost.exe".
It is replaced by the new Windows Terminal, but it currently can't really replace conhost as the default terminal, this is tracked in https://github.com/microsoft/terminal/issues/492, and there is also a [spec](https://github.com/microsoft/terminal/blob/dev/miniksa/defterm_spec/doc/specs/%23492%20-%20Default%20Terminal/spec.md) about their plans.

As for a default shell, Windows only has the option to switch between cmd and powershell, and this also affects almost nothing.

---

So what you're asking is for Wox to parse the Windows Terminal configuration file (JSON) to see what is the default shell that the user has configured.

I'm not sure the configuration file is guaranteed to stay in the same place and have the same format in future versions of Windows Terminal, but I like the idea.

Also a good idea is to have the shell plugin (`Wox.Plugin.Shell`) support more than just CMD and PowerShell in the settings.

**Comment by Drimix20** [comment]
I found pull request [#1308](https://github.com/Wox-launcher/Wox/pull/1308) which is merged and should support wsl command as bash option. But current version of code is changed, so not sure if it is working properly.
