### ISSUE TITLE
Setting to use plugins without typing keyword

### ISSUE THREAD

**Issue by maxfragg** [Wox-launcher/Wox#326]
I would want to have some plugins (like everything) on by default, without having to type a hotword/letter to activate them

**Comment by schmic** [comment]
@maxfragg You can use a different Hotkey for an action/hotword ... 

See "Settings -> Hotkey".

**Comment by deltaidea** [comment]
IIRC, you can just use an empty hotword. That will activate a plugin from the first character in the input.

**Comment by lances101** [comment]
**This issue can be closed.**
You can set \* as the keyword for the plugin to be fired.
