### ISSUE TITLE
program plugin cannot index steam games

### ISSUE THREAD

**Issue by sheey11** [Wox-launcher/Wox#3269]
**Is your feature request related to a problem? Please describe.**
Wox cannot index steam games, which `uri` seems like `steam://rungameid/123456`.

**Describe the solution you'd like**
index any `.url` file which contains a format like `steam://rungameid/**`.

**Describe alternatives you've considered**
index any `.url` file which satisfy a given format.

**Comment by a13ph** [comment]
http://www.wox.one/plugin/135 works for me
