### ISSUE TITLE
When launching applications the "working directory" is not set

### ISSUE THREAD

**Issue by schmic** [Wox-launcher/Wox#327]
I have some portable applications which do not find their data/configurations when started via Wox.

Example: Telegram-Messenger (telegram.exe)

When I double-click the .exe-file everything is fine.
If I start the .exe-file via Wox it wants to create a new configuration.

**Comment by bao-qian** [comment]
Hi, please provide the download link for the problematic application.
And a screenshot of the properties window (right click -> property) of .exe file

**Comment by bao-qian** [comment]
close due to no response, reopen it if you have more info.
