### ISSUE TITLE
No new releases?

### ISSUE THREAD

**Issue by LoZeno** [Wox-launcher/Wox#3296]
The last stable release for Wox dates back to 24 February 2018; since then, it's been only pre-releases until v1.4.1196, which reads, in the release notes

"this will be the last prerelease before stable release."

This was on 25 May 2020. Since then, @bao-qian has gradually become less and less active, and now it's been months since he has showed up.
Is this project dying? Will we see no new releases? And more importantly, does anyone know what has happened to @bao-qian ?

**Comment by cannolis** [comment]
Perhaps he is just tired of the endless debugging tasks.

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
