### ISSUE TITLE
Wox Launcher vs Flow Launcher

### ISSUE THREAD

**Issue by wangyang1633** [Wox-launcher/Wox#3300]
I just switched to windows from Mac...

Wox Launcher looks interesting, but after trying it I found a lot of annoying issues... I searched around and also found Flow Launcher https://github.com/Flow-Launcher/Flow.Launcher

Is Wox Launcher still being actively developed? There are constant issues popping up from users and it looks like Flow Launcher is being rapidly updated with gazillion fixes and features...

I think there are also users asking the same questions here https://github.com/Wox-launcher/Wox/issues/2960

Anyway I don't want to waste anymore time on another launcher so does anyone know what benefits Wox Launcher has over Flow Launcher?

Also has anyone used both and know which one is better?

**Comment by Findoss** [comment]
Flow.Launcher is a fork Wox
