### ISSUE TITLE
[Alfred]  Default  search  without search engine key

### ISSUE THREAD

**Issue by Rat-racer** [Wox-launcher/Wox#3335]
In alfred,  we are able to direct search some contents without 'g' character, which is  set by default search engine. However, in wox, this feature is lost, users have to type extra spaces and keys. Especially for Chinese users , we have to frequently switch input language setting, which is really inconvenient.  Could you add this function later?

**Comment by wangyang1633** [comment]
I had this issue also. Switch to Flow Launcher, it will allow you to remove the 'g' character when searching.
https://github.com/Flow-Launcher/Flow.Launcher
