### ISSUE TITLE
Search box reset feature needed

### ISSUE THREAD

**Issue by devhojaelee** [Wox-launcher/Wox#3340]
**Is your feature request related to a problem? Please describe.**
When I type something on wox search box and enter 'esc' key, 
next time the texts what I wrote are remained.

**Describe the solution you'd like**
Someone would love it or someone not.
So enable button would be better.

**Describe alternatives you've considered**

**Additional context**
I'm using a latest wox and have unchecked 'remember last launch location' (I don't know what this is exactly, but I disabled it anyway)

**Comment by qianlifeng** [comment]
support setting in v2
