### ISSUE TITLE
Option to disable hotkey when a fullscreen application is in focus.

### ISSUE THREAD

**Issue by drathier** [Wox-launcher/Wox#335]
Right now, if a program is running in fullscreen mode, the hotkey for opening Wox still works, with no option to disable it. I would like there to be an option to disable the hotkey if the currently focused window is running in fullscreen mode (not maximized).

**Comment by drathier** [comment]
The main use case for this is gaming.

**Comment by lances101** [comment]
I don't think adding an option to exclude all full-screen applications is a good choice. Rather, we could implement a list of "ignored" applications. Wox will not pop-up when the hotkey is pressed and they are topmost.

**Comment by drathier** [comment]
In that case, why not both? Gamers will surely be annoyed if they have to manually add each game. When you run a new game, you'll accidentally hit your hotkey at the worst possible time. Then you panic and try to get back into the game asap. When you're done playing, you have to remember to add the game to the list of excluded apps. Then you start the game again, and accidentally hit the hotkey, and wox pops up again, because you forgot that most games have at least one launcher (which is the program you run every time you want to start the same, so you think it's the main game executable, but it's not). Then you frantically get back into the game, and hope that you didn't fail the level or die because of that. Once you're done playing again, you try to find that pesky little executable somewhere that is the actual game. I'm pretty sure you'll find the wrong one, or miss one of them.

Give us a few examples of full-screen apps where you still want wox to pop up, as a counter-argument. :)

**Comment by lances101** [comment]
I just don't really run any apps in full-screen mode, so that's why I may be missing the point :)

Anyway. It's done - #340

**Comment by 3DManuH** [comment]
Doesn't work for me. Is there a known issue with the latest version?

**Comment by mattheworres** [comment]
@3DManuH latest version (2.0) is a beta release, and if on Windows especially it's recommended to use the 1.x version in the meantime. 2.0 is in an incomplete state (there has been some level of development since then, but it looks to me like a rewrite in Go. Didn't see any mention of this setting existing in the new version yet).

The 1.x version has the setting that @lances101 added in the PR above.
