### ISSUE TITLE
Overflow or underflow in the arithmetic operation

### ISSUE THREAD

**Issue by ishu3101** [Wox-launcher/Wox#336]
When I open Wox 1.20 beta I get **Overflow or underflow in the arithmetic operation** as shown below.

![wox overflow arithmetic operation error](https://cloud.githubusercontent.com/assets/3212162/10182884/33ea4496-6786-11e5-8cc4-c42a726b59bb.png)

Here is the output from the log file.

```
System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   Source: WindowsBase
   TargetAssembly: WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: WindowsBase.dll
   TargetSite: Void .ctor(Double, Double)
   at System.Windows.Size..ctor(Double width, Double height)
   at System.Windows.Documents.AdornerLayer.InvalidateAdorner(AdornerInfo adornerInfo)
   at System.Windows.Documents.AdornerLayer.UpdateElementAdorners(UIElement element)
   at System.Windows.Documents.AdornerLayer.UpdateAdorner(UIElement element)
   at System.Windows.Documents.AdornerLayer.Add(Adorner adorner, Int32 zOrder)
   at System.Windows.Documents.CaretElement.EnsureAttachedToView()
   at System.Windows.Documents.CaretElement.Update(Boolean visible, Rect caretRectangle, Brush caretBrush, Boolean italic, CaretScrollMethod scrollMethod, Double scrollToOriginPosition)
   at System.Windows.Documents.TextSelection.UpdateCaretStateWorker(Object o)
   at System.Windows.Documents.TextSelection.UpdateCaretState(CaretScrollMethod caretScrollMethod)
   at System.Windows.Documents.TextSelection.EnsureCaret(Boolean isBlinkEnabled, CaretScrollMethod scrollMethod)
   at System.Windows.Documents.TextSelection.System.Windows.Documents.ITextSelection.UpdateCaretAndHighlight()
   at System.Windows.Documents.TextEditor.OnGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.Controls.Primitives.TextBoxBase.OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
   at System.Windows.UIElement.OnGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at Wox.MainWindow.ShowWox(Boolean selectAll) in c:\projects\wox\Wox\MainWindow.xaml.cs:line 544
   at Wox.MainWindow.<ShowApp>b__7() in c:\projects\wox\Wox\MainWindow.xaml.cs:line 103

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: System.Object _InvokeMethodFast(System.Object, System.Object[], System.SignatureStruct ByRef, System.Reflection.MethodAttributes, System.RuntimeTypeHandle)
   at System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Program Files\Wox-1.2.0-beta\Wox.exe" 
- Timestamp: 2015-09-30T15:09:32.8336445+13:00
- IntPtr Length: 4
- System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
- CLR Version: 2.0.50727.5485
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.5420 SP2
  - v3.0 3.0.30729.5420 SP2
  - v3.5 3.5.30729.5420 SP1
  - v4 Client 4.5.50938
  - v4 Full 4.5.50938
  - v4.0 Client 4.0.0.0
  - 4.5.1 installed on Windows 8, Windows 7 SP1, or Windows Vista SP2
## Assemblies - Wox.exe
- Wox, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Wox.exe)
- Exceptionless, Version=1.5.2121.0, Culture=neutral, PublicKeyToken=fc181f0a46f65747 (C:\Program Files\Wox-1.2.0-beta\Exceptionless.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\NHotkey.Wpf.dll)
- Wox.Plugin, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Wox.Plugin.dll)
- Wox.Infrastructure, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Wox.Infrastructure.dll)
- Wox.Core, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Wox.Core.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\NHotkey.dll)
- Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Program Files\Wox-1.2.0-beta\Newtonsoft.Json.dll)
- Exceptionless.Models, Version=1.5.2121.0, Culture=neutral, PublicKeyToken=fc181f0a46f65747 (C:\Program Files\Wox-1.2.0-beta\Exceptionless.Models.dll)
- NAppUpdate.Framework, Version=0.1.0.0, Culture=neutral, PublicKeyToken=d1f1d1f19f9e5a56 (C:\Program Files\Wox-1.2.0-beta\NAppUpdate.Framework.dll)
- NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Program Files\Wox-1.2.0-beta\NLog.dll)
- Wox.Plugin.Caculator, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Calculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Calculator\YAMP.dll)
- Wox.Plugin.CMD, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.CMD\Wox.Plugin.CMD.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Program Files\Wox-1.2.0-beta\WindowsInput.dll)
- Wox.Plugin.Color, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Sys, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- Wox.CrashReporter, Version=1.2.0.422, Culture=neutral, PublicKeyToken=null (C:\Program Files\Wox-1.2.0-beta\Wox.CrashReporter.dll)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll)
- PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_32\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
- PresentationFramework.Aero, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\PresentationFramework.Aero\3.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)
- System.Runtime.Serialization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Runtime.Serialization\3.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Xml.Linq\3.5.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_32\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- UIAutomationProvider, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\assembly\GAC_MSIL\UIAutomationProvider\3.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
- System.Security, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Security\2.0.0.0__b03f5f7f11d50a3a\System.Security.dll)
- System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_32\System.Web\2.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
- System.Data.SqlXml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Data.SqlXml\2.0.0.0__b77a5c561934e089\System.Data.SqlXml.dll)
- System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_32\System.Transactions\2.0.0.0__b77a5c561934e089\System.Transactions.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.ServiceModel\3.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- Accessibility, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\Accessibility\2.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)
- SMDiagnostics, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\SMDiagnostics\3.0.0.0__b77a5c561934e089\SMDiagnostics.dll)
- System.IdentityModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_MSIL\System.IdentityModel\3.0.0.0__b77a5c561934e089\System.IdentityModel.dll)
- System.EnterpriseServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_32\System.EnterpriseServices\2.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll)
- System.Web.Services, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.Web.Services\2.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll)
- System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\assembly\GAC_MSIL\System.ServiceProcess\2.0.0.0__b03f5f7f11d50a3a\System.ServiceProcess.dll)

**Comment by bao-qian** [comment]
Hi, do you still have this issue for the latest build?
Could you provide the setup of your monitor? resolution and how many monitor.

**Comment by ishu3101** [comment]
Great. The latest build solves the issue.

**Comment by bao-qian** [comment]
Thanks for feedback.
