### ISSUE TITLE
Wox crashes at launch "Stopped working" (Windows 10)

### ISSUE THREAD

**Issue by mullerch** [Wox-launcher/Wox#338]
Since I updated to Windows 10, Wox crashes at every start :
- [Report.wer](http://pastebin.com/PYJUEvKP)
- [WER3E05.tmp.WERInternalMetadata.xml](http://pastebin.com/iMWbbpsB)

I never developped under Windows so tell me if I can provide aditionnal information.

I miss wox :) Thanks

**Comment by qianlifeng** [comment]
Did you see any errors in the log file, which should be located under logs folder that besides Wox.exe

**Comment by mullerch** [comment]
Here it is : http://pastebin.com/2kq9HUdX

Seems to be a UserSettingsStorage error.

**Comment by bao-qian** [comment]
@ozwin I'm using Windows 10 as well, no problems at all.
1. try the solution of this [issue](https://github.com/Wox-launcher/Wox/issues/279)
2. it is probably a permission issue, try put it on your user folder or D:\
