### ISSUE TITLE
Switcheroo 插件不支持中文拼音搜索

### ISSUE THREAD

**Issue by makerjackie** [Wox-launcher/Wox#3383]
wox 支持 拼音
![image](https://user-images.githubusercontent.com/18050469/109425146-e803ba80-7a21-11eb-8a2c-1cbc7ad70757.png)

Switcheroo 不支持拼音
![image](https://user-images.githubusercontent.com/18050469/109425138-de7a5280-7a21-11eb-9474-ef683122b6d7.png)

**Comment by penghaiheng** [comment]
![image](https://user-images.githubusercontent.com/25241248/115384084-2ee38480-a209-11eb-8d1d-b6b84a2c4d06.png)
![image](https://user-images.githubusercontent.com/25241248/115384098-373bbf80-a209-11eb-9391-47c5f629302f.png)
![image](https://user-images.githubusercontent.com/25241248/115384162-4ae72600-a209-11eb-87d5-31ed46d4ea0c.png)

I'm not sure that's the problem

**Comment by makerjackie** [comment]
wox works find, but "switcheroo" isn't, for example, try to search `win wyy` won't get result ( when 网易云音乐 is open)
