### ISSUE TITLE
[clipboard] Wox delays LibreOffice copy to clipboard

### ISSUE THREAD

**Issue by georgeto** [Wox-launcher/Wox#342]
When I start LibreOffice, while Wox is running, doesn't matter if in foreground or background, it tooks several seconds till the text i copied out of an LibreOffice document is available for pasting.
In the meantime the clipboard is empty respectively nothing happens if i paste the clipboard in an program that is not LibreOffice.

If I restart Wox or start LibreOffice before Wox everything works fine.

**Comment by lances101** [comment]
@Georgeto, what plugins do you have installed?

**Comment by georgeto** [comment]
```
Chocolatey-ab4b2dc8-c644-4644-8c0f-aa66dd6f6de1\
Clipboard History-48e215d8-6728-493a-a773-d462f4cf56dd\
Currency Converter-7de04925-e091-4aa1-828a-4f111eaf3f2f\
Hosts-4dea3b82-6a39-49ba-96e0-af14737238bd\
Translate-c02b1543-b8a4-4095-902e-bfb94cf867c7\
Wox.Plugin.Caculator\
Wox.Plugin.CMD\
Wox.Plugin.Color\
Wox.Plugin.ControlPanel\
Wox.Plugin.DiskSpace-f79d3689-0725-44d5-a4ba-34f1619def07\
Wox.Plugin.Everything\
Wox.Plugin.Folder\
Wox.Plugin.PluginIndicator\
Wox.Plugin.PluginManagement\
Wox.Plugin.ProcessKiller-9616d7b6-d27f-4a46-b2ae-0f4f823046c0\
Wox.Plugin.Program\
Wox.Plugin.Sys\
Wox.Plugin.Timestamp-e8730902-efd6-4631-8676-ff28526e9462\
Wox.Plugin.Url\
Wox.Plugin.WebSearch\
Wox.Skype-f965f646-bdd7-40da-a475-fdd55cf4894a\
Wox.Spotify-64d18ccb-e115-4378-b32b-193c29e4eb93\
```

**Comment by lances101** [comment]
@Georgeto, hm.. Strange, I have almost the same set of plugins and it seems to be alright in MS Word. Installing Libre now

**Edit:** Confirmed. Most likely this is caused by one specific plugin. I'll narrow this down by disabling them all and enabling one by one

**Comment by georgeto** [comment]
I don't know if it matters, I'm using Libre Office 5.0.2.2.

**Comment by lances101** [comment]
**Found the culprit**
Try disabling **Clipboard history** and it should not happen again. 
As for why it happens, well.. That requires some debugging with the plugin itself.

**Comment by georgeto** [comment]
Somehow disabling the plugin doesn't work for me. Deleting it from the plugin folder did the job.
Thank you, I really appreciate your spontaneous reaction.

**Comment by lances101** [comment]
@Georgeto, yea, the clipboard was hooked upon initialization, so deleting it was the way to go.

**Comment by bao-qian** [comment]
The disable functionality should be improved.
https://github.com/happlebao/Wox/issues/12

**Comment by bao-qian** [comment]
Same problems here: https://github.com/Wox-launcher/Wox/issues/258

**Comment by lances101** [comment]
@happlebao As discussed before, the Clipboard problem is not on our side (_see below_), it's LibreOffice. Consider closing this issue, https://github.com/Wox-launcher/Wox/issues/351 already covers better plugin disable functionality. 

[2005-05-26 - Oldest reference to the problem I could find](https://bz.apache.org/ooo/show_bug.cgi?id=49907)
[2016-03-04 - Still not fixed](https://bz.apache.org/ooo/show_bug.cgi?id=113171)

**Comment by bao-qian** [comment]
@lances101 yeah, great works
