### ISSUE TITLE
搜索结果的排序优化

### ISSUE THREAD

**Issue by netsonicyxf** [Wox-launcher/Wox#3423]
Wox 1.4.1196，搜索pdf3，想打开的“PDFXEdit3 - 快捷方式”，搜索结果不是第一个。
![1](https://user-images.githubusercontent.com/43513391/115942690-0d6eeb00-a4de-11eb-973a-bc11909daf95.png)
下一次再搜索pdf3，搜索结果依然**不是**第一个。

如果改用Launchy，它可以记住你上次打开的程序，第一次搜索pdf3，“PDFXEdit3 - 快捷方式”可能不是在第一个，但打开一次后，后面再搜索pdf3，就会把“PDFXEdit3 - 快捷方式”放在第一个。
![1](https://user-images.githubusercontent.com/43513391/115942820-9f76f380-a4de-11eb-8666-4351d522a99f.png)

**Comment by qianlifeng** [comment]
duplicate with #315
