### ISSUE TITLE
根据搜索频率自动调整搜索结果的排序

### ISSUE THREAD

**Issue by netsonicyxf** [Wox-launcher/Wox#3447]
在Launchy里，搜索次数多的结果会在以后的搜索中自动向上排，比如搜totalcmd（total commander的可执行程序），搜索几次后只要查t，就会在第一个搜索结果显示totalcmd。

但这个在wox里做不到，希望能加上这个功能，非常有效。

**Comment by cai23511** [comment]
有点像智能拼音输入法，常用词自动靠前

**Comment by netsonicyxf** [comment]
> 有点像智能拼音输入法，常用词自动靠前

是的，希望作者能加上这个**非常有用** 也是**非常常用** 的功能。

**Comment by qianlifeng** [comment]
duplicate with #315
