### ISSUE TITLE
Search engine 

### ISSUE THREAD

**Issue by Aaron-Brasher** [Wox-launcher/Wox#3449]
Is there a way to change the default search engine from Chrome to Firefox

**Comment by vladimir-asmo** [comment]
Only if you change the system default browser.

**Comment by vladimir-asmo** [comment]
@WhiteKnight4369, Wox Settings => Plugins => Web Searches ==> Set browser from path.

**Comment by Aaron-Brasher** [comment]
> 
> 
> @WhiteKnight4369, Wox Settings => Plugins => Web Searches ==> Set browser from path.

Thank you I got it fixed. Have a nice day.
