### ISSUE TITLE
Everything plugin client not running

### ISSUE THREAD

**Issue by souxd** [Wox-launcher/Wox#3454]
![image](https://user-images.githubusercontent.com/51197853/121581422-3141ae00-ca04-11eb-95b7-033d16cc6890.png)

**Comment by cai23511** [comment]
要单独安装一下 Everything-1.4.1.969.x64-Setup.exe

**Comment by souxd** [comment]
Everything was installed and running but wouldnt work with wox for some reason but it's working now for some reason
