### ISSUE TITLE
[hotkey] double click  \ 双击

### ISSUE THREAD

**Issue by clm0081** [Wox-launcher/Wox#346]
比如双击alt这样 另外可否考虑添加一个 修改ctrl+空格 为 ctrl+shift 效果的功能

**Comment by bao-qian** [comment]
去下 ![最新 build](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0-build)。
启动快捷键是可以改的，win键好像不能用。你自己试试吧。
![hotkey](http://i.imgur.com/mm10lMu.png)

**Comment by clm0081** [comment]
我想要的效果是 双击某个按键 而不是一个组合键

**Comment by 2ue** [comment]
win7下似乎不支持双击设置快捷键？

**Comment by bao-qian** [comment]
@2ue 现在哪个系统都不支持。。。

**Comment by 2ue** [comment]
额，好吧，期待支持的那天~

**Comment by genequ** [comment]
双击Ctrl的都是Google Desktop的用户 -:)

**Comment by olamaekle** [comment]
Sorry I'm not that fluent in Chines (Google translate), I take it that it's not possible to use double-tap as a hotkey? E.g. tap 2 times on "alt"?

**Comment by 0b5vr** [comment]
+1 for this

**Comment by ghost** [comment]
+1 like listary

**Comment by Dev-Wiki** [comment]
就是因为不支持 双击 ctrl 我试用了一次以后没再使用了 继续使用了 listary

**Comment by mike-boost** [comment]
double type ctrl is more convenient than different keys combination

**Comment by uniquejava** [comment]
mac下的alfred我是设置的double command，
 我想windows上用相同的快捷键。希望作者可以实现。 windows应该是可以的， 有其他软件可以这么设置快捷键。

**Comment by zhangzitao** [comment]
+1 for this

**Comment by qianlifeng** [comment]
Has been implemented in v2, close now
