### ISSUE TITLE
Wox alternatives

### ISSUE THREAD

**Issue by teddyhouse** [Wox-launcher/Wox#3465]
Browsing GitHub, found some worthy alternatives:
- Zazu https://github.com/bayleeadamoss/zazu - looks decent
- Flow Launcher https://github.com/Flow-Launcher/Flow.Launcher - the new Wox
- LaunchyQt https://github.com/samsonwang/LaunchyQt - the new Launchy
- Ueli https://github.com/oliverschwendener/ueli - cross platform launcher

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
