### ISSUE TITLE
现在 window powertoys 支持 类似 wox的功能了

### ISSUE THREAD

**Issue by makerjackie** [Wox-launcher/Wox#3471]
下载地址:  Releases · microsoft/PowerToys · GitHub  
![image](https://user-images.githubusercontent.com/18050469/124340911-48cb1b80-dbeb-11eb-8719-d5a0e3626aa7.png)

**Comment by icksky** [comment]
搜索不给力, 没整合 everyting

**Comment by makerjackie** [comment]
> 搜索不给力, 没整合 everyting

可以改设置，对全局文件索引，搜索结果应该就类似 everything 了，不过确实没 everything 给力
