### ISSUE TITLE
关于Windows11兼容性bug

### ISSUE THREAD

**Issue by StevenLee003** [Wox-launcher/Wox#3479]
Wox版本：1.4.1196
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22000 暂缺 Build 22000
CPU: Intel Core i7-9750H
GPU: NVDIA 1660ti

Wox后台运行后，快速左右移动资源管理器窗口，会出现光标漂移的现象，而且严重情况下可能导致Explorer.exe进程卡死重启
Wox关闭后此问题得到解决
出现此问题之前最近一次打的补丁为KB5004034
尚未打补丁KB5004745
KB5004745打完后仍然出现此Bug

**Comment by Sciroccogti** [comment]
Wox版本：1.4.1196
OS 名称: Microsoft Windows 11 专业版
OS 版本: 10.0.22000 暂缺 Build 22000.65
CPU: AMD 3700X
GPU: NVIDIA 2070SUPER

未打补丁 KB5001030 KB4597245 KB4578967

未出现本问题

**Comment by HasGenvts** [comment]
Wox版本：1.4.1196
OS 名称: Microsoft Windows 11 专业版
OS 版本: 10.0.22000 暂缺 Build 22000.71
CPU: AMD 3750h
GPU: NVIDIA 1650

出现该问题
自从升级至windows11，发现拖动资源管理器延迟
关闭Wox后发现正常。

**Comment by HasGenvts** [comment]
不知道能否尽快兼容

**Comment by Skova-shi** [comment]
我也是发现了，今天自己找到了，也是出现资源管理器出现BUG 
自从升级至windows11，发现拖动资源管理器延迟
关闭Wox 后 可正常使用，重新启动wox后依旧，关闭部分插件，无效果
