### ISSUE TITLE
Organization name

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#348]
Wox has already been taken.
Any ideas?
https://github.com/qianlifeng/Wox/issues/300

**Comment by qianlifeng** [comment]
Wox-Launcher?

**Comment by qianlifeng** [comment]
I have created a [Wox-launcher Organization](https://github.com/Wox-launcher/Wox) and invited you.

**Comment by deltaidea** [comment]
A better name would've been **github.com/getwox/wox**, but this will suffice too.
_Edit:_ This is just my opinion, of course. You decide. :)

**Comment by bao-qian** [comment]
@qianlifeng what do you think? The organization name can be changed.

**Comment by qianlifeng** [comment]
I prefer Wox-launcher :smile:
