### ISSUE TITLE
Is there any way to keep a python plugin in memory?

### ISSUE THREAD

**Issue by tchar** [Wox-launcher/Wox#3499]
Hello,
I am trying to integrate my [plugin](https://github.com/tchar/ulauncher-albert-calculate-anything) into wox but every type I type any key the plugin gets reset.

Suppose the following sample plugin
```python
from wox import Wox
import random
rand = random.randint(1, 10000)

class Main(Wox):
    def query(self, key):
        return [{
            'Title': str(rand)
        }]

if __name__ == "__main__":
    Main()
```
Every time I type a single word I get a different output.
Is there any way to persist the plugin into memory without reinstantiating it every time I type a single word? I can't block the main thread with requests every time I press a key.

**Comment by Animeshz** [comment]
I don't know exactly about these but since the plugin architecture is inside out, based on callbacks you should rely on the actual program to store the data https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Folder/Main.cs has used PluginJsonStorage to store and retrieve data on demand...

**Comment by tchar** [comment]
Hi @Animeshz. Well the problem is that
- I make requests asynchronously so I don't block the UI, so by the time I receive the response my program has ended
- I use sqlite and I can't afford to re open a connection every time.
- I load the currency in a unit storage which the first time may take half a second or one the first time it's loaded

**Comment by qianlifeng** [comment]
will support in v2
