### ISSUE TITLE
Refactor Setting window UI with elysium

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#35]
http://elysium.codeplex.com/

**Comment by qianlifeng** [comment]
<img src="http://ww3.sinaimg.cn/large/5d7c1fa4gw1eej0ppbh5rj20hz0ci3z3.jpg"/>
<img src="http://ww3.sinaimg.cn/large/5d7c1fa4gw1eej0qkn7zcj20hz0ciwfl.jpg" />
<img src="http://ww4.sinaimg.cn/large/5d7c1fa4gw1eej0qt9l2vj20hz0cigmr.jpg" />

Designed by @oott123

**Comment by oott123** [comment]
sorry for my mistake.
now here is the real plugins page.
![plugins](https://f.cloud.github.com/assets/905663/2437321/e23d4ca2-ade5-11e3-86b0-586765d365fb.png)

**Comment by qianlifeng** [comment]
@oott123  Thanks for providing those designs. It looks very good.

**Comment by qianlifeng** [comment]
closing this since Elysium needs .net framework 4 above.
