### ISSUE TITLE
UI flickering

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#350]
The root cause is because the abuse usage of Clear() methods for results.

Releated: https://github.com/Wox-launcher/Wox/issues/244

**Comment by happlebao** [comment]
The UI is less flickering now, because 05a7a00f2833b6517317efa2f2cf4b4de55668e3 made Wox faster.

**Comment by bao-qian** [comment]
Since this commit 6aae5afb19affe0122dc1318a073737e1b21f5d8, delay invoke has been deleted.
As discussed in commit 6aae5afb19affe0122dc1318a073737e1b21f5d8, this will make UI flickering more obvious, it need to be fixed ASAP.

**Comment by bao-qian** [comment]
https://onedrive.live.com/redir?resid=1452AAA400732A3D!99584&authkey=!AICkp0gs6UDzAAM&ithint=video%2cmp4

@qianlifeng The UI part is done. See the video I uploaded. :smile:

**Comment by happlebao** [comment]
Although UI is fixed, the score is seems problematic now.....

**Comment by bao-qian** [comment]
Since the there is a lock when update results.
There should be no more duplication, following issues should be fixed
https://github.com/Wox-launcher/Wox/issues/369
https://github.com/Wox-launcher/Wox/issues/265

**Comment by bao-qian** [comment]
After c57421a 661c485, I think this is completed fixed.
Could you test [it](https://ci.appveyor.com/project/qianlifeng/wox/history)?
@qianlifeng @lances101

**Comment by lances101** [comment]
I've been trying the latest builds, no more flickering so far.
