### ISSUE TITLE
使用windows11时会造成文件或者窗口拖拽卡顿

### ISSUE THREAD

**Issue by MRDOCTOROO** [Wox-launcher/Wox#3503]
To be able to help you we need enough information to find
what is causing your issue. Please follow the instructions 
and type the requested information where prompted. 

Please try reset Wox before continue, backup before you do.
Reset: delete `%APPDATA%\Wox`

Please delete unnecessary instructions after you finished your bug report.

**Describe the bug**
If you have an workaound or above workaround is working for you, 
please also describe it here.

**To Reproduce**
3. See error

**Expected behavior**

**Runtime info**
 - Windows 10 Version: 
 - Wox version

**Wox Error Window text**
Paste below the logs generated by the Wox error reporter.

**Screenshots**

drop and drop your screenshots here.

**Additional context**

**Detailed logs**
Please upload latest log file: 
`%APPDATA%\Wox\Logs\version\<date>.txt`
Please upload log as a whole file

drop and drop your latest log file here

**Comment by Hodpel** [comment]
找到了半个解决办法: 下载并安装最新版的PreRelease 然后使用无透明效果的版本(忍痛割爱啊呜呜)

**Comment by rcHoper** [comment]
win11dev版本更新10.0.22000.120后，wox终于不卡顿了，喜大普奔<(*￣▽￣*)/
