### ISSUE TITLE
Multiple action keywords

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#352]
- [x] merge Action Keyword Plugin and Exclusive plugin
- [x] merge isXXXPlugin and GetXXXPlugin
- [x] web search plugin should be modified
- [x] fix Fix PluginManagement plugin plugin and PluginIndicator plugin 

Related issues:
https://github.com/Wox-launcher/Wox/issues/124

**Comment by bao-qian** [comment]
This feature is partially done. WebSearch is the first plugin utilize this functionality.
But in order to set multiple action keywords, user needs to set both two places.
![tk5umnuth4dijwh1 7 cx 7](https://github-cloud.s3.amazonaws.com/assets%2F1169912%2F10958133%2F25033c82-8363-11e5-8c24-4fc220b06ff5.png)

This is because plugin has no access to `actionKeyword` from `SettingWindow.xaml`.
Any idea? @qianlifeng

**Comment by qianlifeng** [comment]
For web search plugin, we can set the action keyword to *, and let plugin itself to handle the websearch keyword. Ideally, plugin should know nothing about action keyword, because it can be changed by user at any time.
![image](https://cloud.githubusercontent.com/assets/1725475/10959224/13896b72-83b1-11e5-957f-3df087ee832e.png)

**Comment by bao-qian** [comment]
I figured out a way. It will be done tomorrow.
1.  if `plugin.metadata.ActionKeywords > 0` then `actionKeyword.Visbility = false`
2.  in `settingTab_SelectionChanged`, `customizedPluginConfig.ActionKeywords = metadata.ActionKeywords;`

**Comment by bao-qian** [comment]
In order to remove `IExclusive`, multiple action keywords is essential.

**Comment by bao-qian** [comment]
Done.

![u zhq n3sj bs t 7hz 5](https://cloud.githubusercontent.com/assets/1169912/10987752/3d2bd6ae-842e-11e5-823b-0cb1f62e3b4a.png)
![qhk4 h7 0ypf7yevxkpmx](https://cloud.githubusercontent.com/assets/1169912/10987772/5f01671c-842e-11e5-87e4-201ddfcf2fab.png)

Now, if a plugin wants to multiple action keywords, they should handle the ui by themselves.

**Comment by bao-qian** [comment]
The setting is not usable now
