### ISSUE TITLE
System.NullReferenceException when deleting all typed characters

### ISSUE THREAD

**Issue by ningfei** [Wox-launcher/Wox#356]
Just clone the repository and compile it.
1. launch Wox
2. type something
3. delete typed characters
4. after deleting the last character, Wox pops up the System.NullReferenceException error

**Comment by happlebao** [comment]
Could upload a screenshot?

**Comment by bao-qian** [comment]
@ningfei try again?

**Comment by bao-qian** [comment]
You could also try the Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

**Comment by ningfei** [comment]
Works now. Thanks!
