### ISSUE TITLE
Spotify Plugin Error

### ISSUE THREAD

**Issue by IrvingdeNoronha** [Wox-launcher/Wox#3571]
[2021-11-09.txt](https://github.com/Wox-launcher/Wox/files/7503177/2021-11-09.txt)

**Comment by gerab** [comment]
there are a lot of issues there, firstly you have to install python, that is what it says here:

ERROR|Wox.Core.Plugin.PluginsLoader|PythonPlugins|Python can't be found in PATH.

second: some plugins are outdated and not supported anymore. SpotifyAPI plugin is not related to this repository and probably has someone different as an author
