### ISSUE TITLE
Search Bar Startup Bug

### ISSUE THREAD

**Issue by rysci8** [Wox-launcher/Wox#3576]
**Description of bug**
Wox search bar still appears on startup in Windows 11, despite "Hide Wox on startup" box being checked in settings. 

**Runtime info**
 - Windows 11 OS build: 22000.318
 - Wox version: 1.4.1196

**Comment by darkzbaron** [comment]
Same in Win 10

**Comment by qianlifeng** [comment]
please see https://github.com/Wox-launcher/Wox/discussions/3937 and try v2
