### ISSUE TITLE
请问有计划更新一下release版本吗

### ISSUE THREAD

**Issue by Mixlining** [Wox-launcher/Wox#3596]
虽然项目并入微软powertoy，但是powertoy的bug还是不少，而且一些功能用不上，想要纯净的wox，不知大佬有计划更新一下release版本不？

**Comment by dearmark** [comment]
哦，原来是这样，我去试一下PowerToys Run

**Comment by WangJincheng4869** [comment]
的确 powertoy 还没有这个好用

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
