### ISSUE TITLE
Clear last command when re-active wox

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#36]
When I input a command and it executed. Next time i active wox, the command is still there. I must clear it by myself, which is not handy, I think.

I think every thime I active wox, it should be clean
Would you please think about it

**Comment by orzFly** [comment]
I think the box should not be cleared but all the text should be selected.

**Comment by qianlifeng** [comment]
@iEverX 

Like @orzFly said wox will not clear the last command when you active wox again. Instead, wox will select all command text. In this case, Both re-execute last command or start a new query should be convenient

**Comment by iEverX** [comment]
yeah, I did'nt notice that i could directly input my command. I got a mistake.

**Comment by lbergnehr** [comment]
I'm running the newest version and from what I can see, the text is not selected when I re-activate wox. Is this a regression?

**Comment by acicovic** [comment]
I have the same issue. Actually, I noticed that Wox remembers the last selection (try selecting some or all of the text, hide Wox, and when you relaunch it the text that you previously selected will be highlighted). I agree that the whole text should be selected when Wox is shown. I am running the latest pre-release (1.3.424)

**Comment by bensulli** [comment]
^^ This is my experience as well. Using Ctrl+Space as my shortcut if it matters.

**Comment by acicovic** [comment]
For me this worked after changing the option (try changing the option to something else and save it - then come back again and choose the desired one).

**Comment by bensulli** [comment]
No dice. Doesn't seem to matter if I changed it. Also tried a different hotkey.

**Comment by allxiao** [comment]
I had the same problem after initial install. The "Last Query Style" was set to "Select last Query" by default, but it didn't select the last query when I re-activate the launch box. I tried to change the "Last Query Style" option but nothing changed.

Then I closed the application and re-launched it and everything went back to normal. The last query behavior reflected to the settings correctly, and it updated accordingly when I changed the option.

**Comment by jzadra** [comment]
This is still a problem.

**Comment by kageurufu** [comment]
@jzadra I had this problem, but changing the `Last Query Style` in settings, and restarting Wox seemed to clear something out, and it started working again.

**Comment by golfymate** [comment]
I confirm 'Last Query Style' will reset the previous command.

What about right clicking and re-opening Wox?

![image](https://user-images.githubusercontent.com/77216655/174465604-ea18c4f3-7162-4263-955a-ec7c43cee70f.png)

It wont go back from this state.
