### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#360]
- [x] Wox.plugin should not be published to NuGet for every commits from mater because there are no changes in API. 
  - May be we could use a branch called api?
- [x] Chocolatey auto publish? (https://github.com/Wox-launcher/Wox/issues/213) - no
- [x] installer. This one is complicated, because we need to refactoring Wox to use `%APPDATA%` and resolve some UAC issues. (https://github.com/Wox-launcher/Wox/issues/283 , https://github.com/Wox-launcher/Wox/issues/267). Candidates are: wixtoolset, installshield and Squirrel.
- [x] move `logs`, `plugins`, `settings`, `caches` has been moved to `%APPDATA%
- [x] move <del>`themes`</del> and `wox\images` to `%APPDATA%` 
  Any more suggestions?

**Comment by qianlifeng** [comment]
I've created installer scripts [before](https://github.com/Wox-launcher/Wox/tree/master/Deploy/Installer), could we reuse that? we can change the install location to %APPDATA%

**Comment by bao-qian** [comment]
The installation location should be %ProgramFiles%, we should follow MS guideline. I really hate those applications try to install on my user folder.

**Comment by qianlifeng** [comment]
@happlebao  why did you hate that? could not find a way to uninstall? :smile:

**Comment by happlebao** [comment]
- [ ] Include .NET 4.5 with installer using installshield vs extension.

**Comment by lances101** [comment]
@happlebao, maybe you could take a look at [Squirrel](https://github.com/squirrel/squirrel.windows) instead of using something as bulky as InstallShield. 

**Edit**: although, maybe it is a bad idea because if there are problems with it, it will become an extra issue that has to be dealt with.

**Comment by mika76** [comment]
Program files is the right place to install, but any config files or downloaded plugins should actually go into the ProgramData folder. These days program files is protected and a pain to work with.

**Comment by kayone** [comment]
the nice thing about installing in user folder is that you don't need escalation to install/update the app, 

@mika76 `ProgramData` is actually the wrong place to store use specific settings since it's shared between all users, user specific data should be stored in `C:\Users\User\AppData`

**Comment by bao-qian** [comment]
Done! 
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.0
@mika76 @kayone @lances101

**Comment by mika76** [comment]
@happlebao Awesome! Could I make one tiny suggestion? Please don't name it setup.exe - so easy to lose in a download folder - have to keep renaming it. Sounds stupid, but so easy to fix 😊
