### ISSUE TITLE
Web search has different time usage

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#361]
From the release log:

2015-11-04 05:23:13.6975|INFO|Query For Web Searches : 5ms
2015-11-04 05:23:13.7276|INFO|Plugin Web Searches is executing instant search : 39ms

**Comment by bao-qian** [comment]
This time difference is caused by garbage collection when using `Timeit` and `API.PushResults`

**Comment by happlebao** [comment]
Force call `Dispose` is a really bad idea. Huge different!!!
Call `Dispose`:

Don't call `Dispose`:
Query For Web Searches : 0ms
Plugin Web Searches is executing instant search : 6ms

**Comment by bao-qian** [comment]
The results update part can't be optimized, but the `Dispose` method can be replaced by Lambda.
