### ISSUE TITLE
Can I resize the WOX searching box's Height, Width, Colour, Blurriness  and Roundness according to my preference?

### ISSUE THREAD

**Issue by hyzenberg22** [Wox-launcher/Wox#3620]
I am using "WOX" for 4 years...! It works absolutely charm. But I don't like the default size of the search window, I work on different screens and sometimes it looks big, and sometimes it looks small. **Is there any way to set the searching box height, width, and roundness according to the preference of the user**, obviously without crashing the software? If there please let me know. A step-by-step guide or youtube Video would be very much helpful.

I am attaching two files for my view, how the WOX should be, it looks more elegant. Besides the Black and white, their blur versions also would be more preferable.!
Thanks, WOX Team.

![demo 1](https://user-images.githubusercontent.com/43705275/149618379-87627d07-33d1-4c9c-8026-b7e6e8d3efa5.png)
![demo 2](https://user-images.githubusercontent.com/43705275/149618378-8f3b37e2-a8b0-470d-9131-b5c0ea67b67a.png)

**Comment by yar999** [comment]
> I am using "WOX" for 4 years...! It works absolutely charm. But I don't like the default size of the search window, I work on different screens and sometimes it looks big, and sometimes it looks small. **Is there any way to set the searching box height, width, and roundness according to the preference of the user**, obviously without crashing the software? If there please let me know. A step-by-step guide or youtube Video would be very much helpful.
> 
> I am attaching two files for my view, how the WOX should be, it looks more elegant. Besides the Black and white, their blur versions also would be more preferable.! Thanks, WOX Team.
> 
> ![demo 1](https://user-images.githubusercontent.com/43705275/149618379-87627d07-33d1-4c9c-8026-b7e6e8d3efa5.png) ![demo 2](https://user-images.githubusercontent.com/43705275/149618378-8f3b37e2-a8b0-470d-9131-b5c0ea67b67a.png)

Base.xaml file in Themes directory under Wox installation directory, Find Width,MaxWidth and modify it to the number you need, then exit wox and restart wox
