### ISSUE TITLE
wox 插件

### ISSUE THREAD

**Issue by Ln-G0179** [Wox-launcher/Wox#3622]
You can ask other general question here
wox官网是凉了吗，现在怎么安装插件啊

**Comment by ruslanmogilevskiy** [comment]
@bao-qian, is Wox abandoned?

**Comment by ruslanmogilevskiy** [comment]
seems the site is fixed

**Comment by qianlifeng** [comment]
> @bao-qian, is Wox abandoned?

see https://github.com/Wox-launcher/Wox/discussions/3937
