### ISSUE TITLE
The domain name "wox.one" has expired

### ISSUE THREAD

**Issue by steindvart** [Wox-launcher/Wox#3624]
I recently discovered that the site is not working. Reason: The domain name lease has expired.
> Check it: http://www.wox.one/

**Comment by ruslanmogilevskiy** [comment]
it`s fixed and working now

**Comment by steindvart** [comment]
Thank you, team!

**Comment by jhconning** [comment]
It seems that http://www.wox.one/ has expired again... Seems to happen each year about Jan 25 🤣
