### ISSUE TITLE
Wox.Infrastructure nuget package is published

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [Wox-launcher/Wox#3627]
For the sake of plugins development on .NET I've created and published the _Wox.Infrastructure_ assembly in a nuget package ([**link**](https://www.nuget.org/packages/Wox.Infrastructure)). Currently, the latest _v1.4.1196_ is listed there.
@bao-qian, please ping me if you would like to transfer the plugin's ownership to you.

**Comment by gerab** [comment]
that's nice, thanks. 
I think the author semi-abandoned the project and started something else. It's possible fanbase will have to move to another plugin repo in future if someone still cares. The current one hasn't seen any updates for years and I see people posting issues with Win11 in the description. There is really no alternative for me for this piece of software. I'll try to fix it at least for myself and I'm happy to see someone cares to =)

**Comment by ruslanmogilevskiy** [comment]
The alternative **could be** the PowerToys's PowerToys Run in the future (they copied the Wox.Pluging and .Infrastructure codebase completely to their repo), but it doesn't allow the external plugins to be installed as Wox does, only their own plugins are allowed to enable.
In this scope, WoX is much more flexible, sad that it seems abandoned.

**Comment by gerab** [comment]
I didn't know they were _that_ similar. Interesting if it's possible to overcome that 3rd party plugins limitations. Anyway, applications in their default state are far from [Alfred ](https://www.alfredapp.com/powerpack/#:~:text=Take%20Control%20With%20Alfred%20Workflows)extensibility and usability

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
