### ISSUE TITLE
No plugins could be installed

### ISSUE THREAD

**Issue by Grylios** [Wox-launcher/Wox#3632]
For 3 months I can't install any plugins, I reinstalled the program, I have Windows 7 32-bit.

Error id: 8e8ed667677841e1bb6da01421cad321

**Comment by ruslanmogilevskiy** [comment]
the author seems abandoned WoX, so post your complete error log here, maybe someone will help.

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
