### ISSUE TITLE
Can I use the up and down arrow keys to select the most recently entered keywords?

### ISSUE THREAD

**Issue by xwanlion** [Wox-launcher/Wox#3637]
I want to use up key(↑) and down key(↓) to select most recently inputs, but I can't.

**Comment by qianlifeng** [comment]
will support in v2

**Comment by qianlifeng** [comment]
Already implemented in https://github.com/Wox-launcher/Wox/commit/91a18e83739b22e58258c405d1fdb02768d854e0
