### ISSUE TITLE
希望提供禁止搜索uwp应用和系统设置的选项

### ISSUE THREAD

**Issue by scmaybee** [Wox-launcher/Wox#3638]
只想用来搜索指定目录下文件

**Comment by yar999** [comment]
程序插件那里把索引注册表的勾选去掉，只勾选索引开始菜单。只保留想要的快捷方式在开始菜单所在的目录就可以了

**Comment by yar999** [comment]
> 只想用来搜索指定目录下文件

程序插件那里把索引注册表的勾选去掉，只勾选索引开始菜单。只保留想要的快捷方式在开始菜单所在的目录就可以了

**Comment by scmaybee** [comment]
> > 只想用来搜索指定目录下文件
> 
> 程序插件那里把索引注册表的勾选去掉，只勾选索引开始菜单。只保留想要的快捷方式在开始菜单所在的目录就可以了

就是因为那儿取消勾选了还是会搜出来才找来的呀，系统是Win10 21H1企业版。
