### ISSUE TITLE
Expose Wox.Infrastructure instead of Wox.Plugin

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#364]
Right now, if a plugin needs to store it's settings, it can either reference [Wox.Infrastructure](https://github.com/Wox-launcher/Wox/tree/master/Wox.Infrastructure) or implement it's own way of storing them and then still, they are stored wherever. I don't think that is how things should be handled. 

I believe, the Plugin API should provide a way to store plugin settings. Wox should handle all the serialization/deserialization and store the settings in its folder (most-likely AppData). 

This is not in high priority, but definetly something that needs attention.

**Comment by bao-qian** [comment]
It is not so hard to expose `Wox.Infrastructure` to C# developer.
If we also want to expose `Wox.Infrastructure` to JSONRPC, things would be complicated.

**Comment by happlebao** [comment]
Things needs speed up, as this is essential for [multiple action keyword](https://github.com/Wox-launcher/Wox/issues/352).

**Comment by luisrudge** [comment]
Is there any work being done with this?

**Comment by bao-qian** [comment]
I'm pretty busy this week. Hopefully next week.

**Comment by bao-qian** [comment]
use #537
