### ISSUE TITLE
Settings plugin disabled and tray icon off

### ISSUE THREAD

**Issue by FriGiN** [Wox-launcher/Wox#3647]
i messed up my settings by setting the plugin off and the tray icon off is there a command i can type to open it up again without reinstalling i have a lot of customizations in the app and dont want to lose them.

**Comment by luizhcgoncalves** [comment]
I've just had the same problem, but couldn't find any answer for it. However, I searched for every Wox folder to find the settings file in `C:/Users/<user>/AppData/Roaming/Wox/Settings/Settings.json` and there I changed keys `HideOnStartup` and `HideNotifyIcon` to `false`. Restarted the app, and bingo! Tray icon is back, so is the settings window. For some reason, every time I try to search for Wox Settings it seems weird trying to guess the word until I give up. "Wox Settings" probably should call it too

**Comment by qianlifeng** [comment]
please see #3937 and try v2
