### ISSUE TITLE
set key world

### ISSUE THREAD

**Issue by alctny** [Wox-launcher/Wox#3648]
**Is your feature request related to a problem? Please describe.**
1. 我想要打開 **Visual Studio Code** 但其安裝后的啓動文件是 **Code.exe** 所以無法通過輸入 **code** 來啓動,并且我更希望能輸入 **vscode** 來啓動,而不是每次都需要輸入 **Code.exe**
2. 我想要打開一個叫做 **baidu** 的資料夾,但是我電腦上存在多個叫做 **baidu** 的資料夾,并且我希望的結果總是靠後
3. 部分想要打開的文件或軟件名稱較長,與 **vscode** 相似只有在輸入足夠的關鍵字之後才能檢索到結果
4. 免安裝軟件需要匹配更多的文字才能,大部分情況都需要輸入後綴才能匹配到結果
> PS: 只輸入 **Code** 同樣無法檢索到結果,需要至少輸入 **Code.e** 才能查詢到結果.

**Describe the solution you'd like**
通過設置關鍵字即可通過關鍵字來啓動指定的軟件或者資料夾,既不會出現歧義也可以擁有更高的自定義方式

**Describe alternatives you've considered**
為軟件創立快捷方式,通過搜索快捷方式代替搜索軟件本身

**Additional context**
![無法檢索到結果](https://user-images.githubusercontent.com/44720162/157999112-c4ddf981-8938-457e-831a-1b0db6eda41a.png)

**Comment by qianlifeng** [comment]
please try "Query shortcuts" in v2
