### ISSUE TITLE
Wox Plugins

### ISSUE THREAD

**Issue by AdamElitzur** [Wox-launcher/Wox#3662]
Hi, Wox plugins seem really cool, kind of like the PC version of Raycast, which I really want, but I don't know how to make the plugins. I did a ton of research, and it's very unclear. Do you have to make a Github Repo for it or install a package?  When I duplicate an existing plugin and make a small change, Wox doesn't even recognize it and it doesn't show up in the plugins. I want to learn how to make them in Python, any tips? Thanks!

**Comment by cpkio** [comment]
You have Hello world plugin samples in C# and Python installed automatically.
