### ISSUE TITLE
如何修改everything搜索结果的最大显示数量/ How to change the max count of the results provided by Everything plugin

### ISSUE THREAD

**Issue by hxhc** [Wox-launcher/Wox#3666]
在使用wox搜索文件时，比如搜索 “pdf”，会给出约30个检索结果，但直接用everything搜索的话，显示有10000多条检索结果。

我下载源码后，修改了`Wox-1.4.1196\Plugins\Wox.Plugin.Everything\Settings.cs`文件中的`DefaultMaxSearchCount`为999后，生成解决方案，发现新的程序检索结果仍只有30条左右，请问还需要修改哪些地方？谢谢！

When using Wox to search files, say typing 'pdf', it shows about 30 items. But when directly using Everything, it gives about 100000 items. 

So I tried to change the `Wox-1.4.1196\Plugins\Wox.Plugin.Everything\Settings.cs` file, and set `DefaultMaxSearchCount` from 30 to 999. However, there are still about 30 items. What files and variables should change? I would thanks a lot if you could provide some help.

**Comment by Andrew313-ice** [comment]
请问我为什么没找到那个.cs文件？是需要自己创建吗

**Comment by hxhc** [comment]
> 请问我为什么没找到那个.cs文件？是需要自己创建吗

@Andrew313-ice
不是啊，源码中有的啊`Wox-1.4.1196/Plugins/Wox.Plugin.Everything/Settings.cs`

**Comment by Andrew313-ice** [comment]
哦哦哦~，okay，谢谢答复！
________________________________
发件人: hxhc ***@***.***>
发送时间: 2022年4月12日 14:44
收件人: Wox-launcher/Wox ***@***.***>
抄送: Andrew ***@***.***>; Comment ***@***.***>
主题: Re: [Wox-launcher/Wox] 如何修改everything搜索结果的最大显示数量/ How to change the max count of the results provided by Everything plugin (Issue #3666)


请问我为什么没找到那个.cs文件？是需要自己创建吗

不是啊，源码中有的啊Wox-1.4.1196/Plugins/Wox.Plugin.Everything/Settings.cs

―

**Comment by 1907010218** [comment]
你好，请问找到解决方案了吗？wox中搜索的结果数远少于everything的结果数，导致没找到需要的目录。

**Comment by Andrew313-ice** [comment]
Wox-1.4.1196/Plugins/Wox.Plugin.Everything/Settings.cs中可以修改最大显示数量。

不过我好久没用这个软件了，不知道还有没有用

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: 1907010218 ***@***.***>
发送时间: Tuesday, June 4, 2024 12:06:57 AM
收件人: Wox-launcher/Wox ***@***.***>
抄送: Andrew ***@***.***>; Mention ***@***.***>
主题: Re: [Wox-launcher/Wox] 如何修改everything搜索结果的最大显示数量/ How to change the max count of the results provided by Everything plugin (Issue #3666)


你好，请问找到解决方案了吗？wox中搜索的结果数远少于everything的结果数，导致没找到需要的目录。

―

**Comment by 1907010218** [comment]
好的，谢谢啦

**Comment by 1907010218** [comment]
好的，谢谢

**Comment by hxhc** [comment]
> 好的，谢谢

我现在用[flow launcher](https://www.flowlauncher.com/),这个默认显示100个，可以完全替代了

**Comment by 1907010218** [comment]
我去用一下试试，谢谢
