### ISSUE TITLE
Can't install plugin under windows 8.1

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#37]
os: Windows 8.1 64bit
version: 1.0 beta

After click "enable plugin installer" in setting:
![enable_plugin_installer](https://f.cloud.github.com/assets/1169912/2432363/8d37a45c-ad61-11e3-9632-2a21e134b4d2.png)

Crash:

![untitled](https://f.cloud.github.com/assets/1169912/2432199/5b2d47bc-ad59-11e3-8c38-67646d121e42.png)

**Comment by ntwb** [comment]
I had no issues installing Wox 1.0 beta on x64 Windows 8.1
![wox-x64win81](https://f.cloud.github.com/assets/1016458/2432352/19c4a22c-ad61-11e3-9df0-b71879b25b8b.PNG)

**Comment by bao-qian** [comment]
@ntwb 
Hi, I can running Wox, I just mean I can't install **plugin**.

**Comment by john990** [comment]
I also have same problem on windows 7.

**Comment by orzFly** [comment]
@kai-wang-john @happlebao I am so sorry that we forgot the "Wox.UAC.exe" file in the package. I will fix this problem soon.

**Comment by orzFly** [comment]
@kai-wang-john @happlebao The package has been reuploaded. Please check it out.
