### ISSUE TITLE
Resizable search bar

### ISSUE THREAD

**Issue by Suharda-Silva** [Wox-launcher/Wox#3707]
**Is your feature request related to a problem? Please describe.**
The search bar is too bulky and too bit. It covers most of the screen when popped up and hinders the UX.

**Describe the solution you'd like**
Give the user to choose the sizes from a few options like a small, medium (default) and large  (what currently is).

**Describe alternatives you've considered**
Provide a custom option to define a desired width and height.

**Additional context**
None

**Comment by qianlifeng** [comment]
Sorry, but search bar is designed to be un-resizable
