### ISSUE TITLE
Delegating unsupported plugins?

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#371]
Many plugins are abandoned by their developers. Could we come up with a way to delegate the plugin to another user or at least a way to flag the plugin as broken so that it does not popup in wpm?

For example, [the translation plugin](https://www.getwox.com/plugin/38) has not been updated for a long time and is broken. I am using it myself and [updated it](http://discussion.getwox.com/t/translation-plugin/117/12). I would upload a new version of the Translate plugin, but that would pop-up two versions in wpm. 

I know that this is not a priority right now, but still, a way to handle this would be great.

**Comment by bao-qian** [comment]
That depends on @qianlifeng.
Maybe he will have some spare time to move the plugin part into this organization.

**Comment by qianlifeng** [comment]
What did you mean "move the plugin part into this organization", I can just move my plugin into here, but for other user created plugins, we need to get the permission from them to move their repo into this organization if they will.

**Comment by lances101** [comment]
@happlebao I think the easier way to go with this would be to be able to make broken plugins hidden/inactive through `wpm` & _getwox.com_ until they get updated. Again, this is not something there is a rush for, but this will become a worry once 1.2.0 rolls out.

**Comment by bao-qian** [comment]
@qianlifeng I mean the plugin part of the [website](https://www.getwox.com/plugin).
We can add some functionality into the website, like @lances101 said, a outdated flag.

Also I think all plugins should be open sourced (e.g. give the url for their github repo), so somebody can maintain it if the author abandon the plugin.

**Comment by bao-qian** [comment]
@lances101 1.2.0 won't change any existing published API. 1.3 will, but I think it won't happen in this year.
