### ISSUE TITLE
Suggestion: reset right click

### ISSUE THREAD

**Issue by golfymate** [Wox-launcher/Wox#3711]
1. I right click an app/folder
![image](https://user-images.githubusercontent.com/77216655/172025097-0ddf6c6a-db8b-4046-8fdd-68c4a4b1e7da.png)

2. Click any option
![image](https://user-images.githubusercontent.com/77216655/172025115-6a30260f-a32f-42ee-824d-bb1b723065a2.png)

3. Next time I open the launcher, the menu will still be at "right click" status in Picture 2. (open as admin, folder path etc...)

So **I have to right click again** to go back to default and be able to search another App.

I'd like to add a return back to default menu without right clicking again to go back to Apps.

**Comment by golfymate** [comment]
bump

**Comment by qianlifeng** [comment]
there is no context menu in v2
