### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by illiawolkow** [Wox-launcher/Wox#3717]
I tried resetting/reinstalling wox

Blurry text/sharp edges
Same was happening on windows 10 with wox but everywhere else text is clean

**Runtime info**
 - Windows 11 Pro 21H2 Build:22000.708 
 - Wox version 1.4.1196

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/78424567/173532342-fd6ed959-211f-45c6-921f-cfcc6dd31663.png)
![Screenshot_11](https://user-images.githubusercontent.com/78424567/173532380-e638c471-f4a7-41fb-b3a7-6d187c817f5e.png)

**Additional context**
text is not clean only in wox

**Detailed logs**
[2022-06-14.txt](https://github.com/Wox-launcher/Wox/files/8898006/2022-06-14.txt)

**Comment by qianlifeng** [comment]
please see #3937 and try v2
