### ISSUE TITLE
空格展示历史搜索记录

### ISSUE THREAD

**Issue by M142857** [Wox-launcher/Wox#3721]
如题。

所有搜索类的场景里，历史搜索记录还是挺常用的吧，手机上SearchEVO就有。建议增加该功能。

目前也没看到相关的插件，还是做到设置里比较好。

设置当中的上次搜索关键字模式，只能展示/不展示最近的一次搜索记录，不够全，比如经常要执行的一些命令，以及用搜索引擎搜索的记录。

这样也解决了[希望不要保留上次的搜索关键字 #1181](https://github.com/Wox-launcher/Wox/issues/1181)这个问题。

**Comment by qianlifeng** [comment]
会在[#3842](https://github.com/Wox-launcher/Wox/issues/3842)中跟踪
