### ISSUE TITLE
my wox problem

### ISSUE THREAD

**Issue by TheParzivall** [Wox-launcher/Wox#3737]
Wox, calculator etc. I can't get into control panel while using it.

I am using windows 11. 
I can't find the control panel I'm looking for as seen in the picture 

![Screenshot_1](https://user-images.githubusercontent.com/108283801/175965523-0a1be26a-a595-4406-81be-af6b0968f50f.png)
![Screenshot_2](https://user-images.githubusercontent.com/108283801/175965530-e3e80e8d-5f48-4750-9cd5-feb1a31c9677.png)

[url=https://www.hizliresim.com/b83k49v][img]https://i.hizliresim.com/b83k49v.png[/img][/url]
[url=https://www.hizliresim.com/q66c2j0][img]https://i.hizliresim.com/q66c2j0.png[/img][/url]

**Comment by BySuspect** [comment]
wox ayarlarından dili türkçe yapmayı dene.
veya dil deiştir tekrar dene

**Comment by TheParzivall** [comment]
I tried and still have the same problem

**Comment by qianlifeng** [comment]
see #3937
