### ISSUE TITLE
Batch install plugins

### ISSUE THREAD

**Issue by ishu3101** [Wox-launcher/Wox#374]
Please add the ability to Install Wox Plugins from the Command Line.

**Comment by qianlifeng** [comment]
you can use WPM plugin

**Comment by bao-qian** [comment]
The command line function is not the focus for current development(1.2)

**Comment by bao-qian** [comment]
What's the usage scenario for this? You can always use wpm

**Comment by ishu3101** [comment]
Having a package manager for Wox like [chocolatey for windows](https://chocolatey.org/) that you could also run from the command line would let you install/uninstall Wox plugins from the command line and automate installation of plugins using scripts.

When you have a fresh installation of Wox and trying to install all the plugins that you use.
Another scenario, is being able to easily install all the plugins that you may use in a team.
for eg: running `wpm install hackernews weather caniuse diskspace timezone` would install the plugins **Hacker News, Weather, CanIUse, DiskSpace and Timezone** without requiring any input from the user.

**Comment by bao-qian** [comment]
In order install same plugins for your team, just copy the `Plugins` folder to every machine.

**Comment by cmeyertons** [comment]
+1 - typically have a `choco install` script when setting up a new machine, would be nice to be able to do this w/ wox
