### ISSUE TITLE
Consistent installation across multiple users - Feature Request

### ISSUE THREAD

**Issue by CookieSalesman** [Wox-launcher/Wox#3740]
**I tried installing Wox for multiple (many) users on one single computer.**
However, upon trying to install it for a second or third person, often what happens is that the Wox installer asks to uninstall itself. So I do. And then I reinstall.

I believe that the problem may be because Wox installs to %appdata% and not Program Files.

And also, sometimes I run into installation problems related to everything. Although that is not your problem at all.

**Help to explain how I should best install Wox for multiple users**
I thought that most programs, once installed to Program Files, are visible for all users.

**The installation and troubleshooting process is slightly complicated for multiple users**
I do want to point out that half of the issues have been related to installing everything (not related), although in general it does  not help that installing Wox immediately for a 2nd or 3rd or 4th user usually asks me to uninstall Wox. I wonder if this is what ends up causing problems with Everything.

**Comment by qianlifeng** [comment]
sorry for inconvenience, there is no plan for multiple user installation now
