### ISSUE TITLE
What is the plan for new release version

### ISSUE THREAD

**Issue by firemiles** [Wox-launcher/Wox#375]
The last release version is long time ago，do you have a release plan for new version

**Comment by bao-qian** [comment]
The current development is mainly done by myself.
The stable version of v1.2 will be release in 1-2 month.
You can track it [here](https://github.com/Wox-launcher/Wox/issues?q=is%3Aopen+is%3Aissue+milestone%3AV1.2.0)
1. ability to search UWP app.
2. faster query time (near instant now), faster startup time(1.2s->0.9s in my machine)
3. smooth, no more UI flickering
4. better code quality, less lines of code (1k deleted)

**Comment by firemiles** [comment]
Thanks

**Comment by bao-qian** [comment]
@firemiles you can also try Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
