### ISSUE TITLE
you can keep order now, please use new version and set `KeepResultRawScore` in plugin metadata

### ISSUE THREAD

**Issue by 42useGitHub** [Wox-launcher/Wox#3753]
you can keep order now, please use new version and set `KeepResultRawScore` in plugin metadata

https://github.com/Wox-launcher/Wox/pull/2834/files

_Originally posted by @bao-qian in https://github.com/Wox-launcher/Wox/issues/1911#issuecomment-633850246_

how to make it on my own computer to "set KeepResultRawScore"

I can not find any config-like file in my wox directory that I can "set KeepResultRawScore"

**Comment by qianlifeng** [comment]
we have this feature in v2
