### ISSUE TITLE
Help with searching windows apps

### ISSUE THREAD

**Issue by Admrial1989** [Wox-launcher/Wox#3755]
Hi. 
I have been using Wox for a few years now but have never been able to search for Microsoft Apps that I have downloaded from the Microsofr App Store.
I am running Windows 11 Pro, Wox version 1.4.119
I've attached the settings I have for program search

Thanks!

![wox program search settings](https://user-images.githubusercontent.com/110466218/182363737-f23b9f52-1d5b-4279-bee0-e5d73762365f.jpg)

![search calculator wox](https://user-images.githubusercontent.com/110466218/182363491-3b9057b7-a8c6-4f07-8df5-ae6e707c3ce4.jpg)
6

**Comment by Cycier** [comment]
In do have the same problem, I cant find Spotify or OneNote for windows 10 in Wox, even though it shows up as an app and is  installed. 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/93426195/189434643-4f119b14-47b7-4619-96cb-3cd97bf506e2.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/93426195/189434688-7747a484-415c-4229-9144-7032d3e64a3c.png">

**Comment by Cycier** [comment]
Update, been working on it for a short period of time, if you really desperately want to be able to add those apps to wox, just find the exe file in your C:/ Folder and add it as Location to search for programs.
