### ISSUE TITLE
Including more web search by default

### ISSUE THREAD

**Issue by ishu3101** [Wox-launcher/Wox#376]
Is there any possibility of including more web searches by default in a fresh installation of Wox like in Alfred on the Mac?

Here are some of the web searches that I believe users will benefit having included in Wox when they install Wox.
- Facebook
- Twitter
- Wikipedia
- Duckduckgo
- Google Maps
- Google Image
- Google Translate
- Gmail
- Google Drive
- Github
- Amazon
- Ebay
- Youtube

**Comment by bao-qian** [comment]
For now, you can manually add it like:
![lw cwf sz 1pe lmj4xy_a](https://cloud.githubusercontent.com/assets/1169912/11018693/993a71d0-85cd-11e5-92e2-5eb9d135cc8a.png)
1. Download Latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
2. Then go to `Plugins\Wox.Plugin.WebSearch` copy the the content of `setting.json` and paste it here.

**Comment by ishu3101** [comment]
Here is the **settings.json** file

```
{
  "WebSearches": [
    {
      "Title": "Google",
      "ActionWord": "g",
      "IconPath": "Images\\websearch\\google.png",
      "Url": "https://www.google.com/search?q={q}",
      "Enabled": true
    },
    {
      "Title": "Wikipedia",
      "ActionWord": "wiki",
      "IconPath": "Images\\websearch\\wiki.png",
      "Url": "http://en.wikipedia.org/wiki/{q}",
      "Enabled": true
    },
    {
      "Title": "FindIcon",
      "ActionWord": "findicon",
      "IconPath": "Images\\websearch\\pictures.png",
      "Url": "http://findicons.com/search/{q}",
      "Enabled": true
    },
    {
      "Title": "facebook",
      "ActionWord": "facebook",
      "IconPath": "Images\\websearch\\facebook.png",
      "Url": "http://www.facebook.com/search/?q={q}",
      "Enabled": true
    },
    {
      "Title": "twitter",
      "ActionWord": "twitter",
      "IconPath": "Images\\websearch\\twitter.png",
      "Url": "http://twitter.com/search?q={q}",
      "Enabled": true
    },
    {
      "Title": "google maps",
      "ActionWord": "maps",
      "IconPath": "Images\\websearch\\google.png",
      "Url": "http://maps.google.com/maps?q={q}",
      "Enabled": true
    },
    {
      "Title": "google translate",
      "ActionWord": "translate",
      "IconPath": "Images\\websearch\\google_translate.png",
      "Url": "http://translate.google.com/#auto|en|{q}",
      "Enabled": true
    },
    {
      "Title": "duckduckgo",
      "ActionWord": "duckduckgo",
      "IconPath": "Images\\websearch\\duckduckgo.png",
      "Url": "https://duckduckgo.com/?q={q}",
      "Enabled": true
    },
    {
      "Title": "wolframalpha",
      "ActionWord": "wolframalpha",
      "IconPath": "Images\\websearch\\wolframalpha.png",
      "Url": "http://www.wolframalpha.com/input/?i={q}",
      "Enabled": true
    },
    {
      "Title": "github",
      "ActionWord": "github",
      "IconPath": "Images\\websearch\\github.png",
      "Url": "https://github.com/search?q={q}",
      "Enabled": true
    },
    {
      "Title": "github gist",
      "ActionWord": "gist",
      "IconPath": "Images\\websearch\\gist.png",
      "Url": "https://gist.github.com/search?q={q}",
      "Enabled": true
    },
    {
      "Title": "gmail",
      "ActionWord": "gmail",
      "IconPath": "Images\\websearch\\gmail.png",
      "Url": "https://mail.google.com/mail/ca/u/0/#apps/{q}",
      "Enabled": true
    },
    {
      "Title": "google drive",
      "ActionWord": "drive",
      "IconPath": "Images\\websearch\\google_drive.png",
      "Url": "http://drive.google.com/?hl=en&tab=bo#search/{q}",
      "Enabled": true
    },
    {
      "Title": "stackoverflow",
      "ActionWord": "stackoverflow",
      "IconPath": "Images\\websearch\\stackoverflow.png",
      "Url": "http://stackoverflow.com/search?q={q}",
      "Enabled": true
    }
  ],
  "EnableWebSearchSuggestion": false,
  "WebSearchSuggestionSource": "Google"
}
```

**Comment by bao-qian** [comment]
Excellent! Please also give a link for the **icons** (e.g. `Images\\websearch\\stackoverflow.png` you use for different search engines.

**Comment by ishu3101** [comment]
You can find all the icons as well as the **settings.json** at https://github.com/ishu3101/Wox.Plugin.WebSearch

**Comment by bao-qian** [comment]
@ishu3101 sorry for delay, I'm recently busy to find a graduate job.

**Comment by 1Mark** [comment]
Hi, I realised all these have been added thats great. However, Google images was left out?

Anyway I managed to add it by using this.
`https://www.google.co.uk/search?q={q}&source=lnms&tbm=isch&sa=X&ved=0ahUKEwik786W1q7TAhVKBMAKHQBjA00Q_AUICCgB&biw=1440&bih=780`

**Comment by germanoeich** [comment]
@1Mark The important URL parameter is &tbm=isch, so the correct URL without any extra info would be
`https://www.google.com/search?q={q}&tbm=isch`

**Comment by germanoeich** [comment]
Also @happlebao

**Comment by 1Mark** [comment]
@germanoeich Although I realised the one you mentioned is a bit slower? In terms of receiving a response from Google Images.

**Comment by germanoeich** [comment]
@1Mark Looks like a redirect is performed at the link I posted above, but it should not have a significant performance impact on Wox. Latency issues may apply as that is the US google address. But IMO it's better than sending random tokens to google with what seems to be user information.
