### ISSUE TITLE
Way to exclude global program search

### ISSUE THREAD

**Issue by krisu5** [Wox-launcher/Wox#378]
I only want to search programs from specific folders, not to search all programs in the system.

**Comment by bao-qian** [comment]
For what usage scenario you want to do this?

**Comment by krisu5** [comment]
Well, when I used Launchy for years, I had one folder for program shortcuts and one for game shortcuts. I used this to only include programs that I wanted to search through Launchy. There’s option to put optional shortcut folders to Wox, but no way to use **only** those folders that I saw.

**Comment by bao-qian** [comment]
Please try latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).
![mokj9c tklks 6g28 htoje](https://cloud.githubusercontent.com/assets/1169912/11021968/20b22dca-864a-11e5-82cb-500ce91e5dfc.png)

**Comment by krisu5** [comment]
Yeah, that I meant :)

**Comment by bao-qian** [comment]
Please continue provide feedback and bug reports in the future.
