### ISSUE TITLE
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new 1. upload log file: C:\Users\12448\AppData\Roaming\Wox\Logs\1.3.524\2022-09-28.txt 2. copy below exception message  Wox version: 1.3.524 OS Version: Microsoft Windows NT 10.0.19044.0 IntPtr Length: 8 x64: True

### ISSUE THREAD

**Issue by JohnChen1997** [Wox-launcher/Wox#3784]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\12448\AppData\Roaming\Wox\Logs\1.3.524\2022-09-28.txt
2. copy below exception message

Wox version: 1.3.524
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\12448\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 09/28/2022 15:49:21
Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 System.Windows.Clipboard.SetDataInternal(String format, Object data)
   在 Wox.Plugin.Everything.Main.<>c__DisplayClass6_1.<Query>b__1(ActionContext _) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 101
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 146
   在 System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   在 System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by naxl** [comment]
The crash seems to me internal and system dependent.
