### ISSUE TITLE
Win10下，中文输入法，直接Crash

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#379]
操作系统：Microsoft Windows [Version 10.0.10240]
输入法：QQ拼音纯净版

![image](https://cloud.githubusercontent.com/assets/9709390/11025837/b32b029e-86db-11e5-9f97-22720d76864d.png)

**Comment by bao-qian** [comment]
哪个版本？
试一下最新 build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

**Comment by clayzx** [comment]
github版本：\* c60cdcd - Update readme (23 hours ago) <happlebao>

**Comment by clayzx** [comment]
下载的1.2.0.544不会出现这个问题，是我自己编译的问题还是此BUG已经修复了？

**Comment by bao-qian** [comment]
应该是你编译问题。想尝新去下最新build就好了。

**Comment by clayzx** [comment]
请问一下，要怎么编译呢？ 我用的VS2015编译的，没有任何更改！

还有是否能麻烦大大回复一下这个帖子：
http://discussion.getwox.com/t/vs2015/164

谢谢~~~~~

**Comment by bao-qian** [comment]
1. 可能是master那个[ui flickering](https://github.com/Wox-launcher/Wox/issues/350)的问题，在dev中修了。现在合并了。
2. 可能你选了Debug。VS2015-》Release-》Ctrl+F5

那个论坛即将关闭。以后有问题来这问。
那些是c#6的语法糖。
反正vs2015免费，且支持win7/8/10。升级就是了。
