### ISSUE TITLE
Program not working under Win8.1 SP1 x64

### ISSUE THREAD

**Issue by xt-near** [Wox-launcher/Wox#38]
## Error message :

Wox has an error that can't be handled. System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。

   在 System.Windows.Controls.VirtualizingStackPanel.InsertContainer(Int32 childIndex, UIElement container, Boolean isRecycled)

   在 System.Windows.Controls.VirtualizingStackPanel.AddContainerFromGenerator(Int32 childIndex, UIElement child, Boolean newlyRealized)

   在 System.Windows.Controls.VirtualizingStackPanel.BringIndexIntoView(Int32 index)

   在 System.Windows.Controls.ListBox.OnBringItemIntoView(Object arg)

   在 System.Windows.Controls.ListBox.ScrollIntoView(Object item)

   在 Wox.ResultPanel.lbResults_SelectionChanged(Object sender, SelectionChangedEventArgs e)

   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   在 System.Windows.Controls.ListBox.OnSelectionChanged(SelectionChangedEventArgs e)

   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()

   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(Object item, Boolean assumeInItemsCollection)

   在 System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)

   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, OperationType operationType)

   在 System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, OperationType operationType, Boolean isInternal)

   在 System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)

   在 System.Windows.Controls.Primitives.Selector.set_SelectedItem(Object value)

   在 Wox.ResultPanel.Select(Int32 index)

   在 Wox.ResultPanel.SelectFirst()

   在 Wox.ResultPanel.AddResults(List`1 results)

   在 Wox.MainWindow.<OnUpdateResultView>b__e()

   --- 内部异常堆栈跟踪的结尾 ---

   在 System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)

   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)

   在 System.Delegate.DynamicInvokeImpl(Object[] args)

   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)

   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()

   在 System.Threading.ExecutionContext.runTryCode(Object userData)

   在 System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   在 System.Windows.Threading.DispatcherOperation.Invoke()

   在 System.Windows.Threading.Dispatcher.ProcessQueue()

   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)

   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)

   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   在 System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)

   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   在 System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)

   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)

   在 System.Windows.Threading.Dispatcher.Invoke(Delegate method, Object[] args)

   在 Wox.MainWindow.<OnUpdateResultView>b__d(String k)

   在 Wox.DispatcherExtensions.<>c__DisplayClass2.<DelayInvoke>b__0(Object s, EventArgs e)

   在 System.Windows.Threading.DispatcherTimer.FireTick(Object unused)

   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)

   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()

   在 System.Threading.ExecutionContext.runTryCode(Object userData)

   在 System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)

   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   在 System.Windows.Threading.DispatcherOperation.Invoke()

   在 System.Windows.Threading.Dispatcher.ProcessQueue()

   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)

   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Boolean isSingleParameter)

   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   在 System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(MSG& msg)

   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   在 System.Windows.Application.RunInternal(Window window)

   在 Wox.SingleInstanceManager.OnStartup(StartupEventArgs e)

   在 Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

   在 Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)

   在 Wox.EntryPoint.Main(String[] args)

**Comment by qianlifeng** [comment]
Couldn't reproduce now. But it should an error here. 9c1fba3d79ac873c6e66f7b31781fadeb86c78c9
