### ISSUE TITLE
Win10下，用QQ截屏后，WOX全黑！

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#380]
操作系统：Microsoft Windows [Version 10.0.10240]

重现步骤：
1. 快捷键呼出Wox
2. 随便输入关键字（显示出结果列表）
3. 按QQ的截屏快捷键开始截屏
4. 取消或完成截图
5. 出现全黑状态
6. 隐藏后再呼出Wox又恢复正常

![image](https://cloud.githubusercontent.com/assets/9709390/11025917/ff8d9632-86dc-11e5-9dad-e7f65131e4c5.png)

**Comment by bao-qian** [comment]
哪个版本？
试一下最新 build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history) (top green build -> artifacts -> release-binary.zip).

我的是可用的。
![af7b yg7d e j b4wu2r qx](https://cloud.githubusercontent.com/assets/1169912/11025940/49c9aa08-869a-11e5-9036-15922d42e51f.png)

**Comment by bao-qian** [comment]
@clayzx 这一个问题也没有了是吗？
