### ISSUE TITLE
Nobody is fixing bugs.

### ISSUE THREAD

**Issue by ThePython10110** [Wox-launcher/Wox#3801]
**Describe the bug**
Nobody is fixing bugs. I've seen at least 10 copies (and there are probably more) of the EXACT SAME BUG. I am not currently experiencing any bugs... but other people are. 

**To Reproduce**
1. Report an issue
2. Wait months for it to get fixed
3. Nothing.

**Expected behavior**
There should be some indication that Wox has been abandoned or something... Either that, or someone should be paying attention to the 923 issues that currently exist.

**Comment by noah-severyn** [comment]
@ThePython10110 that's because this has pretty much been merged into [PowerToys Run](https://learn.microsoft.com/en-us/windows/powertoys/run).

**Comment by SysC0mp** [comment]
You can also checkout [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher). The project is based on WOX and is actively maintained.

**Comment by ThePython10110** [comment]
I knew PowerToys Run was based on Wox, but not that Wox had actually been merged into it (maybe that should be in the readme for Wox?).
Flow launcher looks great, though. It's got more features than PT Run.
