### ISSUE TITLE
搜索不到微信

### ISSUE THREAD

**Issue by a-little-like** [Wox-launcher/Wox#3803]
![image](https://user-images.githubusercontent.com/73223838/200152914-3b796741-76be-454e-8e9c-8cae5621803b.png)
如图，无法搜索到微信，希望可以添加一个功能：自定义搜索关键词，然后搜索结果为自己定义好的文件或路径。
希望可以得到回复。

**Comment by Henrycheheng** [comment]
![image](https://user-images.githubusercontent.com/48849602/200828175-22158f2b-58de-4247-bbfc-1949a63905c0.png)
it works well!

**Comment by Sinyeee** [comment]
微信叫WeChat，你搜WeChat试试？
![image](https://user-images.githubusercontent.com/99778757/210522646-c3550a1a-d4bb-4b13-8c29-044fb0028a5f.png)

**Comment by Sinyeee** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
