### ISSUE TITLE
GitBook中指向的链接过时。

### ISSUE THREAD

**Issue by kongtianyi** [Wox-launcher/Wox#3818]
注意到当前官网是http://wox.one, 但文档中指向的链接还都是https://www.getwox.com

**Comment by kongtianyi** [comment]
例如这边文档末尾的插件库链接，http://doc.wox.one/zh/plugin/python_plugin.html

**Comment by qianlifeng** [comment]
以后文档/插件/主题商店全部都会放在github, 不会依赖开发者的网站托管, 确保Wox不依赖于开发者.
