### ISSUE TITLE
no Wox.Plugin.CMD in the plugin list

### ISSUE THREAD

**Issue by ningfei** [Wox-launcher/Wox#382]
tried the lastest build from appveyor, also built wox myself, in both cases, under the plugin setting tab, there's not "shell" (Wox.Plugin.CMD), weird...I just notice this recently, it used to work fine in 1.2.0 beta from github release page

**Comment by bao-qian** [comment]
Hi, The problem maybe the action keyword settings of config.
Please paste your `Plugins\Wox.Plugin.CMD\plugin.json` and `Config\config.json`

**Comment by ningfei** [comment]
Hi, the one from appveyor also has this problem, I didn't see any suspectable setting in the json. here it is:

<code>Config\config.json</code>
<code>{
  "DontPromptUpdateMsg": false,
  "ActivateTimes": 3,
  "EnableUpdateLog": false,
  "Hotkey": "Alt + Space",
  "Language": "en",
  "Theme": "Dark",
  "QueryBoxFont": "Microsoft Sans Serif",
  "QueryBoxFontStyle": "Normal",
  "QueryBoxFontWeight": "Normal",
  "QueryBoxFontStretch": "Normal",
  "ResultItemFont": "Microsoft Sans Serif",
  "ResultItemFontStyle": "Normal",
  "ResultItemFontWeight": "Normal",
  "ResultItemFontStretch": "Normal",
  "ThemeBlurEnabled": false,
  "WindowLeft": 283.0,
  "WindowTop": 170.5,
  "CustomizedPluginConfigs": [],
  "CustomPluginHotkeys": [],
  "StartWoxOnSystemStartup": true,
  "Opacity": 1.0,
  "OpacityMode": 0,
  "LeaveCmdOpen": false,
  "HideWhenDeactive": false,
  "RememberLastLaunchLocation": false,
  "IgnoreHotkeysOnFullscreen": false,
  "ProxyServer": null,
  "ProxyEnabled": false,
  "ProxyPort": 0,
  "ProxyUserName": null,
  "ProxyPassword": null,
  "MaxResultsToShow": 6
}</code>

<code>Plugins\Wox.Plugin.CMD\plugin.json</code>
<code>{
    "ID":"D409510CD0D2481F853690A07E6DC426",
    "ActionKeyword":">",
    "Name":"Shell",
    "Description":"Provide executing commands from Wox. Commands should start with >",
    "Author":"qianlifeng",
    "Version":"1.0.0",
    "Language":"csharp",
    "Website":"http://www.getwox.com/plugin",
    "ExecuteFileName":"Wox.Plugin.CMD.dll",
    "IcoPath":"Images\cmd.png"
}</code>

**Comment by bao-qian** [comment]
Strange, I will investigate this. Thanks for report.

**Comment by bao-qian** [comment]
@ningfei Could you provide the **build number** from Appveyor?

**Comment by ningfei** [comment]
I just download the release-binary.zip from here: https://ci.appveyor.com/project/qianlifeng/wox/build/artifacts

**Comment by ningfei** [comment]
I think it might be a problem of the build system. I switched back to old commits, found one commit at which the cmd plugin works, then I switched back to HEAD, rebuilt the solution at HEAD, the generated binaries also work fine. But if I cleaned up my local repository (git -fdx) after I switched back to HEAD, and then build the solution, the problem appears again.

**Comment by bao-qian** [comment]
That's my initial thought. Because new build won't overwrite the old config files. But it seems like not working.

**Comment by bao-qian** [comment]
Only appear in Release mode, extremely hard to Debug....

**Comment by ningfei** [comment]
So it's not the problem of the wox/plugin config files, but some intermediate files generated during building. If we have these intermediate file from previous successful build, then the latest release build will also work. Yes, it's true, very hard to isolate it...I don't have experience with csharp...

**Comment by bao-qian** [comment]
Finally found the problem.
It's because one of DLL required by CMD is missing when dynamic load plugin.
It Will be fixed soon.

**Comment by ningfei** [comment]
@happlebao great job!
