### ISSUE TITLE
Website landing page "Redesign"🚀🙂

### ISSUE THREAD

**Issue by Qiamast** [Wox-launcher/Wox#3821]
Hi there, I viewed your main website a few minutes ago and I noticed that the landing page is not completed
I want to Redesign a landing page with the main software theme for your website. If you agree, please let me know so I can start my work

**Comment by Qiamast** [comment]
?

**Comment by qianlifeng** [comment]
Many thx, but Wox will not have any website/domains instead of github itself. see https://github.com/Wox-launcher/Wox/discussions/3937
