### ISSUE TITLE
Pasting a URLs in Wox launcher displays text superimposed over itself, skewed.  Why?

### ISSUE THREAD

**Issue by mattrussell5** [Wox-launcher/Wox#3832]
![8E37A254-9F75-44F6-8C5B-969E69DCC6D3](https://user-images.githubusercontent.com/110549225/211180322-d659141e-a3ea-42ab-bac5-7426c14d8d12.png)
**Describe the bug**
The text that is displayed in the WOX launcher whenever I display some or a full URL that is longer than the Wox Launcher viewing pane is like seeing the text in double: two copies of it are superimposed and it's just illegibly skewed.  This does not manifest when I paste standard text but seems to be specific to URL paths.  Why?  Can this be fixed?

**To Reproduce**
1. Launch Wox
2. Paste in some copied URL that is wider than the viewing pane of the Wox Launcher window

**Expected behavior**
I see the pasted text as I would see all other pasted text

**Actual behavior"
There are two text previews superimposed.  See attached video.

**Runtime info**
 - Windows 10 Version: 21H2
 - Wox version 1.4.1196

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937 We have different implement of UI in v2
