### ISSUE TITLE
使用中文输入法，wox奔溃

### ISSUE THREAD

**Issue by moorlop** [Wox-launcher/Wox#384]
最新的Build版本，使用中文输入法，wox奔溃

**Comment by bao-qian** [comment]
系统版本？哪个输入法？报错信息？截图？重复步骤？

**Comment by bao-qian** [comment]
你试一下这个build [1.2.0.550](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.0.550/artifacts)，应该会提供更详细的报错信息。

请参考[这里](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87#%E5%A6%82%E4%BD%95%E6%B1%87%E6%8A%A5-bug)提供更多详细信息。

**Comment by morirain** [comment]
我应该遇到了同样的bug。
wox版本是1.2.0.554
操作系统是win10 64位
[2015-11-12.log.txt](https://github.com/Wox-launcher/Wox/files/32158/2015-11-12.log.txt)

bug发生时wox直接闪退，没有提示任何信息。
似乎只有“网页搜索”插件有这个问题，具体的情况就是无法输入中文的搜索内容，否则整个进程直接消失，使用英文则无影响。
使用的输入法是搜狗输入法，不过测试微软的日语输入法后也出现了一样的bug。

一些其他的事情：搜索时没有显示搜索引擎的图标，wox的激活热键无法设置为像win+z这样的组合，另外，求加入透明效果啊啊啊啊啊啊。

**Comment by morirain** [comment]
@happlebao 话说还能艾特人呀= =，不太会用github。

**Comment by bao-qian** [comment]
@morirain 透明效果正在施工中，看[pull request](https://github.com/Wox-launcher/Wox/pull/383)。

**Comment by bao-qian** [comment]
@morirain 感谢反馈。
搜索引擎图标今晚修复。
组合键暂时不能用win键，短时间没空改。
透明效果正在施工中，看[pull request](https://github.com/Wox-launcher/Wox/pull/383)。
中文问题现在确认是个bug。我会尽快修复。

**Comment by bao-qian** [comment]
- [x] search engine icon
- [x] Unicode as search string
- [x] crash report can't catch Unhanded Unicode exception

**Comment by bao-qian** [comment]
@morirain 请试一下这个版本
https://ci.appveyor.com/api/buildjobs/i0nu6chwt2b23t6a/artifacts/Output/release-binary.zip
暂时忽略选中条目的背景颜色。

**Comment by bao-qian** [comment]
@moorlop 麻烦你也试一下这个版本
https://ci.appveyor.com/api/buildjobs/i0nu6chwt2b23t6a/artifacts/Output/release-binary.zip
如果你系统版本小于win8，那么请安装.NET 4.5.2。

**Comment by morirain** [comment]
@happlebao 问题已经解决。
修改搜索引擎时，会提示“新触发关键字已经被指派给其他插件了，请重新选择一个关键字”，导致改动无法保存。

**Comment by bao-qian** [comment]
@morirain 我试没问题。你想在改哪个搜索？想改成哪个关键字？

**Comment by happlebao** [comment]
@qianlifeng .NET 3.5看起来有bug。跟这个也有关：https://github.com/Wox-launcher/Wox/issues/392
有什么建议？
维护一个不能用中文搜索的.NET3.5分支和一个.NET4.5分支？

**Comment by morirain** [comment]
@happlebao 不进行改动，只是点击Update也会触发。
![1](https://cloud.githubusercontent.com/assets/10196181/11139098/e021f53c-8a05-11e5-889e-046ec5cbabb5.png)

**Comment by bao-qian** [comment]
@morirain 已修复。
https://ci.appveyor.com/api/buildjobs/wh9g4werc4xpn0yx/artifacts/Output/release-binary.zip

**Comment by moorlop** [comment]
搜索的内容打不开

**Comment by bao-qian** [comment]
@moorlop 具体是？请提供截图

**Comment by bao-qian** [comment]
@morirain 透明/毛玻璃效果完工了。去 release 下最新的 [beta.2](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta.2）

**Comment by bao-qian** [comment]
@moorlop @morirain 
.net 4.5 已完工。这个问题应该被顺便修复了。试一下 [build 1.2.662](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.662/artifacts)。
