### ISSUE TITLE
Ability to access query history of Wox

### ISSUE THREAD

**Issue by M142857** [Wox-launcher/Wox#3842]
请添加wox自己搜索历史的记录查询，比如空格快捷键展示之前搜索、查询过的历史。

手机上的搜索都有相关历史，甚至淘宝京东这种的搜索框。

如果有插件也可以，但似乎需要调用内置。

请增加。

**Comment by qianlifeng** [comment]
我记得直接在wox激活后, 在输入框中输入方向键上可以切换历史的. 如果不支持, 我们会在v2中支持, 谢谢

**Comment by M142857** [comment]
“ 在输入框中输入方向键上可以切换历史的”
并没反应。

手机上用searchevo，查询历史搜索记录快捷键是空格，可以参考。

另外，激活wox后，用ctrl+h 可以唤起历史搜索记录，但是很久以前的记录，也不全，不知道收录规则，设置中也查不到相关设置。ctrl+h也是无意按出来的。这个有设置么？

**Comment by qianlifeng** [comment]
新版里面, 有两种方式可以访问查询历史:

- `Query History`插件, 触发关键字`h `
- 在激活Wox后, 直接使用方向键上切换上次的历史

**Comment by M142857** [comment]
> 新版里面, 有两种方式可以访问查询历史:
> 
> * `Query History`插件, 触发关键字`h `
> * 在激活Wox后, 直接使用方向键上切换上次的历史

@bao-qian @qianlifeng 

上面的方法在V1中都不可以。
1.没有Query History这个插件
2.使用方向键上

但是，激活wox后，用ctrl+h 可以唤起历史搜索记录，但是很久以前的记录，也不全，不知道收录规则，设置中也查不到相关设置。ctrl+h也是无意按出来的。这个有设置么？

见图

![wox历史搜索查询截图Snipaste_2023-10-31_08-47-07](https://github.com/Wox-launcher/Wox/assets/81762812/8c782d2c-d361-429a-bebe-2ba2e7fcee44)

**Comment by qianlifeng** [comment]
v1是不可以，我说的是新版v2

**Comment by M142857** [comment]
那这个ctrl+h，激活的执行查询是怎么设置的呢，应该是内置的功能。现在的问题是历史不全，也不知道如何收录。

激活wox后，用ctrl+h 可以唤起历史搜索记录，但是很久以前的记录，也不全，不知道收录规则，设置中也查不到相关设置。
