### ISSUE TITLE
UI Flickering #350 changed action handling

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#386]
Changes for #350 changed the functionality how new results are handled. Now that the results don't get purged, but instead are reweighted and updated, Actions that were set on the run won't work.

I'll explain it on an example. My clock plugin has a menu-sub-menu system, so it may well display only one result without actually updating anything. So for example, if type in this command
![image](https://cloud.githubusercontent.com/assets/4784785/11076892/98d90fd0-87fd-11e5-898f-48f4a43caae5.png)
Notice, how there is a result already. 
And the code that is responsible for this:

```
 protected override List<Result> CommandQuery(Query query, ref List<Result> results)
        {
            var args = query.ActionParameters;
            results.Add(new Result()
            {
                Title = "You are adding a new alarm",
                SubTitle = "Accepts: time as HH:MM, name as any string",
                IcoPath = GetIconPath(),
                Action = e =>
                {
                    return Execute(args);
                }
            });
            return results;
        }
```

So now the problem is that as soon as I type `clock add`, a result with one argument (_add_) gets pushed the the result box. By the time I type in `clock add 09:00` the result with the correct arguments (_add 09:00_) will get pushed, but removed (`ResultPanel.xaml.cs, Lines 66-71`), because of the previous `clock add` result being in the collection. 

So of course, when I submit the command `clock add 09:00` instead of it `clock add` gets executed. 

What is the right way to go now about this? Thanks for your time.

**Comment by happlebao** [comment]
I'm struggling with this bug #382.
I will check your code later.
Could you give a link for your source code?

**Comment by happlebao** [comment]
Finally found the problem.
It's because one of DLL required by CMD is missing when dynamic load plugin.
It Will be fixed soon.

**Comment by bao-qian** [comment]
Could you give a link for your source code?

**Comment by lances101** [comment]
@happlebao, sure, [there you go](https://github.com/lances101/Wox.Plugin.SimpleClock)

**Comment by lances101** [comment]
The thing is that the intersection is made based on the Title and Subtitle hashcode, which in my case will _always_ be the same and will match. 

```
Result.cs Line 60
var hashcode = (Title?.GetHashCode() ?? 0) ^ (SubTitle?.GetHashCode() ?? 0);
```

As a dirty fix I could add random symbols to the subtitle, or maybe the last argument so that it differentiates them... But I don't think this is an option

**Edit**: Again, I don't think the fact that it does not get updated is a bug. This is working as intended. Any ideas on an elegant fix to make it actually push the result with the new action?

**Comment by bao-qian** [comment]
Things is pretty simple now, check the Wox.Plugin.PluginManagement to see how to handle multi level comands. I will provide some pseudocode for core logic.
The idea is change the title while user typing.

``` csharp
public List<Result> Query(Query query)
{
List<Result> results = new List<Result>();
int length = query.ActionParameters.Length;
if (length == 0) // autocomplete
{
    results.Add(ResultForAddCommandAutoComplete(query));
    results.Add(ResultForSetCommandAutoComplete(query));
    // and more ... results.Add(ResultFor???CommandAutoComplete(query));
    return results;
}
string command = query.ActionParameters[0];
if (length == 1) // autocomplete too
{
    if (AddCommand.Contains(command))
    {
        results.Add(ResultForAddCommandAutoComplete(query));
    }
    if (SetCommand.Contains(command))
    {
        results.Add(ResultForSetCommandAutoComplete(query));
    }
    // and more ... ???Command.Contains(command)
}
if (length > 1) // display command result
{
    if (command == AddCommand)
    {
        return ResultForAddClock(query);
    }
    if (command == SetCommand)
    {
        return ResultForSettimer(query);
    }
    // and more ... command == ???
}

return results;
}


private Result ResultForAddCommandAutoComplete(Query query)
{
    string title = "Add a new clock";
    string subtitle = "Add <Time> <Name>. Time as HH:MM";
    return ResultForCommand(query, ListCommand, title, subtitle);
}

private Result ResultForCommandAutoComplete(Query query, string command, string title, string subtitle)
{
    const string seperater = Plugin.Query.TermSeperater;
    var result = new Result
    {
        Title = title,
        IcoPath = "Images\\plugin.png",
        SubTitle = subtitle,
        Action = e =>
        {
            context.API.ChangeQuery($"{query.ActionKeyword}{seperater}{command}{seperater}");
            return false;
        }
    };
    return result;
}


private Result ResultForAddClock(Query query)
{
    var time = query.ActionParameters[1];
    var name = query.ActionParameters[2];
    Result reuslt;
    // this is where to change the result accoring to user input
    string title = $"You are adding a new clock at Time: {time} as Name: {name}";
    string subtitle = "Add <Time> <Name>. Time as HH:MM";
    result = new Result
        {
            Title = title,
            IcoPath = "Images\\plugin.png",
            SubTitle = subtitle,
        }
    if (isValidTime(time) && isVaildName(name))
    {
        result.Action = e =>
        {
            AddClock(time, name);
            return true;
        }
    }
    else
    {
        result.Action = e =>
        {
            MessageBox.Show("Time and Name is not vaild, please use bla bla bla");
            return false;
        }
    }
}

```

**Comment by bao-qian** [comment]
I noticed that your plugin has serious UI flickering problems, you won't have it anymore after you refactoring your plugin. :smile:

**Comment by lances101** [comment]
@happlebao could you be more specific about the flickering? I'm getting none

**Comment by bao-qian** [comment]
@lances101 sorry for my poor English.
What I mean is your plugin gif in your repo shows flickering. Result list collapsed and expanded while user typing.

**Comment by lances101** [comment]
@happlebao aaah, that's what you meant :smile: That gif is from the old versions of Wox :)
