### ISSUE TITLE
支持搜索栏大小自定义

### ISSUE THREAD

**Issue by fengyayel** [Wox-launcher/Wox#3863]
**Is your feature request related to a problem? Please describe.**
Wox的搜索栏太长字体太大了对我来说, 请问是否能自定义搜索栏长度大小和字体大小, 还是这种功能我没有在设置里找到.请告诉我,谢谢

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qianlifeng** [comment]
暂时没有计划
