### ISSUE TITLE
设置界面的动画问题

### ISSUE THREAD

**Issue by XIMUMIX** [Wox-launcher/Wox#3866]
环境：
- Wox  1.4.1196
- Win10 22H2 19045.2728

问题描述：
在Wox“设置”-“通用”中，有几个多项选择的选项，例如：“搜索精度”、“上次搜索关键字模式”、“语言”、“最大结果显示个数”。

当单击选项进行选择时，“搜索精度”和“上次搜索关键字模式”中的选项会存在一个从模糊到清晰的变化过程，而“语言”和“最大结果显示个数”则不会，出现选项的瞬间就已经是清晰的了。

如果可以，麻烦在后续版本中对该现象进行解决

**Comment by qianlifeng** [comment]
see #3937
