### ISSUE TITLE
希望添加一键/自动重建索引的功能！

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#388]
当我把本地的Wox拷贝给同事或朋友的时候（里面有我自己推荐给朋友的配置和插件）
他人拿到我给的整个Wox后，结果什么都索引不到！
因为Wox目录里面的索引数据还是我电脑上的！
例如：
Wox\Config\ImageCache.dat
Wox\Plugins\Wox.Plugin.Program\ProgramIndexCache.dat
Wox\Plugins\Wox.Plugin.Everything\PortableEverything\Everything.db

当然，可以删除了这些文件后再发给他人，
但如果我电脑更改了硬盘，或者是改变了本地程序路径（绿色软件等）

当然，也可以删除了这些文件后，再重启Wox，也能得到重建
不过这样是否是太麻烦呢？如果提供一个一键重建，
或者内部自动检测变化，自动更新或重建索引是最好的。

**Comment by bao-qian** [comment]
这一键重建暂时是做不到了。目前bug还很多。
你也看到了，有些就不是Wox的Cache。
用powershell就好了。

``` powershell
Remove-Item -Recurse Wox\Config *.dat
Remove-Item -Recurse Wox\Plugin *.dat
Remove-Item -Recurse Wox\Plugin *.db
```

**Comment by bao-qian** [comment]
- provide global cache folder
- ability to clean/rebuild cach at one click
- this should be done after the refactoring of config #389
