### ISSUE TITLE
Don't index programs every time.

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#390]
In `Wox.Plugin.Program.Programs`
`Stopwatch.Debug("Program Index", IndexPrograms);`
Seems like program plugin will indexing every time?

**Comment by qianlifeng** [comment]
What do you mean "every time"?

**Comment by bao-qian** [comment]
every startup

**Comment by qianlifeng** [comment]
There may be programs installed/uninstalled after Wox exit, so we need to reindex on every startup.
