### ISSUE TITLE
Culture 'ug'

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#392]
When start Wox as Debug mode,
From the exceptions you can see that there are bunch of Arabic font exceptions:

```
Cannot find file 'C:\\WINDOWS\\FONTS\\moolbor.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\simpfxo.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\utsaahbi.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\CORDIAUI.TTF'.
Cannot find file 'C:\\WINDOWS\\FONTS\\CORDIAUB.TTF'.
Cannot find file 'C:\\WINDOWS\\FONTS\\kokilabi.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\kokilabi.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\mangalb.ttf'.
Cannot find file 'C:\\WINDOWS\\FONTS\\CORDIAUZ.TTF'.
```

And there are some culture related exceptions.

```
Culture name 'ug' is not supported.
There is no registered CultureInfo with the IetfLanguageTag 'ug'
```

the 'ug' exception prevent crash report catch unhanded exception. See #287 and #384
And the 'ug' exception prevent debugging real exception pf #384 or that 'ug' exception is the real exception....

**Comment by lances101** [comment]
I have stumbled upon it before. Didn't create issue because I thought it was a problem with my system only.  Please see [this](http://stackoverflow.com/questions/3646488/locating-the-source-of-managed-exceptions-that-arent-coming-directly-from-my-co), it seems to be a problem with Windows itself

**Comment by bao-qian** [comment]
Thanks. I noticed that long before, but it seems like I can't do it correctly.
Normally this is not a issue.
But now, when I want to track the real exception of #384, this culture 'ug' exception is trowed back to me.

**Comment by bao-qian** [comment]
Wow, .NET 4.5 don't have this problems at all! One more reason to upgrade.

**Comment by bao-qian** [comment]
@lances101 you can try it with dotnet45 branch.

**Comment by lances101** [comment]
@happlebao  Yup, no problems with the donet45 branch.

**Comment by bao-qian** [comment]
.net 4.5 is done, check #393
