### ISSUE TITLE
插件配置允许配置为在主线程里初始化

### ISSUE THREAD

**Issue by dreamanlan** [Wox-launcher/Wox#3924]
**Is your feature request related to a problem? Please describe.**
插件里创建窗口的话需要在主线程进行，比如everything api Query(false)需要使用一个窗口句柄来接收消息，如果插件初始化不在主线程初始化的话，我们就没办法提供这样一个句柄。另外，插件如果创建自己的线程，线程退出条件可能需要检查主线程是否退出。

**Describe the solution you'd like**
考虑到修改为并行初始化的目的是提升启动速度，可以在插件配置里增加一个配置项来指明是否在主线程初始化，默认仍然是并行初始化。稍后我改了提个修改request。

**Describe alternatives you've considered**
最简单的办法就是从并行初始化改为foreach，不过可能与当初修改意图有冲突。

**Additional context**

**Comment by qianlifeng** [comment]
因为v2的架构不同, 所以可能不需要了. 具体见: https://github.com/Wox-launcher/Wox/discussions/3937
