### ISSUE TITLE
Favorites for Programs 

### ISSUE THREAD

**Issue by SheepDomination** [Wox-launcher/Wox#3933]
From what I understand, this has been brought into PowerToy for Windows with the exception that it cannot do favorites ?

**Comment by qianlifeng** [comment]
> From what I understand, this has been brought into PowerToy for Windows with the exception that it cannot do favorites ?

What does favorites for programs do? Does this means user can add custom programs folder?

**Comment by qianlifeng** [comment]
Both custom app folders and add search result to favorite are all supported now.
