### ISSUE TITLE
xshell 插件错误

### ISSUE THREAD

**Issue by tianpomin** [Wox-launcher/Wox#394]
问题描述： xshell插件打不开xshell的回话。

操作系统： win7

xshell版本： 
Xshell.exe: 5.0.0031, nssock2.dll: 5.0.0021, nsssh3.dll: 5.0.0027, nsprofile2.dll: 5.0.0020, nslicense.dll: 5.0.0015, nsutil2.dll: 5.0.0020, nsverchk.exe: 5.0.0008, Xagent.exe: 5.0.0016, Xactivator.exe: 5.0.0003

wox版本：1.2.0 beta

步骤： 1. 安装xshell插件，修改配置文件
            2, 可以读到回话信息， 打开会话时报错

错误信息：
在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 c:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 159
在 Wox.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass2.<query>b__1(Object state) 位置 c:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 60
在 System.Threading.ExecutionContext.runTryCode(Object userData)
在 System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallbackInternal(_ThreadPoolWaitCallback tpWaitCallBack)
在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback(Object state)

截图：

![360 20151115170458](https://cloud.githubusercontent.com/assets/1183836/11168230/ce1a61be-8bc0-11e5-91a1-ef31d43437de.png)
![360 20151115170541](https://cloud.githubusercontent.com/assets/1183836/11168231/d1794c30-8bc0-11e5-86e5-1779dbd3d73e.png)

**Comment by bao-qian** [comment]
你是不是考虑去找插件开发者。。。
毕竟代码不在我手上。。。

**Comment by tianpomin** [comment]
xshell 会话名是中文的时候出错， 估计是编码问题吧

**Comment by bao-qian** [comment]
讲真，代码不在我手上，你让我怎么调试。

**Comment by tianpomin** [comment]
这个了解， 我研究下看能不能改。

插件中的 git地址指到这里的，所以就来问了。不好意思。

另外软件很好用， thx

**Comment by bao-qian** [comment]
感谢支持。

**Comment by bao-qian** [comment]
我重新看了下。这是原作者 @qianlifeng 写的。看起来这个插件放弃维护了。并且他最近很忙。
你可以新建一个github repo，修复这个插件，然后重新[上传](https://www.getwox.com/plugin)。

**Comment by bao-qian** [comment]
或者试一下[latest build](https://github.com/Wox-launcher/Wox#installation)

**Comment by bao-qian** [comment]
然后看一下
这个issue： https://github.com/Wox-launcher/Wox/issues/345
和这个repo： https://github.com/anonymousch/Wox.Plugin.xshell
