### ISSUE TITLE
First launch takes a long time

### ISSUE THREAD

**Issue by gblazex** [Wox-launcher/Wox#395]
Even though it's set to launch when the computer starts and it's sitting on the Taskbar,
no matter how much time passes after fully booting,
upon the first key combination it always takes 5-10 seconds for Wox to appear.

Everything should be initialized when booting the system.

**Comment by lances101** [comment]
@galambalazs, please specify what version of Wox you are using

**Comment by gblazex** [comment]
v1.1.1

**Comment by gblazex** [comment]
It only happens for the first keyboard shortcut after booting.
Subsequent launches via the shortcut keys bring up the Wox input box immediately.

**Comment by lances101** [comment]
@galambalazs Can confirm.  **v1.1.1** does have this issue. Could you please try the [1.2.0 beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta)? 

If that still does not load in time, consider trying [one of the recent builds](https://ci.appveyor.com/project/qianlifeng/wox/build/artifacts) (release-binary.zip).  

I can only reproduce the issue on   **v1.1.1** and it would be good to know if it is still present on newer releases. Thanks!

**Comment by gblazex** [comment]
I'll try it.

What's this Everything.exe? Can I safely disable it?
(even after disabling in the settings it comes up everytime I try to launch Wox)

**Comment by lances101** [comment]
_Everything.exe_ is part of the [Everything Search](http://www.voidtools.com/) plugin. 

The thing with not being able to correctly disable a plugin is already known. See #351 
For now, if you want to disable Everything completely - you can delete the plugin from its folder.
