### ISSUE TITLE
MacOSversion requirement matched but with confusing tips: Mac Install Error

### ISSUE THREAD

**Issue by notfresh** [Wox-launcher/Wox#3950]
This is the error when I try to start Wox
<img width="532" alt="image" src="https://github.com/Wox-launcher/Wox/assets/12556509/1080e88f-c783-4dc4-a16c-4f21e8f19be3">

This is my Mac information
<img width="566" alt="image" src="https://github.com/Wox-launcher/Wox/assets/12556509/41a7aebf-eee1-44f1-ac85-6004387c28ed">

**Describe the bug**
My MacOS version meets the requirements of wox, but it can't be started as expected.

**To Reproduce**
1. Download from the release page and choose the version [wox-mac-amd64-20231109-135a5d.dmg](https://github.com/Wox-launcher/Wox/releases/download/v2.0.0-alpha.1/wox-mac-amd64-20231109-135a5d.dmg)
2. install it , open the dmg and click the Next buttons.
3. move the wox.app to the Application directory
4. Can't open anyway. So confusing.

**Expected behavior**
start normally

**Screenshots**
paste above

**Version**
- [ ] v1 (has no resource to fix)
- [x] v2

**Platforms**
- [x] Macos
- [ ] Windows
- [ ] Linux

**Additional context**

**Comment by qianlifeng** [comment]
Sorry for that, since we use golang 1.21, which requires [10.15 Catalina](https://go.dev/doc/go1.20#darwin:~:text=or%20Server%202016.-,Darwin%20and%20iOS,-Go%201.20%20is). The minimal requirement 10.12 is wrong and i will fix it.
