### ISSUE TITLE
基于python开发插件时，wox界面上获取插件的输入过于灵敏。输入关键字之后紧跟空格或者删除键都会触发。

### ISSUE THREAD

**Issue by DirtyKnightForVi** [Wox-launcher/Wox#3952]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**
- [ ] v1 (has no resource to fix)
- [ ] v2

**Platforms**
- [ ] Macos
- [ ] Windows
- [ ] Linux

**Additional context**

**Comment by qianlifeng** [comment]
v2可以设置delay参数
