### ISSUE TITLE
Add compatibility with Everything 1.5a.

### ISSUE THREAD

**Issue by Auscobe** [Wox-launcher/Wox#3953]
**Describe the bug**
Even after restarting Wox and Everything 1.5a after configuring the "Editor Path" of the Everything plugin to use Everything 1.5a's executable, Wox reports Everything as not running.

**To Reproduce**
1. Direct Wox's Everything plugin to Everything 1.5a.
2. Regardless of restarting Wox or Everything, Wox reports that Everything is not running.

**Expected behavior**
Everything 1.5a to be used as easily as the regular one.

**Screenshots**
https://imgur.com/cUkOMcE

**Version**
1.4.1196

**Platforms**
Windows

**Comment by Youxikong** [comment]
![image](https://github.com/Wox-launcher/Wox/assets/26603498/b3a83524-559a-404e-b99f-4db5564c77cd)
You can configure alpha_instance then restart everything.

**Comment by Auscobe** [comment]
Thank you, that worked.
