### ISSUE TITLE
Doesn't work on MacOS M1

### ISSUE THREAD

**Issue by t18n** [Wox-launcher/Wox#3957]
**Describe the bug**
On my Mac M1, arm64 build shows this error "“Wox” is damaged and can’t be opened. You should move it to the Bin."

**To Reproduce**
1. Download [wox-mac-arm64-20231127-724b6e.dmg](https://github.com/Wox-launcher/Wox/releases/download/v2.0.0-alpha.1/wox-mac-arm64-20231127-724b6e.dmg)
2. Copy to Applications
3. Open the app and see the message

**Expected behavior**
The app should open

**Version**
- [ ] v1 (has no resource to fix)
- [x] v2

**Platforms**
- [x] Macos
- [ ] Windows
- [ ] Linux

**Additional context**
MacOS 14.0 (23A344)
Apple M1 Max

**Comment by qianlifeng** [comment]
Try this: https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/#:~:text=Use%20xattr%20on%20the%20App%20Throwing%20the%20Damaged%20Error

**Comment by t18n** [comment]
@qianlifeng I tried it but still didn't work :(

**Comment by aLIEz-xue** [comment]
> @qianlifeng I tried it but still didn't work :(

Delete the ~/.wox folder and try again, I've installed wox before and looked at the logs and found that it's a problem with the default configuration file.

**Comment by qianlifeng** [comment]
MacOS version is now code signed and notarization, so this error should not be exist anymore
