### ISSUE TITLE
What's new in Wox v2?

### ISSUE THREAD

**Issue by jishanalibd** [Wox-launcher/Wox#3960]
What are some of the most exciting changes in **Wox v2**?

**Comment by lukaszjablonski** [comment]
Check here: https://github.com/Wox-launcher/Wox/discussions/3937

**Comment by qianlifeng** [comment]
The biggest change is that Wox now is cross-platform

**Comment by jishanalibd** [comment]
I can not use Wox V2 alpha-1 on my Win10 x64

**Comment by jishanalibd** [comment]
Ok, by installing **Node.js** it run but ....

**Comment by qianlifeng** [comment]
> Ok, by installing **Node.js** it run but ....

v2 is under active development, it may has bugs and not feature complete. You can create a PR or wait util v2 is GA, thx.

**Comment by jishanalibd** [comment]
I think it will be hard to claim as stable performance as v1 for Wox v2 but if you can, you're Superior.

**Comment by qianlifeng** [comment]
> I think it will be hard to claim as stable performance as v1 for Wox v2 but if you can, you're Superior.

Why do you think so?

**Comment by jishanalibd** [comment]
> > I think it will be hard to claim as stable performance as v1 for Wox v2 but if you can, you're Superior.
> 
> Why do you think so?

By using the Wox v2 alpha-1 and Wox is my most loveable program.

**Comment by jishanalibd** [comment]
Setting window doesn't open in Wox v2.
`[INF] [->UI] OpenSettingWindow: {"x":360,"y":180} `

**Comment by qianlifeng** [comment]
> > > I think it will be hard to claim as stable performance as v1 for Wox v2 but if you can, you're Superior.
> > 
> > 
> > Why do you think so?
> 
> By using the Wox v2 alpha-1 and Wox is my most loveable program.

Glad you like Wox. As I said v2 is still under development and  is not feature complete yet. It is not appropriate to compare the current v2 with v1. You can continue to use v1 now and check out v2 after a few months later.

`Setting window doesn't open in Wox v2 now` is because we didn't implement the setting window. And it's just a placeholder.

**Comment by jishanalibd** [comment]
> > > > I think it will be hard to claim as stable performance as v1 for Wox v2 but if you can, you're Superior.
> > > 
> > > 
> > > Why do you think so?
> > 
> > 
> > By using the Wox v2 alpha-1 and Wox is my most loveable program.
> 
> Glad you like Wox. As I said v2 is still under development and is not feature complete yet. It is not appropriate to compare the current v2 with v1. You can continue to use v1 now and check out v2 after a few months later.
> 
> `Setting window doesn't open in Wox v2 now` is because we didn't implement the setting window. And it's just a placeholder.

Ok, go ahead.
