### ISSUE TITLE
Slideshow stops working & Cannot change wallpaper when DWM-Enabled Window is enabled

### ISSUE THREAD

**Issue by koobs** [Wox-launcher/Wox#397]
When _Theme_ -> _Window Mode_ is set to _DWM-Enabled Window_
- Desktop Background Slideshow stops working
- Cannot change wallaper via Desktop -> Right Click -> Next desktop background
- Cannot change wallaper via manually  via Personalization -> Select a Desktop Background

Additional testing:

The above functions fail to work while Wox Settings window is open (any tab)

Sometimes setting _Window Mode_ back to _Layered_ or _Normal_ fixes the issue, sometimes a complete program restart is required.

OS: Windows 7 Ultimate x64 (All updates)
Graphics: MSI R7950 Twin Frozr 3GD5/OC (Catalyst 15.11 Beta)
Wox: 1.1.1

**Comment by bao-qian** [comment]
Thanks for report.
Could you try the [1.2 beta](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta) or the latest build: [history](https://ci.appveyor.com/project/qianlifeng/wox/history)     (top green build -> artifacts -> release-binary.zip)?

**Comment by koobs** [comment]
@happlebao I already tried the latest build (yesterday). The DWM-Enabled option is no longer there to select. Has it been moved or disabled, or only available in debug builds?

**Comment by bao-qian** [comment]
To be honest, I'm not sure. 1.1.1 is a very old version and I just takeover this repo recently. If there is nothing wrong, I will close this issue.

**Comment by qianlifeng** [comment]
@koobs Yes, DWM-Enabled is removed in v1.1.1 and later due to the performance issue

**Comment by koobs** [comment]
@happlebao This is still an issue in 1.2.0 (latest build). It is reproducible once entering the Theme tab

**Comment by lances101** [comment]
Yes. Can confirm. This happens on the latest builds.

**Comment by lances101** [comment]
This happens because Wox locks the Wallpaper file instead of making a copy of it in memory. I will fix it now.

**Comment by lances101** [comment]
PR #427 fixes this inability to cycle through wallpapers as @koobs  described.

If the wallpaper changes while Wox Settings is open, the wallpaper inside of Wox will **not** update. This is intended. A separate issue should be created if such functionality is considered a needed feature.

**Comment by bao-qian** [comment]
@koobs please test the [build](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.619/artifacts) commited by @lances101

**Comment by koobs** [comment]
@happlebao Will do, stand by

**Comment by koobs** [comment]
@happlebao This is still an issue in the latest nightly (As of 01/02/2016) with in-UI Version string: `1.2.639`

Reiterating is symptoms:
- Cannot change desktop wallpaper (or automatic wallpaper slideshow) via:
  - Desktop -> Right-click -> Next desktop background
  - Desktop -> Right-click -> Personalize -> Desktop Background
- Once Wox -> Settings -> Theme tab has been Opened
- Until restarting Wox

**Comment by lances101** [comment]
@koobs, build `1.2.639` does not have the fix for the issue you described.

Please try build [`1.2.619`](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.619/artifacts) so that we can merge it.

**Comment by koobs** [comment]
@lances101 Understood, stand by

**Comment by koobs** [comment]
@lances101 Confirming resolved:
- Desktop -> Right-click -> Next desktop background - **OK**
- Desktop -> Right-click -> Personalize -> Desktop Background - **OK**

**Comment by koobs** [comment]
I'll leave this open until the merge/reference is added :)
