### ISSUE TITLE
请问Microsoft Store上面有人在卖的那个Wox Launcher是官方的吗（看着不像）

### ISSUE THREAD

**Issue by febilly** [Wox-launcher/Wox#3970]
[商店链接1](https://apps.microsoft.com/detail/9NFVVFVL8KVX)
感觉看着很像其他人挂上去骗钱的
![商店截图1](https://github.com/Wox-launcher/Wox/assets/58109587/12c5d49d-7d46-46ca-93eb-479110ee93d1)

Microsoft Store里面还有另外一个wox，但这个好像是给了源码，不知道算不算侵权？
[商店链接2](https://apps.microsoft.com/detail/9NR6M23FJLZ6)
![商店截图2](https://github.com/Wox-launcher/Wox/assets/58109587/c834cf37-2e29-4318-80eb-85eb0b976ed4)

![商店截图3](https://github.com/Wox-launcher/Wox/assets/58109587/54e4ed0f-10a5-4fc6-8c9e-384b9c5b696c)

**Comment by qianlifeng** [comment]
显然不是官方的
