### ISSUE TITLE
wox崩溃问题

### ISSUE THREAD

**Issue by Sinyeee** [Wox-launcher/Wox#3971]
我的电脑是Windows10 x64系统，在使用过程中，当输入一些数字时，偶尔会出现崩溃闪退的问题。比如我有个文件夹叫“20231019活动”，当输入“20231019”时，虽结果列表中显示了符合条件的文件夹，但是wox会崩溃掉，得重新打开wox才行。我使用的wox版本是v1.4.1196。

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937

**Comment by Sinyeee** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
