### ISSUE TITLE
搜中文应用时提示 everything client没有运行

### ISSUE THREAD

**Issue by iamqiz** [Wox-launcher/Wox#3972]
**Describe the bug**
想搜索"网易云音乐",输入中文后提示 everything client没有运行, 截图在下面

**To Reproduce**

**Expected behavior**

**Screenshots**
![Clip_2024-01-02_11-02-20](https://github.com/Wox-launcher/Wox/assets/48077521/29fc4193-eb0e-475a-9ee2-38044acd7eae)

**Version**
- [ ] v1 (has no resource to fix)
- [ ] v2

**Platforms**
- [ ] Macos
- [ ] Windows
- [ ] Linux

**Additional context**

**Comment by qianlifeng** [comment]
如提示所说, 你应该没有运行everything

**Comment by iamqiz** [comment]
我搜英文名的应用没提示用everything,难道中文应用必须用everything搜? 不太科学

**Comment by iamqiz** [comment]
@qianlifeng

**Comment by iamqiz** [comment]
@qianlifeng 怎么自定义everything路径? 我everything在运行, 但是wox说我everything没运行
