### ISSUE TITLE
帮助优化，开启的报错日志

### ISSUE THREAD

**Issue by Aikaxiya** [Wox-launcher/Wox#3976]
2024-01-15 00:00:19.6664|ERROR|Wox.Core.Updater|UpdateApp|Check your connection and proxy settings to api.github.com. The remote server returned an error: (404) Not Found.
2024-01-15 00:52:22.3492|INFO|Wox.App|Dispose|Wox Start Displose
2024-01-15 19:26:35.6184|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2024-01-15 19:26:35.7795|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 01/15/2024 19:26:35
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.22621.0
* x64 OS: True
* x64 Process: True
* System Language: zh-CN
* Wox Language: zh-cn
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v4 Client 4.8.09032
   * v4 Full 4.8.09032
   * v4.0 Client 4.0.0.0

2024-01-15 19:26:36.0348|ERROR|Wox.Core.Plugin.PluginsLoader|PythonPlugins|Python can't be found in PATH.
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Browser Bookmarks> is <73ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Shell> is <60ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Folder> is <65ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <System Commands> is <6ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <URL> is <38ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Calculator> is <43ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <IP Address> is <28ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Wox Plugin Management> is <46ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Colors> is <41ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Web Searches> is <64ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Hello World CSharp> is <46ms>
2024-01-15 19:26:36.3734|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Plugin Indicator> is <35ms>
2024-01-15 19:26:36.3814|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Everything> is <47ms>
2024-01-15 19:26:36.3814|INFO|Wox.Plugin.Program.Main|preloadPrograms|Preload programs cost <7ms>
2024-01-15 19:26:36.3814|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload win32 programs <132>
2024-01-15 19:26:36.3814|INFO|Wox.Plugin.Program.Main|preloadPrograms|Number of preload uwps <4>
2024-01-15 19:26:36.3814|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Program> is <156ms>
2024-01-15 19:26:36.4914|INFO|Wox.Core.Plugin.PluginManager|InitializePlugins|Total init cost for <Control Panel> is <167ms>
2024-01-15 19:26:36.4914|ERROR|Wox.Core.Resource.Internationalization|LanguageFile|Language path can't be found <C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Languages\zh-cn.xaml>
2024-01-15 19:26:36.6040|INFO|Wox.Core.Resource.Theme|.ctor|Runtime Version 10.0.22621.0 True
2024-01-15 19:26:36.7232|INFO|Wox.App|OnStartup|SDK Info: ## SDK Info
* Python Path: 
* Everything SDK Path: C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

2024-01-15 19:26:36.7232|INFO|Wox.App|OnStartup|End Wox startup ----------------------------------------------------  
2024-01-15 19:26:36.7232|INFO|Wox.App|OnStartup|Startup cost <1213ms>
2024-01-15 19:26:36.9947|FATAL|DispatcherUnhandledException|Error id: e349755628934919b9ca69ec9830cee2
Exception begin --------------------
  System.ArgumentException: Value does not fall within the expected range.
  HResult: -2147024809
  Data: <System.Object> -> <>
  Source: WindowsBase
  TargetAssembly: WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  TargetModule: WindowsBase.dll
  TargetSite: Void CreateContext(Int32, CreateContextFlags, System.Object, ITfContext ByRef, Int32 ByRef)
  StackTrace: --------------------
   at MS.Win32.UnsafeNativeMethods.ITfDocumentMgr.CreateContext(Int32 clientId, CreateContextFlags flags, Object obj, ITfContext& context, Int32& editCookie)
   at System.Windows.Documents.TextServicesHost._RegisterTextStore(TextStore textstore)
   at System.Windows.Documents.TextStore.OnAttach()
   at System.Windows.Documents.TextEditor.InitTextStore(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Exception end ------------------------------------------------------------

## Runtime Info
* Command Line: "C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: False
* Timestamp: 01/15/2024 19:26:36
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.22621.0
* x64 OS: True
* x64 Process: True
* System Language: zh-CN
* Wox Language: zh-cn
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v4 Client 4.8.09032
   * v4 Full 4.8.09032
   * v4.0 Client 4.0.0.0

## SDK Info
* Python Path: 
* Everything SDK Path: C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll

## Assemblies - Wox.exe

* Wox, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.exe)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\NLog.dll)
* Wox.Core, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.Core.dll)
* Sentry, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Sentry.dll)
* Sentry.Protocol, Version=2.1.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Sentry.Protocol.dll)
* System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\System.Collections.Immutable.dll)
* Wox.Infrastructure, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.Infrastructure.dll)
* System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\System.Net.Http.dll)
* System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\System.ValueTuple.dll)
* Wox.Plugin, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Wox.Plugin.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Newtonsoft.Json.dll)
* Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Splat.dll)
* NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\NuGet.Squirrel.dll)
* Wox.Plugin.Sys, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.IPAddress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Roaming\Wox\Plugins\IP Address-4a9e8925-35e9-4ec9-83c3-7e6f50439fa8\Wox.Plugin.IPAddress.dll)
* Wox.Plugin.Caculator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.PluginIndicator, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.Url, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.BrowserBookmark, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* Wox.Plugin.Color, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.Everything, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* HelloWorldCSharp, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.PluginManagement, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.ControlPanel, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Shell, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* Wox.Plugin.WebSearch, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\WindowsInput.dll)
* Wox.Plugin.Folder, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Microsoft.Data.Sqlite, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.BrowserBookmark\Microsoft.Data.Sqlite.dll)
* Wox.Plugin.Program, Version=1.4.1196.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\NHotkey.Wpf.dll)
* Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.UI.winmd)
* Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime (C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd)
* System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\System.Runtime.dll)
* CommandLine, Version=2.7.82.0, Culture=neutral, PublicKeyToken=5a870481e358d379 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\CommandLine.dll)
* Sentry.PlatformAbstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0 (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\Sentry.PlatformAbstractions.dll)
* System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Users\ChenZhiFei\AppData\Local\Wox\app-1.4.1196\System.Runtime.InteropServices.RuntimeInformation.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsFormsIntegration\v4.0_4.0.0.0__31bf3856ad364e35\WindowsFormsIntegration.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
* System.Runtime.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll)
* System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)

2024-01-15 19:26:38.4056|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\Users\ChenZhiFei\AppData\Roaming\Microsoft\Windows\Start Menu
2024-01-15 19:26:38.4056|ERROR|Wox.Plugin.Program.Programs.Win32|ProgramPaths|Permission denied C:\ProgramData\Microsoft\Windows\Start Menu
2024-01-15 19:26:38.4481|INFO|Wox.Plugin.Program.Main|IndexPrograms|Win32 index cost <56ms>
2024-01-15 19:26:39.8230|ERROR|Wox.Core.Updater|UpdateApp|Check your connection and proxy settings to api.github.com. The remote server returned an error: (404) Not Found.

**Comment by qianlifeng** [comment]
see https://github.com/Wox-launcher/Wox/discussions/3937
