### ISSUE TITLE
How to uninstall Wox?

### ISSUE THREAD

**Issue by ascosio** [Wox-launcher/Wox#3978]
I've tried to follow this [page](https://github.com/Wox-launcher/Wox/wiki/Uninstalling-Wox) for uninstallation but it cannot find wox's location.
![image](https://github.com/Wox-launcher/Wox/assets/157364118/492deaee-44d9-4b8a-a6c0-f59abb831ba2)

**Comment by qianlifeng** [comment]
see #3937
