### ISSUE TITLE
下载后无法运行

### ISSUE THREAD

**Issue by 1651515568** [Wox-launcher/Wox#3994]
双击运行后只出现了任务栏图标，启动了几个日志等服务
![image](https://github.com/Wox-launcher/Wox/assets/85231080/06fc5198-76ab-482e-9694-9fa34f266aee)
但是无法呼出ui界面使用
右键菜单图标也没有反应
找到日志文件log
[log.txt](https://github.com/Wox-launcher/Wox/files/14503711/log.txt)

**Comment by qianlifeng** [comment]
我看日志你的alt+space热键注册不了, 被其他软件占用了, 所以可能么有办法通过热键显示软件. 目前windows下面的菜单图标确实没有反应, 是个BUG, 需要解决
