### ISSUE TITLE
open error

### ISSUE THREAD

**Issue by GuoouGcn** [Wox-launcher/Wox#3999]
![image](https://github.com/Wox-launcher/Wox/assets/23477046/bbe379ca-d8fd-4705-897e-eecda0b7a3dc)

![image](https://github.com/Wox-launcher/Wox/assets/23477046/9e5455af-4fb0-4823-94d9-137cf8d9cf1d)

**Comment by qianlifeng** [comment]
please upload log for debug: `~/.wox/log/log`

**Comment by GuoouGcn** [comment]
[log.txt](https://github.com/Wox-launcher/Wox/files/14730251/log.txt)

**Comment by qianlifeng** [comment]
> [log.txt](https://github.com/Wox-launcher/Wox/files/14730251/log.txt)

What do you mean open error? did you see the search box after start Wox? I didn't find problems from the log. By the way, I can only see one picture in your description.

**Comment by qianlifeng** [comment]
Please reopen if you still have issues.
