### ISSUE TITLE
Add Clipboard & Snippets plugin

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#4]
From Alfred official website:

> Access text you've saved to your clipboard with a keyboard shortcut, search past clips and paste them wherever you're working.

**Comment by qianlifeng** [comment]
7f769e00b9f925043bde68350f69f02f08481ca3

**Comment by miklide** [comment]
When I was thinking about snippets, I thought about what alfred team did with it:

> Do you frequently have to type your address, a block of text or website address? Typing them manually takes time, requires looking the same information up every time and leaves you with the possibility of making a typo error.
> Saving your text clip as an Alfred snippet ensures that the next time you need it, it'll save you time and be as perfect as the first time you typed it

![](https://www.alfredapp.com/help/features/snippets/snippets-editing.png)
![](https://www.alfredapp.com/help/features/snippets/snippets-preferences.png)
