### ISSUE TITLE
Systems commands feature requests

### ISSUE THREAD

**Issue by tdoerrich** [Wox-launcher/Wox#400]
Hi,

Just found out about this app today, and I'm super glad that something new besides Launchy finally exists! :)

If possible though I would love to have some more system commands to do directly from Wox rather than having to use the taskbar. (As having these would remove the whole use of the taskbar for me)
- Restart the computer from Wox (Maybe type Restart for that, and change the wox restart to WoxRestart? Not sure if this is a good idea, but maybe someone has a good idea how to do this!)
- Empty recycle bin from Wox

**Comment by bao-qian** [comment]
Thanks for suggestion. Since you are super glad about this project, would you mind to start it?

**Comment by tdoerrich** [comment]
I can look into it. Not sure if I can do it yet. Only coded games so far. :) But I will give it a go. Just forked Wox, and will see how it goes.

**Comment by bao-qian** [comment]
@SweBeat have a look at `Wox.Plugin.Sys`, the most important part is `Query` method.

**Comment by tdoerrich** [comment]
Yep, I think I might have done it. The bigger question is how good the code is. :) 

But I have tested both commands and they work. However, where have you found the icons you use for exiting and those? Would like to add a icon for restarting and emptying the recycle bin.

**Comment by bao-qian** [comment]
@qianlifeng should know about it.

**Comment by tdoerrich** [comment]
Cool, I'll wait for that answer so I can use some icons for it. And after that I will do a pull request. I've tried both the commands and had no issue with any of them.

**Comment by ishu3101** [comment]
You will find the icons in the images folder. The full path is: **Wox/Plugins/Wox.Plugin.Sys/Images/** in the source code repository

**Comment by tdoerrich** [comment]
Yup, was more thinking were you found them on internet. :) Or if you did them yourself? I found some I took and used now that was royalty free to use. But figured if you had a website you used to find them, that I should look in the same place as that might follow the same style.

**Comment by ishu3101** [comment]
You would have to ask @qianlifeng for that. Just use what you found on the internet that you are free to use and just use that.

**Comment by ishu3101** [comment]
Also missing are the `hibernate, show recycle bin and the screensaver` system command.

**Comment by tdoerrich** [comment]
True. Can look into that in the future. Not sure I can do it tonight.

**Comment by bao-qian** [comment]
@SweBeat Done. take a look: c95adb1f6c91c8cdc2d0564b1016b37b6fc505d2

**Comment by tdoerrich** [comment]
Thanks! :)

**Comment by vasselai** [comment]
@TobiasDev Hi Tobias, have you ever managed to implement the Hibernate command? That would be pretty helpful. I'm here trying to code it down myself, but still without success
