### ISSUE TITLE
Can't uninstall Wox2 Or at least stop it

### ISSUE THREAD

**Issue by iAutistic** [Wox-launcher/Wox#4005]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

I can't figure to stop Wox2 or uninstall it, I have tried doing everything but it seems not to work.
restarted the computer and still Wox2 still running nothing on the Task Manager

**Log**  
[log.txt](https://github.com/Wox-launcher/Wox/files/14841915/log.txt)

**Comment by qianlifeng** [comment]
Just kill the process in the task manager and then delete the wox exe file and `C:\Users\<yourname>\.wox` folder

**Comment by qianlifeng** [comment]
`Alt + space` is registered by other program, so you can't use hotkey to toggle Wox. And there is a known bug for the tray menus on windows, so in your case, the only way you exit the Wox is killing the process in the task manager, Sorry for the inconvenience

**Comment by iAutistic** [comment]
Yes, the issue is that I have already terminated the process in the task manager and removed all the files, but Wox is still running when I press `Alt + Space`.  even after I rebooted the computer

**Comment by qianlifeng** [comment]
> Yes, the issue is that I have already terminated the process in the task manager and removed all the files, but Wox is still running when I press `Alt + Space`. even after I rebooted the computer

Have you installed Wox v1?

**Comment by iAutistic** [comment]
I installed it and then removed it 

> > Yes, the issue is that I have already terminated the process in the task manager and removed all the files, but Wox is still running when I press `Alt + Space`. even after I rebooted the computer
> 
> Have you installed Wox v1?

**Comment by qianlifeng** [comment]
> Yes, the issue is that I have already terminated the process in the task manager and removed all the files, but Wox is still running when I press `Alt + Space`. even after I rebooted the computer

Really strange, it is running without list in the task manager? Have you tried this? https://github.com/Wox-launcher/Wox/wiki/Uninstalling-Wox

**Comment by iAutistic** [comment]
> > Yes, the issue is that I have already terminated the process in the task manager and removed all the files, but Wox is still running when I press `Alt + Space`. even after I rebooted the computer
> 
> Really strange, it is running without list in the task manager? Have you tried this? https://github.com/Wox-launcher/Wox/wiki/Uninstalling-Wox

Yeah

**Comment by iAutistic** [comment]
Fix it.
