### ISSUE TITLE
how to load settings to my plugin?

### ISSUE THREAD

**Issue by luisrudge** [Wox-launcher/Wox#401]
Say I need the user to specify some input in order to make my plugin work, how would I do that?

**Comment by bao-qian** [comment]
Sorry, working in progress... : https://github.com/Wox-launcher/Wox/issues/364

**Comment by lances101** [comment]
@luisrudge Right now, if you don't want to implement your own storage, the best way is to reference Wox.Infrastructure and work from there.

**Comment by luisrudge** [comment]
Yeah.. I'll wait for #393 and #364 before doing any plugins.
