### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by miskin1702** [Wox-launcher/Wox#4011]
Throw an error on startup and redirect here. And i want write here.

2024-04-20 12:34:42.0535|INFO|Wox.App|OnStartup|Begin Wox startup----------------------------------------------------
2024-04-20 12:34:42.2534|INFO|Wox.App|OnStartup|## Runtime Info
* Command Line: "C:\Users\Mustafa\AppData\Local\Wox\app-1.4.1196\Wox.exe" 
* Portable Mode: True
* Timestamp: 04/20/2024 12:34:42
* Wox version: 1.4.1196
* OS Version: Microsoft Windows NT 10.0.19045.0
* x64 OS: True
* x64 Process: True
* System Language: tr-TR
* Wox Language: en
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.09037
   * v4 Full 4.8.09037
   * v4.0 Client 4.0.0.0

2024-04-20 12:34:42.4436|FATAL|DispatcherUnhandledException|Error id: 1686b2fbc6c24618961f251ff4ed6d87
Exception begin --------------------

--------  continue in txt file-------------
[error.txt](https://github.com/Wox-launcher/Wox/files/15047613/error.txt)

**Comment by qianlifeng** [comment]
see #3937
