### ISSUE TITLE
How do I create custom backend functions?

### ISSUE THREAD

**Issue by SashvDave** [Wox-launcher/Wox#4023]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ ] Windows
- [ ] Linux

**Description**  

If I want to create a custom function in python and then call that as an "application" or "command" from the flutter UI, can you walk me through what the steps for that look like, including where I should define the python files, should I create them as an independent script or in a similar structure to these in the plugins folder, how to create and call the command as a query option in the flutter UI, etc.?

Thank you

**Comment by qianlifeng** [comment]
Sorry, python plugin is not ready. You can make nodejs plugin for now. If you interested in Nodejs plugin, you can refer [DeepL Plugin](https://github.com/Wox-launcher/Wox.Plugin.DeepL) as an example.

**Comment by SashvDave** [comment]
I cloned that repo into my plugins folder. Now how do I run it and make edits and see them in a development environment?

**Comment by qianlifeng** [comment]
1. Go to DeepL Plugin folder and run `pnpm run dev`
2. Go to Wox Plugin Manager setting page and add DeepL Plugin folder to the `Local Plugin Directories`
<img width="1197" alt="image" src="https://github.com/Wox-launcher/Wox/assets/1725475/5ece3e97-5825-424a-93da-781dc3b41ebb">

3. Now you can use `deep ` to activate this plugin. when you make any changes to the plugin, Wox should auto reload the plugin and give you notification
