### ISSUE TITLE
WOX2.0 will affect the normal closure of other windows after the Windows system is opened, and there will be lag

### ISSUE THREAD

**Issue by XiaoCheng991** [Wox-launcher/Wox#4029]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

WOX2.0 will affect the normal closure and minimization of other windows after the Windows system is opened, and there will be lag.

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
What do you mean affect? You can't close other windows when Wox is showing?

**Comment by XiaoCheng991** [comment]
> What do you mean affect? You can't close other windows when Wox is showing?

I know that, because I don't see that the version2 can't adapt windows
