### ISSUE TITLE
Conversations with LLM tools

### ISSUE THREAD

**Issue by SashvDave** [Wox-launcher/Wox#4043]
I saw that the plugin.go for LLMs has a conversations param, is the functionality implemented to have a back and forth or is it just limited right now to 1 message questions?

As in, if I ask my question in the command line, is the functionality already implemented for me to ask a follow-up?

**Comment by qianlifeng** [comment]
The original intention of the LLM tools plugin is to utilize the capabilities of LLM as a tool, such as a translator, website summary, etc. The LLM tool plugin itself does not provide continuous conversation capabilities, but we have opened up the LLM interface to plugins in the latest version (e.g., llm tool and theme plugin both use this interface), allowing plugin developers to create plugins that provide continuous conversation capabilities, similar to ChatGPT.
