### ISSUE TITLE
How is query function in go plugins re-triggered?

### ISSUE THREAD

**Issue by SashvDave** [Wox-launcher/Wox#4047]
I am trying to create a separate input field in the frontend and send the value to the backend. I log it in a couple different places and it seems to be returned fine, but it doesn't re-render/recall the query function within each plugin as it does when query.Search is changed. How do I edit that?

**Comment by qianlifeng** [comment]
You need to invoke [queryForPlugin](https://github.com/Wox-launcher/Wox/blob/3edbaca1e82d7451860ae440eddd894e40a4b0b4/Wox/plugin/manager.go#L598) to query plugins

**Comment by SashvDave** [comment]
So I've added a new text input field in preview view and when i pass it and it gets updated on the backend, I get a "result cache not found. Are there some places where I need to cache the existing response?
