### ISSUE TITLE
how to uninstall v2.0.0-nightly

### ISSUE THREAD

**Issue by ahmetcanisik** [Wox-launcher/Wox#4053]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

I am using Windows11 operating system. 
I downloaded the v2.0.0-nightly version and installed it. At the first startup, the wox screen appeared and I could turn it on and off with alt+space, which was great. When I typed any application name, for example Google Chrome, it did not return anything to me. When I tried to find the home directory to start as administrator I couldn't find it. I scanned it with everything, but I couldn't find it again, so I restarted the system. But this time my alt+space keys were not working. So I decided to delete it, but you will be surprised that it neither appeared in the install and uninstall applications panel nor could I find it in Everything. As a last resort, I came here to help me. I will delete this and install v1.0.

**Log**  
[log](https://github.com/user-attachments/files/15971994/log.txt)
[ui.log](https://github.com/user-attachments/files/15971989/ui.log)

**Comment by qianlifeng** [comment]
Refer https://wox-launcher.github.io/Wox/#/uninstall

**Comment by ahmetcanisik** [comment]
Thank you, actually I deleted it and installed [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) instead and it works for me.
