### ISSUE TITLE
Wox got an eeror

### ISSUE THREAD

**Issue by Dhok** [Wox-launcher/Wox#4055]
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 07/05/2024 07:48:14
Exception:
mscorlib
System.IO.IOException
Le processus ne peut pas accéder au fichier 'C:\Users\dhoka\AppData\Roaming\Wox\Cache\Image.cache', car il est en cours d'utilisation par un autre processus.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   à System.IO.FileStream..ctor(String path, FileMode mode)
   à Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) dans C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:ligne 99
   à Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) dans C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:ligne 44
   à Wox.Infrastructure.Image.ImageLoader.Initialize() dans C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:ligne 37
   à Wox.App.<OnStartup>b__10_0() dans C:\projects\wox\Wox\App.xaml.cs:ligne 52
   à Wox.Infrastructure.Stopwatch.Normal(String message, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 31
   à System.Windows.Application.OnStartup(StartupEventArgs e)
   à System.Windows.Application.<.ctor>b__1_0(Object unused)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2024-07-05.txt](https://github.com/user-attachments/files/16105425/2024-07-05.txt)

**Comment by qianlifeng** [comment]
see #3937
