### ISSUE TITLE
The search was incomplete

### ISSUE THREAD

**Issue by 609639910** [Wox-launcher/Wox#4059]
**Version**  

- [x] v1 (has no resource to fix)
- [ ] v2

**Platform**  

- [ ] Macos
- [ ] Windows
- [ ] Linux
![image](https://github.com/Wox-launcher/Wox/assets/56141772/19403ea6-8639-471a-952e-994fc6b317bf)

**Description**  

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

![image](https://github.com/Wox-launcher/Wox/assets/56141772/543a313d-66aa-45a2-81ad-6cb90a2f4b0d)
<img width="612" alt="Snipaste_2024-07-10_09-18-50" src="https://github.com/Wox-launcher/Wox/assets/56141772/8354089c-9300-4bf5-bd86-d4cdfeecfca6">
<img width="536" alt="Snipaste_2024-07-10_09-19-14" src="https://github.com/Wox-launcher/Wox/assets/56141772/9b7ff71d-cf71-4abc-80a3-6d722890678f">

**Comment by qianlifeng** [comment]
see #3937
