### ISSUE TITLE
The wox tray icon will be automatically hidden

### ISSUE THREAD

**Issue by Joackk** [Wox-launcher/Wox#4063]
**Version**  

- [ ] v1 (has no resource to fix)
- [√] v2

**Platform**  

- [ ] Macos
- [ √] Windows
- [ ] Linux

**Description**  

Although I turned on the display tray icon option, the wox tray icon would only be displayed for a moment and then disappeared. However, the process did exist. I tried to turn off the open tray option, but it still couldn't disappear automatically.

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
Yes, there are still some minor issues with the tray icon on Windows.

**Comment by qianlifeng** [comment]
https://github.com/Wox-launcher/Wox/commit/65122ab324a9baf894c0ae82749bb897b5b3cd65
