### ISSUE TITLE
just a restart

### ISSUE THREAD

**Issue by 3C0D** [Wox-launcher/Wox#4068]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ ] Windows
- [x ] Linux

**Description**  

You should specify in readme a restart maybe needed on windows after installation

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
It doesn't need a restart after installation, why do you say that?

**Comment by 3C0D** [comment]
Because it was blanked UI until a restart

**Comment by 3C0D** [comment]
but maybe it was a local bug
