### ISSUE TITLE
when started chrome can be closed or any tab added deleted

### ISSUE THREAD

**Issue by 3C0D** [Wox-launcher/Wox#4069]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ x] Windows
- [ ] Linux

**Description**  

After starting it. google chrome tab are freezed (can't open or close) and can't close chrome
**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
duplicate with #4036
