### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by Razvanxp** [Wox-launcher/Wox#407]
Could use a X button though.. if Wox is open with Alt+Space if you change your mind and don't actually open anything you have no way to close it, you must open something before the search window closes. Hope this remark is constructive.

//Razvan

**Comment by bao-qian** [comment]
You need hide, not close.
Type <kbd>ESC</kbd>
Please star Wox if you like Wox.

**Comment by highend** [comment]
May I ask if you could provide an additional setting that allows us to use ESC for clearing the input field of Wox (when it _has_ content) while still retaining the hide functionality (ESC hides Wox when the input field doesn't have any content)?
