### ISSUE TITLE
Cant work in ubuntu24.04

### ISSUE THREAD

**Issue by spirit223** [Wox-launcher/Wox#4073]
**Version**  

-  v2.0.0-nightly
-  wox-linux-amd64-20240820-b21be6

**Platform**  

- [ ] Macos
- [ ] Windows
- [x ] Linux
This is my system version info
```shell
$ cat /proc/version
# Linux version 6.8.0-41-generic (buildd@lcy02-amd64-100) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024
$ lsb_release -a
# No LSB modules are available.
# Distributor ID:	Ubuntu
# Description:	Ubuntu 24.04 LTS
# Release:	24.04
# Codename:	noble
```

**Description**  

I got the binary file named  `wox-linux-amd64-20240820-b21be6` from release page.
add executable permission with `chmod +x wox-linux-amd64-xxx`
and
try start it with `./wox-linux-amd64-xxx`
nothing was happen,  I can't get any error information, in my home, have nothing file or directory related to wox

**Log**  
nothing file or directory related to wox in my home

**Comment by ADernikas** [comment]
I have the same issue

**Comment by spirit223** [comment]
I am trying to build WoX on Ubuntu 
installed all dependency and run `just dev`, `go run main.go`.
after build complete, run `Flutter.UI.Wox/wox/build/linux/x64/release/bundle/wox`
I got the error message
```
flutter: MissingPluginException(No implementation found for method listen on channel dev.leanflutter.plugins/protocol_handler_event)
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676)
flutter: <asynchronous suspension>
```
In 'Wox.UI.Flutter/wox'， I was run `flutter pub get`, don't found any trouble.
maybe the `protocol handler` plugin being **incompatible** with Ubuntu?

**Comment by qianlifeng** [comment]
I haven't tested it on Ubuntu yet, so there may be some issues. PR welcome

**Comment by qianlifeng** [comment]
Will track on #3963
