### ISSUE TITLE
use directory opus open parent folder

### ISSUE THREAD

**Issue by lu161513** [Wox-launcher/Wox#4078]
**Version**  

- [x] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

Can "open parent folder" be opened with my Directory Opus? By default, it opens with the system's file manager; I want to use my Directory Opus. Additionally, regardless of whether it's V1 or V2.

**Comment by qianlifeng** [comment]
Where are you using "open parent folder"?  In the action list of the Apps?
