### ISSUE TITLE
Alt + space 调用搜索窗口时，光标无法自动聚焦到搜索窗口

### ISSUE THREAD

**Issue by lemon956** [Wox-launcher/Wox#4080]
**Version**  

- [ ] v1 (has no resource to fix)
- [√] v2

**Platform**  

- [ ] Macos
- [√ ] Windows 10
- [ ] Linux

**Description**  
当我在使用 Alt + space 调出 Wox 时，无法直接在输入框内输入进行搜索，需要使用鼠标进行点击，才能成功输入搜索内容

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by HopePAPA** [comment]
win11出现同样的问题，请问有解决方法了吗？

**Comment by sdgsgsdf** [comment]
In addition, sihu has another problem. Options after the outbound plug-in cannot be clicked with the mouse. For example, when I enter the st outbound setting option, I cannot click on it with the mouse. I need to use Enter to open it normally.

**Comment by qianlifeng** [comment]
Please test the latest version to see if the problem still exists
