### ISSUE TITLE
Localize Wox Plugins forgotten strings

### ISSUE THREAD

**Issue by vankasteelj** [Wox-launcher/Wox#409]
This line lacks localization :)

https://github.com/Wox-launcher/Wox/blob/7657a309e6645decefbed60ec6891bef8b69574e/Plugins/Wox.Plugin.PluginIndicator/PluginIndicator.cs#L25

**Comment by bao-qian** [comment]
- [ ] force `subtile` using `GetTranslation`, e.g. `subtile` is not `string`, is `Message`.
- [ ] force `MessageBox` using `GetTranslation`, e.g. same as above.

**Comment by bao-qian** [comment]
For now, just translate the main interface is enough.
