### ISSUE TITLE
无法检测到everything

### ISSUE THREAD

**Issue by iamqiz** [Wox-launcher/Wox#4095]
**Version**  

- [x] v1 (has no resource to fix)
- [] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

我everything明明在运行, 却检测不到(搜索时提示我 everything client没有运行)

**Comment by iamqiz** [comment]
@qianlifeng  v2版本能检测到everything,但是 v2的设置页面怎么打开? 右键菜单只有这两个?
![PixPin_2024-11-03_08-12-22](https://github.com/user-attachments/assets/d7b805a3-e514-40c9-9871-dade2e7bb86a)

**Comment by qianlifeng** [comment]
> @qianlifeng v2版本能检测到everything,但是 v2的设置页面怎么打开? 右键菜单只有这两个? ![PixPin_2024-11-03_08-12-22](https://private-user-images.githubusercontent.com/48077521/382514958-d7b805a3-e514-40c9-9871-dade2e7bb86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDMyNDYsIm5iZiI6MTczMDYwMjk0NiwicGF0aCI6Ii80ODA3NzUyMS8zODI1MTQ5NTgtZDdiODA1YTMtZTUxNC00MGM5LTk4NzEtZGFkZTJlN2JiODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDAzMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NDRkNzExZWRjYmE0YTg3ZDcyMTU0YmMyN2E0ODljYzEwNWRmYjVlMWNmZTE4YWY5MzQ2ZDBjNjVjMzZjMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gZibG2xhLk8TWelFBsgttZAQix0c5WHSJ35AJ9I0U9I)

搜索框里面输入setting
<img width="800" alt="image" src="https://github.com/user-attachments/assets/1b84234b-d9d4-4ea6-bbe9-c68e47855297">
