### ISSUE TITLE
应用突然崩溃

### ISSUE THREAD

**Issue by nottyjay** [Wox-launcher/Wox#4097]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ x] Windows
- [ ] Linux

**Description**  
突然崩溃，无前置操作

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows
[2024-11-05.txt](https://github.com/user-attachments/files/17625772/2024-11-05.txt)

**Comment by qianlifeng** [comment]
you are now using v1, please see #3937 and try v2
