### ISSUE TITLE
[v2]wox设置窗口没关闭的情况下按alt+space会显示wox设置窗口而不是搜索框

### ISSUE THREAD

**Issue by iamqiz** [Wox-launcher/Wox#4098]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

如果wox设置窗口没关闭,那么再次按下alt space时,弹出的框里会是wox设置窗口,而不是正常的搜索框

![PixPin_2024-11-09_15-38-14](https://github.com/user-attachments/assets/b272ee39-cc5d-4e38-81f8-ad33d6393ca5)

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
奇怪, 我并没有办法复现. 代码的处理逻辑是: 在wox设置窗口打开的情况, 再次按alt + space会退回到搜索框. 我这边的行为也是这样的

**Comment by qianlifeng** [comment]
你是每次都复现么? 还是有一些其他步骤触发

**Comment by iamqiz** [comment]
@qianlifeng 
稳定复现:
按下alt space ,输入setting打开 设置窗,按下alt-tab或者鼠标点击其它窗口, 切换到其它窗口, 然后按下alt space 这时弹窗就有问题了,再按一次alt space 又正常了

**Comment by iamqiz** [comment]
按下alt space ,输入setting打开 设置窗, 这时继续按alt space,设置窗口变成搜索输入框,再按alt space 搜索输入框消失 
这些都没问题,
所以`按下alt-tab或者鼠标点击其它窗口, 切换到其它窗口`  这一步导致了问题
