### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by satgo1546** [Wox-launcher/Wox#41]
In fact I'd like to use amo (AVG Maker Orange) instead of cgwz to run ~~the rubbish,~~ 橙光文字游戏制作工具, so alias would be very useful here.

**Comment by orzFly** [comment]
I don't think it's necessary in Wox. You can just create a shortcut named "amo" in the Start Menu.

**Comment by satgo1546** [comment]
Good idea! But this will add a lot of new shortcut in my Start Menu... BTW I can't execute 'calc' for calculator but 'jsq' is right... That's really a problem because only 'calc' or 'calc.exe' is right in _Windows Run_ dialog.

**Comment by orzFly** [comment]
Try ">calc". However I am going to add these app paths into program list.
Thank you for your idea.

**Comment by orzFly** [comment]
As #42 has finished, this should be closed now.
