### ISSUE TITLE
 [v2] 给搜到的结果加上菜单

### ISSUE THREAD

**Issue by iamqiz** [Wox-launcher/Wox#4101]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ ] Windows
- [ ] Linux

**Description**  

搜到快捷方式或者exe后,有时并不想打开
而是想复制路径,或者是打开所在的目录
所以建议加上菜单

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows

**Comment by qianlifeng** [comment]
已经有此功能: alt + J

<img width="800" alt="image" src="https://github.com/user-attachments/assets/567738fa-10c3-440c-81b3-8cd923b763f8">

**Comment by iamqiz** [comment]
"open containing folder" 有bug, 有时不是打开exe所在的目录,而是运行exe

**Comment by qianlifeng** [comment]
最新版应该解决了
