### ISSUE TITLE
When will a new release be made?

### ISSUE THREAD

**Issue by tomasnorre** [Wox-launcher/Wox#4103]
The latest nightly build is made Oct 30, 2023. When can we expect a new release?

Or has the release process changed? I have just discovered this project today.

**Comment by qianlifeng** [comment]
Although the nightly build was created on Oct 30, 2023, it is compiled with every commit, and you can get the latest compiled version from the nightly compilation. The official version of v2 is not yet complete, Macos has the best usability, windows is second, and there are still some big problems to be solved on linux platforms.

**Comment by tomasnorre** [comment]
Thanks. The date is quite confusing then.

**Comment by andrumak** [comment]
any eta on the stable release? (for the windows at least). 
I have some issue with the latest v1 build, but it seems that you are not working on patches for v1 and I have to wait for the v2 as it is probably fixed there already 🤔

**Comment by qianlifeng** [comment]
> any eta on the stable release? (for the windows at least). I have some issue with the latest v1 build, but it seems that you are not working on patches for v1 and I have to wait for the v2 as it is probably fixed there already 🤔

Sorry, there is no specific release time yet, as there are still many bugs to be fixed.

**Comment by qianlifeng** [comment]
I have changed the title of the latest nightly build, which should be more make sense now.
