### ISSUE TITLE
Link to "theme AI" configuration page returns 404

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#4105]
The text on [this page](https://wox-launcher.github.io/Wox/#/ai_theme) has a link for "AI settings".

The latter link is missing (404).

Please fix the link.

Also, is there some place else I can see how to enable the theme ai feature?

**Comment by qianlifeng** [comment]
The doc has been updated. https://wox-launcher.github.io/Wox/#/ai_settings. After configure the AI provider, you can select the AI model in the theme manager setting page.
![image](https://github.com/user-attachments/assets/4de2db79-c1c3-4d95-87d1-fe291c71c899)
