### ISSUE TITLE
Documentation about writing plugins returns a 404 page

### ISSUE THREAD

**Issue by Mechazawa** [Wox-launcher/Wox#4106]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

**Platform**  

- [ ] Macos
- [ ] Windows
- [ ] Linux

**Description**  

The documentation on writing plugins does not work. When navigating to the page it returns a 404.

https://wox-launcher.github.io/Wox/#/vue

<img width="148" alt="image" src="https://github.com/user-attachments/assets/513b5be0-7322-4684-a71c-6b9027563c02">

**Comment by qianlifeng** [comment]
Yes, because of the complex of the plugin part, the documentation is not ready. If you want to develop plugins, you can refer to the
https://github.com/Wox-launcher/Wox.Plugin.Template.Nodejs
https://github.com/Wox-launcher/Wox.Plugin.DeepL
https://github.com/Wox-launcher/Wox.Plugin.Spotify
