### ISSUE TITLE
Can't find some applications via the app search

### ISSUE THREAD

**Issue by Cateds** [Wox-launcher/Wox#4108]
**Version**  

- [ ] v1 (has no resource to fix)
- [x] v2

The Version is *wox-windows-amd64-20241122*

**Platform**  

- [ ] Macos
- [x] Windows
- [ ] Linux

**Description**  

When using application search, both v1 and v2 have the problem that certain applications cannot be searched, such as Keil uVision 5 here.

**Log**  

The log file (renamed as log.log because GitHub does not support the file without extension name) is uploaded. So do the screenshots.
[log.log](https://github.com/user-attachments/files/17904966/log.log)
![屏幕截图 2024-11-25 230707](https://github.com/user-attachments/assets/66effd46-986a-4840-b407-1a3a894ada58)
![屏幕截图 2024-11-25 222257](https://github.com/user-attachments/assets/defca5a0-7193-4d5d-86a3-a815fc42618c)

**Comment by qianlifeng** [comment]
where is Keil uVision 5 installed, `C:\Program Files`?

**Comment by Cateds** [comment]
The path is `C:\Users\thisi\AppData\Local\Keil_v5\UV4`
I think it's the default path for the applications installed for one user.

**Comment by qianlifeng** [comment]
Should be fixed in the latest release.
