### ISSUE TITLE
Feature Request:  Right arrow(→) on a file to activate detailed menu.

### ISSUE THREAD

**Issue by redreamality** [Wox-launcher/Wox#4109]
## What happens
Currently, the right arrow simply does nothing.

## Expected behaviour
When reach/selected a search result, right arrow key will activate a detailed menu, which currently can only be activated via mouse right click on the entry.

## Other useful info
I'm migrating from Listary.

## Version
I'm testing with v1.4.1196 as recommended in the release page.

**Comment by qianlifeng** [comment]
Right arrow is used to move the cursor in your search text. By the way, please try v2, v1 is feature freeze now.
