### ISSUE TITLE
部分主题失效

### ISSUE THREAD

**Issue by liugongxun1103** [Wox-launcher/Wox#4116]
**Version**  
1.4.1196
- [x] v2

**Platform**  
- [x ] Windows

**Description**  

选择了主题BlurBlack和BlurWhite效果都和BlackAndWhite一样

**Log**  

please upload wox log to help identify your bug.
- `~/.wox/log/log` if you use macos or linux
- `C:\Users\<yourname>\.wox\log\log` if you use windows
[log.log](https://github.com/user-attachments/files/18243675/log.log)

**Comment by liugongxun1103** [comment]
![bug1](https://github.com/user-attachments/assets/61ba0bee-ddbe-49c2-9c23-6b64556d503a)
![bug2](https://github.com/user-attachments/assets/57dfa072-917f-4dca-80cb-a441c337ed63)

**Comment by qianlifeng** [comment]
please see https://github.com/Wox-launcher/Wox/discussions/3937 and try v2
