### ISSUE TITLE
Icons on tray

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#413]
![screenclip](https://cloud.githubusercontent.com/assets/7104786/11482404/cbdd09d2-9774-11e5-976f-e12923c72e7a.png)

I get a bunch of wox icons on tray when I restart wox (with wox command). Also, I get a weird search icon I did not have with wox v1.1.

Awesome to have this project as alternative for alfred on windows. Cheers guys.

Build 1.2.603, Windows 10x64.
Please advice if is not the correct feedback format/channel.

**Comment by bao-qian** [comment]
That search icon is for [everything](http://www.voidtools.com/).
It's essential to search files.

**Comment by bao-qian** [comment]
Try again with build 1.2.605.

**Comment by rickmed** [comment]
The duplicated icons is fixed!
No way to hide the search icon? Or a future feature planned to incorporate it to wox as opposed to a separated program?

**Comment by bao-qian** [comment]
![option](http://i.imgur.com/JyZBQo1.png)

**Comment by rickmed** [comment]
Awesome. Thanks. Maybe setting it off by default?

**Comment by bao-qian** [comment]
As I said. This is a separate application. So I can't.
