### ISSUE TITLE
clock plugin misbehaving wox 1.2

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#415]
Clock plugin worked fine with v1.1.

When the clock ends (should play a sound). I get the exception:

Could not find a part of the path 'D:\Program Files\WoxBeta\Plugins\Wox.Plugin.SimpleClock-9dc30b5a-10a7-4182-8ccc-43d1b884e1d6\Sounds\beepbeep.mp3'.

My windows install is in C drive, so it seems wox is looking for the sound in the wrong drive name.

build 1.2.605, win10x64.
Cheers.

**Comment by bao-qian** [comment]
@lances101

**Comment by rickmed** [comment]
got it fixed by changing the path to the sound files in the plugin settings. Not sure why the path is hard coded to an aboslute path to the "D:" drive.

**Comment by lances101** [comment]
@ricmed205 Oh... I must've uploaded it with the settings file. Sorry for that. It generates the path if no path is provided based on Wox's location and I must've forgotten to delete the config before uploading. Will fix it now.

@happlebao This issue can be closed. 

**Edit**: uploaded a new version without the config
