### ISSUE TITLE
cmd bug

### ISSUE THREAD

**Issue by monsteryip** [Wox-launcher/Wox#418]
build:1.2.610, Windows 10x64
执行完cmd命令后直接关闭串口，勾选了 执行后不关闭窗口 也没用

**Comment by bao-qian** [comment]
不好意思。这是个已知bug。

**Comment by monsteryip** [comment]
好的~请问您有赞助链接吗~我想要支持下你们

**Comment by bao-qian** [comment]
主页有[链接](https://github.com/Wox-launcher/Wox#wox-----)
这是给原作者 @qianlifeng 的，我现在不缺钱就不用了。

**Comment by bao-qian** [comment]
use #141 to discuss in the future.
用 #141 来追踪。
