### ISSUE TITLE
Provide custom index for program plugin.

### ISSUE THREAD

**Issue by pokoblin** [Wox-launcher/Wox#42]
什么时候能推出自定义索引项的功能？

**Comment by orzFly** [comment]
谢谢，我正有此意加上这个功能。之前看到 #41
的时候我就在想，可以加上自定义索引文件夹的功能来代替那个别名功能。我打算让程序扫描这个文件夹中所有的快捷方式。我认为这样已经完全足够使用了。

话说，我个人现在在 Windows 上使用的大部分工具软件都是便携版，其中有很多
PortableApps，中午我在优化程序搜索的时候我就想过这个问题。我打算顺便兼容一下 PortableApps.com
的程序菜单的格式，这样也可以将 Wox 放进 U 盘，作为 U 盘中工具的启动器。（现在基本上都是 Windows 7 / 8 了，.NET
也不是问题了）

与此同时，我觉得可以留一个搜索结果优先级的设置，可以将来自某个位置的结果提前，这主要是为了方便便携版使用者，将来自 U
盘的程序提前（这种情况下，开始菜单中的结果反而不会非常有用）。

界面似乎可以这样，其中前三个因为是特殊路径所以不可删除，但是可以禁用。而后面两个是用户自己添加的，可以自己删改。

[image: Inline image 1]

— orzFly / Yeechan Lu

**Comment by orzFly** [comment]
图片在这里：

![image](https://f.cloud.github.com/assets/158528/2446048/c71fcad2-ae7e-11e3-8fa8-bcde425e1d01.png)

**Comment by pokoblin** [comment]
看起来很棒，这应该正是大多数人需要的功能，我现在用的[Executor](http://executor.dk/)，需要把每个需要加入索引的软件拖进去，当然这样也可以，但他没有提供导出配置的功能，每次我重装系统都要重新拖。

还是在一个文件夹里放快捷方式最方便，我[Free Launch Bar](http://www.freelaunchbar.com/)的时候就是用这种方式来管理启动项的。

感谢开发这么好用的软件，期待此功能早日发布。

**Comment by orzFly** [comment]
GUI will be add in the following days. However, we can edit `config.json` on our own and modify ProgramSources at present:

``` json
    ........
    "ProgramSources": [
      {
        "Location": null,
        "Type": "CommonStartMenuProgramSource",
        "BounsPoints": 0,
        "Enabled": true,
        "Meta": null
      },
      {
        "Location": null,
        "Type": "UserStartMenuProgramSource",
        "BounsPoints": 0,
        "Enabled": true,
        "Meta": null
      },
      {
        "Location": null,
        "Type": "AppPathsProgramSource",
        "BounsPoints": -10,
        "Enabled": true,
        "Meta": null
      },
      {
        "Location": "C:\\MyShortcuts",
        "Type": "FileSystemProgramSource",
        "BounsPoints": -10,
        "Enabled": true,
        "Meta": null
      },
      {
        "Location": "C:\\PortableApps",
        "Type": "PortableAppsProgramSource",
        "BounsPoints": 10,
        "Enabled": true,
        "Meta": null
      }
    ],
    ........
```
