### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by EXPLOR3R** [Wox-launcher/Wox#422]
不知从何时起，每次启动时都会提示throw了一个exception没有handle。
关掉提示窗口后Wox正常运行。
细节如图：
![wox_1](https://cloud.githubusercontent.com/assets/3682816/11760548/71b73cdc-a054-11e5-81a5-6b6505798aba.png)
![wox_2](https://cloud.githubusercontent.com/assets/3682816/11760550/755af7de-a054-11e5-9465-ea92e62ad0a9.png)

**Comment by bao-qian** [comment]
给个大图啊。。。
复制也行啊。。。

**Comment by bao-qian** [comment]
1.1啊。下[最新版](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0-build)
