### ISSUE TITLE
Noticeable delay when activating Wox for the first time after launching

### ISSUE THREAD

**Issue by forkburn** [Wox-launcher/Wox#424]
When activating wox using the hotkey for the first time, there is a 2~3 second delay before the wox window appears. This delay will not appear in any subsequent activation of the wox window.

This delay will not appear again even if I close and restart wox. But if I restart my PC, this delay can be reproduced.

**Comment by happlebao** [comment]
please follow [this simple guide](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-report-bug)

**Comment by bao-qian** [comment]
please follow [this simple guide](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-report-bug) to provide more information

**Comment by happlebao** [comment]
close due to no response.

**Comment by bao-qian** [comment]
close due to no response, reopen it if you have more info.
