### ISSUE TITLE
安装插件显示无法连接到远程服务器

### ISSUE THREAD

**Issue by halois** [Wox-launcher/Wox#425]
输入 
wpm install Browser Bookmarks
之后显示无法连接到远程服务器

版本1.2.0
异常类型System.Net.WebException
堆栈信息   在 System.Net.HttpWebRequest.GetResponse()
   在 Wox.Plugin.PluginManagement.HttpRequest.CreateGetHttpResponse(String url, IHttpProxy proxy) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\HttpRequest.cs:行号 32
   在 Wox.Plugin.PluginManagement.Main.InstallPlugin(String queryPluginName) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 137
   在 Wox.Plugin.PluginManagement.Main.Query(Query query) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 0
   在 Wox.Core.Plugin.PluginManager.ExecutePluginQuery(PluginPair pair, Query query) 位置 c:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 193

ps. 现在能否通过下载.wox文件来安装插件

**Comment by bao-qian** [comment]
不好意思。证书过期了。
下[最新版](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0-build)

**Comment by qianlifeng** [comment]
@halois 可以的，直接下载.wox文件，然后拖到Wox里面就可以安装

**Comment by halois** [comment]
@qianlifeng  找到下载的地方了
