### ISSUE TITLE
1.2 beta2 回车和上下键选择没反应

### ISSUE THREAD

**Issue by pengzhxyz** [Wox-launcher/Wox#428]
win10 64 位，用1.2 beta2，启动速度加快。但是致命问题是回车无法打开，上下也无法选中侯选项。
不知是什么问题啊，偶尔(几率很小)会正常一下。
![1](https://cloud.githubusercontent.com/assets/15181343/11776196/3164dca6-a280-11e5-93a5-55e271346d3d.gif)

**Comment by happlebao** [comment]
感谢反馈。截一个可以正常选中候选项的图。

**Comment by happlebao** [comment]
之前那个 beta 正常是吗？

**Comment by bao-qian** [comment]
原来是gif啊。刚手机端看不了。
这在 .net 4.5 下有问题。
下 .net 3.5:
https://www.microsoft.com/en-us/download/details.aspx?id=14037

**Comment by bao-qian** [comment]
顺便报一下你的 .net version。下这个软件：http://www.asoft.be/prod_netver.html
把像这样的内容贴上来：

```
<32Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8669
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6 Unknown build:394271 (CLR:4.0)
```

**Comment by pengzhxyz** [comment]
<32Bit>
4.6.127.1
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319
4.6.127.1
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 4.6.1  (CLR:4.0)

**Comment by bao-qian** [comment]
你的 win 10 是全新安装，不是升级升上来的是吧？

**Comment by pengzhxyz** [comment]
是Win8.1 用iso更新 升上来的

**Comment by bao-qian** [comment]
装了 .net 3.5 还有问题吗？

**Comment by pengzhxyz** [comment]
装了。net3.5 好用了。
但是发现个小问题，打开的时候有时会闪一下

**Comment by bao-qian** [comment]
最好能录段视频……

**Comment by pengzhxyz** [comment]
视频上传不了，我放在百度网盘里
http://pan.baidu.com/s/1mht9yOw

**Comment by bao-qian** [comment]
以后闪烁问题用 #435 来追踪。
无响应问题用 #393 来追踪。
