### ISSUE TITLE
Wox crashes on startup if an other program is already listening to the shortcut

### ISSUE THREAD

**Issue by moser96** [Wox-launcher/Wox#430]
Hi,
First at all I have to say this is a really nice launcher! Thx :smile: 

But I found a bug and I'd be happy if it gets fixed! If I start Wox, wox crashes because an other running program is already listening to that shortcut.

**Comment by bao-qian** [comment]
What version of wox? Which shortcut? Which program?

**Comment by moser96** [comment]
Version 1.2, Alt + Space, my own program

**Comment by bao-qian** [comment]
1.2 beta or 1.2 beta.2 ?

**Comment by moser96** [comment]
Sry I forgot about this issue.
I'm using v1.2.0-beta.2.

**Comment by bao-qian** [comment]
hi, this should be fixed now.

try again with [build 1.2.788](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.788/artifacts)

![demo](http://i.imgur.com/AWksb93.png)

please confirm it if it indeed resolved.
please reopen the issue if not.
