### ISSUE TITLE
安装插件时崩溃

### ISSUE THREAD

**Issue by pengzhxyz** [Wox-launcher/Wox#433]
是网站后台又挂了么  
在 System.Net.HttpWebRequest.GetResponse()
   在 Wox.Plugin.PluginManagement.HttpRequest.CreateGetHttpResponse(String url, IHttpProxy proxy) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\HttpRequest.cs:行号 32
   在 Wox.Plugin.PluginManagement.Main.InstallPlugin(String queryPluginName) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 137
   在 Wox.Plugin.PluginManagement.Main.Query(Query query) 位置 c:\projects\wox\Plugins\Wox.Plugin.PluginManagement\Main.cs:行号 61
   在 Wox.Core.Plugin.PluginManager.ExecutePluginQuery(PluginPair pair, Query query) 位置 c:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 193
![image](https://cloud.githubusercontent.com/assets/15181343/11801301/70dce622-a31f-11e5-94a1-7a8fd77b19c2.png)
![image](https://cloud.githubusercontent.com/assets/15181343/11801307/785c16d4-a31f-11e5-96b6-a70f63c70bb8.png)
一排错误
![image](https://cloud.githubusercontent.com/assets/15181343/11801318/90a2a51e-a31f-11e5-934c-33929677d6e3.png)

**Comment by bao-qian** [comment]
1. 没挂。我可以装。但我不在国内，不清楚。。。
   你试下这个链接能不能访问： `http://api.getwox.com/plugin/`
2. 版本？ `1.2 beta.2` 吗？
3. 不要放在 `c:\projects`，放在 `c:\users\xxx\wox`

**Comment by pengzhxyz** [comment]
1. api链接可以访问，可以返回json数据
2. 1.2 beta
3. 放在哪儿都出错。

试了下1.2 beta2 可以访问服务器安装插件，但是Alt+空格会出现时闪烁一下，不能忍。。

原来用1.2 beta 正常，现在无法连接服务器，无法安装插件。暂时只能手动安装插件了

**Comment by bao-qian** [comment]
1.2 beta.2 就是用来修复插件安装问题的啊……

**Comment by bao-qian** [comment]
闪烁是你在 #428 里说的那个闪烁吗？

**Comment by pengzhxyz** [comment]
对，是#428中说的那个闪烁，录了个视频http://pan.baidu.com/s/1mht9yOw

**Comment by bao-qian** [comment]
以后闪烁问题用 #435 来追踪。
