### ISSUE TITLE
Support the user's locale settings in calculator

### ISSUE THREAD

**Issue by bb** [Wox-launcher/Wox#436]
Hi,

I'm using Wox in a German Windows environment with German local where the decimal separator is not `.` but `,` and thus, the key between `0` and `enter` on the Num block of the keyboard is `,` etc.

Thus, I'd like Wox to use the Decimal Symbol which is configured in Control Panel / Region and Language /  Additional.

**Comment by mortenbangjustesen** [comment]
Same in Denmark. Used Launchy earlier which supported this

**Comment by bao-qian** [comment]
implemented: https://ci.appveyor.com/project/happlebao/wox/build/1.3.432/artifacts

**Comment by bb** [comment]
Works great, thanks!
