### ISSUE TITLE
不能固定wox的启动位置

### ISSUE THREAD

**Issue by lqzhgood** [Wox-launcher/Wox#439]
我在Wox\Config\config.json中设置
  "WindowLeft": 866.0,
  "WindowTop": 630.0,
  "RememberLastLaunchLocation": true,
关掉wox后重新打开， WOX还是在左上角，而且每次坐标都不同。

启动后的坐标依次在  52/52 130/130 208/208 循环。

**Comment by bao-qian** [comment]
试一下 [build 1.2.612](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.612/artifacts) （下载 release-binary). 这是 PR #423 的一部分。

**Comment by bao-qian** [comment]
以后用 #271 来追踪这个问题。
