### ISSUE TITLE
reloadplugin argument creates duplicate

### ISSUE THREAD

**Issue by oxysoft** [Wox-launcher/Wox#440]
example: http://i.imgur.com/0ObuNdv.png

on a fresh installation of 1.20-beta2

**Comment by bao-qian** [comment]
hi @oxysoft, remind me, what did you mean by "reloadplugin"?

**Comment by oxysoft** [comment]
The commandline argument

i.e:
`Wox.exe reloadplugin`

**Comment by bao-qian** [comment]
Sorry, the command line argument is buggy for a long time, and it won't be fixed in wox 1.2.

**Comment by bao-qian** [comment]
CLI has been removed, and won't be supported.
