### ISSUE TITLE
建议：半透明风格添加窗口边框或阴影

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#442]
![123](https://cloud.githubusercontent.com/assets/9709390/12028969/593bb456-ae1b-11e5-9026-02474ad44f7c.png)

毛玻璃风格确实很好看，但是没有边框或阴影来过渡的话，
看起来和背景融为一体，不容易识别，而且看起来也不好看。

**Comment by bao-qian** [comment]
边框可以自己加。
Set the `BorderThickness` of `WindowBorderStyle` to **n**

```
<Style x:Key="WindowBorderStyle" BasedOn="{StaticResource BaseWindowBorderStyle}" TargetType="{x:Type Border}">
        <Setter Property="BorderThickness" Value="n" />
    </Style>
```
