### ISSUE TITLE
Enhance wox to display pictures from http

### ISSUE THREAD

**Issue by CNpunkt** [Wox-launcher/Wox#443]
For my plugin [SwiftTweet](http://bit.ly/1mlMaY4) (a Twitter plugin for Wox) it would be great to enhance Wox so it can display pictures in the search result list directly from an http source without saving it to a local drive.

I would be happy about this feature because i'm planning to enhance my plugin so i can display a the users image regarding to a tweet directly from Twitter (see [SwiftTweet issue#3](https://github.com/NCiher/Wox.Plugin.SwiftTweet/issues/3#issue-123098150)).

**Comment by bao-qian** [comment]
What you should do is cache the user image on the local disk, then set `IcoPath` in `Result`

**Comment by CNpunkt** [comment]
I already tried your solution but this was horrible for the performance.
There are only minor changes needed to directly display http images in the result list of wox. I will create a pull request for this soon.

**Comment by bao-qian** [comment]
No, all internet resource should be cached.

**Comment by lances101** [comment]
Cache it in a background thread and then only push the results. Wox itself should **not** be pulling http images, **imo**

**Comment by CNpunkt** [comment]
Ok thanks for your help.
