### ISSUE TITLE
Change browser of URL opening

### ISSUE THREAD

**Issue by symsmith** [Wox-launcher/Wox#445]
Hey everyone,

Is it possible to open URLs in different browsers?

Thanks

**Comment by bao-qian** [comment]
That's not a wox problem, go search for "how to change default browser for windows".

**Comment by lances101** [comment]
I think what @symsmith meant is that one url is opened in a bunch of different browsers. This could be done via a plugin, but it does not sound as something that should be included as default functionality.

**Comment by symsmith** [comment]
That's not what I meant; what I was asking for was to do like : "chrome google.com" to open google on chrome and "safari google.com" to open it on safari.

Sorry for inconvenience and for the unclarity of the question.

@symsmith

**Comment by bao-qian** [comment]
Sure is possible, write a plugin by yourself if you want.

**Comment by symsmith** [comment]
Ok I'll check if I can do that thanks

**Comment by lances101** [comment]
[Check the documentation on getwox.com](http://doc.getwox.com/en/plugin/create_plugin.html) for more info

**Comment by bao-qian** [comment]
the doc is outdated, open issue if you need.

**Comment by symsmith** [comment]
ok thanks

**Comment by symsmith** [comment]
Bonjour Wox-launcher/Wox,
Smithsymeon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/PLqXrR/0oy/?hg=1GgudRakvK pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=a2d5f8f1&email=reply@reply.github.com.&hg=1GgudRakvK
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by symsmith** [comment]
Bonjour Wox-launcher/Wox,


Smithsymeon vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/PLqXrR/0oy/?hg=wgZR5FAJEB pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=a2d5f8f1&email=reply@reply.github.com.&hg=wgZR5FAJEB
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
