### ISSUE TITLE
Index only folder names

### ISSUE THREAD

**Issue by druellan** [Wox-launcher/Wox#446]
Hi! I'm testing V1.2 beta, and something I'm missing or I don't know how to achieve is the ability to index only folder names and not filenames.
What I need is a way to index only folder names inside /Documents (ideally only 1 or 2 depth).

Using the Folder plugin: I can add folders, but one by one manually.
Using the Program plugin: I can only filter by suffix, and I don't know how to match folders.
No idea how to handle this using Everything, but seems overkill.

I believe Program can be tweaked to achieve this, somehow, but not sure if this is currently possible?

Thanks!

**Comment by bao-qian** [comment]
Why you want to do this?
The search for files and folders is handled by Everything, you can configure everything to search specific location.

**Comment by druellan** [comment]
Well, I'm porting my configuration from Launchy, and I never used it as a file index, since my projects are full of duplicates an redundant files: the folder name is the only thing unique. I ended up indexing only folder names and some filetypes.

I'm going to try use Everything as you suggest.
Thanks!

**Comment by bao-qian** [comment]
Thanks for choosing Wox!
Everything is very powerful and flexible.
You can search file under given folder as show below.
![show](http://i.imgur.com/2vh3Unz.png)
