### ISSUE TITLE
Folder plugin should add a trailing slash the first time you select a folder

### ISSUE THREAD

**Issue by druellan** [Wox-launcher/Wox#447]
Hi!
A small detail I've found using the Folder plugin:

When you first select a folder, the trailing slash is missing, and you need to manually add it if you want to keep searching subfolders.

![2015-12-30 21_30_48-wox](https://cloud.githubusercontent.com/assets/6965667/12059597/2c238bba-af3d-11e5-85d2-c8a339bbabda.png)

If you then navigate to another folder, the trailing slash is added.

![2015-12-30 21_31_21-google translate - firefox developer edition](https://cloud.githubusercontent.com/assets/6965667/12059599/34b5c4f0-af3d-11e5-9efd-75d948ab0177.png)

**Comment by happlebao** [comment]
Hi. thanks for feedback, what your wox version?
As you see in for following gif, I can't reproduce this.
http://i.imgur.com/QGl1Gbo.gifv

Could you try [latest build](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-install-latest-build), and record a gif (you can download ShareX to record gif).

**Comment by bao-qian** [comment]
Hi. thanks for feedback, what's your wox version?
As you see in for following gif, I can't reproduce this.
![gif](http://i.imgur.com/QGl1Gbo.gif)

Could you try [latest build](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-install-latest-build), and record a gif (you can download ShareX to record gif).

**Comment by druellan** [comment]
I'm using this release: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta.2
I'm going to try again using the latest build.

**Comment by druellan** [comment]
Found the problem, sorry for the vague report, lets try this again.
- Go to the settings -> plugins -> Folder plugin
- Ad a Folder shortcut, for example, c:\users\xxxx\Documents
- Close the settings window, and open WOX
- Type the name of the folder added (ex: "documents"), highlight the shortcut and push enter

In this case, the path has no trailing slash, but if you start to explore the folder tree (the way you did just typing "c:"), the slash is added.

That makes sense?

**Comment by lances101** [comment]
@druellan yep, confirmed. The last slash is not added. 

There are two ways of fixing this: we could either store the path with the trailing slash or add the trailing slash upon selecting the result. I suggest going for the second one.

**Comment by druellan** [comment]
Thanks lances101.
