### ISSUE TITLE
Launch and last launch location regressions

### ISSUE THREAD

**Issue by koobs** [Wox-launcher/Wox#449]
In the latest CI build (`1.2.639`) and the latest beta `1.2.0 (beta 2)`, Wox:
- Does not remember (or restore) _last launch location_ across restarts
- Launches the query input on my systems second monitor (2 x 1920x1200 in extend mode)

Reproduction steps:
- Wox -> Settings -> ☑ Remember last launch location
- Move Wox query window somewhere (remembering where)
- Close Wox
- Start Wox
- Note that Wox isn't opened in the location you last moved it

**Comment by bao-qian** [comment]
Try [build 1.2.612](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.612/artifacts)（Download release-binary). This is part of #423

**Comment by bao-qian** [comment]
use #271 to track this issue in the future.
