### ISSUE TITLE
"Single App" mode [FEATURE] 

### ISSUE THREAD

**Issue by koobs** [Wox-launcher/Wox#450]
Simply the **best**, **most productive** and **usable** aspect about AlfredApp on OSX is that launching an app takes you to that application if it is already open, on a different space (desktop) if necessary.

This is the default behaviour and is a function of, and handled by OSX, not AlfredApp itself.

This would be a game changer. Currently, the only thing stopping me from using Wox literally _all the time_ (as I do Alfred on OSX), is that this isn't how Wox behaves, and that my primary use case is not always launching _new_ applications, but instead:
- The ability to locate, switch to, and manage many _existing_ (open) applications, such as:
  - Browser (Firefox)
  - Email (Thunderbird)
  - IM / Social (Skype, Tweetdeck, etc)
  - Development (puTTY), Notepad
- Across multiple desktops (Using Dexpot)
- Some of which might be minimised, or hidden behind other applications

For this feature, which I have dubbed here **_Single App Mode**_, I imagine something like the following:
- A setting that globally switches from the default Multiple to Single app mode, like:
  - Wox -> Settings -> ☑ Single application mode
- That affects all functions that _open programs_
-  Enables a keyboard modifier (say maybe, `Ctrl` by default) for `Enter` key when using the Wox query box
  - Which when used, opens a _new_ application instance
  - When not used (default), shows or activates the existing, **open** application instance

Bonus Points for:
- The ability to search existing open applications matched by Window Title

I won't purport to know exactly how this might be achieved, particularly since I'm not familiar with what exact SDK's and components are in use for Wox. 

Having said that, there have been in the past, and continue to exist various modern methods to this _activate another process/application window_ feature, including:
- BringtoFront()
- Activate()
- Searching window / handle classes and names
- Probably many others

To get the ball rolling, here are some search results that show promise:
- [MSDN: FindWindow & ShowWindow API](https://social.msdn.microsoft.com/forums/windows/en-US/ef89d134-b0f0-4935-88bf-85c8bd612add/findwindow-showwindow-api)
- [MSDN: Control.BringToFront Method () (.NET 4.x)](https://msdn.microsoft.com/en-us/library/system.windows.forms.control.bringtofront%28v=vs.110%29.aspx)
- [StackOverflow: Bring a window to the front in WPF](https://stackoverflow.com/questions/257587/bring-a-window-to-the-front-in-wpf)
  - Particularly: [Answer 111552906](https://stackoverflow.com/a/11552906)

Outlined below are a number of links I found for people requesting features for or describing workarounds for _open new not existing window_ in Alfred.
- [Keyboard modifier to open a new window for an application](http://www.alfredforum.com/topic/2363-keyboard-modifier-to-open-a-new-window-for-an-application/)
- [Open new Chrome window using Alfred](https://blog.hanshelgebuerger.de/2013/open-new-chrome-window-using-alfred/)
- [Launching a new instance of something instead opening existing one?](https://apple.stackexchange.com/questions/62771/launching-a-new-instance-of-something-instead-opening-existing-one)
- [How does one keep Alfred 2 from opening and entering your Terminal command in a new window when Terminal is already open?](https://stackoverflow.com/questions/22290329/how-does-one-keep-alfred-2-from-opening-and-entering-your-terminal-command-in-a)
- [Web search with Alfred create new tab or new window randomly](http://www.alfredforum.com/topic/4839-web-search-with-alfred-create-new-tab-or-new-window-randomly/)

**Comment by bao-qian** [comment]
try this plugin : [Switcheroo for Wox](http://www.getwox.com/plugin/52) and set a custom hotkey for that plugin.
I believe this can fulfill your all feature requests, correct me if I misunderstand you.

**Comment by lizhecao** [comment]
very good plugin with hotkey
