### ISSUE TITLE
Wox crash if you type in path to directory 

### ISSUE THREAD

**Issue by henrikroschmann** [Wox-launcher/Wox#455]
Wox crashes if you type in for example C:\program Fi..

   vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   vid System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   vid System.IO.DirectoryInfo.GetDirectories(String searchPattern, SearchOption searchOption)
   vid Wox.Plugin.Folder.FolderPlugin.QueryInternal_Directory_Exists(String rawQuery) i C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Folder\FolderPlugin.cs:rad 183
   vid Wox.Plugin.Folder.FolderPlugin.Query(Query query) i C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Folder\FolderPlugin.cs:rad 126
   vid Wox.Core.Plugin.PluginManager.<>c__DisplayClass30_0.<QueryForPlugin>b__0() i C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:rad 192
   vid Wox.Infrastructure.Stopwatch.Normal(String name, Action action) i C:\Users\Ricky\Documents\GitHub\Wox\Wox.Infrastructure\Stopwatch.cs:rad 29
   vid Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) i C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:rad 190

**Comment by henrikroschmann** [comment]
This was due to Access permission
-       $exception  {" c:\program access denied."} System.UnauthorizedAccessException

This should not result in crash, instead display a friendly message.

**Comment by bao-qian** [comment]
Hi, I can't reproduce this, what's your wox version?
[how to report bug](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-report-bug)

**Comment by bao-qian** [comment]
It would be better to record a gif, I recommend using ShareX.

**Comment by bao-qian** [comment]
close due to no response.
