### ISSUE TITLE
Tab to activate plugin

### ISSUE THREAD

**Issue by lasgor** [Wox-launcher/Wox#460]
I would like to have the option to be able to use Tab key to activate plugins (which is currently possible with the Enter key).

**Comment by lances101** [comment]
@lasgor Configurable hotkeys may come as a feature further down the road, but I doubt it will get implemented before 1.3.0, unless somebody specially dedicates their time on it

**Comment by bao-qian** [comment]
As you can see in other applications, tab key is used for navigation instead of confirmation.

**Comment by lasgor** [comment]
Launchy uses Tab. And I have also tried Listary as replacement for Launchy, where Tab also can be used.

**Comment by lasgor** [comment]
I'm long time Launchy user and very used to using Tab (and arrow keys for navigation). Although I understand that configurable hotkeys is more work and thus not a priority at this point, it would probably not be much work putting in an option for the user to choose the Tab key behavior (between navigation and plugin activation).
