### ISSUE TITLE
Folder plugin does not handle keywords

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#461]
Adding a keyword to the Folder plugin breaks its functionality.  

<img width="244" alt="2016-01-04 16 06 29" src="https://cloud.githubusercontent.com/assets/4784785/12092434/5daa32ce-b2fd-11e5-8800-295ad7943df7.png">
<img width="249" alt="2016-01-04 16 07 06" src="https://cloud.githubusercontent.com/assets/4784785/12092438/5fb50e4a-b2fd-11e5-8562-f94a8c78e2eb.png">

Selecting a result will set the query without the keyword 
<img width="504" alt="2016-01-04 16 07 13" src="https://cloud.githubusercontent.com/assets/4784785/12092442/60f0431a-b2fd-11e5-800e-544b7ee3fba4.png">

**Comment by pieper126** [comment]
@lances101 what build are you using? 
My build isn't even able to load folder Plugin.
![image](https://cloud.githubusercontent.com/assets/6524882/12224247/2a77839a-b7ec-11e5-9318-31eb802a675d.png)
![image](https://cloud.githubusercontent.com/assets/6524882/12224255/51b9b3d8-b7ec-11e5-84bc-847fa79a586c.png)
![image](https://cloud.githubusercontent.com/assets/6524882/12224263/840bb73c-b7ec-11e5-9514-aa54a12292bd.png)

**Comment by bao-qian** [comment]
@pieper126 @lances101 
https://ci.appveyor.com/project/happlebao/wox/build/1.3.57/artifacts
