### ISSUE TITLE
网页搜索功能崩溃BUG

### ISSUE THREAD

**Issue by JeyPiao** [Wox-launcher/Wox#470]
输入g,使用win10自带中文输入法时会崩溃。

**Comment by bao-qian** [comment]
版本？

**Comment by JeyPiao** [comment]
1.20测试版本。刚下载的

**Comment by bao-qian** [comment]
[v1.2.0-beta.2](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta.2)?

**Comment by JeyPiao** [comment]
是的

**Comment by bao-qian** [comment]
这是已知bug。已经在代码里修复了。下一个版本过些时候放出来。
用这个 [1.2.710](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.710/artifacts)
