### ISSUE TITLE
wox在win10上开机启动无效

### ISSUE THREAD

**Issue by JeyPiao** [Wox-launcher/Wox#471]
在启动中加入快捷方式也无法让wox开机启动

**Comment by bao-qian** [comment]
版本？
这个选项勾了吗？
![选项](http://i.imgur.com/D66giiq.png)

**Comment by JeyPiao** [comment]
勾选了。并且每次打开程序都会有系统的安全认证出现。

**Comment by bao-qian** [comment]
版本？

**Comment by bao-qian** [comment]
之前有吗？

**Comment by JeyPiao** [comment]
昨天你发给我的那个测试版。

发送自 Outlook Mobile

On Wed, Jan 13, 2016 at 1:56 AM -0800, "happlebao" notifications@github.com wrote:

版本？

**Comment by JeyPiao** [comment]
我是昨天才开始用的wox，之前没用过。

**Comment by bao-qian** [comment]
[v1.2.0-beta.2](https://github.com/Wox-launcher/Wox/releases/tag/v1.2.0-beta.2) 这个版本没有问题是吗？

**Comment by JeyPiao** [comment]
这个版本还没有测试开机启动，就换了你给的新版本了。

**Comment by bao-qian** [comment]
麻烦测试一下。

**Comment by JeyPiao** [comment]
好的，现在在外面，晚上到家了测试完给你回复

**Comment by JeyPiao** [comment]
1.2可以启动。
1.27不行

**Comment by bao-qian** [comment]
@JeyPiao 
1. 你的 wox 是放在哪个目录下的？ 是放在 %userprofile% 下吗？
2. 能贴一下 log 吗？（在 `Wox\Log`)

**Comment by bao-qian** [comment]
试下新的
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.0
