### ISSUE TITLE
[Web Searchs] 插件WebSearch有问题

### ISSUE THREAD

**Issue by jokerd** [Wox-launcher/Wox#472]
添加新的配置时会先提示“添加成功”，然后再提示“键被占用....”，就添加不了了。
然后我查看配置文件，Wox\Config\config.jason能看到键值，但插件目录下的setting.jason看不到添加的条目。
是不是写入执行顺序或者搜索执行顺序有问题。
对了，添加第一条配置条目可以成功，后面就一直这样报错了。

**Comment by jokerd** [comment]
还有系统环境时win7

**Comment by bao-qian** [comment]
版本？

**Comment by jokerd** [comment]
最新的release版本。1.2.0 beta2吧。
刚我重新用文件覆盖又不会出现了，不知道之前为什么这样。
等我再复现出来告诉你哈！

**Comment by JeyPiao** [comment]
1.2.7也会出现这个问题

**Comment by JeyPiao** [comment]
我是win10环境

**Comment by jokerd** [comment]
刚把原始的google删了，再添加google.tw同样绑定'g'，就添加不了了。“键被占用”

**Comment by jokerd** [comment]
删除没删干净？之前第一次我是直接编辑原始的那个google的搜索项，加了'.tw'的。

**Comment by jokerd** [comment]
刚试了一种复现出来的办法：
1. 之前随便加几个自己的
2. Enable失焦自动隐藏（General - 2nd）
3. 加一个和之前快捷键值重复的（会提示存在，失败）
4. 再正常加配置就和之一样了出错，加不进去了。

**Comment by bao-qian** [comment]
感谢报告。

**Comment by bao-qian** [comment]
@jokerd @JeyPiao 修完了
试一下： https://github.com/Wox-launcher/Wox/releases/tag/v1.2.875
如果喜欢请在左上角 star
