### ISSUE TITLE
Everything plugin - Out of Memory crash

### ISSUE THREAD

**Issue by jaredbidlow** [Wox-launcher/Wox#473]
Everything crashes when I try to type before text that was already entered. For example, I type "dog" and in order to narrow the search I want to type "wholeword:" in front of "dog". When I do this through Wox, Everything crashes. When I do it through the main Everything window, it works.

**Comment by bao-qian** [comment]
wox version?

**Comment by bao-qian** [comment]
bundled everything or everything download from getwox.com/plugins ?

**Comment by jaredbidlow** [comment]
Wox 1.2.0
I should have mentioned. I replace Everything with the beta version (Everything-1.4.0.713b.x86) in Wox.Plugin.Everything because it supposedly uses less memory with additional indexing options

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15034486/0ddaeee8-126e-11e6-93f1-d0fa0e5a3129.png)

should be fixed now
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898
