### ISSUE TITLE
[Web Searchs] typing blocked when waiting for search suggestions

### ISSUE THREAD

**Issue by PierBover** [Wox-launcher/Wox#476]
I've enabled the "search suggestions" options in the Web searches plugin.

When typing a bit fast the typing is blocked and letters take a while to appear in the input box. It seems the plugin is waiting for the search results to display the next chunk of letters.

**Comment by bao-qian** [comment]
yeah, it is not async.

**Comment by puco** [comment]
I have the same issue and have search suggestions disabled. Are you aware of any other plugin I should disable? Isn't the query only executed in the plugins after the keyword has a match?

**Comment by bao-qian** [comment]
@puco yeah, it should. I don't think you are talking about same issue.
could you record a short video?

**Comment by bao-qian** [comment]
@PierBover I probably misunder your question, could you upload a short video?

**Comment by PierBover** [comment]
Here is a video
https://youtu.be/McGvfNx32aY

You can see the chunks of text appearing when I have stopped writing long ago.

This also happens when deleting btw.

**Comment by bao-qian** [comment]
@PierBover thanks, I will fix it ASAP.

**Comment by bao-qian** [comment]
@PierBover @puco done
try it: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.875
please star this project if you like it
