### ISSUE TITLE
"Wox isn't working anymore" until Config/ImageCache.dat is deleted

### ISSUE THREAD

**Issue by snipem** [Wox-launcher/Wox#479]
![2016-01-25 08_33_58-new issue wox-launcher_wox](https://cloud.githubusercontent.com/assets/985581/12544964/7b5085ca-c33e-11e5-8ade-adc16af5e9a2.png)

The dialog is displaying "Wox isn't working anymore - ... - Close Application".

I'm using Windows 7 and v1.2.0-beta.2. Everytime I close the Dialog, Wox closes. If I minimize the dialog Wox is fully usable. After deleting `Config/ImageCache.dat` the application starts working again. After a few minutes of work the error appears again.

**Comment by guilhas** [comment]
Hello,

Same here.

@snipem how did you found the solution?

**Comment by bao-qian** [comment]
Hi, Please provide logs from `Wox\Logs` if you have.

**Comment by bao-qian** [comment]
steps to follow:
1. delete logs
2. delete cache
3. run wox until you encounter error
4. upload logs

Thanks for using Wox.

**Comment by bao-qian** [comment]
and what language you system use?

**Comment by snipem** [comment]
I tried to reproduce the error since then. Somehow it hasn't appeared since then. It's safe to assume that the error is gone for now.

**Comment by guilhas** [comment]
EN-UK.
Seems to be working now here also.
