### ISSUE TITLE
求助Wox偶尔在后台占用大量CPU问题

### ISSUE THREAD

**Issue by j67678** [Wox-launcher/Wox#481]
我在去年8月份fork了Wox的代码 https://github.com/renzhn/Wox 并做了一些个性化修改（比如舍弃Everything插件加强Program插件），之后在使用过程中只有一个影响使用的问题：偶尔在后台占用大量CPU，怀疑是Program插件自动扫描停不下来，但是也不知道什么情况会复现。请问可能会是什么问题？怎么调试？我可以提供出现此问题时的进程转储文件。

**Comment by LingForCC** [comment]
开发者里面有中国人吗？

**Comment by bao-qian** [comment]
Wox 从那之后已经大改了。。。
你可以先从 release 里下一下新版本

**Comment by j67678** [comment]
https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Program/FileChangeWatcher.cs#L41 这里的`isIndexing`是不是有问题？
整个项目里，isIndexing只有一处赋值为 false，是不是应该在45行前加入`isIndexing = true;` ？

**Comment by bao-qian** [comment]
@qianlifeng

**Comment by bao-qian** [comment]
@renzhn 
你有试新版吗？https://github.com/Wox-launcher/Wox/releases
`isindexing` 当然是个问题。。。 你能改掉就最好了。。。

**Comment by bao-qian** [comment]
有问题再开。

**Comment by bao-qian** [comment]
@renzhn 
正在重写这个插件
因为 index 的时候内部会有个 locker，所以这个 `isIndexing` 其实是没有用的。
