### ISSUE TITLE
Settings lost at times

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#482]
有时候，所有自己改过的设置都会变成默认设置，包括主题、语言等

最新的release
win10 64

**Comment by happlebao** [comment]
我无法重复。

**Comment by bao-qian** [comment]
我暂时没遇到这个问题。

**Comment by KuroiLight** [comment]
I get this same exact issue, not sure when or why its triggering, but It happens every few days/weeks.

_[Disclaimer: I can't read Chinese, used Google Translate]_

**Comment by iEverX** [comment]
as far as I know, it happens when the computer left powered off a few days

**Comment by bao-qian** [comment]
use #580
