### ISSUE TITLE
MVVM refactoring

### ISSUE THREAD

**Issue by LingForCC** [Wox-launcher/Wox#486]
I did a quick review for all the UI related code. I suggest that we introduce MVVM design pattern into the whole project to make the code cleaner. The influence scope may cover most of the WPF implementations in Wox project. Since there are quite a lot of work to do, followings are corresponding tasks.
- [x] Refactor MainWindow and ResultPanel
- [ ] Refactor SettingWindow
- [ ] Implement an unified mechanism to display messages

**Comment by bao-qian** [comment]
I'd appreciate it if you could open a PR.

**Comment by bao-qian** [comment]
WoxUpdate will be abandoned, and I will use squirrel in the future.
Msg is messy. ![c3npimth qx 97 ahehu_dw](https://cloud.githubusercontent.com/assets/1169912/10920855/5d10259e-826a-11e5-8286-a3160c1eed4c.png) and `MessageBox.Show` should be unified.

**Comment by LingForCC** [comment]
I agree with the Squirrel part. We could create another issue to follow up. I will modify the third task to follow up enhancement in Msg.

**Comment by jhdxr** [comment]
我建议把『热键』选项卡整合到具体插件的设置页面

**Comment by qianlifeng** [comment]
Close since v2 is not using MVVM
