### ISSUE TITLE
#bug 使用拼音输入法会使wox崩溃

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#489]
很奇怪，用拼音输入法键入英文（即enter输入英文）启动搜索命令如Google、wiki，wox必崩溃，其他命令目前暂未发现。

**Comment by LingForCC** [comment]
Wox是啥版本？用的啥输入法？

**Comment by ZacharyJia** [comment]
同样出现这个问题，wox版本v1.2.0beta.2。qq拼音输入法和微软拼音输入法都有这个问题。
我这边是win10，不用按回车，输入的时候就会字母会自动显示上去，然后再转换为中文（选字后再变成中文），只要键入首字母，wox就会崩溃。

**Comment by ZacharyJia** [comment]
再次测试发现，使用拼音输入法键入其他插件的关键字（setting、exit、wpm等），不会出现此问题，感觉应该是网页搜索插件的问题

**Comment by ghost** [comment]
对对，我就的就是Windows 10，64位，用的bing输入法、手心输入法、小狼毫、谷歌输入法都有问题，wox版本1.2.0 beta2，禁用了网络搜索插件，其他的命令全部正常

**Comment by bao-qian** [comment]
这是 .NET 版本问题。在 master 中已经修复。但 master 中有别的问题……。但我下周才有 vs…

**Comment by ZacharyJia** [comment]
命令行插件也有这个问题，不知道是不是相同的原因。

**Comment by bao-qian** [comment]
@ZacharyJia 命令行插件指什么？

**Comment by ZacharyJia** [comment]
@happlebao 就是按“>”，然后能够执行命令行命令的那个插件

**Comment by bao-qian** [comment]
试一下 build [1.2.726](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.726/artifacts)
需要 .net 4.5.2

**Comment by ZacharyJia** [comment]
@happlebao  没有问题了，谢谢！

**Comment by bao-qian** [comment]
@MioXie 你呢？

**Comment by ghost** [comment]
实测，已经完全没问题了，感谢！@happlebao
