### ISSUE TITLE
Launching vbs script without extension

### ISSUE THREAD

**Issue by stania** [Wox-launcher/Wox#491]
I think vbs script should be launched in wox by "Run" mode.

For example, I have "gvim.vbs" like below.

```
Dim RunCmd
RunCmd = ""
ReDim arr(1)
arr(0) = "_gvim.bat"
If WScript.Arguments.Count >= 1 Then
    ReDim arr(WScript.Arguments.Count)
    arr(0) = "_gvim.bat"
    For i = 0 To WScript.Arguments.Count-1
        Arg = WScript.Arguments(i)
        If InStr(Arg, " ") > 0 Then Arg = """" & Arg & """"
      arr(i+1) = Arg
    Next
End If
RunCmd = Join(arr)
CreateObject("Wscript.Shell").Run RunCmd, 0, True
```

In cmd, I can run this script with 'gvim', but in wox 1.1, I have to launch the script with ">gvim.vbs", instead of ">gvim".

Can this problem be fixed?

**Comment by bao-qian** [comment]
please try build [1.2.726](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.726/artifacts)
need .net 4.5.2

**Comment by bao-qian** [comment]
close due to no response.
reopen it if you still can't solve it.

**Comment by stania** [comment]
With 1.2.726, I can run "gvim.vbs" with "gvim", but Wox leaves cmd window that I didn't expected.

**Comment by bao-qian** [comment]
what do you mean by "leaves cmd window"?
do you want to cmd close or not?

**Comment by stania** [comment]
I want to launch a vbs script without seeing any cmd window.

**Comment by bao-qian** [comment]
Did you uncheck this option?
![option](http://i.imgur.com/NmsfXvW.png)

**Comment by stania** [comment]
Sure. 
![image](https://cloud.githubusercontent.com/assets/903320/13369182/2b767a58-dd35-11e5-9ed9-22ea963d83bc.png)

**Comment by bao-qian** [comment]
ah, I see.
the remain cmd windows is not the one opened by wox.
as indicated [here](https://msdn.microsoft.com/en-us/library/d5fk67ky%28v=vs.84%29.aspx?f=255&MSPPError=-2147217396), you should try `CreateObject("Wscript.Shell").Run RunCmd, 0, False`.
but, why you don't want to just run `_gvim.bat` from wox?
