### ISSUE TITLE
Got Win32Exception when selecting a "stale" shortcut

### ISSUE THREAD

**Issue by tvhong** [Wox-launcher/Wox#492]
While investigating issue #478, I uninstalled a program and kept the shortcut around in the start menu folder (C:\Users\XX\AppData\Roaming\Microsoft\Windows\Start Menu\Programs). I then use Wox to search for the program and select it. After a few seconds, Wox gives me a System.ComponentMode.Win32Exception at Programs.cs:47.

I can recreate the problem with the follow steps also:
1. create a new file
2. create a shortcut for that file
3. delete the file
4. use Wox to search and select the shortcut

I would have expected Wox to either:
- fail silently.
- give me a warning that the shortcut is no longer valid and offer to remove it, like what Windows does.

My system:
- Windows 10 64-bit
- Wox: commit f84574 on branch master.

This is the full stack trace:

>   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
>    at Wox.Plugin.Program.Programs.<>c__DisplayClass5_1.<Query>b__3(ActionContext e) in D:\Codes\Wox\Plugins\Wox.Plugin.Program\Programs.cs:line 48
>    at Wox.MainWindow.SelectResult(Result result) in D:\Codes\Wox\Wox\MainWindow.xaml.cs:line 824
>    at Wox.ResultPanel.OnLeftMouseClick(Result result) in D:\Codes\Wox\Wox\ResultPanel.xaml.cs:line 35
>    at Wox.ResultPanel.LbResults_OnPreviewMouseDown(Object sender, MouseButtonEventArgs e) in D:\Codes\Wox\Wox\ResultPanel.xaml.cs:line 280
>    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    at System.Windows.Input.InputManager.ProcessStagingArea()
>    at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
@tvhong @sjulien 
Hi, try again with [build 1.2.788](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.788/artifacts)
Please confirm it if the problem resolved.
If not, reopen this issue.
