### ISSUE TITLE
Everything.exe does not close after exiting Wox

### ISSUE THREAD

**Issue by tvhong** [Wox-launcher/Wox#493]
If Wox launched Everything on startup then shouldn't it closes Everything before it exits?

**Comment by ZaLiTHkA** [comment]
There's something else to keep in mind with this.. "Everything" is being launched with the "Everything service" option enabled (Settings > General > Search), which causes it to launch a system process as well. Simply closing the app from it's system tray icon doesn't seem to end this background process. Is this typical behaviour for Everything..?

Either way, if Wox is also meant to close "Everything" on exit, I suggest it be made to close both foreground and background processes..

**Comment by bao-qian** [comment]
thanks for suggestion.
wox use existing installed / running everything now, and won't launch everything on startup

https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898
