### ISSUE TITLE
Exiting Wox does not close process - causes crash when reopening

### ISSUE THREAD

**Issue by DaveyD** [Wox-launcher/Wox#498]
After exiting Wox, the Wox process remains open.
When I try to reopen Wox, it immediately crashes.
The only way to reopen is by going into Task Manager > Details  and manually closing the process.

This happens whether I exit Wox using the Exit command from within Wox, or if I close Wox from the system tray.

I am running Wox 1.2.0 on Windows 10 pro

---

P.S. I don't know if this is the place to write this, but...
I just switched back to PC from MAC, and I miss alfred tremendously! I've been using Launchy, but it's nowhere near Alfred.
Recently, I saw a link to this app on superuser.com.
I immediatley followed the link and I was so excited when I saw this app - and after installing it and using it a little... and it works awesome!... I love it! Thanks to the developer!!

**Comment by bao-qian** [comment]
Hi, thanks for report.

please try following steps to help us diagnose the bug.
1. download [latest build](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.737/artifacts).
2. remove all plugins.
3. when Wox crash, do you have exception prompted?
4. provide logs from `Wox\Logs`. (delete old logs before try to reproduce the bug)

**Comment by DaveyD** [comment]
Hi, thanks
Where is that link headed? I dont have access there through my proxy
Is there a way to install latest build from within github?

**Comment by bao-qian** [comment]
try this one
https://ci.appveyor.com/api/buildjobs/mvthym0rxmimhce6/artifacts/Wox-1.2.737.zip

**Comment by bao-qian** [comment]
It will redirect to our CI server.

**Comment by DaveyD** [comment]
Thanks
I seemingly dont have access to that
I will try to ask them to open this for me

**Comment by bao-qian** [comment]
Ok, I uploaded it for you.
[Wox-1.2.737.zip](https://github.com/Wox-launcher/Wox/files/139667/Wox-1.2.737.2.zip)

**Comment by DaveyD** [comment]
Great! Thanks
I will start trying now

**Comment by DaveyD** [comment]
Awesome! With this version it does close the process when exiting!
Thanks a lot

P.S. Just for your information, issue #414 still exists

**Comment by bao-qian** [comment]
Thanks.
