### ISSUE TITLE
Crash when type D:

### ISSUE THREAD

**Issue by artzers** [Wox-launcher/Wox#502]
When I type "D:" in wox, it crashed and exit with no warnings. However in everything, i can type "D:\ somefile" to find files in "D:\" path. If I could find files in intended directory, it‘s great.

**Comment by artzers** [comment]
my version is 1.2.0-beta2

**Comment by bao-qian** [comment]
I think this problem has already been solved in the latest build.
try [build 1.2.748](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.748/artifacts).

**Comment by bao-qian** [comment]
reopen this issue if you can't solve it.

**Comment by bao-qian** [comment]
Thanks for choose Wox, please star it if you like it.

**Comment by artzers** [comment]
I use wox 1.2.748. when I type D: , it still mentioned that path format is not support, and then crashed.

**Comment by artzers** [comment]
@happlebao

**Comment by bao-qian** [comment]
1. please give a screenshot.
2. please provide logs from `Wox\Logs` if you have.

**Comment by bao-qian** [comment]
close due to no response. reopen if the problem still exist.
