### ISSUE TITLE
Problem with Runner Plugin

### ISSUE THREAD

**Issue by Wishmaster172** [Wox-launcher/Wox#503]
Hi,

I have a problem with the runner plugin.
Everytime I write an "r" and the beginning of a keyword I get this message here:
https://i.imgur.com/dnImZ3A.jpg

System.NullReferenceException

   bei Wox.Plugin.Runner.Runner.<>c__DisplayClass6.<Query>b__3(Command c)
   bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bei System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   bei System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   bei Wox.Plugin.Runner.Runner.Query(Query query)
   bei Wox.Core.Plugin.PluginManager.ExecutePluginQuery(PluginPair pair, Query query) in c:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 193.

Can anyone help me to solve this?

Best Regards

**Comment by bao-qian** [comment]
Thanks for choose Wox, please star it if you like it.
1. which version?
2. try [latest build](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.753/artifacts)
3. put wox under your user folder (e.g. %userprofile%)

**Comment by Wishmaster172** [comment]
Hi, sorry for the delay... ;)
1. newest version (1.2.882)
2. see 1
3. Wox is running in my dropbox folder. That shouldn't be a problem, should it?

Best regards

**Comment by bao-qian** [comment]
you default dropbox folder should be under `%USERPROFILE%` (e.g. `C:\Users\yourname`) instead of `C:\projects` as shown in the error list. Did you put it in your `%USERPROFILE%`

**Comment by bao-qian** [comment]
as said in #579

**Comment by bao-qian** [comment]
Fixed now, update it with `wpm install Wox.Plugin.Runner`
