### ISSUE TITLE
Problems occured on my Windows 10 machine

### ISSUE THREAD

**Issue by latte-z** [Wox-launcher/Wox#506]
1. Wox经常会卡中文输入法...大概是英文输入结束后马上shift切回中文打字的一瞬间就会崩溃...
2. 快速命令行插件，勾选了不关闭窗口依旧还是会自动消失。启用的是新版的cmd，Wox也重启过多次，依旧无效

**Comment by bao-qian** [comment]
哪个版本？
2 的问题在[最新版](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.756/artifacts)已经修复

**Comment by latte-z** [comment]
如果没记错是v1.20，官网直接下的应该是新版吧？

**Comment by latte-z** [comment]
Sorry 可能我下载错了，没注意小版本号，打扰了。

**Comment by bao-qian** [comment]
试一下[最新 build](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.756/artifacts)

**Comment by bao-qian** [comment]
感谢反馈。有问题再开。
