### ISSUE TITLE
Allow to swap between open windows applications : suggestion

### ISSUE THREAD

**Issue by eleijonmarck** [Wox-launcher/Wox#507]
When I am in Visual Studio I want to quickly swap between Google Chrome,Git Extension, console and then back to Visual Studio without opening the appllication but rather just swap between open applications. Just like alfred in OSx is this a new feature coming?

**Comment by bao-qian** [comment]
Check this plugin http://www.getwox.com/plugin/52

**Comment by bao-qian** [comment]
by the way, which feature of Alfred will handle this situation?

**Comment by lances101** [comment]
@happlebao Alfred does not handle this in any way AFAIK. In OSX upon calling an app that is already running, it will bring up the last foremost window into focus

**Comment by eleijonmarck** [comment]
@happlebao, @lances101 
 that is exactly what i was looking for, but I think it would be great to have as a default feature, instead of having to write "win visual". I have suggested this to our companies hackathon to try to make it default.
