### ISSUE TITLE
Developing plugins: how to test

### ISSUE THREAD

**Issue by mennovf** [Wox-launcher/Wox#508]
I'm trying to develop a plugin for Wox in C#. I've compiled a .dll with a class inheriting from IPlugin from Wox.Plugin. I've created an executable which uses my library to test it.
Now I want to test it using Wox but I can't find how I should add my plugin to Wox. Putting it in the plugin folder (with an appropriate plugin.json) doesn't seem to do anything. The English documentation for manually installing a plugin is written in broken English which really doesn't help when my native language isn't English.

**Comment by bao-qian** [comment]
Thanks for your interests.
1. checkout from master branch
2. put you plugin source code folder under `Wox\Plugins`
3. run vs
4. run debugger

**Comment by staff0rd** [comment]
I can't seem to get debugging to work per the instructions above.  I can get the plugin loaded by sticking it in \outputs\debug\plugins but this runs it without debugging.

Sticking it in \wox\plugins (and including it in the solution) does not result in it being loaded at all.

**Comment by staff0rd** [comment]
Looks like you need to additionally;
- Change the output directory for your project to \output\debug\yourprojectname
- Ensure plugin.json is being copied to the output directory
- Build your project

I can't figure out how the other plugins in the solution are being built on debug startup - they don't seem to be referenced but they are being built.  As such, I'm just manually building my project from within the project and then starting the debugger.

**Comment by bao-qian** [comment]
@staff0rd sorry for delay, do you need any more helps now?

**Comment by staff0rd** [comment]
> I can't figure out how the other plugins in the solution are being built on debug startup - they don't seem to be referenced but they are being built. As such, I'm just manually building my project from within the project and then starting the debugger.

How is the build being triggered for plugins?  I'd like to do something similar for the plugin I'm working on.

**Comment by bao-qian** [comment]
1. the plugin project is included by solution
2. so it will be builded and will be copied to `Output\Release\Plugins\pluginname` 
3. wox will dynamic load all plugins located in that directory, and `%APPDATA%\Plugins\pluginname` as well

this is for c# plugins.

**Comment by bao-qian** [comment]
did you try this way?
![image](https://cloud.githubusercontent.com/assets/1169912/15103190/4bb0f30e-15a0-11e6-8e92-b497746c5455.png)

**Comment by bao-qian** [comment]
@staff0rd Hi, I just made an csharp example, take a look 
https://github.com/Wox-launcher/Wox/commit/7e58a23d05f42c4e4b5af62f4fecbdccd3a5f3ea

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15103471/bc7fe0d8-15a3-11e6-939e-ae470e30ffcf.png)

**Comment by staff0rd** [comment]
I figured out the missing piece/remembered what was wrong - I had added it as an _Existing Project_ as per your screenshots above, however, it was in another directory on the file system (not the Wox repository).  It seems the project must also be saved to the \Plugins directory or it won't be queued for build (even if it was added as an existing project).

So I guess my question is, how is that solution building the projects in \Plugins, considering it doesn't seem to be by Solution reference...

**Comment by bao-qian** [comment]
> it won't be queued for build

that's strange.
every projects in vs should be built
1. could you check your `plugidirectory/obj` directory? the temp build result (`dll`) should be there
2. could you check your build configuration manager? http://i.stack.imgur.com/xuPS3.png

> considering it doesn't seem to be by Solution reference...

what do you mean by this? since you added it in vs, right?

**Comment by bao-qian** [comment]
@staff0rd reopen if you have more questions.

**Comment by bao-qian** [comment]
@staff0rd 
Hi, I think I found it.
solution properties -> project dependicies -> wox -> choose your project
![image](https://cloud.githubusercontent.com/assets/1169912/15445727/0917199a-1efd-11e6-89c3-290ee3b2fddd.png)
