### ISSUE TITLE
Does not respect "Remember last launch location" 

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox#511]
Depending on what was the initial intention this may be a bug or not.

Previously, "Remember last launch location" would remember the location where Wox was shown last time and if it was set to false it would ignore it and display in the center of the currently active screen.

On the latest build (1.2.758) it always sticks to the last location to where it was dragged. 

Is this a bug or the initially intended behavior?

**Reproduce**
- Disable "Remember last launch location" in settings 
- Hide/Show Wox
- Wox stays in the last location.

**Comment by bao-qian** [comment]
bug

**Comment by bao-qian** [comment]
@lances101 
Hi, try again using build [1.2.778](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.778/artifacts).
Reopen it if problem still exist.
