### ISSUE TITLE
Encoding issues with Everything plugin

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#52]
![image](https://f.cloud.github.com/assets/6761242/2456327/eb71feaa-af14-11e3-83ec-a4a867138c5f.png)

**Comment by orzFly** [comment]
What'r your Everything version? I didn't get this error in 1.3.3.658b.

**Comment by orzFly** [comment]
bug has been reproduced on Everything 1.2.1.371.
