### ISSUE TITLE
ChangeQuery updates the result set but not the query value

### ISSUE THREAD

**Issue by staff0rd** [Wox-launcher/Wox#520]
I'm implementing a plugin against master latest (8f3b0d6).

**REPRO**

```
public List<Result> Query(Query query)
{
    return new List<Result>
    {
        new Result
        {
            Title = "test this",
            Action = c => 
            {
                if (!string.IsNullOrWhiteSpace(query.FirstSearch))
                    Success();
                else
                    context.API.ChangeQuery(query.RawQuery + " firstSearch");
                return false;
            }
            //,SubTitle = query.RawQuery
        }
    };
```

Launch wox and type;

```
kw // result set displays "test this"
<hit enter> // MainWindow now reads "kw firstSearch"
<hit enter>
```

**EXPECTED**
`query.RawValue == "kw firstSearch"` and `Success()`  called.

**ACTUAL**
`query.RawValue == "kw"`, `Success()` not called.

If I un-comment the `SubTitle` line at the bottom of the code snippet, then the value of `query` on the second enter is "kw firstSearch" (as expected)

**Comment by bao-qian** [comment]
you should not use `ChangeQuery` api, it will be removed in the future.
why you want to change query?

**Comment by staff0rd** [comment]
When the user hits enter on one of the dropdown values, the text in the main box should update to reflect it.  For example, Wox already does this when navigating through the filesystem's folder structure.  If `ChangeQuery` is not the expected way to update the query, what is?

**Comment by bao-qian** [comment]
My plan is to add a `autocomplete` field in the `result`.
so when hit enter, it will check whether there is `action`, if no, query will be changed to as same as `autocomplete` 

but you know, a plan is just plan.....
I will try to fix this api in the meantime

**Comment by bao-qian** [comment]
Hi, I figured out how to use the API now.
once you called `ChangeQuery`, the wox will use updated `QueryText` to `Query()` again.
so you should move the `if else` logic outside `Action`:

```
public List<Result> Query(Query query)
{
    if (!string.IsNullOrWhiteSpace(query.FirstSearch))
    {
        Success();
        return new List<Result>();
    }
    else
    {
        var result = new Result
        {
            Title = "test this",
            Action = c => 
            {
                context.API.ChangeQuery(query.RawQuery + " firstSearch");
                return false;
            }
        return new List<Result>() { result }
    }           
}
```

**Comment by bao-qian** [comment]
re open if you have more questions.
