### ISSUE TITLE
Folder name crash wox at startup

### ISSUE THREAD

**Issue by lysanlin** [Wox-launcher/Wox#521]
it's not a big problem, just prevent some one dumb like me

I used to work with wox 1.1.1 in a specific folder named #Software\wox without problem.
After I tried to upgrade wox 1.2.0 beta or beta 2, application will get failed while startup all the time as below image.
![image](https://cloud.githubusercontent.com/assets/17824143/13739177/a1dd440c-ea04-11e5-8b0c-ec0df3da18cd.png)

After some tests I figure out the root cause is due to the #, everything working well after removed. :)

**Comment by bao-qian** [comment]
As you see, this is not that important. I will try to fix it in the future.

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
