### ISSUE TITLE
How to unit test plugins

### ISSUE THREAD

**Issue by mika76** [Wox-launcher/Wox#522]
Is there any way to unit test a plugin? I cannot see how I can create a Query object with a search term since it only allows get properties...

**Comment by addamichal** [comment]
Not sure about this, but I think you will have to use PluginManager.QueryInit(string text) in Wox.Core. Method returns new Query object. But you will have to reference whole Wox.Core project to do this.

**Comment by mika76** [comment]
Yeah it's the same conclusion I came to looking at the code - and also seeing the response to some other questions on testing being "download the whole core". I would suggest to add some helper functions for unit testing. There's no reason to actually run wox to be able to unit test a plugin.

Also some more information on what each property of the Query object holds and how it is parsed...

**Comment by bao-qian** [comment]
I know this is sad, but you can't. at least for now....
