### ISSUE TITLE
[Web search] doesn't work with some keywords

### ISSUE THREAD

**Issue by theotherp** [Wox-launcher/Wox#523]
Version 1.2.0 on Windows 10. No logs as no exception

Using the default web search for wikipedia entering "w test" does not call the web search but instead the first autocomplete result (in my case wpm). Using "g test" works fine.

![wox settings](https://cloud.githubusercontent.com/assets/14368889/13818799/96f3826a-eb97-11e5-913a-c6deffa89c47.png)
![wox wikipedia doesnt work](https://cloud.githubusercontent.com/assets/14368889/13818798/96e7d2c6-eb97-11e5-855f-6e516581986d.png)
![wox google works](https://cloud.githubusercontent.com/assets/14368889/13818797/96dd8d34-eb97-11e5-8332-2ad3ca6525c5.png)

**Comment by tbnguyen1407** [comment]
Seems wikipedia web search is defined with "wiki" keyword from your 2nd screenshot.

**Comment by theotherp** [comment]
What? It says "w" right there in the "Action Keyword" column. The result "wiki" allows me to activate the web searches plugin which in itself is weird because as you can see in the first screenshot it's already enabled.

**Comment by tbnguyen1407** [comment]
The result "wiki" is what you want ("wiki test"). Could be a bug that you are seeing "w" defined but it is actually "wiki" instead.

Same thing if you type "f" it will suggest "findicon" to "Activate Web Searches plugin".

You should check your plugin config file to ensure the correct keywords set.

**Comment by theotherp** [comment]
![wox wiki doesnt work](https://cloud.githubusercontent.com/assets/14368889/13839755/eccec4a2-ec1d-11e5-8ba3-69036d4fcfb1.png)

No it's not.

**Comment by theotherp** [comment]
```
{
  "WebSearches": [
    {
      "Title": "Google",
      "ActionKeyword": "g",
      "IconPath": "Images\\google.png",
      "Url": "https://www.google.com/search?q={q}",
      "Enabled": true
    },
    {
      "Title": "Wikipedia",
      "ActionKeyword": "w",
      "IconPath": "Images\\wiki.png",
      "Url": "http://en.wikipedia.org/wiki/{q}",
      "Enabled": true
    },
    {
      "Title": "FindIcon",
      "ActionKeyword": "findicon",
      "IconPath": "Images\\pictures.png",
      "Url": "http://findicons.com/search/{q}",
      "Enabled": true
    },
    {
      "Title": "Leo",
      "ActionKeyword": "leo",
      "IconPath": "Images\\leo.png",
      "Url": "http://dict.leo.org/dictQuery/m-vocab/ende/de.html?searchLoc=0&lp=ende&lang=de&directN=0&search={q}&resultOrder=basic&multiwordShowSingle=on",
      "Enabled": true
    }
  ],
  "EnableWebSearchSuggestion": false,
  "WebSearchSuggestionSource": "Google"
}
```

**Comment by theotherp** [comment]
![wox wik shows](https://cloud.githubusercontent.com/assets/14368889/13839871/e5b1dffa-ec1e-11e5-8d1b-336eb38db6e8.png)
![wox wiki doesnt show](https://cloud.githubusercontent.com/assets/14368889/13839870/e4791c52-ec1e-11e5-9741-333ffea7cfae.png)

**Comment by theotherp** [comment]
I'm going back to launchy, fix it or not, I don't care. My first impressions are horrible, sorry.

**Comment by tbnguyen1407** [comment]
I think it's bug. Try uninstall plugin, delete the config and reinstall the plugin.

**Comment by theotherp** [comment]
Worked after deleting the plugin directory and restoring it from the archive. So obviously there's something wrong here.

**Comment by happlebao** [comment]
@saccohuo @druellan done
try it: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.875
please star this project if you like it

**Comment by bao-qian** [comment]
@theotherp @tbnguyen1407 done
try it: https://github.com/Wox-launcher/Wox/releases/tag/v1.2.875
please star this project if you like it

**Comment by tbnguyen1407** [comment]
I still have ArgumentOutOfRangeException when trying to change the keyword. Specifically:

> at Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin(PluginPair plugin, String oldActionKeyword, String newActionKeyword)
> in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 319 

I think the problem is due to keyword mismatch between those 2 files:
- config/settings.json
- config/plugins/wox.plugin.websearch/settings.json

If only 1 of the files is updated correctly with new keyword, the next keyword edit will fail at this line (ArgumentOutOfRangeException since index=-1):

``` csharp
// update existing action keyword
else
{
    int index = actionKeywords.IndexOf(oldActionKeyword);
    actionKeywords[index] = newActionKeyword;
    // more codes
}
```

**Comment by bao-qian** [comment]
Thanks for detailed analysis ! I will take a look when I back home .

**Comment by bao-qian** [comment]
@tbnguyen1407 Wox is not running as Admin, so I don't think it has permission to access `C:projects`. Then wox can't save the updated settings.
Could you try to put Wox in `%USERPROFILE%`  ?

**Comment by tbnguyen1407** [comment]
C:\projects\wox\Wox.Core\Plugin\PluginManager.cs is your code lol.

Still my local installation is also in `C:` drive so that seems to be the problem. I tried from `%USERPROFILE%`, no more problem. Thanks :)
