### ISSUE TITLE
How to upload a plugin?

### ISSUE THREAD

**Issue by jindongwang** [Wox-launcher/Wox#524]
I have created a wox plugin myself using Python 2.7.11.
But the problem is:
How do I upload my plugin to getwox.com?
The site said my plugin should end with .wox, so I used winrar to zip my file and renamed it as "xxxx.wox". However it didn't work.
Can anyone please tell my how to upload the package?Even how to package?

**Comment by ishu3101** [comment]
To upload the plugin, first you need to create a account. Once you have created your account, you need to log in.

Once you are logged in, go to http://www.getwox.com/plugin, and click on the upload button which will take you to http://www.getwox.com/plugin/create page.

There you need to upload your plugin icon, the plugin itself which needs to be a .Wox file, and a preview image.

You can also add the link to your github repo (which is where people can find the source code for your plugin) and a detailed description of your plugin.

**Comment by jindongwang** [comment]
Thank you for your kind reply, but I have done what you said before.The only thing I want to know is :
My plugin files are .py file with .json file, so how do I create .wox file?
That is my wonder.
Thank you！

From: ishu3101
Date: 2016-03-18 15:21
To: Wox-launcher/Wox
CC: Jindong Wang
Subject: Re: [Wox] How to upload a plugin? (#524)
To upload the plugin, first you need to create a account. Once you have created your account, you need to log in.
Once you are logged in, go to http://www.getwox.com/plugin, and click on the upload button which will take you to http://www.getwox.com/plugin/create page.
There you need to upload your plugin icon, the plugin itself which needs to be a .Wox file, and a preview image.
You can also add the link to your github repo (which is where people can find the source code for your plugin) and a detailed description of your plugin.

**Comment by roose** [comment]
@jindongwang Download any plugin, open it in WinRar and see how it made, folder structure etc.

**Comment by ishu3101** [comment]
The root of the folder should contain the python file and the plugin.json file when you create a zip file. Make sure that the files exist in the root of the folder and that they are not in a subfolder

**Comment by bao-qian** [comment]
seem resolved. re open if you have more questions.
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.0
new version is out
use py3 in the future
