### ISSUE TITLE
Resolve environment variables

### ISSUE THREAD

**Issue by crazy-max** [Wox-launcher/Wox#526]
Wox 1.2.0 b2
Windows 10 Pro 64bits

Would be nice to resolve environment variables like %USERPROFILE% :

![image1](https://cloud.githubusercontent.com/assets/1951866/13876405/52907d3a-ed04-11e5-9896-f294fc3851fc.png)

**Comment by staff0rd** [comment]
On the dev branch it doesn't matter where I put the shortcuts folder (environment variable or not) it finds it.  I assume because of Wox.Plugin.Everything.

**Comment by bao-qian** [comment]
I think this should be fixed in the [lastest build 1.2.771](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.771/artifacts), try it.

**Comment by bao-qian** [comment]
reopen it if you still can't resolve it.

**Comment by crazy-max** [comment]
Hi,

This is not working for the latest build 1.2.771 :

![image1](https://cloud.githubusercontent.com/assets/1951866/14025717/c290f0a2-f1ef-11e5-8027-89ba207c14aa.png)

![image2](https://cloud.githubusercontent.com/assets/1951866/14025720/c4f1c66e-f1ef-11e5-8738-a71a2288d573.png)

**Comment by crazy-max** [comment]
@bao-qian, any news about this features ? Thanks!
