### ISSUE TITLE
建议《有道词典》支持选择并复制查询结果！

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#527]
每次翻译了后，只能看到结果，不能复制，很蛋疼！！！

**Comment by skefy** [comment]
一样的要求。

**Comment by bao-qian** [comment]
> 问题：使用有道翻译插件，选中翻译结果，会崩溃。
> 希望：选中翻译结果，应该复制到剪切板。
> 
> 软件很棒，期待更好！感谢作者！

@skefy 大哥，我帮你移过来了。。。

**Comment by vantasy** [comment]
我想问一下这个插件要怎么安装啊？

**Comment by billzhuang** [comment]
好像这个插件现在没了，前两天还看到的

**Comment by bao-qian** [comment]
周末修复后上架。

**Comment by zlphoenix** [comment]
这个插件似乎还是不work, 使用yd 搜索work 这个词的 时候，滚动条一直走，但是没有返回结果。我配置了Python地址，本地Python 版本3.5.1

**Comment by ousui** [comment]
wox.py 复制到插件目录就可以了，这个文件调用有点问题。

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox.Plugin.Youdao/issues/1

**Comment by happlebao** [comment]
你们是想复制翻译结果？？

**Comment by happlebao** [comment]
谁截个图说明一下是想复制什么。。。。

**Comment by happlebao** [comment]
插件已更新
http://www.getwox.com/plugin/78

**Comment by bao-qian** [comment]
@clayzx @skefy @vantasy @billzhuang @zlphoenix @ousui 
插件已更新
http://www.getwox.com/plugin/78

**Comment by bao-qian** [comment]
回车是复制
如果觉得复制的结果不对，再开。。。

**Comment by bao-qian** [comment]
@skefy 
插件已更新
http://www.getwox.com/plugin/78

**Comment by bao-qian** [comment]
@psycoHo
插件已更新
http://www.getwox.com/plugin/78

**Comment by bao-qian** [comment]
@clayzx @skefy @vantasy @billzhuang @zlphoenix @ousui @skefy @psycoHo

忘了说了。。需要配合新版 wox
https://ci.appveyor.com/project/happlebao/wox/build/1.3.64/artifacts
