### ISSUE TITLE
热键呼出后焦点不在 wox 的输入窗上

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#528]
最新版本1.2.770热键呼出后焦点不在wox上！

**Comment by bao-qian** [comment]
我行啊。
能说下重复步骤或者录个视频吗？
可选用 sharex 来录。

**Comment by bao-qian** [comment]
要下 **master** 分支的 build. 比如说这个: [1.2.771](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.771/artifacts)

**Comment by clayzx** [comment]
嗯，我下了1.2.771版本发现没问题了！
