### ISSUE TITLE
Failed to query with V2EX plugin

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#53]
log.txt如下：
Date：2014-03-19 11:09:42,212 Level：ERROR Msg：Python Invoke failed: ValueError : 
Date：2014-03-19 11:09:43,962 Level：ERROR Msg：Python Invoke failed: ValueError : 
Date：2014-03-19 11:09:44,626 Level：ERROR Msg：Python Invoke failed: ValueError : 
Date：2014-03-19 11:09:44,876 Level：ERROR Msg：Python Invoke failed: ValueError :

**Comment by orzFly** [comment]
You need to install following libraries manually.

``` python
from __future__ import unicode_literals
import requests
from bs4 import BeautifulSoup
import json
import webbrowser
```

**Comment by aihuasxy** [comment]
已解决，环境中装了2个版本的python和2个版本的requests，所以冲突了。
