### ISSUE TITLE
1.2.0三个问题

### ISSUE THREAD

**Issue by fzxing** [Wox-launcher/Wox#531]
wox是一个非常好的软件，不过从1.0版本升级到1.2.0版本后，发现了几个问题。

版本 1.2.0.770
操作系统 win10 

问题1： 1.2.0版本，python插件中，传递的key为中文时，编码有问题。原来1.0版本是utf8编码，但现在这个编码似乎既不是utf8也不是gbk
    class AAAAA(Wox):
    def query(self, key):
    r = requests.get('http://xxx.php?nick='+key)

问题2：1.2.0版本 python插件中调用 WoxAPI.show_msg('123','ttt')会报错：SyntaxError: invalid syntax

问题3：输入一个大数字时，计算器失效变成了负数，如输入99999999999999

**Comment by bao-qian** [comment]
感谢汇报
1. 
升成 py3，然后用新的文件：https://github.com/Wox-launcher/Wox/blob/master/JsonRPC/wox.py
你电脑装了 py 后，添加到 `%PATH%`
然后装新版 https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898 
1. 不要用这个 api，马上要删掉了，就用 query
2. 计算器另外开 issue
