### ISSUE TITLE
Sometimes can't type without clicking on wox bar

### ISSUE THREAD

**Issue by anhchuong95** [Wox-launcher/Wox#532]
Sometimes, after pressing hot-key, I can't type without clicking on the wox bar. It's not actually a bug, but it's kind of annoying. I'm using windows 10 64bit, wox version 1.2.770. Have anyone faced this problem before or know how to fix this? Any suggestion is appreciated. Thanks in advance

**Comment by bao-qian** [comment]
I remember this has been fixed.
I'd appreciated if you could find a way to tell me how to reproduce it.

**Comment by bao-qian** [comment]
what do you mean by hot-key, <kbd>alt</kbd> <kbd>space</kbd> ?

**Comment by bao-qian** [comment]
Chinese user go here #528

**Comment by tbnguyen1407** [comment]
Same problem with windows 10 build 14291. Seems to be with the way application focus is done on windows 10. Those happen every once in a while after activating the app:
- Cursor is inside the text input but can't type anything
- Cursor not inside text input hence can't type anything

Both can be fixed by clicking on the text input field.

I realize that the focus on those cases are actually on the app in the background so input is directed at them instead of wox.

**Comment by anhchuong95** [comment]
Just like tbnguyen1407 said, it's kind of random. About the way to reproduce it, just open many windows then activate wox and that problem is very likely to happen. Also, I'm on windows 10 64-bit Version 1511 build 10586.164 and using Alt+Enter as my hotkey.

**Comment by bao-qian** [comment]
@tbnguyen1407 wox version? 1.2.770?

**Comment by tbnguyen1407** [comment]
Yep 1.2.770

**Comment by bao-qian** [comment]
@tbnguyen1407 @anhchuong95 
did you notice when you press hotkey <kbd>alt</kbd> <kbd>space</kbd>, all the text is selected?
like this 
![demo](http://i.imgur.com/v2Clefw.png)

**Comment by tbnguyen1407** [comment]
I tried a few times. Same problem occurs with both cases (sometimes all text selected and sometimes not).

**Comment by tbnguyen1407** [comment]
1 way I can consistently reproduce is:
1. Activate wox
2. Switch to another app (alt+tab). Wox will hide
3. Reactivate wox. Now text input won't work

**Comment by bao-qian** [comment]
Got it. 
I'm sorry for the unclear instruction.
You should download build from **master** branch.
Like this one: [1.2.771](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.771/artifacts)

**Comment by tbnguyen1407** [comment]
Seems ok to me on 1.2.771 ;)

**Comment by bao-qian** [comment]
Thanks for reporting.
@anhchuong95 reopen it if you still can't resolve it.
please star it if you like it.

**Comment by aakala** [comment]
Issue still exists on 1.4.1196 (Win 10)

**Comment by guruuvai** [comment]
> Issue still exists on 1.4.1196 (Win 10)

yup, same issue. any fixes? (Win 10 20H2)
