### ISSUE TITLE
How to record a demo like the one for Wox?

### ISSUE THREAD

**Issue by vatterspun** [Wox-launcher/Wox#533]
[This isn't specifically a problem but I contacted the developer and he asked me to open a github issue about this.]

The program demo for Wox is just outstanding:

https://github.com/Wox-launcher/Wox/blob/master/README.md

Can someone give me some indicator of what software was used?  That's definitely a step above Camtasia.  Thanks!

**Comment by bao-qian** [comment]
It tooks me a while to recall it.
1. use [carnac](http://code52.org/carnac/) to visualize keystroke.
2. use [sharex](https://getsharex.com/) to record gif and upload it.

You can also try this combined solution -- [KeyCastOW](https://brookhong.github.io/2014/04/28/keycast-on-windows.html)

It's good to hear you like the demo. If you like this project, please star it.

**Comment by vatterspun** [comment]
> If you like this project, please star it.

I do.  Starred :)
