### ISSUE TITLE
No increase in weight for frequent searches from Folder plugin

### ISSUE THREAD

**Issue by lehasb** [Wox-launcher/Wox#534]
I use the Folder plugin to define several folders I want to navigate to quickly. When searching for applications, the ones I use most commonly jump to the top of the list, as expected. But when searching for the folders I have defined, they are still 10+ items down in the list, even when none of the items above them are things I ever use.

Expected behavior: Frequently selected folders move to the top of the search results
Actual behavior: Position in the search results of frequently selected folders does not change

Wox 1.2.758 on Windows 10 (installed to %userprofile%)

**Comment by bao-qian** [comment]
temper fix: use everything syntax to search files inside a folder
`foldername\ filename`

releated: #315
