### ISSUE TITLE
Can't execute context menu item when using enter

### ISSUE THREAD

**Issue by anjia0532** [Wox-launcher/Wox#535]
从 https://ci.appveyor.com/project/qianlifeng/wox/build/artifacts 下载的最新的build，Wox-1.2.776.zip
1.  Wox 版本 Wox-1.2.776
2. 搜索出结果后，用Ctrl+O出现的【打开所属文件夹】【在当前结果中置顶】，会直接运行，用鼠标右键弹出此菜单，选择 【打开所属文件夹】【在当前结果中置顶】是可以的
3.  Windows 版本 windows 10版本号1511（OS 10586.164）

**Comment by bao-qian** [comment]
我试了一下。不管是 <kbd>Ctrl</kbd><kbd>O</kbd> 还是右键。只要是用回车，那么就是运行。用鼠标才会触发该有的行为。

**Comment by bao-qian** [comment]
找到问题了。明天修复。

**Comment by bao-qian** [comment]
试一下 [build 1.2.782](https://ci.appveyor.com/project/qianlifeng/wox/build/1.2.782/artifacts)。
应该修复了。
有问题重新打开 issue，没问题也请说一声。
