### ISSUE TITLE
New API structure

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#537]
This is issue is just for my own reference.
- `Wox` -> `Wox.WPF`
- `Wox.Infrastructure` + `Wox.Plugin` -> `Wox`
- `IPublicAPI`
  - Delete
    - `PushResults`
    - `OpenSettingDialog`
    - `GlobalKeyboardEvent`: bultin
    - `StartLoadingBar`: builtin, use timer to check
    - `StopLoadingBar`: builtin, use timer to check
    - `BackKeyDownEvent`: use builtin <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> support
  - Plugin should not control the GUI of Wox (thanks @LingForCC for discussion)
    - `HideApp` + `ShowApp`
      - delete
      - <del>use `hide` parameter to check, default vaule for hide will be `true`</del>
      - <del>`Func<ActionContext, bool> Action` -> `delegate void Action(out bool hide);`</del>
      - use two `Action`. 
        - `Action` + `WoxStillOpenAction` or
        - `CloseWoxAction` + `Action`
      - use `Hide` field in `Result`
    - `ChangeQuery`
      - add `autocomplete` field in `Result`
      - <kbd>Ctrl</kbd>+<kbd>Enter</kbd> will teriger autocomplete
      - if `Action == null && !autocomplete.isNullOrEmpty()` then <kbd>Enter</kbd> will triger autocomplete too
    - `ShowContextMuen` + `LoadContextMenu` #933: 
      - should I use `ContextMenu` delegate in `Result` instead? 
    - Probally we can add a `ActionType` enum in Result or as `Action` return value?  #933
      - Show, Hide, ShowContextMenu, autocomplete?
  - Move into `Wox`
    - `ShowMsg`: `ShowMessageBox` + `ShowToastseperate` in seperate `Message` class
    - `GetTranslation`: Move `InternationalManager` into `Wox`
  - Embedded + delete:
    - need to implement a unified score calculator / matcher
    - `SettingDialog`: embedded
    - `CloseApp`: Application.Shutdown() + embedded
    - `RestarApp`: `UpdateManager.Restart() + embedded
    - `InstallPlugin`, `ReloadPlugins`: embedded
    - `GetAllPlugins`: delete
  - Unknown: 
    - `GlobalKeyboardEvent`: blocking #459
  - if all methods in _not sure_ is deleted, the whole `IPublicAPI` will be deleted, then there will be no `PublicAPIIntance`
  - <del>else</del>
    - <del>option 1: made `PublicAPIIntance` static, then move into `Wox.Base`</del>
    - <del>option 2: pass `PublicAPIIntance` as parameter in plugin initilization phase </del>
- New
  - `Logger`
  - `PluginSettings`
- `PluginPair`
  - `PluginPair`, `IPluhin`, `PluginMetadata` should be merged into just one class `Plugin`
- `PluginInitContext`: delete

**Comment by skefy** [comment]
问题：使用有道翻译插件，选中翻译结果，会崩溃。
希望：选中翻译结果，应该复制到剪切板。

软件很棒，期待更好！感谢作者！

**Comment by bao-qian** [comment]
use duck typing for api changes
e.g. change from 
wox.plugin.result -> wox.result
wox.plugin.iplugin -> wox.plugin
http://stackoverflow.com/questions/8008902/dynamic-namespace-switching

**Comment by bao-qian** [comment]
Move plugin manager into wox.infra? So the iapi can remove install plugin, remove plugin, reload plugins etc.

**Comment by bao-qian** [comment]
- [ ] publish symbols along with dll (.symbols.nupkg or [GitLink](https://github.com/GitTools/GitLink))

**Comment by bao-qian** [comment]
non-cli plugin api:
1. msgpack-rpc (like neovim)?
2. still use json-rpc?
3. send reset api like http request, return result using json? (rest style)

**Comment by roose** [comment]
I think it isn't necessary to change, what change when you changing plugin api? Performance doesn't improve, it's just local files, not web.

**Comment by bao-qian** [comment]
@roose 
the current design is conflict with MVVM pattern.
which cause enormous bugs, and the code base can't be easily refactored.
clean code -> less bugs
clean api -> much easier to support other languages. (current design cause lots of api can't be exposed to other languages, e.g. multiple keywords, settings gui )

**Comment by roose** [comment]
@happlebao I'm about:

> non-cli plugin api:
> 1. msgpack-rpc (like neovim)?
> 2. still use json-rpc?
> 3. send reset api like http request, return result using json? (rest style)

not about whole api structure )

**Comment by bao-qian** [comment]
useful new api: https://msdn.microsoft.com/en-us/library/system.appcontext(v=vs.110).aspx

**Comment by shanehou** [comment]
So... will Wox support context menu using python?

**Comment by Garulf** [comment]
I too would like to know if context menu is coming to python

**Comment by bao-qian** [comment]
track using #2831
