### ISSUE TITLE
[Web Searches] 程序停止运行

### ISSUE THREAD

**Issue by ltd920678778** [Wox-launcher/Wox#539]
我的Wox版本是1.2.0. 系统版本是windows10 ,14291.rs1_release.
在我每次使用网页收索功能时, 都会提示程序停止运行![截图](http://7xsd1c.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160328145241.png)

**Comment by NanerLee** [comment]
我也是

**Comment by bao-qian** [comment]
是 1.2.0 beta 2 吗？
挂 VPN 呢？

**Comment by ltd920678778** [comment]
是的，在github上下载最新版，我是用的Shadowsocks客户端的. 但是我用百度搜索也是会卡死啊！

2016年3月28日 +0800 20:48 happlebao notifications@github.com，写道：

是 1.2.0 beta 2 吗？
挂 VPN 呢？

**Comment by bao-qian** [comment]
感谢汇报
@ltd920678778 @NanerLee 试一下新版本： 
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.875

**Comment by bao-qian** [comment]
代理好像还有点问题，
但应该不影响普通使用

**Comment by bao-qian** [comment]
试一下，应该修复了，用 google 记得设代理。。。
@ltd920678778 @NanerLee
https://ci.appveyor.com/project/happlebao/wox/build/1.2.907/artifacts

**Comment by bao-qian** [comment]
没解决的话再开

**Comment by ltd920678778** [comment]
好的，明天试试！

发自我的 iPhone

在 2016年5月5日，23:39，happlebao <notifications@github.com<mailto:notifications@github.com>> 写道：

没解决的话再开

―

**Comment by ltd920678778** [comment]
web search功能是可用的，不过只能输入关键字后回车打开浏览器，而不会在wox下现实搜索结果条目！

发自我的 iPhone

在 2016年5月5日，23:40，李 腾达 <ltd111118@outlook.com<mailto:ltd111118@outlook.com>> 写道：

好的，明天试试！

发自我的 iPhone

在 2016年5月5日，23:39，happlebao <notifications@github.com<mailto:notifications@github.com>> 写道：

没解决的话再开

―

**Comment by bao-qian** [comment]
本来就是这么设计的。。。

**Comment by ltd920678778** [comment]
恩, 了解.

发件人: happlebao [mailto:notifications@github.com]
发送时间: 2016年5月6日 10:32
收件人: Wox-launcher/Wox Wox@noreply.github.com
抄送: lee ltd111118@outlook.com; Mention mention@noreply.github.com
主题: Re: [Wox-launcher/Wox] [Web Searches] 程序停止运行 (#539)

本来就是这么设计的。。。
