### ISSUE TITLE
Strange white outline ? 

### ISSUE THREAD

**Issue by oott123** [Wox-launcher/Wox#54]
![wox-strange-outline](https://f.cloud.github.com/assets/905663/2457557/b7b94e36-af39-11e3-84a4-caad2b129568.png)
just like the screenshot.

**Comment by qianlifeng** [comment]
Did your get the latest Wox version in the release page? Since I turn off the shadow effect, this issue should not occur.

**Comment by oott123** [comment]
sorry , i get that bug the day before yesterday and it's OK now.
