### ISSUE TITLE
Don't work edit plugin on getwox.com

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#541]
Editing plugin doesn't work, when selecting a plugin file it's replaced by icon file
P.S. omg, direct link to edit plugin page available for non authorized users

**Comment by seza443** [comment]
Hi, 
Editing the plugin works just fine for me, even if the file is replaced by icon file ;-)
And OMG like you said, the page is indeed available for unauthorized users :open_mouth: 
Fortunately, credentials are asked when clicking the update button

**Comment by roose** [comment]
why closed?

**Comment by bao-qian** [comment]
@seza443 said the editing is works just fine.
so it still not working?

**Comment by roose** [comment]
no, now test it, plugin file replaced by icon file

**Comment by roose** [comment]
![wox plugin edit](https://cloud.githubusercontent.com/assets/277651/15446083/4219dbdc-1f35-11e6-93a8-ca523dde1a40.png)
may be adding new file is works normally, but editing not )
