### ISSUE TITLE
输入中文很容易闪退

### ISSUE THREAD

**Issue by zhoujiangzi** [Wox-launcher/Wox#543]
## 中文 / Chinese
1. 请提供 Wox 版本
   版本为1.2.0
2. 请提供如何**重现** bug 的步骤
   a.启动后，输入weather 成都  ，然后就极容易出现闪退，英文没问题
   b. 添加百度的搜索快捷键b   然后输入 b 测试 回车后就闪退    但是输入  b ceshi   回车正常
3. 请提供 Windows 版本
   windows 10 10586.164

输入框输入中文就很容易出现闪退

**Comment by bao-qian** [comment]
感谢汇报。这问题已修复。请下最新 [最新的 build](https://github.com/Wox-launcher/Wox/wiki/FAQ-%E4%B8%AD%E6%96%87#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0-build)。
