### ISSUE TITLE
It's better to add evaluation score for historical hit?

### ISSUE THREAD

**Issue by zhougy0717** [Wox-launcher/Wox#549]
I'm a lauchy fans. The greatest point lauchy has is it can trigger hot apps with least key stroke.
For example, the first time I hit 'putty', then launchy shows me putty.exe for me to start.
Next time, I may only need to hit 'p', then putty shows up.

In current Wox (FuzzyMatcher, Evaluate, CalScore), I don't see any weigh up for historical result hit.
Do we have any possibility to add this point into current score calculation algorithm? I think it will improves user stickiness a lot.

By the way, I'm new to C#. I don't understand the code well. But I think we can put this in our TODO list.

How about you guys thinking?

**Comment by bao-qian** [comment]
it's on todo list...
the actual problem is the score add to items is too small, and will be bumped up after several turns...

**Comment by zhougy0717** [comment]
Could you share more explicitly? I don't see the rating up in below function.

```
        private int CalScore(string str, int firstIndex, int matchLen)
        {
            //a match found near the beginning of a string is scored more than a match found near the end
            //a match is scored more if the characters in the patterns are closer to each other, while the score is lower if they are more spread out
            var score = 100 * (query.Length + 1) / ((1 + firstIndex) + (matchLen + 1));
            //a match with less characters assigning more weights
            if (str.Length - query.Length < 5)
                score = score + 20;
            else if (str.Length - query.Length < 10)
                score = score + 10;

            return score;
        }
```

**Comment by bao-qian** [comment]
it has already been report in #315
a temp hack would change the number of `_userSelectedRecord.GetSelectedCount(o) * 5;` in `UpdateResultView` to a larger one.

**Comment by bao-qian** [comment]
but if you use that temp hack, just keep it in your repo, don't send pr...

**Comment by zhougy0717** [comment]
great thanks!
I will close this issue and move up to #315.
