### ISSUE TITLE
Hotkey Change Recognize error

### ISSUE THREAD

**Issue by qin-nz** [Wox-launcher/Wox#552]
1. Please specify Wox version  
   v1.2.0-beta.2 0ce9f0d  
2. Please describe the steps to **reproduce** the bug  
   Change Hotkey to Ctrl + Space  
3. Please provide Windows version  
   Windows 10.0.10586  
4. Please provide Exception info if you have.  
   Hotkey changed to Ctrl + LeftCtrl  

![image](https://cloud.githubusercontent.com/assets/6998071/14135817/32251cee-f692-11e5-81c6-f3ea24be2c32.png)

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue

**Comment by qin-nz** [comment]
`v1.3.424` on Windows 10.0.16257 has same problem.

And I can't reopen the issue

**Comment by icksky** [comment]
+1 `v1.3.424` on win10

**Comment by qin-nz** [comment]
@happlebao Please reopen this.
