### ISSUE TITLE
1.2.810增加program目录闪退

### ISSUE THREAD

**Issue by iulo** [Wox-launcher/Wox#553]
Wox版本：1.2.810
步骤：settings - plugin - program - add - chioce a folder - 闪退

**Comment by Eucaly** [comment]
- tested some recent versions (include: 801, 805, 811), have similar issue

System.InvalidCastException: 無法將類型 'System.String[]' 的物件轉換為類型 'System.String'。
   Source: Wox.Plugin.Program
   TargetAssembly: Wox.Plugin.Program, Version=1.2.801.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Program.dll
   TargetSite: System.Object Convert(System.Object, System.Type, System.Object, System.Globalization.CultureInfo)
   於 Wox.Plugin.Program.StringEmptyConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture) 於 C:\projects\wox\Plugins\Wox.Plugin.Program\StringEmptyConverter.cs: 行 12

**Comment by iulo** [comment]
@happlebao

**Comment by bao-qian** [comment]
@iulo, @Eucaly  

感谢反馈，新 build 出来了。
试一下： https://github.com/Wox-launcher/Wox/releases/tag/v1.2.857
如果喜欢这个项目，请在右上角点 star。

**Comment by Eucaly** [comment]
@happlebao

tested 857 pre-release, OK so far
