### ISSUE TITLE
How to do a completely clean uninstall of Wox and its plugins and all artifacts?

### ISSUE THREAD

**Issue by wox-anon** [Wox-launcher/Wox#555]
I've searched but have been unable to find this information:

How does one go about completely uninstalling all traces of wox, its plugins and any and all artifacts (e.g. registry entries, AppData entries, etc.)?  It used to work but I must have messed it up somehow.  I'm running on "Windows 7 Home Premium".  Wox version "Wox-1.2.810"

Thank you.

**Comment by bao-qian** [comment]
for this version, just remove Wox directory,
for future version (not released) remove `%APPDATA%/Wox` and Wox installation directory

**Comment by nickimola** [comment]
I am afraid it doesn't work for me.
I removed %APPDATA%/Wox, removed all the entries in the registry, removed everything i fund related to Wox but still, it comes back at every reboot.

So i'm bringing this issue up again and i ask, I do i completely remove Wox from my pc (windows)?

Thanks

**Comment by lances101** [comment]
@nickimola I have made a simple .bat that uninstalls Wox and clears up the roaming and local AppData folders. 

You can either [download the .bat file from here](https://github.com/Wox-launcher/Wox/files/1712694/wox_uninstaller.bat.txt) (please note that you will have to remove the .txt extension. Github does not allow .bat files to be uploaded directly), or [copy the code from this gist](https://gist.github.com/lances101/e86802c79ec33bc1a82c7f677a9d5043), paste it into notepad and save the file as `wox_uninstall.bat`

Once you have the .bat file, run it. 

Quick rundown of what it does:
```
:: First we call the Squirrel updater with the uninstall flag and the directory where it resides
%LOCALAPPDATA%\Wox\Update.exe --uninstall . 

:: Once Squirrel has done its job, we delete Wox's application folder recursively
rmdir %LOCALAPPDATA%\Wox /S /Q

:: We also delete Wox's configuration folder recursively
rmdir %APPDATA%\Wox /S /Q
```

**Comment by lances101** [comment]
[Added a small article on the wiki covering uninstallation](https://github.com/Wox-launcher/Wox/wiki/Uninstalling-Wox)

Eventually we will provide an easier way.

**Comment by nickimola** [comment]
Hi,
Thanks for getting back to me. I did try your bat file (both as admin and not admin) but after rebooting i still see wox coming back up.

**Comment by lances101** [comment]
That's strange. 
When Wox autoruns again, open the task manager, right-click on Wox and hit "Open file location". Comment here with the path where Wox is located.

**Comment by nickimola** [comment]
Hi again, the path is the following:
C:\Users\Nick\AppData\Local\Wox\app-1.3.424
