### ISSUE TITLE
崩溃-1.2.813

### ISSUE THREAD

**Issue by HOHDH** [Wox-launcher/Wox#558]
![01](https://cloud.githubusercontent.com/assets/17843655/14488634/c0f21288-019b-11e6-99e9-76a032655b38.png)
![02](https://cloud.githubusercontent.com/assets/17843655/14488635/c124243a-019b-11e6-9f33-bda5c4e395ff.png)

搜索gsonFormat想看一下gsonFormat在哪，结果到了置顶，然后蹦了，

**Comment by bao-qian** [comment]
@HOHDH 

感谢反馈，新 build 出来了。
我在新 build 中是没看这个问题的。
试一下： https://github.com/Wox-launcher/Wox/releases/tag/v1.2.857
如果喜欢这个项目，请在右上角点 star。
