### ISSUE TITLE
How to change the font?

### ISSUE THREAD

**Issue by aihuasxy** [Wox-launcher/Wox#56]

**Comment by qianlifeng** [comment]
You can edit the theme file to change the font. For example:

```
    <Style x:Key="QueryBoxStyle" BasedOn="{StaticResource BaseQueryBoxStyle}" TargetType="{x:Type TextBox}">
        <Setter Property="Background" Value="#EBEBEB"/>
        <Setter Property="Foreground" Value="#000000" />
        <Setter Property="FontFamily" Value="Comic Sans MS" />
    </Style>
```

<img src="http://ww2.sinaimg.cn/large/5d7c1fa4gw1eelalcmwdej20dw054q3h.jpg" />  

We will provide Font Setting in Wox Setting Dialog. [#35](https://github.com/qianlifeng/Wox/issues/35)

**Comment by aihuasxy** [comment]
thx
Small chinese font in WPF is too ugly and can not be rendered by mactype。
Do u have some suggestion for font selection or way to solve it？

**Comment by qianlifeng** [comment]
Check it out
<img src="http://ww2.sinaimg.cn/large/5d7c1fa4gw1eelfcr7v5wj20ng0bb75q.jpg" />
