### ISSUE TITLE
Python sqlite3.dll is outdated

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#560]
Trying to use the database created with newer sqlite3.dll version, throws an exception: `sqlite3.DatabaseError: file is encrypted or is not a database`. 
More info: https://deshmukhsuraj.wordpress.com/2015/02/07/windows-python-users-update-your-sqlite3/
sqlite3 version in Wox - 3.6.21
latest sqlite3 version - 3.12.1
Update please latest sqlite3.dll version from: http://www.sqlite.org/download.html

**Comment by bao-qian** [comment]
try latest prerelease, it will use the python installed by your self
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898
