### ISSUE TITLE
总是下载不了，能提供百度云链接吗？

### ISSUE THREAD

**Issue by gibbon-cn** [Wox-launcher/Wox#561]
总是下载不了，能提供百度云链接吗？
![download fail](http://ww2.sinaimg.cn/large/886e01e7jw1f32akzsuzjj20lw01z0sq.jpg)

**Comment by bao-qian** [comment]
你既然能上github，不用下载器直接下行吗？

**Comment by bao-qian** [comment]
有问题再开。
