### ISSUE TITLE
appveyor无法下载

### ISSUE THREAD

**Issue by anjia0532** [Wox-launcher/Wox#562]
中文文档说是从appveyor下载最新的build，但是根本无法打开
https://ci.appveyor.com/project/qianlifeng/wox/history 就一直在loading
https://ci.appveyor.com/project/qianlifeng/wox/ 就显示Project not found or access denied.

**Comment by bao-qian** [comment]
去 release 里面找 prerelease。文档还没改。

**Comment by bao-qian** [comment]
done.
