### ISSUE TITLE
Add a setting to REMOVE the tray icon

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#563]
There is a request to hide it (https://github.com/Wox-launcher/Wox/issues/282), but I'd like to remove it completely.
I know I can hide it, but it's still there and clutters the space when I click to expand the hidden area to access another app. I'd never need a tray icon for Wox since I can easily type "settings".
Would you please add a separate option to **disable** showing **tray icon** completely (like other apps have a setting to add a tray icon)?

**Comment by highend** [comment]
+1!

**Comment by jhdxr** [comment]
It's not difficult to remove the tray icon. In fact there is a commit above which implement this feature. The problem is if we offer this option, and user somehow mess the setting (enable removing tray icon, and change hotkey to some nonsense), he cannot get Wox back unless he modify the `setting.xml` directly, which is a really bad idea for newbie.

**Comment by sqqqs** [comment]
> It's not difficult to remove the tray icon.

It seems to me that this is very difficult. This option has been asked for a very long time, but the developer closes the request.

> which is a really bad idea for newbie

For example, additional settings can be called when the installer starts.

**Comment by ayZagen** [comment]
> he cannot get Wox back unless he modify the setting.xml directly

@jhdxr The option could be disabled by opening settings from the Wox. (by right clicking on the wox input area). If hotkey is not available, launching the Wox from directory or start menu opens input area too. So no need to modify `settings.xml`. This option should be  available.

**Comment by qrqhuang** [comment]
When use `Executor` before,  I hide the tray permanently.
It didn't seem confusion to me.
So please add it anyway.

**Comment by EnKrypt** [comment]
I feel like this should work like most other apps with the same functionality do :

If wox is executed while it is already running (whether it is hidden in the tray or not), it should just open the settings (and give the user access to the hide in tray option)

This way we get the hide in tray setting in the standard way as per convention, and most importantly, it is noob friendly so it won't fuck a user over if they accidentally hide it and want it back again.
