### ISSUE TITLE
1.2.825版本，更新之后只能搜索C盘了，上一个版本都是一切正常的

### ISSUE THREAD

**Issue by RichardBao1993** [Wox-launcher/Wox#564]
1.20 beta 版本更新到825的，之前的删除以后直接解压新版本，然后打开进行搜索就搜索不到C盘以外的文件了

**Comment by bao-qian** [comment]
具体什么意思？文件还是程序？

**Comment by bao-qian** [comment]
你说的是用 everything 搜索吗？
直接用 everything 能搜索到吗？

**Comment by acebravo** [comment]
我连c盘的文件都无法搜索了。之前版本内置了everthing的搜索，可以搜索任意文件，现在版本装了插件也无法搜索。

**Comment by bao-qian** [comment]
直接用 everything 行吗？

**Comment by acebravo** [comment]
我装了everything使用没有问题

**Comment by bao-qian** [comment]
1 打开 wox
2 wox 会运行自带的 everything
3 打开 **自带** 的 everything

是这样的吗？

**Comment by bao-qian** [comment]
试一下最新版
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.900
