### ISSUE TITLE
界面：底部padding增大

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#565]
版本 1.2.825
系统：win10
重现：输入任何字符，然后删除，底部的padding会增大（应该是底部的结果在消失的时候，结果的padding没有去掉）
![image](https://cloud.githubusercontent.com/assets/1268312/14759720/cd074046-095e-11e6-98c0-02cb130ed722.png)

**Comment by bao-qian** [comment]
@iEverX 完工
CI 过慢，build 估计要等几分钟（没钱
https://ci.appveyor.com/project/happlebao/wox/build/1.2.865/artifacts
