### ISSUE TITLE
1.825版本，添加新的软件目录之后，就再也打不开这个插件了

### ISSUE THREAD

**Issue by NanerLee** [Wox-launcher/Wox#566]
1. Wox 版本：1.825
2. 重现bug 的步骤：打开设置-插件-program-添加新目录。之后程序闪退，重新打开程序，无法进入program插件，点击就会闪退
3. Windows 版本：win10

**Comment by mokeyjay** [comment]
同此问题，Win7 x64旗舰版
另外切换主题也报错，但不闪退

Wox真的很强大很好用，只可惜崩溃个不停，希望作者继续努力！谢谢作者

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/14761857/e8942892-0963-11e6-8569-8a4c74864855.png)

看看代码删除数。。。
我只能说我尽力了。。。

**Comment by mokeyjay** [comment]
额……请问这个BUG跟代码删除数有什么关系呢？

**Comment by bao-qian** [comment]
@NanerLee @mokeyjay 

感谢反馈，新 build 出来了。
试一下： https://github.com/Wox-launcher/Wox/releases/tag/v1.2.857
如果喜欢这个项目，请在右上角点 star。

**Comment by mokeyjay** [comment]
必须Star，谢谢大触
