### ISSUE TITLE
Doc plugin: SQLite processor architecture

### ISSUE THREAD

**Issue by orzFly** [Wox-launcher/Wox#57]
This will prevent Wox.Plugin.Doc working on a x86 system.

> 363  C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1635,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "System.Data.SQLite, Version=1.0.90.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=MSIL", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\Projects\Wox\Plugins\Wox.Plugin.Doc\Wox.Plugin.Doc.csproj]

**Comment by qianlifeng** [comment]
Moved to https://github.com/qianlifeng/Wox.Plugin.Doc/issues/6
