### ISSUE TITLE
结果栏里的最后一项显示不完整

### ISSUE THREAD

**Issue by NanerLee** [Wox-launcher/Wox#570]
版本：1.2858
win10
@happlebao 强迫症好难受 
![2016-04-24 13 35 16](https://cloud.githubusercontent.com/assets/16791509/14765743/9063dee2-0a21-11e6-99d4-b622511df4d8.png)
不要怪我又来报issue了。。。。。

**Comment by bao-qian** [comment]
你是高分屏吗？dpi是多少？

**Comment by NanerLee** [comment]
不是高分屏的，就是普通的笔记本1366*768，你觉得是不是跟这个问题有关？[https://github.com/Wox-launcher/Wox/issues/565](url)

**Comment by bao-qian** [comment]
@NanerLee 这种设置完了以后要 `restart wox`
CI 过慢，build 估计要等几分钟（没钱
https://ci.appveyor.com/project/happlebao/wox/build/1.2.860

**Comment by NanerLee** [comment]
好的，谢谢了
