### ISSUE TITLE
code sign

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#571]
candidates:
- https://www.startssl.com/ : Object Code Signing 59.90 dollar for 2 year
- https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing.html: 17 euro
- https://www.globalsign.com/en/ssl/ssl-open-source/: free

**Comment by lances101** [comment]
@happlebao we could go with globalsign I guess. It's been time since I used appveyor, but I think the way to go was to store the key (encrypted) in the actual git repo while storing a passphrase to that key in appveyor's environment variable.
