### ISSUE TITLE
希望清理无用文件

### ISSUE THREAD

**Issue by nicky-sh** [Wox-launcher/Wox#572]
@happlebao ，从1.2.825版本开始，感觉有好多无用文件，建议清理一下。

**Comment by nicky-sh** [comment]
比如：
Exceptionless.Models.xml
Exceptionless.xml
JetBrains.Annotations.xml
MarkdownSharp.xml
Newtonsoft.Json.xml
NLog.xml
WindowsInput.xml

**Comment by nicky-sh** [comment]
每个插件目录下的
JetBrains.Annotations.dll
JetBrains.Annotations.xml
Newtonsoft.Json.xml
NLog.xml
Pinyin4Net.dll

**Comment by nicky-sh** [comment]
*.pdb对于桌面用户也是没用的吧？

**Comment by bao-qian** [comment]
如果没有 pdb，程序 crash 了就不能知道是哪个函数的哪行导致的

**Comment by bao-qian** [comment]
其它的我会清理一下
