### ISSUE TITLE
Use existing Everything installation

### ISSUE THREAD

**Issue by SMUsamaShah** [Wox-launcher/Wox#574]
Wox uses everything to search files on the system instantly. Everything is always installed and only a hotkey away to search something. Wox should be able to use already running Everything instance instead of launching its own.

**Comment by bao-qian** [comment]
Ideally, yes…

**Comment by bao-qian** [comment]
ideally, there should be a installer which install all dependencies (python/everything)

**Comment by bao-qian** [comment]
related: 

#473 
https://github.com/Wox-launcher/Wox/issues/258
https://github.com/Wox-launcher/Wox/issues/493
#529

**Comment by bao-qian** [comment]
done.
https://github.com/Wox-launcher/Wox/releases/tag/v1.2.898

**Comment by eugenesvk** [comment]
By the way, for python dependency could you please allow a custom folder outside of the Program Files folder? I know I can just copy&paste my Conda install folder, but then I don't get the positive feedback that's it's set and I should restart my Wox and also it seems to just reset itself on restart.
Everything seems to be working fine without any additional config
Thank you!

**Comment by bao-qian** [comment]
@eugenesvk use #587
