### ISSUE TITLE
Can't (temporarily) disable everything plugin

### ISSUE THREAD

**Issue by eugenesvk** [Wox-launcher/Wox#575]
1. Please specify Wox version
   v1.2.868 
2. Please describe the steps to **reproduce** the bug
   Open Wox settings
   Try to disable Everything plugin (I wanted to test Wox other plugins without Everything interfering)
   Switch to another plugin
   See that Everything is not disabled
   Close settings
   Reopen settings
   See that there are multiple Everything plugins now
   
   Maybe it's related to the fact that I have Everything running as a background service by default (though I used to be able to disable it in some earlier versions ~a week ago)
3. Please provide Windows version
   Win 10.0.10586 x64
4. Please provide Exception info if you have.
   None
5. Please provide logs from `Wox\Logs` if you have.
   https://gist.github.com/eugenesvk/bc0fef70eb25baae9e92bb701883844b
6. Please provide screenshot if you have
   ![wox everything](https://cloud.githubusercontent.com/assets/12956286/14801963/643cde96-0b56-11e6-900b-dbe964705cb5.png)

**Comment by bao-qian** [comment]
the only way to fully disable is delete the plugin directory,
hopefully implemented in this weekend
tracking here #351

**Comment by bao-qian** [comment]
fixed in d68badfcadd4f463c6a12a54d5c06af093bf6098

**Comment by bao-qian** [comment]
Thanks for report bug
please try `Releases\Setup.exe` from latest build https://ci.appveyor.com/project/happlebao/wox/build/1.3.18/artifacts
and then upload the whole log file from `%APPDATA%\Wox\Logs`
reopen the issue if you still can't solve it
