### ISSUE TITLE
 内置的插件web searches能加入百度搜索吗？

### ISSUE THREAD

**Issue by lukaschan** [Wox-launcher/Wox#576]
1、快捷键：b
2、链接：https://www.baidu.com/s?wd={q}
3、在images文件夹加入百度logo：http://downloadicons.net/sites/default/files/baidu-icon-64296.png

当然，如果涉及版权等限制之外加不了的话，那就算咯。我们只能默默自己加上。

**Comment by bao-qian** [comment]
can't use chinese because typing by company's 
off course you can
add it and create a PR

**Comment by bao-qian** [comment]
百度加进去了：https://ci.appveyor.com/project/happlebao/wox/build/1.2.894/artifacts
