### ISSUE TITLE
UUID / ID problems and register wox extension

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#577]
@happlebao 
What you think about create `~\.wox` folder for store plugin settings/cache files, e.g. `~\.wox\data\caniuse-e234e3fbf4294af9a0b78f75bd89edd1\settings.json`, `~\.wox\cache\caniuse-e234e3fbf4294af9a0b78f75bd89edd1\name.json`?
When updating the plugin, old settings/cache are reserved.
- [ ] By the way, why plugin folder name contains UUID which differs from UUID stored in plugin.json?
- [ ] And last, how about to register Wox as the default app for .wox files, when opening .wox files be prompted to install/update the plugin?

**Comment by bao-qian** [comment]
The first one is nearly done, but should be put in APPDATA (this is not a *nix app

The second one I think is just a bug

The third one is good, but I don't have time to do it now . I'd appreciate if you could create a pr for this.

**Comment by roose** [comment]
APPDATA for plugins settings or for whole Wox app?

Unfortunately I do not know C# :disappointed: 
Recently I tried add new function in IPublicAPI, but I got smell code :laughing:  e.g.

``` c#
public bool CopyToClipboard(string text)
{
    try
    {
        Thread thread = new Thread(() => Clipboard.SetText(text));
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        thread.Join();
        return true;
    }
    catch (Exception e)
    {
        MessageBox.Show("Copy failed, please try later" + e);
        return false;
    }
}
```

python can't copy to clipboard :disappointed:

**Comment by bao-qian** [comment]
try this python library https://github.com/terryyin/clipboard

**Comment by bao-qian** [comment]
the data and program should be treated separately within wox code logic, the actual location depends on installer. e.g. normal exe installer will install to `%PROGRAMFILES%`, but clickonce will install into `%APPDA%`

**Comment by roose** [comment]
@happlebao 
Heh, creating registry keys requires administrative rights, registration Wox as the default app for .wox files is impossible :cry: 

Other variant is add file associations in `clickonce` manifest file, but Wox don't have it, and I don't know require it admin rights or not

And last, Wox already can install plugin from args, but where I can get full Wox executable path? From registry in Run key? What if user disable autorun in settings? :smile: May be necessary to add the path to the file in the settings?

**Comment by bao-qian** [comment]
a installer will coming soon, hopefully this week.
so the registry things can be done later (default app, executable path).

I'm considering remove the command line interface, why you need it? (batch install etc)?
If we keep the command line interface, of course it should be app to `%PATH%`

**Comment by roose** [comment]
nice news about installer )

I'm writing a python library(helper for python plugin developers), I want to check the new version of the plugin and offer to update it in the query results.
If you want to remove this possibility, probably need the appropriate api in PublicApi?
