### ISSUE TITLE
[Web Searches] 打开搜索建议后搜索功能失效/添加自定义webSearch引擎报热键冲突

### ISSUE THREAD

**Issue by smthvitas** [Wox-launcher/Wox#578]
【build 1.2.882】
1、setting->插件->网页搜索，勾选"启用搜索建议"后，热键唤出主窗口，输入"g test"，没有加载任何搜索建议，回车，chrome打开的链接是
"https://www.google.com/search?q="
此处没有判断无搜索建议的情况？
win7/64bit， logs中无记录

2、setting->插件->网页搜索，点添加，标题"翻译"，URL "http://dict.youdao.com/w/{q}"：
指定热键"asdfadsf"，先提示"成功"，然后提示"新触发关键字已经被指派给其他插件了，请重新选择一个关键字"。添加失败。
再指定热键"dddd"，同上添加失败。
再重新指定热键"asdfasdf"，不提示成功，直接提示"新触发关键字已经被指派给其他插件了，请重新选择一个关键字"。添加失败。

**Comment by bao-qian** [comment]
can't use chinese in company
1. this one is obviously a proxy issue, did you set proxy in wox settings and internet options?
2. I will look into this one when I come home

**Comment by bao-qian** [comment]
忘了说了
2 在 8d9f2423863a91a4b9209b9c2b7eae4e87b09af7 已经修复了
试一下吧 https://github.com/Wox-launcher/Wox/releases/tag/v1.2.882

**Comment by bao-qian** [comment]
@smthvitas 
1 的问题你填了代理设置吗。。。？

**Comment by smthvitas** [comment]
关于2
我已经是1.2.882版本了

关于1
设置代理以后也有这个问题，如果输入足够快，或者代理足够慢的话。

**Comment by bao-qian** [comment]
我看走眼了不好意思。。

设置代理以后，等一段时间建议会出来吗（网速慢？）？

**Comment by smthvitas** [comment]
会的。

**Comment by bao-qian** [comment]
那无解了啊。。。
网速慢你还能要我怎么办。。。

**Comment by smthvitas** [comment]
……

搜索建议出不来，就不能用直接输入的原文搜索吗？

**Comment by bao-qian** [comment]
@smthvitas  你是这个意思。。。
马上马上。。。

**Comment by smthvitas** [comment]
:+1:

**Comment by bao-qian** [comment]
完工，用 google 记得设代理。。。
1. 现在会自动判断网站速度，网速快就同步，网速慢就异步
2. 我忘了哪个版本修复了。。。反正我现在用 1.2.907 是没有问题的。。
@smthvitas 
https://ci.appveyor.com/project/happlebao/wox/build/1.2.907/artifacts

**Comment by bao-qian** [comment]
没解决再看
