### ISSUE TITLE
System.NullReferenceException in Wox.Plugin.Runner

### ISSUE THREAD

**Issue by Wishmaster172** [Wox-launcher/Wox#579]
Hi,

there's a problem in the Runner Plugin. Everytime I type the shortcut "r" and just space and one single letter, I get this exception:

>    bei Wox.Plugin.Runner.Runner.<>c__DisplayClass6.<Query>b__3(Command c)
>    bei System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    bei System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
>    bei System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
>    bei Wox.Plugin.Runner.Runner.Query(Query query)
>    bei Wox.Core.Plugin.PluginManager.<>c__DisplayClass30_0.<QueryForPlugin>b__0() in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:Zeile 192.
>    bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Infrastructure\Stopwatch.cs:Zeile 28.
>    bei Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:Zeile 190.

Can someone help, please?

Best regards,
Steffen

**Comment by bao-qian** [comment]
I think this is a bug of plugin
open issue here:
https://github.com/jessebarocio/Wox.Plugin.Runner/issues

**Comment by bao-qian** [comment]
Fixed now, update it with `wpm install Wox.Plugin.Runner`
