### ISSUE TITLE
每隔一天，设置总是会自动丢失，一切被初始化

### ISSUE THREAD

**Issue by mokeyjay** [Wox-launcher/Wox#580]
版本：1.2.865
系统：Win7 x64 旗舰版

设置了开机启动，今天发现皮肤又恢复为Gray了，打开一看果然设置都被重置了。大概是隔一天来一次，这是什么奇葩BUG……？

**Comment by iEverX** [comment]
#482 
不过我的丢的没有这么频繁

**Comment by bao-qian** [comment]
你关机了是吗？

**Comment by mokeyjay** [comment]
当然关机了啊……每天都关机的

**Comment by bao-qian** [comment]
今天有空修。暂时办法是手动退出。打 （exit

**Comment by mokeyjay** [comment]
难道配置不是实时保存的嘛……真是奇葩BUG，辛苦了

**Comment by bao-qian** [comment]
请再试一下：https://ci.appveyor.com/project/happlebao/wox/build/1.2.892/artifacts

**Comment by Freedomlee5y14** [comment]
有一个问题就是：键入了关键词之后，它的下面的选项光标会自动向下跳。
