### ISSUE TITLE
Incompatible plugins and settings can't be saved

### ISSUE THREAD

**Issue by kawori** [Wox-launcher/Wox#581]
OS: Windows 10 build 10582
~~Issue1. On neither the latest version 1.2.822 nor the older version (1.2.0-beta2), the shell plugin could not work normally - After typing '>', there is no reactions.~~
Issue2. On version 1.2.822, ~~trying to right-click Wox's icon to exit would cause "Wox has stopped working" problem.~~ And after installing a new plugin, restarting Wox would cause the same problem.
Issue3. On version 1.2.822, some of Wox's settings would be reset after shutting down the machine, e.g. the trigger of everything would be reset to none.

**Comment by bao-qian** [comment]
issue3 should be fixed in this build：https://ci.appveyor.com/project/happlebao/wox/build/1.2.892/artifacts

**Comment by bao-qian** [comment]
for issue1, could you paste your logs (`%APPDATA%/Wox/Logs`) here?

**Comment by kawori** [comment]
I'm pretty sorry for my mistake. 
I've just found that a blank space is needed after typing '>' to run shell command.
I'll delete issue1 after now.

**Comment by bao-qian** [comment]
For issue 2, paste your logs here too

**Comment by kawori** [comment]
There's no logs there.
But a wrong info snip was made by me.

![info](https://cloud.githubusercontent.com/assets/11918823/15016046/cd59733e-1241-11e6-8f31-c035bc0cfc9a.png)

**Comment by bao-qian** [comment]
1. Could you also check Logs in your installation location? (`Wox\Logs`).
2. Could you paste the **Details** of this wrong info? As you can see, you can scroll the scroll bar.....

**Comment by kawori** [comment]
**1. Log**

[2016-05-04.log.txt](https://github.com/Wox-launcher/Wox/files/248888/2016-05-04.log.txt)

**2. Details of the wrong info**

[_wox_complete_info_of_system_warnning.txt](https://github.com/Wox-launcher/Wox/files/248883/_wox_complete_info_of_system_warnning.txt)

**Comment by bao-qian** [comment]
could you make an clean log by
1. delete `Wox` installation directory and `%APPDATA%\Wox`
2. exit wox by right click tray icon
2. copy the new log to here

**Comment by kawori** [comment]
It seems that I could find the second issue only after installing a new plugin and restarting wox by wox's hints automatically. 
Then there would be two tray icons of wox on the task bar. 
And now, if I right click the tray icon to exit wox, the ".NET framework" warnning would appear after a while.

**Comment by bao-qian** [comment]
大哥 我们用中文

第二个问题是随便装一个插件还是就是特定插件？（clipboard ？）

两个 tray icon 不影响，鼠标移上去会消失

now 你指什么？装了导致第二个问题的插件还是什么都没装没改？给 logs 和 截图……

**Comment by kawori** [comment]
就是在 wpm install clip 之后，wox 会提示要不要重启以使得 plugin 生效，选择 OK 之后，
wox 就重启了。然后任务栏就有了两个 tray icon，而且是同时存在的，cursor 移上去也不会消失。
然后想去掉一个，就会 right click 其中一个 icon 来退出 wox，几秒钟之后就出现上面那个图
（.NET Framework）了，选择 Quit 之后，其中一个 wox 就消失了。

只装过 clipboard 和 remove usb，都是如此。

**Comment by bao-qian** [comment]
这是插件挂了导致不能正常退出
测试版改了一些 api

我会在下个测试版加一些兼容层

**Comment by bao-qian** [comment]
我看了一下， remove usb 应该是没有问题的。
clipboard 插件挂并不是因为新的 api 变动。好久没更新了，已经挂了好久了。。
