### ISSUE TITLE
Settings not saved unless you clean exit

### ISSUE THREAD

**Issue by shaivyamahajan** [Wox-launcher/Wox#583]
Versions tried: 1.2.882 and 1.2.875

OS: Windows 10 v1511

Steps to reproduce: Change some plugin / Wox settings and exit the **settings** panel.  Now check the JSON config files, none of the changes get written.  Now completely exit Wox using the tray icon, and the config files get updated.  

Note: If you have change settings, close the settings dialog and reboot (cleanly) it will still fail to save the settings.  This is how I first ran into the problem after upgrading. 

Bit of an inconvenience, might be hard for people to figure out what is going on.

**Comment by bao-qian** [comment]
thanks for report
try again: https://ci.appveyor.com/project/happlebao/wox/build/1.2.892/artifacts
