### ISSUE TITLE
1.2.882 crashed with switcheroo 1.0.4

### ISSUE THREAD

**Issue by lunxian** [Wox-launcher/Wox#584]
## English

Before you report any bugs, please try [latest build](https://github.com/Wox-launcher/Wox/wiki/FAQ-English#how-to-install-latest-build) 
from **master** branch.
1. Wox   - 1.2.882
2. wpm install switcheroo 1.0.4, restart , then crashed
   3.Win 10.0.586
3. crashed with a flash screen, then all is gone.
4. Logs:
   2016-05-02 11:43:03.8479|INFO|Wox.Infrastructure.Logger.Log|Preload 272 programs from cache
   2016-05-02 11:45:27.2837|FATAL|Wox.Infrastructure.Logger.Log
   [2016-05-02.log.txt](https://github.com/Wox-launcher/Wox/files/244560/2016-05-02.log.txt)

**Comment by lances101** [comment]
Please report this to the [Switcheroo repo](https://github.com/Wox-launcher/Wox.Plugin.Switcheroo)

**Comment by lances101** [comment]
Please test. Updated Switcheroo to work with the [latest build from the master branch `1.2.891`](https://ci.appveyor.com/project/happlebao/wox/build/1.2.891/artifacts)
