### ISSUE TITLE
1.2.882安装Browser Bookmarks插件崩溃

### ISSUE THREAD

**Issue by atomsyoung** [Wox-launcher/Wox#585]
1.wox版本：1.2.882
2.使用`wpm install Browser Bookmarks`命令安装插件后重启，软件崩溃并无法重新打开，删除wox所在文件夹后使用重新解压后的程序文件夹仍然崩溃并马上关闭
3. Windows 版本：Windows 8.1 Pro 64bit

**Comment by bao-qian** [comment]
删除那个插件文件夹
要么在 %appdata%/wox/plugin 要么在 wox/plugin

**Comment by atomsyoung** [comment]
多谢。我已经解决了，用的同样方法。
