### ISSUE TITLE
开机自启搜索框界面能否自动隐藏或者直接后台启动？

### ISSUE THREAD

**Issue by lukaschan** [Wox-launcher/Wox#586]
最新的1.2.894版本，开机自启时，搜索框界面必须得点一下搜索框，再点外部，搜索框才会自动隐藏。我想最好是开机直接后台启动，就不要显示搜索框界面了，毕竟几乎没人一开机就用的。你说呢？

**Comment by bao-qian** [comment]
道理是这个道理。。。
但最近不是很有空修这个。。。

**Comment by zhao-xu** [comment]
已提交 PR，不知道翻译的东西是人翻还是机翻，只写了简中和英文的
