### ISSUE TITLE
Wox cannot start everything plugin automatically @1.2.900

### ISSUE THREAD

**Issue by flying3615** [Wox-launcher/Wox#591]
## English

Before you report any bugs, please try  **Pre-release** in [Releases](https://github.com/Wox-launcher/Wox/releases)
1. Please specify Wox version
   1.2.900
2. Please describe the steps to **reproduce** the bug
   start wox, there will be a warning saying "everything is not running", click it and it will return error
3. Please provide Windows version
   win 10
4. Please provide Exception info if you have.
   System.NullReferenceException

在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__97_8(Object o) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 305
   在 Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 321
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

报 bug 之前, 请试一下 [Release](https://github.com/Wox-launcher/Wox/releases) 橘红色标签的 **Pre-release**
1. 请提供 Wox 版本
   - 如果你是从 Github Releases 下载的，请提供 **build number** (e.g. 1.2.0.550)
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
2. 请提供如何**重现** bug 的步骤
3. 请提供 Windows 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

**Comment by bao-qian** [comment]
use existing installed everything
download .exe installer from https://www.voidtools.com/
use x64 version if your windows is 64bit

**Comment by flying3615** [comment]
Thanks, I just thought wox still comes with everything.
after install everything alone, it works
