### ISSUE TITLE
Add Dictionary plugin

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#6]

**Comment by qianlifeng** [comment]
b2081dcbc97917ffa47b5f713482ac949abd04d0

**Comment by FatCache** [comment]
There is no offline dictionary support/plugin for Wox Launcher. I'm willing to work on it if there is support for it. Top of my head, integrating this https://wordweb.info/developer/ with Wox Launcher would be a really nice add-on in my opinion. 

-> https://github.com/harrynull/WoxDictionary this might be it.
