### ISSUE TITLE
1.3.0 使用主题“BlurBlack”，重启crash！

### ISSUE THREAD

**Issue by skefy** [Wox-launcher/Wox#606]
系统：win10 64位
wox：1.3.0
描述：设置中使用“BlurBlack”主题，然后重启wox，就会出现crash！

**Comment by bao-qian** [comment]
如果不能重启的话，暂时先把 `%APPDATA%\Wox\Settings\Settings` 删了。

**Comment by bao-qian** [comment]
感谢汇报
试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/1.3.9/artifacts
的  `Releases\Setup.exe`
