### ISSUE TITLE
设置界面

### ISSUE THREAD

**Issue by iEverX** [Wox-launcher/Wox#608]
win10英文版，wox 中文
每次启动，两个按钮都看不见。把语言改为英文再改成中文，才能正常显示。应该是没有响应的语言翻译

![image](https://cloud.githubusercontent.com/assets/1268312/15133835/436221ba-1699-11e6-9bde-a70d5a21c3f7.png)
![image](https://cloud.githubusercontent.com/assets/1268312/15133844/54e23560-1699-11e6-97da-b0237796d1ce.png)

**Comment by iEverX** [comment]
1.3.30版本，bug还在

**Comment by ousui** [comment]
同楼主，切换成英文直接没有文字了。

**Comment by bao-qian** [comment]
https://ci.appveyor.com/api/buildjobs/kaqpru7vp275d5ux/artifacts/Releases/Setup.exe
