### ISSUE TITLE
Cannot disable plugins on v1.3.0 release

### ISSUE THREAD

**Issue by gregist** [Wox-launcher/Wox#609]
System: Win 10 English with latest update

When I try to tick the `disable` checkbox in the plugin submenu, the plugin duplicate itself to the bottom of the list.

![2016-05-10_16-46-19](https://cloud.githubusercontent.com/assets/6292095/15140860/a49bc658-16cf-11e6-8eec-36af49b330cd.png)

**Comment by bao-qian** [comment]
temp fix: disable the plugin directory

**Comment by bao-qian** [comment]
@gregist @koteq
Thanks for report bug
please try `Releases\Setup.exe` from latest build https://ci.appveyor.com/project/happlebao/wox/build/1.3.18/artifacts
and then upload the whole log file from `%APPDATA%\Wox\Logs`
reopen the issue if you still can't solve it
