### ISSUE TITLE
Wox 1.3 instant crash

### ISSUE THREAD

**Issue by Dikay900** [Wox-launcher/Wox#612]
1. Wox Version v1.3
2. Windows 10 x64
   log: https://gist.github.com/Dikay900/5f541afbe9af99c161b898dac637cb71
   error in english says cannot access file because its getting used by another process

i upgraded from 1.2.989 which was running just fine before. I already made a clean install.

I also saw that after installing wox it was started twice since i got two standard exception windows saying exactly the same error as stated here.

**Comment by bao-qian** [comment]
Just delete that file or try restart your computer.

**Comment by Dikay900** [comment]
thanks that fixed it, way too easy...
:+1: keep up the great work

**Comment by bao-qian** [comment]
Great to hear that :)
