### ISSUE TITLE
1.3.0运行setup出错

### ISSUE THREAD

**Issue by jingouwangzi** [Wox-launcher/Wox#615]
github releases下载的1.3.0 setup文件，运行直接出错，家里和办公室电脑（win10 1511 X64）都出现相同的情况。
![default](https://cloud.githubusercontent.com/assets/5857162/15219443/643d92da-1896-11e6-9552-bcc50602a675.PNG)
异常类型：
System.ArgumentNullException
异常源：
PresentationFramework
堆栈信息：
在 System.Windows.Interop.WindowInteropHelper..ctor(Window window)
   在 Wox.Core.Resource.Theme.SetWindowAccent(Window wind, AccentState themeAccentMode) 位置 C:\projects\wox\Wox.Core\Resource\Theme.cs:行号 181
   在 Wox.Core.Resource.Theme.ChangeTheme(String themeName) 位置 C:\projects\wox\Wox.Core\Resource\Theme.cs:行号 66
   在 Wox.ViewModel.MainViewModel..ctor() 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 71
   在 Wox.App.<OnStartup>b__12_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 46
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
感谢汇报
把 `%APPDATA%\Wox\Settings\Settings` 删了。
试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/1.3.9/artifacts
的  `Releases\Setup.exe`
