### ISSUE TITLE
include WinSxS by default

### ISSUE THREAD

**Issue by smthvitas** [Wox-launcher/Wox#616]
为什么不能把windows中间点开始->运行能够直接运行的，都作为搜索结果的默认值？

例如搜索regedit，注册表编辑器排在很靠后的位置，甚至在文件夹之后；
搜索msconfig，同样。
搜索cmd更过分，从头翻到尾都没有cmd.exe的影子。

**Comment by bao-qian** [comment]
`C:\Windows\WinSxS` 手动加这个目录

**Comment by smthvitas** [comment]
什么意思？在哪里加？
settings->插件->文件夹？
加了没用啊。regedit/msconfig都找不到

**Comment by bao-qian** [comment]
program 那个插件

**Comment by bao-qian** [comment]
这个目录有的目录名有太多杂音，我会单独处理一下

**Comment by bao-qian** [comment]
- [ ] add all executable from %PATH% to program plugin
