### ISSUE TITLE
关于无法安装任何插件的问题！

### ISSUE THREAD

**Issue by ChannD** [Wox-launcher/Wox#619]
1. 1.3版本
2. 在在安装插件过程中
3. Windows10 14342 rs1

![image](https://cloud.githubusercontent.com/assets/13447467/15268568/a3415f1c-1a16-11e6-82ac-f90e202a8349.png)

**Comment by bao-qian** [comment]
please try 1.3.21
https://ci.appveyor.com/project/happlebao/wox/build/1.3.21/artifacts

**Comment by ChannD** [comment]
Thank you !!!
