### ISSUE TITLE
"Could not load assembly" on wpm install *

### ISSUE THREAD

**Issue by alexb5dh** [Wox-launcher/Wox#621]
Trying to install any plugin via `wpm install` leads to the following:
![image](https://cloud.githubusercontent.com/assets/4650832/15273491/dc984914-1aa3-11e6-977d-0cacebe51921.png)

The problem is in one the libraries (_Wox.Core_ maybe, not sure) that references signed version of _ICSharpCode.SharpZipLib.dll_ while unsigned one is provided in the installer.
Replacing it with signed version from nuget fixes the problem.

**Wox**: 1.3.0
**Windows 8.1**

**Comment by bao-qian** [comment]
please try 1.3.21
https://ci.appveyor.com/project/happlebao/wox/build/1.3.21/artifacts

**Comment by alexb5dh** [comment]
Can't test with **1.3.21** as `wpm install *` is forever loading even after response arrived but it works fine in **1.3.26**.
