### ISSUE TITLE
Wox能提供一个离线运行的选项么？

### ISSUE THREAD

**Issue by bestony** [Wox-launcher/Wox#622]
在离线情况下会报错无法连接api.github.com
能不能加一个选项，支持离线功能？
离线情况下不会报错，可以正常使用？

**Comment by bao-qian** [comment]
can't use chines in company
in the latest build, 
the network error of auto updates will be dismissed
https://ci.appveyor.com/project/happlebao/wox/build/1.3.27/artifacts

**Comment by bao-qian** [comment]
please star wox if you like it.
