### ISSUE TITLE
Start wox on system startup don't work

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#625]
Windows v10
Wox v1.3.27

path in autorun app-1.3.27 folder, not app-1.3.27\wox.exe
![wox autorun](https://cloud.githubusercontent.com/assets/277651/15327796/6ce7fad8-1c74-11e6-97d0-0919f8e5a4f5.png)

**Comment by bao-qian** [comment]
you seems using win10, right?
but your logs shows that you are using win8 (Microsoft Windows NT 6.2.9200.0).

**Comment by roose** [comment]
Microsoft Windows [Version 10.0.10586]
I don't know why shows as win8 )

**Comment by lunxian** [comment]
遇到同样问题

**Comment by NanerLee** [comment]
确实有这个问题，我试过好几个1.30之后build的版本，都有，我也是win10

**Comment by bao-qian** [comment]
thanks for report.
fixed:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.35/artifacts
