### ISSUE TITLE
Using without internet crashes

### ISSUE THREAD

**Issue by dandrejvv** [Wox-launcher/Wox#630]
## English
1. Please specify Wox version
   
   1.3.0
2. Please describe the steps to **reproduce** the bug
   
   Disconnect from the internet (disable WiFi or plug out your network cable or disable your network adapter) and try to use Wox.
3. Please provide Windows version
   
   Windows 8.1 and Windows 10
4. Please provide Exception info if you have.
   
   See screenshot
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
   
   [2016-05-18.txt](https://github.com/Wox-launcher/Wox/files/270152/2016-05-18.txt)
6. Please provide screenshot if you have

![error](https://cloud.githubusercontent.com/assets/7236289/15354762/8032a8b0-1cef-11e6-979c-d5fc40481e4c.png)

![exception](https://cloud.githubusercontent.com/assets/7236289/15354769/83ba19aa-1cef-11e6-90aa-4de6941ad962.png)

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.29/artifacts

**Comment by dandrejvv** [comment]
@happlebao May I ask why this is closed without a reason given?

**Comment by bao-qian** [comment]
@dandrejvv just download setup.exe in the above link, this has been fixed in current code

**Comment by dandrejvv** [comment]
Apologies. I downloaded the latest version and it works. Thanks.

**Comment by bao-qian** [comment]
great! :smile:
