### ISSUE TITLE
为什么wox能找到不精确的匹配结果？

### ISSUE THREAD

**Issue by smthvitas** [Wox-launcher/Wox#631]
版本：1.2.882
搜索mactype，everything能给出精确的搜索结果，三个：
D:\Software\UI\MacType
D:\Software\UI\MacType\MacType.dll
D:\Software\UI\MacType\MacType.ini

wox搜索mactype，搜出大概三四页，一堆windows rights management之类的，everything的结果排在最后。摘录其中一个如下：
C:\Windows\winsxs\x86_microsoft-windows-s..native-whitebox-isv_31bf3856ad364e35_6.1.7601.17514_none_eb5947ea4debcf36\RMActivate_isv.exe
这个文件和mactype似乎没有什么关系？

**Comment by bao-qian** [comment]
现在没有一个统一的评分结果
program 插件默认比 everything 插件高

**Comment by smthvitas** [comment]
很影响体验啊。program插件能不能指定排除某些目录？不行就只能禁用这个插件，常用的几个程序都手工置顶了
2016年5月18日 下午7:37，"happlebao" notifications@github.com写道：

**Comment by bao-qian** [comment]
`winsxs` 把这个目录从 program 里面移除就好了

**Comment by bao-qian** [comment]
我看到你 #616 了
我会想办法把这两个一起修了

**Comment by smthvitas** [comment]
ok，感谢。
我个人感觉，wox需要的不是实时搜索更多目录，而是更少目录。如果能自定义排除某些目录的搜索结果就好了。
在没有完善的技术手段的前提下，是否可以考虑把路径短的结果优先放前面？
截个图供参考：

​
另外，1.3版本确实快很多，赞！

2016-05-18 22:09 GMT+08:00 happlebao notifications@github.com:

**Comment by smthvitas** [comment]
![image](https://cloud.githubusercontent.com/assets/18712253/15379777/041711a8-1da3-11e6-96c6-2dc1048b39ba.png)

Gmail直接回复不能带图啊

**Comment by junxy** [comment]
因为这个小问题，我还用着 `1.2.0`版本，感觉不升级没什么问题 :joy:

**Comment by smthvitas** [comment]
1.3版本确实bug有点多

2016-09-28 20:00 GMT+08:00 Junior Hsu notifications@github.com:

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases

if you want to search for files only, use  everything search syntax like `files:`
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
