### ISSUE TITLE
wox crashes when view pre/next searches

### ISSUE THREAD

**Issue by pythonik** [Wox-launcher/Wox#632]
Version: Latest master branch development build
Reproduce step:
- Build wox in VS 2015, Delete Wox folder from %APPDATA%
- Open wox.exe from debug folder
- search "notepad" and open it
- search "python", open python console 
- backspace remove "python" from searchbox
- repeat Ctrl+up to show previous searches
- Wox crashed with following exception 
  ![6](https://cloud.githubusercontent.com/assets/5600432/15369130/e818cd2c-1cf6-11e6-942b-551cb1860010.PNG)

Reproducible in Win7 and Win10

**Comment by bao-qian** [comment]
yes: #592

**Comment by bao-qian** [comment]
@pythonik try new build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.177/artifacts
