### ISSUE TITLE
Elevate application priviledges

### ISSUE THREAD

**Issue by dandrejvv** [Wox-launcher/Wox#633]
With [Launchy](http://www.launchy.net/) you had the option to run an application with elevated admin priviledges by typing in the application name and instead of pressing enter you pressed CTRL+SHIFT+ENTER. Windows would prompt you for launching the application with elevated priviledges (if so configured in Windows of course) and then it would happen.

It would be great to have a similar feature for WoX to launch applications with elevated administrator priviledges by having some hot keys being pressed or something.

**Comment by bao-qian** [comment]
shift + enter 
then you get context menu
![image](https://cloud.githubusercontent.com/assets/1169912/15372623/3a644786-1d39-11e6-9607-ebf3362f6830.png)

**Comment by dandrejvv** [comment]
Thanks for the very quick reply! You guys are really responsive!

**Comment by bao-qian** [comment]
please star it if you like it :smile:
