### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by dandrejvv** [Wox-launcher/Wox#634]
Is there something in the pipeline to import/export the WoX settings along with the plugin settings?
It would also be great if it stored the list of plugins installed so that if I were to move to another desktop, install Wox and import the settings, that it would download the plugins for me and apply their settings if applicable.

**Comment by bao-qian** [comment]
copy the whole %APPDATA%\Wox for now

**Comment by dandrejvv** [comment]
Ok, sounds fair.

**Comment by bao-qian** [comment]
exclude Cache

**Comment by bao-qian** [comment]
use #259
