### ISSUE TITLE
Plugin Download Error with ICSharpCode.SharpLibZip.dll

### ISSUE THREAD

**Issue by lee0c** [Wox-launcher/Wox#637]
Wox 1.30
Windows 8, 64-bit

Full log (fairly empty as I just reinstalled to see if there was just a simple install error):

> 2016-05-18 23:09:06.8144|INFO|Wox.Infrastructure.Image.ImageLoader.PreloadImages|Preload 0 images from cache
> 2016-05-18 23:09:07.6335|INFO|Wox.Infrastructure.Stopwatch.Normal|Preload 0 programs from cache

Error description/reporoduction:
When trying to install plugins via wpm install (has happened with four unrelated plugins, it's not plugin specific), installation tries and fails. Error message:

> download plugin [name] failed. Could not load file or assembly "ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Screenshots:

![step1](https://cloud.githubusercontent.com/assets/13122293/15381760/878b1938-1d50-11e6-9cb1-47670c1ee58b.png)
![step2](https://cloud.githubusercontent.com/assets/13122293/15381761/878f5462-1d50-11e6-988c-c024aab8dbe5.png)

**Comment by bao-qian** [comment]
.... use 1.3.30
