### ISSUE TITLE
使用1.3.30版的wox无法安装open filezilla插件

### ISSUE THREAD

**Issue by godefy** [Wox-launcher/Wox#638]
以前一直在使用1.20版本，插件可以正常使用。
安装了最新的1.3.30版本，无法安装open filezilla插件。
使用wpm install 插件名 方式  和 直接将以前的插件文件目录拷贝的方式都无法成功安装。

**Comment by bao-qian** [comment]
报什么错？log 呢？

**Comment by godefy** [comment]
我以为这是个必现的问题，看来不是。我去找一下Log。

**Comment by bao-qian** [comment]
没问题我就关了咯
