### ISSUE TITLE
有道插件

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#639]
## 中文 / Chinese

版本： 1.3.30
系统： Win 10 pro x64 

复现步骤：
1. 执行 `wpm install Youdao Translator`  （在这一步能够自动提示Youdao Translator这个插件）
2. 提示是否要安装有道翻译插件，确定
3. 提示是否要安装下列插件（有道翻译 0.0.1），选择是
4. 提示有道翻译插件安装成功，是否要重启wox，选择是
5. 重启后搜索`yd apple`，没有效果。插件里没有显示有道翻译插件，在插件目录下也没有看到相应的文件。

**Comment by bao-qian** [comment]
这插件有问题，下架了，还没修好。。。。。

**Comment by bao-qian** [comment]
use #590

**Comment by bao-qian** [comment]
@jhdxr 
插件已更新
http://www.getwox.com/plugin/78

**Comment by bao-qian** [comment]
忘了说了。。需要配合新版 wox
https://ci.appveyor.com/project/happlebao/wox/build/1.3.64/artifacts

**Comment by jhdxr** [comment]
@happlebao 测试ok，似乎和老的不是同一个插件了，有两个疑问/建议（如果有需要的话我可以去新开个issue）
1. 老插件依然能搜到（在`wpm install`中），这是个接口上的bug？
2. `plugin.json`允许开发者设置能够兼容的wox的最低版本/最高版本

**Comment by bao-qian** [comment]
@jhdxr
1. 有个 python 版本的，不是我写的。。。也不是原作者写的。。。
2. 公开 api 是一直没有动的。。。
   实现可能有变化，或者用了未公开 api。。。
   `plugin.json` 中指定 api 版本会在 #537 后加入
