### ISSUE TITLE
1.3.38 switchhero image cause wox crash

### ISSUE THREAD

**Issue by lunxian** [Wox-launcher/Wox#640]
更新了1.3.38，发现在弹出错误弹窗后，就无法进行everything的搜索了。
log如下：
[2016-05-19.log.txt](https://github.com/Wox-launcher/Wox/files/272459/2016-05-19.log.txt)

**Comment by bao-qian** [comment]
错误弹窗你贴出来啊。。。。
试下删除 `%APPDATA%\Wox\Cache\ImageCache`

**Comment by lunxian** [comment]
![image](https://cloud.githubusercontent.com/assets/550273/15413718/c2e45a10-1e65-11e6-993d-8dff1bc04ad8.png)

刚才有出现一次， 图片见上面的。  出现这个以后，发现是所有功能都失效。 不仅仅是搜索不行了。 
挺严重的。

log如下：
[2016-05-20.log.txt](https://github.com/Wox-launcher/Wox/files/273690/2016-05-20.log.txt)

**Comment by bao-qian** [comment]
你删了 imagecache 吗？
这是 Switcheroo 的问题。。敬请期待他的更新。。。
https://github.com/Wox-launcher/Wox.Plugin.Switcheroo/issues/5

**Comment by lunxian** [comment]
删除了 imagecache了。

等待switcheroo的更新。 也希望我们这个版本尽快稳定。
