### ISSUE TITLE
Typed in phrase doesnt bring up the desired list of items

### ISSUE THREAD

**Issue by dandrejvv** [Wox-launcher/Wox#643]
It is something that happens on occasion and I understand that the tool is doing the best it can but for the times when it doesn't fully behave the way I expect, is there a way to explicitly say that "I want this phrase to be associated with this application"?

So in the scenario that I am in, I have a tool called ConEmu but I don't want to type in "ConEmu" to gain access to it, instead I would like to type in "cmd". The given list of items that "cmd" shows does not show the application I am looking for, instead it does have references to some of its couterparts but they are not the things I'm looking for.
So is there a way to tell WoX to associate "cmd" strongly with "ConEmu"?

I hope this makes sense.

**Comment by bao-qian** [comment]
make a directory called association
Add this directory to program plugin
Make a shortcut to conemu called cmd
Done

**Comment by dandrejvv** [comment]
Hmm, not quite what I expected. I can use that as a workaround for now. Any possibility for this to be an enhancement?

**Comment by bao-qian** [comment]
No
The aim of this project is automatically match
Why not use cmu instead of cmd

**Comment by dandrejvv** [comment]
Because "cmd" or "command" doesn't come up with the normal windows command prompt in the suggestion list and ConEmu is a replacement console for the Windows console. 
It picks up the other consoles like Visual Stuiod's Command Prompt link or the Python command prompt one but not the vanilla one and so those consoles are the plain old Windows console versions (or some variation thereof) where ConEmu can't hook into.

So essentially I want to open the normal windows command propmpt from WoX but I don't see the normal option in the list.

**Comment by dandrejvv** [comment]
![command options](https://cloud.githubusercontent.com/assets/7236289/15405202/3148cc08-1e01-11e6-9981-31297066a4fb.png)

Here is an example

**Comment by dandrejvv** [comment]
Ok, nevermind. I think there is a separate issue to address.
Sorry for the trouble and thanks for your help.

**Comment by bao-qian** [comment]
upload your screenshot
![image](https://cloud.githubusercontent.com/assets/1169912/15405662/bee630ac-1dfa-11e6-9380-60754bffa651.png)

**Comment by dandrejvv** [comment]
![command options](https://cloud.githubusercontent.com/assets/7236289/15405952/9357fa42-1e04-11e6-9db3-d3086f1188f2.png)

**Comment by dandrejvv** [comment]
![command options2](https://cloud.githubusercontent.com/assets/7236289/15406002/bfc815ee-1e04-11e6-92de-10ef6f1d103a.png)

The first item is not the one I'm looking for, its some other utility of ConEmu.

**Comment by bao-qian** [comment]
i'm confused.
what are you trying to find?
command prompt or conemu?

**Comment by dandrejvv** [comment]
I wanted to find ConEmu by typing "command" or "cmd"

**Comment by bao-qian** [comment]
then why? why "console" or "cmu" or "emulator" won't suit your purpose?

**Comment by dandrejvv** [comment]
It does, I just like to type cmd for command prompt.
Like I said, I think there is an issue with ConEmu that it is not replacing the normal command prompt being executed from WoX.
So if I type "cmd" and choose "Command Prompt" I want ConEmu to show up even though it is bringing up the normal windows comand propmpt, it is supposed to be one of its features.

**Comment by bao-qian** [comment]
ok
