### ISSUE TITLE
Huge Ugly buttons in Wox error dialog

### ISSUE THREAD

**Issue by Artoria2e5** [Wox-launcher/Wox#646]
VoX 1.3.30, Windows 10b14342
## Steps to Reproduce:
1. Don't install Everything
2. Open Wox
3. Click the 'not installed' warning
4. 'Object reference not set to an instance of an object.'
## What's wrong?

Use your eyes:
![image](https://cloud.githubusercontent.com/assets/6459309/15413786/cc13c5b2-1e01-11e6-8078-d4eae9f5d12b.png)

**Comment by Artoria2e5** [comment]
我个人是觉得图标没必要。

**Comment by bao-qian** [comment]
没有美工就是这样的啦啦。。。

**Comment by bao-qian** [comment]
那两个 button 其实没用了，我等下删掉。。。

**Comment by Tr0jsperi** [comment]
所以现在可以不装everything使用吗？开启了everything插件但是一直提示Everything 没有运行

**Comment by bao-qian** [comment]
@troywmz 可以。忽略或者禁用插件

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.59
