### ISSUE TITLE
[1.3.30] 随系统自动启动失败

### ISSUE THREAD

**Issue by smthvitas** [Wox-launcher/Wox#649]
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
"Wox"="\"C:\Users\user\AppData\Local\Wox\app-1.3.30\" --hidestart"

D:>"C:\Users\user\AppData\Local\Wox\app-1.3.30" --hidestart
'"C:\Users\user\AppData\Local\Wox\app-1.3.30"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by bao-qian** [comment]
fixed:
https://ci.appveyor.com/project/happlebao/wox/build/1.3.35/artifacts
