### ISSUE TITLE
插件开发的一些问题

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#652]
尝试做了一个ip138的插件，遇到了一些问题，虽然基本上都解决了，但是还是在这反馈一下。
wox版本：master分支
参考doc：http://doc.getwox.com/zh/index.html

http://doc.getwox.com/zh/plugin/plugin_json.html 里提到plugins.json中`ActionKeyword`字段应该是一个string，参考wox项目里其他插件，大部分也是如此。但是我这么做了以后却失败了，排查后发现在`GetPluginMetadata`中解析时这个自动是解析为collection的，所以应该是一个数组。换成数组后问题解决。
上面这个变更，如果原先是支持字符串，后面改为数组的，那我觉得应该实现成两种都支持（出于对老的插件的兼容性考虑，频繁改动接口/约定并不好）

---

网站相关：
1. 上传需要wox类型，完全不知道是什么东西。。。
2. 猜测是zip改了个后缀，试了下，server error。。。

---

使用相关
虽然在wox里直接`wpm install`感觉很酷。但我觉得如果有一个文件，双击一下直接安装（正如alfread那样）会更方便

**Comment by jhdxr** [comment]
@happlebao 上传插件那个问题能不能解答下。。。

**Comment by bao-qian** [comment]
ActionKeywords 是数组，
ActionKeyword 是字符串
老接口没有变，所以才没去改文档。。。

就是 zip 类型。你丢上来我看一下
参考：https://github.com/Wox-launcher/Wox/issues/524

网站不是我写的，所以不是很清楚。。。。

**Comment by jhdxr** [comment]
文件在此（由于github限制文件后缀，因此并没有改为wox）
[Wox.Plugin.IP138.zip](https://github.com/Wox-launcher/Wox/files/275178/Wox.Plugin.IP138.zip)

icon就用的image目录下那个icon（.ico和转为png都试过，都不行）

附github地址（如果需要自己编译一下看看的话）：https://github.com/jhdxr/Wox-Plugin-IP138

**Comment by bao-qian** [comment]
咦 icon 和不能上传什么关系？

**Comment by bao-qian** [comment]
上传插件右上角有错误提示的，你截个屏

**Comment by jhdxr** [comment]
提示就只是简单的server error，如图，我也很无奈。。。
![error](https://cloud.githubusercontent.com/assets/1993373/15446075/96aa5888-1f45-11e6-841b-c40804612e6d.png)

**Comment by bao-qian** [comment]
这样是成功的
![image](https://cloud.githubusercontent.com/assets/1169912/15448895/6b567326-1f66-11e6-8268-29fa041b4823.png)

**Comment by bao-qian** [comment]
我试过了 你再试试吧

**Comment by jhdxr** [comment]
的确成功了。。。我知道原因了。。。文件名不能含中文，然而我的效果图是直接QQ截图的。。。
