### ISSUE TITLE
Folder 结果的默认图标

### ISSUE THREAD

**Issue by Artoria2e5** [Wox-launcher/Wox#655]
WoX 1.3.46.

似乎目前非文件夹的东西得到的图标还是 WoX默认，建议找个一张纸的文件图标之类的。exe 什么的要是能直接用程序的图标就更好了（别的其实也可以用 Windows 设置的图标）。

如果想复制图标的话也许可以看看 Numix（忘记是什么许可证的了，反正可以考虑做外置图标包←挖坑）。另外 WoX 本身的图标长得有点不 Windows 在任务栏里略奇怪，可以考虑做个透明白色的简单的矢量图标。别的我不知道，只知道字要用 Segoe UI.

**Comment by bao-qian** [comment]
program 插件用了 win 的图标啊，folder 插件没有。
给个截图？shift enter 可以看是哪个插件…
这是以前不知道谁画的，我个人完全不会画画………

**Comment by bao-qian** [comment]
或者你来一个？我的支付宝已经饥渴难耐（

**Comment by Artoria2e5** [comment]
确认是 Folder
1. Alt Space
2. `C:\Windows\system32`
3. 下，找个 dll 看

**Comment by happlebao** [comment]
> 下，找个 dll 看
啥？
我说的是雇你来重画 wox 图标，什么矢量图啊之类的。。

**Comment by bao-qian** [comment]
> 如果想复制图标的话也许可以看看 Numix

大部分图标已经换成了 icons8.com 里面的

**Comment by bao-qian** [comment]
懂你什么意思了。。
画图标考虑一下吗？（

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.57/artifacts

**Comment by bao-qian** [comment]
没问题我就关咯

**Comment by bao-qian** [comment]
想画 WoX 本身图标的时候请联系我，我的支付宝时刻准备着 (
