### ISSUE TITLE
auto-complete for shell plugin

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#657]
以`notepad c:\windows\system32\drivers\etc\hosts`为例，输入`notepad c:\`后能够自动补全（在下方给出建议项，或者按tab进行自动补全等）。

**Comment by bao-qian** [comment]
这略难啊
补全命令容易点……

**Comment by jhdxr** [comment]
是很难。。。我也没想到如何实现。。。不然就是提PR而不是issue了。。。
所以先开了一个，看看有没有谁有什么比较好的思路。。。

**Comment by bao-qian** [comment]
因为不止有路径，还有别的
这等于重写一个真正的 shell 了，摔
