### ISSUE TITLE
Any way to exclude folders from Everything plugin searches?

### ISSUE THREAD

**Issue by illTimber** [Wox-launcher/Wox#658]
Not a bug but a usage questions: Is there anyway to customise the list of folders that Everything plug searches? When I use Everything I have quite a few excluded folders so that I don't get search results from folders such as Windows and Program Files. Is there anyway to do this with the Everything plugin?

Wox version: 1.3.30
Windows 10 x64 Build 10586

**Comment by bao-qian** [comment]
You don't need to do anything on wox side. Just set in everything setting
