### ISSUE TITLE
FileSystemProgramSource Loading Issue

### ISSUE THREAD

**Issue by aaroncampf** [Wox-launcher/Wox#66]
I was edited the code to allow user to specify folders to search using FileSystemProgramSource and I added a folder that had far to many files and folders in it.

I think it might be a good idea to add a timer to stop GetAppFromDirectory if it is taking to long.

**Comment by orzFly** [comment]
By design, ProgramSource is not for file searching. At this moment we do not plan to add file searching features. If you want to search files using Wox, please refer to [Everything plugin](https://github.com/qianlifeng/Wox.Plugin.Everything).

**Comment by aaroncampf** [comment]
I created a way to add additional directories to the list that gets automatically searched (like the start menu).

I think it this is how I should do it because there is no way to add settings to my plugins like you can with ProgramSource and it does the exact same thing (except limits the items to the selected folder).

I want to be able to go 
Scott -> [Open Folder]
Not
C:\Storage_Work\Scott -> [Open Folder]

Why have me select files and folders I'll never use, but not let me select the one's I actually want.

If I was to make this a plugin then...would I have to make an external way to select the folders to include and how would I set there point values?

**Comment by orzFly** [comment]
@aaroncampf Plugins will have their way to add settings in the setting dialog. In the latest nightly builds, I have already added a feature tab. Your plugin should implement ISettingProvider and return a WPF control.

**Comment by orzFly** [comment]
By the way, FileSystemProgramSource was designed for shortcuts in folders. I think you just need create some shortcuts in a folder and then add that folder into Wox.

For example, create a folder named `C:\WoxShortcuts`. Then create a shortcut `C:\WoxShortcuts\Scott.lnk` pointing `C:\Storage_Work\Scott`.

**Comment by aaroncampf** [comment]
I have seen the feature tab, but I do not see anyway to use it.
I am quite bad with WPF, so forgive me if there is a way and I just don't understand.

FileSystemProgramSource only grabs files AND searches all child folders, which has unacceptable performance implications and adds undesired items to the menu.

Here is the best solution
Modify [DirectoryIndicator] so  DirectoryIndicator.driverNames can contain additional directories AND have those directories appear in the list of items.

Currently the Item list is VERY polluted with so many items that I would have to know exactly what I am looking for to select it. Turning off the bookmarks eliminated most of this.

It would be awesome to go
Games -> Don't Starve -> open
Games -> RPG -> (browse the games I have in that folder)

Am I wrong?
I don't want to do things that mess up your work.

**Comment by aaroncampf** [comment]
I have added a replacement plugin and will consider deleting the FileSystemProgramSource, unless anyone wants me to keep it
