### ISSUE TITLE
插件热键BUG，加space会全选

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#660]
例如设置了 shift+v 快捷键对应插件cb，后面不加space，那呼出没有问题
如果设置了 shift+t 快捷键对应 yd（有道），后面加个space方便输入，呼出以后，会全选关键字。

另外，设置界面出发关键字一栏是空的
![image](https://cloud.githubusercontent.com/assets/2839512/15445825/47b64df4-1f3b-11e6-9416-9e0f56451112.png)

**Comment by bao-qian** [comment]
整个设置一团糟，正在进行 mvvm 重构。。。 #486

**Comment by ousui** [comment]
赞啊。

**Comment by bao-qian** [comment]
试一下 1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts

**Comment by ousui** [comment]
从上个版本起好像就没有这个问题了。
