### ISSUE TITLE
做了个生成二维码的插件，欢迎试用，另外请求开放剪贴板的接口

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#661]
麻烦老板写个获取剪贴板内容和写入到剪贴板的接口啊，如果用python来写的话好麻烦的，不如接口提供来的方便实惠。

[传送](https://github.com/ousui/Wox.Plugin.Py.Qrcode)

注意需要预先安装python，并且自己安装依赖。

利用二维码，你可以方便的复制链接啊什么的文本到你的电脑上拉。

![image](https://cloud.githubusercontent.com/assets/2839512/15445833/a52cf8de-1f3b-11e6-8c8a-6162feedde0c.png)

**Comment by bao-qian** [comment]
http://stackoverflow.com/questions/579687/how-do-i-copy-a-string-to-the-clipboard-on-windows-using-python

``` python
import os
def addToClipBoard(text):
    command = 'echo ' + text.strip() + '| clip'
    os.system(command)

#example
addToClipBoard('penny lane')
```

**Comment by ousui** [comment]
谢谢啦，python还在继续学习中。

但是我觉得这些基本操作还是放到接口里比较好

**Comment by bao-qian** [comment]
这不是基本操作。。
这是 os 相关的操作。。。

**Comment by ousui** [comment]
哦，我不是说代码这块，是指wox使用层面，使用剪贴板内容应该是最基本的需求啊，如果有接口就很方便啊。

**Comment by jhdxr** [comment]
使用剪贴板是最基本的需求没错，但很明显应该编程语言自己提供啊。。。不然按照你的理论，其他基础操作例如IO等wox难道也要封装一遍么？

btw，我个人建议能用c#实现的还是用c#实现。毕竟如果这个要给普通用户（无编程经验）来用，要安装一个Python环境已经比较困难了，更何况还要『自己安装依赖』
↑ 这也是wox和alfread最大的不同之一，osX自带了N种环境，开发者可以根据他们自己的喜好来选择开发语言，并且对普通用户基本没有影响。。。而wox虽然提供了这种跨语言的开发机制，然而大部分用户的电脑上不会有那么多环境。。。。

**Comment by bao-qian** [comment]
依赖以后可以自动安装 有 requirement.txt 的话。。
当然，以后。。。。
