### ISSUE TITLE
put theme files in %APPDATA%

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#662]
我自定的主题，放在app-1.3.3/theme文件夹下，更新以后程序打不开报错，因为被删了，但是设置文件还在。。。
另外，官网主题builder文件 `color` 字段应该为  `SolidColorBrush`，虽然我知道不是你弄滴 :100: 

可以把制作主题这个直接写在软件本地 :+1:

**Comment by bao-qian** [comment]
1. 是这样的
2. 网站 @qianlifeng 
3. 以后。。。
