### ISSUE TITLE
有道词典在选择复制的时候报错

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#663]
![qq 20160521115434](https://cloud.githubusercontent.com/assets/9709390/15446216/ce06eb8e-1f4a-11e6-9fb3-05c4ab40e852.png)

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15446242/321e335a-1f11-11e6-9456-8dcb8aa75700.png)
。。。。。

**Comment by jhdxr** [comment]
其实截图够了。。。『CLIPBRD_E_CANT_OPEN』，错误在youdao的`main.cs`的第95行，也就是`Clipboard.SetText(t.key);`

剪贴板需要先open才能使用，然而如果在你open的时候别的应用程序正在使用，那么就会报上面那个错误。可以参考`System.Windows.Forms.Clipboard`的做法，循环+延时解决（目前插件引入的是`System.Windows.Clipboard`）

**Comment by clayzx** [comment]
[2016-05-21.txt](https://github.com/Wox-launcher/Wox/files/275706/2016-05-21.txt)

日志已提交！

**Comment by bao-qian** [comment]
@jhdxr 你考不考虑去开个 pr。。。

**Comment by jhdxr** [comment]
@happlebao  好。。。我明天来开个pr。。。

**Comment by bao-qian** [comment]
http://www.getwox.com/plugin/78
1.1.1
出来了。重装即可。
