### ISSUE TITLE
python 编写的插件无法使用

### ISSUE THREAD

**Issue by Tr0jsperi** [Wox-launcher/Wox#664]
Wox版本：1.3.65
Windows版本：win 10
Python版本：3.4.4
问题描述：
通过wpm安装的python插件无法使用，测试了豆瓣电影，hacker news，shadowsocks插件。
Wox能识别触发关键字，下拉菜单会显示符合的插件，但继续输入文字后没有任何输出。
Python路径已添加到系统环境变量和Wox设置中。

**Comment by bao-qian** [comment]
目测这些插件不兼容 py2。
1. 要么你去找作者
2. 要么你自己改一改去开 pr
3. 用 py2

py2 和 py3 的兼容性问题就是一把泪。。。

**Comment by Tr0jsperi** [comment]
试了py2依然没有反应，有没有办法测试是插件无法运行还是wox调用python失败

**Comment by bao-qian** [comment]
自带个 hello world python 插件啊

**Comment by bao-qian** [comment]
或者你试试把每个插件都替换成新的 wox.py

**Comment by Tr0jsperi** [comment]
查了下发现原来的插件里都没有wox.py  拷进去后终于有反应了，谢谢

**Comment by dswybs** [comment]
我也遇到同样的问题，所有python插件均没有输出包括lz说的豆瓣电影，wox.py拷贝到插件目录下也没用，打开wox就消失了。
hello world 倒是能get到query

log如下：
2016-08-09 11:47:20.3416|ERROR|Wox.Core.Plugin.JsonRPCPlugin.Execute|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
2016-08-09 11:47:20.3416|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-09 11:47:20.3416|ERROR|Wox.Core.Plugin.PluginManager.QueryForPlugin|豆瓣电影 : QueryForPlugin failed
2016-08-09 11:47:20.3416|ERROR|Wox.Core.Plugin.PluginManager.QueryForPlugin|
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 189
2016-08-09 11:47:20.3416|ERROR|Wox.Core.Plugin.PluginManager.QueryForPlugin|Traceback (most recent call last):
  File "C:\Users\pingx\AppData\Roaming\Wox\Plugins\豆瓣电影-34a8ae4a-5d39-4aa3-83c2-bd7fd4b8b834\main.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by bao-qian** [comment]
@dswybs wox 版本？豆瓣电影插件要手动装 requests。管理员模式启动命令行，然后  `pip install requests`

**Comment by dswybs** [comment]
Wox版本：1.3.65
Windows版本：win 10
Python版本：3.5.2
根据log又装了beautifulsoup4后豆瓣电影能用了，但知乎日报和威锋网的插件依然没反应……
log如下，请指教！

2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
   在 Wox.Core.Plugin.PythonPlugin.ExecuteQuery(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 43
   在 Wox.Core.Plugin.JsonRPCPlugin.Query(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 35
   在 Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 181
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 0
2016-08-10 10:17:52.5340|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|发生一个或多个错误。
2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|feng : QueryForPlugin failed
2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 189
   在 Wox.ViewModel.MainViewModel.<>c__DisplayClass88_0.<QueryResults>b__2(PluginPair plugin) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 403
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|  File "C:\Users\pingx\AppData\Roaming\Wox\Plugins\feng-99357967-b31d-4b57-82d2-6181996da665\feng.py", line 26
    proxies = {
              ^
TabError: inconsistent use of tabs and spaces in indentation

2016-08-10 10:17:52.5340|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
   在 Wox.Core.Plugin.PythonPlugin.ExecuteQuery(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 43
   在 Wox.Core.Plugin.JsonRPCPlugin.Query(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 35
   在 Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 181
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号

**Comment by roose** [comment]
it's [feng plugin](https://github.com/shuson/wox-plugin-feng) error
`Python 3 disallows mixing the use of tabs and spaces for indentation`

**Comment by bao-qian** [comment]
@dswybs 威锋网的插件中 `feng.py` 混用了 tab 和 space。你格式化一下。

**Comment by dswybs** [comment]
已格式化过，依然无输出……
log：
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
   在 Wox.Core.Plugin.PythonPlugin.ExecuteQuery(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 43
   在 Wox.Core.Plugin.JsonRPCPlugin.Query(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 35
   在 Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 181
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 0
2016-08-11 17:13:14.9037|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|发生一个或多个错误。
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|feng : QueryForPlugin failed
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 189
   在 Wox.ViewModel.MainViewModel.<>c__DisplayClass88_0.<QueryResults>b__2(PluginPair plugin) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 403
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|  File "C:\Users\pingx\AppData\Roaming\Wox\Plugins\feng-99357967-b31d-4b57-82d2-6181996da665\feng.py", line 26
    proxies = {
          ^
IndentationError: expected an indented block

2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
   在 Wox.Core.Plugin.PythonPlugin.ExecuteQuery(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 43
   在 Wox.Core.Plugin.JsonRPCPlugin.Query(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 35
   在 Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 181
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 0
2016-08-11 17:13:14.9037|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|发生一个或多个错误。
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|feng : QueryForPlugin failed
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 189
   在 Wox.ViewModel.MainViewModel.<>c__DisplayClass88_0.<QueryResults>b__2(PluginPair plugin) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 403
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|  File "C:\Users\pingx\AppData\Roaming\Wox\Plugins\feng-99357967-b31d-4b57-82d2-6181996da665\feng.py", line 26
    proxies = {
          ^
IndentationError: expected an indented block

2016-08-11 17:13:14.9037|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 156
   在 Wox.Core.Plugin.PythonPlugin.ExecuteQuery(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 43
   在 Wox.Core.Plugin.JsonRPCPlugin.Query(Query query) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 35
   在 Wox.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPlugin>b__0() 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 181
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 0

作者您平时使用这些插件么？正常么？

**Comment by roose** [comment]
@shuson please fix your plugin =)
@dswybs, please copy&paste this code to your feng.py

``` python
# -*- coding: utf-8 -*-

import os
import shutil
import unicodedata
import webbrowser

import requests
from wox import Wox,WoxAPI
from bs4 import BeautifulSoup

BasicUrl = "http://bbs.feng.com/"
URL = 'forum.php?mod=forumdisplay&filter=author&orderby=dateline&fid='

def full2half(uc):
    """Convert full-width characters to half-width characters.
    """
    return unicodedata.normalize('NFKC', uc)


class Main(Wox):

    def request(self,url):
    #get system proxy if exists
        if self.proxy and self.proxy.get("enabled") and self.proxy.get("server"):
            proxies = {
                "http":"http://{}:{}".format(self.proxy.get("server"),self.proxy.get("port")),
                "https":"http://{}:{}".format(self.proxy.get("server"),self.proxy.get("port"))
            }
            return requests.get(url,proxies = proxies)
        return requests.get(url)

    def query(self, param):
        url = BasicUrl + URL
        fname = param.strip()
        if fname == 'mac':
            url = url + "68"
        elif fname == 'ershou':
            url = url + "29"
        else:
            url = url + "601"


        r = self.request(url)
        r.encoding = 'utf-8'
        bs = BeautifulSoup(r.content, 'html.parser')
        posts = bs.select('tbody[id^=normalthread]')

        result = []
        for p in posts:
                ptitle = p.find('a', class_='s xst')
                ptime = p.find('span').string
                pname = p.find('cite').find('a').string
                item = {
                    'Title': u'{subject}'.format(subject=full2half(ptitle.string)),
                    'SubTitle': u'by: {name} | {time}'.format(name=pname, time=ptime),
                    'IcoPath': os.path.join('img', 'feng.png'),
                    'JsonRPCAction': {
                        'method': 'open_url',
                        'parameters': [BasicUrl+ptitle['href']]
                    }
                }
                result.append(item)

        return result

    def open_url(self, url):
        webbrowser.open(url)

if __name__ == '__main__':
    Main()
```

**Comment by dswybs** [comment]
@roose Thanks! I got the output after using your code, though the code can only display the newest posts and can't search them. But it's clear that the trouble is in the plugin code now.
So @shuson could you update your code, please? I think it's very helpful to many Wox users. Btw I also try to fix the code of ZhihuDaily replacing 8 spaces with tab like roose did but it still not work, could you fix it together? I'm not a coder I just can ask for help, thanks for all the job you did @happlebao @roose @shuson and other Authors

**Comment by shuson** [comment]
@roose @dswybs 
Sorry for making troubles. I will do the fixing ASAP

**Comment by shuson** [comment]
Hi, the indentation issues in feng and zhihudaily plugin have been fixed. 
BTW, I am still using wox version 1.1.1 with python 2.7. It is a swift and stable version in my point of view. Because it has no Everything dependency.

**Comment by dswybs** [comment]
@shuson I updated feng & zhihudaily all to the new version, but it seems that the codes still have mixed spaces and tab so all of them don't work, I used the code roose posted and it can output newest posts list but can't search them, zhihudaily doesn't work either...
Is it because I'm using python 3? Shall I change it to 2?

**Comment by shuson** [comment]
@dswybs I must say I don't have them tested in python 3 env. For space and tab issues, I used IDLE as editor, it should have no problem.
If u could do it on your side, please send pull request to the repo, after that, I will update it on wox website.

**Comment by bao-qian** [comment]
@shuson 

> Because it has no Everything dependency.
> Everything is not a dependency. you can use wox without Everything.

**Comment by bao-qian** [comment]
close due no further question from author or other user.
