### ISSUE TITLE
theme bug: color of selected item not displaying correctly

### ISSUE THREAD

**Issue by caoyue** [Wox-launcher/Wox#665]
- Wox version: 1.3.65
- Windows 10 (10586)
- theme bug:  
    color of selected item not displaying correctly
  ![selected](https://cloud.githubusercontent.com/assets/522324/15446696/222fabd2-1f5b-11e6-8c3b-5f0b58b30cf8.png)

**Comment by bao-qian** [comment]
我没看出哪里不对啊。。。你具体说一下？

**Comment by caoyue** [comment]
选中项的字体颜色没有变化

找到个之前的图
![1](https://cloud.githubusercontent.com/assets/522324/15452327/aaf378dc-201d-11e6-89d6-9eeb7aabdbec.png)

**Comment by bao-qian** [comment]
完工。感谢报告。
https://ci.appveyor.com/project/happlebao/wox/build/1.3.78/artifacts
