### ISSUE TITLE
Everything plugin problem

### ISSUE THREAD

**Issue by lingkz** [Wox-launcher/Wox#668]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   - If you checkout from master/dev branch, please specify **commit number**
2. Please describe the steps to **reproduce** the bug
3. Please provide Windows version
4. Please provide Exception info if you have.
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
     1.3.67
2. 请提供如何**重现** bug 的步骤
   启动wox
3. 请提供 Windows 版本
   windows10企业版
4. 如果有 Exception/Crash Report 的话，请一并提供
   Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
5. upload log file: C:\Users\sunyd\AppData\Roaming\Wox\Logs\1.3.67\2016-05-22.log
6. copy below exception message
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 10.0.10240.0
   Date: 05/22/2016 10:04:45
   Exception:
   mscorlib
   System.IO.DirectoryNotFoundException
   未能找到路径“C:\Users\sunyd\AppData\Roaming\Wox\Plugins\Everything-73da97bb-3a3e-4556-98c7-b637ad52ebb3\EverythingSDK\x64”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   在 System.IO.Directory.GetFiles(String path)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 39
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 137
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 90
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )
7. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
8. 如果有截图的话，请一并提供

**Comment by bao-qian** [comment]
大哥 你发帖子后自己看一眼行不行。。。

删掉 `C:\Users\sunyd\AppData\Roaming\Wox\Plugins\Everything-73da97bb-3a3e-4556-98c7-b637ad52ebb3`

**Comment by lingkz** [comment]
嗯，这个问题解决了，我重装了一下，再请教一下，everything用不了，软件装了64位，插件也装了，这个需要怎么配置一下，谢谢

**Comment by bao-qian** [comment]
> 插件也装了

你装了啥？everything 插件内置了啊。

![image](https://cloud.githubusercontent.com/assets/1169912/15452201/7470cfec-1fde-11e6-81c4-da81e65da5b2.png)

![image](https://cloud.githubusercontent.com/assets/1169912/15452232/64714486-1fdf-11e6-807a-cdc1f486d2e7.png)
1. 检查 everything 服务是否启动
2. 试一下直接用 everything 能不能搜
3. 传 log 上来

**Comment by bao-qian** [comment]
删除 %localappdata%\wox 和 %APPDATA%\wox
有问题再开
