### ISSUE TITLE
wox windows 1.3.67

### ISSUE THREAD

**Issue by dibadalu** [Wox-launcher/Wox#670]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 05/22/2016 16:25:43
Exception:
mscorlib
System.IO.DirectoryNotFoundException
未能找到路径“C:\Users\dibad\AppData\Roaming\Wox\Plugins\Everything-483925a3-8e03-4f43-a30b-1cd8baa85758\EverythingSDK\x64”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   在 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   在 System.IO.Directory.GetFiles(String path)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 39
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 137
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 90
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by jhdxr** [comment]
dup #668 
search before you open a new issue.

**Comment by bao-qian** [comment]
Everything 内置了，把那插件删掉。
