### ISSUE TITLE
Everything plugin problem

### ISSUE THREAD

**Issue by duccck** [Wox-launcher/Wox#671]
# Wox版本：1.3.67
# 系统：Windows 7

你好，我原来用的免安装版，因为手贱把原来那个everything服务删掉了，装上最新版后，everything服务就装不上了，折腾了很久还是搞不定。

**Comment by bao-qian** [comment]
重新去 everything 官网下 exe installer 啊…
x64 要用 x64 版本

**Comment by duccck** [comment]
好吧，我以为执行插件里的everything.dll就行呢。
谢谢。

**Comment by bao-qian** [comment]
那是 sdk…… 只有接口…

**Comment by duccck** [comment]
但还有个问题，everything服务有了，但wox还是提示everything没有运行。

**Comment by bao-qian** [comment]
重启 wox 了吗

**Comment by duccck** [comment]
嗯，重启了，everything插件也是开着的。

**Comment by bao-qian** [comment]
....
下 https://www.teamviewer.com/
然后告诉我 ID，密码。。。

**Comment by duccck** [comment]
你好，我把wox卸载了重装还是不行，我决定不浪费时间了。
麻烦了，谢谢。

**Comment by bao-qian** [comment]
删除 %localappdata%\wox 和 %APPDATA%\wox
