### ISSUE TITLE
輸入繁體中文，出現錯誤訊息

### ISSUE THREAD

**Issue by KreenChang** [Wox-launcher/Wox#673]
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 1.3.67
2. 请提供如何**重现** bug 的步骤：
   - ALT+ Space 出現任務框後，使用注音輸入法輸入**中文注音**就會跳出「Wox 出錯啦」錯誤視窗，但切換為英文時就完全沒問題。
3. 请提供 Windows 版本：
   - Microsoft Windows NT 6.1.7601 Service Pack 1
4. 如果有 Exception/Crash Report 的话，请一并提供：
   - PresentationFramework
     System.ArgumentException
     要求的距離超出關聯之文件的內容。
     於 System.Windows.Documents.TextPointer.InitializeOffset(TextPointer position, Int32 distance, LogicalDirection direction)
     於 System.Windows.Documents.TextPointer.System.Windows.Documents.ITextPointer.CreatePointer(Int32 offset, LogicalDirection gravity)
     於 System.Windows.Documents.ImmComposition.SetCompositionAdorner(Int32[] clauseInfo, Byte[] attributes)
     於 System.Windows.Documents.ImmComposition.UpdateCompositionString(Char[] resultChars, Char[] compositionChars, Int32 caretOffset, Int32 deltaStart, Int32[] clauseInfo, Byte[] attributes)
     於 System.Windows.Documents.ImmComposition.OnWmImeComposition(IntPtr hwnd, IntPtr lParam, Boolean& handled)
     於 System.Windows.Documents.ImmComposition.ImmCompositionFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     於 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供：
   - [log 檔點此](https://www.codepile.net/pile/ngQVJ62B)
6. 如果有截图的话，请一并提供:
   - http://i.imgur.com/emgy8yx.png

**Comment by bao-qian** [comment]
这是输入法的锅。用 win10 内置繁体输入法没有问题。

**Comment by KreenChang** [comment]
萬分感謝。

**Comment by bao-qian** [comment]
感谢请在右上角加星 :smile:

**Comment by KreenChang** [comment]
當然，這真是一個神器！
