### ISSUE TITLE
突然内存占用超高

### ISSUE THREAD

**Issue by taolive** [Wox-launcher/Wox#675]
1. 请提供 Wox 版本
   1.3.35
2. 请提供如何**重现** bug 的步骤
   多用wox进行了cmd、bd、baidu.com、及打开当前系统中的exe文件，之后大概20分钟，突然机器卡住了，鼠标迟钝反应，后面查看任务管理器，发现Wox的内存占用5G，还有缓慢增长中，很怪异，之前都没有发现此问题
3. 请提供 Windows 版本
   win10
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/15458660/0fa8650e-2095-11e6-91c0-eac542fa5ff5.png)

。。。。。。。。。。。。。。。

**Comment by bao-qian** [comment]
因没回复而关闭
