### ISSUE TITLE
搜索"zhifu"时崩溃

### ISSUE THREAD

**Issue by yunnysunny** [Wox-launcher/Wox#677]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 05/23/2016 14:50:06
Exception:

System.Runtime.InteropServices.COMException
无法找不到组件。 (异常来自 HRESULT:0x88982F50)

日志如下：
[2016-05-23.log.txt](https://github.com/Wox-launcher/Wox/files/276936/2016-05-23.log.txt)

错误截图：
![qq 20160523145229](https://cloud.githubusercontent.com/assets/734818/15462602/6385e2b2-20f6-11e6-8bf7-1e0146255a52.png)

**Comment by bao-qian** [comment]
你挡住了关键结果…
最后一个 #qiao.ba 是啥？传上来

**Comment by yunnysunny** [comment]
现在我搜zhifu两字的时候，已经不出现这个文件了，但是还是崩溃
![qq 20160523221718](https://cloud.githubusercontent.com/assets/734818/15473781/51a22234-2134-11e6-9594-98a8598417b7.png)
这个`#qiao.baidu.com`是个文件夹，位于`C:\Users\sunny\AppData\Local\Google\Chrome\User Data\Default\Pepper Data\Shockwave Flash\WritableRoot\#SharedObjects\FNHMC6VH\macromedia.com\support\flashplayer\sys\#qiao.baidu.com`

**Comment by bao-qian** [comment]
zip 一下，传上来
删掉 %appdata%\wox\cachr

**Comment by bao-qian** [comment]
删掉 %appdata%\wox\cache

**Comment by bao-qian** [comment]
zip 一下，传那个文件夹上来

**Comment by jhdxr** [comment]
@yunnysunny @happlebao 你试一试，是不是使用everything插件，搜索图片，并且这个**图片的路径里含有空格**，就会导致这个crash？我并没有装everything，也并没有打算装，因此不能自己验证复现的条件

**Comment by jhdxr** [comment]
再看了一下第二张截图，好像并不是。。。
毕竟我不是专业做c#的，只是看了下日志打个酱油。。。还是路过飘走吧。。。

**Comment by bao-qian** [comment]
@jhdxr 路径名有空格是经典 *nix 问题，我还没有看到在 .net 下有这种问题。。。。

**Comment by bao-qian** [comment]
#521 可能也有关

**Comment by yunnysunny** [comment]
[Wox.zip](https://github.com/Wox-launcher/Wox/files/278709/Wox.zip)

**Comment by bao-qian** [comment]
传这个文件夹 #qiao.baidu.com 上来…………

**Comment by yunnysunny** [comment]
[#qiao.baidu.com.zip](https://github.com/Wox-launcher/Wox/files/280876/qiao.baidu.com.zip)

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/521
probably reletaed

**Comment by jhdxr** [comment]
@happlebao  According to the second screenshot, I think # may not be the only cause.

**Comment by bao-qian** [comment]
试下新的
https://ci.appveyor.com/project/happlebao/wox/build/1.3.109/artifacts
