### ISSUE TITLE
Broken view after new monitor connection

### ISSUE THREAD

**Issue by enzy** [Wox-launcher/Wox#678]
The black line is opened Wox window.
![image](https://cloud.githubusercontent.com/assets/809888/15464188/717af95e-20d6-11e6-8f50-5afd45d3f5a5.png)

How to reproduce:
1. Launch Wox (1.3.67)
2. Use it for a while
3. Connect a second monitor (Extend option)
4. Open Wox window and see the problem
5. You need to restart Wox to fix the problem

OS: Window 10 x64 Home, latest stable version
Wox: 1.3.67 via installer

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue
