### ISSUE TITLE
Bugreport: Exception on running Kickass Torrent plugin

### ISSUE THREAD

**Issue by kdkunde** [Wox-launcher/Wox#679]
## English

Before you report any bugs try search existing issues
1. Wox version 1.367
2. Steps to **reproduce** the bug:
   Started a search for "hair musical" selected an (any) item in the resulting list and pressed enter.
   Voila! Exception!
3. Windows 10 Pro 64.bit
4. Please provide Exception info if you have.
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 10.0.10586.0
   Date: 05/23/2016 10:39:06
   Exception:
   System
   System.ComponentModel.Win32Exception
   Anwendung nicht gefunden
   bei System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei Wox.KickassTorrent.Main.<>c__DisplayClass8.<Query>b__3(ActionContext e) in f:\Windows 7 files\Documents\Visual Studio 2013\Projects\ClassLibrary3\ClassLibrary3\Class1.cs:Zeile 67.
   bei Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:Zeile 187.
   bei Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) in C:\projects\wox\Wox\MainWindow.xaml.cs:Zeile 224.
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   bei System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   bei System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

[2016-05-23.zip](https://github.com/Wox-launcher/Wox/files/277115/2016-05-23.zip)

Best regards
KDKunde

**Comment by bao-qian** [comment]
Ask plugin author
