### ISSUE TITLE
Replace files when upgrade plugins.

### ISSUE THREAD

**Issue by qianlifeng** [Wox-launcher/Wox#68]
We have provided upgrade function when user install a new version plugin. But it will remove the old plugin folder and then load the new plugin folder. This action may lose plugin configs. For example. [https://github.com/orzfly/wox.plugin.weather](https://github.com/orzfly/wox.plugin.weather) will produce a config in its plugin folder. currently, we will remove this config file, which may confuse users.

**Comment by bao-qian** [comment]
config should be stored in `%APPDATA%\Settings\plugin`
