### ISSUE TITLE
用有道词典时出错

### ISSUE THREAD

**Issue by jiange1236** [Wox-launcher/Wox#680]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 05/23/2016 20:43:32
Exception:
mscorlib
System.Runtime.InteropServices.COMException
OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 Wox.Plugin.Youdao.Main.<>c__DisplayClass2_1.<Query>b__1(ActionContext c) 位置 C:\Users\Ricky\Documents\GitHub\Wox\Plugins\Wox.Plugin.Youdao\Main.cs:行号 77
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 194
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2016-05-23.log.txt](https://github.com/Wox-launcher/Wox/files/277478/2016-05-23.log.txt)

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/issues/663
