### ISSUE TITLE
参考workflow，对目前plugin的一些建议和思考

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#682]
先上一张workflow的设置的截图（来源是一个workflow开发教程） <img width="1212" alt="4" src="https://cloud.githubusercontent.com/assets/1993373/15473457/c0fdbf46-2132-11e6-9622-7298db8eb0de.png">

首先是workflow最重要的一点，就是支持很多语言（解释器），然而这也是我觉得对wox最大的挑战，osX是自带多种语言的解释器，然而Windows下并没有自带这么多环境。目前wox的方式是需要用户自行安装环境，我觉得这个对于普通用户来说基本上是不可能完成的。。。而且就我个人来说其实在有选择的情况下我也不想装那么多环境。。。所以我觉得比较优雅的的方式是wox支持自带环境（不一定要直接捆绑在安装包中，可以在用到的时候去下载）参考sourcetree里调用git的方式，可以用户指定路径，也可以直接去下载一个内置的。否则（就像现在这样子）我觉得只能尽可能让插件作者来开发.net的（因为这是唯一一个win自带runtime的）

其次是各种用户体验的方面alfread强的多，如图中的各种placeholder，还有一点就是workflow的返回值中有autocomplete的支持，可以实现插件（内容的）自动补全，而不只是命令的开头。

最后很重要的一点，workflow之所以是flow，是因为各个命令可以不断的组合传递下去（把结果里的arg传给下个作为query），而目前plugin是拿到了初始的query后，后续所有操作都都是要插件自己完成的。而且这一点也是如果要改，最好尽早修改的，因为越往后，修改接口/协议影响越大。。。

**Comment by bao-qian** [comment]
> 多语言

多语言插件框架我已经已经有想法了，写好后增加新语言只要不到 50 行。
其实也没几种，就 python，nodejs，php。。。

> 运行时
1. 初步想法是一个 bootstrap installer 包含所有可选运行时，按需安装，自动下载 <- 这一步好难写，微软罪大恶极，文档超烂
2. 然后默认读 `%PATH%` 或用户可自行指定路径 (现在 python 也会读 `%PATH%` 和自选啊。。）

> placeholder 

我觉得这个没什么用。。。 你写插件里面不一样。。。

> autocomplete

这个会有的

> flow 

这是因为 alfred 用了 pipe，只能这么实现 callback。。。
还没类型。。
反正你写插件的时候就用一种语言。。
或者你举个具体例子？

现在进度是 UI MVVM 重构中 #486 ，然后才是 API #537

**Comment by jhdxr** [comment]
flow这个我觉得是让更多的语言实现了更多的可能性（因为你把一些可能语言本身不能活很难实现的用接口的形式暴露出来了），举几个场景。
1. trigger时不光通过唤起wox后输入关键词，还能直接通过快捷键唤起（例如现在的cmd插件支持win+R。再举一个场景，这个功能配合一些词典类的plugin，就能够取代一些字典软件了）
2. 最后的设置剪贴板可能有的语言无法实现（例如php，除非wox包装一层COM接口提供给PHP），或者类似现在有道插件再复制成功后的右下角提示，也是除c#以外，无法实现/无法比较简单的实现

**Comment by bao-qian** [comment]
1. this one will builtin, using hotkey tab in settings. (although it's buggy now...) #459 
2. why use php for this kind of plugin, what benefits you will get...?
   this kind of plugin needs use os specific language / runtime c# for win, objectc for osx etc..

ps: I can't type chinese in company, but I can read... so you don't need to type english..

**Comment by jhdxr** [comment]
选择用什么语言就行开发不应该是因为某种语言对于开发者来说比较方便么？以现在的c#版有道插件为例，任何一个语言都能实现它的查询功能，但是如果想要做好（例如现在的加上复制和提示），那么只有c#才能做到

btw，其实中文英文对我来说也无所谓，我也读写都ok的。。。

**Comment by bao-qian** [comment]
> 选择用什么语言就行开发不应该是因为某种语言对于开发者来说比较方便么？

道理是这个道理，但总是有局限的。你不能指望 php 写 android app 吧。。。

> 提示

会提供统一 toast 接口

> 复制

其实就算用 python 写复制也没问题啊。。。 https://github.com/Wox-launcher/Wox/issues/661#issuecomment-220753171

另：我习惯中国人就用中文，除非有什么条件限制。。

**Comment by bao-qian** [comment]
讨论完了？

**Comment by alannotnerd** [comment]
我有个想法...为什么不集成chocolatey呢..

**Comment by liango2** [comment]
插件做出来了吗，叫啥名字啊
