### ISSUE TITLE
提示没有启动Everything，以及一些建议！

### ISSUE THREAD

**Issue by clayzx** [Wox-launcher/Wox#684]
![20160524140108](https://cloud.githubusercontent.com/assets/9709390/15493755/b33a8b24-21b8-11e6-9345-13404931a229.png)

操作系统win10 64位
我尝试过1.3.64和1.3.67，结果一样！

一点建议：
新的setup.exe是自动安装文件到：C:\Users\XXX\AppData\Local\Wox
配置文件在：C:\Users\XXX\AppData\Roaming\Wox

能否可以选择安装路劲和配置路径？
因为在C盘下，如果我重装系统就得重新配置！
我有几台电脑，几个想共用配置，当然还有包含自定义的Theme和插件！

**Comment by bao-qian** [comment]
1. 我在 readme 里面说了… 去 everything 官网下 exe installer
2. 不能，你可以把 我的文档重定向到其他盘
3. 拷贝 %LOCALAPPPDATA%\theme 和 %APPDATA%\wox (除了 cache）
