### ISSUE TITLE
Wox shortcut does not work on windows 10 desktop

### ISSUE THREAD

**Issue by aeberts** [Wox-launcher/Wox#687]
Firstly, many thanks for Wox! For people switching from Mac it's great to have something like alfred :-) 

Before you report any bugs try search existing issues

Done - no other issue found.
1. Please specify Wox version

1.3.67
1. Please describe the steps to **reproduce** the bug
- Press Win+D to access the windows 10 desktop.
- Press the assigned Wox shortcut (Ctrl+space) 
  -> Wox does not start. (shortcut works when other windows are open, e.g. Chrome, Explorer, etc)
1. Please provide Windows version

Windows 10
1. Please provide Exception info if you have.

No exception
1. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

```
2016-05-24 07:17:03.1921|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|Python can't be found in PATH.
2016-05-24 07:17:03.2078|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|
2016-05-24 07:17:03.3484|INFO|Wox.Plugin.Program.Main.Init|Preload 248 programs from cache
2016-05-24 07:17:06.8557|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
```
1. Please provide screenshot if you have

**Comment by bao-qian** [comment]
thanks for such detailed report, I think the problem is because the hotkey library we used is not updated to windows 10. part of #459

**Comment by aeberts** [comment]
Please let me know if there's anything I can do to help!

**Comment by bao-qian** [comment]
leave it open as a reminder ....

**Comment by bao-qian** [comment]
> Please let me know if there's anything I can do to help!

oh, you can star this project...

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue

**Comment by aeberts** [comment]
Hi happleboa,
Thanks for the update. I have tried version 1.3.102 and the same problem persists. I have also noticed that the hotkey does not work when the windows 10 task manager is active (not sure if that helps). All other features that I use regularly appear to be working fine.

**Comment by bao-qian** [comment]
@aeberts did you select 
![image](https://cloud.githubusercontent.com/assets/1169912/15634982/f72c8fde-25c9-11e6-92c9-d7743550afe7.png)
?

**Comment by aeberts** [comment]
Yes, ignore hotkeys in fullscreen mode was selected (to avoid hitting the shortcut when I'm playing a games in fullscreen mode...)

Deselecting "Ignore hotkeys in fullscreen mode" option solves the bug (i.e.): 
- Deselect "ignore hotkeys in fullscreen mode" in settings.
- Press Win+D to access the windows 10 desktop.
- Press the assigned Wox shortcut (Ctrl+space) 
  result -> Wox is displayed fine.

For me personally, the ideal situation would be for Wox to work when the desktop displayed _and_ while "ignore hotkeys in fullscreen mode" is selected.

**Comment by bao-qian** [comment]
yeah, of course. this question is just help me to identify the root course.

**Comment by bao-qian** [comment]
> Wox version: 1.3.67
> Steps to reproduce:
> Click anywhere on the desktop OR minimize all open windows by pressing Win+D;
> try to open Wox by pressing Alt+Space;
> Wox doesn't open.
> Click anywhere except the desktop;
> try to open Wox by pressing Alt+Space;
> Wox opens.
> Reproducibility: 100%.
> Windows version: Windows 10 Pro 64-bit.
> Thank you for your work!

@SergTTL
#703 moved to here
