### ISSUE TITLE
bookmarks plugin breaks Version=1.3.67.0

### ISSUE THREAD

**Issue by rickmed** [Wox-launcher/Wox#689]
most plugins are not updated to version +1.3?

**Comment by bao-qian** [comment]
exception? logs?

**Comment by rickmed** [comment]
it's a question...

**Comment by Lkxxx** [comment]
当我安装完成BrowserBookmark插件重启wox时会报错

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 05/25/2016 23:12:27
Exception:
Wox.Plugin.BrowserBookmark
System.TypeLoadException
未能从程序集“Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null”中加载类型“Wox.Infrastructure.Unidecoder”。
   在 Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   在 Wox.Plugin.BrowserBookmark.ChromeBookmarks.ParseChromeBookmarks(String path, String source) 位置 d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:行号 51
   在 Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks(String path, String name) 位置 d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:行号 69
   在 Wox.Plugin.BrowserBookmark.ChromeBookmarks.LoadChromeBookmarks() 位置 d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:行号 76
   在 Wox.Plugin.BrowserBookmark.ChromeBookmarks.GetBookmarks() 位置 d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\ChromeBookmarks.cs:行号 16
   在 Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) 位置 d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:行号 26
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 90
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
@rickmed
Most failed? Depends

**Comment by bao-qian** [comment]
@Lkxxx 删掉，插件挂了

**Comment by bao-qian** [comment]
use #590
