### ISSUE TITLE
1.3.97造成键盘失灵

### ISSUE THREAD

**Issue by jingouwangzi** [Wox-launcher/Wox#690]
1.3.97版
启动之后，除了少量程序键盘能用（比如记事本），其他程序中键盘失效，屏幕键盘也不行，wox程序自身正常。

**Comment by monsteryip** [comment]
我是全部失灵，一换回旧版本就没问题

**Comment by bao-qian** [comment]
can't use chinese in company,
https://ci.appveyor.com/project/happlebao/wox/build/1.3.99
wait build 1.3.99 to finish and try it

**Comment by bao-qian** [comment]
and thanks for trying the new build!!

**Comment by jingouwangzi** [comment]
Error uploading artifact to Google Storage。build出错，不着急，你下班再搞。

**Comment by jingouwangzi** [comment]
问题解决
