### ISSUE TITLE
建议为查询结果增加分页

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#691]
例如，查询到了某些结果，结果较多，
或者用爬虫爬网页，包含分页，如果翻第二页，只能通过代码实现，建议在 query 函数上增加分页，查询结果最下方可以增加分页按钮。

我现在是 query keywords {page}
这样来做的。

**Comment by happlebao** [comment]
can't use chinese in company
no, a **button** is a bad idea for a keyboad oriented application..
results can be updated in c# plugin using `PushResults` for now,
I'm trying to figure out a way to do data binding...

**Comment by jhdxr** [comment]
我觉得你现在的解决方案非常好啊。。。添加分页不伦不类的，我还是没能理解你的场景，wox是个launcher，如果用户进行了一个查询，然而结果居然要靠分页才能找到（而不是直接在前面出现），我觉得一定是什么东西出了问题

**Comment by bao-qian** [comment]
> 查询到了某些结果，结果较多，

that's fine, just return all results, wox won't blow up unless you have 100k resutls..

> 包含分页
1. use your current method is fine
2. are you trying to do lazy evaluation?

**Comment by ousui** [comment]
@jhdxr 嗯，用顺手了也没什么关系。
主要是针对网络请求，如果一次请求量太大，网络会很卡，请求少的话就需要分页了。

**Comment by bao-qian** [comment]
c# 有个 `pushresult` api

**Comment by ousui** [comment]
@happlebao 本人用 python。。
另外，请求结果这个可否添加异步支持，即例如，我要在一次查询返回多个网站内容，想要查到一个在页面中添加一个请求结果，直到全部添加完毕。

**Comment by bao-qian** [comment]
第三方语言的异步更新满难写的 我想想…
