### ISSUE TITLE
如何取消系统热键win+r

### ISSUE THREAD

**Issue by libra1010** [Wox-launcher/Wox#693]
系统热键win+r调用运行，结果现在被替换成了wox,没有办法使用运行
原以为wox可以代替运行
使用mstsc和calc试用了下，发现会先打开一个CMD窗口，然后在运行 远程桌面和计算器
能不能替换win+r快捷键？
或者重新加入一个指令
代替 > 这样就不用弹出CMD窗口
命令 calc
谢谢

**Comment by bao-qian** [comment]
can't use chiense in company
1. use latest release https://github.com/Wox-launcher/Wox/releases/download/v1.3.67/Setup.exe
2. choose RunCommand in shell plugin
