### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#694]
Need anything else, let me know.

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.14342.0
Date: 05/25/2016 09:43:17
Exception:
Wox
System.NullReferenceException
Object reference not set to an instance of an object.
   at Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-05-25.log.txt](https://github.com/Wox-launcher/Wox/files/282218/2016-05-25.log.txt)

**Comment by jhdxr** [comment]
Did you upgrade from an old version or just a clean install?
Does uninstall wox and re-install fix this problem?

**Comment by bao-qian** [comment]
remove Clipboard plugin directory from %APPDATA%\Wox\plugin

**Comment by ghost** [comment]
This is an upgrade from an old version. Uninstalling and re-installing doesn't fix it, but I imagine deleting everything leftover from the uninstall in %APPDATA%\Wox should clear things up.

There is no clipboard directory in %APPDATA%\Wox\plugin and I can't find any other directory that references the clipboard. I don't think I had that plugin installed, but I can't verify that. Also, I deleted all the directories in %APPDATA%\Wox\plugin, but I'm still having this issue. 

Moving the %APPDATA%\Wox\ directory and allowing wox to create a new one on installation does clear things up. I removed the new directory and moved my original %APPDATA%\Wox\ directory back,  to try to reproduce it, but the issue is still gone. I'm not sure what happened or what caused it. 

Sorry I couldn't be more help!

**Comment by bao-qian** [comment]
did you overwrite the new %APPDATA%\Wox\ with your existing %APPDATA%\Wox\ ? or just Completely delete the newly created one ?

**Comment by ghost** [comment]
I overwrote the new one.

**Comment by bao-qian** [comment]
ah, the actual reason would be some setting field is changed in new release.
