### ISSUE TITLE
 RunCommand in shell plugin 无法保存配置

### ISSUE THREAD

**Issue by libra1010** [Wox-launcher/Wox#695]
设置 RunCommand in shell plugin 设置为RunCommand
当前是生效，电脑重启后恢复为CMD
多次尝试均是如此

**Comment by jhdxr** [comment]
原来这是个bug么。。。我也遇到了。。。我还以为是因为我自己开发环境的配置和生产环境的配置没区分开来导致的问题。。。

**Comment by bao-qian** [comment]
try 1.3.100 
https://ci.appveyor.com/project/happlebao/wox/build/1.3.100/artifacts
