### ISSUE TITLE
rename setup.exe

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#696]
https://github.com/Wox-launcher/Wox/issues/360#issuecomment-221872291

> @happlebao Awesome! Could I make one tiny suggestion? Please don't name it setup.exe - so easy to lose in a download folder - have to keep renaming it. Sounds stupid, but so easy to fix :blush:

@mika76

**Comment by mika76** [comment]
Thanks - I wasn't sure whether to make an issue or not. I suggest you add the name and version as well to the download file - I know plenty of people who like to keep older versions of software in case they have to go back.

**Comment by mika76** [comment]
Thanks - I wasn't sure whether to make an issue or not. I suggest you add the name and version as well to the download file - I know plenty of people who like to keep older versions of software in case they have to go back.
