### ISSUE TITLE
Font weights resets when clicking "Theme" tab

### ISSUE THREAD

**Issue by krisu5** [Wox-launcher/Wox#697]
1. Please specify Wox version
   - 1.3.67
2. Please describe the steps to **reproduce** the bug
   - 1. Set font weights
   - 2. Close settings window
   - 3. Open settings window again
   - 4. Click "theme" tab, font weights reset themselfs.
3. Please provide Windows version
   - Windows 10

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue
