### ISSUE TITLE
System.TypeLoadException when running Setup.exe

### ISSUE THREAD

**Issue by DamirAinullin** [Wox-launcher/Wox#698]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 05/26/2016 23:17:35
Exception:
Wox.Plugin.BrowserBookmark
System.TypeLoadException
Не удалось загрузить тип "Wox.Infrastructure.Unidecoder" из сборки "Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null".
   в Wox.Plugin.BrowserBookmark.Bookmark.set_Name(String value)
   в Wox.Plugin.BrowserBookmark.FirefoxBookmarks.<GetBookmarks>b__1(SQLiteDataReader x) в d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:строка 39
   в Wox.Plugin.BrowserBookmark.Extensions.<Select>d__0`1.MoveNext() в d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:строка 85
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Wox.Plugin.BrowserBookmark.FirefoxBookmarks.GetBookmarks() в d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\FirefoxBookmarks.cs:строка 39
   в Wox.Plugin.BrowserBookmark.Main.Init(PluginInitContext context) в d:\Personal\Github\Wox.Plugin.BrowserBookmark\source\Main.cs:строка 24
   в Wox.Infrastructure.Stopwatch.Normal(String name, Action action) в C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:строка 28
   в Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) в C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:строка 90
   в System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   в System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   в System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
this BrowserBookmark is buggy now #590 
delete it from `%APPDATA%\wox\plugins`
