### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by broven** [Wox-launcher/Wox#699]
win10
just open WOX,press ↑ or ↓ 
crashed
System.ArgumentOutOfRangeException
![qq 20160527074711](https://cloud.githubusercontent.com/assets/12854613/15593509/7f64a086-23df-11e6-9560-27c585b70f57.png)
![qq 20160527074922](https://cloud.githubusercontent.com/assets/12854613/15593517/8d486516-23df-11e6-980a-3aa57c02d7a9.png)

**Comment by bao-qian** [comment]
感谢汇报。
历史记录现在爆了， #632
