### ISSUE TITLE
建议恢复"是否替换Win+R"的开关

### ISSUE THREAD

**Issue by zlphoenix** [Wox-launcher/Wox#700]
那个替换Win+R 的开关还是恢复回来吧，有些功能Wox不太方便，比如打开带有环境变量的目录，或者samb共享目录，启动Metro应用等。如果能够达到完全替代Win+R的时候咱们再取消这个开关不迟

**Comment by zlphoenix** [comment]
#建议
那个替换Win+R 的开关还是恢复回来吧，有些功能Wox不太方便，比如打开带有环境变量的目录，或者samb共享目录，启动Metro应用等
![image](https://cloud.githubusercontent.com/assets/1305437/15596736/5ebb68fc-23fc-11e6-9a58-0f96fb9cee2a.png)

我需要用Win+S 或者Win+X+R解决，不太习惯

**Comment by jhdxr** [comment]
那个开关一直都在啊。。。你用的什么版本。。。

**Comment by bao-qian** [comment]
…… 你哪个版本啊大哥？

**Comment by bao-qian** [comment]
因没回复而关闭。有问题再开。

**Comment by laobubu** [comment]
版本 1.3.183 从百度云下载的
没有这个选项，而且“启动时不显示主窗口”功能无效

![](https://ooo.0o0.ooo/2016/10/04/57f3679814fbf.png)

**Comment by jhdxr** [comment]
@laobubu 插件——shell，设置项在右边
