### ISSUE TITLE
输入 "增强" 然后 退格

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#701]
第一次可能没事，但是没结果，然后再来一次，必现

其他词后续本帖跟进。

![image](https://cloud.githubusercontent.com/assets/2839512/15605835/01e48d0e-243b-11e6-9e67-d22a897bd8c3.png)
[log.txt](https://github.com/Wox-launcher/Wox/files/286292/log.txt)

**Comment by bao-qian** [comment]
upload these two files

**Comment by bao-qian** [comment]
try to delete `%APPDATA%\Wox\imageCache`

**Comment by ousui** [comment]
会去读文件内容吗？刚看了下，
F:\新建文件夹\USA\qian\萁姐俱乐部2014-1月\布楠-VO会增加问题来观察你面部表情的变化.png
这个图片文件是我从硬盘恢复的，属于损坏的文件。

pdf 文件为正常文件
F:/Download/shuai.w/人力资源部（2）/2012offer/201204offer/录用函赵增宾.pdf

**Comment by ousui** [comment]
删除缓存了 remoting 下 wox\cache\image... 缓存文件还是不行

**Comment by bao-qian** [comment]
it will try to read the file icon, that's why I asked you to **upload** the files...

**Comment by ousui** [comment]
确实是这个问题，删除后没事了。
这个异常捕获下吧。

**Comment by bao-qian** [comment]
啊？？你不说删除了 imagecache 还是有问题吗？？

**Comment by bao-qian** [comment]
你之前是不是装了 switcheroo？

**Comment by ousui** [comment]
不是，是把有问题的图片文件都删了，就没问题了。
这个图片文件是损坏的无法打开。
没装过switcheroo。

---

刚随便新建了个文本文件，后缀名改为 .png，然后找这个文件，也报错。

**Comment by bao-qian** [comment]
好的

**Comment by jhdxr** [comment]
#677 应该也是相同的原因，我看了ta的日志也是在读取图片的时候出错。错误描述和这个issue描述也一样的

**Comment by bao-qian** [comment]
@jhdxr 但他那个是文件夹。文件夹的图标读取是一个专门的 win32 api。。。 和读取一般图标的不是一个。。。

**Comment by bao-qian** [comment]
试下新的
https://ci.appveyor.com/project/happlebao/wox/build/1.3.109/artifacts
我试了新建空白文件然后重命名成 .png 是没有问题了

**Comment by ousui** [comment]
不会报错了，但是这时候好像占用着文件，文件不能删除。
![image](https://cloud.githubusercontent.com/assets/2839512/15637136/8cb6cc7a-2644-11e6-8925-624488ac6e79.png)

**Comment by bao-qian** [comment]
关掉 wox 再删应该就能用了吧 那关 issue 了
