### ISSUE TITLE
插件禁用无效

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#702]
直接贴复现步骤吧：
1. cmd插件开启替换win+r，然后禁用此插件
2. win+r，依然会唤起wox

猜测是因为wox的禁用仅仅是在查询时不去触发插件的关键词？。。。

**Comment by bao-qian** [comment]
没错，猜测完全正确（逃

**Comment by bao-qian** [comment]
不过这个选项马上就会移除了
![image](https://cloud.githubusercontent.com/assets/1169912/15617547/55705f88-2441-11e6-943e-a9763d0e2a17.png)
以后统一在 setting 的 hotkey tab 设置

**Comment by jhdxr** [comment]
这个有点坑，我觉得是不是应该考虑加入一些方法，让插件在被禁用/启用时有机会做一些处理。例如我记得有个插件是闹钟，那么我的预期也是禁用后闹钟不再提醒的。如果插件无法知道自己的状态，就没有机会这么做了

**Comment by bao-qian** [comment]
这个可以考虑。启用有 constructor 就好了，禁用要单独加，不能用 destructor
记在 #351

**Comment by jhdxr** [comment]
现在不启用的插件也会被new一个出来的吧。。。那构造还是会被调到的吧。。。

**Comment by bao-qian** [comment]
@jhdxr 这到时候会一起改啦
