### ISSUE TITLE
Wox doesn't open if the focus is on the desktop.

### ISSUE THREAD

**Issue by SergTTL** [Wox-launcher/Wox#703]
Wox version: 1.3.67

Steps to reproduce:
- Click anywhere on the desktop OR minimize all open windows by pressing Win+D;
- try to open Wox by pressing Alt+Space;
- Wox doesn't open.
- Click anywhere except the desktop;
- try to open Wox by pressing Alt+Space;
- Wox opens.

Reproducibility: 100%.

Windows version: Windows 10 Pro 64-bit.

Thank you for your work!

**Comment by bao-qian** [comment]
thanks for report, working on it now.

**Comment by bao-qian** [comment]
hi, try  1.3.102
https://ci.appveyor.com/project/happlebao/wox/build/1.3.102/artifacts
reopen if you still have this issue

**Comment by bao-qian** [comment]
use #687
