### ISSUE TITLE
Everything问题

### ISSUE THREAD

**Issue by taolive** [Wox-launcher/Wox#704]
## 中文 / Chinese
1. 请提供 Wox 版本
   V1.3.67
2. 请提供如何**重现** bug 的步骤
   搜索文件的时候，提示：“Everything没有运行，我们将自动为启动内置Everythin，请稍后进行查询”，但是后面不管隔多久，还是如是提示
3. 请提供 Windows 版本
   Win10 14352

**Comment by bao-qian** [comment]
readme 有说。去 everything 官网下 .exe installer，并且开启 everything 系统服务。
