### ISSUE TITLE
After windows start menu is launched, wox can't get focus

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#706]
这个问题时不时发生，我并没有找到具体的规律，但可以给出一个在我这100%复现的方法

Wox: 1.3.100
OS: Win10 pro latest

在任何情况下（这一句主要是为了排除掉桌面那一种已知的bug），按Win唤起开始菜单，然后按Alt+Space，能够唤出Wox界面，然后直接输入文字，发现焦点在开始菜单的搜索而非Wox上

---

Wox: 1.3.100
OS: Win10 Pro x64 10586

This issue happes from time to time, and I didn't figure out the rule behind this problem. however, here is one way to reproduce this issue:
1. press Win to launch the start menu
2. press Alt+space and you can see the form of Wox 
3. input some keywords, and you will find the foucs is on the search bar(cotana) instead of wox

**Comment by bao-qian** [comment]
你再等两天，重构就完了。。
应该在周末之前完工

**Comment by jhdxr** [comment]
可是今天已经是周日了 :sweat: 
当然我猜你不在东八区。。。

**Comment by happlebao** [comment]
我在东八区我白天干嘛不能用中文 （

新鲜出炉：
https://ci.appveyor.com/project/happlebao/wox/build/1.3.101/artifacts

**Comment by jhdxr** [comment]
新鲜出炉的1.3.101问题略多。。。我先滚回100了。。。你加油修一修。。。

**Comment by bao-qian** [comment]
@jhdxr 这位大哥留步，具体说一说？

我以为这个 bug 一起修复了，其实没有，心塞。。。 只修复了 #703 #687 。。。

**Comment by jhdxr** [comment]
version: 1.3.102
1. 启动后快捷键无效（alt+space和win+r都是，并且此时没有其他程序抢占了这个热键，老版的wox进程也确定终结了）。开启设置界面，然后切换走快捷键（我这儿之试了alt+space)再切换回来（因为无法设置相同的快键键，会提示被占用）后快捷键功能恢复
2. #703 和这个#706 实测并未修复。（win10 pro x64  build:10586)
3. 热键设置界面，新增的热键无法删除
4. 热键设置界面，新增的热键如果不绑定任何按键（为None），则Wox下次启动的时候会crash（因为去尝试绑定了None）

我只是随手测了测，有点惨不忍睹。。。我还是继续默默滚回100了。。。

**Comment by jhdxr** [comment]
如果你那上面1、4两个问题也能复现的话。。。我建议把101和102两个版本从ci上删了或者把留言删了，问题影响有点大。。。

**Comment by bao-qian** [comment]
1 试下删除 settings.json?
2 703 我试没问题。。。 706 我是没招了。。
3 要选中。。。 
- [ ] 可改成默认删除最后一个

4 https://ci.appveyor.com/project/happlebao/wox/build/1.3.103

**Comment by happlebao** [comment]
有了一个新思路，求测试
https://ci.appveyor.com/project/happlebao/wox/build/1.3.111

**Comment by bao-qian** [comment]
this won't happen on the release version 1.3.67, right?

**Comment by jhdxr** [comment]
@happlebao  yes, in 1.3.67 when I launch wox, start menu will disappear and wox will get the focus

**Comment by bao-qian** [comment]
But 1.3.67 has some other different kinds of focus problems, right?

**Comment by jhdxr** [comment]
I don't know. I switched back to the latest version after I verified that issue. Could you list some case to test?

**Comment by bao-qian** [comment]
1. 2a3bf727be1c8bc185f1b436893b1c4385d982ac 中的 left top 设置
2. eeb8310381e4af0ab9b1e96c7bd62d82141969b9 换成了 `LowLevelKeyboardProc`

如果我们用了 `LowLevelKeyboardProc`, 那么即使用黑魔法 `AttachThreadInput` 这个问题也不能修复。(in win10)

https://bitbucket.org/josephcooney/learnwpf.com.samples/src/f2fb54ba7ecb8ef45d5004d7184c8026520b8b87/KeyboardHook/?at=default
上面这份代码可用来测试。

**Comment by bao-qian** [comment]
三个问题需要验证。。。需要版本号 v 满足 1.3.67 <= v < 1.3.96 
1. <kbd>alt+space</kbd> 来呼出 #706 是不存在了。除了 #703。还有别的不能取得输入焦点的情况吗?
2. 如果安装 switcheroo 插件。勾选覆盖 <kbd>alt+tab</kbd> 选项，用 <kbd>alt+tab</kbd> 的时候能取得输入焦点吗？ 除了 #706 和 #703 。
3. 在 shell 插件中，勾选 <kbd>win+r</kbd>，用 <kbd>win+r</kbd> 的时候能取得输入焦点吗？除了 #706 和 #703 。

**Comment by bao-qian** [comment]
新的快捷键代码有根本性问题， revert 了。。

**Comment by jhdxr** [comment]
根本性问题是什么。。。。说出来分享下经验呗

**Comment by jhdxr** [comment]
另外我记得你当时那个提交是fix了某个issue来着的（无法设置带win的快捷键？），你revert了的话是不是应该把对应的issue reopen回来。。。

**Comment by bao-qian** [comment]
那些都是因为这个新的快捷键方法导致的。

LowLevelKeyboardProc 在 win10 下不管你怎么用黑魔法，p/invoke 在某些情况下（任务管理器/开始菜单等等）都是不能获取焦点的。安全性大大增强（

**Comment by jhdxr** [comment]
这个某些情况你有分析出是什么原因么。。。好像是程序可以自己屏蔽的。。。我上次用火绒剑的时候也同样是无法唤出wox，和任务管理器一样。感觉是它们自己做了处理

------------------ 原始邮件 ------------------
发件人: "happlebao"; 
发送时间: 2016年6月17日(星期五) 凌晨0:17
收件人: "Wox-launcher/Wox"; 
抄送: "江湖大虾仁"; "Mention"; 
主题: Re: [Wox-launcher/Wox] After windows start menu is launched, woxcan't get focus (#706)

那些都是因为这个新的快捷键方法导致的。

LowLevelKeyboardProc 在 win10 下不管你怎么用黑魔法，p/invoke 在某些情况下（任务管理器/开始菜单等等）都是不能获取焦点的。安全性大大增强（

&mdash;

**Comment by bao-qian** [comment]
@jhdxr 你用火绒剑的时候用的是 release 里面的（1.3.67） 还是这个 issue 里面有问题的那个版本 （1.3.100）？

**Comment by jhdxr** [comment]
@happlebao 有问题的版本。我目前更新到了158（revert后的版本），不管是任务管理器还是火绒剑都可以正常唤起wox

**Comment by bao-qian** [comment]
@jhdxr 就是我在这 https://github.com/Wox-launcher/Wox/issues/706#issuecomment-226536019
说的问题了
