### ISSUE TITLE
hotkey problem

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#707]
Version: 1.3.103 (clean install)
1. press win+R sometimes will fail to launch wox. besides, even if the form of wox displayed, it's possible that the start menu will pop up like I press win only. And When I press alt+space to lanuch wox, sometimes menu of current running progrom will pop up (like press alt only) 
2. if "ignore hotkeys in fullscreen mode" selected, I still have the same problem as #703 (and I wonder if the setting is the cause of that issue instead of the old way of implements)

btw, delete setting.json only (like you suggest in [#706 comments](https://github.com/Wox-launcher/Wox/issues/706#issuecomment-222340980)) will cause wox crash, and after I delete eveything under `AppData\Roaming\Wox`, some problems I mentioned in the comments of #706 went away. but I still suggest we should take the old versions into consideration, such as writing some codes to migrate setting file from old format to the new one.

**Comment by jhdxr** [comment]
well, if I unselected "ignore hotkeys in fullscreen mode", 1.3.100 works fine on the desktop #703

**Comment by bao-qian** [comment]
1. 我知道 win 键是有问题的，而且也知道怎么修。。。 alt space 我只在 task manager 有这个问题，你看一下你是哪个软件？
2. logs 有报错吗？
3. 设置：设置格式我应该没有改。。。你传份 crash 时候的 log？

**Comment by jhdxr** [comment]
我看到了你在#459 里提到了task manager的问题，但是这个和我遇到的不一样。task manager是wox无法响应快捷键，我遇到的那个是在firefox中，能够唤起wox，但同时firefox会响应alt（唤起菜单），这个问题和win 键的问题比较相似

**Comment by bao-qian** [comment]
只在 firefox？

**Comment by jhdxr** [comment]
不知道。。。我验证了下103的问题以后就马上换回了1.3.100。。。

**Comment by bao-qian** [comment]
>  if I unselected "ignore hotkeys in fullscreen mode", 1.3.100 works fine on the desktop

这个问题按你这么讲的话应该是 `WindowIntelopHelper.IsWindowFullscreen()` 这个函数的问题，不是因为改了 hotkey 的代码。

**Comment by jhdxr** [comment]
对，是Wox在全屏上的判断有问题，我还发现了其他一些有问题的case，正在修。
所以我才说103的改动并没有修好什么热键问题，反而还引入了一些。。。

**Comment by bao-qian** [comment]
1. <del> 这个应该在 1.3.105 中修复了。win 我试了是没问题了。我无法重现 alt+space 在 firefox 中的情况，你试一下。</del> 那方法有别的问题。。。 https://github.com/Wox-launcher/Wox.Plugin.Switcheroo/issues/6#issuecomment-222382709
   接下来的讨论用 #459 。
2. 用 #687 

开多了有点乱。。。
