### ISSUE TITLE
一直显示everything没有运行，我们将为您启动内置的everything

### ISSUE THREAD

**Issue by S7venYoung** [Wox-launcher/Wox#708]
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   1.3.67
   2.搜索文件时，一直显示everything没有运行，我们将为您启动内置的everything

**Comment by bao-qian** [comment]
readme 有说。去 everything 官网下 .exe installer，并且开启 everything 系统服务。
