### ISSUE TITLE
1.3.109 大问题啊。。。 alt 键粘连

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#710]
是这样：
alt+space 开启以后，alt 粘连，就好像被按下去一样，必须再次按下alt键才可以正常使用
总之就是如果只按了一次，默认alt键一直按下。。。。

我还以为我键盘坏了呢，差点砸了。。

更换了其他快捷键， 例如 win+ ctrl+ 都有问题。。。

**Comment by ousui** [comment]
顺带提一下改进建议：
第一次热键激活到前台以后，如果这个时候鼠标切到别的焦点，干了别的事，这个时候再次按下热键希望是将wox切回热点，而不是隐藏。

另外，如果在焦点上时，如果按下 ESC ，希望将内容情况，而不是隐藏 wox

**Comment by bao-qian** [comment]
https://ci.appveyor.com/project/happlebao/wox/build/1.3.114

**Comment by ousui** [comment]
更到了 1.3.115 问题解决

**Comment by bao-qian** [comment]
焦点改进单独开啊。。

**Comment by bao-qian** [comment]
现在 win 键好像也有粘连？

**Comment by bao-qian** [comment]
如果是的话，v1.3.67 有 win 键粘连吗？

**Comment by jhdxr** [comment]
我本来倒没发现有这问题（无论是alt还是win），但刚才进设置尝试设置一些快捷键，发现在那好像win的粘连是必现的。（build 114)

而且好像还有一个问题。。。怎么我把下面自定义快捷键全删了以后alt+space唤不起wox了。。。要手动去点击任务栏的图标后才恢复

**Comment by happlebao** [comment]
如果是的话，v1.3.67 有 win 键粘连吗？

**Comment by ousui** [comment]
115 win 也有

**Comment by bao-qian** [comment]
这个 commit 的方法有大问题。。。 revert 了
