### ISSUE TITLE
设置中搜索框半透明/阴影 / blurry in settings

### ISSUE THREAD

**Issue by jingouwangzi** [Wox-launcher/Wox#711]
目前用的1.3.115，感觉最近的版本都是这样的。
安装新版本之后第一次打开时，设置里面的“失去焦点时自动隐藏窗口”失效，也就是窗口一直都在，非要重启一下或者打开设置什么的才起作用。
还有打开设置会出现半透明的界面在设置界面上，效果如下：

![qq 20160530185821](https://cloud.githubusercontent.com/assets/5857162/15648877/dc964d00-269f-11e6-8436-e44aa8049e1d.jpg)

**Comment by jhdxr** [comment]
顺便说一句，半透明那个窗口不确定是否是主程序的界面，因为我也是如图的半透明效果，然而我用的主题不是这样子的。。。

**Comment by bao-qian** [comment]
@jingouwangzi @jhdxr 
应该修好了
https://ci.appveyor.com/project/happlebao/wox/build/1.3.346/artifacts

**Comment by bao-qian** [comment]
@jp311 @ifdog  @oliutiano @Kaol-Fu @DaRingLee 
应该修好了
https://ci.appveyor.com/project/happlebao/wox/build/1.3.346/artifacts

**Comment by bao-qian** [comment]
有问题再开
reopen if bug still exist
