### ISSUE TITLE
memory leak in deps

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#713]
#675 报告了一个内存占用超高的问题，所以我刚才在调试的时候顺手调试了下内存，发现

```
hyjiacan.util.p4n.ChineseToPinyinResource [静态变量 hyjiacan.util.p4n.ChineseToPinyinResource+ChineseToPinyinResourceHolder.theInstance]    1
```

存在内存泄露的问题。其中的[unicodeToHanyuPinyinTable](https://github.com/hyjiacan/Pinyin4Net/blob/2fb33745c2dd7c2d871bcd89bd1b59e0c4471b52/Pinyin4Net/ChineseToPinyinResource.cs#L19)似乎不会进行回收。。。

**Comment by bao-qian** [comment]
擦 原来的那个就有内存泄露 换了一个以为修复了 又来……

**Comment by bao-qian** [comment]
等等 这不是
因为用的那个拼音库没带字典 不能解决多音字问题
所以拼音是在查询的时候还要转换一次（具体细节我忘了）
这个 table 是缓存

**Comment by jhdxr** [comment]
是缓存。然而没有回收的话这同样是问题。

**Comment by bao-qian** [comment]
缓存干嘛要回收…
每次查询都要用…

**Comment by bao-qian** [comment]
主要原因是没个好用的拼音库

**Comment by jhdxr** [comment]
不回收的话用的时间长了就会像 #675 里那样子内存占用奇大无比。既然是缓存，那就应该限制下自己的大小，或者定时回收下。c#能不能反射然后去操作下那个map的？

**Comment by bao-qian** [comment]
原始资源文件就 几 mb…… 那个问题不可能是这个原因…

**Comment by bao-qian** [comment]
就 几 mb，所以就常驻内存了…

**Comment by jhdxr** [comment]
我这已经20MB了。。。只不过的确离上G还差距巨大。。。

其实本来在debug之前我的猜测是不是有icon没回收，然而我没装everything，所以也没办法了。。。
