### ISSUE TITLE
[Runner] Method not found: 'Void Wox.Plugin.IPublicAPI.ReloadPlugins()'

### ISSUE THREAD

**Issue by Airgunster** [Wox-launcher/Wox#714]
1. Please specify Wox version: **1.3.67**
   - If you checkout from master/dev branch, please specify **commit number**: **N/A**
2. Please describe the steps to **reproduce** the bug:
   Here are the steps:
   A) wpm install Wox.Plugin.Runner (http://www.getwox.com/plugin/36)
   B) Go to 'Wox Settings > Plugin > Wox.Plugin.Runner', then add new command and click 'Save Changes', then you will get following message,
   
   > Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
   > 1. upload log file: C:\Users\ealmaty\AppData\Roaming\Wox\Logs\1.3.67\2016-05-30.log
   > 2. copy below exception message
   > Wox version: 1.3.67
   > OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
   > Date: 05/30/2016 16:45:14
   > Exception:
   > Wox.Plugin.Runner
   > System.MissingMethodException
   > Method not found: 'Void Wox.Plugin.IPublicAPI.ReloadPlugins()'.
   >    at Wox.Plugin.Runner.Settings.RunnerSettingsViewModel.<get_SaveChanges>b__5()
3. Please provide Windows version: **Windows 7 SP1**
4. Please provide Exception info if you have: **stated above**
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have: [2016-05-30.zip](https://github.com/Wox-launcher/Wox/files/289788/2016-05-30.zip)
6. Please provide screenshot if you have: [screenshot - 30_05_2016 17_14_52](https://cloud.githubusercontent.com/assets/7937957/15652976/3a0fd0ca-268a-11e6-8898-0899e6b08b8e.png)

Please have a look!
Thank you a lot in advance!

**Comment by NickCraver** [comment]
This was broken by commit https://github.com/Wox-launcher/Wox/commit/a7f1b24d60705b19f449de59b8ab88b5cab22ddf. I left a comment there - changes like this to public interfaces _cannot_ happen - for any environment. When we're talking abouit plugins it's an even stricter scenario. Changes like break everyone downstream. I hit the same error as in this issue. 

If Wox wants to maintain a plugin model of any stability, this cannot happen. The interfaces _must_ remain stable. If new functionality is needed, then new interfaces at major version changes are the proper route to do such, but that should likely be paired with plugin filtering for version support matches.

**Comment by bao-qian** [comment]
Thanks

**Comment by bao-qian** [comment]
@Airgunster @NickCraver @isaksky
Fixed now, update it with `wpm install Wox.Plugin.Runner`

**Comment by Airgunster** [comment]
Verified correction, fix is working fine, thanks.
