### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by IamIpanda** [Wox-launcher/Wox#72]
本来用英语写了一堆……一想装什么装。
首先，必须要有一个设置界面。
对我来说把书签放在最前面实在是太反人类了，一般启动Wox也就开个应用还要往下扫三行难以忍受。
快捷键个人的习惯依然是Alt+Space，Win+W在我的观念中一向来是关闭的意思？
启动速度慢，这个没办法的事情。Alfred也比Spotlight略慢一点。
虽然很流氓，但是开机请自启，至少提供个选项。
For：唯一的那个Release

本来想用来替代被COMODO疯狂骚扰的Launchy，现在看来为时尚早。

**Comment by orzFly** [comment]
Hi Peter,

Do you know there is a command called "setting"? If you don't know, please
try it at once.

You will find all settings in it, except the bookmark one. I will figure
out a way to add a common setting to control plugins soon.

**Comment by qianlifeng** [comment]
we already have a setting dialog (type setting in wox). Maybe it's hard to find the setting entrance, we will provide an setting icon beside query box later(could be hidden by the user) .
