### ISSUE TITLE
[Shadowsocks] SS插件不能用

### ISSUE THREAD

**Issue by a5066987** [Wox-launcher/Wox#723]
一开始输入ss后没有任何反应，后来我看到说要手动添加wox.py，于是把hellopython里的wox.py拷贝到ss插件的目录里。
随便试了一个域名，比如baidu.com： （ss baidu.com），就提示我出错了。
错误信息如下：

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.14342.0
Date: 05/31/2016 19:47:19
Exception:
Wox.Core
Wox.Infrastructure.Exception.WoxJsonRPCException
Traceback (most recent call last):
  File "C:\Users\bwcui\AppData\Roaming\Wox\Plugins\Shadowsocks for windows-a0d10067-3af6-438f-99cf-36fcac9da1b5\main.py", line 40, in <module>
    Shadowsocks()
  File "C:\Users\bwcui\AppData\Roaming\Wox\Plugins\Shadowsocks for windows-a0d10067-3af6-438f-99cf-36fcac9da1b5\wox.py", line 20, in **init**
    results = request_method(*request_parameters)
  File "C:\Users\bwcui\AppData\Roaming\Wox\Plugins\Shadowsocks for windows-a0d10067-3af6-438f-99cf-36fcac9da1b5\main.py", line 19, in add_new_domain
    with open(self.get_pac_path(),"r+") as pac:
  File "C:\Users\bwcui\AppData\Roaming\Wox\Plugins\Shadowsocks for windows-a0d10067-3af6-438f-99cf-36fcac9da1b5\main.py", line 10, in get_pac_path
    config = json.loads(content_file.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 38: illegal multibyte sequence

   在 Wox.Core.Plugin.JsonRPCPlugin.Execute(ProcessStartInfo startInfo) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 155
   在 Wox.Core.Plugin.PythonPlugin.ExecuteCallback(JsonRPCRequestModel rpcRequest) 位置 C:\projects\wox\Wox.Core\Plugin\PythonPlugin.cs:行号 42
   在 Wox.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass6_0.<Query>b__0(ActionContext c) 位置 C:\projects\wox\Wox.Core\Plugin\JsonRPCPlugin.cs:行号 59
   在 Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__24_8(Object index) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 187
   在 Wox.MainWindow.OnPreviewKeyDown(Object sender, KeyEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 224
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   在 System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   在 System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   在 System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
`UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 38: illegal multibyte sequence`

换 python3？

**Comment by bao-qian** [comment]
这应该就是 python 的 unicode 问题。装 python3 应该就好了。
不行再开。

**Comment by a5066987** [comment]
我用的是python35啊

**Comment by ghost** [comment]
问一个小白的问题，我是不是可以不用Shadowsock只用WOX插件实现翻墙，你的插件是什么实现原理？EVERYTHING这个插件只有我安装EVERYTHING这个软件才能用？？？

**Comment by bao-qian** [comment]
不行
不是我写的 原理说不了
是

**Comment by ghost** [comment]
好吧，我以为只要有插件就可以用的，折腾到现在也没成功，又把那些软件安装上去了，那你的EVERYTHING插件就是调用EVERYTHING软件的功能喽？你的SS插件是什么功能啊？我没看懂。。。

**Comment by bao-qian** [comment]
> 那你的EVERYTHING插件就是调用EVERYTHING软件的功能喽

是

> 你的SS插件是什么功能啊？我没看懂。。。

未知。。 这不是我写的。。

**Comment by ghost** [comment]
Edit config.json in plugin folder and replace the pacPath to your shadowsocks pac path. 没看懂。。。
我把SS软件放在那个文件夹里把PAC PACH 填进去？

**Comment by bao-qian** [comment]
这个插件现在崩了 你别试了

**Comment by ghost** [comment]
原来是想实现什么功能？我学生党一枚，想看看代码学学

**Comment by bao-qian** [comment]
我看了一眼
添加 域名 到你 ss 的 pac 文件
基本没用。。。。

你想学写插件 先看程序里面的两个 helloworld 然后看文档 http://doc.getwox.com/zh/plugin/

**Comment by ghost** [comment]
好的，谢谢。

**Comment by ghost** [comment]
顺便提一句，WEB搜索插件，只会在默认浏览器打开网页吗？不能指定路径用其他浏览器打开吗？

**Comment by bao-qian** [comment]
不能
你换默认浏览器不就好了

**Comment by ghost** [comment]
我默认浏览器是EDGE，但我一般用CHROME或者FIREFOX来搜索非日常的需求

**Comment by ghost** [comment]
学术、代码、资源等等

**Comment by ghost** [comment]
个人觉得EDGE应付日常的搜索还可以，UI设计也还不错

**Comment by ghost** [comment]
对了，有一个是不是BUG，我把Wox插件管理的触发关键词设置为NULL，就修改不了了，不知道其他插件是不是也这样。

**Comment by bao-qian** [comment]
@smallnerd 每个 issue 有特定主题，有问题另开

**Comment by ghost** [comment]
哦哦

**Comment by HsunGong** [comment]
建议关闭issue，具体问题可以到ss插件的github页面问。
此外，这个插件就是把你输入的网址加到pac文件里面，建议你自己手改，其实也很方便。

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by bao-qian** [comment]
插件的问题找建议插件开发
