### ISSUE TITLE
程序发生未知错误

### ISSUE THREAD

**Issue by rosuH** [Wox-launcher/Wox#724]
//log文件在附件
[2016-06-01.zip](https://github.com/Wox-launcher/Wox/files/292542/2016-06-01.zip)
中
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/01/2016 10:13:44
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[

](url)

**Comment by rosuH** [comment]
由于没有特定的条件之下复现此错误，也不知道原因，所以标题只能这么写了。见谅。

**Comment by bao-qian** [comment]
就是打不开吗？还是怎样？

**Comment by bao-qian** [comment]
是一直这样还是就一次？

**Comment by rosuH** [comment]
打开了之后立刻闪退，然后出现此错误提示。
只发生了一次。

**Comment by bao-qian** [comment]
那就忽略好了。。。
这是用的更新包报的错，只要能打开就不影响使用。。。
