### ISSUE TITLE
System.UnauthorizedAccessException Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)

### ISSUE THREAD

**Issue by alexnv** [Wox-launcher/Wox#726]
i'v just install it. that was first run

Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/01/2016 16:16:22
Exception:
mscorlib
System.UnauthorizedAccessException
Попытка выполнить несанкционированную операцию.
   в Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   в Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   в Wox.SettingWindow.SetStartup() в C:\projects\wox\Wox\SettingWindow.xaml.cs:строка 247
   в Wox.App.<OnStartup>b__8_0() в C:\projects\wox\Wox\App.xaml.cs:строка 62
   в Wox.App.OnStartup(Object sender, StartupEventArgs e) в C:\projects\wox\Wox\App.xaml.cs:строка 41
   в System.Windows.Application.<.ctor>b__1(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

[2016-06-01.zip](https://github.com/Wox-launcher/Wox/files/293480/2016-06-01.zip)

**Comment by alexnv** [comment]
runing with administrator rights take same error

**Comment by alexnv** [comment]
my antivirus is block program.

**Comment by bao-qian** [comment]
thanks for report

**Comment by alexnv** [comment]
may be add try/finnaly on this code? on my work pc i'm can't change antivirus parameters

**Comment by bao-qian** [comment]
Good point.
For now, modify appdata/wox/settings/settings.json 
Change start with system to false

**Comment by alexnv** [comment]
Thanks, that's work. But file doesn't exist with fresh install
