### ISSUE TITLE
关于 Wox 的一些功能意见

### ISSUE THREAD

**Issue by Kenshin** [Wox-launcher/Wox#729]
**1.3.67 版本， Windows 8.1 x64**

我是一个 效率类 应用的喜爱者，先后使用过很多类似产品，如：`CLanuch`，`ALTRun`，`Listary` 等等。

很早就使用过 Wox，但感觉速度一般，新版发布后，又重新使用了几天，还不错，尤其是结合 Everything 后，明显实用性增加了很多，感谢带给我们了新版。

以下是我在使用的时候发现的一些问题而形成的建议：
1. UI 需要雕琢；（例如：某些部分还是英文）
2. 回车后，隐藏输入框；（`增加选项`）
3. 启动后，隐藏窗体；（`增加选项`）
4. 新打开的窗体，建议为空白，而非上次输入的内容；（`增加选项`）
5. 开机自启应该默认不启动；（UE）
6. `主题` 无法修改字体大小以及窗体大小；
7. 网页搜索时，图标可以从URL处获取；
8. 最好有绿色版，以及更便捷的下载方式；
9. Everything 插件最好能一并提供下载；
10. 代理无法使用SOCKS5；
11. 每个插件应该有简单的介绍以及链接到 plugins 的地址；
12. 曾经输入过的内容应该有历史功能；

以上仅代表我的个人意见，请酌情考虑。 :)

**Comment by bao-qian** [comment]
1. 个人项目。。。
2. 这个取决于插件
3. 有了，等下一版
4. 以后加
5. 这个见仁见智了
6. 手动改 theme 的 xaml
7. 这太慢了。。。
8. #629 
9. 以后加。 bootstrap 不会写。。。
10. <del> 在 ie 设置，然后关掉 wox 的代理 </del>
11. 以后加
12. 现在这个功能有 bug，暂时关了

**Comment by SueChuan** [comment]
能够自定义窗口大小 和字体就好了

**Comment by rekcah1986** [comment]
第四条很要命，之前用mac的spot和alfred来着，很不习惯，如果能优先处理就再好不过了……

**Comment by Landius** [comment]
> ...
> 6. 手动改 theme 的 xaml
> ...
建议把第6条加到wox的文档说明里边
@bao-qian

**Comment by rekcah1986** [comment]
转战火萤酱了，用着还可以
