### ISSUE TITLE
[NullReferenceException] Wox.Plugin.Folder

### ISSUE THREAD

**Issue by utrott** [Wox-launcher/Wox#730]
Hi,

whenever Wox is started, the following appears again.

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\mkoch\AppData\Roaming\Wox\Logs\1.3.67\2016-06-02.log
2. copy below exception message
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/02/2016 09:09:58
Exception:
Wox.Plugin.Folder
System.NullReferenceException
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

And in the Log:

2016-06-02 09:09:58.2431|WARN|Wox.Core.Plugin.PluginConfig.GetPluginMetadata|parse plugin C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.MatHbMantisSearch\plugin.json failed: didn't find config file.
2016-06-02 09:09:58.6643|INFO|Wox.Infrastructure.Stopwatch.Normal|Preload 340 programs from cache
2016-06-02 09:09:58.6799|ERROR|Wox.Plugin.Folder.Main.Init|First Chance Exception:
2016-06-02 09:09:58.6799|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|First Chance Exception:
2016-06-02 09:09:58.6799|ERROR|Wox.Plugin.Folder.Main.Init|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.6799|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.6955|ERROR|Wox.Plugin.Folder.Main.Init|
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
2016-06-02 09:09:58.6955|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|
   bei Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 136.
2016-06-02 09:09:58.7111|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|First Chance Exception:
2016-06-02 09:09:58.7267|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|First Chance Exception:
2016-06-02 09:09:58.7267|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.7423|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.7423|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
2016-06-02 09:09:58.7423|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClassf`1.<ForWorker>b__c|
   bei Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 136.
   bei Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 102.
   bei Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:Zeile 94.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
2016-06-02 09:09:58.7579|ERROR|System.Threading.Tasks.Task.Wait|First Chance Exception:
2016-06-02 09:09:58.7735|ERROR|System.Threading.Tasks.Task.Wait|Mindestens ein Fehler ist aufgetreten.
2016-06-02 09:09:58.7735|ERROR|System.Threading.Tasks.Task.Wait|
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2016-06-02 09:09:58.7735|ERROR|System.Threading.Tasks.Task.Wait|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.7891|ERROR|System.Threading.Tasks.Task.Wait|
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
2016-06-02 09:09:58.7891|ERROR|System.Threading.Tasks.Parallel.ForWorker|First Chance Exception:
2016-06-02 09:09:58.8047|ERROR|System.Threading.Tasks.Parallel.ForWorker|Mindestens ein Fehler ist aufgetreten.
2016-06-02 09:09:58.8047|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-06-02 09:09:58.8047|ERROR|System.Threading.Tasks.Parallel.ForWorker|Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
2016-06-02 09:09:58.8203|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)
2016-06-02 09:09:58.8359|FATAL|System.Windows.Threading.Dispatcher.CatchException|
## Exception

```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   Source: Wox.Plugin.Folder
   TargetAssembly: Wox.Plugin.Folder, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Folder.dll
   TargetSite: Void Init(Wox.Plugin.PluginInitContext)
   bei Wox.Plugin.Folder.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:Zeile 40.
   bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:Zeile 25.
   bei Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 81.
   bei System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

System.AggregateException: Mindestens ein Fehler ist aufgetreten.
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Boolean Wait(Int32, System.Threading.CancellationToken)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   bei Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:Zeile 79.
   bei Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:Zeile 54.
   bei Wox.App.OnStartup(Object sender, StartupEventArgs e) in C:\projects\wox\Wox\App.xaml.cs:Zeile 41.
   bei System.Windows.Application.<.ctor>b__1(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Wox.exe" 
- Timestamp: 2016-06-02T09:09:58.8359966+02:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 6.1.7601 Service Pack 1
- CLR Version: 4.0.30319.34209
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.5420 SP2
  - v3.0 3.0.30729.5420 SP2
  - v3.5 3.5.30729.5420 SP1
  - v4 Client 4.5.51209
  - v4 Full 4.5.51209
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Wox.exe)
- Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Wox.Infrastructure.dll)
- Wox.Core, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Wox.Core.dll)
- Wox.Plugin, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Wox.Plugin.dll)
- Squirrel, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Squirrel.dll)
- Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Splat.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Newtonsoft.Json.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\NLog.dll)
- Wox.Plugin.Caculator, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\mkoch\AppData\Local\Wox\app-1.3.67\NHotkey.Wpf.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_de_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- PresentationCore.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_de_31bf3856ad364e35\PresentationCore.resources.dll)
- PresentationFramework.Aero, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll)

2016-06-02 09:22:53.9895|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|First Chance Exception:
2016-06-02 09:22:53.9965|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|Die Anwendungsidentität ist nicht festgelegt.
2016-06-02 09:22:53.9965|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   bei System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
2016-06-02 09:23:00.2189|ERROR|System.Number.ParseDouble|First Chance Exception:
2016-06-02 09:23:00.2189|ERROR|System.Number.ParseDouble|Die Eingabezeichenfolge hat das falsche Format.
2016-06-02 09:23:00.2369|ERROR|System.Number.ParseDouble|
   bei System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)

**Comment by bao-qian** [comment]
try new build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.157/artifacts

**Comment by utrott** [comment]
The new build does work as well as the old version, after I deleted the settings dir.

So, sadly I am no longer able to reproduce the error. Sorry. I'd suggest to close this issue.

thx.

**Comment by bao-qian** [comment]
thanks for report
