### ISSUE TITLE
windows10 安装后出现的异常信息

### ISSUE THREAD

**Issue by wenxingyu** [Wox-launcher/Wox#733]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/03/2016 19:21:46
Exception:
mscorlib
System.UnauthorizedAccessException
尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Wox.SettingWindow.SetStartup() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 246
   在 Wox.App.AutoStartup() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 77
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 62
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
check your antivirus
or
https://github.com/Wox-launcher/Wox/issues/726#issuecomment-223010732

**Comment by wenxingyu** [comment]
it's the antivirus cause this exception
