### ISSUE TITLE
不能获得焦点

### ISSUE THREAD

**Issue by runforprogram** [Wox-launcher/Wox#734]
`alt+space`调用出来的时候,有时候获得不到焦点.这个时候`esc`不能最小化程序

**Comment by bao-qian** [comment]
请具体描述什么情况下。
最近正在攻克这个问题。
详细描述十分重要。
已知情况
开始菜单打开，任务管理器在焦点，没有任何程序打开的情况下。

**Comment by bao-qian** [comment]
因无回复而关闭。有问题再开。
