### ISSUE TITLE
[SimpleClock] buggy

### ISSUE THREAD

**Issue by mjrlgue** [Wox-launcher/Wox#735]
## English
1.  Wox version: 1.3.67
2. Describ bug:
   it shows an error message, see the full message below.
3.  Windows version: 10 
4. logs uploaded
   ******************************_Error message:**_****************************
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 10.0.10586.0
   Date: 06/03/2016 17:34:07
   Exception:
   Wox.Plugin.SimpleClock
   System.TypeLoadException
   Impossible de charger le type 'Wox.Infrastructure.Storage.BaseStorage`1' à partir de l'assembly 'Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null'.
   à Wox.Plugin.SimpleClock.Commands.AlarmCommand.InitializeStorage(PluginInitContext context)
   à Wox.Plugin.SimpleClock.Commands.AlarmCommand..ctor(PluginInitContext context, CommandHandlerBase parent)
   à Wox.Plugin.SimpleClock.ClockPlugin.Init(PluginInitContext context)
   à Wox.Infrastructure.Stopwatch.Normal(String name, Action action) dans C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:ligne 28
   à Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) dans C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:ligne 90
   à System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   à System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   à System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[logWox.zip](https://github.com/Wox-launcher/Wox/files/297987/logWox.zip)

**Comment by bao-qian** [comment]
delete  Wox.Plugin.SimpleClock plugin from %APPDATA%\Wox\Plugin

**Comment by mjrlgue** [comment]
thank you #happlebao, it works :D

**Comment by bao-qian** [comment]
@mjrlgue SimpleClock has been updated

**Comment by mjrlgue** [comment]
okey, thanks
