### ISSUE TITLE
[NullReferenceException] OnStartup

### ISSUE THREAD

**Issue by zarub666** [Wox-launcher/Wox#736]
## English

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/04/2016 09:29:41
Exception:
Wox
System.NullReferenceException
Ссылка на объект не указывает на экземпляр объекта.
   в Wox.App.<OnStartup>b__8_0() в C:\projects\wox\Wox\App.xaml.cs:строка 48
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[log](http://www31.zippyshare.com/v/7oUx568S/file.html)

**Comment by bao-qian** [comment]
try delete %APPDATA%\Wox

**Comment by alexinea** [comment]
Thx. In this way, I can enjoy Wox again.

**Comment by bao-qian** [comment]
close due to no response.
