### ISSUE TITLE
有Windows Xp sp3可用的版本么？

### ISSUE THREAD

**Issue by pipiliang** [Wox-launcher/Wox#740]
## windows xp sp3无法安装最近几个版本，是否有可用的版本？
1. Wox Version: 1.3.67
2. 无法安装
3. Windows Xp sp3

**Comment by jhdxr** [comment]
这年头。。。最起码WIN7起了吧。。。XP太多东西不能用了。。。

**Comment by bao-qian** [comment]
没有。
