### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by xiongwei-git** [Wox-launcher/Wox#741]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/06/2016 20:34:46
Exception:
Wox.Core
System.MissingMethodException
找不到方法:“Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)”。
   在 Wox.Core.Resource.Theme.SetWindowAccent(Window wind, AccentState themeAccentMode)
   在 Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 60
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[
[2016-06-06.log.txt](https://github.com/Wox-launcher/Wox/files/300364/2016-06-06.log.txt)
[Uploading 2016-06-06.log.txt…]()

](url)

[Uploading 2016-06-06.log.txt…]()

**Comment by bao-qian** [comment]
重启电脑试一下

**Comment by bao-qian** [comment]
下 .net 4.5.2 
https://www.microsoft.com/en-ie/download/details.aspx?id=42643
