### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by pluieFox** [Wox-launcher/Wox#743]
1. 希望能够增加自定义程序的启动命令，因为有一些非安装的绿色版程序，使用Wox的话就只能通过everything来搜索了。
2. 增加关闭显示器的命令，这个功能executor里有。

**Comment by bao-qian** [comment]
1. program 插件可以设置搜索路劲
   ![image](https://cloud.githubusercontent.com/assets/1169912/16102337/43851d3e-3366-11e6-8aef-00b1fb2de5a9.png)

**Comment by VictoriousRaptor** [comment]
关闭显示器可以由如下命令安装插件实现

```
wpm install Close Screen
```

插件关键字：

```
closescreen
```
