### ISSUE TITLE
无法找不到组件。 (异常来自 HRESULT:0x88982F50)

### ISSUE THREAD

**Issue by guofuzi111** [Wox-launcher/Wox#752]
你好，遇到如下问题：
1. 请提供 Wox 版本
   - 1.3.67
2. 请提供如何 **重现** bug 的步骤
   - 使用计算器插件，无响应
   - 添加有道程序目录到`program`里面，不能查词
   - 添加有道插件，输入yd，无反应，有移动进度条状出现
     ![y](https://cloud.githubusercontent.com/assets/4075564/15984376/05174734-2ffb-11e6-9ad9-d3737af7807a.jpg)
     ![yd](https://cloud.githubusercontent.com/assets/4075564/15984378/085fa490-2ffb-11e6-93f9-55b96bdd82c5.jpg)
     ![进度条](https://cloud.githubusercontent.com/assets/4075564/15984375/05106dba-2ffb-11e6-8050-326684eebd78.jpg)
     ![bug](https://cloud.githubusercontent.com/assets/4075564/15984377/061c2348-2ffb-11e6-8079-5096e181ac25.jpg)
3. 请提供 Windows 版本
   - win 8.1 64bit 专业版
4. 如果有 Exception/Crash Report 的话，请一并提供
   [2016-06-11log.txt](https://github.com/Wox-launcher/Wox/files/310174/2016-06-11log.txt)
   - Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
5. upload log file: C:\Users\123\AppData\Roaming\Wox\Logs\1.3.67\2016-06-11.log
6. copy below exception message

Wox version: 1.3.67

OS Version: Microsoft Windows NT 6.3.9600.0

Date: 06/11/2016 16:57:06

Exception:

System.Runtime.InteropServices.COMException

无法找不到组件。 (异常来自 HRESULT:0x88982F50)
1. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
2. 如果有截图的话，请一并提供

**Comment by bao-qian** [comment]
有道词典下这一个：
之前那个文件从 %APPDATA%\Wox\plugin 中删除
http://www.getwox.com/plugin/78

**Comment by coffee-or-tea** [comment]
您好，我想下载这个.exe看下功能怎么样，可是我发现这个Wox-1.3.67.exe怎么也下载不下来，所以想问下有什么解决方法？

**Comment by bao-qian** [comment]
无回复而关闭
