### ISSUE TITLE
.exe 不能下载。

### ISSUE THREAD

**Issue by coffee-or-tea** [Wox-launcher/Wox#755]

**Comment by jhdxr** [comment]
翻墙  你所在地区的aws可能被墙了

**Comment by bao-qian** [comment]
@jhdxr 国内不翻墙不能下 github release 的东西？

**Comment by coffee-or-tea** [comment]
OK,Got it,thanks.

**Comment by bao-qian** [comment]
@coffee-or-tea 确定是 aws 的问题？你说一下你的地区和运营商？

**Comment by coffee-or-tea** [comment]
@happlebao ，北京电信。

**Comment by coffee-or-tea** [comment]
@happlebao ，是不是aws的问题不太确定呀

**Comment by bao-qian** [comment]
1. 你开了代理能下了
2. 你不开代理就能下

1 还是 2 ？

**Comment by coffee-or-tea** [comment]
不开代理，大概下个零点几兆就断了。开代理，能下，不过巨慢。

**Comment by bao-qian** [comment]
这不行啊。。
过段时间我加个国内镜像。。。

**Comment by bao-qian** [comment]
https://pan.baidu.com/s/1mhN0boc#path=%252FWox-v1.3.183
