### ISSUE TITLE
[NullReferenceException] wox got a error

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#757]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   - If you checkout from master/dev branch, please specify **commit number**
2. Please describe the steps to **reproduce** the bug
3. Please provide Windows version
4. Please provide Exception info if you have.
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
2. 请提供如何**重现** bug 的步骤
3. 请提供 Windows 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

wox 
2016-06-12 20:12:24.6342|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:12:24.6654|ERROR|Wox.App.<OnStartup>b__8_0|未将对象引用设置到对象的实例。
2016-06-12 20:12:24.6967|ERROR|Wox.App.<OnStartup>b__8_0|
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
2016-06-12 20:12:24.7279|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox
   TargetAssembly: Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.exe
   TargetSite: Void <OnStartup>b__8_0()
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe" 
- Timestamp: 2016-06-12T20:12:24.7279914+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe)
- Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Infrastructure.dll)
- Wox.Core, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Core.dll)
- Wox.Plugin, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Plugin.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Newtonsoft.Json.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)

2016-06-12 20:12:28.5333|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:12:28.5533|ERROR|Wox.App.Dispose|未将对象引用设置到对象的实例。
2016-06-12 20:12:28.5533|ERROR|Wox.App.Dispose|
   在 Wox.App.Dispose() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 132
2016-06-12 20:12:28.5713|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:12:28.5713|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|未将对象引用设置到对象的实例。
2016-06-12 20:12:28.5883|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   在 Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) 位置 C:\projects\wox\Wox\Helper\ErrorReporting.cs:行号 0
2016-06-12 20:14:08.5969|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:14:08.6282|ERROR|Wox.App.<OnStartup>b__8_0|未将对象引用设置到对象的实例。
2016-06-12 20:14:08.6594|ERROR|Wox.App.<OnStartup>b__8_0|
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
2016-06-12 20:14:08.6907|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox
   TargetAssembly: Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.exe
   TargetSite: Void <OnStartup>b__8_0()
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe" 
- Timestamp: 2016-06-12T20:14:08.6907049+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe)
- Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Infrastructure.dll)
- Wox.Core, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Core.dll)
- Wox.Plugin, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Plugin.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Newtonsoft.Json.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)

2016-06-12 20:14:41.2848|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:14:41.2848|ERROR|Wox.App.Dispose|未将对象引用设置到对象的实例。
2016-06-12 20:14:41.2848|ERROR|Wox.App.Dispose|
   在 Wox.App.Dispose() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 132
2016-06-12 20:14:41.3004|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:14:41.3004|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|未将对象引用设置到对象的实例。
2016-06-12 20:14:41.3160|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   在 Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) 位置 C:\projects\wox\Wox\Helper\ErrorReporting.cs:行号 0
2016-06-12 20:15:05.7382|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:15:05.7850|ERROR|Wox.App.<OnStartup>b__8_0|未将对象引用设置到对象的实例。
2016-06-12 20:15:05.7850|ERROR|Wox.App.<OnStartup>b__8_0|
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
2016-06-12 20:15:05.8163|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox
   TargetAssembly: Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.exe
   TargetSite: Void <OnStartup>b__8_0()
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe" 
- Timestamp: 2016-06-12T20:15:05.8007226+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.exe)
- Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Infrastructure.dll)
- Wox.Core, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Core.dll)
- Wox.Plugin, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Wox.Plugin.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\Newtonsoft.Json.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\wu152\AppData\Local\Wox\app-1.3.67\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)

2016-06-12 20:15:13.3169|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:15:13.3326|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|未设置应用程序标识。
2016-06-12 20:15:13.3326|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   在 System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
2016-06-12 20:15:14.3482|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:15:14.3482|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
2016-06-12 20:15:14.3638|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
2016-06-12 20:15:15.3795|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:15:15.3795|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
2016-06-12 20:15:15.3795|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
2016-06-12 20:16:15.8117|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:16:15.8257|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
2016-06-12 20:16:15.8367|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
2016-06-12 20:16:16.7754|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:16:16.7754|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
2016-06-12 20:16:16.7754|ERROR|System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal|
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
2016-06-12 20:16:16.8165|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:16:16.8205|ERROR|Wox.App.Dispose|未将对象引用设置到对象的实例。
2016-06-12 20:16:16.8205|ERROR|Wox.App.Dispose|
   在 Wox.App.Dispose() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 132
2016-06-12 20:16:16.8205|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-06-12 20:16:16.8355|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|未将对象引用设置到对象的实例。
2016-06-12 20:16:16.8355|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   在 Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) 位置 C:\projects\wox\Wox\Helper\ErrorReporting.cs:行号 0

**Comment by bao-qian** [comment]
1. try delete %APPDATA%\Wox
2. please try new build: https://ci.appveyor.com/project/happlebao/wox/build/1.3.156/artifacts

**Comment by bao-qian** [comment]
close due to no response
