### ISSUE TITLE
cancel the "enable plugin installer" cause crash

### ISSUE THREAD

**Issue by mapleray** [Wox-launcher/Wox#76]
In the Wox-settings, when I click the "enable plugin installer" button, then it comes a dialog about whether to run "wox.UAC.exe". I chose "no" and then the application crashed. 
- A Wonderful Application!*

**Comment by kerams** [comment]
I think you might be running an older version. It's working alright for me and it seems it's been fixed here b07d1b027c.

**Comment by mapleray** [comment]
em....I downloaded it from the main page. 
https://github.com/qianlifeng/wox/releases
It released a month ago...not the latest. Thanks
