### ISSUE TITLE
ImageCache.dat in use

### ISSUE THREAD

**Issue by friscoMad** [Wox-launcher/Wox#762]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   1.3.67
2. Please describe the steps to **reproduce** the bug
   Open WOX with windows, no other WOX instances running. Restarting WOX does not fix the issue.
3. Please provide Windows version
   W7 64bits
4. Please provide Exception info if you have.
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
   Date: 06/13/2016 11:01:24
   Exception:
   mscorlib
   System.IO.IOException
   El proceso no puede obtener acceso al archivo 'C:\Users\ramiro.aparicio.ext\AppData\Roaming\Wox\Cache\ImageCache.dat' porque está siendo utilizado en otro proceso.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode)
   en Wox.Infrastructure.Storage.BinaryStorage`1.Save() en C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:línea 104
   en Wox.Infrastructure.Storage.BinaryStorage`1.Load() en C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:línea 40
   en Wox.Infrastructure.Image.ImageLoader..cctor() en C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:línea 41
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

[2016-06-13.txt](https://github.com/Wox-launcher/Wox/files/311516/2016-06-13.txt)

**Comment by bao-qian** [comment]
1. how about delete all plugins from %APPDATA%\Wox\Plugin
2. try https://ci.appveyor.com/project/happlebao/wox/build/1.3.156

**Comment by friscoMad** [comment]
Indeed I deleted the image cache file and it worked again but I was not showing programs from the launch menu, wih this build (and deleting the plugin folder) everything seems ok.

The only "bug" I found is that calling Exit command from wox did close the interface but not the process just the first time the installation runs, killed from task manager and runing and exit worked again without issues.

**Comment by bao-qian** [comment]
my own todo:
- [x] if use static method in other thread, will this cause static constructor called twice?
no
