### ISSUE TITLE
[NullReferenceException] Wox.Plugin.Folder

### ISSUE THREAD

**Issue by houskii** [Wox-launcher/Wox#766]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/14/2016 22:23:38
Exception:
Wox.Plugin.Folder
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Folder.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Folder\Main.cs:行号 40
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 81
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by houskii** [comment]
Reinstall show me the same error log

**Comment by bao-qian** [comment]
试一下
https://ci.appveyor.com/project/happlebao/wox/build/1.3.157/artifacts

**Comment by houskii** [comment]
error still

Wox version: 1.3.157
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/16/2016 17:57:13
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__18_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 81
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by houskii** [comment]
forget to delete Folder [wox] in C:\Users\Administrator\AppData\Roaming
after delete and reinstall , seems no error anymore

**Comment by bao-qian** [comment]
thanks for report
