### ISSUE TITLE
希望增加通配符配置功能

### ISSUE THREAD

**Issue by xjl456852** [Wox-launcher/Wox#769]
wox版本 1.3.67

希望在插件中的Program插件中,增加通配符的设置功能,因为有时候会把电子书pdf,chm,txt等等格式的文件放在目录中,并快速启动.书籍的目录经常会增加很多内容.如果只是执行精确的扩展名,确实不方便.
希望增加通配符 \* 的功能,可以表示文件夹下的所有内容.

**Comment by bao-qian** [comment]
使用方法有误啊。。
那是用来搜索应用程序的。
你应该用 装 everything + 开 everything service + 用内置的 everything 插件

**Comment by xjl456852** [comment]
everything 我有,但是everything是搜索所有目录下的内容,launchy就有增加通配符的功能,wox也可以增加这种功能,其实书籍,文档这类东西只是有些目录的文件比较常用,才会增加快速启动,并不是电脑上所有的文件都是常用的.所以增加通配符效果更好,更加方便.

**Comment by bao-qian** [comment]
everything 可以设置搜索路径
在 everything 自己的设置中

**Comment by xjl456852** [comment]
增加通配符不仅不会影响原有功能,还能给软件设置上带来便捷性,功能更加强大,何乐而不为.
快速启动,就是可以对任何你想快速启动的内容,进行瞬间启动.everything主要是搜索,匹配的项目太多了
就像搜索linux,可以匹配无数目录和文件,但是快速启动的话是只启动设置中的linux中指定的目录或文件.跟everything的需求完全是两回事,不能把everything修改的跟快速启动工具功能一样,如果用everything设置软件快捷方式的目录,再设置文档的目录,用起来会很别扭,因为everything就是全局搜索.
而且那样wox岂不是又多了个竞争对手.
要让wox更加完美,更加无法匹敌才是重要的目的.

**Comment by bao-qian** [comment]
program  插件加了很多处理的。比如拼音，缩写，等等。这么搞的话会很慢的。。。
1. 你想搜索指定目录，everything 有专门语法啊。 `folder\ linux`
2. 你多按几次，常用的就在前面了

wox 就是个整合而已。把所有相关的整合起来。

**Comment by xjl456852** [comment]
速度的快慢主要是跟program所设置的中文件夹下内容的多少有关系.这个跟用户的使用习惯有关系,如果把这个作为软件功能上的限制,我认为会制约软件的发展.everything也不会因为用户的文件多就不搜索或者搜索太慢.Launchy就可以用通配符来做匹配,也可以执行exe,bat等等扩展名,这只是一种便捷的功能,
至于用户用不用,或者用它来添加什么样的目录,启动什么样的文件,这个我认为都不是软件作者能限制住的或者应该限制的.
希望wox变得越来越好

**Comment by AjiMIde** [comment]
使用此软件一年有余，一直不知道如何搜索路径，现将方法点明：
* everything--设置--搜索--允许前斜杆作为路径分隔符
* 搜索举例如下：
aa/ bb/ cc 注意斜杆后面有个空格
这样就能搜索路径啦，有错请点明，谢谢
