### ISSUE TITLE
Custom plugin not being loaded when Wox is restarted

### ISSUE THREAD

**Issue by LukaHorvat** [Wox-launcher/Wox#77]
I wanted to make a plugin but I can't seem to get it working.
I did everything in the guide and I placed my files in Wox/Plugins/Wox.Plugin.Volume but when I restart Wox and type in "wpm list", my plugin isn't there.

This is my  plugin.json

```
{
    "ID":"WoxVolume",   //Plugin Unique ID
    "ActionKeyword":"vol",                     //Plugin action keyword that user used to trigger your plugin
    "Name":"WoxVolume",                   //Plugin name
    "Description":"Volume manager for Wox",    //Plugin description
    "Author":"Luka Horvat",                     //Author name
    "Version":"1.0",                           //Plugin version. should be a double
    "Language":"csharp",                       //Plugin type. In csharp case, you should use "csharp"
    "Website":"",         //Plugin website
    "ExecuteFileName":"Wox.Plugin.Volume.dll"                //your plugin dll
}
```

In my project I have a namespace Wox.Plugin.Volume, in it a class Plugin that implements IPlugin.

The code in it is

```
    public void Init(PluginInitContext context)
    {
    }

    public List<Result> Query(Query query)
    {
        var results = new List<Result>();
        results.Add(new Result
        {
            Title = "Test",
            SubTitle = "SubTitle",
            IcoPath = "Images\\img.png",
            Action = c => true
        });
        return results;
            }
```

The target framework is .NET 3.5. What else do I need to do?

**Comment by orzFly** [comment]
You cannot see your plugin unless you uploaded your plugin to [qianlifeng/Wox.Plugins](https://github.com/qianlifeng/Wox.Plugins). WPM only loads the plugin list from that repo since it's a plugin download tool.

**Comment by LukaHorvat** [comment]
In any case, my plugin doesn't work. When I write "vol", it just reacts like I'm searching for applications.

**Comment by LukaHorvat** [comment]
Never mind. The problem was with the comments in the JSON. It says the format is invalid if it has comments.

**Comment by qianlifeng** [comment]
@orzFly wpm list will list the installed plugins, not the list from getwox.com.

**Comment by LukaHorvat** [comment]
wpm list works now that I've fixed my plugin.json. I still think that it should load it even if there are comments in it.

**Comment by orzFly** [comment]
Comments is not a part of JSON....

## 

@qianlifeng OK. I didn't read too much about WPM.

**Comment by LukaHorvat** [comment]
They are given in the C# plugin guide.
