### ISSUE TITLE
wox无法启动

### ISSUE THREAD

**Issue by xtrats** [Wox-launcher/Wox#774]
按电源键强制重启之后，wox就不能启动了，再正常重启也不行。

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/16/2016 10:04:12
Exception:
Wox
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 48
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`

**Comment by bao-qian** [comment]
上传整个 `%APPDATA%\Wox`

**Comment by bao-qian** [comment]
有问题再开

**Comment by XuelinHu** [comment]
版本 1.4.1196 ，安装在Windows 10 专业版，启动后没有弹出搜索框，alt+space无效，右击
![image](https://user-images.githubusercontent.com/9259745/167991458-52b5857d-2f70-4b2d-b256-6cbf3eb1c887.png)
，没有反应
