### ISSUE TITLE
多显示器，启动后无法定位焦点

### ISSUE THREAD

**Issue by ousui** [Wox-launcher/Wox#776]
默认显示器在左边，
但是我在右边的显示器 快捷键唤醒默认是在左边
如果我选项里设置了记住上次位置，移动到右边，鼠标在左边，快捷键唤醒，**退格删除以后**，窗体会来到鼠标所在的窗体。
1.3.139

**Comment by bao-qian** [comment]
之前大改快捷键失败了。。。 导致很多问题。。。revert 了
你用下面这个。。。
https://ci.appveyor.com/project/happlebao/wox/build/1.3.161
