### ISSUE TITLE
[WebSearch] 网页搜索插件中，历史触发关键词无法再次使用

### ISSUE THREAD

**Issue by tanyuxiang** [Wox-launcher/Wox#777]
Wox1.3.6
网页搜索插件中，修改和添加删除留下的**历史**触发关键词无法再次使用。另外添加新搜索时，有时出现保存成功然后立即提示关键词无法使用，列表中并没有保存成功，这个触发关键词之后也无法再次添加。

建议添加功能：触发关键词管理。列出所有触发关键词，清理失效触发关键词。

**Comment by bao-qian** [comment]
1.3.67 吧？

**Comment by bao-qian** [comment]
试一下新的
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174/artifacts
