### ISSUE TITLE
[WebSearch] 第一次使用，感觉bug有点多啊

### ISSUE THREAD

**Issue by ribber** [Wox-launcher/Wox#778]
想添加一个知乎的搜索，关键字定义z zh zhi 都说关键字已指派给其他插件。后来就报了这个错误
## English
1. upload log file: C:\Users\wrb\AppData\Roaming\Wox\Logs\1.3.67\2016-06-17.log
2. copy below exception message
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
   Date: 06/17/2016 21:23:35
   Exception:
   mscorlib
   System.ArgumentOutOfRangeException
   索引超出范围。必须为非负值并小于集合大小。
   参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 System.Collections.Generic.List`1.set_Item(Int32 index, T value)
   在 Wox.Core.Plugin.PluginManager.UpdateActionKeywordForPlugin(PluginPair plugin, String oldActionKeyword, String newActionKeyword) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 275
   在 Wox.SettingWindow.<>c__DisplayClass34_0.<lbPlugins_OnSelectionChanged>b__0(IMultipleActionKeywords o, ActionKeywordsChangedEventArgs e) 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 644
   在 Wox.Plugin.ActionKeywordsChangedEventHandler.Invoke(IMultipleActionKeywords sender, ActionKeywordsChangedEventArgs e)
   在 Wox.Plugin.WebSearch.Main.NotifyActionKeywordsUpdated(String oldActionKeywords, String newActionKeywords) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\Main.cs:行号 172
   在 Wox.Plugin.WebSearch.WebSearchSetting.ConfirmButtonOnClick(Object sender, RoutedEventArgs e) 位置 C:\projects\wox\Plugins\Wox.Plugin.WebSearch\WebSearchSetting.xaml.cs:行号 89
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
感谢汇报

**Comment by bao-qian** [comment]
试一下新的
https://ci.appveyor.com/project/happlebao/wox/build/1.3.174/artifacts
