### ISSUE TITLE
Wox Source not Building

### ISSUE THREAD

**Issue by wasimmalik88** [Wox-launcher/Wox#779]
Hi I am trying to build source code because i want to contribute in project.
I am using visual studio 2013 to build it 

Here are errors
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\PluginMetadata.cs(47,35,47,37): error CS1002: ; expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\PluginMetadata.cs(47,45,47,46): error CS1519: Invalid token ';' in class, struct, or interface member declaration
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(47,35,47,37): error CS1002: ; expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(47,38,47,49): error CS1520: Method must have a return type
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(47,50,47,51): error CS1031: Type expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(64,36,64,38): error CS1002: ; expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(64,39,64,50): error CS1520: Method must have a return type
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(64,51,64,52): error CS1031: Type expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(69,35,69,37): error CS1002: ; expected
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(69,38,69,49): error CS1520: Method must have a return type
1>C:\Users\wdin\Downloads\Wox-master\Wox-master\Wox.Plugin\Query.cs(69,50,69,51): error CS1031: Type expected

I am sorry if i am posting it on wrong but i need help so that i can help community to build Wox much greater

**Comment by bao-qian** [comment]
use vs 2015
