### ISSUE TITLE
Application quit on entering CIFS address in WIN+R dialog

### ISSUE THREAD

**Issue by minzhang** [Wox-launcher/Wox#78]
To re-produce:
1. press Win+R
2. enter \\192.168.1.1 after the ">"
3. press Enter
4. Wox freeze and quit

**Comment by aaroncampf** [comment]
What you did caused an error that killed the application.
That error will now be handled properly and a message will be displayed.

I assume that error was because the computer did not know how to run \192.168.1.1
If this fix is acceptable, please close the issue.

**Comment by qianlifeng** [comment]
@minzhang I have tested in the lastest Wox build, and this issues should not exist anymore.

**Comment by minzhang** [comment]
Verified and close issue.
