### ISSUE TITLE
新安装打开报错，设置general里面的下拉菜单什么东西都没有

### ISSUE THREAD

**Issue by LiuChaoCN** [Wox-launcher/Wox#780]
[2016-06-18.txt](https://github.com/Wox-launcher/Wox/files/321547/2016-06-18.txt)
1. copy below exception message
   Wox version: 1.3.67
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
   Date: 06/18/2016 10:58:38
   Exception:
   mscorlib
   System.UnauthorizedAccessException
   尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Wox.SettingWindow.SetStartup() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 247
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 62
   在 Wox.App.OnStartup(Object sender, StartupEventArgs e) 位置 C:\projects\wox\Wox\App.xaml.cs:行号 41
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
检查杀软或者防火墙

**Comment by bao-qian** [comment]
或者取消自动启动

**Comment by LiuChaoCN** [comment]
关闭杀软解决了

**Comment by bao-qian** [comment]
你不应该关闭杀软，给 wox 设个白名单之类的更好
