### ISSUE TITLE
Could I have documentation how to create custom plugin settings?

### ISSUE THREAD

**Issue by jardicc** [Wox-launcher/Wox#784]
Could I have documentation how to create custom plugin settings? I am creating plugin for URL shortener using https://yourls.org API

**Comment by bao-qian** [comment]
py or c#?

**Comment by jardicc** [comment]
c# please

**Comment by bao-qian** [comment]
1. use https://github.com/Wox-launcher/Wox/blob/master/Wox.Plugin/ISettingProvider.cs for settings ui
2. use https://github.com/Wox-launcher/Wox/blob/master/Wox.Infrastructure/Storage/PluginJsonStorage.cs for json storage.  (this api is not stable now, as it is not exposed in wox.plguin dll)

**Comment by bao-qian** [comment]
example:

```
var storage = new PluginJsonStorage<Model>();
var model = storage.Load();
storage.save()
```

**Comment by jardicc** [comment]
I have no idea how to use it. There is no explanation. It's just code. 
This documentation is ok. http://doc.getwox.com/en/plugin/csharp_plugin.html 
I was able create plugin, but without custom UI settings.

**Comment by happlebao** [comment]
1.

**Comment by bao-qian** [comment]
for custom UI settings, you need use `ISettingProvider` interface and implement `CreateSettingPanel`. in that method, you need return your view class.

```
public class Main : IPlugin, ISettingProvider
{
    public Control CreateSettingPanel()
    {
        var control = new SettingsControl();
        return control;
    }
}
```

**Comment by jardicc** [comment]
Still not good documentation. I need step by steb guide :-/ 

Now I have problem with: "PluginJsonStorage" Type or namespace couldn't be found. I added Newtonsoft.Json into references, but I have no Idea if I need it.

If you want to have a good and a famous program, you need a lot of good plugins. And if you want a lot of good plugins, you need good documentation.

**Comment by lances101** [comment]
@jardicc Your project with the plugin needs to be aware of `Wox.Infrastructure` namespace. The `Wox.Plugin` nuget package does not include it (although there were discussions about migrating it). 

Easiest way for you would be to add a reference to the `Wox.Infrastructure.dll` inside of your project (you can find the .dll in Wox's installation folder). 

Also, yes. The documentation is lacking and covers only the basics of creating a plugin. Somebody needs to put his/her hands on that.

**Comment by bao-qian** [comment]
Because that is not a public api and it's not finished.
And of course, this is a casual project, lack of time, peoples etc.

**Comment by jardicc** [comment]
Ok, I already figured it out.
I thought that if other plugins have their own UI settings, so it is finished.

**Comment by bao-qian** [comment]
i'm sorry for confused docs

**Comment by Rand-o** [comment]
Is there a way to do this using Python? Definitely not clear

**Comment by LumosLovegood** [comment]
> Is there a way to do this using Python? Definitely not clear

I also want to know how to create a plugin setting page using python.
