### ISSUE TITLE
未找到适用于完成此操作的图像处理组件

### ISSUE THREAD

**Issue by flowprog** [Wox-launcher/Wox#787]
刚打开做正常搜索的时候，好像是敲入第一个字母的时候，好像上一次搜索进入了二级菜单还没退出来

Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 06/21/2016 10:48:33
Exception:

System.Runtime.InteropServices.COMException
异常来自 HRESULT:0x88982F50

[2016-06-21 .txt](https://github.com/Wox-launcher/Wox/files/324704/2016-06-21.txt)

**Comment by bao-qian** [comment]
试一下新 build
https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Comment by bao-qian** [comment]
有问题再开
