### ISSUE TITLE
wox使用过程中everything没了

### ISSUE THREAD

**Issue by RichardBao1993** [Wox-launcher/Wox#788]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   - If you checkout from master/dev branch, please specify **commit number**
2. Please describe the steps to **reproduce** the bug
3. Please provide Windows version
4. Please provide Exception info if you have.
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
2. 请提供如何**重现** bug 的步骤
3. 请提供 Windows 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

我之前用的1.2beta版本，很稳定，很好用。看到更新很多了，于是下载了最新的版本，但是发现只有不到10M大小，后来看了下是没有everything内置，又跑去下了个最后一个带everything版本的，发现可以使用，于是又去把最新版本放进同一个文件夹里面，然后又崩了。。。。
后来我就通过设置里面自动更新试了下，发现貌似可以用了。。。但是今天又出现问题了。。。
希望能够同步推出完整版本（傻瓜安装），方便我们小白使用。。。。。对了，希望增加个快捷键可以设置定时关机的。。。。

一如既往的支持wox launcher！！！！！！希望能够收到反馈

Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/21/2016 22:02:41
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
everything 要去官网下：https://www.voidtools.com/
下完之后安装，开系统服务

自带 everything 安装包的有当然有计划， 但安装包太难写。。。。。
1. 删掉之前的东西 
2. 下 everything 安装
3. 下 wox 安装

**Comment by bao-qian** [comment]
既然支持，请在右上角 加星 :smile:

**Comment by bao-qian** [comment]
有问题再开

**Comment by RichardBao1993** [comment]
已加星！！！希望做成商业产品！！！！
考虑开发个UWP版本???

对了，提议个小意见（最好每次都提供百度网盘的下载包，完整版的，里面一定一定附加个安装说明，这个对小白用户很友好！！）
