### ISSUE TITLE
Remove wox window when clicking out of it

### ISSUE THREAD

**Issue by kesm** [Wox-launcher/Wox#79]
Like alfred it could be great to hide wox window if user clicks anywhere else than wox

**Comment by JohnTheGr8** [comment]
This has already been suggested (#65) and implemented (36f3c293f08f608d922477ffdc033670ad8db4fc).

**Comment by qianlifeng** [comment]
As @JohnTheGr8 said, this has been implemented, pls find the option in setting panel.
