### ISSUE TITLE
Fonts in Theme's dropdown all unordered

### ISSUE THREAD

**Issue by S-ed** [Wox-launcher/Wox#790]
Wox 1.3.67

![screenshot 1466597454](https://cloud.githubusercontent.com/assets/3008353/16266067/a6f84cc2-388b-11e6-8ecf-156ebba5a9aa.png)

Hope it's not supposed to be that way.

**Comment by bao-qian** [comment]
Assorted ? Could you explain it in detail?

**Comment by S-ed** [comment]
Assorted means - unordered.
Should be A-B-C-D-E-F-G...not S-K-S-M-B-S-L-P-M-F-C-A-J...
That's how it supposed to be:

![screenshot 1466598289](https://cloud.githubusercontent.com/assets/3008353/16266430/7f398780-388d-11e6-9147-ec0ffb8b733b.png)

**Comment by bao-qian** [comment]
Oh thanks

**Comment by S-ed** [comment]
No problem.
Sorry for misunderstanding.

**Comment by bao-qian** [comment]
check again
https://ci.appveyor.com/project/happlebao/wox/build/1.3.373/artifacts
