### ISSUE TITLE
中国用户进来报下网速

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#792]
1. 地区 + 运营商
2. `ping github-cloud.s3.amazonaws.com` 结果
3. 下 [release](https://github.com/Wox-launcher/Wox/releases) 里面东西的速度 （kb/s）
4. 下 [update](https://github.com/Wox-launcher/Wox/releases/download/v1.3.67/Wox-1.3.67-full.nupkg) 所需要的时间
5. `ping github.com` 结果
6. `ping 107.170.225.193` 结果

如果实在所有人都很慢的话，我会考虑开 CDN

**Comment by 1989car** [comment]
-  地区 + 运营商
  北京联通
-  ping github-cloud.s3.amazonaws.com 结果

```
正在 Ping s3-1-w.amazonaws.com [54.231.50.26] 具有 32 字节的数据:
来自 54.231.50.26 的回复: 字节=32 时间=252ms TTL=34
来自 54.231.50.26 的回复: 字节=32 时间=253ms TTL=34
来自 54.231.50.26 的回复: 字节=32 时间=252ms TTL=34
来自 54.231.50.26 的回复: 字节=32 时间=252ms TTL=34
```
- 下 release 里面东西的速度 （kb/s）

无法下载
-  下 update 所需要的时间

无法下载
- ping github.com 结果

```

正在 Ping github.com [192.30.252.129] 具有 32 字节的数据:
来自 192.30.252.129 的回复: 字节=32 时间=265ms TTL=46
来自 192.30.252.129 的回复: 字节=32 时间=265ms TTL=46
来自 192.30.252.129 的回复: 字节=32 时间=267ms TTL=46
来自 192.30.252.129 的回复: 字节=32 时间=265ms TTL=46

192.30.252.129 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 265ms，最长 = 267ms，平均 = 265ms
```
- ping 107.170.225.193 结果

```

正在 Ping 107.170.225.193 具有 32 字节的数据:
来自 107.170.225.193 的回复: 字节=32 时间=242ms TTL=51
请求超时。
来自 107.170.225.193 的回复: 字节=32 时间=236ms TTL=51
来自 107.170.225.193 的回复: 字节=32 时间=236ms TTL=51

107.170.225.193 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 236ms，最长 = 242ms，平均 = 238ms
```

**Comment by ousui** [comment]
北京，公司集团网，限制网速 512KB/s

```
正在 Ping s3-1-w.amazonaws.com [54.231.120.187] 具有 32 字节的数据: 
来自 54.231.120.187 的回复: 字节=32 时间=260ms TTL=28               
来自 54.231.120.187 的回复: 字节=32 时间=260ms TTL=28               
来自 54.231.120.187 的回复: 字节=32 时间=259ms TTL=28               
来自 54.231.120.187 的回复: 字节=32 时间=259ms TTL=28               
```

公司下载国外网站东西基本就是不动。

```
正在 Ping github.com [192.30.252.131] 具有 32 字节的数据:
来自 192.30.252.131 的回复: 字节=32 时间=256ms TTL=37    
来自 192.30.252.131 的回复: 字节=32 时间=255ms TTL=37    
来自 192.30.252.131 的回复: 字节=32 时间=254ms TTL=37    
来自 192.30.252.131 的回复: 字节=32 时间=259ms TTL=37    
```

```
正在 Ping 107.170.225.193 具有 32 字节的数据:
来自 107.170.225.193 的回复: 字节=32 时间=168ms TTL=43
来自 107.170.225.193 的回复: 字节=32 时间=175ms TTL=43
来自 107.170.225.193 的回复: 字节=32 时间=170ms TTL=43
来自 107.170.225.193 的回复: 字节=32 时间=162ms TTL=43
```

**Comment by jingouwangzi** [comment]
1、地区 + 运营商
武汉电信单位网络，50M带宽，无限速
2、ping github-cloud.s3.amazonaws.com 结果
正在 Ping s3-1-w.amazonaws.com [54.231.49.138] 具有 32 字节的数据:
来自 54.231.49.138 的回复: 字节=32 时间=345ms TTL=34
来自 54.231.49.138 的回复: 字节=32 时间=344ms TTL=34
来自 54.231.49.138 的回复: 字节=32 时间=344ms TTL=34
来自 54.231.49.138 的回复: 字节=32 时间=344ms TTL=34

54.231.49.138 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 344ms，最长 = 345ms，平均 = 344ms
3、下 release 里面东西的速度 （kb/s）
下载python3.5.1，200KB/s慢慢升到600KB/s下载完成。
4、下 update 所需要的时间
100KB/s升到400KB/s下载完成
5、ping github.com 结果
正在 Ping github.com [204.13.251.16] 具有 32 字节的数据:
来自 204.13.251.16 的回复: 字节=32 时间=238ms TTL=46
来自 204.13.251.16 的回复: 字节=32 时间=237ms TTL=46
来自 204.13.251.16 的回复: 字节=32 时间=238ms TTL=46
来自 204.13.251.16 的回复: 字节=32 时间=238ms TTL=46

204.13.251.16 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 237ms，最长 = 238ms，平均 = 237ms
6、ping 107.170.225.193 结果
正在 Ping 107.170.225.193 具有 32 字节的数据:
来自 107.170.225.193 的回复: 字节=32 时间=196ms TTL=47
来自 107.170.225.193 的回复: 字节=32 时间=195ms TTL=47
来自 107.170.225.193 的回复: 字节=32 时间=197ms TTL=47
来自 107.170.225.193 的回复: 字节=32 时间=195ms TTL=47

107.170.225.193 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 195ms，最长 = 197ms，平均 = 195ms

**Comment by jhdxr** [comment]
地区 + 运营商
江苏联通

ping github-cloud.s3.amazonaws.com 结果
Pinging github-cloud.s3.amazonaws.com [54.231.34.41] with 32 bytes of data:
Reply from 54.231.34.41: bytes=32 time=229ms TTL=34
Reply from 54.231.34.41: bytes=32 time=225ms TTL=34
Reply from 54.231.34.41: bytes=32 time=229ms TTL=34
Reply from 54.231.34.41: bytes=32 time=230ms TTL=34

Ping statistics for 54.231.34.41:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 225ms, Maximum = 230ms, Average = 228ms

下 release 里面东西的速度 （kb/s）
无法下载

下 update 所需要的时间
无法下载

ping github.com 结果
Pinging github.com [192.30.252.129] with 32 bytes of data:
Reply from 192.30.252.129: bytes=32 time=336ms TTL=52
Reply from 192.30.252.129: bytes=32 time=326ms TTL=52
Reply from 192.30.252.129: bytes=32 time=329ms TTL=52
Reply from 192.30.252.129: bytes=32 time=336ms TTL=52

Ping statistics for 192.30.252.129:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 326ms, Maximum = 336ms, Average = 331ms

ping 107.170.225.193 结果
Pinging 107.170.225.193 with 32 bytes of data:
Reply from 107.170.225.193: bytes=32 time=231ms TTL=52
Reply from 107.170.225.193: bytes=32 time=239ms TTL=52
Reply from 107.170.225.193: bytes=32 time=243ms TTL=52
Reply from 107.170.225.193: bytes=32 time=243ms TTL=52

Ping statistics for 107.170.225.193:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 231ms, Maximum = 243ms, Average = 239ms

此外，ci中的构建产物可以很顺畅的下载（我现在也一般直接用它），另外我使用了 racaljk/hosts 用来避免某些干扰措施

**Comment by ygxxii** [comment]
- 地区 + 运营商
  江西南昌，移动校园网
- ping github-cloud.s3.amazonaws.com 结果

```
Pinging s3-1-w.amazonaws.com [54.231.13.1] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 54.231.13.1:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
- 下 release 里面东西的速度 （kb/s）
  无法下载
- ping github.com 结果

```
Pinging github.com [192.30.252.130] with 32 bytes of data:
Reply from 192.30.252.130: bytes=32 time=253ms TTL=50
Reply from 192.30.252.130: bytes=32 time=252ms TTL=50
Reply from 192.30.252.130: bytes=32 time=257ms TTL=50
Reply from 192.30.252.130: bytes=32 time=256ms TTL=50

Ping statistics for 192.30.252.130:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 252ms, Maximum = 257ms, Average = 254ms
```
- ping 107.170.225.193 结果

```
Pinging 107.170.225.193 with 32 bytes of data:
Reply from 107.170.225.193: bytes=32 time=199ms TTL=48
Reply from 107.170.225.193: bytes=32 time=199ms TTL=48
Reply from 107.170.225.193: bytes=32 time=199ms TTL=48
Reply from 107.170.225.193: bytes=32 time=200ms TTL=48

Ping statistics for 107.170.225.193:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 199ms, Maximum = 200ms, Average = 199ms
```

**Comment by ghost** [comment]
## 地区 + 运营商

四川南充，电信100M

## ping github-cloud.s3.amazonaws.com 结果

Server deng$ ping -c 4 github-cloud.s3.amazonaws.com
PING s3-1-w.amazonaws.com (54.231.33.155): 56 data bytes
64 bytes from 54.231.33.155: icmp_seq=0 ttl=37 time=293.075 ms
64 bytes from 54.231.33.155: icmp_seq=1 ttl=37 time=428.420 ms
Request timeout for icmp_seq 2
64 bytes from 54.231.33.155: icmp_seq=2 ttl=37 time=1138.439 ms
64 bytes from 54.231.33.155: icmp_seq=3 ttl=37 time=960.279 ms

--- s3-1-w.amazonaws.com ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 293.075/705.053/1138.439/353.276 ms

建议换成韩国节点吧。我用的AWS的韩国和日本的节点。ping基本在120左右。。

**Comment by bao-qian** [comment]
十分感谢
以后更新会在百度云盘丢一份
不过要手动下，只会有提示。。。
中国区的自动更新就从长再议了。。。
