### ISSUE TITLE
Can't find Microsoft Edge when searching

### ISSUE THREAD

**Issue by nolanlawson** [Wox-launcher/Wox#797]
Thanks for a great project. I'm a big fan! However, I wish I could launch Edge using Wox.

![wox](https://cloud.githubusercontent.com/assets/283842/16287516/a514d9fe-3898-11e6-8069-80c9afc6e1b8.png)
- Wox version: 1.3.67
- Steps to reproduce: type "Edge". Notice nothing shows up.
- Windows 10 1607 14366.0

**Comment by bao-qian** [comment]
wow, thanks
I'm working on uwp support now, should be available before end of this week.

**Comment by bao-qian** [comment]
use #198
