### ISSUE TITLE
select all text when wox is visible is not working

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#801]
os: win7
wox: 1.3.183

**Comment by bao-qian** [comment]
can't reproduce now....

**Comment by Pimmetje** [comment]
I have a issue is will not select my last text when i reopen the window by hotkey. So i have to backspace it before i can use a new one. Is this the same issue as u have?

Edit:
I can reproduce it. When i change the hotkey it won't select the text when i try to launch something. Restarting Wox seems to fix the issue. Somehow the the changing/registering of the hotkey seems to fail on change.

**Comment by bao-qian** [comment]
update:
> When i change the hotkey it won't select the text when i try to launch something. 

this is because there are multiple `SetHotkey`, and `LastQuerySelected` is not updated when hot key is chaned.

> Somehow the the changing/registering of the hotkey seems to fail on change.

do you mean you can't change hot key after restart wox?

try https://ci.appveyor.com/project/happlebao/wox/build/1.3.342 anyway, there is one more option to empty last command / query
@Pimmetje

**Comment by bao-qian** [comment]
reopen if somebody can reproduce it
