### ISSUE TITLE
Hide Wox when focus is lost

### ISSUE THREAD

**Issue by Leandros** [Wox-launcher/Wox#805]
If Wox looses focus to the Windows taskbar, it's not hiding itself.

**Steps to reproduce:**
- Open Wox
- Click on the taskbar
- Wox is loosing focus, but still visible

Wox Version: v1.3.183
Windows Version: Windows 8.1

**Comment by bao-qian** [comment]
There is a option in the settings "hide wox when lost focus". Did you check that?

**Comment by Leandros** [comment]
Yes. It's working, as long as it looses focus to another window, but not generally.
It's creating all sorts of issues with multimonitor setups.

**Comment by lances101** [comment]
@Leandros, cannot reproduce your issue on a Windows 8.1 VM with Wox 1.3.183. 

As long as the option is enabled alt+tabbing or clicking on a different window (and windows taskbar) makes Wox lose focus, fire a deactivated event and then hide. 

I've made a build that also listens for LostFocus events, [could you please try it?](https://github.com/lances101/Wox/releases/download/1.3.183-bf-805-001/1.3.183-bf-805-001.zip)

**Comment by Leandros** [comment]
Ok, did some investigations and yes, it's working as you describe if all the actions happen on the same monitor. Only if I activate Wox on one monitor, and then lose focus to the windows taskbar on the other monitor, Wox is not dismissed.
In fact, it's never losing focus to a window on another monitor.

**Comment by bao-qian** [comment]
still can't reproduce it.
could you upload  a video?
