### ISSUE TITLE
wox 开机启动出现这个错误

### ISSUE THREAD

**Issue by finalghoul** [Wox-launcher/Wox#806]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 06/25/2016 22:37:46
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
重开 wox 就好了

**Comment by bao-qian** [comment]
有问题再开
