### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by yxhlcl** [Wox-launcher/Wox#808]
我的版本是：Wox-1.3.183。今天开机，wox没有启动，手动运行也不能启动，没有任何反应。通过控制面板卸载，也没有反应，无法卸载。重新安装，提示错误：
![Uploading 20160626193637.jpg…]()

**Comment by bao-qian** [comment]
你发了以后看一眼啊，错误是啥？

**Comment by yxhlcl** [comment]
上传不了附件，发图片链接：http://image18-c.poco.cn/mypoco/myphoto/20160627/09/17931813820160627094807054.jpg?366x183_120
log文件也没有新的内容

**Comment by yxhlcl** [comment]
有没有什么运行参数可以打开异常输出的

**Comment by bao-qian** [comment]
这是安装包错误
你点那个 open setup log 啊…

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
打开的日志文件，什么都没有，前面已经说了

**Comment by yxhlcl** [comment]
重新下载了百度云上的安装包，也是一样

**Comment by bao-qian** [comment]
看一下有没有一个文件叫 `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`
如果有 
1. 删除 `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`
2. 安装
3. 上传 `%LOCALAPPDATA%\SquirrelTemp\SquirrelSetup.log`

**Comment by bao-qian** [comment]
有问题再开
