### ISSUE TITLE
Could't find python environment, all python plugins disabled.

### ISSUE THREAD

**Issue by fzxing** [Wox-launcher/Wox#81]
Wox is a nice and customizable app.
It works well using existing c# plugins, but there are some problems when using python's. When wox starting, there is a log in log.txt: 
Level：WARN  Msg：Could't find python environment, all python plugins disabled.

i have installed python27 from official website, and set eviroment variable "Path".
my os is win7-64,  not install visual-studio and any other windows dev tools
wox version is 1.0.0.119

**Comment by qianlifeng** [comment]
did you install the python x64? You should install x64 python when your os is win7-64.

**Comment by fzxing** [comment]
yes, after installing python_x64, it works, thank you
