### ISSUE TITLE
Cursor position jumps to end / 光标会自动移动到查询框最后

### ISSUE THREAD

**Issue by eight04** [Wox-launcher/Wox#813]
Type some text in Input field:
`abc<home>123`
Expect:
`123|abc`
Result:
`1abc23|`

Wox 1.3.183
Windows 7 x64

**Comment by bao-qian** [comment]
@eight04 @roose  @shayneholmes
fixed, try again: https://ci.appveyor.com/project/happlebao/wox/build/1.3.202/artifacts

**Comment by eight04** [comment]
Confirmed the fix :+1:
