### ISSUE TITLE
Wox 1.3.183 有道插件没法正常使用

### ISSUE THREAD

**Issue by skefy** [Wox-launcher/Wox#814]
wox版本：1.3.183
有道插件版本：1.1.0
截图：
![qq 20160629110318](https://cloud.githubusercontent.com/assets/4201208/16439262/3d33f742-3de9-11e6-8723-a36abb4ed125.png)

**Comment by jhdxr** [comment]
原来我不是一个人。。。

**Comment by jhdxr** [comment]
https://github.com/Wox-launcher/Wox/commit/d739920462b14c5eb41e54cb1f4fd4b46ca7874a#diff-e6f935e35d6c8bf13dd2c7aaa90390a9L12
这个提交导致了
https://github.com/Wox-launcher/Wox.Plugin.Youdao/blob/master/Main.cs#L48
会无法执行

@happlebao 我看你在wox项目里的修复是简单的去除了proxy的设置，这是否会导致代理功能不可用？还是有其他实现方式？另外还是麻烦发个新版修复一下吧

**Comment by bao-qian** [comment]
不好意思，手误忘改了。。。
已更新插件
wpm install yd
