### ISSUE TITLE
Submitting a plugin

### ISSUE THREAD

**Issue by breisfeld** [Wox-launcher/Wox#818]
I am having a problem submitting a plugin via http://www.getwox.com/plugin/create

My top-level directory is `Wox.Plugin.MyPlugin` and underneath that I have 
- `Images/`
- `plugin.json`
- `myplugin.py`
- `wox.py`

When I drag the directory onto the `Attach Plugin by dropping it here or Choose Fileselecting Plugin` box and click `Submit`, I get an error:

`Invalid plugin file. Wox plugin should end with .wox`

What director structure or format should be used to submit a plugin?

Thanks. 

~BR

**Comment by lances101** [comment]
A .wox is a .zip with a changed extension. Just zip your plugin, rename and
you should be fine : )

**Comment by bao-qian** [comment]
![image](https://cloud.githubusercontent.com/assets/1169912/16542479/0b969ab2-40a2-11e6-8473-2e157e52cb97.png)

**Comment by bao-qian** [comment]
close due to no response
