### ISSUE TITLE
Everything.dll 正由另一进程使用，因此该进程无法访问此文件。

### ISSUE THREAD

**Issue by iMactool** [Wox-launcher/Wox#819]
[以下是报错的信息。](url)
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/02/2016 09:25:53
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 53
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 144
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

everything 是每次开机都可以自动启动，但是wox不会，然后现在是手动点击 wox启动的时候就会报这个错误。
【Python 3.5.1 我的版本】

日志文件信息：

2016-07-02 09:25:52.2459|INFO|Wox.Plugin.Program.Main.Init|Preload 245 programs from cache
2016-07-02 09:25:52.2599|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:25:52.2879|ERROR|System.IO.__Error.WinIOError|文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
2016-07-02 09:25:52.3020|ERROR|System.IO.__Error.WinIOError|
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2016-07-02 09:25:52.3020|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:25:52.3020|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
2016-07-02 09:25:52.3315|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 53
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 144
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
2016-07-02 09:25:53.0951|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:25:53.0991|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|发生一个或多个错误。
2016-07-02 09:25:53.0991|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-07-02 09:25:53.0991|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
2016-07-02 09:25:53.0991|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 53
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 144
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-07-02 09:25:53.1131|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:25:53.1131|ERROR|System.Threading.Tasks.Parallel.ForWorker|发生一个或多个错误。
2016-07-02 09:25:53.1131|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-07-02 09:25:53.1281|ERROR|System.Threading.Tasks.Parallel.ForWorker|文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
2016-07-02 09:25:53.1281|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 53
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 144
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-07-02 09:25:53.1521|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.IO.IOException: 文件“C:\Users\Administrator\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll”正由另一进程使用，因此该进程无法访问此文件。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void WinIOError(Int32, System.String)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 Wox.Infrastructure.Helper.ValidateDataDirectory(String bundledDataDirectory, String dataDirectory) 位置 C:\projects\wox\Wox.Infrastructure\Helper.cs:行号 53
   在 Wox.Plugin.Everything.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Everything\Main.cs:行号 144
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: 发生一个或多个错误。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 94
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 53
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Wox.exe" 
- Timestamp: 07/02/2016 09:25:53
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Wox.exe)
- Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
- Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
- Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- Wox.Plugin.UrlEncode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Roaming\Wox\Plugins\Wox.Plugin.UrlEncode-de79a086-dc18-4d2e-9899-9023689d1ecb\Wox.Plugin.UrlEncode.dll)
- Wox.Plugin.Youdao, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Roaming\Wox\Plugins\有道翻译-1431da96-0f74-4972-8989-7c44ebe8e17e\Wox.Plugin.Youdao.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\NLog.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- PresentationCore.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)

2016-07-02 09:26:07.1109|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:26:07.1159|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|未设置应用程序标识。
2016-07-02 09:26:07.1159|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   在 System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
2016-07-02 09:28:10.8915|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:28:10.8965|ERROR|System.Number.ParseDouble|输入字符串的格式不正确。
2016-07-02 09:28:10.8965|ERROR|System.Number.ParseDouble|
   在 System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
2016-07-02 09:28:11.0883|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:28:11.0883|ERROR|System.Number.ParseDouble|输入字符串的格式不正确。
2016-07-02 09:28:11.0968|ERROR|System.Number.ParseDouble|
   在 System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
2016-07-02 09:28:11.2542|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-02 09:28:11.2542|ERROR|System.Number.ParseDouble|输入字符串的格式不正确。
2016-07-02 09:28:11.2542|ERROR|System.Number.ParseDouble|
   在 System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)

**Comment by bao-qian** [comment]
1. 你开机后检查一下有没有 wox 进程运行
2. 用 resource monitor 检查一下是哪个程序在使用这个 dll
   ![image](https://cloud.githubusercontent.com/assets/1169912/16542934/dec95e30-40b4-11e6-86e5-997f53f05181.png)
3. 上传 `%APPDATA%\Wox\Logs\1.3.183\2016-x-x.log`

**Comment by iMactool** [comment]
这里是第一次检查，
![cdjp 5z i55a5i 727 5r](https://cloud.githubusercontent.com/assets/3078413/16549413/c5c28a1a-41d1-11e6-92e1-3f1acec8f22d.jpg)

然后kill 前面那个之后，这张图是启动wox之后我这里显示的有两个进程
![kv6fl dvff c er 4 1im6](https://cloud.githubusercontent.com/assets/3078413/16549417/cc58317c-41d1-11e6-83aa-627bb3341561.jpg)

日志下面
[2016-07-04.txt](https://github.com/Wox-launcher/Wox/files/345442/2016-07-04.txt)

有
![t jw51mrj aosr3v errboy](https://cloud.githubusercontent.com/assets/3078413/16549490/50c5e7f6-41d2-11e6-9dda-bed9c7b01889.jpg)
设置了python 这个应该不影响吧

**Comment by iMactool** [comment]
还有一个问题， 插件好像可以重复安装？(显示上看一个是中文显示，一个是英文显示).
![image](https://cloud.githubusercontent.com/assets/3078413/16549535/d350cf10-41d2-11e6-9884-735029c3abf3.png)

**Comment by bao-qian** [comment]
问题就应该出在这两个 everything 上。。
应该只有一个。。
而且 everything 是自带的，何来重复安装之说。。

检查下面这两个地方是不是有 everything
1. `%LOCALAPPDATA%\Wox\app-1.3.183\Plugins`
2. `%APPDATA%\Wox\Plugins`

不会删就全删了，然后覆盖安装（设置还在）

**Comment by iMactool** [comment]
卸载wox,然后删除所有wox的文件，重新安装就没有问题了。

---

检查下面这两个地方是不是有 everything
1. %LOCALAPPDATA%\Wox\app-1.3.183\Plugins ==》现在是有
2. %APPDATA%\Wox\Plugins ===》现在没有

---

总之，感谢你的耐心解答~ :+1:
