### ISSUE TITLE
Wox.Plugin.Program System.NullReferenceException

### ISSUE THREAD

**Issue by iNostoc** [Wox-launcher/Wox#822]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/03/2016 08:42:47

```
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
```

突然打开就直接弹出错误信息，之前一直正常。

日志：

2016-07-03 09:01:20.5571|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:20.5571|ERROR|Wox.App.Dispose|未将对象引用设置到对象的实例。
2016-07-03 09:01:20.5571|ERROR|Wox.App.Dispose|
   在 Wox.App.Dispose() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 134
2016-07-03 09:01:20.5571|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:20.5571|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|未将对象引用设置到对象的实例。
2016-07-03 09:01:20.5571|ERROR|Wox.Helper.ErrorReporting.UnhandledExceptionHandle|
   在 Wox.Helper.ErrorReporting.UnhandledExceptionHandle(Object sender, UnhandledExceptionEventArgs e) 位置 C:\projects\wox\Wox\Helper\ErrorReporting.cs:行号 0
2016-07-03 09:01:32.7701|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|Python can't be found in PATH.
2016-07-03 09:01:32.7911|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|

2016-07-03 09:01:32.9211|INFO|Wox.Plugin.Program.Main.Init|Preload 0 programs from cache
2016-07-03 09:01:32.9306|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:32.9306|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|未将对象引用设置到对象的实例。
2016-07-03 09:01:32.9306|ERROR|Wox.Plugin.Program.Main.DefaultProgramSources|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
2016-07-03 09:01:32.9306|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:32.9306|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|未将对象引用设置到对象的实例。
2016-07-03 09:01:32.9306|ERROR|System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1.<ForWorker>b__1|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
2016-07-03 09:01:32.9929|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|发生一个或多个错误。
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|未将对象引用设置到对象的实例。
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Task.ThrowIfExceptional|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-07-03 09:01:32.9929|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Parallel.ForWorker|发生一个或多个错误。
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Parallel.ForWorker|未将对象引用设置到对象的实例。
2016-07-03 09:01:32.9929|ERROR|System.Threading.Tasks.Parallel.ForWorker|
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
2016-07-03 09:01:33.0134|FATAL|Wox.Helper.ErrorReporting.Report|
## Exception

```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   Source: Wox.Plugin.Program
   TargetAssembly: Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Wox.Plugin.Program.dll
   TargetSite: System.Collections.Generic.List`1[Wox.Plugin.Program.ProgramSource] DefaultProgramSources()
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Plugin.Program.Main.Init(PluginInitContext context) 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 94
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

System.AggregateException: 发生一个或多个错误。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void ThrowIfExceptional(Boolean)
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   在 System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   在 Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 94
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 53
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
## Environment
- Command Line: "C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Wox.exe" 
- Timestamp: 07/03/2016 09:01:33
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0
## Assemblies - Wox.exe
- Wox, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Wox.exe)
- Wox.Infrastructure, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Wox.Infrastructure.dll)
- Wox.Plugin, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Wox.Plugin.dll)
- Wox.Core, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Wox.Core.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.183.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- RemoveUSB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Roaming\Wox\Plugins\Remove USB-0104281d-8811-4274-8470-daadd47691dd\RemoveUSB.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\NLog.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Oubowen\AppData\Local\Wox\app-1.3.183\NHotkey.Wpf.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- PresentationCore.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)

**Comment by bao-qian** [comment]
看起来你解决了是吗？怎么解决的？

**Comment by iNostoc** [comment]
之前系统自带卸载后重装依然有同样的问题，但我用iobit uninstaller卸载后再清除关联文件后，重装就正常了。

happlebao notifications@github.com于2016年7月20日周三 上午8:28写道：

**Comment by bao-qian** [comment]
十分感谢
