### ISSUE TITLE
Position Reset .启动/查询 后位置自动恢复到起始位置 -v1.3.183

### ISSUE THREAD

**Issue by lqzhgood** [Wox-launcher/Wox#823]
# English

When input or start , Wox will be reset position in screen, regardless of the _‘Remember last launch location’_ selected.

setting.json  >   _"WindowLeft": 0.0,_  _"WindowTop": 0.0,_  Not change
# 中文
1. wox版本 1.3.183
2. 无论设置里面是否勾选 “记住上次的位置”， 移动WOX位置以后， 只要输入（例如hc） 或者下次启动，都会自动恢复到屏幕的初始位置（大概在屏幕中央）。
3. windows7 (VM 虚拟机里面特意创建的一个MSDN纯净版本)
4.  
5.  日志没有显示错误

setting.json 中的 _"WindowLeft": 0.0,_  _"WindowTop": 0.0,_ 这两项不会有改变。如果直接Setting.json中修改这两项为 _"WindowLeft": 100.100,_  _"WindowTop": 100.100,_ 也不会改变初始位置。应该是这两项没有生效的缘故

**Comment by bao-qian** [comment]
修完了，试一下： https://ci.appveyor.com/project/happlebao/wox/build/1.3.202/artifacts

**Comment by shayneholmes** [comment]
Checked 1.3.202, bug still present.

**Comment by ghost** [comment]
1.3.202，问题依旧。

**Comment by a5066987** [comment]
1.3.243也有这个问题

**Comment by davidszp** [comment]
I have this problem with 1.3.183

**Comment by Vanav** [comment]
If I move Wox window, then type some characters (e.g. a calculator expression), Wox window will sometimes jump to the center of screen. Windows should always remember its position, if moved manually. Confirmed in v1.3.324.
Possible duplicate: #1172.

**Comment by bao-qian** [comment]
@lqzhgood @shayneholmes @rocalker @a5066987 @makloda @Vanav 
try new build https://ci.appveyor.com/project/happlebao/wox/build/1.3.352/artifacts

**Comment by bao-qian** [comment]
reopen if issue still exist

**Comment by specter119** [comment]
@bao-qian I think it still exists, 1.3.524

**Comment by lqzhgood** [comment]
@bao-qian it still exists, 1.3.524

**Comment by fofolee** [comment]
@bao-qian it still exists, 1.3.578

**Comment by dx838** [comment]
1.3.578 还是会复位。
