### ISSUE TITLE
启动顺序人工置顶/人工调整启动顺序权重/人工调整启动顺序

### ISSUE THREAD

**Issue by cntjww** [Wox-launcher/Wox#824]
1. 请提供 Wox 版本
   - 当前Release版本
2. 请提供如何**重现** bug 的步骤
   - 启动顺序权重
   - 文档里写着：Wox搜索列表中的每一项都有自己的权重值。每次选择一项后，该项的权重会增大。这样下次再次搜索此项的时候，该项将会优先显示在列表前面。
   - 但是这样需要重复很多次才行，最好能人工置顶，一次就可以了
3. 请提供 Windows 版本
   - 不重要，但是当前是Win10
4. 如果有 Exception/Crash Report 的话，请一并提供
   - NA
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
   - NA
6. 如果有截图的话，请一并提供
   -NA

**Comment by bao-qian** [comment]
邮件 \ ctrl+o \ shift + enter 有一个置顶选项

**Comment by cntjww** [comment]
shift + enter works, but when enter "shift+enter" mode, it need to click "shift+enter" again to enter normal mode, I think it is not a good featuer, maybe a bug.

And, I do not know what ctrl+o is, I enter the key, nothing happens...

**Comment by bao-qian** [comment]
这不是 bug。。
你还可以按 esc 退出。。
