### ISSUE TITLE
Feature request: Add possibility to load icons from URL

### ISSUE THREAD

**Issue by skttl** [Wox-launcher/Wox#829]
In stead of loading icons from the filesystem, it would be cool to be able to load them from a URL.

Then we can make better plugins for websearch, like on youtube or sites like that.

**Comment by Megasware128** [comment]
What I did was caching the icon manually (even did some conversion for svg) and give Wox the file on disk, you can see this happening in my repo [Wox.Plugin.Choco](https://github.com/Megasware128/Wox.Plugin.Choco). But yes, it would be useful if Wox could automate this process

**Comment by skttl** [comment]
I did the same for my Giphy plugin.

man. 18. jul. 2016 kl. 10.08 skrev Jordy Hulck notifications@github.com:
