### ISSUE TITLE
Question: Value of "maximum results shown"

### ISSUE THREAD

**Issue by skttl** [Wox-launcher/Wox#832]
Is it possible to reference the users "maximum results hown" setting in a plugin?

**Comment by bao-qian** [comment]
not possible, and why you want to use it?

**Comment by skttl** [comment]
For a search plugin I'm working on. Say the user has a maximum of 10, then I want the first 9 results to come from the search engine, and the last to be a link to the full search results page.

Are there other ways this can be done?

**Comment by bao-qian** [comment]
1. manually read settings from `%APPDATA%\Wox\Settings\Setting` or
2. give user a option to set how many results they want to have. Default value should be 5 since default maximum results for wox is 6.

**Comment by bao-qian** [comment]
close due to no response

**Comment by skttl** [comment]
Sorry for the missing response. I think your first suggestion is fine, thanks!
