### ISSUE TITLE
Squirrel.UpdateManager.d__2b.MoveNext()

### ISSUE THREAD

**Issue by li7nux** [Wox-launcher/Wox#835]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/06/2016 09:22:10
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2016-07-06.txt](https://github.com/Wox-launcher/Wox/files/348918/2016-07-06.txt)

**Comment by bao-qian** [comment]
这是因为自动更新用到了 github release，但是它被墙了。。。
以后会用自己的服务器
可在 setting 中设置 http 代理
或者关闭自动更新
或者忽略
