### ISSUE TITLE
App crashes on search for "*.png"

### ISSUE THREAD

**Issue by acid7331** [Wox-launcher/Wox#836]
Wox version: 1.3.67
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 07/06/2016 22:52:24
Exception:

System.Runtime.InteropServices.COMException
HRESULT: 0x88982F50

i searched for "*.png" and the app crashed
issue: http://pastebin.com/EHexK2S0

**Comment by bao-qian** [comment]
this is because there are some broken pngs in your computer
use latest [183](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183) version
the latest version will auto ignore it
