### ISSUE TITLE
unsing a builded theme wox crushed

### ISSUE THREAD

**Issue by pavonz** [Wox-launcher/Wox#838]
[2016-07-07.txt](https://github.com/Wox-launcher/Wox/files/352349/2016-07-07.txt)

**Comment by bao-qian** [comment]
1. which theme?
2. try reinstall wox
   1. delete `%LOCALAPPDATA%\Wox\app-1.3.183\Themes` 
   2. uninstall wox
   3. install wox again

**Comment by bao-qian** [comment]
close due to no response
