### ISSUE TITLE
How to publish plugin?

### ISSUE THREAD

**Issue by jardicc** [Wox-launcher/Wox#839]
I did URL shortener plugin. I want share code and publish it. It works for me, but it's done from 80-90% some bugs can appear and some improvements would be nice. But I don't want care about my code. A repair it and maintain it. Anyway, it is not complicated. I use Yourls API. https://yourls.org/#API You must have access to Yourls API if you want use it.

What should I do?

Plugin reads directly from clipboard. No ctrl+c, ctrl+v needed. You can choose custom keyword. If keyword is already in use, you get statistics for it and posibility get long/short url.

![image](https://cloud.githubusercontent.com/assets/13526959/16668485/7aba0fda-4491-11e6-83a2-9bc18a0c9c1c.png)

![image](https://cloud.githubusercontent.com/assets/13526959/16668490/7e73618a-4491-11e6-96da-bdee3a51bf76.png)

**Comment by jhdxr** [comment]
you can publish your plugin here: http://www.getwox.com/#plugin

**Comment by bao-qian** [comment]
seems resolved?

**Comment by jardicc** [comment]
I am programmer noob. I am no sure. Maybe I will need help.

**Comment by bao-qian** [comment]
so what kind of help you need now?

**Comment by jardicc** [comment]
Sorry I am bussy right now... I will do it later

**Comment by bao-qian** [comment]
no worries

**Comment by bao-qian** [comment]
close due to no response
