### ISSUE TITLE
Failed to install a plugin using a wpm install ...

### ISSUE THREAD

**Issue by omer727** [Wox-launcher/Wox#842]
When I try to search and install a plugin using wpm it failed.
I get the following message in the log.txt

Date:2016-07-09 12:30:28,024 Level:ERROR Msg:Plugin Wox Plugin Management query failed: The underlying connection was closed: An unexpected error occurred on a send

wox version 1.1.1
Windows 7 - no proxy

**Comment by bao-qian** [comment]
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183
