### ISSUE TITLE
Wox 1.3.183 no results

### ISSUE THREAD

**Issue by taolive** [Wox-launcher/Wox#843]
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   -  1.3.183
2. 请提供如何**重现** bug 的步骤
   - 全新安装后
   - 开始几次可以输入Settings或其他关键字，进行搜索
   - 重启机器后（也不知道是不是重启的原因），输入Settings、> cmd 或其他关键字，wox没显示任何结果（python、Search Everything，都已经安装）
   - 查看：SquirrelSetup.log 日志文件，里面没任何输出异常，以及打开Wox的设置窗口，点击里面任一模块，都是正常的
3. 请提供 Windows 版本
   - Win10 14383 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

**Comment by taolive** [comment]
![1](https://cloud.githubusercontent.com/assets/1654524/16707474/95b7cec8-4601-11e6-9124-4493e9c0a528.jpg)

**Comment by jhdxr** [comment]
这个我也遇到过，并没有找到复现规律/去进行调试，退出wox重新打开一般可以活过来。。。

**Comment by taolive** [comment]
@jhdxr 有时碰到，重新打开或重装都没用，必须把所有wox相关的缓存或配置文件，全部删除后，再重装，才有可能解决

**Comment by bao-qian** [comment]
@taolive 

> 如果有 logs （%APPDATA%\Wox\Logs）的话，请一并提供

那么你的 log 呢。。。。？

**Comment by samuel-xie** [comment]
我今天也遇到类似的问题。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
