### ISSUE TITLE
Object reference not set to an instance of an object. at Wox.Plugin.Program.Main.DefaultProgramSources() 

### ISSUE THREAD

**Issue by Beyarz** [Wox-launcher/Wox#844]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/09/2016 16:42:08
Exception:
Wox.Plugin.Program
System.NullReferenceException
Objektreferensen har inte angetts till en instans av ett objekt.
   vid Wox.Plugin.Program.Main.DefaultProgramSources() i C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:rad 136
   vid Wox.Plugin.Program.Main.IndexPrograms() i C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:rad 102
   vid Wox.Plugin.Program.Main.Init(PluginInitContext context) i C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:rad 94
   vid Wox.Infrastructure.Stopwatch.Normal(String name, Action action) i C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:rad 27
   vid Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) i C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:rad 96
   vid System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   vid System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   vid System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by Beyarz** [comment]
My guess is that my antivirus is behind this problem, not sure.
I'll come back when it is confirmed.

**Comment by bao-qian** [comment]
whole log please if confirmed it
`%APPDATA%\Wox\Logs\1.3.183\log`

**Comment by bao-qian** [comment]
try delete `%APPDATA%\Wox\Cache`

**Comment by bao-qian** [comment]
close due to no response
