### ISSUE TITLE
System.InvalidOperationException 只能在按下主鼠标按钮时调用 DragMove。 在 System.Windows.Window.DragMove()

### ISSUE THREAD

**Issue by Junyi-99** [Wox-launcher/Wox#845]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   - If you checkout from master/dev branch, please specify **commit number**
2. Please describe the steps to **reproduce** the bug
3. Please provide Windows version
4. Please provide Exception info if you have.
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
2. 请提供如何**重现** bug 的步骤
3. 请提供 Windows 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供
   [2016-07-11.txt](https://github.com/Wox-launcher/Wox/files/356088/2016-07-11.txt)

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/11/2016 00:02:31
Exception:
PresentationFramework
System.InvalidOperationException
只能在按下主鼠标按钮时调用 DragMove。
   在 System.Windows.Window.DragMove()
   在 Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 109
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

重现：我双击了一个不存在的快捷方式。

**Comment by HustLion** [comment]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: **Log文件附在后面**
2. copy below exception message
Wox version: 1.3.67
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/19/2016 20:22:46
Exception:
PresentationFramework
System.InvalidOperationException
只能在按下主鼠标按钮时调用 DragMove。
   在 System.Windows.Window.DragMove()
   在 Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 157
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Log文件内容：

2016-07-19 20:22:46.1435|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-19 20:22:46.1705|ERROR|System.Windows.Window.DragMove|只能在按下主鼠标按钮时调用 DragMove。
2016-07-19 20:22:46.2035|ERROR|System.Windows.Window.DragMove|
   在 System.Windows.Window.DragMove()
2016-07-19 20:22:46.5248|FATAL|Wox.Helper.ErrorReporting.Report|

## Exception

```
System.InvalidOperationException: 只能在按下主鼠标按钮时调用 DragMove。
   Source: PresentationFramework
   TargetAssembly: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationFramework.dll
   TargetSite: Void DragMove()
   在 System.Windows.Window.DragMove()
   在 Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 157
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
- Command Line: "C:\Users\rares\AppData\Local\Wox\app-1.3.67\Wox.exe" 
- Timestamp: 2016-07-19T20:22:46.4977744+08:00
- IntPtr Length: 8
- System Version: Microsoft Windows NT 10.0.10586.0
- CLR Version: 4.0.30319.42000
- Installed .NET Framework: 
  - v2.0.50727 2.0.50727.4927 SP2
  - v3.0 3.0.30729.4926 SP2
  - v3.5 3.5.30729.4926 SP1
  - v4 Client 4.6.01038
  - v4 Full 4.6.01038
  - v4.0 Client 4.0.0.0

## Assemblies - Wox.exe
- Wox, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Wox.exe)
- Wox.Infrastructure, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Wox.Infrastructure.dll)
- Wox.Core, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Wox.Core.dll)
- Wox.Plugin, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Wox.Plugin.dll)
- Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Newtonsoft.Json.dll)
- HelloWorldCSharp, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
- Wox.Plugin.Caculator, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
- YAMP, Version=1.4.0.22422, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Caculator\YAMP.dll)
- Wox.Plugin.Color, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
- Wox.Plugin.ControlPanel, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
- Wox.Plugin.Everything, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
- Wox.Plugin.Folder, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
- Wox.Plugin.PluginIndicator, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
- Wox.Plugin.PluginManagement, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
- Wox.Plugin.Program, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
- Wox.Plugin.Shell, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\rares\AppData\Local\Wox\app-1.3.67\WindowsInput.dll)
- Wox.Plugin.Sys, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
- Wox.Plugin.Url, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
- Wox.Plugin.WebSearch, Version=1.3.67.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
- NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\NHotkey.dll)
- NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\NHotkey.Wpf.dll)
- NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\rares\AppData\Local\Wox\app-1.3.67\NLog.dll)
- Squirrel, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Squirrel.dll)
- Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Splat.dll)
- Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (dynamic assembly doesn't has location)
- NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\NuGet.Squirrel.dll)
- Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\rares\AppData\Local\Wox\app-1.3.67\Pinyin4Net.dll)
- mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
- PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
- System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
- PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
- System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
- System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
- System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
- System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
- System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
- System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- PresentationCore.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll)
- PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
- System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
- System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll)
- PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
- PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)
- PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
- System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.resources.dll)
- UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
- mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)
- System.Net.Http.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.resources\v4.0_4.0.0.0_zh-Hans_b03f5f7f11d50a3a\System.Net.Http.resources.dll)
- System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
- System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll)
- UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
- Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll)

2016-07-19 20:23:12.6784|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-19 20:23:12.6784|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|未设置应用程序标识。
2016-07-19 20:23:12.6784|ERROR|System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment|
   在 System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
2016-07-19 20:24:14.8437|ERROR|Wox.App+<>c.<RegisterAppDomainExceptions>b__13_0|First Chance Exception:
2016-07-19 20:24:14.8848|ERROR|System.Number.ParseDouble|输入字符串的格式不正确。
2016-07-19 20:24:14.8848|ERROR|System.Number.ParseDouble|
   在 System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)

**Comment by bao-qian** [comment]
1. 截图
2. 你按的是哪个选项？

**Comment by bao-qian** [comment]
although there is no workaround now, but this issue is repeated: #811
