### ISSUE TITLE
wox quit silently without exception pop up

### ISSUE THREAD

**Issue by sxdxyxy** [Wox-launcher/Wox#848]
## English

Before you report any bugs try search existing issues
1. Please specify Wox version
   - If you checkout from master/dev branch, please specify **commit number**
2. Please describe the steps to **reproduce** the bug
3. Please provide Windows version
4. Please provide Exception info if you have.
5. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.
6. Please provide screenshot if you have
## 中文 / Chinese

windows 10 下面经常不正常的退出，原因不明。

版本wox 1.3.183,
windows 10 

报 bug 之前搜索一下已经有的 issue
1. 请提供 Wox 版本
   - 如果你是从 master/dev branch checkout 的，请提供 **commit number**
2. 请提供如何**重现** bug 的步骤
3. 请提供 Windows 版本
4. 如果有 Exception/Crash Report 的话，请一并提供
5. 如果有 **logs** （`%APPDATA%\Wox\Logs`）的话，请一并提供
6. 如果有截图的话，请一并提供

**Comment by bao-qian** [comment]
不正常退出的时候肯定有 报错 窗口的。。
截个图啊。。

**Comment by jingouwangzi** [comment]
也会遇到这个问题，没有报错窗口，等发现的时候，wox已经不见了

**Comment by bao-qian** [comment]
@jingouwangzi 
遇到这个问题的时候
1. 看一下时间然后告诉我
2. 然后上传 `%APPDATA%\Wox\Logs\1.3.183\date.log`

**Comment by f12998765** [comment]
@happlebao 

Win 10 ，Wox-1.3.183，更换自定义主题，不正常退出了。

**Logs：**[http://showtxt.cn/clar3](http://showtxt.cn/clar3)

**exception message：**

```
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/25/2016 22:39:24
Exception:
PresentationCore
System.FormatException
不允许空字符串。
   在 MS.Internal.Parsers.ParseBrush(String brush, IFormatProvider formatProvider, ITypeDescriptorContext context)
   在 System.Windows.Media.Brush.Parse(String value, ITypeDescriptorContext context)
   在 System.Windows.Setter.System.ComponentModel.ISupportInitialize.EndInit()
   在 MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
```

**Comment by bao-qian** [comment]
@f12998765 你用的那个 theme 有问题。
在 %APPDATA%\Wox\Settings\Settings.json 中删除 "Theme" 这一行。然后删掉你那个自定义 theme 文件。

**Comment by f12998765** [comment]
@happlebao 
怎么安装自定义主题啊？wiki的文档挂掉了。

按网上搜的，把[http://www.getwox.com/theme/builder](http://www.getwox.com/theme/builder)下的主题放入Themes中，然后在设置中选择，再然后wox就崩了。

？？？

**Comment by bao-qian** [comment]
> wiki的文档挂掉了。

你指哪个网址。。？

那个网站的忘记更新了。。
你把你制作好的传上来，我帮你改一下。。。

**Comment by f12998765** [comment]
@happlebao 

wiki（[https://github.com/Wox-launcher/Wox/wiki](https://github.com/Wox-launcher/Wox/wiki)）里面的**Wox文档**，目录中点击**安装主题**出现空白页，**基本使用**后面的图都挂了。

现在用 `BlurWhite` 感觉不错，不用改了，谢谢。

**Comment by bao-qian** [comment]
Please try new release https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Reopen if above method won't help.
