### ISSUE TITLE
Wox.Plugin.Program.Main.DefaultProgramSources()

### ISSUE THREAD

**Issue by Vxider** [Wox-launcher/Wox#850]
## English

Before you report any bugs try search existing issues
1. Wox, Version=1.3.183.0
2. Crash when click wox icon.
3. windos 10
   [2016-07-16.txt](https://github.com/Wox-launcher/Wox/files/367097/2016-07-16.txt)
## 中文 / Chinese

报 bug 之前搜索一下已经有的 issue
1. Wox, Version=1.3.183.0
2. 运行程序直接崩溃
3. windows 10

**Comment by bao-qian** [comment]
试一下删除 `%AppData%\Wox\Cache`
如果还不行试一下 删除 `%AppData%\Wox\Settings` （删前记得备份）

**Comment by bao-qian** [comment]
有问题再开
