### ISSUE TITLE
wox长期占用cpu25%左右

### ISSUE THREAD

**Issue by laodao** [Wox-launcher/Wox#851]
1、版本：1.3.183
2、操作系统：windows10 pro
3、重现步骤：随机出现，目前不知道怎么重现
![image](https://cloud.githubusercontent.com/assets/1702657/16906438/5a18ab86-4cea-11e6-8980-65d302366790.png)

**Comment by laodao** [comment]
已经持续了好几个小时了，似乎没有歇一下的迹象，不知道有没有办法让他不那么忙。

**Comment by bao-qian** [comment]
这种情况一般要挂 visual studio 的 debugger 。。。
如果你不会的话，按下面的顺序试一下
1. 试一下删除 `%APPDATA%\Wox\Settings` （删设置之前记得备份）和 `%APPDATA%\Wox\Cache`
2. 禁用 program 插件（我唯一想得到的会在后台运作的部分。。）
3. 禁用 自动更新

**Comment by bao-qian** [comment]
有问题再开
