### ISSUE TITLE
Object reference not set to an instance of an object. at Wox.Plugin.Program.Main.DefaultProgramSources() 

### ISSUE THREAD

**Issue by aligundogdu** [Wox-launcher/Wox#853]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.3.9600.0
Date: 07/19/2016 09:48:33
Exception:
Wox.Plugin.Program
System.NullReferenceException
Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: Wox.Plugin.Program.Main.DefaultProgramSources() C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs içinde: satır 136
   konum: Wox.Plugin.Program.Main.IndexPrograms() C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs içinde: satır 102
   konum: Wox.Plugin.Program.Main.Init(PluginInitContext context) C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs içinde: satır 94
   konum: Wox.Infrastructure.Stopwatch.Normal(String name, Action action) C:\projects\wox\Wox.Infrastructure\Stopwatch.cs içinde: satır 28
   konum: Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) C:\projects\wox\Wox.Core\Plugin\PluginManager.cs içinde: satır 96
   konum: System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
   konum: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   konum: System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object param0)

**Comment by bao-qian** [comment]
whole log file please.

**Comment by bao-qian** [comment]
try delete `%APPDATA%\Wox\Cache`

**Comment by aligundogdu** [comment]
[2016-07-20.txt](https://github.com/Wox-launcher/Wox/files/372987/2016-07-20.txt)

i deleted cache dir but not fix.

**Comment by bao-qian** [comment]
try delete `%APPDATA%\Wox\Settings` (backup it before you delete that)

**Comment by aligundogdu** [comment]
It's worked , Thanks.
