### ISSUE TITLE
Option "Hide Wox on Startup " and "Ignore hotkeys in full-screen mode" won't work on Windows 10

### ISSUE THREAD

**Issue by MakeshVineeth** [Wox-launcher/Wox#855]
I'm currently using:
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14388.0

Wox won't hide on startup even if the option was enabled. I need to focus the text-box manually and click on start-menu in order to make it closed.

Also checking the option "Ignore hotkeys in full-screen mode" won't launch Wox at all !! Even if I've not opened any software but just a desktop, Wox won't show up at all !!

**Comment by bao-qian** [comment]
> hide wox on startup

should be fixed now: https://ci.appveyor.com/project/happlebao/wox/build/1.3.202/artifacts

> ignore hotkeys in full-screen mode

@lances101 I remember you did something to this option in one issue, but I can't find the issue.
Could you find it?

**Comment by MakeshVineeth** [comment]
> hide wox on startup
> ignore hotkeys in full-screen mode

Thanks for the reply. I installed the version 1.3.202. Everything working fine now.
