### ISSUE TITLE
无法找到UWP版有道云音乐

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#857]
wox version: 1.3.188
os: win 10 x64 (build 10586) 英文版

我能够成功安装有道云音乐UWP版本，名称为`netease music`，然而无论搜索`netease music`·、`yyy`（readme里提到的）、`云音乐`都找不到。。。

**Comment by bao-qian** [comment]
那么答案当然是 uwp 还没支持啦……

**Comment by bao-qian** [comment]
这 feature 坑了好久了……
现在终于在写了（

**Comment by bao-qian** [comment]
use #198
