### ISSUE TITLE
the first query will always slow

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#858]
the first query will always slow (> 3s)
after change log level from info to debug, we found that both program plugin and control panel plugin cost > 3s in the first query.
they both called `ScoreForPinyin`.
so the conclusion is the initialization of pinyin library cost more than 3s.

**Comment by sxdxyxy** [comment]
I have the same issue.

**Comment by jhdxr** [comment]
I think pinyin related parts should be disabled unless the language chosen is Chinese. furthermore, we may move those codes to localization package, for example, people from Japan may need their own "pinyin translate".

**Comment by bao-qian** [comment]
@jhdxr
1. the pinyin related parts are in separate methods. `Score` and `ScoreForPinYin`.
2. yeah, there should be a option to disable it.

Todo:
Instead of checking displaying language, we can check installed IME.
Since lots of chinese people using english os, but they must installed some kinds of chinese IME.

**Comment by jhdxr** [comment]
well, I mean the language setting of Wox instead of OS. I think it's much easier than checking IME and judging if they are chinese IME.

and this doesn't solve the problem of initialization spending too much time.

**Comment by martijnburgers** [comment]
This is one of the most annoying issues. Can this init not be done ahead of time, i.e. app startup.

**Comment by lances101** [comment]
We could force Wox to prefire at startup. This would always cost those 3 seconds, but I think its worth it. 

Regarding disabling Pinyin, I think the IME detection method is a good idea. I will look into that. But even with that implemented, I still think that prefiring Wox is a good idea.

**Comment by bao-qian** [comment]
now the pinyin library init has been moved into startup.
the auto language detect will be add later

**Comment by bao-qian** [comment]
much faster now in the new release.
