### ISSUE TITLE
Remove bookmarks from results

### ISSUE THREAD

**Issue by mihai-vlc** [Wox-launcher/Wox#86]
Is there any way we can deactivate the bookmarks from showing up in the results ?
I use this mostly to quickly fire up the programs i need, i rarely use the bookmarks.

**Comment by aaroncampf** [comment]
The development version has a setting to do just that Just uncheck the bookmark box and your good to go.

I added it in myself!

**Comment by mihai-vlc** [comment]
I have builded the project and checkded the checkboxes but they don't seem to persist when i close the window.
And they show up like this
http://puu.sh/97YkG/ec16c07704.png

**Comment by aaroncampf** [comment]
You have that version.

Go to the plugin Tab and uncheck Enable Bookmark Plugin

**Comment by mihai-vlc** [comment]
Yes that did the trick. Thank you
