### ISSUE TITLE
Again process can not access the file web_search.png

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox#862]
Strange, wox version `1.3.202` but error `process can not access the file` about `web_search.png` in folder `app-1.3.183` =) this folder and file really created and deleted after Wox lost focus

Wox version: 1.3.202
OS Version: Microsoft Windows NT 10.0.10586.0
IntPtr Length: 8
x64: True
Python Path: C:\Users\User\AppData\Local\Programs\Python\Python35\pythonw.exe
Everything SDK Path: 
Date: 07/23/2016 01:59:52
Exception:
mscorlib
System.IO.IOException
Процесс не может получить доступ к файлу "C:\Users\User\AppData\Local\Wox\app-1.3.183\Plugins\Wox.Plugin.WebSearch\Images\web_search.png", так как этот файл используется другим процессом.
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalDelete(String path, Boolean checkHost)
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 234
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 342
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 0
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 234
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 342
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 0
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 234
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 342
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 0
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 234
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 342
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a9>d__b7.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:строка 286
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 533
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__7b.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:строка 49
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:строка 73
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:строка 533
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() в c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:строка 169
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Wox.Core.Updater.<UpdateApp>d__0.MoveNext() в C:\projects\wox\Wox.Core\Updater.cs:строка 56
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
whole log?

**Comment by roose** [comment]
@happlebao 
[2016-07-23.txt](https://github.com/Wox-launcher/Wox/files/379064/2016-07-23.txt)

**Comment by bao-qian** [comment]
looks like the squirrel auto updater wants to delete the old version.
could you use wox as normal (this exception won't pop up again) ?
if so, this exception is  ignorable .

**Comment by roose** [comment]
hmm, looks like a false alarm =)

in first time - I deleted file and restart wox - exception, 
second time - I deleted app-1.3.183 folder and restarted wox again and I see app-1.3.183 folder is created and deleted after wox lost focus - exception, 
now i restarted wox in third time - no exception
