### ISSUE TITLE
Wox got an Error

### ISSUE THREAD

**Issue by belabeier** [Wox-launcher/Wox#866]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/24/2016 11:02:50
Exception:
System
System.UriFormatException
Ungültiger URI: Der URI ist leer.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei Wox.Core.Resource.Theme.GetResourceDictionary() in C:\projects\wox\Wox.Core\Resource\Theme.cs:Zeile 70.
   bei Wox.Core.Resource.ResourceMerger.UpdateResource[T](T t) in C:\projects\wox\Wox.Core\Resource\ResourceMerger.cs:Zeile 31.
   bei Wox.Core.Resource.Theme.ChangeTheme(String themeName) in C:\projects\wox\Wox.Core\Resource\Theme.cs:Zeile 58.
   bei Wox.MainWindow.OnLoaded(Object sender, RoutedEventArgs _) in C:\projects\wox\Wox\MainWindow.xaml.cs:Zeile 53.
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Interop.HwndTarget.OnResize()
   bei System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
whole log file?

**Comment by belabeier** [comment]
That was all it showed me?

**Comment by roose** [comment]
@belabeier go to `C:\Users\User\AppData\Roaming\Wox\Logs\1.3.183` and attach latest log file

**Comment by belabeier** [comment]
Ha, thanks roose! Didnt know there was an additional one. Here it is: 
(Attached) 

[2016-07-24.txt](https://github.com/Wox-launcher/Wox/files/380974/2016-07-24.txt)

**Comment by bao-qian** [comment]
seems like a invalid theme file. did you used an older version of wox before?
try delete `%LOCALAPPDATA%\Wox` and %APPDATA%\Wox`, then install again.

**Comment by belabeier** [comment]
Hi! 
Yes, I used 1.2 for quite a while (Portable, stored in my dropbox), but it kept forgetting the shortcut and the settings....   but reinstaling it seems to have worked! 
Thanks! 
And on my work-machine  I'll just be a bit slower :P 

Greetings and thank you! 
Bela

**Comment by bao-qian** [comment]
What do you mean slower? New version of wox is slower?

**Comment by bao-qian** [comment]
You can star this project :)

**Comment by belabeier** [comment]
Hi! "SLower" meaning I have to  spend time every morning doing the whole config on the workmachine, not "Wox running slower"  ;) 

And it is starred - have been using it for about a year now, and can't imagine working without it :D

**Comment by bao-qian** [comment]
great
