### ISSUE TITLE
Non conventional button positions on Wox and plugins dialogs

### ISSUE THREAD

**Issue by druellan** [Wox-launcher/Wox#867]
Testing on Wox 1.3.183
Don't know if this is something related to the Chinese translation, but button positions on the dialogs are sometimes reversed compared to Windows conventions.

A good example is the Wox.Plugin.WebSearch dialog.

![2016-07-24 11_33_38-search source setting](https://cloud.githubusercontent.com/assets/6965667/17084479/34c139ac-5195-11e6-9e88-41fff7bb0dc4.png)

On western languages the convention is to place the afirmative action on the left, that means Confirm, then Cancel.

Other plugins also have inverted buttons, like this one:

![2016-07-24 11_50_51-wox settings](https://cloud.githubusercontent.com/assets/6965667/17084480/4647102a-5195-11e6-81ea-c54fb8f54c96.png)

By convention, buttons should be positioned: Add  Edit  Delete

Of course this is by no means a critical issue, but I believe this details improve the quality of the software.

**Comment by happlebao** [comment]
https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/

**Comment by bao-qian** [comment]
https://www.nngroup.com/articles/ok-cancel-or-cancel-ok/

I believe there are two opinions.
