### ISSUE TITLE
Can't run in windows 10 with .net 4.6

### ISSUE THREAD

**Issue by LiHaoGit** [Wox-launcher/Wox#869]
Wox-1.3.183无法再window10 运行

.net版本 394254 (Windows 10) or 394271 (All other OS versions)    .NET Framework 4.6.1

![qq 20160725145444](https://cloud.githubusercontent.com/assets/7036191/17092819/c9ea1f34-5277-11e6-8a4d-47c5c47a67b8.png)

**Comment by bao-qian** [comment]
。。。
你是 windows insider 码？

**Comment by SizheCai** [comment]
不是,我刚刚查了一下,也有一些的需要.net4.5的软件都没法安装

**Comment by LiHaoGit** [comment]
不是,我刚刚查了一下,也有一些的需要.net4.5的软件都没法安装.你是用哪个版本的vs开发的,我试试改下.NETFramework,Version,能不能编译通过

**Comment by bao-qian** [comment]
改一下肯定是行的。 vs 2015。

**Comment by bao-qian** [comment]
你是新装 win10 吗？
下个 .net 4.5.2  行吗？

**Comment by LiHaoGit** [comment]
win10自带.net4.6 所以装不了4.5
会提示以安装了高版本的.net

**Comment by LiHaoGit** [comment]
问题解决了,不是.net版本的问题,是我的这个宽带,在下载这个EXE文件的时候,少了几十KB!!导致不能运行

**Comment by bao-qian** [comment]
好吧…
