### ISSUE TITLE
Can't find the action keyword for the plugin that I installed.

### ISSUE THREAD

**Issue by mu-yu** [Wox-launcher/Wox#87]
比如我安装了everything插件，但是得通过输入ev xxxx才能搜索，如果我通过wpm安装插件，那么我就没法知道这个插件怎么用了…建议在设置页面里面能够显示出插件的详细信息如作用、用法，作者等…

另外建议增加一个在通知区域不显示图标的选项（像everything那样），不喜欢右下角有太多图标……

**Comment by qianlifeng** [comment]
we will add the detail description for the plugin in the plugin tab later, also there will be an switch for the plugin to turn it on or off.

**Comment by qianlifeng** [comment]
I have added Plugin action keyword information to plugins tabs in setting panel.
