### ISSUE TITLE
Very useful, It must be better if Wox can be run in portable mode

### ISSUE THREAD

**Issue by blueyi** [Wox-launcher/Wox#872]
I have used Wox some days, which is so convenient, I think if Wox can be used in portable mode, it will be more convenient when transfer to another computer. I would like to participate in the Wox project or plugin project, but I haven't find the details document. Thanks #

**Comment by bao-qian** [comment]
1. #629 
2. no documents for development yet
3. plugin: http://doc.getwox.com/en/
