### ISSUE TITLE
Wox1.3.183的搜索框阴影和黑线问题

### ISSUE THREAD

**Issue by 2hang3an** [Wox-launcher/Wox#875]
## 中文 / Chinese
1. Wox 1.3.183
2. 1  更换主题后，搜索框所在位置会出现阴影，有时搜索内容所在的位置也会出现阴影，重新打开、关闭搜索框后阴影消失。

2.2  搜索框消失，搜索框位置只剩下一条与搜索框等高的黑线，频繁出现，暂时不知道如何重现。

系统：  Windows 10

运行时报了一次错，不知道是否与我所说的阴影和黑线有关，截图为阴影：
 Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/27/2016 19:55:04
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
：
6. 截图 （可选）：
![31](https://cloud.githubusercontent.com/assets/20420437/17176080/a506e4fa-543d-11e6-927d-a972500007a2.png)

**Comment by bao-qian** [comment]
>  更换主题后，搜索框所在位置会出现阴影，有时搜索内容所在的位置也会出现阴影，重新打开、关闭搜索框后阴影消失。

没看懂。。。 截图？录像？

> 搜索框消失，搜索框位置只剩下一条与搜索框等高的黑线，频繁出现，暂时不知道如何重现。

你是多显示器吗？

**Comment by 2hang3an** [comment]
图片是阴影的截屏，笔记本电脑，不是多显示器。

你看我的截屏中间本来因该是Wox搜素框的位置出现了阴影，更换主题后就会出现这种情况，有时阴影的范围会很大，重新打开、关闭搜索框后阴影消失。时不时的搜索框会变成一条黑线，无法输入。
今天是第一次用Wox,发现了问题，过来支持一下。

**Comment by bao-qian** [comment]
> 过来支持一下。

这位客官右上角加个星呗

搜索框阴影： #711 
黑线： 我记得我修过这个问题，如果你能找出重现方法就最好了。。

**Comment by 2hang3an** [comment]
星星已加，黑线的话，今天下午刚安装时出现了一次，随后的几个小时里不知道什么原因又出现了两次，然后现在怎么按都不出现了。。。。。。

**Comment by Kaol-Fu** [comment]
确实有阴影的问题，我也碰到了

**Comment by DaRingLee** [comment]
遇到同样问题，更改主题后，不使用热键激活，使用右击图标打开就会出现。

**Comment by trigsoft** [comment]
我一直都这样，就一条黑线。其实可以接受输入，但是因为是黑线，所以看不见输入的是什么。

**Comment by HiIcy** [comment]
win10 在启动wox的同时如果输入cmd+r命令，wox出现异常，搜索框变成一条竖杠
这个问题我都遇到好多次 关闭掉后 就又打不开 想问问bug怎么弄啊

**Comment by 2hang3an** [comment]
最新的Wox-1.3.347仍然存在黑线问题，而且线更长了，如图![](http://i.imgur.com/uokAnFd.jpg)重现方法为，点击如图的第一项，即，Wox-a launcher for windows![](http://i.imgur.com/OF8PMik.jpg).

**Comment by bao-qian** [comment]
黑线问题我没办法重现
为了排除环境问题
你有空的话
不如新建个系统账号
登陆
然后找到重现方法

**Comment by 2hang3an** [comment]
好的，有空我试试，可能是我的环境问题

**Comment by bao-qian** [comment]
@oliutiano 试一下新 build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.352/artifacts

**Comment by bao-qian** [comment]
@Kaol-Fu @DaRingLee @trigsoft @ansiqu @hksuki @DDDthis @Ghostish @Ramon403 @drcege @satlxq @CepheiSigma @LittleHans8 
试一下新 build
https://ci.appveyor.com/project/happlebao/wox/build/1.3.352/artifacts

**Comment by bao-qian** [comment]
有问题再开

**Comment by hobofire** [comment]
####  使用了1.3.352版依旧存在这个问题
>  操作系统: win10 pro

**Comment by kaluluosi** [comment]
v1.3.578 仍然后这个黑线问题
![image](https://user-images.githubusercontent.com/1620585/53300307-5edcaa80-3880-11e9-975c-332dc6a2f8f5.png)

我个人猜测这个黑线在高分辨率屏幕上出现的概率会更高一点，因为我的surface pro4 和 surface book2 都出现过，但是在1080的台式机上从来没有出现。

**Comment by SamuelZon258** [comment]
+1 win+r必现

**Comment by sharkman2008cn** [comment]
win10 ltsc ，4k显示屏 ，win+r 竖直黑线 ，无法输入搜索内容

**Comment by Lanpice** [comment]
+1 我是新用户，win10 专业版，1080P双屏，安装好1.3.578后，win+r必现。

**Comment by flyuuo9** [comment]
+1 我是新用户，win10 专业版，1080P，安装好1.3.524后，win+r后必现。

**Comment by DFQISMYHERO** [comment]
<img width="581" alt="wox" src="https://user-images.githubusercontent.com/52648014/60787463-71e77b80-a18c-11e9-9c3d-4d76bd78f200.png">

**Comment by bao-qian** [comment]
试一下新 build
https://github.com/Wox-launcher/Wox/releases/tag/v1.3.735

**Comment by Cheng-Hz** [comment]
win 10家庭中文版，安装了1.3.881版本，win+R仍有黑线问题。目前解决方案只有在setting中取消“替换win+R"。

**Comment by bao-qian** [comment]
could you try new build?
if problem still exist, please upload log file.

https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1039

**Comment by Lanpice** [comment]
最新版v1.4.1196 Win+R依然必现。暂时先关了命令行替换。
Windows 10 Pro 1909

**Comment by WeiXinbang** [comment]
似乎是替换Win+R后的下一次唤出会触发
Windows 8.1 分辨率 1366*768 似乎和分辨率没有关系
