### ISSUE TITLE
Keepass with keefoxRPC to launch urls

### ISSUE THREAD

**Issue by Pimmetje** [Wox-launcher/Wox#878]
I think it would be nice if Wox could search keepass using https://github.com/luckyrat/KeeFox/wiki/en-%7C-Technical-%7C-KeePassRPC-detail i know it's not easy, i am willing to work on it if there more people willing to help. 

My idea would be to index the names. Use them in the Wox index. If u hit a entry it should open the url. Wox won't/should never read or access the password in the container. Just the search part and opening the url. This can be done calling keepass with the UUID of the entry.

**Comment by bao-qian** [comment]
you could  do this by make a c# plugin
doc.getwox.com
