### ISSUE TITLE
update theme builder site

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox#880]
change 
`<Color>`
to 
`<SolidColorBrush>`

exception: System.UriFormatException

**Comment by YYRancho** [comment]
In fact, I think the format of the **WoxTheme.xaml** that I download from **theme builder site** does not fit the new version **1.3.183**. The format of the downloaded theme is not the same as the original theme such as **pink.xaml**.
When I encountered the same bug, I tried rewriting the downloaded theme file according to the **pink.xaml** and it worked. Therefore, I think that as long as you update the format of the downloaded theme file, everything will be okay.

**Comment by bao-qian** [comment]
@YYRancho the website has been fixed.
