### ISSUE TITLE
web search plugin can't edit Icon and can't display search Icon 

### ISSUE THREAD

**Issue by zhiyue** [Wox-launcher/Wox#881]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug:
- adding custom web search in `web search plugin`.
- close wox
- open wox and try to type `action keyword` like `bd` ,it could not normally display the  Icon.
- try just edit the `icon path` in `web search plugin` and confirm ,then it show `New action keywords have been assigned to another plugin`.
1. Windows version: win10
2. Exception:
   just show messagebox 
   `New action keywords have been assigned to another plugin`
3. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):

```
2016-07-29 03:23:08.4882|INFO|Wox.Plugin.Program.Main.Init|Preload 503 programs from cache
2016-07-29 03:23:08.6411|INFO|Wox.App.<OnStartup>b__8_0|Preload 124 images from cache
```
1. Screenshot (optional): 
   ![image](https://cloud.githubusercontent.com/assets/4208883/17226936/8349d136-553e-11e6-954c-aca072bb9bb5.png)

![image](https://cloud.githubusercontent.com/assets/4208883/17226849/17d20982-553e-11e6-83f9-01c941dc0522.png)

**Comment by bao-qian** [comment]
已经修完了，还没放更新
https://ci.appveyor.com/project/happlebao/wox/build/1.3.224/artifacts

**Comment by zhiyue** [comment]
好的。我去测试一下

**Comment by zhiyue** [comment]
@happlebao  `icon` 可以成功修改。但是还有一个bug。
就是每次重启wox 后 `web search plugin` 里面的图标全部重置为
![image](https://cloud.githubusercontent.com/assets/4208883/17229044/64137b50-5548-11e6-9479-a5e4f0d77f3d.png)

对比之前版本插件配置目录下的`setting.json`:
![image](https://cloud.githubusercontent.com/assets/4208883/17229086/9975c1b8-5548-11e6-9ad0-8e0e5f5e6ac3.png)

右边的为新版，发现没有`IconPath`的字段，是保存在别的地方了吗？

**Comment by bao-qian** [comment]
。。。
我等下看看
vs 正在超慢更新中。。
