### ISSUE TITLE
UI美化建议:  图标位置和下拉列表

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#882]
不想每次打开都看见长长的列表, 如果只有一个框, 那可cool多了

建议打开时不要自动显示下拉列表, 当我按↓的时候才出现列表

增加个开关咯

**Comment by ghost** [comment]
这是我以前用的,  叫executor:  http://www.executor.dk/
![image](https://cloud.githubusercontent.com/assets/20717914/17238888/275d6578-5592-11e6-8d96-c2a2d77a020e.png)

建议wox也把图标的位置放在右边,

**Comment by ztmdsbt** [comment]
@tangchacha 说实话我觉得这个好丑......
