### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Reygos** [Wox-launcher/Wox#886]
I recive this message when I try to install wox.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 07/31/2016 15:20:43
Exception:
Wox
System.NullReferenceException
Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Wox.ViewModel.SettingWindowViewModel..ctor() in C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:riga 28
   in Wox.App.<OnStartup>b__8_0() in C:\projects\wox\Wox\App.xaml.cs:riga 44
   in Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:riga 27
   in System.Windows.Application.OnStartup(StartupEventArgs e)
   in System.Windows.Application.<.ctor>b__1_0(Object unused)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bao-qian** [comment]
delete %APPDATA%\Wox\Settings 
backup before delete

**Comment by bao-qian** [comment]
close due to no response
