### ISSUE TITLE
Select all text on launch

### ISSUE THREAD

**Issue by DagW** [Wox-launcher/Wox#890]
Using version 1.3.183 and loving it.

When I launch the app the last search term is already typed, and not selected.
Then I have to press CTRL+A to select all the text, and then type my new search.

Preferred behaviour:
Launch app, last searched text is selected.
Type new search to overwrite previous text.

**Comment by bao-qian** [comment]
your preferred behaviour should be actual behaviour..
1. what's your os version?
2. try https://ci.appveyor.com/project/happlebao/wox/build/1.3.231/artifacts

**Comment by DagW** [comment]
I am using it on Windows 7 Enterprise, SP1.
The version you linked to works fine, thanks.

Ill try this out for a while :+1:
