### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by zktz** [Wox-launcher/Wox#891]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Zhang Zheng.DESKTOP-8SOITK0\AppData\Roaming\Wox\Logs\1.3.183\
[2016-08-01.txt](https://github.com/Wox-launcher/Wox/files/393610/2016-08-01.txt)
2016-08-01.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10240.0
Date: 08/01/2016 19:24:00
Exception:
Wox.Plugin.Program
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Plugin.Program.Main.DefaultProgramSources() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 136
   在 Wox.Plugin.Program.Main.IndexPrograms() 位置 C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:行号 102
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 27
   在 Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) 位置 C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:行号 96
   在 System.Threading.Tasks.Parallel.<>c__DisplayClass9`1.<ForWorker>b__11()
   在 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   在 System.Threading.Tasks.Task.<>c__DisplayClass0.<ExecuteSelfReplicating>b__1(Object )

**Comment by zktz** [comment]
我想卸载后重新安装也不行。

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox\Settings` 
删前记得备份

**Comment by zktz** [comment]
刚才尝试了一下，确实解决。多谢。
