### ISSUE TITLE
Typing puts characters to the end, ignoring a caret position

### ISSUE THREAD

**Issue by enzy** [Wox-launcher/Wox#892]
The input field shouldn't move a caret position or act as in an insert mode. 
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug:
3. Windows version: 10 x64

**Comment by bao-qian** [comment]
try https://ci.appveyor.com/project/happlebao/wox/build/1.3.231/artifacts
#813

**Comment by enzy** [comment]
The build works great!
