### ISSUE TITLE
在输入文字后，光标会自动移动到查询框最后

### ISSUE THREAD

**Issue by jhdxr** [Wox-launcher/Wox#893]
1. Wox 版本 / commit number： build 183
2. 如何**重现** bug：打开wox，输入任意内容，然后按home或者左箭头移动到查询框前方，然后输入任何字母，光标会自动移到的最后。（预期结果光标不会自动移动到别的地方）
3. Windows 版本： win10x64  build 10586

**Comment by bao-qian** [comment]
试一下 https://ci.appveyor.com/project/happlebao/wox/build/1.3.231/artifacts
#813

**Comment by jhdxr** [comment]
@happlebao 验证已修复
