### ISSUE TITLE
亲，官网的链接好像下载不鸟

### ISSUE THREAD

**Issue by sherlockHK** [Wox-launcher/Wox#897]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by bao-qian** [comment]
有墙
<del> 旁边不是附了个百度盘吗 <del>

居然过期了。。。
我等下重传一下

**Comment by bao-qian** [comment]
或者你试着拖进迅雷。。。？

**Comment by bao-qian** [comment]
https://pan.baidu.com/s/1c28zLKk
