### ISSUE TITLE
Wox does not take focus after moving between Windows 10 desktops

### ISSUE THREAD

**Issue by Nick-Lucas** [Wox-launcher/Wox#900]
Wox: v1.3.183 0300bb5
Windows 10 

Reproduction: ('Open' refers to pressing Alt+Space)
1. Open Wox - observe cursor focus is taken, and can press Esc to close it
2. Move to other Virtual Desktop (Ctrl+Win+Arrow) - do not click into any window on this desktop
3. Open Wox - observe cursor is not placed in Wox and requires clicking into before you can Esc and or type

**Comment by roose** [comment]
in 1.3.202 all ok, try latest build https://ci.appveyor.com/project/happlebao/wox/build/1.3.243/artifacts

**Comment by Nick-Lucas** [comment]
Yep that fixes it! Thanks!
