### ISSUE TITLE
difficult to edit middle of query string b/c cursor always jumps to end

### ISSUE THREAD

**Issue by jondaniels** [Wox-launcher/Wox#901]
I expect the main input box to behave as a normal text input field.  But the cursor is moved to the end of the query string after any character is entered, even if the cursor/edit is in the middle of the query string.

Steps to reproduce:
- launch Wox
- start typing query, e.g. "firfox" (say you started to type "firefox" but forgot the "e")
- use either the mouse or back arrow to place the cursor where the "e" should go
- enter "e"
- note the cursor automatically moves to after the "x"

This behavior is especially annoying when trying to use the calculator plugin to edit the previous calculation to have a new number, e.g. trying to edit "100/4" to be "25/4" instead.

I'm on 1.3.183 on Windows 10

**Comment by bao-qian** [comment]
try this one https://ci.appveyor.com/project/happlebao/wox/build/1.3.243/artifacts

**Comment by jondaniels** [comment]
Perfect, this build behaves as expected.
