### ISSUE TITLE
使用自定义theme输入任意字符Wox崩溃

### ISSUE THREAD

**Issue by Kaol-Fu** [Wox-launcher/Wox#905]
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：使用theme builder制作了个theme，放入到app-1.3.183下的theme文件夹下，应用该theme后，在软件窗口输入任何字符都会使Wox崩溃，而且没有任何的log！改回软件自带的theme后，没有再发生这种情况！
3. Windows 版本：Windows 10 14393

**Comment by bao-qian** [comment]
网站还没空更新 #880 

打开 theme 文件
把
System.Windows.Media.Color
改成
System.Windows.Media.Brush

不行就上传你的 theme 文件

**Comment by Kaol-Fu** [comment]
打开了theme文件了，没有找到这一项啊
[WoxTheme.zip](https://github.com/Wox-launcher/Wox/files/404065/WoxTheme.zip)

**Comment by bao-qian** [comment]
[WoxTheme.zip](https://github.com/Wox-launcher/Wox/files/404081/WoxTheme.zip)

**Comment by bao-qian** [comment]
你试一下改好的

**Comment by Kaol-Fu** [comment]
现在没问题了，谢谢！
