### ISSUE TITLE
The priority of the bookmark is too high.

### ISSUE THREAD

**Issue by faninx** [Wox-launcher/Wox#91]
作为一个速启软件，个人还是希望在运行本地程序方面更快捷一点，我的书签很多，所以随便输个关键字就是一大把书签，匹配的太多了，要翻N页才能到程序

**Comment by qianlifeng** [comment]
恩，后面可能会将书签分离出来作为一个插件使用关键字触发。你可以暂时在设置里面关闭书签搜索。

**Comment by pokoblin** [comment]
请问怎么在设置关闭书签功能？我在设置里只看到有书签这个插件在第一位，试了半天也没试出来怎么关闭它。  @qianlifeng 

![20140626102907](https://cloud.githubusercontent.com/assets/104797/3394216/0fed2ff8-fcda-11e3-899c-049399087c8e.png)

**Comment by qianlifeng** [comment]
@bindiry 暂时在Plugins tab下面

**Comment by pokoblin** [comment]
找到了，多谢。
