### ISSUE TITLE
new issue following the wox's instruction

### ISSUE THREAD

**Issue by horizonl** [Wox-launcher/Wox#913]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 1.3.183
2. Steps to **reproduce** the bug:no idea
3. Windows version:Microsoft Windows NT 10.0.14393.0
4. Exception:mscorlib
   System.Threading.Tasks.TaskCanceledException
   已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):[2016-08-08.txt](https://github.com/Wox-launcher/Wox/files/405769/2016-08-08.txt)
6. Screenshot (optional):

**Comment by bao-qian** [comment]
1. 可忽略
2. 这是网络/墙的问题，试一下设置 http 代理

**Comment by bao-qian** [comment]
有问题再开
