### ISSUE TITLE
action keywords wpm 显示无效

### ISSUE THREAD

**Issue by chinawzy22** [Wox-launcher/Wox#915]
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：action keywords wpm 显示无效
3. Windows 版本：win10 rd1
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）： 没，检查配置文件正常
6. 截图 （可选）：

![image](https://cloud.githubusercontent.com/assets/4240584/17490460/725117fa-5dd5-11e6-8893-2256da96c15e.png)

![image](https://cloud.githubusercontent.com/assets/4240584/17490516/bca79298-5dd5-11e6-888c-cb2c1179c649.png)

**Comment by bao-qian** [comment]
没看懂什么意思。。
你设置一个 action keyword 不行？

**Comment by bao-qian** [comment]
有问题再开
