### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by sapomuyverde** [Wox-launcher/Wox#916]
Hi,
I got an error with Wox and it displayed a window with these instructions.

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/09/2016 11:24:17
Exception:
Wox.Plugin.Program
System.NullReferenceException
Referencia a objeto no establecida como instancia de un objeto.
   en Wox.Plugin.Program.Main.DefaultProgramSources() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 136
   en Wox.Plugin.Program.Main.IndexPrograms() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 102
   en Wox.Infrastructure.Stopwatch.Debug(String name, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 19
   en Wox.Plugin.Program.Main.Init(PluginInitContext context) en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 94
   en Wox.Core.Plugin.PluginManager.<>c__DisplayClass19_0.<InitializePlugins>b__1() en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 98
   en Wox.Infrastructure.Stopwatch.Normal(String name, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 27
   en Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 96
   en System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   en System.Threading.Tasks.Task.InnerInvoke()
   en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
[2016-08-09.txt](https://github.com/Wox-launcher/Wox/files/409428/2016-08-09.txt)

Regards,
Javier

**Comment by bao-qian** [comment]
delete %APPDATA%\Wox
backup %APPDATA%\Wox\Settings before you do that

**Comment by bao-qian** [comment]
close due to no response

**Comment by sapomuyverde** [comment]
Hi,
Sorry for delay, now everything works fine after delete %APPDATA%\Wox according to the instruction.

Regards,
Javier
