### ISSUE TITLE
[clipboard] wox can't exit / close

### ISSUE THREAD

**Issue by xujianbiao** [Wox-launcher/Wox#918]
右键退出wox后，仍有进程在运行，此时如果再次打开wox，没有任何反应，wox没有被激活，之前的进程仍然在，只有强行结束进程之后再打开wox才能被激活，win7和win10系统都有这种情况

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox\Logs\1.3.183\today`
重试一遍
上传 `%APPDATA%\Wox\Logs\1.3.183\today`

**Comment by xujianbiao** [comment]
然而这样操作并没有什么日志，下面这几句不知道有没有用。。
2016-08-12 09:07:43.0448|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|Python can't be found in PATH.
2016-08-12 09:07:43.0768|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|

2016-08-12 09:07:43.2399|INFO|Wox.Infrastructure.Stopwatch.Normal|Preload 293 programs from cache
2016-08-12 09:07:45.3776|INFO|Wox.Infrastructure.Image.ImageLoader.PreloadImages|Preload 200 images from cache

**Comment by bao-qian** [comment]
我还是无法重现。。。
你是在右下角的托盘图标那右键点的退出吧？

**Comment by xujianbiao** [comment]
是的，即使用命令退出还是会有进程驻留，此时双击桌面的wox打开没反应，只有结束进程，再双击打开才可以。

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox` 呢？删前手动备份一下。。

**Comment by xujianbiao** [comment]
找到原因了，删除%APPDATA%\Wox这时候是正常的，于是怀疑是插件的问题，一个一个试，到了Clipboard History这个插件问题就复现了，是这个插件的锅，进程退出不了，退出之后不应该留在后台收集剪切板吧？不装这个插件就可以正常退出了，还有一个问题想问一下大神你，为什么每次打开wox桌面都会刷新一次？？

**Comment by bao-qian** [comment]
你 Clipboard 的版本是多少？
后台收集不会。。。 应该是抛了异常导致不能正常退出。。。
刷一下：未知。。

**Comment by xujianbiao** [comment]
最新的1.1.0，每次打开都刷新一下桌面T_T

**Comment by xujianbiao** [comment]
还有一个问题需要反馈一下的，在输入框输入一些关键字，然后把光标移到第一位，再打字的话，此时第一个打的字显示在第一位，这个没问题，但是第二个打的字跳到最后一位去了，光标自己跳到最后一位

**Comment by bao-qian** [comment]
这个问题修复了 还没推更新
https://ci.appveyor.com/project/happlebao/wox/build/1.3.259/artifacts

**Comment by xujianbiao** [comment]
好的谢谢解答
