### ISSUE TITLE
功能建议：建议加入类似listary中的行动菜单的功能

### ISSUE THREAD

**Issue by cireu** [Wox-launcher/Wox#919]

**Comment by bao-qian** [comment]
这啥 你至少给个说明/截图。。

**Comment by cireu** [comment]
在listary中，搜索到文件以后按Ctrl + O可以打开行动菜单  

![qq 20160818103909](https://cloud.githubusercontent.com/assets/18224684/17760142/0a308194-6530-11e6-8a9c-2801b172236a.png)

利用行动菜单可以快捷的对搜索到的文件执行各种操作，可以说是十分方便（也正是如此我选择了listary而不是everything）  

![qq 20160818104025](https://cloud.githubusercontent.com/assets/18224684/17760165/3481f31a-6530-11e6-9659-7c3fc9d1aa1f.png)

虽说wox中按Ctrl + O组合键也能调出类似的功能，但是与listary的菜单相比实在是相形见绌，望能加以改进

**Comment by S7venYoung** [comment]
你不知道，他没美工。。。
