### ISSUE TITLE
Crashed after launch

### ISSUE THREAD

**Issue by jhezjkp** [Wox-launcher/Wox#92]
## Exception

```
System.Windows.Markup.XamlParseException: 无法找到名为“VirtualizationMode”的属性的 DependencyProperty 或 PropertyInfo。属性名区分大小写。  标记文件“Wox;component/resultpanel.xaml”中对象“lbResults”处的错误。
   Source: PresentationFramework
   TargetAssembly: PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
   TargetModule: PresentationFramework.dll
   TargetSite: Void ThrowException(System.String, System.Exception, Int32, Int32, System.Uri, System.Windows.Markup.XamlObjectIds, System.Windows.Markup.XamlObjectIds, System.Type)
   在 System.Windows.Markup.XamlParseException.ThrowException(String message, Exception innerException, Int32 lineNumber, Int32 linePosition, Uri baseUri, XamlObjectIds currentXamlObjectIds, XamlObjectIds contextXamlObjectIds, Type objectType)
   在 System.Windows.Markup.XamlParseException.ThrowException(ParserContext parserContext, Int32 lineNumber, Int32 linePosition, String message, Exception innerException)
   在 System.Windows.Markup.BamlRecordReader.ThrowException(String message, Exception innerException)
   在 System.Windows.Markup.BamlRecordReader.CreateInstanceFromType(Type type, Int16 typeId, Boolean throwOnFail)
   在 System.Windows.Markup.BamlRecordReader.GetElementAndFlags(BamlElementStartRecord bamlElementStartRecord, Object& element, ReaderFlags& flags, Type& delayCreatedType, Int16& delayCreatedTypeId)
   在 System.Windows.Markup.BamlRecordReader.BaseReadElementStartRecord(BamlElementStartRecord bamlElementRecord)
   在 System.Windows.Markup.BamlRecordReader.ReadElementStartRecord(BamlElementStartRecord bamlElementRecord)
   在 System.Windows.Markup.BamlRecordReader.ReadRecord(BamlRecord bamlRecord)
   在 System.Windows.Markup.BamlRecordReader.Read(Boolean singleRecord)
   在 System.Windows.Markup.TreeBuilderBamlTranslator.ParseFragment()
   在 System.Windows.Markup.TreeBuilder.Parse()
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   在 Wox.MainWindow.InitializeComponent() 位置 c:\Projects\Wox\Wox\MainWindow.xaml:行号 1
   在 Wox.MainWindow..ctor() 位置 c:\Projects\Wox\Wox\MainWindow.xaml.cs:行号 61
   在 Wox.App.OnStartup(StartupEventArgs e) 位置 c:\Projects\Wox\Wox\App.xaml.cs:行号 113
   在 System.Windows.Application.<.ctor>b__0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Boolean isSingleParameter)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Boolean isSingleParameter, Delegate catchHandler)

```
## Environment
- Command Line: "D:\Program Files\Wox\Wox.exe" 
- Exception Handle: System.Windows.Application.DispatcherUnhandledException
- Timestamp: 2014-06-26T10:51:40.1875000+08:00
- IntPtr Length: 4
- System Version: Microsoft Windows NT 5.1.2600 Service Pack 3
- CLR Version: 2.0.50727.1891
- Installed .NET Framework: 
## Assemblies - Wox.exe
- Wox, Version=1.0.0.119, Culture=neutral, PublicKeyToken=null (D:\Program Files\Wox\Wox.exe)
- log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a (D:\Program Files\Wox\log4net.dll)
- Wox.Plugin, Version=1.0.0.119, Culture=neutral, PublicKeyToken=null (D:\Program Files\Wox\Wox.Plugin.dll)
- Wox.Infrastructure, Version=1.0.0.119, Culture=neutral, PublicKeyToken=null (D:\Program Files\Wox\Wox.Infrastructure.dll)
- WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (D:\Program Files\Wox\WindowsInput.dll)
- NHotkey, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null (D:\Program Files\Wox\NHotkey.dll)
- mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll)
- System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\assembly\GAC_MSIL\System\2.0.0.0__b77a5c561934e089\System.dll)
- System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\assembly\GAC_MSIL\System.Windows.Forms\2.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
- System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\assembly\GAC_MSIL\System.Drawing\2.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
- Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualBasic\8.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll)
- System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
- System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\assembly\GAC_MSIL\System.Xml\2.0.0.0__b77a5c561934e089\System.Xml.dll)
- PresentationFramework, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_MSIL\PresentationFramework\3.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
- PresentationCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_32\PresentationCore\3.0.0.0__31bf3856ad364e35\PresentationCore.dll)
- WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_MSIL\WindowsBase\3.0.0.0__31bf3856ad364e35\WindowsBase.dll)
- System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\assembly\GAC_MSIL\System.Core\3.5.0.0__b77a5c561934e089\System.Core.dll)
- System.Runtime.Remoting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\assembly\GAC_MSIL\System.Runtime.Remoting\2.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
- PresentationFramework.Classic, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_MSIL\PresentationFramework.Classic\3.0.0.0__31bf3856ad364e35\PresentationFramework.Classic.dll)
- PresentationFramework.resources, Version=3.0.0.0, Culture=zh-CHS, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll)
- PresentationFramework.Luna, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\assembly\GAC_MSIL\PresentationFramework.Luna\3.0.0.0__31bf3856ad364e35\PresentationFramework.Luna.dll)
- mscorlib.resources, Version=2.0.0.0, Culture=zh-CHS, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll)
## Modules - Wox
- D:\Program Files\Wox\Wox.exe (Wox, 1.0.0.119, Wox, 1.0.0.119, ), 0x0000000000400000
- C:\WINDOWS\system32\ntdll.dll (NT Layer DLL, 5.1.2600.6007 (xpsp_sp3_gdr.100630-1644), Microsoft(R) Windows(R) Operating System, 5.1.2600.6007, Microsoft Corporation), 0x000000007C920000
- C:\WINDOWS\system32\mscoree.dll (Microsoft .NET Runtime Execution Engine, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x0000000079000000
- C:\WINDOWS\system32\KERNEL32.dll (Windows NT BASE API Client DLL, 5.1.2600.6293 (xpsp_sp3_gdr.121001-1622), Microsoft(R) Windows(R) Operating System, 5.1.2600.6293, Microsoft Corporation), 0x000000007C800000
- C:\WINDOWS\system32\ADVAPI32.dll (Advanced Windows 32 Base API, 5.1.2600.5512 (xpsp.080413-2113), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000077DA0000
- C:\WINDOWS\system32\RPCRT4.dll (Remote Procedure Call Runtime, 5.1.2600.6477 (xpsp_sp3_qfe.131106-0418), Microsoft® Windows® Operating System, 5.1.2600.6477, Microsoft Corporation), 0x0000000077E50000
- C:\WINDOWS\system32\Secur32.dll (Security Support Provider Interface, 5.1.2600.5753 (xpsp_sp3_gdr.090203-1302), Microsoft® Windows® Operating System, 5.1.2600.5753, Microsoft Corporation), 0x0000000077FC0000
- C:\WINDOWS\system32\SHLWAPI.dll (Shell Light-weight Utility Library, 6.00.2900.5912 (xpsp_sp3_gdr.091207-1454), Microsoft(R) Windows(R) Operating System, 6.00.2900.5912, Microsoft Corporation), 0x0000000077F40000
- C:\WINDOWS\system32\GDI32.dll (GDI Client DLL, 5.1.2600.6460 (xpsp_sp3_qfe.131009-0419), Microsoft® Windows® Operating System, 5.1.2600.6460, Microsoft Corporation), 0x0000000077EF0000
- C:\WINDOWS\system32\USER32.dll (Windows XP USER API Client DLL, 5.1.2600.5512 (xpsp.080413-2105), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000077D10000
- C:\WINDOWS\system32\msvcrt.dll (Windows NT CRT DLL, 7.0.2600.5512 (xpsp.080413-2111), Microsoft® Windows® Operating System, 7.0.2600.5512, Microsoft Corporation), 0x0000000077BE0000
- C:\WINDOWS\system32\IMM32.DLL (Windows XP IMM32 API Client DLL, 5.1.2600.5512 (xpsp.080413-2105), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000076300000
- C:\WINDOWS\system32\LPK.DLL (Language Pack, 5.1.2600.5512 (xpsp.080413-2105), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000062C20000
- C:\WINDOWS\system32\USP10.dll (Uniscribe Unicode script processor, 1.0420.2600.6421 (xpsp_sp3_qfe.130709-0421), Microsoft(R) Uniscribe Unicode script processor, 1.0420.2600.6421, Microsoft Corporation), 0x0000000073FA0000
- C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\mscorwks.dll (Microsoft .NET Runtime Common Language Runtime - WorkStation, 2.0.50727.1891 (QFEN-1.050727-1800), Microsoft® .NET Framework, 2.0.50727.1891, Microsoft Corporation), 0x0000000079E70000
- C:\WINDOWS\WinSxS\x86_Microsoft.VC80.CRT_1fc8b3b9a1e18e3b_8.0.50727.6195_x-ww_44262b86\MSVCR80.dll (Microsoft® C Runtime Library, 8.00.50727.6195, Microsoft® Visual Studio® 2005, 8.00.50727.6195, Microsoft Corporation), 0x0000000078130000
- C:\WINDOWS\system32\shell32.dll (Windows Shell Common Dll, 6.00.2900.6242 (xpsp_sp3_gdr.120608-1638), Microsoft(R) Windows(R) Operating System, 6.00.2900.6242, Microsoft Corporation), 0x000000007D590000
- C:\WINDOWS\WinSxS\x86_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.2600.6028_x-ww_61e65202\comctl32.dll (User Experience Controls Library, 6.0 (xpsp_sp3_qfe.100823-1643), Microsoft® Windows® Operating System, 6.00.2900.6028, Microsoft Corporation), 0x0000000077180000
- C:\WINDOWS\system32\comctl32.dll (Common Controls Library, 5.82 (xpsp_sp3_qfe.100823-1643), Microsoft® Windows® Operating System, 6.00.2900.6028, Microsoft Corporation), 0x000000005D170000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\mscorlib\709b207f778a3f7053329a6f3e17859c\mscorlib.ni.dll (Microsoft Common Language Runtime Class Library, 2.0.50727.1891 (QFEN-1.050727-1800), Microsoft® .NET Framework, 2.0.50727.1891, Microsoft Corporation), 0x00000000790C0000
- C:\WINDOWS\system32\ole32.dll (Microsoft OLE for Windows, 5.1.2600.6435 (xpsp_sp3_qfe.130803-0418), Microsoft(R) Windows(R) Operating System, 5.1.2600.6435, Microsoft Corporation), 0x0000000076990000
- C:\WINDOWS\system32\uxtheme.dll (Microsoft UxTheme Library, 6.00.2900.5512 (xpsp.080413-2105), Microsoft(R) Windows(R) Operating System, 6.00.2900.5512, Microsoft Corporation), 0x000000005ADC0000
- C:\WINDOWS\system32\MSCTF.dll (MSCTF Server DLL, 5.1.2600.5512 (xpsp.080413-2105), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000074680000
- C:\Program Files\360\360Safe\safemon\safemon.dll (360安全卫士 网盾防护模块, 8, 4, 0, 1390, 360安全卫士, 8, 4, 0, 1390, 360.cn), 0x0000000070200000
- C:\WINDOWS\system32\OLEAUT32.dll (, 5.1.2600.6341, , 5.1.2600.6341, Microsoft Corporation), 0x00000000770F0000
- C:\WINDOWS\system32\PSAPI.DLL (Process Status Helper, 5.1.2600.5512 (xpsp.080413-2105), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000076BC0000
- C:\WINDOWS\system32\VERSION.dll (Version Checking and File Installation Libraries, 5.1.2600.5512 (xpsp.080413-2105), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000077BD0000
- C:\WINDOWS\system32\WS2_32.dll (Windows Socket 2.0 32-Bit DLL, 5.1.2600.5512 (xpsp.080413-0852), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000071A20000
- C:\WINDOWS\system32\WS2HELP.dll (Windows Socket 2.0 Helper for Windows NT, 5.1.2600.5512 (xpsp.080413-0852), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000071A10000
- C:\WINDOWS\system32\NETAPI32.dll (Net Win32 API DLL, 5.1.2600.6260 (xpsp_sp3_gdr.120706-1619), Microsoft® Windows® Operating System, 5.1.2600.6260, Microsoft Corporation), 0x000000005FDD0000
- C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\mscorjit.dll (Microsoft .NET Runtime Just-In-Time Compiler, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x0000000079060000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System\7978492e9b3628cb2a7a93cbd9997189\System.ni.dll (.NET Framework, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x000000007A440000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Drawing\03356e236eab21c5bf176e3d4c1c1bcc\System.Drawing.ni.dll (.NET Framework, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x000000007ADE0000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Windows.Forms\f66eb174e35422dc69a63390fd4f7de5\System.Windows.Forms.ni.dll (.NET Framework, 2.0.50727.1891 (QFEN-1.050727-1800), Microsoft® .NET Framework, 2.0.50727.1891, Microsoft Corporation), 0x000000007AFD0000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\Microsoft.VisualBas#\ad581d12ea761c5bc457cff3d5aeeda1\Microsoft.VisualBasic.ni.dll (Visual Basic Runtime Library, 8.0.50727.1433 (REDBITS.050727-1400), Microsoft® Visual Studio® 2005, 8.0.50727.1433, Microsoft Corporation), 0x000000005E430000
- C:\WINDOWS\system32\rsaenh.dll (Microsoft Enhanced Cryptographic Provider, 5.1.2600.5507 (xpsp.080318-1711), Microsoft® Windows® Operating System, 5.1.2600.5507, Microsoft Corporation), 0x0000000068000000
- C:\WINDOWS\system32\xpsp2res.dll (Service Pack 2 Messages, 5.1.2600.5512 (xpsp.080413-2113), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000003400000
- D:\Program Files\Wox\log4net.dll (Apache log4net for .NET Framework 2.0, 1.2.13.0, log4net, 1.2, The Apache Software Foundation), 0x0000000000F30000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Configuration\c5d69d419ed6b2022b6529f2e7f16dff\System.Configuration.ni.dll (System.Configuration.dll, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x0000000064890000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Xml\ecc0c0880528133aac633431f9128091\System.Xml.ni.dll (.NET Framework, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x00000000637A0000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\WindowsBase\d48d3d38341fd3223d34d7f160ad3920\WindowsBase.ni.dll (Windows Presentation Foundation Base Library, 3.0.6920.1109 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x0000000056D30000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\PresentationCore\1a33ca6963a1470b6e36996668ba9930\PresentationCore.ni.dll (Windows Presentation Foundation Core Components Library, 3.0.6920.1109 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x00000000538A0000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\PresentationFramewo#\a4aba207ad9ccc2798d99010ad43a6e2\PresentationFramework.ni.dll (Windows Presentation Foundation Framework Library, 3.0.6920.1109 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x0000000055270000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Core\c7f395ab62f0bf242d1200d9218eaf3e\System.Core.ni.dll (.NET Framework, 3.5.21022.8 built by: RTM, Microsoft® .NET Framework, 3.5.21022.8, Microsoft Corporation), 0x000000006C190000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\System.Runtime.Remo#\0ecbd84b257f10f6ada35ecdafbc03b5\System.Runtime.Remoting.ni.dll (Microsoft .NET Runtime Object Remoting, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft® .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x0000000067770000
- C:\WINDOWS\system32\TCCNF.DLL (NETFilter DLL, 1, 0, 0, 1, NETFilter Dynamic Link Library, 1, 0, 0, 1, ), 0x0000000010000000
- C:\WINDOWS\system32\MFC71.DLL (MFCDLL Shared Library - Retail Version, 7.10.3077.0, Microsoft® Visual Studio .NET, 7.10.3077.0, Microsoft Corporation), 0x000000007C140000
- C:\WINDOWS\system32\MSVCR71.dll (Microsoft® C Runtime Library, 7.10.6030.0, Microsoft® Visual Studio .NET, 7.10.6030.0, Microsoft Corporation), 0x000000007C360000
- C:\WINDOWS\system32\MSWSOCK.dll (Microsoft Windows Sockets 2.0 Service Provider, 5.1.2600.5625 (xpsp_sp3_gdr.080620-1249), Microsoft(R) Windows(R) Operating System, 5.1.2600.5625, Microsoft Corporation), 0x00000000719C0000
- C:\WINDOWS\system32\hnetcfg.dll (Home Networking Configuration Manager, 5.1.2600.5512 (xpsp.080413-0852), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000060FD0000
- C:\WINDOWS\System32\wshtcpip.dll (Windows Sockets Helper DLL, 5.1.2600.5512 (xpsp.080413-0852), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000071A00000
- C:\WINDOWS\system32\msctfime.ime (Microsoft Text Frame Work Service IME, 5.1.2600.5512 (xpsp.080413-2105), Microsoft® Windows® Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000073640000
- D:\Program Files\Wox\Wox.Plugin.dll (Wox.Plugin, 1.0.0.119, Wox.Plugin, 1.0.0.119, ), 0x0000000004060000
- D:\Program Files\Wox\Wox.Infrastructure.dll (Wox.Infrastructure, 1.0.0.119, Wox.Infrastructure, 1.0.0.119, ), 0x0000000004070000
- D:\Program Files\Wox\WindowsInput.dll (WindowsInput, 1.0.4.0, WindowsInput, 1.0.4.0, michaelnoonan), 0x0000000004030000
- D:\Program Files\Wox\NHotkey.dll (NHotkey, 1.1.0.0, NHotkey, 1.1.0.0, ), 0x0000000004200000
- C:\WINDOWS\system32\urlmon.dll (OLE32 Extensions for Win32, 6.00.2900.6470 (xpsp_sp3_qfe.131024-0419), Microsoft(R) Windows(R) Operating System, 6.00.2900.6470, Microsoft Corporation), 0x000000007EAE0000
- C:\WINDOWS\system32\MilCore.dll (Microsoft MIL Core Library, 6.0.6001.17014 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 6.0.6001.17014, Microsoft Corporation), 0x0000000053190000
- C:\WINDOWS\system32\WindowsCodecs.dll (Microsoft Windows Codecs Library, 6.0.6001.17009 (longhorn.070920-1905), Microsoft® Windows® Operating System, 6.0.6001.17009, Microsoft Corporation), 0x000000004A170000
- C:\WINDOWS\system32\mscms.dll (Microsoft Color Matching System DLL, 5.1.2600.5627 (xpsp_sp3_gdr.080624-1245), Microsoft® Windows® Operating System, 5.1.2600.5627, Microsoft Corporation), 0x0000000073AA0000
- C:\WINDOWS\system32\WINSPOOL.DRV (Windows Spooler Driver, 5.1.2600.5512 (xpsp.080413-0852), Microsoft(R) Windows(R) Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000072F70000
- C:\WINDOWS\system32\WindowsCodecsExt.dll (Microsoft Windows Codecs Extended Library, 6.0.6001.17009 (longhorn.070920-1905), Microsoft® Windows® Operating System, 6.0.6001.17009, Microsoft Corporation), 0x000000007CE10000
- C:\WINDOWS\system32\icm32.dll (Microsoft Color Management Module (CMM), 5.1.2600.5512 (xpsp.080413-2105), Microsoft? Windows? Operating System, 5.1.2600.5512, Microsoft Corporation), 0x0000000060A20000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\PresentationFramewo#\0fa6d07ad23847d96a1d52449b3ce206\PresentationFramework.Classic.ni.dll (Windows Presentation Foundation Classic Theme, 3.0.6920.1109 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x00000000561B0000
- C:\WINDOWS\assembly\GAC_MSIL\PresentationFramework.resources\3.0.0.0_zh-CHS_31bf3856ad364e35\PresentationFramework.resources.dll (Windows 演示基础框架库, 3.0.6920.0 (vista_rtm_wcp.061020-1904), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x0000000004240000
- C:\WINDOWS\system32\d3d9.dll (Microsoft Direct3D, 5.03.2600.5512 (xpsp.080413-0845), Microsoft® Windows® Operating System, 5.03.2600.5512, Microsoft Corporation), 0x000000004B640000
- C:\WINDOWS\system32\d3d8thk.dll (Microsoft Direct3D OS Thunk Layer, 5.03.2600.5512 (xpsp.080413-0845), Microsoft® Windows® Operating System, 5.03.2600.5512, Microsoft Corporation), 0x000000006DD20000
- C:\WINDOWS\system32\WINMM.dll (MCI API DLL, 5.1.2600.6160 (xpsp_sp3_gdr.111014-1624), Microsoft(R) Windows(R) Operating System, 5.1.2600.6160, Microsoft Corporation), 0x0000000076B10000
- C:\WINDOWS\assembly\NativeImages_v2.0.50727_32\PresentationFramewo#\2e91e6fc90bd32ca0a43e602045522ea\PresentationFramework.Luna.ni.dll (Windows Presentation Foundation Luna Theme, 3.0.6920.1109 (lh_tools_devdiv_wpf.071009-1109), Microsoft® Windows® Operating System, 3.0.6920.0, Microsoft Corporation), 0x0000000056230000
- C:\WINDOWS\assembly\GAC_MSIL\mscorlib.resources\2.0.0.0_zh-CHS_b77a5c561934e089\mscorlib.resources.dll (Microsoft 公共语言运行库类库, 2.0.50727.1433 (REDBITS.050727-1400), Microsoft(R) .NET Framework, 2.0.50727.1433, Microsoft Corporation), 0x00000000045E0000
- C:\WINDOWS\Microsoft.NET\Framework\v2.0.50727\diasymreader.dll (Dia based SymReader, 8.0.50727.1433 (REDBITS.050727-1400), Microsoft® Visual Studio® 2005, 8.0.50727.1433, Microsoft Corporation), 0x000000005E3A0000
## Threads - 12
- 7548, Running Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810735
- 9360, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 9940, Wait Highest, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 6612, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 8108, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 1112, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 5904, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 5648, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 9384, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 9352, Wait Normal, Started: 2014-6-26 10:51:39, StartAddress: 0x000000007C810729
- 8796, Wait Normal, Started: 2014-6-26 10:51:40, StartAddress: 0x000000007C810729
- 8692, Wait Normal, Started: 2014-6-26 10:51:40, StartAddress: 0x000000007C810729

**Comment by qianlifeng** [comment]
Can you try to latest release? it seems your xaml file has some issues
