### ISSUE TITLE
Typing at the start of text sends cursor to the end

### ISSUE THREAD

**Issue by AmrEldib** [Wox-launcher/Wox#920]
If Wox's text box already has some text, and you go the start and try to type something, after each character, the cursor gets sent to the end of the text.

Steps to reproduce:
1. Start Wox, type something like: "word"
2. Hit "Home" or use the arrow keys to the go to the start of the text.
3. Start typing any letter, notice that you immediately get sent to the end.

Effect:
I use letters for each plugin. If I have the same word and I want to try different plugins on it, it's very difficult. If I forget to write the plugin's letter at the start, and I go back and try to add it, it doesn't work easily.

Wox version: 1.3.183
Windows version: 10 (Version 1607 OS Build 14393.67)

**Comment by deltaidea** [comment]
Duplicates: #813, #892.

Upgrade to build [1.3.231](https://ci.appveyor.com/project/happlebao/wox/build/1.3.231/artifacts) or newer.
