### ISSUE TITLE
使用自己编写的python插件wox崩溃

### ISSUE THREAD

**Issue by juventusryp** [Wox-launcher/Wox#921]
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：使用自己编写的插件
3. Windows 版本：win10
4. Exception：使用自己编写的插件wox就会崩溃
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   2016-08-15 16:55:55.4997|INFO|Wox.Plugin.Program.Main.Init|Preload 524 programs from cache
   2016-08-15 16:55:55.7940|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
   只有这两行

作者您好，自己写了个简单的python插件代码如下：
在wox运行后，shell窗口可以正常打开并进入到设置的文件夹，但是wox会出现无响应，崩溃状态。

``` python
#encoding=utf8
from wox import Wox
import os

class Main(Wox):
    def query(self,query):
        results = []
        results.append({
                        "Title": "hexo",
                        "IcoPath": "Images/hexo.gif",
                        "JsonRPCAction": {"method": "opencmd"}
        })
        return results
    def opencmd(self):
        os.chdir('G:\\kuaipan')
        os.system('C:\\WINDOWS\\system32\\cmd.exe')

if __name__ == "__main__":
    Main()

```

**Comment by bao-qian** [comment]
你这么直接用 os.system 的话，代码会不会往下走？
比如你在 os.system 后面用 wox.debug 输出一下？

**Comment by juventusryp** [comment]
@happlebao 您好，不好意思 ，我也是小白，求教如何使用wox.debug？我再测试下

另外我没太明白os.system 代码会不会往下走是什么意思？

我的代码只有两行，这个执行完成后，cmd是可以正常出来的，在cmd里文件夹路径也是G:\kuaipan，等于说是代码完成了它的任务，但是wox会崩溃。

**Comment by bao-qian** [comment]
```
os.chdir('G:\\kuaipan')
os.system('C:\\WINDOWS\\system32\\cmd.exe')
wox.debug("TEST os.system")
```

改成这样，你看有没有弹窗输出 `TEST　os.system`

**Comment by juventusryp** [comment]
@happlebao 您好，加上您说的代码还是和原来一样，打开一个shell并进入到设定的目录，但是wox崩溃

我录了个gif，可以看下

![](https://raw.githubusercontent.com/juventusryp/searchplatform/master/1.gif)

**Comment by bao-qian** [comment]
我猜没错啊
你不能这么用 os.system
这不叫崩溃
这叫卡死
卡死是因为 os.system 没有执行完/返回
没有返回时因为你 cmd 窗口没有关闭

**Comment by juventusryp** [comment]
@happlebao 哦哦 原来是这样
明白了,十分感谢
那我再去研究研究
