### ISSUE TITLE
功能建议：建议加入executor的History功能

### ISSUE THREAD

**Issue by eddiechowx** [Wox-launcher/Wox#924]
如题：日常使用的一些快捷方式，现在每次都要输入很长的字符的才能完全匹配，如果有历史记录且根据使用频率进行排序的话，那样启动一些日常应用/程序将更加快捷，相信会提升很多的便捷性，希望作者考虑加入。
类似executor的History功能，截图如下：

![qq 20160817101115](https://cloud.githubusercontent.com/assets/11539740/17722196/f4796816-6462-11e6-88fb-61a5edfae3df.png)

**Comment by bao-qian** [comment]
有啊 ctrl+h
