### ISSUE TITLE
wpm install can't connect to remote server, can it use the proxy?

### ISSUE THREAD

**Issue by Risitide** [Wox-launcher/Wox#93]
国内到github的连接不好，经常连不上。能不能给wpm添加代理设置？

手动下载的插件如何安装？

**Comment by qianlifeng** [comment]
如果需要手动安装插件，将下载的xxxxxxx.wox拖拽到Wox界面上即可。

**Comment by qianlifeng** [comment]
e4898bbbb3162d512856761dba131e06ccf08cff

**Comment by YangKeao** [comment]
每当我在plugin下对enable打勾后，再回到setting它又是未打勾的状态。并且要让.wox关联什么？

**Comment by qianlifeng** [comment]
@VDON 请下载最新版本[https://github.com/qianlifeng/Wox/releases/tag/v1.0-beta](https://github.com/qianlifeng/Wox/releases/tag/v1.0-beta) 你下的那个版本enable功能没有实现。如果要手动安装插件，将下载的xxxxxxx.wox拖拽到Wox界面上即可。
