### ISSUE TITLE
[Everything] support regex

### ISSUE THREAD

**Issue by Lewis-Liu** [Wox-launcher/Wox#930]
# 问题：wox的everything插件支持正则匹配吗？

> 直接在everything里面是支持正则的，但是在wox里面，不知道是否支持正则？

**Comment by bao-qian** [comment]
你说的是通配符吧？ `*`
通配符是支持的

**Comment by Lewis-Liu** [comment]
是标准的正则表达式。

**Comment by Lewis-Liu** [comment]
![everything](https://cloud.githubusercontent.com/assets/5558564/17769108/b7624454-6569-11e6-947d-1834b419c929.JPG)

**Comment by bao-qian** [comment]
不支持

**Comment by Lewis-Liu** [comment]
谢谢，知道了。
