### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by limitpb** [Wox-launcher/Wox#931]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 08/18/2016 18:41:29
Exception:
Wox.Plugin.Program
System.NullReferenceException
[2016-08-18.txt](https://github.com/Wox-launcher/Wox/files/424684/2016-08-18.txt)

**Comment by bao-qian** [comment]
delete 
`%APPDATA%\Wox\Cache`

**Comment by bao-qian** [comment]
close due to no response
