### ISSUE TITLE
Autopropagate / Hitlist

### ISSUE THREAD

**Issue by opuslux** [Wox-launcher/Wox#932]
Let's say we enter a string like "Visu" to launch Visual Studio 2015 and have to go down in the list with a few clicks on the arrow button (to pass by the older versions of Visual Studio) to launch it. It would be great if Wox remembers that we were interested in this item and move it to the top the next time we enter this string (or a very similar one). Could this be realized with a plugin or would it depend on a adaption in the core of wox?

**Comment by bao-qian** [comment]
1. Auto Propagate: duplicate: #315 
2. history: <kbd>Ctrl+H</kbd>
