### ISSUE TITLE
Add ShowContextMenu method into IPublicAPI

### ISSUE THREAD

**Issue by petrhorny** [Wox-launcher/Wox#933]
In version 1.2.x there was a method with signature  `void ShowContextMenu(PluginMetadata plugin, List<Result> results);` in the IPublicAPI interface.

Without this method, we are unable to do nested search/navigation.

We have built a plugin which allow us to search internal websites. When we click on one of the found websites another results/actions are shown (enter website, manage website, restart website, etc.)

Now we are stuck with version 1.2 because we are unable to port the plugin into version 1.3.xxx

**Comment by bao-qian** [comment]
the url for your plugin?

**Comment by bao-qian** [comment]
oh, it still there, just the location changed:
check `IFeatures.cs`

```
    public interface IContextMenu : IFeatures
    {
        List<Result> LoadContextMenus(Result selectedResult);
    }
```

**Comment by petrhorny** [comment]
Thank you for fast reply.
We tried to implement the method, but unfortunately the method LoadContextMenus is called only after right mouse click. We need to invoke this method after user selects one of the result with enter key. This is very uncomfortable because the user needs to leave the keybord and catch the mouse.
In version 1.2 we could open the context menu in the Action callback via public API. There was more control.

**Comment by bao-qian** [comment]
you probably need something else, give the url of your code

**Comment by petrhorny** [comment]
The plugin is not hosted on internet yet. Below is stub of the source code for version 1.2.
1. When you enter query, found websites are shown
2. When you select a result and press enter another results (options) are shown
3. You can then select which browser should open the website

```
public List<Result> Query(Query query)
        {
            // According to the query, find the results. This is an example, so we return always two results.
            return new List<Result>
                   {
                       new Result {Title = "go to www.microsoft.com", Action = ctx => ProcessAction("http://www.microsoft.com")},
                       new Result {Title = "go to www.intel.com", Action = ctx => ProcessAction("http://www.intel.com")},
                   };
        }

        private bool ProcessAction(string url)
        {
            var results = new List<Result>
                          {
                              new Result { Title = "open with Chrome", Action = ctx => OpenUrl(url, "chrome")},
                              new Result { Title = "open with Firefox", Action = ctx => OpenUrl(url, "firefox") },
                              new Result { Title = "open with Internet Explorer", Action = ctx => OpenUrl(url, "iexplore") },
                          };
            _api.ShowContextMenu(_pluginMetadata, results);
            return true;
        }
```

**Comment by bao-qian** [comment]
fair reason.
a temp workaround I suggest before I add some api:
1. implement LoadContextMenus
2. send shift+enter keys https://msdn.microsoft.com/en-us/library/system.windows.forms.sendkeys.sendwait.aspx

**Comment by petrhorny** [comment]
Great, your workaround works.
Thank you.
