### ISSUE TITLE
计算器和控制面板插件问题

### ISSUE THREAD

**Issue by zerojade** [Wox-launcher/Wox#938]
已经有的 issue并没有解决问题。
1. Wox 版本：1.3.183
2. 问题描述：有计算插件，在未设置计算器插件热键的情况下，在wox界面直接输入例如“1+1”，不能得到计算结果，设置了热键之后可以得到结果。控制面板同理。可是按照设计是应该不用热键也可以的。
3. Windows 10 Version 1607 累积更新 (KB3176495)
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   [2016-08-22.txt](https://github.com/Wox-launcher/Wox/files/429601/2016-08-22.txt)
   6.截图：
   ![-1](https://cloud.githubusercontent.com/assets/21169074/17847537/0d8c07ec-6881-11e6-94b5-394ded4c3359.png)

**Comment by bao-qian** [comment]
1. 试一下新 build https://ci.appveyor.com/project/happlebao/wox/build/1.3.280/artifacts
2. 还不行试一下删除 `%APPDATA%\Wox\`, 删前记得备份

**Comment by bao-qian** [comment]
有问题再开
