### ISSUE TITLE
Smart Bar

### ISSUE THREAD

**Issue by metude** [Wox-launcher/Wox#94]
First of all, thanks for Wox. AFAIS best launchy alternative. I'll post my suggestions and issues as long as using.

Here's my first suggestion. When I show popup and type word it shows me my all bookmarks http://prntscr.com/3xot98
But I would like to launch Word 2013. Also, is wox tracking my frequently used apps?

**Comment by aaroncampf** [comment]
I have not worked in Wox myself in a few weeks, but I do not think it does.
Personally, uncheck the Enable Bookmark Plugin, that way your search results will be far less polluted.

I think it might be useful for it to remember, for example, the last 100 items you opened and give them priority.

You can always add a new folder into the File System plugin and then use that to help you find what you want.

Example:
Put Shortcuts in Shortcuts Folder
Add Shortcuts folder path into File System plugin
Then Search
Shortcuts

This will only search items in Shortcuts folder

**Comment by JohnTheGr8** [comment]
What if it was possible for the user to assign a custom keyword to bookmark search? That way you don't have to disable the bookmarks plugin and other searches are not filled with bookmark results...

**Comment by aaroncampf** [comment]
Yes, that is 100% possible (and a good idea).
I will email qianlifeng and see what he wants to do (only he has the authority to make this kind of change).

I think it should use the keyword bookmarks
I also think that it should work that way by default and not clutter the search results by default.

**Comment by metude** [comment]
I was thinking something like this: http://prntscr.com/3xqpmt
First down arrow key press will go to first item of bookmarks, second press will go to first item of apps, third one for others...

Also keyword for bookmarks would be nice.

**Comment by aaroncampf** [comment]
That's a great Idea, to bad I don't have the skills to do it
I'll see what qianlifeng thinks.

**Comment by metude** [comment]
Thanks anyway.

Just for note, Smart Bar refers to Mozilla Firefox's smart address bar. Smart address bar makes similar job in my draft screenshot. Blending bookmarks, recent tabs, current tabs, and shows best possible matches.

**Comment by qianlifeng** [comment]
Yes, Bookmarks should be removed from the default source. Since many people complaint their search results are full of bookmarks(well, sometimes me too). We will make the bookmark as a plugin, and triggered by `b` or `bk`.

**Comment by qianlifeng** [comment]
[http://prntscr.com/3xqpmt](http://prntscr.com/3xqpmt) looks good. What if user want to select the second bookmark in the bookmark group? when he press the down arrow twice, it will jump to app group.  
Currently, Wox will auto adjust the weight of your search item by your selections. and we didn't provide a last used items for now, this will not be a good choice for plugins searches, I think we shouldn't list the plugin searches for last used items at least. What's you guys options?

**Comment by orzFly** [comment]
In Alfred, workflow commands are just like normal commands:

![image](https://cloud.githubusercontent.com/assets/158528/3425472/e5773a7a-0003-11e4-94cc-68b3b2e430bf.png)
(I seldom use `ip138`)

![image](https://cloud.githubusercontent.com/assets/158528/3425473/e8d2bdd4-0003-11e4-9abb-2b83ca2572b5.png)
(I use `mongodb` and `mongoose` everyday)

However, when the plugin mode is entered, there will be no results from system plugins.

**Comment by qianlifeng** [comment]
Is there bookmark plugins in Alfred? How did he handle this kind of issues?

**Comment by orzFly** [comment]
In fact, no.
-- 
orzFly / Yeechan Lu

On June 30, 2014 at 12:52:40, qianlifeng (notifications@github.com) wrote:

Is there bookmark plugins in Alfred? How did he handle this kind of issues?

**Comment by aaroncampf** [comment]
I assume its built in some how

**Comment by metude** [comment]
_"We will make the bookmark as a plugin, and triggered by b or bk."_
That would be much better.

_"What if user want to select the second bookmark in the bookmark group? when he press the down arrow twice, it will jump to app group."_
My suggestion just a suggestion. Always we can find few solution. First idea came in my mind, if user wants to select second item, `down arrow`->`right arrow` in current group (bookmarks, apps, etc, and wox think user wants to bookmarks, then wox can add more items to search box)->`down arrow` (this will select second item.)

If this is very extreme, then put normal behaviour.

**Comment by qianlifeng** [comment]
Yes, That would be a little complicated for users.

**Comment by JohnTheGr8** [comment]
@qianlifeng nice work, I assume you will put bookmarks plugin in the Plugin tab and make it optional to disable it, right?

Thank you

Edit: Actually, the option is there, at first it was not there because I did not build the plugin projects. However, all `enable` options seem to reset every time the settings window is opened.

**Comment by qianlifeng** [comment]
@JohnTheGr8 The `enable` function didn't implemente yet.

**Comment by qianlifeng** [comment]
I'm closing this issues since we moved bookmark plugin into a third-party  plugin, and user can disable it or change the actionkeyword.
