### ISSUE TITLE
issue at windows startup

### ISSUE THREAD

**Issue by Reygos** [Wox-launcher/Wox#940]
i have this error each time windows start

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/23/2016 15:33:40
Exception:
Wox.Plugin.Program
System.NullReferenceException
Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in Wox.Plugin.Program.Main.DefaultProgramSources() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:riga 136
   in Wox.Plugin.Program.Main.IndexPrograms() in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:riga 102
   in Wox.Plugin.Program.Main.Init(PluginInitContext context) in C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:riga 94
   in Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:riga 27
   in Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:riga 96
   in System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   in System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   in System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that
