### ISSUE TITLE
我下载了代码，运行不了？

### ISSUE THREAD

**Issue by MianB1zhe** [Wox-launcher/Wox#943]
作者的软件很棒，我想下下来学习一下，可是运行不了？

环境 win10 vs2015 

有十多处这样的错误
严重性   代码  说明  项目  文件  行
错误      The type or namespace name 'RandomAccessStreamReference' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs    256

等等

是需要一些设置才能运行么？我只写过单个项目的小程序，不太清楚，谢谢

**Comment by bao-qian** [comment]
右键工程
restore nuget package
 或者
build

**Comment by bao-qian** [comment]
有问题再开

**Comment by MianB1zhe** [comment]
我还原了nuget包，生成还是会出现以下错误（不过错误数少了20个左右）：
环境win10 64位+vs2015    debug x86
再次还原，提示所有程序包都已安装，没有要还原的内容。

严重性   代码  说明  项目  文件  行 禁止显示状态
错误  CS0246  The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   40  活动
错误  CS0234  The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)    Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   10  活动
错误  CS0234  The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)    Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   11  活动
错误  CS0234  The type or namespace name 'Management' does not exist in the namespace 'Windows' (are you missing an assembly reference?)  Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   13  活动
错误  CS0234  The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   14  活动
错误  CS0246  The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   36  活动
错误  CS0246  The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   98  活动
错误  CS0246  The type or namespace name 'Package' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   155 活动
错误  CS0246  The type or namespace name 'RandomAccessStreamReference' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   208 活动
错误  CS0246  The type or namespace name 'RandomAccessStreamReference' could not be found (are you missing a using directive or an assembly reference?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   262 活动

**Comment by bao-qian** [comment]
直接点 buuld solution

**Comment by bao-qian** [comment]
debug x86 什么意思

**Comment by MianB1zhe** [comment]
就是启动那设置的debug X86

我是中文版，但应该就是  在解决方案上右键 生成解决方案 吧，我就是这么做的，错误就是这些

严重性   代码  说明  项目  文件  行 禁止显示状态
错误  CS0234  命名空间“Windows”中不存在类型或命名空间名“Storage”(是否缺少程序集引用?)    Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   14  活动
错误  CS0234  命名空间“Windows”中不存在类型或命名空间名“ApplicationModel”(是否缺少程序集引用?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   10  活动
错误  CS0234  命名空间“Windows”中不存在类型或命名空间名“ApplicationModel”(是否缺少程序集引用?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   11  活动
错误  CS0234  命名空间“Windows”中不存在类型或命名空间名“Management”(是否缺少程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   13  活动
错误  CS0246  未能找到类型或命名空间名“Package”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   36  活动
错误  CS0246  未能找到类型或命名空间名“Package”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   40  活动
错误  CS0246  未能找到类型或命名空间名“Package”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   98  活动
错误  CS0246  未能找到类型或命名空间名“Package”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   155 活动
错误  CS0246  未能找到类型或命名空间名“RandomAccessStreamReference”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   208 活动
错误  CS0246  未能找到类型或命名空间名“RandomAccessStreamReference”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   262 活动
错误  CS1061  “Package”未包含“Id”的定义，并且找不到可接受第一个“Package”类型参数的扩展方法“Id”(是否缺少 using 指令或程序集引用?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   43  活动
错误  CS1061  “Package”未包含“Id”的定义，并且找不到可接受第一个“Package”类型参数的扩展方法“Id”(是否缺少 using 指令或程序集引用?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   44  活动
错误  CS1061  “Package”未包含“Id”的定义，并且找不到可接受第一个“Package”类型参数的扩展方法“Id”(是否缺少 using 指令或程序集引用?)   Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   45  活动
错误  CS1061  “Package”未包含“InstalledLocation”的定义，并且找不到可接受第一个“Package”类型参数的扩展方法“InstalledLocation”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   46  活动
错误  CS0246  未能找到类型或命名空间名“AppListEntry”(是否缺少 using 指令或程序集引用?)    Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   100 活动
错误  CS0246  未能找到类型或命名空间名“Size”(是否缺少 using 指令或程序集引用?)    Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   117 活动
错误  CS0246  未能找到类型或命名空间名“PackageManager”(是否缺少 using 指令或程序集引用?)  Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   162 活动
错误  CS0246  未能找到类型或命名空间名“Package”(是否缺少 using 指令或程序集引用?) Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   176 活动
错误  CS0246  未能找到类型或命名空间名“IRandomAccessStreamWithContentType”(是否缺少 using 指令或程序集引用?)  Wox.Plugin.Program  C:\Users\lee\Downloads\Wox-\Wox-master\Plugins\Wox.Plugin.Program\Programs\UWP.cs   264 活动

**Comment by bao-qian** [comment]
重新安装一下 uwp 那个 nuget 包

**Comment by MianB1zhe** [comment]
好，谢谢，我试试~

**Comment by MianB1zhe** [comment]
是指uwpdesktop这个包么？以uwp开头的只有这个，我重装或者安装其它版本号的，错误都没变

**Comment by bao-qian** [comment]
恩

**Comment by bao-qian** [comment]
那你去下 1.3.813 的代码去看吧

**Comment by MianB1zhe** [comment]
行，我试试，非常感谢

**Comment by MianB1zhe** [comment]
谢谢，没问题了，可以正常运行~1.3.813

其实我也试过1.3.310，那个版本可以生成，但是无法运行。
