### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by SkiTiSu** [Wox-launcher/Wox#945]
刚才注销了一下系统再登录就报错

Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 08/25/2016 21:39:22
Exception:
mscorlib
System.Threading.Tasks.TaskCanceledException
已取消一个任务。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<GitHubUpdateManager>d__2b.MoveNext() 位置 c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.Factory.cs:行号 69
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__0.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-08-25.txt](https://github.com/Wox-launcher/Wox/files/437150/2016-08-25.txt)

**Comment by SkiTiSu** [comment]
刚才看到了#939，但是我以前从来没有遇到过，而且SS PAC模式始终打开的

**Comment by bao-qian** [comment]
只有一次吗？
还是现在每次都有？

**Comment by tianzhipengfei** [comment]
我也是有这样的问题，频率还没有到每次都出现，但大概有一半是这样的

**Comment by bao-qian** [comment]
@tianzhipengfei 
1. 你开了代理也是这么频繁吗？
2. 开了代理能从 github 下载 wox 吗？

**Comment by SkiTiSu** [comment]
@happlebao 这几天使用下来，只有一次（30日早）在开机自启动时（wox界面还未打开时）报错，错误类型相同，猜测可能是ss未启动完成wox先打开导致的？

**Comment by bao-qian** [comment]
@SkiTiSu 那就没问题了，这个异常下次版本会被自动忽略。。。 暂时忍忍。。。
