### ISSUE TITLE
System.NullReferenceException @ _historyItemsStorage

### ISSUE THREAD

**Issue by Wishmaster172** [Wox-launcher/Wox#947]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.10586.0
Date: 08/28/2016 00:10:46
Exception:
Wox
System.NullReferenceException
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:Zeile 159.
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2016-08-28.txt](https://github.com/Wox-launcher/Wox/files/440872/2016-08-28.txt)

**Comment by DudoMan** [comment]
I have the same problem and removal / installation does not helps

我有同样的问题，并拆卸/安装没有帮助

**Comment by DudoMan** [comment]
WOX Deleted folder in C: \ Users \ USERNAME \ Roaming. It seems to me that the problem in working plugin

**Comment by Wishmaster172** [comment]
Do you have an idea which plugin is responsible for the issue?

**Comment by bao-qian** [comment]
delete `%APPDATA%\Wox`, backup before you do that

**Comment by bao-qian** [comment]
close due to no response
