### ISSUE TITLE
Blur setting in windows 8

### ISSUE THREAD

**Issue by mehrad-m** [Wox-launcher/Wox#948]
Is there a way to use blur like this in windows 8 
also thanks for this great launcher

![](https://cloud.githubusercontent.com/assets/4784785/11069570/000e5952-87d7-11e5-9f3e-41d7a6dab22c.png)

![a](https://cloud.githubusercontent.com/assets/6609524/18044690/50487a44-6de4-11e6-8aeb-4d07d6349fd7.PNG)

**Comment by lances101** [comment]
**@mehrad-m**, I do not have access to a Windows 8 machine right now, but the feature was tested at the time of development. 

Could you share your theme's `.xaml` file? 

[Here is an example theme that I am currently using. ](https://github.com/Wox-launcher/Wox/files/442420/Themes.zip) Actually, it's the same one that you linked, but with a different background image. 

There does seem to be an issue with the accent setting for transparency, so once you select the theme with blur close the settings window and exit Wox. Upon launch the blur flag should be picked up.

**Comment by mehrad-m** [comment]
I tried your skin but had same issue , probably had issue on my system

![screenshot 218](https://cloud.githubusercontent.com/assets/6609524/18060299/bea957d0-6e32-11e6-94cd-de7cb86a2380.png)

[Skin_1.zip](https://github.com/Wox-launcher/Wox/files/442994/Skin_1.zip)

**Comment by Announcement** [comment]
is aero and everything enabled?
The default blur\* themes are blurring for me...

**Comment by mehrad-m** [comment]
@Announcement How can i enable aero?

**Comment by bao-qian** [comment]
@lances101 I remember you add a PR to check windows version before apply blur to wox?

**Comment by lances101** [comment]
@happlebao, yes I did. [Here it is](https://github.com/Wox-launcher/Wox/blob/master/Wox.Core/Resource/Theme.cs#L62). The main goal was to avoid crashing Wox on older systems.

@mehrad-m, please do the following:
- open Wox's settings and switch to a blurred theme. 
- restart Wox
- once Wox has restarted upload the latest log file from `%appdata%\Wox\Logs` (`%appdata%` points to your appdata/roaming folder)

I will take a look into it.

**Comment by mehrad-m** [comment]
@lances101 
[2016-09-16.txt](https://github.com/Wox-launcher/Wox/files/477290/2016-09-16.txt)

**Comment by bao-qian** [comment]
sorry but blur currently for windows10 only
