### ISSUE TITLE
关闭Wox后，使用WIN + R报错，并且系统会失去响应10s左右

### ISSUE THREAD

**Issue by 2ue** [Wox-launcher/Wox#950]
1. Wox 版本：1.3.813
2. 如何**重现** bug：关闭Wox后，使用WIN + R
3. Windows 版本：win7
4. Exception：关闭Wox后使用WIN + R报错，提示Wox已停止工作，操作系统失去响应10秒左右
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   问题签名:
   问题事件名称:   CLR20r3
   问题签名 01:  wox.exe
   问题签名 02:  1.3.183.0
   问题签名 03:  576c5cf2
   问题签名 04:  Wox.Plugin.Shell
   问题签名 05:  1.3.183.0
   问题签名 06:  576c5cec
   问题签名 07:  b
   问题签名 08:  30
   问题签名 09:  System.NullReferenceException
   OS 版本:    6.1.7601.2.1.0.256.1
   区域设置 ID:  2052
   其他信息 1:   3147
   其他信息 2:   3147326a15d0a83609e3d1827a27cf69
   其他信息 3:   f315
   其他信息 4:   f315223c71ea96006bfb28da89f6572e
6. 截图 （可选）：
   ![image](https://cloud.githubusercontent.com/assets/13751432/18122915/330d1d66-6f9e-11e6-8767-8d0046b3a21a.png)

**Comment by bao-qian** [comment]
1. 你拿任务管理器强制结束 wox 以后还有这种问题吗？
2. 你解决了 #895 后还是不行吗？
3. log 呢？？  `%APPDATA%\Wox\Logs\version\date.txt`

**Comment by bao-qian** [comment]
看起来解决了？

**Comment by 2ue** [comment]
恩，是的，这个问题解决了，谢谢了。
