### ISSUE TITLE
自定义主题后，输入命令，程序崩溃

### ISSUE THREAD

**Issue by 2ue** [Wox-launcher/Wox#952]
Wox 版本：1.3.813
如何重现 bug：官网上自定义主题，放到本地主题目录C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Themes，重启程序，输入命令
Windows 版本：win7
Exception：官网上自定义主题，放到本地主题目录C:\Users\Administrator\AppData\Local\Wox\app-1.3.183\Themes，重启程序，输入命令。程序崩溃，如果不删除主题目录下自定义主题，下次启动系统会卡顿，并且再次使用仍然会崩溃。

**Comment by bao-qian** [comment]
change 
`<Color>`
to 
`<SolidColorBrush>`
#880
