### ISSUE TITLE
Cursor position jumps to end of text when typing

### ISSUE THREAD

**Issue by dracan** [Wox-launcher/Wox#958]
- Wox version: 1.3.183
- Windows version: Windows 10
### Steps to reproduce
1. Alt-Space
2. Type multiple characters
3. Press the home key to move the cursor to the beginning
4. Type a single character, and notice that the cursor has immediately jumped to the end of the text

This makes it hard to move the cursor and insert/edit what you've typed into the  textbox.

**Comment by bao-qian** [comment]
fixed in new build: https://ci.appveyor.com/project/happlebao/wox/build/1.3.287/artifacts
#813

**Comment by liuyang1** [comment]
find same issue, Thanks for fix.
