### ISSUE TITLE
how to start a python timer thread in JsonRPCAction

### ISSUE THREAD

**Issue by JGMathematica** [Wox-launcher/Wox#961]
1. Wox version / commit number: 1.3.183

Are there any example about start a timer thread in the JsonRPCAction,  I wrote a bus tracking plugin using python 3.5, and would like to add timer to remind me for the coming bus.

what I did is as follow, but there is no response, can anyone tell me what is wrong here

results.append({"Title": "Bus Time", "SubTitle": stnow, "IcoPath": "Images/app.ico",
                            "JsonRPCAction":
                                {
                                    **"method": "alarm",
                                    "parameters": [query],**
                                    "dontHideAfterAction": True
                                }

 def timer(self,query):
         WoxAPI.show_msg(query, query, "Images/app.ico")

def alarm(self, query):
       Thread(target=timer,args=(int(query),))

**Comment by bao-qian** [comment]
from what I understand, the python process is existed after `query` method, try don't use a new thread.

**Comment by JGMathematica** [comment]
def alarm(self, query):
       # WoxAPI.hide_app()#doesnt work
        time.sleep(int(query))
        WoxAPI.show_msg("Time to go", "sub_title", "Images/app.ico")
        winsound.PlaySound("BUZZ.wav", winsound.SND_FILENAME)

Changed the code as above, it works, but Wox stopped responding until the code finished. It seems that the sleep() blocked the app.

I also want to try WoxAPI.shell_run(), but not sure how to use it, is there any way to run a python file using shell_run?

**Comment by bao-qian** [comment]
>  thread

that's it, you can't use async or background thread with current python api structure.

> shell_run

don't use that, just use subprocess.

**Comment by JGMathematica** [comment]
subprocess.Popen(["python","alram.py",query], shell=True)

This also blocks the app, it wired.

**Comment by bao-qian** [comment]
as I said, there is no non-blocking method for jsonrpc plugin in the current arch design, unless you maintain a separate process manually.
