### ISSUE TITLE
Wox Search Box will not open / vertical line probelm

### ISSUE THREAD

**Issue by Whoareyouagain** [Wox-launcher/Wox#962]
Sometime it will not bring up the Wox when I press the hotkey or I click the system tray to open it. It just stuck. Only way I can get it to open the search box is to restart the app itself. It occurring everyday. However, It only have issue on my laptop which I am using to typing it out. My desktop don't have any issue with it and showing the search box whenever I press the hotkey. I can use Wox normally, but when I put it to sleep or shutdown. Then I wake it up, the Wox just stop working. 

Wox Version: 1.3.183

Step to reproduce: I am not sure if anyone can reproduce it. It seem too random for it to happen. And it only happen specifically to my laptop, not my desktop. One thing that I notice it only happen after I put it to sleep or I boot it up. Just use the hotkey. 

Window version: Window 10 Home 1607

No Exception Errors

Logs: I have a few logs file. It occur everyday, so I will post all of the logs files that occur those issue. 

[2016-08-28.txt](https://github.com/Wox-launcher/Wox/files/453565/2016-08-28.txt)
[2016-08-29.txt](https://github.com/Wox-launcher/Wox/files/453566/2016-08-29.txt)
[2016-08-30.txt](https://github.com/Wox-launcher/Wox/files/453567/2016-08-30.txt)
[2016-08-31.txt](https://github.com/Wox-launcher/Wox/files/453569/2016-08-31.txt)
[2016-09-01.txt](https://github.com/Wox-launcher/Wox/files/453568/2016-09-01.txt)
[2016-09-02.txt](https://github.com/Wox-launcher/Wox/files/453571/2016-09-02.txt)
[2016-09-03.txt](https://github.com/Wox-launcher/Wox/files/453570/2016-09-03.txt)
[2016-08-24.txt](https://github.com/Wox-launcher/Wox/files/453574/2016-08-24.txt)
[2016-08-25.txt](https://github.com/Wox-launcher/Wox/files/453572/2016-08-25.txt)
[2016-08-26.txt](https://github.com/Wox-launcher/Wox/files/453573/2016-08-26.txt)
[2016-08-27.txt](https://github.com/Wox-launcher/Wox/files/453575/2016-08-27.txt)

**Comment by spencerhooks** [comment]
I have a similar problem. It only happens after coming out of sleep. I don't see the search box, but instead get what looks like a very tall cursor (a vertical line). See the attached picture. However, Wox still functions as I can type something and hit enter and still see the result.

It happens every day and makes Wox unusable. Was there any resolution?

![woxcapture](https://cloud.githubusercontent.com/assets/15079404/20839623/2942073a-b862-11e6-8af5-e27dc6a3f0d0.PNG)

**Comment by bao-qian** [comment]
@Whoareyouagain @spencerhooks 
please try new build 
https://ci.appveyor.com/project/happlebao/wox/build/1.3.352/artifacts

**Comment by bao-qian** [comment]
reopen if issue still exist

**Comment by spencerhooks** [comment]
The update didn't solve the problem for me. I still have this issue with version 1.3.357.

**Comment by bao-qian** [comment]
@spencerhooks could you find a way to reproduce it after you crate a new account?

**Comment by spencerhooks** [comment]
I setup a new account on my PC this morning and will report back on how things work there.

**Comment by spencerhooks** [comment]
After one sleep/wake cycle I saw the same behavior on my new account. Could it be something about my screen resolution (3440x1440) or perhaps the way that it is simulated by Windows during sleep/wake? I do notice that my windows get resized and moved by Windows when sleeping sometimes.

**Comment by bao-qian** [comment]
@spencerhooks your os version?

**Comment by bao-qian** [comment]
I'm also use 4k hidpi screen, that should be fine.

**Comment by spencerhooks** [comment]
OS Version is 1607

**Comment by bao-qian** [comment]
@spencerhooks your dpi settings is 200%?

**Comment by spencerhooks** [comment]
I'm at 100%

**Comment by MitjaBezensek** [comment]
I have the same problem. My DPI is 125% on the laptop, but I have it connected to external monitors with DPI 100% as well. I didn't yet catch which combination causes it, if I manage to find it out I'll let you know.

**Comment by ramalhovfc** [comment]
happens to me too at 100% (win10, all monitors at 100%dpi setting)

**Comment by icanc0** [comment]
same problem again in 2019
new build still got the bug

**Comment by HsunGong** [comment]
Seems you still love `Wox`. One last way, reinstall Windows and install and test wox first. NO ERROR!!!
Or use windows-sandbox to test it? I bet no error will happen......

**Comment by bao-qian** [comment]
could you try new build?
if problem still exist, please upload log file.

https://github.com/Wox-launcher/Wox/releases/tag/v1.3.1039

**Comment by icanc0** [comment]
its gone for me after a while, dont have a log since i switched to macos

**Comment by cyber2e** [comment]
Still having this issue with the latest release.  When my Windows laptop is connected to an external monitor. It always shows a vertical line after waking up from sleep when pressing "Alt+Space". Very frustrated... 

Can someone provide a solution for this? I really appreciate it.

**Comment by RikKoedoot** [comment]
this issue also occurs for me after hibernating windows 10

**Comment by kindadolf** [comment]
Just installed wox. and this problem does occur after I put windows 10 to sleep.

**Comment by proimage** [comment]
This issue happens for me as well. I get the feeling that it's some sort of desktop/window compositing/rendering subsystem that's crashed in the background, which both Wox AND Microsoft's PowerToys Run rely on, since whenever Wox stops working like this, I try PowerToys Run and it also has a rendering issue.

**Comment by dagfinnr** [comment]
Me too, on Windows 11. The best I've been able to do is a batch file that restarts Wox. Tried to make it run automatically after waking up from hibernation, but without success so far.

**Comment by dagfinnr** [comment]
Got my workaround to work.

restart-wox.bat:

```
taskkill /f /im Wox.exe
start /d C:\Users\dagfi\AppData\Local\Wox Wox.exe
```

Scheduled it using Task Scheduler as explained here:

https://answers.microsoft.com/en-us/windows/forum/all/best-way-to-run-a-task-after-hibernation/f87f2f5b-a870-4082-9898-9fb939b15846
