### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by Seacux** [Wox-launcher/Wox#966]
Wox.Plugin.Program
System.NullReferenceException
Referencia a objeto no establecida como instancia de un objeto.
   en Wox.Plugin.Program.Main.DefaultProgramSources() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 136
   en Wox.Plugin.Program.Main.IndexPrograms() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 102
   en Wox.Plugin.Program.Main.Init(PluginInitContext context) en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 94
   en Wox.Infrastructure.Stopwatch.Normal(String name, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 27
   en Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 96
   en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2016-09-06.txt](https://github.com/Wox-launcher/Wox/files/456974/2016-09-06.txt)

**Comment by bao-qian** [comment]
dup #783 
delete cache from %APPDATA%\Wox\Cache

**Comment by Seacux** [comment]
i already did, but doesn't work

**Comment by bao-qian** [comment]
try delete  `%APPDATA%\Wox` completely. backup before you do that

**Comment by Seacux** [comment]
ok, all this, right?
![image](https://cloud.githubusercontent.com/assets/22030736/18289811/98f9b182-7446-11e6-90c5-7b0d69cb6bdd.png)

**Comment by bao-qian** [comment]
yeah, make a copy of settings folder.

**Comment by Seacux** [comment]
Ok, just the .json files? or also the plugins folder?

**Comment by bao-qian** [comment]
just the .json files

**Comment by Seacux** [comment]
done, i already deleted all the folders, except fot the plugins folder, i can't delete that folder ¬¬
![image](https://cloud.githubusercontent.com/assets/22030736/18290090/b7ca0b10-7447-11e6-94fd-7ac1b11f30f6.png)

**Comment by bao-qian** [comment]
close wox process by using task manager

**Comment by Seacux** [comment]
it's working again, thanks man :)

**Comment by bao-qian** [comment]
good

**Comment by bao-qian** [comment]
you can say thanks by star (upper right) this project  :)
