### ISSUE TITLE
bookmarks crash with dash.doc by SQLite.Interop.dll

### ISSUE THREAD

**Issue by wuhuocao** [Wox-launcher/Wox#967]
Version=1
EventType=APPCRASH
EventTime=131176614214069188
ReportType=2
Consent=1
UploadTime=131176614214569217
ReportIdentifier=c2a1f265-7462-11e6-b230-005056c00008
IntegratorReportIdentifier=c2a1f264-7462-11e6-b230-005056c00008
Response.BucketId=256998188
Response.BucketTable=28
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=Wox.exe
Sig[1].Name=应用程序版本
Sig[1].Value=1.3.183.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=576c5cf2
Sig[3].Name=故障模块名称
Sig[3].Value=SQLite.Interop.dll
Sig[4].Name=故障模块版本
Sig[4].Value=1.0.102.0
Sig[5].Name=故障模块时间戳
Sig[5].Value=576ade08
Sig[6].Name=异常代码
Sig[6].Value=c0000005
Sig[7].Name=异常偏移
Sig[7].Value=000000000006e5e5
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=6.1.7601.2.1.0.256.1
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=a44c
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=a44c210c65c802d822a9605299a9de41
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=0a98
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=0a9814f14b389f986a7de0cbe6623f30
UI[2]=P:\Users\illegal\AppData\Local\Wox\app-1.3.183\Wox.exe
UI[3]=Wox 已停止工作
UI[4]=Windows 可以联机检查该问题的解决方案。
UI[5]=联机检查解决方案并关闭该程序
UI[6]=以后联机检查解决方案并关闭程序
UI[7]=关闭程序
LoadedModule[0]=P:\Users\illegal\AppData\Local\Wox\app-1.3.183\Wox.exe
LoadedModule[1]=P:\windows\SYSTEM32\ntdll.dll
LoadedModule[2]=P:\windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=P:\windows\system32\KERNEL32.dll
LoadedModule[4]=P:\windows\system32\KERNELBASE.dll
LoadedModule[5]=P:\windows\system32\ADVAPI32.dll
LoadedModule[6]=P:\windows\system32\msvcrt.dll
LoadedModule[7]=P:\windows\SYSTEM32\sechost.dll
LoadedModule[8]=P:\windows\system32\RPCRT4.dll
LoadedModule[9]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=P:\windows\system32\SHLWAPI.dll
LoadedModule[11]=P:\windows\system32\GDI32.dll
LoadedModule[12]=P:\windows\system32\USER32.dll
LoadedModule[13]=P:\windows\system32\LPK.dll
LoadedModule[14]=P:\windows\system32\USP10.dll
LoadedModule[15]=P:\windows\system32\IMM32.DLL
LoadedModule[16]=P:\windows\system32\MSCTF.dll
LoadedModule[17]=P:\Windows\system32\nvinitx.dll
LoadedModule[18]=P:\Program Files\NVIDIA Corporation\CoProcManager\detoured.dll
LoadedModule[19]=P:\Program Files\NVIDIA Corporation\CoProcManager\nvd3d9wrapx.dll
LoadedModule[20]=P:\windows\system32\SETUPAPI.dll
LoadedModule[21]=P:\windows\system32\CFGMGR32.dll
LoadedModule[22]=P:\windows\system32\OLEAUT32.dll
LoadedModule[23]=P:\windows\system32\ole32.dll
LoadedModule[24]=P:\windows\system32\DEVOBJ.dll
LoadedModule[25]=P:\Program Files\NVIDIA Corporation\CoProcManager\nvdxgiwrapx.dll
LoadedModule[26]=P:\windows\system32\VERSION.dll
LoadedModule[27]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[28]=P:\windows\system32\MSVCR120_CLR0400.dll
LoadedModule[29]=P:\windows\assembly\NativeImages_v4.0.30319_64\mscorlib\0b312f3f14daccc8bdc79fdcd75a45e2\mscorlib.ni.dll
LoadedModule[30]=P:\windows\system32\CRYPTBASE.dll
LoadedModule[31]=P:\windows\system32\uxtheme.dll
LoadedModule[32]=P:\windows\assembly\NativeImages_v4.0.30319_64\System\9a2715c05cb7bc5d06a7cc5801c474ca\System.ni.dll
LoadedModule[33]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Core\82c05157a6f4f6a2690055ba9d050986\System.Core.ni.dll
LoadedModule[34]=P:\windows\assembly\NativeImages_v4.0.30319_64\WindowsBase\a4ee246e71b68112d4cf7874d0989a31\WindowsBase.ni.dll
LoadedModule[35]=P:\windows\system32\CRYPTSP.dll
LoadedModule[36]=P:\windows\system32\rsaenh.dll
LoadedModule[37]=P:\windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\df7c237251519a09340d3300f71ac0ae\PresentationCore.ni.dll
LoadedModule[38]=P:\windows\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\6f7ffac002507c35fe004ddda8c5c735\PresentationFramework.ni.dll
LoadedModule[39]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Xaml\f8c4f70478d109c58ef68fd051344621\System.Xaml.ni.dll
LoadedModule[40]=P:\windows\system32\dwrite.dll
LoadedModule[41]=P:\windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[42]=P:\windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[43]=P:\windows\system32\api-ms-win-core-xstate-l2-1-0.dll
LoadedModule[44]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[45]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Runt73a1fc9d#\e63b164ccd55fbc25e71735d4850faea\System.Runtime.Remoting.ni.dll
LoadedModule[46]=P:\windows\system32\SspiCli.dll
LoadedModule[47]=P:\windows\system32\ws2_32.dll
LoadedModule[48]=P:\windows\system32\NSI.dll
LoadedModule[49]=P:\windows\system32\mswsock.dll
LoadedModule[50]=P:\windows\System32\wshtcpip.dll
LoadedModule[51]=P:\windows\System32\wship6.dll
LoadedModule[52]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\478aa7abe92f2fd1fe94658518f5f39a\System.Configuration.ni.dll
LoadedModule[53]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Xml\c971f0ba8d03fe3fb35b6f1de636a882\System.Xml.ni.dll
LoadedModule[54]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\nlssorting.dll
LoadedModule[55]=P:\windows\system32\RpcRtRemote.dll
LoadedModule[56]=P:\windows\system32\dwmapi.dll
LoadedModule[57]=P:\windows\system32\apphelp.dll
LoadedModule[58]=P:\windows\system32\SOGOUPY.IME
LoadedModule[59]=P:\windows\system32\MSIMG32.dll
LoadedModule[60]=P:\windows\system32\OLEACC.dll
LoadedModule[61]=P:\windows\system32\ntmarta.dll
LoadedModule[62]=P:\windows\system32\WLDAP32.dll
LoadedModule[63]=P:\windows\system32\SHELL32.dll
LoadedModule[64]=q:\soft\SogouInput\Components\PicFace\1.0.0.1403\PicFace64.dll
LoadedModule[65]=P:\windows\system32\profapi.dll
LoadedModule[66]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Numerics\e69882ec1b12350d7961be5fd846e77d\System.Numerics.ni.dll
LoadedModule[67]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Runteb92aa12#\8cf302fbd3a2c1b404957da062b373f1\System.Runtime.Serialization.ni.dll
LoadedModule[68]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Xml.Linq\469046c7a0fbbd5562cb273ce86a0824\System.Xml.Linq.ni.dll
LoadedModule[69]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Data\38fe60d801112399e578ce150d24f5a6\System.Data.ni.dll
LoadedModule[70]=P:\windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[71]=P:\windows\system32\CRYPT32.dll
LoadedModule[72]=P:\windows\system32\MSASN1.dll
LoadedModule[73]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\6597ef744b81c7e65312aece5f13299c\System.Drawing.ni.dll
LoadedModule[74]=P:\windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.23508_none_145555328b95eaaa\gdiplus.dll
LoadedModule[75]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\e2fca27894fc6372dae2d922d7e41c52\System.Windows.Forms.ni.dll
LoadedModule[76]=q:\soft\SogouInput\7.9.0.7625\Resource.dll
LoadedModule[77]=P:\windows\system32\PSAPI.DLL
LoadedModule[78]=P:\windows\system32\WtsApi32.dll
LoadedModule[79]=P:\windows\system32\WINSTA.dll
LoadedModule[80]=P:\windows\system32\d3d9.dll
LoadedModule[81]=P:\windows\system32\d3d8thk.dll
LoadedModule[82]=P:\windows\system32\nvumdshimx.dll
LoadedModule[83]=P:\windows\system32\igdumdim64.dll
LoadedModule[84]=P:\windows\system32\igdusc64.dll
LoadedModule[85]=P:\windows\system32\urlmon.dll
LoadedModule[86]=P:\windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
LoadedModule[87]=P:\windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[88]=P:\windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[89]=P:\windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[90]=P:\windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[91]=P:\windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[92]=P:\windows\system32\normaliz.DLL
LoadedModule[93]=P:\windows\system32\iertutil.dll
LoadedModule[94]=P:\windows\system32\WININET.dll
LoadedModule[95]=P:\windows\system32\USERENV.dll
LoadedModule[96]=P:\windows\system32\WindowsCodecs.dll
LoadedModule[97]=P:\windows\system32\mscms.dll
LoadedModule[98]=P:\windows\system32\WindowsCodecsExt.dll
LoadedModule[99]=P:\windows\system32\icm32.dll
LoadedModule[100]=P:\windows\assembly\NativeImages_v4.0.30319_64\Presentatio1c9175f8#\0c499c7e3370e6a4c79a07e5e12276b5\PresentationFramework.Aero.ni.dll
LoadedModule[101]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Transactions\7994ff089eb7da4c28fb6e37af1c908d\System.Transactions.ni.dll
LoadedModule[102]=P:\windows\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll
LoadedModule[103]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.ServiceModel\de20e37f35b2ffe706fee40a2633b10c\System.ServiceModel.ni.dll
LoadedModule[104]=P:\Users\illegal\AppData\Roaming\Wox\Plugins\Browser Bookmarks-128eb525-fb1c-4c5a-ab26-10a837ec559b\x64\SQLite.Interop.dll
LoadedModule[105]=P:\windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_fa3b1e3d17594757\comctl32.dll
LoadedModule[106]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Web\94e0d14d8d91eb7e9999125dd9ba645b\System.Web.ni.dll
LoadedModule[107]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\webengine4.dll
LoadedModule[108]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Ente96d83b35#\c4f0511ca21568ba792837e95dcaaed1\System.EnterpriseServices.ni.dll
LoadedModule[109]=P:\windows\assembly\NativeImages_v4.0.30319_64\System.Ente96d83b35#\c4f0511ca21568ba792837e95dcaaed1\System.EnterpriseServices.Wrapper.dll
LoadedModule[110]=P:\windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.Wrapper.dll
LoadedModule[111]=P:\Users\illegal\AppData\Roaming\Wox\Plugins\Dash.Doc-43c6147a-a161-4493-8357-661c9f594298\x64\SQLite.Interop.dll
LoadedModule[112]=P:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
LoadedModule[113]=P:\windows\system32\DbgHelp.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=256998188/nBucketTable=28/nResponse=1/n
FriendlyEventName=已停止工作
ConsentKey=APPCRASH
AppName=Wox
AppPath=P:\Users\illegal\AppData\Local\Wox\app-1.3.183\Wox.exe

**Comment by lances101** [comment]
@q647885974, do you still have this problem? 
What do you mean by "bookmarks crash"? If you still have this problem, then please reproduce the issue and upload the latest `.log` file (attach it, instead of pasting). The logs can be found at `%appdata%\Wox\Logs\`

**Comment by lances101** [comment]
Closed due to inactivity.
