### ISSUE TITLE
I still have this message

### ISSUE THREAD

**Issue by Seacux** [Wox-launcher/Wox#968]
Wox.Plugin.Program
System.NullReferenceException
Referencia a objeto no establecida como instancia de un objeto.
   en Wox.Plugin.Program.Main.DefaultProgramSources() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 136
   en Wox.Plugin.Program.Main.IndexPrograms() en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 102
   en Wox.Plugin.Program.Main.Init(PluginInitContext context) en C:\projects\wox\Plugins\Wox.Plugin.Program\Main.cs:línea 94
   en Wox.Infrastructure.Stopwatch.Normal(String name, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 27
   en Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) en C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:línea 96
   en System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   en System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   en System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

[2016-09-06.txt](https://github.com/Wox-launcher/Wox/files/457642/2016-09-06.txt)

**Comment by bao-qian** [comment]
don't create new issue.
