### ISSUE TITLE
Prevent existing same plugin install twice

### ISSUE THREAD

**Issue by lovebdsobuj** [Wox-launcher/Wox#972]
## A dialog should be promot.

![screenshot_2016 09 09_21h40m04s_001_install plugin](https://cloud.githubusercontent.com/assets/10352682/18393494/60b3417e-76d7-11e6-8f33-1f6b8031d66a.png)

**Comment by jhdxr** [comment]
however, the only way to upgrade an exist plugin is to reinstall the new version

**Comment by lovebdsobuj** [comment]
Main subject (goal) is **Need to prevent existing plugin install twice.**

Change dialog box button text `update` to `override`
