### ISSUE TITLE
Newtonsoft.Json Newtonsoft.Json.JsonReaderException Unterminated string. Expected delimiter: ". Path 'Items[37].ExecutedDateTime', line 153, position 49.

### ISSUE THREAD

**Issue by uniquexiaobai** [Wox-launcher/Wox#974]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\uniqu\AppData\Roaming\Wox\Logs\1.3.183\2016-09-10.txt
2. copy below exception message
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 09/10/2016 09:23:44
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unterminated string. Expected delimiter: ". Path 'Items[37].ExecutedDateTime', line 153, position 49.
   在 Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   在 Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   在 Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   在 Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 58
   在 Wox.Infrastructure.Storage.JsonStrorage`1.Load() 位置 C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:行号 40
   在 Wox.ViewModel.MainViewModel..ctor(Settings settings) 位置 C:\projects\wox\Wox\ViewModel\MainViewModel.cs:行号 62
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 49
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by roose** [comment]
@uniquexiaobai  Looks like config file is corrupted. Try to delete it.

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份
