### ISSUE TITLE
Mouse cursor changes current dropdown selection

### ISSUE THREAD

**Issue by dracan** [Wox-launcher/Wox#975]
If when the Wox display opens after hitting alt-space, the mouse pointer happens to be over one of the available dropdown items, it'll select it straight away. This means that if I hit alt-space followed by enter (presuming my previous selection), it could run something completely different depending on my mouse cursor position.

It would be good if a mouse selection required the mouse to move a few pixels first after the Wox window had opened. If you open the window without moving the mouse, the mouse position shouldn't be changing the selected item.

**Comment by snwFlake** [comment]
Was this suggestion was rejected/ignored/added?! Info please

**Comment by snwflake** [comment]
Since here doesn't seem to happen anything, I fixed it for myself.
Just remove [this line](https://github.com/Wox-launcher/Wox/blob/master/Wox/ResultListBox.xaml.cs#L25). Mouse input (click) is still enabled, but mouseHover doesn't select anything anymore.
