### ISSUE TITLE
pac not working

### ISSUE THREAD

**Issue by danalexa** [Wox-launcher/Wox#985]
Please add an option like "Use automatic configuration script" because that's how my proxy is configured at work (it's a proxy.pac file located on the network)so that means my Wox has no internet connection => i cannot install any additional plugins.

You can either add an option like modern browsers have: "Detect system proxy settings"

**Comment by bao-qian** [comment]
that is enabled by default.
try unclick "enable http proxy"
or
your proxy is not http proxy?

**Comment by danalexa** [comment]
![image](https://cloud.githubusercontent.com/assets/22215798/18548541/f782f36e-7b51-11e6-92bd-470273f5cc44.png)

this is how it looks like

**Comment by bao-qian** [comment]
try unclick "enable http proxy" in wox settings

**Comment by danalexa** [comment]
Tryied. This does not work
"wpm install Wox.Plugin.SimpleClock" just shows loading, nothing happens if i press <Enter>

**Comment by bao-qian** [comment]
not sure why pac is not working in your computer.
but if you manually copy your pac url, and open is in browser.
you can find the actual http proxy server.
and past it into wox settings

**Comment by danalexa** [comment]
Normally you are right, but this file is 695 lines long and is full of functions and if cases, i guess it allocates proxy servers dynamically

**Comment by danalexa** [comment]
I thought about what you said and studyied the file a bit more, it is allocating a different proxy for different categories of IP so i looked for my ip and found the correct proxy config and now it works, i can also install plugins.

This is really not intuitive, if you have the time available you should add an option to use system proxy settings

**Comment by bao-qian** [comment]
as I said, wox actually use system proxy settings, as it is working in my pc of my company.
but it is not working in your computer, and not sure why.

**Comment by danalexa** [comment]
Yes you are right, but browsers like firefox or vivaldi works using system wide proxy settings.... something is weird :P
