### ISSUE TITLE
cannot start

### ISSUE THREAD

**Issue by arthurdayne** [Wox-launcher/Wox#988]
[2016-09-18.txt](https://github.com/Wox-launcher/Wox/files/478494/2016-09-18.txt)
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 09/18/2016 10:41:18
Exception:
Wox
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.ViewModel.SettingWindowViewModel..ctor() 位置 C:\projects\wox\Wox\ViewModel\SettingWindowViewModel.cs:行号 28
   在 Wox.App.<OnStartup>b__8_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 44
   在 Wox.Infrastructure.Stopwatch.Normal(String name, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 28
   在 System.Windows.Application.<.ctor>b__1(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by roose** [comment]
@arthurdayne Try latest version https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份
