### ISSUE TITLE
win10专业版下经常显示不出来

### ISSUE THREAD

**Issue by Ramon403** [Wox-launcher/Wox#989]
Wox 版本 1.3.183
 Windows 版本：win10 专业版 x64 10.0.14393 系统是刚全新安装的，没装什么乱七八糟的软件

![image](https://cloud.githubusercontent.com/assets/2922635/18663472/3227e2ec-7f51-11e6-853f-0bff7c34382a.png)

问题就是打开Wox，不显示本身的黑色输入框，而是一个黑色线条竖在我的屏幕中央，关闭Wox，这个黑色线条就隐藏了

**Comment by drcege** [comment]
我也是这样，win10。。第一次装Wox，想试试是不是传说的的那么好用，结果根本不能用……

**Comment by satlxq** [comment]
是的，经常第一次正常，之后就就成为竖线了； 
我现在win+R 就经常能重现

**Comment by CepheiSigma** [comment]
同样的症状，只能还原1.20版了

**Comment by LittleHans8** [comment]
同样的问题，我退回到上个版本(v1.3.67)就正常了。

**Comment by bao-qian** [comment]
黑线是 bug ：#875

**Comment by bao-qian** [comment]
请订阅 #875 来接收更新
