### ISSUE TITLE
hide on startup

### ISSUE THREAD

**Issue by winteryoung** [Wox-launcher/Wox#991]
1.3.183, windows x64 专业版

设置中选中了启动时不显示主窗口，但是启动之后还是显示

**Comment by zayn-0101** [comment]
是的

**Comment by VickChen1992** [comment]
+1

**Comment by dasu88** [comment]
+1
还有「开机时启动」不勾选，还是会强迫于开机时载入

**Comment by lances101** [comment]
对不起，我的“翻译”中文。
[请尝试这个版本。](https://ci.appveyor.com/api/buildjobs/cmvaiden1r4um51m/artifacts/Releases%2FWox-1.3.295.exe)
您可能需要先解锁二进制文件（通过打开属性并单击解除阻止）。

**Comment by dasu88** [comment]
执行后出错：

[2016-11-09.txt](https://github.com/Wox-launcher/Wox/files/580276/2016-11-09.txt)

**Comment by ghost** [comment]
同样这个问题，希望尽快能改进

**Comment by bao-qian** [comment]
试一下 1.3.321
https://ci.appveyor.com/project/happlebao/wox/build/1.3.321/artifacts

**Comment by megaroeny** [comment]
Getting this too. Win 10 Anniversary Update 64-bit (1607). Really annoying ☹️ Just installed Wox too

**Comment by lances101** [comment]
@jaminroe what version of Wox are you using?

**Comment by megaroeny** [comment]
1.3.183. My solution for now was to enable _Hide Wox when focus is lost_. Which actually I prefer

**Comment by MovGP0** [comment]
there are two options in settings: 
- right-click on the Wox symbol right next to the clock/date. 
    - (you might need to unfold the list of symbols when hidden)
- click on `Settings`
- enable the following options:
    - `Hide Wox on system startup`
    - `Hide Wox when focus is lost`
- close the window

**Comment by megaroeny** [comment]
@MovGP0 yeah I did that. Doesn't always seem consistent still.

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributiors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributiors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!
