### ISSUE TITLE
System.NullReferenceException: 未将对象引用设置到对象的实例。    Source: Wox.Plugin.Program

### ISSUE THREAD

**Issue by dora8127** [Wox-launcher/Wox#993]
[2016-09-21.txt](https://github.com/Wox-launcher/Wox/files/484064/2016-09-21.txt)
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：
2. 如何**重现** bug：
3. Windows 版本：
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
6. 截图 （可选）：

**Comment by lances101** [comment]
dora8127, [please try this build](https://ci.appveyor.com/api/buildjobs/x48xfu93b8jq2fir/artifacts/Releases%2FWox-1.3.297.exe). 
You might need to unlock the binaries first (do that by opening properties and click unblock).

**Comment by bao-qian** [comment]
删除 `%APPDATA%\Wox`，删前记得备份
