### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by Seacux** [Wox-launcher/Wox#994]
Wox version: 1.3.183
OS Version: Microsoft Windows NT 10.0.14393.0
Date: 09/21/2016 16:25:41
Exception:
Newtonsoft.Json
Newtonsoft.Json.JsonReaderException
Unexpected character encountered while parsing value: . Path '', line 0, position 0.
   en Newtonsoft.Json.JsonTextReader.ParseValue()
   en Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   en Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   en Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   en Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   en Wox.Infrastructure.Storage.JsonStrorage`1.Deserialize(String searlized) en C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:línea 58
   en Wox.Infrastructure.Storage.JsonStrorage`1.Load() en C:\projects\wox\Wox.Infrastructure\Storage\JsonStorage.cs:línea 40
   en Wox.ViewModel.MainViewModel..ctor(Settings settings) en C:\projects\wox\Wox\ViewModel\MainViewModel.cs:línea 62
   en Wox.App.<OnStartup>b__8_0() en C:\projects\wox\Wox\App.xaml.cs:línea 49
   en Wox.Infrastructure.Stopwatch.Normal(String name, Action action) en C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:línea 28
   en System.Windows.Application.OnStartup(StartupEventArgs e)
[2016-09-21.txt](https://github.com/Wox-launcher/Wox/files/486071/2016-09-21.txt)

**Comment by lances101** [comment]
@Seacux Have you tried cleaning your `%appdata%\Wox\Settings\` folder? Looks like some config got corrupted.

**Comment by Seacux** [comment]
Thanks man, it worked

**Comment by lances101** [comment]
@happlebao solved.

**Comment by lances101** [comment]
@Seacux if you could close the issue that would be great. Thanks.
