### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wkissw** [Wox-launcher/Wox#995]
## Known problems for 1.3.813:
1. `System.NullReferenceException`: try reset wox by delete %APPDATA%\Wox, backup before you do that
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: 设置 http 代理
## English

Try search existing issues before you open new one
1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 
## 中文 / Chinese

提问之前搜索一下已经有的 issue
1. Wox 版本 / commit number：1.3.183
2. 如何**重现** bug：初次加载
3. Windows 版本：OS Version: Microsoft Windows NT 10.0.10586.0
4. Exception：
5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
   [2016-09-22.txt](https://github.com/Wox-launcher/Wox/files/486541/2016-09-22.txt)
6. 截图 （可选）：

**Comment by lances101** [comment]
@wkissw, could you provide any details? Thanks.

**Comment by bao-qian** [comment]
reopen if you have more info (log && exception)
