### ISSUE TITLE
插件必须设置触发关键字才可使用

### ISSUE THREAD

**Issue by RealityJOY** [Wox-launcher/Wox#997]
系统自带的插件，比如搜索程序的插件，直接输入程序名称没有响应，设置了触发关键字之后，倒是工作正常，可是看官网上说的不是不用设置关键字么？

系统为win10

**Comment by bao-qian** [comment]
哪个版啊。。。
是最新版吗 https://github.com/Wox-launcher/Wox/releases/tag/v1.3.183
